.TH "dcstgeo" 3 "Mon Apr 17 2023" "Version 1.10.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcstgeo \- Constants for orientation and stretching of map\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real(dp), dimension(3, 3) \fBrotm\fP"
.br
.RI "Orthogonal rotation matrix\&. "
.ti -1c
.RI "real(dp) \fBsc\fP"
.br
.RI "Schmidt stretching factor\&. "
.ti -1c
.RI "real(dp) \fBsci\fP"
.br
.RI "Schmidt inverse stretching factor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Constants for orientation and stretching of map\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real(dp), dimension(3,3) dcstgeo::rotm"

.PP
Orthogonal rotation matrix\&. 
.PP
Definition at line 20 of file pmat5\&.f90\&.
.SS "real(dp) dcstgeo::sc"

.PP
Schmidt stretching factor\&. 
.PP
Definition at line 21 of file pmat5\&.f90\&.
.SS "real(dp) dcstgeo::sci"

.PP
Schmidt inverse stretching factor\&. 
.PP
Definition at line 22 of file pmat5\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
