pkind
NAME
pkind - Standard integer, real, and complex single and double precision kinds.
SYNOPSIS
Variables
integer, parameter dp =selected_real_kind(15, 300)
Double precision real kind.
integer, parameter dpc =dp
Double precision real kind.
integer, parameter dpi =selected_int_kind(12)
Double precision integer kind.
integer, parameter sp =selected_real_kind(6, 30)
Single precision real kind.
integer, parameter spc =sp
Single precision real kind.
integer, parameter spi =selected_int_kind(6)
Single precision integer kind.
Detailed Description
Standard integer, real, and complex single and double precision kinds.
Author:
R. J. Purser
Variable Documentation
integer, parameter pkind::dp =selected_real_kind(15, 300)
Double precision real kind.
Definition at line 11 of file pkind.f90.
Referenced by pmat4::det_id(), and regional_grid().
integer, parameter pkind::dpc =dp
Double precision real kind.
Definition at line 13 of file pkind.f90.
Referenced by pmat4::ctoz(), and pmat4::ztocd().
integer, parameter pkind::dpi =selected_int_kind(12)
Double precision integer kind.
Definition at line 9 of file pkind.f90.
Referenced by pmat4::det_id().
integer, parameter pkind::sp =selected_real_kind(6, 30)
Single precision real kind.
Definition at line 10 of file pkind.f90.
integer, parameter pkind::spc =sp
Single precision real kind.
Definition at line 12 of file pkind.f90.
integer, parameter pkind::spi =selected_int_kind(6)
Single precision integer kind.
Definition at line 8 of file pkind.f90.
Author
Generated automatically by Doxygen for grid_tools from the source code.