.TH "pmat4::rowops" 3 "Mon Apr 17 2023" "Version 1.10.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::rowops
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBrowops\fP (m, n, ipiv, tt, v, vv)"
.br
.RI "Apply the row-operations, implied by ipiv and tt returned by rowgram, to the single column vector, v, to produce the transformed vector vv\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file pmat4\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat4::rowops::rowops (integer(spi), intent(in) m, integer(spi), intent(in) n, integer(spi), dimension(n), intent(in) ipiv, real(dp), dimension(m,n), intent(in) tt, real(dp), dimension(m), intent(in) v, real(dp), dimension(m), intent(out) vv)\fC [private]\fP"

.PP
Apply the row-operations, implied by ipiv and tt returned by rowgram, to the single column vector, v, to produce the transformed vector vv\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP number of rows of matrix tt, dimension of vectors V and VV 
.br
\fIn\fP number of columns of matrix tt 
.br
\fIipiv\fP integer vector encoding the pivoting sequence 
.br
\fItt\fP row-normalized matrix provided by subroutine rowgram 
.br
\fIv\fP input single column vector 
.br
\fIvv\fP output column vector vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1400 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
