.TH "pmat2::u1lbx" 3 "Mon Apr 17 2023" "Version 1.10.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::u1lbx
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBU1LBX\fP (mx, mah1, mah2, my, a, v)"
.br
.RI "Special back-substitution step of parallel linear inversion involving Banded matrix and X-right-Vectors\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file pmat2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat2::u1lbx::U1LBX (integer(spi), intent(in) mx, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) my, real(sp), dimension(mx,\-mah1:mah2), intent(in) a, real(sp), dimension(mx,my), intent(inout) v)\fC [private]\fP"

.PP
Special back-substitution step of parallel linear inversion involving Banded matrix and X-right-Vectors\&. 
.PP
\fBParameters:\fP
.RS 4
\fImx\fP the number of rows assumed for A and length of X-vectors stored in V 
.br
\fImah1\fP the left half-bandwidth of fortran array A 
.br
\fImah2\fP the right half-bandwidth of fortran array A 
.br
\fImy\fP number of parallel X-vectors inverted 
.br
\fIa\fP encodes the [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB 
.br
\fIv\fP input as right-hand-side vectors, output as solution vectors 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1996 
.RE
.PP

.PP
Definition at line 1186 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
