.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/psym2.f90" 3 "Mon Apr 17 2023" "Version 1.10.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/psym2.f90 \- Matrix routines\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBpsym2::chol2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::eigensym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::expsym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::expsym2d_e\fP"
.br
.ti -1c
.RI "interface \fBpsym2::expsym2d_t\fP"
.br
.ti -1c
.RI "interface \fBpsym2::id2222\fP"
.br
.ti -1c
.RI "interface \fBpsym2::invsym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::logsym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::sqrtsym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::sqrtsym2d_e\fP"
.br
.ti -1c
.RI "interface \fBpsym2::sqrtsym2d_t\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBpsym2\fP"
.br
.RI "A suite of routines to perform the eigen-decomposition of symmetric 2*2 matrices and to deliver basic analytic functions, and the derivatives of these functions, of such matrices\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBpsym2::chol2\fP (s, c, ff)"
.br
.RI "Return the cholesky lower triangular factor, C, of the 2X2 symmetric matrix, S, or raise the failure flag, FF, if S is not positive-definite\&. "
.ti -1c
.RI "subroutine, public \fBpsym2::eigensym2\fP (em, vv, oo)"
.br
.RI "Get the orthogonal eigenvectors, vv, and diagonal matrix of eigenvalues, oo, of the symmetric 2*2 matrix, em\&. "
.ti -1c
.RI "subroutine \fBpsym2::eigensym2d\fP (em, vv, oo, vvd, ood, ff)"
.br
.RI "For a symmetric 2*2 matrix, em, return the normalized eigenvectors, vv, and the diagonal matrix of eigenvalues, oo\&. "
.ti -1c
.RI "subroutine, public \fBpsym2::expsym2\fP (em, expem)"
.br
.RI "Get the exp of a symmetric 2*2 matrix\&. "
.ti -1c
.RI "subroutine \fBpsym2::expsym2d\fP (x, z, zd)"
.br
.RI "Get the exp of a symmetric 2*2 matrix, and its symmetric derivative\&. "
.ti -1c
.RI "subroutine \fBpsym2::expsym2d_e\fP (x, z, zd)"
.br
.RI "Get the exponential and its symmetric derivative for a symmetric 2*2 matrix using eigen-decomposition\&. "
.ti -1c
.RI "subroutine \fBpsym2::expsym2d_t\fP (x, z, zd)"
.br
.RI "Use the Taylor-series method (eigenvalues both fairly close to zero)\&. "
.ti -1c
.RI "subroutine, public \fBpsym2::id2222\fP (em)"
.br
.RI "General routine for a symmetrized 4th-rank tensor that acts as an effective identity for operations on symmetric matrices\&. "
.ti -1c
.RI "subroutine, public \fBpsym2::invsym2\fP (em, z)"
.br
.RI "Get the inverse of a 2*2 matrix (need not be symmetric in this case)\&. "
.ti -1c
.RI "subroutine \fBpsym2::invsym2d\fP (em, z, zd)"
.br
.RI "Get the inverse, z,of a 2*2 symmetric matrix, em, and its derivative, zd, with respect to symmetric variations of its components\&. "
.ti -1c
.RI "subroutine, public \fBpsym2::logsym2\fP (em, logem)"
.br
.RI "Get the log of a symmetric positive-definite 2*2 matrix\&. "
.ti -1c
.RI "subroutine \fBpsym2::logsym2d\fP (x, z, zd)"
.br
.RI "General routine to evaluate the logarithm, z=log(x), and the symmetric derivative, zd = dz/dx, where x is a symmetric 2*2 positive-definite matrix\&. "
.ti -1c
.RI "subroutine, public \fBpsym2::sqrtsym2\fP (em, z)"
.br
.RI "Get the sqrt of a symmetric positive-definite 2*2 matrix\&. "
.ti -1c
.RI "subroutine \fBpsym2::sqrtsym2d\fP (x, z, zd)"
.br
.RI "General routine to evaluate z=sqrt(x), and the symmetric derivative, zd = dz/dx, where x is a symmetric 2*2 positive-definite matrix\&. "
.ti -1c
.RI "subroutine \fBpsym2::sqrtsym2d_e\fP (x, z, zd)"
.br
.RI "Eigen-method\&. "
.ti -1c
.RI "subroutine \fBpsym2::sqrtsym2d_t\fP (x, z, zd)"
.br
.RI "Use the Taylor-series method (eigenvalues both fairly close to unity)\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(dp), dimension(2, 2, 2, 2) \fBpsym2::id\fP"
.br
.RI "ID\&. "
.in -1c
.SH "Detailed Description"
.PP 
Matrix routines\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP
\fBDate:\fP
.RS 4
September 2018 
.RE
.PP

.PP
Definition in file \fBpsym2\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
