.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/weight_gen.fd Directory Reference" 3 "Wed Mar 13 2024" "Version 1.13.0" "weight_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/weight_gen.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBscrip\&.F90\fP"
.br
.RI "\fICreate ESMF 'scrip' files for a gaussian grid\&. \fP"
.in -1c
