.TH "/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/global_cycle.fd Directory Reference" 3 "Mon Jun 21 2021" "Version 1.5.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/global_cycle.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcycle\&.f90\fP"
.br
.RI "\fIUpdate surface and NSST fields\&. \fP"
.ti -1c
.RI "file \fBmachine\&.f90\fP"
.br
.RI "\fIHolds machine dependent constants for global_cycle\&. \fP"
.ti -1c
.RI "file \fBnum_parthds\&.f90\fP"
.br
.RI "\fIReturn number of threads\&. \fP"
.ti -1c
.RI "file \fBread_write_data\&.f90\fP"
.br
.RI "\fIContains utility routines that read and write data\&. \fP"
.ti -1c
.RI "file \fBsfcsub\&.F\fP"
.br
.RI "\fIThis is a limited point version of surface program\&. \fP"
.in -1c
