.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd Directory Reference" 3 "Wed Mar 13 2024" "Version 1.13.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcycle\&.f90\fP"
.br
.RI "\fIUpdate surface and NSST fields\&. \fP"
.ti -1c
.RI "file \fBland_increments\&.f90\fP"
.br
.RI "\fIRoutines for applyng land DA increments\&. \fP"
.ti -1c
.RI "file \fBmachine\&.f90\fP"
.br
.RI "\fIHolds machine dependent constants for global_cycle\&. \fP"
.ti -1c
.RI "file \fBnum_parthds\&.f90\fP"
.br
.RI "\fIReturn number of threads\&. \fP"
.ti -1c
.RI "file \fBread_write_data\&.f90\fP"
.br
.RI "\fIContains utility routines that read and write data\&. \fP"
.ti -1c
.RI "file \fButils\&.F90\fP"
.br
.RI "\fIUtility routines\&. \fP"
.in -1c
