/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/UFS_UTILS/sorc/global_cycle.fd/num_parthds.f90
NAME
/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/UFS_UTILS/sorc/global_cycle.fd/num_parthds.f90 -
Return number of threads.
SYNOPSIS
Functions/Subroutines
integer function num_parthds ()
Return the number of omp threads.
Detailed Description
Return number of threads.
Author:
Mark Iredell NCEP/EMC
Definition in file num_parthds.f90.
Function/Subroutine Documentation
integer function num_parthds ()
Return the number of omp threads.
Returns:
num_parthds The number of threads.
Author:
Mark Iredell NCEP/EMC
Definition at line 9 of file num_parthds.f90.
Referenced by ga2la(), la2ga(), merge(), qcmxmn(), and sfc_drv().
Author
Generated automatically by Doxygen for global_cycle from the source code.