read_write_data
NAME
read_write_data - This module contains routines that read and write data.
SYNOPSIS
Data Types
type nsst_data
Functions/Subroutines
subroutine, public get_dim_nc (filename, nlat, nlon)
Get the i/j dimensions of the data from a NetCDF file.
subroutine, public get_tf_clm_dim (file_sst, mlat_sst, mlon_sst)
Get the i/j dimensions of RTG SST climatology file.
subroutine nc_check (status)
Check the NetCDF status code.
subroutine netcdf_err (ERR, STRING)
If a NetCDF call returns an error, print out a user-supplied message and the NetCDF library message.
subroutine, public read_data (LSOIL, LENSFC, DO_NSST, DO_SNO_INC_JEDI, DO_SOI_INC_JEDI, INC_FILE, IS_NOAHMP, TSFFCS, SMCFCS, SWEFCS, STCFCS, TG3FCS, ZORFCS, CVFCS, CVBFCS, CVTFCS, ALBFCS, VEGFCS, SLIFCS, CNPFCS, F10M, VETFCS, SOTFCS, ALFFCS, USTAR, FMM, FHH, SIHFCS, SICFCS, SITFCS, TPRCP, SRFLAG, SNDFCS, VMNFCS, VMXFCS, SLCFCS, STCINC, SLCINC, SLPFCS, ABSFCS, T2M, Q2M, SLMASK, ZSOIL, NSST)
Read the first guess surface records and nsst records (if selected) for a single cubed-sphere tile.
subroutine, public read_gsi_data (GSI_FILE, FILE_TYPE, LSOIL)
Read increment file from the GSI containing either the foundation temperature increments and mask, or the soil increments.
subroutine, public read_lat_lon_orog (RLA, RLO, OROG, OROG_UF, TILE_NUM, IDIM, JDIM, IJDIM, LANDFRAC)
Read latitude and longitude for the cubed-sphere tile from the 'grid' file.
subroutine, public read_salclm_gfs_nc (filename, sal, xlats, xlons, nlat, nlon, itime)
Read the woa05 salinity monthly climatology file.
subroutine, public read_tf_clim_grb (file_sst, sst, rlats_sst, rlons_sst, mlat_sst, mlon_sst, mon)
Read a GRIB1 sst climatological analysis file.
subroutine remove_checksum (ncid, id_var)
Remove the checksum attribute from a netcdf record.
subroutine, public write_data (lensfc, idim, jdim, lsoil, do_nsst, inc_file, nsst, slifcs, tsffcs, vegfcs, swefcs, tg3fcs, zorfcs, albfcs, alffcs, cnpfcs, f10m, t2m, q2m, vetfcs, sotfcs, ustar, fmm, fhh, sicfcs, sihfcs, sitfcs, tprcp, srflag, swdfcs, vmnfcs, vmxfcs, slpfcs, absfcs, slcfcs, smcfcs, stcfcs, stcinc, slcinc)
Update surface records - and nsst records if selected - on a single cubed-sphere tile to a pre-existing model restart file (in netcdf).
Variables
real, dimension(:,:), allocatable, public dtref_gaus
GSI foundation temperature increment on the gaussian grid.
integer, public idim_gaus
'i' dimension of GSI gaussian grid.
integer, public jdim_gaus
'j' dimension of GSI gaussian grid.
real, dimension(:,:,:), allocatable, public slc_inc_gaus
GSI soil moisture increments on the gaussian grid.
integer, dimension(:,:), allocatable, public slmsk_gaus
GSI land mask on the gaussian grid.
integer, dimension(:,:), allocatable, public soilsnow_gaus
GSI soil / snow mask for land on the gaussian grid.
real, dimension(:,:,:), allocatable, public stc_inc_gaus
GSI soil temperature increments on the gaussian grid.
Detailed Description
This module contains routines that read and write data.
Author:
Xu Li, Hang Lei, George Gayno NOAA/EMC
Data Type Documentation
type read_write_data::nsst_data
Definition at line 16 of file read_write_data.f90.
Data Fields:
real, dimension(:), allocatable c_0
real, dimension(:), allocatable c_d
real, dimension(:), allocatable d_conv
real, dimension(:), allocatable dt_cool
real, dimension(:), allocatable ifd
real, dimension(:), allocatable qrain
real, dimension(:), allocatable tfinc
real, dimension(:), allocatable tref
real, dimension(:), allocatable w_0
real, dimension(:), allocatable w_d
real, dimension(:), allocatable xs
real, dimension(:), allocatable xt
real, dimension(:), allocatable xtts
real, dimension(:), allocatable xu
real, dimension(:), allocatable xv
real, dimension(:), allocatable xz
real, dimension(:), allocatable xzts
real, dimension(:), allocatable z_c
real, dimension(:), allocatable zm
Function/Subroutine Documentation
subroutine, public read_write_data::get_dim_nc (character (len=*), intent(in) filename, integer, intent(out) nlat, integer, intent(out) nlon)
Get the i/j dimensions of the data from a NetCDF file.
Parameters:
filename Name of the file to be read.
nlat 'j' dimension of the data in the file.
nlon 'i' dimension of the data in the file.
Author:
Xu Li NOAA/EMC
Definition at line 1922 of file read_write_data.f90.
References nc_check().
Referenced by get_sal_clm().
subroutine, public read_write_data::get_tf_clm_dim (character(*), intent(in) file_sst, integer, intent(out) mlat_sst, integer, intent(out) mlon_sst)
Get the i/j dimensions of RTG SST climatology file. The file is GRIB1.
Parameters:
file_sst File name of the sst file.
mlat_sst The 'j' dimension of the data.
mlon_sst The 'i' dimension of the data.
Author:
Xu Li NOAA/EMC
Date:
2019-03-13
Definition at line 1793 of file read_write_data.f90.
Referenced by get_tf_clm().
subroutine read_write_data::nc_check (integer, intent(in) status)
Check the NetCDF status code. If there is an error, print the library error message and stop processing.
Parameters:
status NetCDF status code.
Author:
Xu Li NOAA/EMC
Definition at line 1959 of file read_write_data.f90.
Referenced by get_dim_nc(), and read_salclm_gfs_nc().
subroutine read_write_data::netcdf_err (integer, intent(in) ERR, character(len=*), intent(in) STRING)
If a NetCDF call returns an error, print out a user-supplied message and the NetCDF library message. Then stop processing.
Parameters:
ERR NetCDF error code.
STRING User-defined error message.
Author:
George Gayno NOAA/EMC
Definition at line 876 of file read_write_data.f90.
Referenced by read_data(), read_gsi_data(), read_lat_lon_orog(), remove_checksum(), and write_data().
subroutine, public read_write_data::read_data (integer, intent(in) LSOIL, integer, intent(in) LENSFC, logical, intent(in) DO_NSST, logical, intent(in) DO_SNO_INC_JEDI, logical, intent(in) DO_SOI_INC_JEDI, logical, intent(in) INC_FILE, logical, intent(out), optional IS_NOAHMP, real, dimension(lensfc), intent(out), optional TSFFCS, real, dimension(lensfc,lsoil), intent(out), optional SMCFCS, real, dimension(lensfc), intent(out), optional SWEFCS, real, dimension(lensfc,lsoil), intent(out), optional STCFCS, real, dimension(lensfc), intent(out), optional TG3FCS, real, dimension(lensfc), intent(out), optional ZORFCS, real, dimension(lensfc), intent(out), optional CVFCS, real, dimension(lensfc), intent(out), optional CVBFCS, real, dimension(lensfc), intent(out), optional CVTFCS, real, dimension(lensfc,4), intent(out), optional ALBFCS, real, dimension(lensfc), intent(out), optional VEGFCS, real, dimension(lensfc), intent(out), optional SLIFCS, real, dimension(lensfc), intent(out), optional CNPFCS, real, dimension(lensfc), intent(out), optional F10M, real, dimension(lensfc), intent(out), optional VETFCS, real, dimension(lensfc), intent(out), optional SOTFCS, real, dimension(lensfc,2), intent(out), optional ALFFCS, real, dimension(lensfc), intent(out), optional USTAR, real, dimension(lensfc), intent(out), optional FMM, real, dimension(lensfc), intent(out), optional FHH, real, dimension(lensfc), intent(out), optional SIHFCS, real, dimension(lensfc), intent(out), optional SICFCS, real, dimension(lensfc), intent(out), optional SITFCS, real, dimension(lensfc), intent(out), optional TPRCP, real, dimension(lensfc), intent(out), optional SRFLAG, real, dimension(lensfc), intent(out), optional SNDFCS, real, dimension(lensfc), intent(out), optional VMNFCS, real, dimension(lensfc), intent(out), optional VMXFCS, real, dimension(lensfc,lsoil), intent(out), optional SLCFCS, real, dimension(lensfc,lsoil), intent(out), optional STCINC, real, dimension(lensfc,lsoil), intent(out), optional SLCINC, real, dimension(lensfc), intent(out), optional SLPFCS, real, dimension(lensfc), intent(out), optional ABSFCS, real, dimension(lensfc), intent(out), optional T2M, real, dimension(lensfc), intent(out), optional Q2M, real, dimension(lensfc), intent(out), optional SLMASK, real(kind=4), dimension(lsoil), intent(out), optional ZSOIL, type(nsst_data), optional NSST)
Read the first guess surface records and nsst records (if selected) for a single cubed-sphere tile.
Parameters:
LSOIL Number of soil layers.
LENSFC Total number of points on a tile.
DO_NSST When true, nsst fields are read.
DO_SNO_INC_JEDI When true, read in snow increment file
DO_SOI_INC_JEDI When true, read in soil increment file
INC_FILE When true, read from an increment file. False reads from a restart file. increments are on the cubed-sphere tiles
IS_NOAHMP When true, process for the Noah-MP LSM.
TSFFCS Skin Temperature.
SMCFCS Total volumetric soil moisture.
SWEFCS Snow water equivalent.
STCFCS Soil temperature.
TG3FCS Soil substrate temperature.
ZORFCS Roughness length.
CVFCS Cloud cover.
CVBFCS Cloud base.
CVTFCS Cloud top.
ALBFCS Snow-free albedo.
SLIFCS Land-sea mask including ice flag.
VEGFCS Vegetation greenness.
CNPFCS Plant canopy moisture content.
F10M log((z0+10)/z0). See model routine sfc_diff.f for details.
VETFCS Vegetation type.
SOTFCS Soil type.
ALFFCS Fractional coverage for strong/weak zenith angle dependent albedo.
USTAR Friction velocity.
FMM log((z0+z1)/z0). See model routine sfc_diff.f for details.
FHH log((ztmax+z1)/ztmax). See model routine sfc_diff.f for details.
SIHFCS Sea ice depth.
SICFCS Sea ice concentration.
SITFCS Sea ice temperature.
TPRCP Precipitation.
SRFLAG Snow/rain flag.
SNDFCS Snow depth.
VMNFCS Minimum vegetation greenness.
VMXFCS Maximum vegetation greenness.
SLCFCS Liquid portion of volumetric soil moisture.
SLPFCS Slope type.
ABSFCS Maximum snow albedo.
T2M Two-meter air temperature.
Q2M Two-meter specific humidity.
SLMASK Land-sea mask without ice flag.
ZSOIL Soil layer thickness.
NSST Data structure containing nsst fields.
SLCINC Liquid soil moisture increments on the cubed-sphere tiles
STCINC Soil temperature increments on the cubed-sphere tiles
Author:
George Gayno NOAA/EMC
Yuan Xue: add capability to read soil related increments on the cubed-sphere tiles directly
Definition at line 1101 of file read_write_data.f90.
References netcdf_err().
Referenced by sfcdrv().
subroutine, public read_write_data::read_gsi_data (character(len=*), intent(in) GSI_FILE, character(len=3), intent(in) FILE_TYPE, integer, intent(in), optional LSOIL)
Read increment file from the GSI containing either the foundation temperature increments and mask, or the soil increments. The data is in NetCDF and on a gaussian grid. The grid contains two extra rows for each pole. The interpolation from gaussian to native grid assumes no pole points, so these are removed.
Parameters:
GSI_FILE Path/name of the GSI file to be read.
FILE_TYPE file-type to be read in, 'NST' or 'LND'.
LSOIL Number of model soil levels.
Author:
George Gayno NOAA/EMC
Definition at line 909 of file read_write_data.f90.
References dtref_gaus, idim_gaus, jdim_gaus, netcdf_err(), slc_inc_gaus, slmsk_gaus, soilsnow_gaus, and stc_inc_gaus.
Referenced by sfcdrv().
subroutine, public read_write_data::read_lat_lon_orog (real, dimension(ijdim), intent(out) RLA, real, dimension(ijdim), intent(out) RLO, real, dimension(ijdim), intent(out) OROG, real, dimension(ijdim), intent(out) OROG_UF, character(len=5), intent(out) TILE_NUM, integer, intent(in) IDIM, integer, intent(in) JDIM, integer, intent(in) IJDIM, real(kind=kind_io8), dimension(ijdim), intent(out), optional LANDFRAC)
Read latitude and longitude for the cubed-sphere tile from the 'grid' file. Read the filtered and unfiltered orography and optionally the land fraction from the 'orography' file.
Parameters:
IDIM 'i' dimension of cubed-sphere tile.
JDIM 'j' dimension of cubed-sphere tile.
IJDIM Total number of points on the cubed-sphere tile.
RLA Latitude on the cubed-sphere tile.
RLO Longitude on the cubed-sphere tile.
OROG Filtered orography.
OROG_UF Unfiltered orography.
TILE_NUM Cubed-sphere tile number
LANDFRAC Land fraction.
Author:
George Gayno NOAA/EMC
Definition at line 733 of file read_write_data.f90.
References netcdf_err().
Referenced by sfcdrv().
subroutine, public read_write_data::read_salclm_gfs_nc (character (len=*), intent(in) filename, real, dimension(nlon,nlat), intent(out) sal, real, dimension(nlat), intent(out) xlats, real, dimension(nlon), intent(out) xlons, integer, intent(in) nlat, integer, intent(in) nlon, integer, intent(in) itime)
Read the woa05 salinity monthly climatology file. The file is NetCDF.
Parameters:
filename The name of the climatology file.
nlat The 'j' dimension of the data in the file.
nlon The 'i' dimension of the data in the file.
itime The monthly record to read.
xlats The latitude of the data points.
xlons The longitude of the data points.
sal The salinity.
Author:
Xu Li NOAA/EMC
Definition at line 1851 of file read_write_data.f90.
References nc_check().
Referenced by get_sal_clm_ta().
subroutine, public read_write_data::read_tf_clim_grb (character(*), intent(in) file_sst, real, dimension(mlon_sst,mlat_sst), intent(out) sst, real, dimension(mlat_sst), intent(out) rlats_sst, real, dimension(mlon_sst), intent(out) rlons_sst, integer, intent(in) mlat_sst, integer, intent(in) mlon_sst, integer, intent(in) mon)
Read a GRIB1 sst climatological analysis file. Read the sst analysis and save it as an expanded and transposed array.
Note:
The data is stored from north to south, but this routine flips the poles.
Parameters:
file_sst File name of the sst file.
mlat_sst 'j' dimension of the sst data.
mlon_sst 'i' dimension of the sst data.
mon The month of the year.
sst The sst analysis data.
rlats_sst The latitudes of the sst data points.
rlons_sst The longitudes of the sst data points.
Author:
Xu Li NOAA/EMC
Date:
2019-03-13
Definition at line 1651 of file read_write_data.f90.
Referenced by get_tf_clm_ta().
subroutine read_write_data::remove_checksum (integer, intent(in) ncid, integer, intent(in) id_var)
Remove the checksum attribute from a netcdf record.
Parameters:
ncid netcdf file id
id_var netcdf variable id.
Author:
George Gayno NCEP/EMC
Definition at line 693 of file read_write_data.f90.
References netcdf_err().
Referenced by write_data().
subroutine, public read_write_data::write_data (integer, intent(in) lensfc, integer, intent(in) idim, integer, intent(in) jdim, integer, intent(in) lsoil, logical, intent(in) do_nsst, logical, intent(in) inc_file, type(nsst_data), intent(in) nsst, real, dimension(lensfc), intent(in), optional slifcs, real, dimension(lensfc), intent(in), optional tsffcs, real, dimension(lensfc), intent(in), optional vegfcs, real, dimension(lensfc), intent(in), optional swefcs, real, dimension(lensfc), intent(in), optional tg3fcs, real, dimension(lensfc), intent(in), optional zorfcs, real, dimension(lensfc,4), intent(in), optional albfcs, real, dimension(lensfc,2), intent(in), optional alffcs, real, dimension(lensfc), intent(in), optional cnpfcs, real, dimension(lensfc), intent(in), optional f10m, real, dimension(lensfc), intent(in), optional t2m, real, dimension(lensfc), intent(in), optional q2m, real, dimension(lensfc), intent(in), optional vetfcs, real, dimension(lensfc), intent(in), optional sotfcs, real, dimension(lensfc), intent(in), optional ustar, real, dimension(lensfc), intent(in), optional fmm, real, dimension(lensfc), intent(in), optional fhh, real, dimension(lensfc), intent(in), optional sicfcs, real, dimension(lensfc), intent(in), optional sihfcs, real, dimension(lensfc), intent(in), optional sitfcs, real, dimension(lensfc), intent(in), optional tprcp, real, dimension(lensfc), intent(in), optional srflag, real, dimension(lensfc), intent(in), optional swdfcs, real, dimension(lensfc), intent(in), optional vmnfcs, real, dimension(lensfc), intent(in), optional vmxfcs, real, dimension(lensfc), intent(in), optional slpfcs, real, dimension(lensfc), intent(in), optional absfcs, real, dimension(lensfc,lsoil), intent(in), optional slcfcs, real, dimension(lensfc,lsoil), intent(in), optional smcfcs, real, dimension(lensfc,lsoil), intent(in), optional stcfcs, real, dimension(lensfc,lsoil), intent(in), optional stcinc, real, dimension(lensfc,lsoil), intent(in), optional slcinc)
Update surface records - and nsst records if selected - on a single cubed-sphere tile to a pre-existing model restart file (in netcdf).
Note:
The model restart files contain an additional snow field - snow cover (snocvr). That field is required for bit identical reproducability. If that record does not exist, the model will compute it as an initialization step. Because this program does not contain the snow cover algorithm, it will let the model compute it.
Parameters:
idim 'i' dimension of a tile.
jdim 'j' dimension of a tile.
lensfc Total number of points on a tile.
lsoil Number of soil layers.
do_nsst When true, nsst fields were processed.
inc_file When true, write out increments to files
nsst Data structure containing nsst fields.
slifcs Land-sea mask.
tsffcs Skin temperature.
vegfcs Vegetation greenness.
swefcs Snow water equivalent
tg3fcs Soil substrate temperature.
zorfcs Roughness length.
albfcs Snow-free albedo.
alffcs Fractional coverage for strong/weak zenith angle dependent albedo.
cnpfcs Plant canopy moisture content.
f10m log((z0+10)/z0). See model routine sfc_diff.f for details.
t2m Two-meter air temperature.
q2m Two-meter specific humidity.
vetfcs Vegetation type.
sotfcs Soil type.
ustar Friction velocity.
fmm log((z0+z1)/z0). See model routine sfc_diff.f for details.
fhh log(ztmax+z1)/ztmax). See model routine sfc_diff.f for details.
sicfcs Sea ice concentraton.
sihfcs Sea ice depth.
sitfcs Sea ice temperature.
tprcp Precipitation.
srflag Snow/rain flag.
swdfcs Physical snow depth.
vmnfcs Minimum vegetation greenness.
vmxfcs Maximum vegetation greenness.
slpfcs Slope type.
absfcs Maximum snow albedo.
slcfcs Liquid portion of volumetric soil moisture.
smcfcs Total volumetric soil moisture.
stcfcs Soil temperature.
stcinc Soil temperature increments on the cubed-sphere tiles
slcinc Liquid soil moisture increments on the cubed-sphere tiles
Author:
George Gayno NOAA/EMC
Definition at line 132 of file read_write_data.f90.
References netcdf_err(), and remove_checksum().
Referenced by sfcdrv().
Variable Documentation
real, dimension(:,:), allocatable, public read_write_data::dtref_gaus
GSI foundation temperature increment on the gaussian grid.
Definition at line 49 of file read_write_data.f90.
Referenced by adjust_nsst(), and read_gsi_data().
integer, public read_write_data::idim_gaus
'i' dimension of GSI gaussian grid.
Definition at line 38 of file read_write_data.f90.
Referenced by adjust_nsst(), land_increments::gaussian_to_fv3_interp(), and read_gsi_data().
integer, public read_write_data::jdim_gaus
'j' dimension of GSI gaussian grid.
Definition at line 40 of file read_write_data.f90.
Referenced by adjust_nsst(), land_increments::gaussian_to_fv3_interp(), and read_gsi_data().
real, dimension(:,:,:), allocatable, public read_write_data::slc_inc_gaus
GSI soil moisture increments on the gaussian grid.
Definition at line 55 of file read_write_data.f90.
Referenced by land_increments::gaussian_to_fv3_interp(), and read_gsi_data().
integer, dimension(:,:), allocatable, public read_write_data::slmsk_gaus
GSI land mask on the gaussian grid.
Definition at line 42 of file read_write_data.f90.
Referenced by adjust_nsst(), and read_gsi_data().
integer, dimension(:,:), allocatable, public read_write_data::soilsnow_gaus
GSI soil / snow mask for land on the gaussian grid. 1 - soil, 2 - snow, 0 - not land
Definition at line 45 of file read_write_data.f90.
Referenced by land_increments::gaussian_to_fv3_interp(), and read_gsi_data().
real, dimension(:,:,:), allocatable, public read_write_data::stc_inc_gaus
GSI soil temperature increments on the gaussian grid.
Definition at line 52 of file read_write_data.f90.
Referenced by land_increments::gaussian_to_fv3_interp(), and read_gsi_data().
Author
Generated automatically by Doxygen for global_cycle from the source code.