.TH "read_write_data::nsst_data" 3 "Tue Mar 9 2021" "Version 1.0.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read_write_data::nsst_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "real, dimension(:), allocatable \fBc_0\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBc_d\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBd_conv\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBdt_cool\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBifd\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBqrain\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBtfinc\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBtref\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBw_0\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBw_d\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBxs\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBxt\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBxtts\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBxu\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBxv\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBxz\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBxzts\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBz_c\fP"
.br
.ti -1c
.RI "real, dimension(:), allocatable \fBzm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file read_write_data\&.f90\&.
.SH "Field Documentation"
.PP 
.SS "real, dimension(:), allocatable read_write_data::nsst_data::c_0"

.PP
Definition at line 11 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::c_d"

.PP
Definition at line 12 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::d_conv"

.PP
Definition at line 13 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::dt_cool"

.PP
Definition at line 14 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::ifd"

.PP
Definition at line 15 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::qrain"

.PP
Definition at line 16 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::tfinc"

.PP
Definition at line 18 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::tref"

.PP
Definition at line 17 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::w_0"

.PP
Definition at line 19 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::w_d"

.PP
Definition at line 20 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::xs"

.PP
Definition at line 21 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::xt"

.PP
Definition at line 22 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::xtts"

.PP
Definition at line 23 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::xu"

.PP
Definition at line 24 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::xv"

.PP
Definition at line 25 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::xz"

.PP
Definition at line 26 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::xzts"

.PP
Definition at line 27 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::z_c"

.PP
Definition at line 28 of file read_write_data\&.f90\&.
.SS "real, dimension(:), allocatable read_write_data::nsst_data::zm"

.PP
Definition at line 29 of file read_write_data\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
