.TH "sfccyc_module" 3 "Fri Apr 30 2021" "Version 1.3.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sfccyc_module \- This program runs in two different modes:  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBkpdabs\fP"
.br
.RI "GRIB1 parameter number of maximum snow albedo\&. "
.ti -1c
.RI "integer \fBkpdabs_0\fP"
.br
.RI "GRIB1 parameter number of legacy maximum snow albedo\&. "
.ti -1c
.RI "integer \fBkpdabs_1\fP"
.br
.RI "GRIB1 parameter number of modis-based maximum snow albedo\&. "
.ti -1c
.RI "integer \fBkpdacn\fP"
.br
.RI "GRIB1 parameter number of sea ice concentration\&. "
.ti -1c
.RI "integer \fBkpdais\fP"
.br
.RI "GRIB1 parameter number of roughness length\&. "
.ti -1c
.RI "integer, dimension(4) \fBkpdalb\fP"
.br
.RI "GRIB1 parameter number of 4-component snow-free albedo\&. "
.ti -1c
.RI "integer, dimension(4), parameter \fBkpdalb_0\fP =(/212,215,213,216/)"
.br
.RI "GRIB1 parameter numbers for brigleb snow-free albedo\&. "
.ti -1c
.RI "integer, dimension(4), parameter \fBkpdalb_1\fP =(/189,190,191,192/)"
.br
.RI "GRIB1 parameter numbers for modis snow-free albedo\&. "
.ti -1c
.RI "integer, dimension(2), parameter \fBkpdalf\fP =(/214,217/)"
.br
.RI "GRIB1 parameter numbers of fraction for strongly/weakly zenith angle dependent albedo\&. "
.ti -1c
.RI "integer \fBkpdgla\fP"
.br
.RI "GRIB1 parameter number of glacial ice\&. "
.ti -1c
.RI "integer \fBkpdmsk\fP"
.br
.RI "GRIB1 parameter number of land mask\&. "
.ti -1c
.RI "integer \fBkpdmxi\fP"
.br
.RI "GRIB1 parameter number of maximum ice extent\&. "
.ti -1c
.RI "integer \fBkpdoro\fP"
.br
.RI "GRIB1 parameter number of orography\&. "
.ti -1c
.RI "integer \fBkpdplr\fP"
.br
.RI "GRIB1 parameter number of plant resistance\&. "
.ti -1c
.RI "integer \fBkpdscv\fP"
.br
.RI "GRIB1 parameter number of snow cover\&. "
.ti -1c
.RI "integer \fBkpdslp\fP"
.br
.RI "GRIB1 parameter number of slope type\&. "
.ti -1c
.RI "integer \fBkpdsmc\fP"
.br
.RI "GRIB1 parameter number of soil moisture\&. "
.ti -1c
.RI "integer \fBkpdsnd\fP"
.br
.RI "GRIB1 parameter number of physical snow depth\&. "
.ti -1c
.RI "integer \fBkpdsno\fP"
.br
.RI "GRIB1 parameter number of liquid equivalent snow depth\&. "
.ti -1c
.RI "integer \fBkpdsot\fP"
.br
.RI "GRIB1 parameter number of soil type\&. "
.ti -1c
.RI "integer \fBkpdstc\fP"
.br
.RI "GRIB1 parameter number of soil temperature\&. "
.ti -1c
.RI "integer \fBkpdtg3\fP"
.br
.RI "GRIB1 parameter number of soil substrate temperature\&. "
.ti -1c
.RI "integer \fBkpdtsf\fP"
.br
.RI "GRIB1 parameter number of skin temperature/SST\&. "
.ti -1c
.RI "integer \fBkpdveg\fP"
.br
.RI "GRIB1 parameter number of vegetation greenness\&. "
.ti -1c
.RI "integer \fBkpdvet\fP"
.br
.RI "GRIB1 parameter number of vegetation type\&. "
.ti -1c
.RI "integer \fBkpdvmn\fP"
.br
.RI "GRIB1 parameter number of minimum vegetation greenness\&. "
.ti -1c
.RI "integer \fBkpdvmx\fP"
.br
.RI "GRIB1 parameter number of maximum vegetation greenness\&. "
.ti -1c
.RI "integer \fBkpdwet\fP"
.br
.RI "GRIB1 parameter number of soil wetness\&. "
.ti -1c
.RI "integer \fBkpdzor\fP"
.br
.RI "GRIB1 parameter number of physical snow depth\&. "
.ti -1c
.RI "integer, parameter \fBmdata\fP =\fBxdata\fP*\fBydata\fP"
.br
.RI "Maximum number of input data points\&. "
.ti -1c
.RI "integer \fBsoil_type_landice\fP"
.br
.RI "Soil type category at permanent land-ice points\&. "
.ti -1c
.RI "integer \fBveg_type_landice\fP"
.br
.RI "Vegetation type category at permanent land-ice points\&. "
.ti -1c
.RI "integer, parameter \fBxdata\fP =5000"
.br
.RI "Maximum 'i' dimension of input data\&. "
.ti -1c
.RI "integer, parameter \fBydata\fP =2500"
.br
.RI "Maximum 'j' dimension of input data\&. "
.in -1c
.SH "Detailed Description"
.PP 
This program runs in two different modes: 


.IP "1." 4
analysis mode (fh=0\&.) this program merges climatology, analysis and forecast guess to create new surface fields\&. if analysis file is given, the program uses it if date of the analysis matches with iy,im,id,ih (see note below)\&.
.IP "2." 4
forecast mode (fh\&.gt\&.0\&.) this program interpolates climatology to the date corresponding to the forecast hour\&. if surface analysis file is given, for the corresponding dates, the program will use it\&.
.PP
.PP
if the date of the analysis does not match given iy,im,id,ih, (and fh), the program searches an old analysis by going back 6 hours, then 12 hours, then one day upto nrepmx days (parameter statement in the subrotine fixrd\&. now defined as 8)\&. this allows the user to provide non-daily analysis to be used\&. if matching field is not found, the forecast guess will be used\&.
.PP
use of a combined earlier surface analyses and current analysis is not allowed (as was done in the old version for snow analysis in which old snow analysis is used in combination with initial guess), except for sea surface temperature\&. for sst anolmaly interpolation, you need to set lanom=\&.true\&. and must provide sst analysis at initial time\&.
.PP
if you want to do complex merging of past and present surface field analysis, you need to create a separate file that contains daily surface field\&.
.PP
for a dead start, do not supply fnbgsi or set fnbgsi=' '
.PP
.IP "\(bu" 2
lugb is the unit number used in this subprogram
.IP "\(bu" 2
len \&.\&.\&. number of points on which sfccyc operates
.IP "\(bu" 2
lsoil \&.\&. number of soil layers (2 as of april, 1994)
.IP "\(bu" 2
iy,im,id,ih \&.\&. year, month, day, and hour of initial state\&.
.IP "\(bu" 2
fh \&.\&. forecast hour
.IP "\(bu" 2
rla, rlo -- latitude and longitudes of the len points
.IP "\(bu" 2
sig1t \&.\&. sigma level 1 temperature for dead start\&. should be on gaussian grid\&. if not dead start, no need for dimension but set to zero as in the example below\&.
.PP
.PP
\fBAuthor\fP
.RS 4
M\&. Iredell, xuli, Hang Lei, George Gayno 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "integer sfccyc_module::kpdabs"

.PP
GRIB1 parameter number of maximum snow albedo\&. 
.PP
Definition at line 77 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdabs_0"

.PP
GRIB1 parameter number of legacy maximum snow albedo\&. 
.PP
Definition at line 79 of file sfcsub\&.F\&.
.PP
Referenced by sfccycle()\&.
.SS "integer sfccyc_module::kpdabs_1"

.PP
GRIB1 parameter number of modis-based maximum snow albedo\&. 
.PP
Definition at line 81 of file sfcsub\&.F\&.
.PP
Referenced by sfccycle()\&.
.SS "integer sfccyc_module::kpdacn"

.PP
GRIB1 parameter number of sea ice concentration\&. 
.PP
Definition at line 68 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdais"

.PP
GRIB1 parameter number of roughness length\&. 
.PP
Definition at line 57 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer, dimension(4) sfccyc_module::kpdalb"

.PP
GRIB1 parameter number of 4-component snow-free albedo\&. 
.PP
Definition at line 83 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer, dimension(4), parameter sfccyc_module::kpdalb_0 =(/212,215,213,216/)"

.PP
GRIB1 parameter numbers for brigleb snow-free albedo\&. 
.PP
Definition at line 95 of file sfcsub\&.F\&.
.PP
Referenced by sfccycle()\&.
.SS "integer, dimension(4), parameter sfccyc_module::kpdalb_1 =(/189,190,191,192/)"

.PP
GRIB1 parameter numbers for modis snow-free albedo\&. 
.PP
Definition at line 98 of file sfcsub\&.F\&.
.PP
Referenced by sfccycle()\&.
.SS "integer, dimension(2), parameter sfccyc_module::kpdalf =(/214,217/)"

.PP
GRIB1 parameter numbers of fraction for strongly/weakly zenith angle dependent albedo\&. 
.PP
Definition at line 101 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdgla"

.PP
GRIB1 parameter number of glacial ice\&. 
.PP
Definition at line 61 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdmsk"

.PP
GRIB1 parameter number of land mask\&. 
.PP
Definition at line 66 of file sfcsub\&.F\&.
.PP
Referenced by sfccycle()\&.
.SS "integer sfccyc_module::kpdmxi"

.PP
GRIB1 parameter number of maximum ice extent\&. 
.PP
Definition at line 62 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdoro"

.PP
GRIB1 parameter number of orography\&. 
.PP
Definition at line 65 of file sfcsub\&.F\&.
.SS "integer sfccyc_module::kpdplr"

.PP
GRIB1 parameter number of plant resistance\&. 
.PP
Definition at line 60 of file sfcsub\&.F\&.
.SS "integer sfccyc_module::kpdscv"

.PP
GRIB1 parameter number of snow cover\&. 
.PP
Definition at line 63 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdslp"

.PP
GRIB1 parameter number of slope type\&. 
.PP
Definition at line 76 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdsmc"

.PP
GRIB1 parameter number of soil moisture\&. 
.PP
Definition at line 64 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdsnd"

.PP
GRIB1 parameter number of physical snow depth\&. 
.PP
Definition at line 78 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdsno"

.PP
GRIB1 parameter number of liquid equivalent snow depth\&. 
.PP
Definition at line 54 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdsot"

.PP
GRIB1 parameter number of soil type\&. 
.PP
Definition at line 71 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdstc"

.PP
GRIB1 parameter number of soil temperature\&. 
.PP
Definition at line 67 of file sfcsub\&.F\&.
.PP
Referenced by sfccycle()\&.
.SS "integer sfccyc_module::kpdtg3"

.PP
GRIB1 parameter number of soil substrate temperature\&. 
.PP
Definition at line 58 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdtsf"

.PP
GRIB1 parameter number of skin temperature/SST\&. 
.PP
Definition at line 52 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdveg"

.PP
GRIB1 parameter number of vegetation greenness\&. 
.PP
Definition at line 69 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdvet"

.PP
GRIB1 parameter number of vegetation type\&. 
.PP
Definition at line 70 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdvmn"

.PP
GRIB1 parameter number of minimum vegetation greenness\&. 
.PP
Definition at line 72 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdvmx"

.PP
GRIB1 parameter number of maximum vegetation greenness\&. 
.PP
Definition at line 74 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdwet"

.PP
GRIB1 parameter number of soil wetness\&. 
.PP
Definition at line 53 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer sfccyc_module::kpdzor"

.PP
GRIB1 parameter number of physical snow depth\&. 
.PP
Definition at line 56 of file sfcsub\&.F\&.
.PP
Referenced by setrmsk(), and sfccycle()\&.
.SS "integer, parameter sfccyc_module::mdata =\fBxdata\fP*\fBydata\fP"

.PP
Maximum number of input data points\&. 
.PP
Definition at line 106 of file sfcsub\&.F\&.
.PP
Referenced by fixrda(), fixrdc(), fixrdg(), hmskrd(), and sfccycle()\&.
.SS "integer sfccyc_module::soil_type_landice"

.PP
Soil type category at permanent land-ice points\&. 
.PP
Definition at line 109 of file sfcsub\&.F\&.
.PP
Referenced by merge(), and sfccycle()\&.
.SS "integer sfccyc_module::veg_type_landice"

.PP
Vegetation type category at permanent land-ice points\&. 
.PP
Definition at line 107 of file sfcsub\&.F\&.
.PP
Referenced by merge(), and sfccycle()\&.
.SS "integer, parameter sfccyc_module::xdata =5000"

.PP
Maximum 'i' dimension of input data\&. 
.PP
Definition at line 104 of file sfcsub\&.F\&.
.PP
Referenced by hmskrd()\&.
.SS "integer, parameter sfccyc_module::ydata =2500"

.PP
Maximum 'j' dimension of input data\&. 
.PP
Definition at line 105 of file sfcsub\&.F\&.
.PP
Referenced by hmskrd()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
