.TH "sfccyc_module" 3 "Tue Mar 9 2021" "Version 1.0.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sfccyc_module \- This program runs in two different modes:  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBkpdais\fP"
.br
.ti -1c
.RI "integer, dimension(4), parameter \fBkpdalb_0\fP =(/212,215,213,216/)"
.br
.ti -1c
.RI "integer, dimension(4), parameter \fBkpdalb_1\fP =(/189,190,191,192/)"
.br
.ti -1c
.RI "integer, dimension(2), parameter \fBkpdalf\fP =(/214,217/)"
.br
.ti -1c
.RI "integer \fBkpdgla\fP"
.br
.ti -1c
.RI "integer \fBkpdplr\fP"
.br
.ti -1c
.RI "integer \fBkpdsno\fP"
.br
.ti -1c
.RI "integer \fBkpdtg3\fP"
.br
.ti -1c
.RI "integer \fBkpdtsf\fP"
.br
.ti -1c
.RI "integer \fBkpdwet\fP"
.br
.ti -1c
.RI "integer \fBkpdzor\fP"
.br
.ti -1c
.RI "integer, parameter \fBmdata\fP =xdata*ydata"
.br
.ti -1c
.RI "integer \fBsoil_type_landice\fP"
.br
.ti -1c
.RI "integer \fBveg_type_landice\fP"
.br
.ti -1c
.RI "integer, parameter \fBxdata\fP =5000"
.br
.ti -1c
.RI "integer, parameter \fBydata\fP =2500"
.br
.in -1c
.SH "Detailed Description"
.PP 
This program runs in two different modes: 


.IP "1." 4
analysis mode (fh=0\&.) this program merges climatology, analysis and forecast guess to create new surface fields\&. if analysis file is given, the program uses it if date of the analysis matches with iy,im,id,ih (see note below)\&.
.IP "2." 4
forecast mode (fh\&.gt\&.0\&.) this program interpolates climatology to the date corresponding to the forecast hour\&. if surface analysis file is given, for the corresponding dates, the program will use it\&.
.PP
.PP
if the date of the analysis does not match given iy,im,id,ih, (and fh), the program searches an old analysis by going back 6 hours, then 12 hours, then one day upto nrepmx days (parameter statement in the subrotine fixrd\&. now defined as 8)\&. this allows the user to provide non-daily analysis to be used\&. if matching field is not found, the forecast guess will be used\&.
.PP
use of a combined earlier surface analyses and current analysis is not allowed (as was done in the old version for snow analysis in which old snow analysis is used in combination with initial guess), except for sea surface temperature\&. for sst anolmaly interpolation, you need to set lanom=\&.true\&. and must provide sst analysis at initial time\&.
.PP
if you want to do complex merging of past and present surface field analysis, you need to create a separate file that contains daily surface field\&.
.PP
for a dead start, do not supply fnbgsi or set fnbgsi=' '
.PP
.IP "\(bu" 2
lugb is the unit number used in this subprogram
.IP "\(bu" 2
len \&.\&.\&. number of points on which sfccyc operates
.IP "\(bu" 2
lsoil \&.\&. number of soil layers (2 as of april, 1994)
.IP "\(bu" 2
iy,im,id,ih \&.\&. year, month, day, and hour of initial state\&.
.IP "\(bu" 2
fh \&.\&. forecast hour
.IP "\(bu" 2
rla, rlo -- latitude and longitudes of the len points
.IP "\(bu" 2
sig1t \&.\&. sigma level 1 temperature for dead start\&. should be on gaussian grid\&. if not dead start, no need for dimension but set to zero as in the example below\&.
.PP
.PP
\fBAuthor\fP
.RS 4
M\&. Iredell, xuli, Hang Lei, George Gayno 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
