/home/ed/UFS_UTILS/sorc/global_cycle.fd/sfcsub.F
NAME
/home/ed/UFS_UTILS/sorc/global_cycle.fd/sfcsub.F - This is a limited point version of surface program.
SYNOPSIS
Modules
module sfccyc_module
This program runs in two different modes:
Functions/Subroutines
subroutine albocn (albclm, slmask, albomx, len)
Set the albedo at open water points.
subroutine analy (lugb, iy, im, id, ih, fh, len, lsoil, slmask, fntsfa, fnweta, fnsnoa, fnzora, fnalba, fnaisa, fntg3a, fnscva, fnsmca, fnstca, fnacna, fnvega, fnveta, fnsota, fnvmna, fnvmxa, fnslpa, fnabsa, tsfanl, wetanl, snoanl, zoranl, albanl, aisanl, tg3anl, cvanl, cvbanl, cvtanl, smcanl, stcanl, slianl, scvanl, acnanl, veganl, vetanl, sotanl, alfanl, tsfan0, vmnanl, vmxanl, slpanl, absanl, kpdtsf, kpdwet, kpdsno, kpdsnd, kpdzor, kpdalb, kpdais, kpdtg3, kpdscv, kpdacn, kpdsmc, kpdstc, kpdveg, kprvet, kpdsot, kpdalf, kpdvmn, kpdvmx, kpdslp, kpdabs, irttsf, irtwet, irtsno, irtzor, irtalb, irtais, irttg3, irtscv, irtacn, irtsmc, irtstc, irtveg, irtvet, irtsot, irtalf, irtvmn, irtvmx, irtslp, irtabs, imsk, jmsk, slmskh, outlat, outlon, gaus, blno, blto, me, lanom)
Read analysis fields.
subroutine anomint (tsfan0, tsfclm, tsfcl0, tsfanl, len)
Add initial SST anomaly to date interpolated climatology.
subroutine clima (lugb, iy, im, id, ih, fh, len, lsoil, slmask, fntsfc, fnwetc, fnsnoc, fnzorc, fnalbc, fnaisc, fntg3c, fnscvc, fnsmcc, fnstcc, fnacnc, fnvegc, fnvetc, fnsotc, fnvmnc, fnvmxc, fnslpc, fnabsc, tsfclm, tsfcl2, wetclm, snoclm, zorclm, albclm, aisclm, tg3clm, cvclm, cvbclm, cvtclm, cnpclm, smcclm, stcclm, sliclm, scvclm, acnclm, vegclm, vetclm, sotclm, alfclm, vmnclm, vmxclm, slpclm, absclm, kpdtsf, kpdwet, kpdsno, kpdzor, kpdalb, kpdais, kpdtg3, kpdscv, kpdacn, kpdsmc, kpdstc, kpdveg, kpdvet, kpdsot, kpdalf, tsfcl0, kpdvmn, kpdvmx, kpdslp, kpdabs, deltsfc, lanom, imsk, jmsk, slmskh, outlat, outlon, gaus, blno, blto, me, lprnt, iprnt, fnalbc2, ialb, tile_num_ch, i_index, j_index)
Driver routine that reads in climatological data for a given time, and, if necessary, interpolates it to the model grid.
subroutine count (slimsk, sno, ijmax)
Counts the number of model points that are snow covered land, snow-free land, open water, sea ice, and snow covered sea ice.
subroutine dayoyr (iyr, imo, idy, ldy)
Compute day of the year based on month and day.
subroutine filanl (tsfanl, tsfan2, wetanl, snoanl, zoranl, albanl, aisanl, tg3anl, cvanl, cvbanl, cvtanl, cnpanl, smcanl, stcanl, slianl, scvanl, veganl, vetanl, sotanl, alfanl, sihanl, sicanl, vmnanl, vmxanl, slpanl, absanl, tsfclm, tsfcl2, wetclm, snoclm, zorclm, albclm, aisclm, tg3clm, cvclm, cvbclm, cvtclm, cnpclm, smcclm, stcclm, sliclm, scvclm, vegclm, vetclm, sotclm, alfclm, sihclm, sicclm, vmnclm, vmxclm, slpclm, absclm, len, lsoil)
Fill in analysis arrays with climatology before reading analysis data.
subroutine filfcs (tsffcs, wetfcs, snofcs, zorfcs, albfcs, tg3fcs, cvfcs, cvbfcs, cvtfcs, cnpfcs, smcfcs, stcfcs, slifcs, aisfcs, vegfcs, vetfcs, sotfcs, alffcs, sihfcs, sicfcs, vmnfcs, vmxfcs, slpfcs, absfcs, tsfanl, wetanl, snoanl, zoranl, albanl, tg3anl, cvanl, cvbanl, cvtanl, cnpanl, smcanl, stcanl, slianl, aisanl, veganl, vetanl, sotanl, alfanl, sihanl, sicanl, vmnanl, vmxanl, slpanl, absanl, len, lsoil)
Fill in model grid guess arrays with analysis values if this is a dead start.
subroutine fixrda (lugb, fngrib, kpds5, slmask, iy, im, id, ih, fh, gdata, len, iret, imsk, jmsk, slmskh, gaus, blno, blto, outlat, outlon, me)
Read in grib1 analysis data for the requested date and horizontally interpolate to the model grid.
subroutine fixrdc (lugb, fngrib, kpds5, kpds7, mon, slmask, gdata, len, iret, imsk, jmsk, slmskh, gaus, blno, blto, outlat, outlon, me)
Read in grib1 climatology data for a specific month and and horizontally interpolate to the model grid.
subroutine fixrdc_tile (filename_raw, tile_num_ch, i_index, j_index, kpds, var, mon, npts, me)
Reads in climatological data on the model grid tile for a given month.
subroutine fixrdg (lugb, idim, jdim, fngrib, kpds5, gdata, gaus, blno, blto, me)
Read a GRIB1 file.
subroutine ga2la (gauin, imxin, jmxin, regout, imxout, jmxout, wlon, rnlat, rlnout, rltout, gaus, blno, blto)
Interpolation from lat/lon or gaussian grid to a lat/lon grid.
subroutine gaulat (gaul, k)
Calculate gaussian latitudes.
subroutine getarea (kgds, dlat, dlon, rslat, rnlat, wlon, elon, ijordr, me)
For a given GRIB1 grid description section array, determine some grid specifications.
subroutine getscv (snofld, scvfld, len)
Set snow cover flag based on snow depth.
subroutine getsmc (wetfld, len, lsoil, smcfld, me)
Set soil moisture from soil wetness.
subroutine getstc (tsffld, tg3fld, slifld, len, lsoil, stcfld, tsfimx)
Set soil temperature and sea ice column temperature.
subroutine hmskrd (lugb, imsk, jmsk, fnmskh, kpds5, slmskh, gausm, blnmsk, bltmsk, me)
Read a high-resolution land mask.
subroutine la2ga (regin, imxin, jmxin, rinlon, rinlat, rlon, rlat, inttyp, gauout, len, lmask, rslmsk, slmask, outlat, outlon, me)
Interpolate data from a lat/lon grid to the model grid.
subroutine landtyp (vegtype, soiltype, slptype, slmask, len)
Set vegetation, soil and slope type at undefined model points.
subroutine maxmin (f, imax, kmax)
Compute the maxmimum and minimum of a field.
subroutine merge (len, lsoil, iy, im, id, ih, fh, deltsfc, sihfcs, sicfcs, vmnfcs, vmxfcs, slpfcs, absfcs, tsffcs, wetfcs, snofcs, zorfcs, albfcs, aisfcs, cvfcs, cvbfcs, cvtfcs, cnpfcs, smcfcs, stcfcs, slifcs, vegfcs, vetfcs, sotfcs, alffcs, sihanl, sicanl, vmnanl, vmxanl, slpanl, absanl, tsfanl, tsfan2, wetanl, snoanl, zoranl, albanl, aisanl, cvanl, cvbanl, cvtanl, cnpanl, smcanl, stcanl, slianl, veganl, vetanl, sotanl, alfanl, ctsfl, calbl, caisl, csnol, csmcl, czorl, cstcl, cvegl, ctsfs, calbs, caiss, csnos, csmcs, czors, cstcs, cvegs, ccv, ccvb, ccvt, ccnp, cvetl, cvets, csotl, csots, calfl, calfs, csihl, csihs, csicl, csics, cvmnl, cvmns, cvmxl, cvmxs, cslpl, cslps, cabsl, cabss, irttsf, irtwet, irtsno, irtzor, irtalb, irtais, irttg3, irtscv, irtacn, irtsmc, irtstc, irtveg, irtvmn, irtvmx, irtslp, irtabs, irtvet, irtsot, irtalf, landice, me)
Blend the model forecast (or first guess) fields with the analysis/climatology.
subroutine monitr (lfld, fld, slimsk, sno, ijmax)
Determine the maximum and minimum values of a surface field at snow-free and snow covered land, open water, and snow-free and snow covered sea ice.
subroutine netcdf_err (error)
Print the error message for a given netCDF return code.
subroutine newice (slianl, slifcs, tsfanl, tsffcs, len, lsoil, sihnew, sicnew, sihanl, sicanl, albanl, snoanl, zoranl, smcanl, stcanl, albsea, snosea, zorsea, smcsea, smcice, tsfmin, tsfice, albice, zorice, tgice, rla, rlo, me)
Adjust surface fields when ice melts or forms.
subroutine qcbyfc (tsffcs, snofcs, qctsfs, qcsnos, qctsfi, len, lsoil, snoanl, aisanl, slianl, tsfanl, albanl, zoranl, smcanl, smcclm, tsfsmx, albomx, zoromx, me)
Quality control analysis fields using the first guess.
subroutine qcmxice (glacir, amxice, len, me)
Quality control maximum ice extent.
subroutine qcmxmn (ttl, fld, slimsk, sno, iceflg, fldlmx, fldlmn, fldomx, fldomn, fldimx, fldimn, fldjmx, fldjmn, fldsmx, fldsmn, epsfld, rla, rlo, len, mode, percrit, lgchek, me)
Range check a field.
subroutine qcsice (ais, glacir, amxice, aicice, aicsea, sllnd, slmask, rla, rlo, len, me)
Check the sea ice cover mask against the land-sea mask.
subroutine qcsli (slianl, slifcs, len, me)
Check consistency between the forecast and analysis land-sea-ice mask.
subroutine qcsnow (snoanl, slmask, aisanl, glacir, len, snoval, landice, me)
Quality control snow at the model points.
subroutine rof01 (aisfld, len, op, crit)
Round a field up to one or down to zero.
subroutine scale (fld, len, scl)
Multiply a field by a scaling factor.
subroutine setlsi (slmask, aisfld, len, aicice, slifld)
Set land-sea-ice mask at sea ice.
subroutine setrmsk (kpds5, slmask, igaul, jgaul, wlon, rnlat, data, imax, jmax, rlnout, rltout, lmask, rslmsk, gaus, blno, blto, kgds1, kpds4, lbms)
Set the mask for the input data.
subroutine setzro (fld, eps, len)
Set a field to zero if it is less than a threshold.
subroutine sfccycle (lugb, len, lsoil, sig1t, deltsfc, iy, im, id, ih, fh, rla, rlo, slmask, orog, orog_uf, use_ufo, nst_anl, sihfcs, sicfcs, sitfcs, swdfcs, slcfcs, vmnfcs, vmxfcs, slpfcs, absfcs, tsffcs, snofcs, zorfcs, albfcs, tg3fcs, cnpfcs, smcfcs, stcfcs, slifcs, aisfcs, vegfcs, vetfcs, sotfcs, alffcs, cvfcs, cvbfcs, cvtfcs, me, nlunit, sz_nml, input_nml_file, ialb, isot, ivegsrc, tile_num_ch, i_index, j_index)
Surface cycling driver routine.
subroutine snodpth (scvanl, slianl, tsfanl, snoclm, glacir, snwmax, snwmin, landice, len, snoanl, me)
Estimate snow depth at glacial, land and sea ice points.
subroutine snodpth2 (glacir, snwmax, snoanl, len, me)
Ensure deep snow pack at permanent glacial points.
subroutine snosfc (snoanl, tsfanl, tsfsmx, len, me)
Check skin temperature at points with snow.
subroutine subst (data, imax, jmax, dlon, dlat, ijordr)
Take an array of data on a lat/lon based grid and rearrange it so the corner point is in the 'lower left' and adjacent points in the 'i' direction are consecutive.
subroutine tsfcor (tsfc, orog, slmask, umask, len, rlapse)
Adjust skin temperature or SST for terrain.
subroutine usesgt (sig1t, slianl, tg3anl, len, lsoil, tsfanl, stcanl, tsfimx)
Set soil temperature and sea ice column temperature for a dead start.
Variables
integer sfccyc_module::kpdabs
GRIB1 parameter number of maximum snow albedo.
integer sfccyc_module::kpdabs_0
GRIB1 parameter number of legacy maximum snow albedo.
integer sfccyc_module::kpdabs_1
GRIB1 parameter number of modis-based maximum snow albedo.
integer sfccyc_module::kpdacn
GRIB1 parameter number of sea ice concentration.
integer sfccyc_module::kpdais
GRIB1 parameter number of roughness length.
integer, dimension(4) sfccyc_module::kpdalb
GRIB1 parameter number of 4-component snow-free albedo.
integer, dimension(4), parameter sfccyc_module::kpdalb_0 =(/212,215,213,216/)
GRIB1 parameter numbers for brigleb snow-free albedo.
integer, dimension(4), parameter sfccyc_module::kpdalb_1 =(/189,190,191,192/)
GRIB1 parameter numbers for modis snow-free albedo.
integer, dimension(2), parameter sfccyc_module::kpdalf =(/214,217/)
GRIB1 parameter numbers of fraction for strongly/weakly zenith angle dependent albedo.
integer sfccyc_module::kpdgla
GRIB1 parameter number of glacial ice.
integer sfccyc_module::kpdmsk
GRIB1 parameter number of land mask.
integer sfccyc_module::kpdmxi
GRIB1 parameter number of maximum ice extent.
integer sfccyc_module::kpdoro
GRIB1 parameter number of orography.
integer sfccyc_module::kpdplr
GRIB1 parameter number of plant resistance.
integer sfccyc_module::kpdscv
GRIB1 parameter number of snow cover.
integer sfccyc_module::kpdslp
GRIB1 parameter number of slope type.
integer sfccyc_module::kpdsmc
GRIB1 parameter number of soil moisture.
integer sfccyc_module::kpdsnd
GRIB1 parameter number of physical snow depth.
integer sfccyc_module::kpdsno
GRIB1 parameter number of liquid equivalent snow depth.
integer sfccyc_module::kpdsot
GRIB1 parameter number of soil type.
integer sfccyc_module::kpdstc
GRIB1 parameter number of soil temperature.
integer sfccyc_module::kpdtg3
GRIB1 parameter number of soil substrate temperature.
integer sfccyc_module::kpdtsf
GRIB1 parameter number of skin temperature/SST.
integer sfccyc_module::kpdveg
GRIB1 parameter number of vegetation greenness.
integer sfccyc_module::kpdvet
GRIB1 parameter number of vegetation type.
integer sfccyc_module::kpdvmn
GRIB1 parameter number of minimum vegetation greenness.
integer sfccyc_module::kpdvmx
GRIB1 parameter number of maximum vegetation greenness.
integer sfccyc_module::kpdwet
GRIB1 parameter number of soil wetness.
integer sfccyc_module::kpdzor
GRIB1 parameter number of physical snow depth.
integer, parameter sfccyc_module::mdata =xdata*ydata
Maximum number of input data points.
integer sfccyc_module::soil_type_landice
Soil type category at permanent land-ice points.
integer sfccyc_module::veg_type_landice
Vegetation type category at permanent land-ice points.
integer, parameter sfccyc_module::xdata =5000
Maximum 'i' dimension of input data.
integer, parameter sfccyc_module::ydata =2500
Maximum 'j' dimension of input data.
Detailed Description
This is a limited point version of surface program.
Author
Shrinivas Moorthi Mark Iredell NOAA/EMC
Definition in file sfcsub.F.
Function/Subroutine Documentation
subroutine albocn (real (kind=kind_io8), dimension(len,4) albclm, real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8) albomx, integer len)
Set the albedo at open water points.
Parameters
albclm Albedo.
slmask The land-sea-ice mask.
albomx The albedo at open water.
len Number of model points to process.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 6622 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine analy (integer lugb, integer iy, integer im, integer id, integer ih, real (kind=kind_io8) fh, integer len, integer lsoil, real (kind=kind_io8), dimension(len) slmask, character*500 fntsfa, character*500 fnweta, character*500 fnsnoa, character*500 fnzora, character*500 fnalba, character*500 fnaisa, character*500 fntg3a, character*500 fnscva, character*500 fnsmca, character*500 fnstca, character*500 fnacna, character*500 fnvega, character*500 fnveta, character*500 fnsota, character*500 fnvmna, character*500 fnvmxa, character*500 fnslpa, character*500 fnabsa, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len) wetanl, real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) zoranl, real (kind=kind_io8), dimension(len,4) albanl, real (kind=kind_io8), dimension(len) aisanl, real (kind=kind_io8), dimension(len) tg3anl, real (kind=kind_io8), dimension (len) cvanl, real (kind=kind_io8), dimension(len) cvbanl, real (kind=kind_io8), dimension(len) cvtanl, real (kind=kind_io8), dimension(len,lsoil) smcanl, real (kind=kind_io8), dimension(len,lsoil) stcanl, real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) scvanl, real (kind=kind_io8), dimension(len) acnanl, real (kind=kind_io8), dimension(len) veganl, real (kind=kind_io8), dimension(len) vetanl, real (kind=kind_io8), dimension(len) sotanl, real (kind=kind_io8), dimension(len,2) alfanl, real (kind=kind_io8), dimension(len) tsfan0, real (kind=kind_io8), dimension(len) vmnanl, real (kind=kind_io8), dimension(len) vmxanl, real (kind=kind_io8), dimension(len) slpanl, real (kind=kind_io8), dimension(len) absanl, integer kpdtsf, integer kpdwet, integer kpdsno, integer kpdsnd, integer kpdzor, integer, dimension(4) kpdalb, integer kpdais, integer kpdtg3, integer kpdscv, integer kpdacn, integer kpdsmc, integer kpdstc, integer kpdveg, integer kprvet, integer kpdsot, integer, dimension(2) kpdalf, integer kpdvmn, integer kpdvmx, integer kpdslp, integer kpdabs, integer irttsf, integer irtwet, integer irtsno, integer irtzor, integer irtalb, integer irtais, integer irttg3, integer irtscv, integer irtacn, integer irtsmc, integer irtstc, integer irtveg, integer irtvet, integer irtsot, integer irtalf, integer irtvmn, integer irtvmx, integer irtslp, integer irtabs, integer imsk, integer jmsk, real (kind=kind_io8), dimension(imsk,jmsk) slmskh, real (kind=kind_io8), dimension(len) outlat, real (kind=kind_io8), dimension(len) outlon, logical gaus, real (kind=kind_io8) blno, real (kind=kind_io8) blto, integer me, logical lanom)
Read analysis fields.
Parameters
lugb Fortran unit number for analysis files.
iy Cycle year.
im Cycle month.
id Cycle day.
ih Cycle hour.
fh Forecast hour.
len Number of model points to process.
lsoil Number of soil layers.
slmask Model land-sea mask.
fntsfa SST analysis file.
fnweta Soil wetness analysis file.
fnsnoa Snow analysis file
fnzora Roughness length analysis file.
fnalba Snow-free albedo analysis file.
fnaisa Sea ice mask analysis file.
fntg3a Soil substrate analysis file.
fnscva Snow cover analysis file.
fnsmca Soil moisture analysis file.
fnstca Soil temperature analysis file.
fnacna Sea ice concentration analysis file.
fnvega Vegetation greenness analysis file.
fnveta Vegetation type analysis file.
fnsota Soil type analysis file.
fnvmna Minimum vegetation greenness analysis file.
fnvmxa Maximum vegetation greenness analysis file.
fnslpa Slope type analysis file.
fnabsa Maximum snow albedo analysis file.
tsfanl Skin temperature/SST analysis on model grid.
wetanl Soil wetness analysis on model grid.
snoanl Snow analysis on model grid.
zoranl Roughness length analysis on model grid.
albanl Snow-free albedo analysis on model grid.
aisanl Sea ice mask analysis on model grid.
tg3anl Soil substrate analysis on model grid.
cvanl Convective cloud cover analysis on model grid.
cvbanl Convective cloud base analysis on model grid.
cvtanl Convective cloud top analysis on model grid.
smcanl Soil moisture analysis on model grid.
stcanl Soil temperature analysis on model grid.
slianl Not used.
scvanl Snow cover analysis on model grid.
acnanl Sea ice concentration analysis on model grid.
veganl Vegetation greenness analysis on model grid.
vetanl Vegetation type analysis on model grid.
sotanl Soil type analysis on model grid.
alfanl Analysis of fraction for strongly and weakly zenith angle dependent albedo on model grid.
tsfan0 SST analysis at forecast hour 0 on model grid.
vmnanl Minimum vegetation greenness analysis on model grid.
vmxanl Maximum vegetation greenness analysis on model grid.
slpanl Slope type analysis on model grid.
absanl Maximum snow albedo analysis on model grid.
kpdtsf Grib parameter number of skin temperature/SST.
kpdwet Grib parameter number of soil wetness.
kpdsno Grib parameter number of liquid equivalent snow depth.
kpdsnd Grib parameter number of physical snow depth.
kpdzor Grib parameter number of roughness length.
kpdalb Grib parameter number of snow-free albedo.
kpdais Grib parameter number of sea ice mask.
kpdtg3 Grib parameter number of soil substrate temperature.
kpdscv Grib parameter number of snow cover.
kpdacn Grib parameter number of sea ice concentration.
kpdsmc Grib parameter number of soil moisture.
kpdstc Grib parameter number of soil temperature.
kpdveg Grib parameter number of vegetation greenness.
kprvet Grib parameter number of vegetation type.
kpdsot Grib parameter number of soil type.
kpdalf Grib parameter number for fraction for strongly and weakly zenith angle dependent albedo.
kpdvmn Grib parameter number of minimum vegetation greenness.
kpdvmx Grib parameter number of maximum vegetation greenness.
kpdslp Grib parameter number of slope type.
kpdabs Grib parameter number of maximum snow albedo.
irttsf Return code from read of skin temperature/SST analysis file.
irtwet Return code from read of soil wetness analysis file.
irtsno Return code from read of snow analysis file.
irtzor Return code from read of roughness length file.
irtalb Return code from read of snow-free albedo analysis file.
irtais Return code from read of ice mask analysis file.
irttg3 Return code from read of soil substrate temperature analysis file.
irtscv Return code from read of snow cover analysis file.
irtacn Return code from read of sea ice concentration analysis file.
irtsmc Return code from read of soil moisture analysis file.
irtstc Return code from read of soil temperature analysis file.
irtveg Return code from read of vegetation greenness analysis file.
irtvet Return code from read of vegetation type analysis file.
irtsot Return code from read of soil type analysis file.
irtalf Return code from read of file containing fraction for strongly and weakly zenith angle dependent albedo.
irtvmn Return code from read of minimum vegetation greenness analysis file.
irtvmx Return code from read of maximum vegetation greenness analysis file.
irtslp Return code from read of slope type analysis file.
irtabs Return code from read of maximum snow albedo analysis file.
imsk 'i' dimension of the high-res mask used for analysis data without a bitmap.
jmsk 'j' dimension of the high-res mask used for analysis data without a bitmap.
slmskh The high-resolution mask used for analysis data without a bitmap.
outlat Model latitudes
outlon Model longitudes
gaus When true, the high-res mask is on a gaussian grid.
blno Corner point longitude of the high-res mask.
blto Corner point latitude of the high-res mask.
me MPI task number.
lanom When true, do sst anomaly interpolation.
Author
Shrinivas Moorthi
Definition at line 4077 of file sfcsub.F.
References fixrda(), machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine anomint (real (kind=kind_io8), dimension(len) tsfan0, real (kind=kind_io8), dimension(len) tsfclm, real (kind=kind_io8), dimension(len) tsfcl0, real (kind=kind_io8), dimension(len) tsfanl, integer len)
Add initial SST anomaly to date interpolated climatology.
Parameters
tsfan0 Skin temperature/SST analysis at initial time.
tsfclm Skin temperature/SST climatology.
tsfcl0 Skin temperature/SST climatology at initial time.
tsfanl Updated skin temperature/SST.
len Number of model points to process.
Author
Shrinivas Moorthi
Definition at line 7694 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine clima (integer lugb, integer iy, integer im, integer id, integer ih, real (kind=kind_io8) fh, integer len, integer lsoil, real (kind=kind_io8), dimension(len) slmask, character*500 fntsfc, character*500 fnwetc, character*500 fnsnoc, character*500 fnzorc, character*500 fnalbc, character*500 fnaisc, character*500 fntg3c, character*500 fnscvc, character*500 fnsmcc, character*500 fnstcc, character*500 fnacnc, character*500 fnvegc, character*500 fnvetc, character*500 fnsotc, character*500 fnvmnc, character*500 fnvmxc, character*500 fnslpc, character*500 fnabsc, real (kind=kind_io8), dimension(len) tsfclm, real (kind=kind_io8), dimension(len) tsfcl2, real (kind=kind_io8), dimension(len) wetclm, real (kind=kind_io8), dimension(len) snoclm, real (kind=kind_io8), dimension(len) zorclm, real (kind=kind_io8), dimension(len,4) albclm, real (kind=kind_io8), dimension(len) aisclm, real (kind=kind_io8), dimension(len) tg3clm, real (kind=kind_io8), dimension (len) cvclm, real (kind=kind_io8), dimension(len) cvbclm, real (kind=kind_io8), dimension(len) cvtclm, real (kind=kind_io8), dimension(len) cnpclm, real (kind=kind_io8), dimension(len,lsoil) smcclm, real (kind=kind_io8), dimension(len,lsoil) stcclm, real (kind=kind_io8), dimension(len) sliclm, real (kind=kind_io8), dimension(len) scvclm, real (kind=kind_io8), dimension(len) acnclm, real (kind=kind_io8), dimension(len) vegclm, real (kind=kind_io8), dimension(len) vetclm, real (kind=kind_io8), dimension(len) sotclm, real (kind=kind_io8), dimension(len,2) alfclm, real (kind=kind_io8), dimension(len) vmnclm, real (kind=kind_io8), dimension(len) vmxclm, real (kind=kind_io8), dimension(len) slpclm, real (kind=kind_io8), dimension(len) absclm, integer kpdtsf, integer kpdwet, integer kpdsno, integer kpdzor, integer, dimension(4) kpdalb, integer kpdais, integer kpdtg3, integer kpdscv, integer kpdacn, integer kpdsmc, integer kpdstc, integer kpdveg, integer kpdvet, integer kpdsot, integer, dimension(2) kpdalf, real (kind=kind_io8), dimension(len) tsfcl0, integer kpdvmn, integer kpdvmx, integer kpdslp, integer kpdabs, real (kind=kind_io8) deltsfc, logical lanom, integer imsk, integer jmsk, real (kind=kind_io8), dimension(imsk,jmsk) slmskh, real (kind=kind_io8), dimension(len) outlat, real (kind=kind_io8), dimension(len) outlon, logical gaus, real (kind=kind_io8) blno, real (kind=kind_io8) blto, integer me, logical lprnt, integer iprnt, character*500 fnalbc2, integer ialb, character(len=*), intent(in) tile_num_ch, integer, dimension(len), intent(in) i_index, integer, dimension(len), intent(in) j_index)
Driver routine that reads in climatological data for a given time, and, if necessary, interpolates it to the model grid.
Parameters
lugb Fortran unit number of GRIB1 climatological data.
iy Cycle year.
im Cycle month.
id Cycle day.
ih Cycle hour.
fh Forecast hour.
len Number of model points to process.
lsoil Number of soil layers.
slmask Model land-sea-ice mask.
fntsfc Climatological SST file.
fnwetc Climatological soil wetness file.
fnsnoc Climatological snow depth file.
fnzorc Climatological roughness length file. Or 'igbp' to use igbp vegetation type lookup table. Or 'sib' to use sib vegeation type lookup table.
fnalbc Climatological snow-free albedo file.
fnaisc Climatological sea ice mask file.
fntg3c Climatological soil substrate temperature file.
fnscvc Climatological snow cover file.
fnsmcc Climatological soil moisture file.
fnstcc Climatological soil temperature file.
fnacnc Climatological sea ice concentration file.
fnvegc Climatological vegetation greenness file.
fnvetc Climatological vegetation type file.
fnsotc Climatological soil type file.
fnvmnc Climatological minimum vegetation greenness file.
fnvmxc Climatological maximum vegetation greenness file.
fnslpc Climatological slope type file.
fnabsc Climatological maximum snow albedo file.
tsfclm Climatological skin temperature/SST on model grid.
tsfcl2 Climatological skin temperature/SST on model grid at time minus deltsfc.
wetclm Climatological soil wetness on model grid.
snoclm Climatological liquid equivalent snow depth on model grid.
zorclm Climatological roughness length on model grid.
albclm Climatological snow-free albedo on model grid.
aisclm Climatological sea ice mask on model grid.
tg3clm Climatological soil substrate temperature on model grid.
cvclm Climatological convective cloud cover on model grid.
cvbclm Climatological convective cloud base on model grid.
cvtclm Climatological convective cloud top on model grid.
cnpclm Climatological canopy water content on model grid.
smcclm Climatological soil moisture on model grid.
stcclm Climatologcial soil temperature on model grid.
sliclm Climatological model land-sea-ice mask.
scvclm Climatological snow cover on model grid.
acnclm Climatological sea ice concentration on model grid.
vegclm Climatological vegetation greenness on model grid.
vetclm Climatological vegetation type on model grid.
sotclm Climatological soil type on model grid.
alfclm Climatological fraction for strongly and weakly zenith angle dependent albedo on model grid.
vmnclm Climatological minimum vegetation greenness on model grid.
vmxclm Climatological maximum vegetation greenness on model grid.
slpclm Climatological slope type on model grid.
absclm Climatological maximum snow albedo on model grid.
kpdtsf Grib parameter number of skin temperature/SST.
kpdwet Grib parameter number of soil wetness.
kpdsno Grib parameter number of liquid equivalent snow depth.
kpdzor Grib parameter number of roughness length.
kpdalb Grib parameter number of snow-free albedo.
kpdais Grib parameter number of sea ice mask.
kpdtg3 Grib parameter number of soil substrate temperature.
kpdscv Grib parameter number of snow cover.
kpdacn Grib parameter number of sea ice concentration.
kpdsmc Grib parameter number of soil moisture.
kpdstc Grib parameter number of soil temperature.
kpdveg Grib parameter number of vegetation greenness.
kpdvet Grib parameter number of vegetation type.
kpdsot Grib parameter number of soil type.
kpdalf Grib parameter number for fraction for strongly and weakly zenith angle dependent albedo.
tsfcl0 Climatological SST at forecast hour 0.
kpdvmn Grib parameter number of minimum vegetation greenness.
kpdvmx Grib parameter number of maximum vegetation greenness.
kpdslp Grib parameter number of slope type.
kpdabs Grib parameter number of maximum snow albedo.
deltsfc Cycling frequency in hours.
lanom When true, do sst anomaly interpolation.
imsk 'i' dimension of the high-res mask used for climatological data without a bitmap.
jmsk 'j' dimension of the high-res mask used for climatological data without a bitmap.
slmskh The high-resolution mask used for climatological data without a bitmap.
outlat Model latitudes
outlon Model longitudes
gaus When true, the high-res mask is on a gaussian grid.
blno Corner point longitude of the high-res mask.
blto Corner point latitude of the high-res mask.
me MPI task number.
lprnt Turn of diagnostic print.
iprnt Index of diagnotic print point.
fnalbc2 File containing climatological fraction for strongly and weakly zenith angle dependent albedo.
ialb Use modis albedo when '1'. Use brigleb when '0'.
tile_num_ch Model tile number to process.
i_index The 'i' indices of the model grid to process.
j_index The 'j' indices of the model grid to process.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 7823 of file sfcsub.F.
References fixrdc(), fixrdc_tile(), machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine count (real (kind=kind_io8), dimension(1) slimsk, real (kind=kind_io8), dimension(1) sno, integer ijmax)
Counts the number of model points that are snow covered land, snow-free land, open water, sea ice, and snow covered sea ice.
Parameters
slimsk The land-sea-ice mask.
sno Snow
ijmax Number of model points to process.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 2626 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by fixrdc_tile(), and read_write_data::read_salclm_gfs_nc().
subroutine dayoyr (integer iyr, integer imo, integer idy, integer ldy)
Compute day of the year based on month and day.
Parameters
iyr Year.
imo Month.
idy Day.
ldy Day of the year.
Author
Mark Iredell NOAA/EMC
Definition at line 2761 of file sfcsub.F.
subroutine filanl (real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len) tsfan2, real (kind=kind_io8), dimension(len) wetanl, real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) zoranl, real (kind=kind_io8), dimension(len,4) albanl, real (kind=kind_io8), dimension(len) aisanl, real (kind=kind_io8), dimension(len) tg3anl, real (kind=kind_io8), dimension (len) cvanl, real (kind=kind_io8), dimension(len) cvbanl, real (kind=kind_io8), dimension(len) cvtanl, real (kind=kind_io8), dimension(len) cnpanl, real (kind=kind_io8), dimension(len,lsoil) smcanl, real (kind=kind_io8), dimension(len,lsoil) stcanl, real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) scvanl, real (kind=kind_io8), dimension(len) veganl, real (kind=kind_io8), dimension(len) vetanl, real (kind=kind_io8), dimension(len) sotanl, real (kind=kind_io8), dimension(len,2) alfanl, real (kind=kind_io8), dimension(len) sihanl, real (kind=kind_io8), dimension(len) sicanl, real (kind=kind_io8), dimension(len) vmnanl, real (kind=kind_io8), dimension(len) vmxanl, real (kind=kind_io8), dimension(len) slpanl, real (kind=kind_io8), dimension(len) absanl, real (kind=kind_io8), dimension(len) tsfclm, real (kind=kind_io8), dimension(len) tsfcl2, real (kind=kind_io8), dimension(len) wetclm, real (kind=kind_io8), dimension(len) snoclm, real (kind=kind_io8), dimension(len) zorclm, real (kind=kind_io8), dimension(len,4) albclm, real (kind=kind_io8), dimension(len) aisclm, real (kind=kind_io8), dimension(len) tg3clm, real (kind=kind_io8), dimension (len) cvclm, real (kind=kind_io8), dimension(len) cvbclm, real (kind=kind_io8), dimension(len) cvtclm, real (kind=kind_io8), dimension(len) cnpclm, real (kind=kind_io8), dimension(len,lsoil) smcclm, real (kind=kind_io8), dimension(len,lsoil) stcclm, real (kind=kind_io8), dimension(len) sliclm, real (kind=kind_io8), dimension(len) scvclm, real (kind=kind_io8), dimension(len) vegclm, real (kind=kind_io8), dimension(len) vetclm, real (kind=kind_io8), dimension(len) sotclm, real (kind=kind_io8), dimension(len,2) alfclm, real (kind=kind_io8), dimension(len) sihclm, real (kind=kind_io8), dimension(len) sicclm, real (kind=kind_io8), dimension(len) vmnclm, real (kind=kind_io8), dimension(len) vmxclm, real (kind=kind_io8), dimension(len) slpclm, real (kind=kind_io8), dimension(len) absclm, integer len, integer lsoil)
Fill in analysis arrays with climatology before reading analysis data.
Parameters
tsfanl Skin temperature/SST analysis on model grid.
tsfan2 Skin temperature/SST analysis on model grid at time minus deltsfc.
wetanl Soil wetness analysis on model grid.
snoanl Liquid equivalent snow depth analysis on model grid.
zoranl Roughness length analysis on model grid.
albanl Snow-free albedo analysis on model grid.
aisanl Sea ice mask analysis on model grid.
tg3anl Soil substrate temperature analysis on model grid.
cvanl Convective cloud cover analysis on model grid.
cvbanl Convective cloud base analysis on model grid.
cvtanl Convective cloud top analysis on model grid.
cnpanl Canopy water content analysis on model grid.
smcanl Soil moisture analysis on model grid.
stcanl Soil temperature analysis on model grid.
slianl Land-sea-ice mask analysis on model grid.
scvanl Snow cover analysis on model grid.
veganl Vegetation greenness analysis on model grid.
vetanl Vegetation type analysis on model grid.
sotanl Soil type analysis on model grid.
alfanl Fraction for strongly and weakly zenith angle dependent albedo analysis on model grid.
sihanl Sea ice depth analysis on model grid.
sicanl Sea ice concentration analysis on model grid.
vmnanl Minimum vegetation greenness analysis on model grid.
vmxanl Maximum vegetation greenness analysis on model grid.
slpanl Slope type analysis on model grid.
absanl Maximum snow albedo analysis on model grid.
tsfclm Climatological skin temperature/SST on model grid.
tsfcl2 Climatological skin temperature/SST on model grid at time minus deltsfc.
wetclm Climatological soil wetness on model grid.
snoclm Climatological liquid equivalent snow depth on model grid.
zorclm Climatological roughness length on model grid.
albclm Climatological snow-free albedo on model grid.
aisclm Climatological sea ice mask on model grid.
tg3clm Climatological soil substrate temperature on model grid.
cvclm Climatological convective cloud cover on model grid.
cvbclm Climatological convective cloud base on model grid.
cvtclm Climatological convective cloud top on model grid.
cnpclm Climatological canopy water content on model grid.
smcclm Climatological soil moisture on model grid.
stcclm Climatologcial soil temperature on model grid.
sliclm Climatological model land-sea-ice mask.
scvclm Climatological snow cover on model grid.
vegclm Climatological vegetation greenness on model grid.
vetclm Climatological vegetation type on model grid.
sotclm Climatological soil type on model grid.
alfclm Climatological fraction for strongly and weakly zenith angle dependent albedo on model grid.
sihclm Climatological sea ice depth on the model grid.
sicclm Climatological sea ice concentration on the model grid.
vmnclm Climatological minimum vegetation greenness on model grid.
vmxclm Climatological maximum vegetation greenness on model grid.
slpclm Climatological slope type on model grid.
absclm Climatological maximum snow albedo on model grid.
len Number of model points to process.
lsoil Number of soil layers.
Author
Shrinivas Moorthi
Definition at line 3857 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine filfcs (real (kind=kind_io8), dimension(len) tsffcs, real (kind=kind_io8), dimension(len) wetfcs, real (kind=kind_io8), dimension(len) snofcs, real (kind=kind_io8), dimension(len) zorfcs, real (kind=kind_io8), dimension(len,4) albfcs, real (kind=kind_io8), dimension(len) tg3fcs, real (kind=kind_io8), dimension (len) cvfcs, real (kind=kind_io8), dimension(len) cvbfcs, real (kind=kind_io8), dimension(len) cvtfcs, real (kind=kind_io8), dimension(len) cnpfcs, real (kind=kind_io8), dimension(len,lsoil) smcfcs, real (kind=kind_io8), dimension(len,lsoil) stcfcs, real (kind=kind_io8), dimension(len) slifcs, real (kind=kind_io8), dimension(len) aisfcs, real (kind=kind_io8), dimension(len) vegfcs, real (kind=kind_io8), dimension(len) vetfcs, real (kind=kind_io8), dimension(len) sotfcs, real (kind=kind_io8), dimension(len,2) alffcs, real (kind=kind_io8), dimension(len) sihfcs, real (kind=kind_io8), dimension(len) sicfcs, real (kind=kind_io8), dimension(len) vmnfcs, real (kind=kind_io8), dimension(len) vmxfcs, real (kind=kind_io8), dimension(len) slpfcs, real (kind=kind_io8), dimension(len) absfcs, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len) wetanl, real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) zoranl, real (kind=kind_io8), dimension(len,4) albanl, real (kind=kind_io8), dimension(len) tg3anl, real (kind=kind_io8), dimension (len) cvanl, real (kind=kind_io8), dimension(len) cvbanl, real (kind=kind_io8), dimension(len) cvtanl, real (kind=kind_io8), dimension(len) cnpanl, real (kind=kind_io8), dimension(len,lsoil) smcanl, real (kind=kind_io8), dimension(len,lsoil) stcanl, real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) aisanl, real (kind=kind_io8), dimension(len) veganl, real (kind=kind_io8), dimension(len) vetanl, real (kind=kind_io8), dimension(len) sotanl, real (kind=kind_io8), dimension(len,2) alfanl, real (kind=kind_io8), dimension(len) sihanl, real (kind=kind_io8), dimension(len) sicanl, real (kind=kind_io8), dimension(len) vmnanl, real (kind=kind_io8), dimension(len) vmxanl, real (kind=kind_io8), dimension(len) slpanl, real (kind=kind_io8), dimension(len) absanl, integer len, integer lsoil)
Fill in model grid guess arrays with analysis values if this is a dead start. All fields are on the model grid.
Parameters
tsffcs First guess skin temperature/SST analysis.
wetfcs First guess soil wetness.
snofcs First guess liquid equivalent snow depth.
zorfcs First guess roughness length.
albfcs First guess snow-free albedo.
tg3fcs First guess soil substrate temperature.
cvfcs First guess cloud cover.
cvbfcs First guess convective cloud bottom.
cvtfcs First guess convective cloud top.
cnpfcs First guess canopy water content.
smcfcs First guess soil moisture.
stcfcs First guess soil temperature.
slifcs First guess land-sea-ice mask.
aisfcs First guess sea ice mask.
vegfcs First guess vegetation greenness.
vetfcs First guess vegetation type.
sotfcs First guess soil type.
alffcs First guess of fraction for strongly and weakly zenith angle dependent albedo.
sihfcs First guess sea ice depth.
sicfcs First guess sea ice concentration.
vmnfcs First guess minimum greenness fraction.
vmxfcs First guess maximum greenness fraction.
slpfcs First guess slope type.
absfcs First guess maximum snow albedo analysis.
tsfanl Skin temperature/SST analysis.
wetanl Soil wetness analysis.
snoanl Liquid equivalent snow depth analysis.
zoranl Roughness length analysis.
albanl Snow-free albedo analysis.
tg3anl Soil substrate temperature analysis.
cvanl Convective cloud cover analysis.
cvbanl Convective cloud base analysis.
cvtanl Convective cloud top analysis.
cnpanl Canopy water content analysis.
smcanl Soil moisture analysis.
stcanl Soil temperature analysis.
slianl Land-sea-ice mask analysis.
aisanl Sea ice mask analysis.
veganl Vegetation greenness analysis.
vetanl Vegetation type analysis.
sotanl Soil type analysis.
alfanl Analysis of fraction for strongly and weakly zenith angle dependent albedo.
sihanl Sea ice depth analysis.
sicanl Sea ice concentration analysis.
vmnanl Minimum greenness fraction analysis.
vmxanl Maximum greenness fraction analysis.
slpanl Slope type analysis.
absanl Maximum snow albedo analysis.
len Number of model points to process.
lsoil Number of soil layers.
Author
Shrinivas Moorthi
Definition at line 4792 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine fixrda (integer lugb, character*500 fngrib, integer kpds5, real (kind=kind_io8), dimension(len) slmask, integer iy, integer im, integer id, integer ih, real (kind=kind_io8) fh, real (kind=kind_io8), dimension(len) gdata, integer len, integer iret, integer imsk, integer jmsk, real (kind=kind_io8), dimension(imsk,jmsk) slmskh, logical gaus, real (kind=kind_io8) blno, real (kind=kind_io8) blto, real (kind=kind_io8), dimension(len) outlat, real (kind=kind_io8), dimension(len) outlon, integer me)
Read in grib1 analysis data for the requested date and horizontally interpolate to the model grid. If data not found for the requested date, a backwards search is performed.
Parameters
lugb Fortran unit number of the grib1 analysis data file.
fngrib The name of the grib1 analysis data file.
kpds5 The grib1 parameter number of the requested data.
slmask Model land-sea-ice mask.
iy Year.
im Month.
id Day.
ih Hour.
fh Forecast hour.
gdata The analysis data interpolated to the model grid.
len The number of model points to process.
iret Return code. '0' is success.
imsk 'i' dimension of the high-res mask used for input analysis data without a bitmap.
jmsk 'j' dimension of the high-res mask used for input analysis data without a bitmap.
slmskh The high-resolution mask used for input analysis data witouth a bitmap.
gaus When true, the high-res mask is on a gaussian grid.
blno Corner point longitude of the high-res mask.
blto Corner point latitude of the high-res mask.
outlat Model latitudes.
outlon Model longitudes.
me MPI task number
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 9391 of file sfcsub.F.
References getarea(), machine::kind_io4, machine::kind_io8, la2ga(), sfccyc_module::mdata, setrmsk(), and subst().
Referenced by analy().
subroutine fixrdc (integer lugb, character*500 fngrib, integer kpds5, integer, intent(in) kpds7, integer mon, real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8), dimension(len) gdata, integer len, integer iret, integer imsk, integer jmsk, real (kind=kind_io8), dimension(imsk,jmsk) slmskh, logical gaus, real (kind=kind_io8) blno, real (kind=kind_io8) blto, real (kind=kind_io8), dimension(len) outlat, real (kind=kind_io8), dimension(len) outlon, integer me)
Read in grib1 climatology data for a specific month and and horizontally interpolate to the model grid.
Parameters
lugb Fortran unit number of the grib1 climatology data file.
fngrib The name of the grib1 climatology data file.
kpds5 The grib1 parameter number of the requested data.
kpds7 The grib1 level indicator of the requested data.
mon The requested month.
slmask Model land-sea-ice mask.
gdata The climatology data interpolated to the model grid.
len The number of model points to process.
iret Return code. '0' is success.
imsk 'i' dimension of the high-res mask used for input data without a bitmap.
jmsk 'j' dimension of the high-res mask used for input data without a bitmap.
slmskh The high-resolution mask used for input data witouth a bitmap.
gaus When true, the high-res mask is on a gaussian grid.
blno Corner point longitude of the high-res mask.
blto Corner point latitude of the high-res mask.
outlat Model latitudes.
outlon Model longitudes.
me MPI task number
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 9190 of file sfcsub.F.
References getarea(), machine::kind_io4, machine::kind_io8, la2ga(), sfccyc_module::mdata, setrmsk(), and subst().
Referenced by clima(), and sfccycle().
subroutine fixrdc_tile (character(len=*), intent(in) filename_raw, character(len=*), intent(in) tile_num_ch, integer, dimension(npts), intent(in) i_index, integer, dimension(npts), intent(in) j_index, integer, intent(in) kpds, real(kind_io8), dimension(npts), intent(out) var, integer, intent(in) mon, integer, intent(in) npts, integer, intent(in) me)
Reads in climatological data on the model grid tile for a given month. Unlike fixrdc, this routine assumes the input data is already interpolated to the model tile. The climatological data must be NetCDF.
Parameters
filename_raw The name of the climatological file.
tile_num_ch The tile number to be processed.
i_index The 'i' indices of the model grid to process.
j_index The 'j' indices of the model grid to process.
kpds Parameter code for the data.
var The climatological data on the model grid.
mon Which month of data to read.
npts Number of model points to process.
me MPI task number.
Author
George Gayno NOAA/EMC
Definition at line 9009 of file sfcsub.F.
References count(), machine::kind_io8, and netcdf_err().
Referenced by clima().
subroutine fixrdg (integer lugb, integer idim, integer jdim, character*(*) fngrib, integer kpds5, real (kind=kind_io8), dimension(idim*jdim) gdata, logical gaus, real (kind=kind_io8) blno, real (kind=kind_io8) blto, integer me)
Read a GRIB1 file. Return the requested data record and some grid specifications.
Parameters
lugb Fortran unit number of the grib file.
idim 'i' dimension of the data.
jdim 'j' dimension of the data.
fngrib Name of the grib file.
kpds5 The grib1 parameter number for the requested field.
gdata The requested data.
gaus When true, grid is gaussian.
blno Corner point longitude of grid.
blto Corner point latitude of grid.
me MPI task number.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 2840 of file sfcsub.F.
References machine::kind_io4, machine::kind_io8, and sfccyc_module::mdata.
Referenced by hmskrd().
subroutine ga2la (real (kind=kind_io8), dimension (imxin,jmxin) gauin, integer imxin, integer jmxin, real (kind=kind_io8), dimension(imxout,jmxout) regout, integer imxout, integer jmxout, real (kind=kind_io8) wlon, real (kind=kind_io8) rnlat, real (kind=kind_io8), dimension(imxout) rlnout, real (kind=kind_io8), dimension(jmxout) rltout, logical gaus, real (kind=kind_io8) blno, real (kind=kind_io8) blto)
Interpolation from lat/lon or gaussian grid to a lat/lon grid.
Parameters
gauin Input data.
imxin 'i' dimension of input data.
jmxin 'j' dimension of input data.
regout Output data.
imxout 'i' dimension of output data.
jmxout 'j' dimension of output data.
wlon Longitude of west boundary of input data.
rnlat Latitude of north row of input data.
rlnout Longitudes on output data grid.
rltout Latitudes on output data grid.
gaus Is input data on gaussian grid?
blno Corner point longitude of input data.
blto Corner point latitude of input data.
Author
Shrinivas Moorthi
Definition at line 7383 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by setrmsk().
subroutine gaulat (real (kind=kind_io8), dimension(k) gaul, integer k)
Calculate gaussian latitudes.
Parameters
gaul Gaussian latitudes
k Number of latitudes
Author
Shrinivas Moorthi
Definition at line 7662 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
subroutine getarea (integer, dimension(22) kgds, real (kind=kind_io8) dlat, real (kind=kind_io8) dlon, real (kind=kind_io8) rslat, real (kind=kind_io8) rnlat, real (kind=kind_io8) wlon, real (kind=kind_io8) elon, logical ijordr, integer me)
For a given GRIB1 grid description section array, determine some grid specifications.
Parameters
kgds GRIB1 grid description section array.
dlat Grid resolution in the 'j' direction.
dlon Grid resolution in the 'i' direction.
rslat Latitude of the southern row of data.
rnlat Latitude of the northern row of data.
wlon Longitude of the western column of data.
elon Longitude of the eastern column of data.
ijordr When false, adjacent points in the 'i' direction are consecutive. Otherwise, 'j' points are consecutive.
me MPI rank number.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 2970 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by fixrda(), and fixrdc().
subroutine getscv (real (kind=kind_io8), dimension(len) snofld, real (kind=kind_io8), dimension(len) scvfld, integer len)
Set snow cover flag based on snow depth.
Parameters
snofld Snow depth.
scvfld Snow cover.
len Number of model points to process.
Author
Shrinivas Moorthi
Definition at line 6460 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine getsmc (real (kind=kind_io8), dimension(len) wetfld, integer len, integer lsoil, real (kind=kind_io8), dimension(len,lsoil) smcfld, integer me)
Set soil moisture from soil wetness.
Parameters
wetfld Soil wetness
len Number of model points to process.
lsoil Number of soil layers.
smcfld Soil moisture.
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 6526 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine getstc (real (kind=kind_io8), dimension(len) tsffld, real (kind=kind_io8), dimension(len) tg3fld, real (kind=kind_io8), dimension(len) slifld, integer len, integer lsoil, real (kind=kind_io8), dimension(len,lsoil) stcfld, real (kind=kind_io8) tsfimx)
Set soil temperature and sea ice column temperature.
Parameters
tsffld Skin temperature/SST.
tg3fld Soil substrate temperature.
slifld Land-sea-ice mask.
len Number of model points to process.
lsoil Number of soil layers.
stcfld Soil/sea ice column temperature.
tsfimx Freezing point of sea water.
Author
Shrinivas Moorthi
Definition at line 6484 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle(), and usesgt().
subroutine hmskrd (integer lugb, integer imsk, integer jmsk, character*500 fnmskh, integer kpds5, real (kind=kind_io8), dimension(mdata) slmskh, logical gausm, real (kind=kind_io8) blnmsk, real (kind=kind_io8) bltmsk, integer me)
Read a high-resolution land mask. It will be used as a surrogate for GRIB input data without a bitmap. This is NOT the model land mask. This mask file is GRIB1.
Parameters
lugb Fortran unit number of the mask file.
imsk 'i' dimension of the mask.
jmsk 'j' dimension of the mask.
fnmskh Name of the mask file.
kpds5 GRIB1 parameter number for mask.
slmskh The high-resolution mask.
gausm When true, mask is on a gaussian grid.
blnmsk Corner point longitude of the mask grid.
bltmsk Corner point latitude of the mask grid.
me MPI task number.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 2792 of file sfcsub.F.
References fixrdg(), machine::kind_io4, machine::kind_io8, sfccyc_module::mdata, sfccyc_module::xdata, and sfccyc_module::ydata.
Referenced by sfccycle().
subroutine la2ga (real (kind=kind_io8), dimension (imxin,jmxin) regin, integer imxin, integer jmxin, real (kind=kind_io8), dimension(imxin) rinlon, real (kind=kind_io8), dimension(jmxin) rinlat, real (kind=kind_io8) rlon, real (kind=kind_io8) rlat, integer inttyp, real (kind=kind_io8), dimension(len) gauout, integer len, logical lmask, real (kind=kind_io8), dimension(imxin,jmxin) rslmsk, real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8), dimension(len) outlat, real (kind=kind_io8), dimension(len) outlon, integer me)
Interpolate data from a lat/lon grid to the model grid.
Parameters
regin Input data.
imxin 'i' dimension of input data.
jmxin 'j' dimension of input data.
rinlon
rinlat
rlon
rlat
inttyp
gauout The interpolated data on the model grid.
len Number of model points to process.
lmask
rslmsk
slmask Model land-sea-ice mask.
outlat Latitudes on the model grid.
outlon Longitudes on the model grid.
me MPI task number.
Author
Shrinivas Moorth
Definition at line 3213 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by fixrda(), and fixrdc().
subroutine landtyp (real (kind=kind_io8), dimension(len) vegtype, real (kind=kind_io8), dimension(len) soiltype, real (kind=kind_io8), dimension(len) slptype, real (kind=kind_io8), dimension(len) slmask, integer len)
Set vegetation, soil and slope type at undefined model points.
Parameters
vegtype Vegetation type
soiltype Soil type
slptype Slope type
slmask Land-sea-ice mask.
len Number of model points to process.
Author
Shrinivas Moorthi
Definition at line 7638 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine maxmin (real (kind=kind_io8), dimension(imax,kmax) f, integer imax, integer kmax)
Compute the maxmimum and minimum of a field.
Parameters
f The field to check.
imax The horizontal dimension of the field.
kmax Number of vertical levels of the field.
Author
Shrinivas Moorthi
Definition at line 3757 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
subroutine merge (integer len, integer lsoil, integer iy, integer im, integer id, integer ih, real (kind=kind_io8) fh, real (kind=kind_io8) deltsfc, real (kind=kind_io8), dimension(len) sihfcs, real (kind=kind_io8), dimension(len) sicfcs, real (kind=kind_io8), dimension(len) vmnfcs, real (kind=kind_io8), dimension(len) vmxfcs, real (kind=kind_io8), dimension(len) slpfcs, real (kind=kind_io8), dimension(len) absfcs, real (kind=kind_io8), dimension(len) tsffcs, real (kind=kind_io8), dimension(len) wetfcs, real (kind=kind_io8), dimension(len) snofcs, real (kind=kind_io8), dimension(len) zorfcs, real (kind=kind_io8), dimension(len,4) albfcs, real (kind=kind_io8), dimension(len) aisfcs, real (kind=kind_io8), dimension (len) cvfcs, real (kind=kind_io8), dimension(len) cvbfcs, real (kind=kind_io8), dimension(len) cvtfcs, real (kind=kind_io8), dimension(len) cnpfcs, real (kind=kind_io8), dimension(len,lsoil) smcfcs, real (kind=kind_io8), dimension(len,lsoil) stcfcs, real (kind=kind_io8), dimension(len) slifcs, real (kind=kind_io8), dimension(len) vegfcs, real (kind=kind_io8), dimension(len) vetfcs, real (kind=kind_io8), dimension(len) sotfcs, real (kind=kind_io8), dimension(len,2) alffcs, real (kind=kind_io8), dimension(len) sihanl, real (kind=kind_io8), dimension(len) sicanl, real (kind=kind_io8), dimension(len) vmnanl, real (kind=kind_io8), dimension(len) vmxanl, real (kind=kind_io8), dimension(len) slpanl, real (kind=kind_io8), dimension(len) absanl, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len) tsfan2, real (kind=kind_io8), dimension(len) wetanl, real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) zoranl, real (kind=kind_io8), dimension(len,4) albanl, real (kind=kind_io8), dimension(len) aisanl, real (kind=kind_io8), dimension (len) cvanl, real (kind=kind_io8), dimension(len) cvbanl, real (kind=kind_io8), dimension(len) cvtanl, real (kind=kind_io8), dimension(len) cnpanl, real (kind=kind_io8), dimension(len,lsoil) smcanl, real (kind=kind_io8), dimension(len,lsoil) stcanl, real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) veganl, real (kind=kind_io8), dimension(len) vetanl, real (kind=kind_io8), dimension(len) sotanl, real (kind=kind_io8), dimension(len,2) alfanl, real (kind=kind_io8) ctsfl, real (kind=kind_io8) calbl, real (kind=kind_io8) caisl, real (kind=kind_io8) csnol, real (kind=kind_io8), dimension(lsoil) csmcl, real (kind=kind_io8) czorl, real (kind=kind_io8), dimension(lsoil) cstcl, real (kind=kind_io8) cvegl, real (kind=kind_io8) ctsfs, real (kind=kind_io8) calbs, real (kind=kind_io8) caiss, real (kind=kind_io8) csnos, real (kind=kind_io8), dimension(lsoil) csmcs, real (kind=kind_io8) czors, real (kind=kind_io8), dimension(lsoil) cstcs, real (kind=kind_io8) cvegs, real (kind=kind_io8) ccv, real (kind=kind_io8) ccvb, real (kind=kind_io8) ccvt, real (kind=kind_io8) ccnp, real (kind=kind_io8) cvetl, real (kind=kind_io8) cvets, real (kind=kind_io8) csotl, real (kind=kind_io8) csots, real (kind=kind_io8) calfl, real (kind=kind_io8) calfs, real (kind=kind_io8) csihl, real (kind=kind_io8) csihs, real (kind=kind_io8) csicl, real (kind=kind_io8) csics, real (kind=kind_io8) cvmnl, real (kind=kind_io8) cvmns, real (kind=kind_io8) cvmxl, real (kind=kind_io8) cvmxs, real (kind=kind_io8) cslpl, real (kind=kind_io8) cslps, real (kind=kind_io8) cabsl, real (kind=kind_io8) cabss, integer irttsf, integer irtwet, integer irtsno, integer irtzor, integer irtalb, integer irtais, integer irttg3, integer irtscv, integer irtacn, integer irtsmc, integer irtstc, integer irtveg, integer irtvmn, integer irtvmx, integer irtslp, integer irtabs, integer irtvet, integer irtsot, integer irtalf, logical, intent(in) landice, integer me)
Blend the model forecast (or first guess) fields with the analysis/climatology. The forecast/first guess variables are named with 'fcs'. The analysis/climatology variables are named with 'anl'. On output, the blended fields are stored in the 'anl' variables.
Parameters
len Number of model points to process.
lsoil Number of soil layers.
iy Cycle year.
im Cycle month.
id Cycle day.
ih Cycle hour.
fh Forecast hour.
deltsfc Cycling frequency in hours.
sihfcs First guess sea ice depth.
sicfcs First guess sea ice concentration.
vmnfcs First guess minimum vegetation greenness.
vmxfcs First guess maximum vegetation greenness.
slpfcs First guess slope type.
absfcs First guess maximum snow albedo.
tsffcs First guess skin temperature/SST.
wetfcs First guess soil wetness.
snofcs First guess liquid equivalent snow depth.
zorfcs First guess roughness length.
albfcs First guess snow free albedo.
aisfcs First guess ice.
cvfcs First guess convective cloud cover.
cvbfcs First guess convective cloud bottom.
cvtfcs First guess convective cloud top.
cnpfcs First guess canopy water content.
smcfcs First guess soil moisture.
stcfcs First guess soil/ice temperature.
slifcs First guess land-sea-ice mask.
vegfcs First guess vegetation greenness.
vetfcs First guess vegetation type.
sotfcs First guess soil type.
alffcs First guess strong/weak zenith angle dependent albedo.
sihanl Blended sea ice depth.
sicanl Blended sea ice concentration.
vmnanl Blended minimum vegetation greenness.
vmxanl Blended maximum vegetation greenness.
slpanl Blended slope type.
absanl Blended maximum snow albedo.
tsfanl Blended skin temperature/SST.
tsfan2 Not used.
wetanl Blended soil wetness.
snoanl Blended liquid equivalent snow depth.
zoranl Blended roughness length.
albanl Blended snow-free albedo.
aisanl Blended ice.
cvanl Blended convective cloud cover.
cvbanl Blended convective cloud base.
cvtanl Blended convective cloud top.
cnpanl Blended canopy moisture content.
smcanl Blended soil moisture.
stcanl Blended soil/ice temperature.
slianl Blended land-sea-ice mask.
veganl Blended vegetation greenness.
vetanl Blended vegetation type.
sotanl Blended soil type.
alfanl Blended strong/weak zenith angle dependent albedo.
ctsfl Merging coefficient for skin temperature.
calbl Merging coefficient for snow-free albedo at land points.
caisl Merging coefficient for sea ice at land points.
csnol Merging coefficient for snow at land points.
csmcl Merging coefficient for soil moisture at land points.
czorl Merging coefficient for roughness length at land points.
cstcl Merging coefficient for soil temperature at land points.
cvegl Merging coefficient for vegetation greenness at land points.
ctsfs Merging coefficient for SST.
calbs Merging coefficient for snow-free albedo at water points.
caiss Merging coefficient for sea ice at water points.
csnos Merging coefficient for snow at water points.
csmcs Merging coefficient for soil moisture at water points.
czors Merging coefficient for roughness length at water points.
cstcs Merging coefficient for sea ice temperature at water points.
cvegs Merging coefficient for vegetation greenness at water points.
ccv Merging coefficient for convective cloud cover.
ccvb Merging coefficient for covective cloud bottom.
ccvt Merging coefficient for covective cloud top.
ccnp Merging coefficient for canopy moisture.
cvetl Merging coefficient for vegetation type at land points.
cvets Merging coefficient for vegetation type at water points.
csotl Merging coefficient for soil type at land points.
csots Merging coefficient for soil type at water points.
calfl Merging coefficient for strong/weak zenith angle dependent albedo at land points.
calfs Merging coefficient for strong/weak zenith angle dependent albedo at water points.
csihl Merging coefficient for sea ice depth at land points.
csihs Merging coefficient for sea ice depth at water points.
csicl Merging coefficient for sea ice concentration at land points.
csics Merging coefficient for sea ice concentration at water points.
cvmnl Merging coefficient for minimum vegetation greenness at land points.
cvmns Merging coefficient for minimum vegetation greenness at water points.
cvmxl Merging coefficient for maximum vegetation greenness at land points.
cvmxs Merging coefficient for maximum vegetation greenness at water points.
cslpl Merging coefficient for slope type at land points.
cslps Merging coefficient for slope type at water points.
cabsl Merging coefficient for maximum snow albedo at land points.
cabss Merging coefficient for maximum snow albedo at water points.
irttsf Return code from read of skin temperature/SST analysis file.
irtwet Return code from read of soil wetness analysis file.
irtsno Return code from read of snow analysis file.
irtzor Return code from read of roughness length file.
irtalb Return code from read of snow-free albedo analysis file.
irtais Return code from read of ice mask analysis file.
irttg3 Return code from read of soil substrate temperature analysis file.
irtscv Return code from read of snow cover analysis file.
irtacn Return code from read of sea ice concentration analysis file.
irtsmc Return code from read of soil moisture analysis file.
irtstc Return code from read of soil temperature analysis file.
irtveg Return code from read of vegetation greenness analysis file.
irtvmn Return code from read of minimum vegetation greenness analysis file.
irtvmx Return code from read of maximum vegetation greenness analysis file.
irtslp Return code from read of slope type analysis file.
irtabs Return code from read of maximum snow albedo analysis file.
irtvet Return code from read of vegetation type analysis file.
irtsot Return code from read of soil type analysis file.
irtalf Return code from read of file containing fraction for strongly and weakly zenith angle dependent albedo.
landice Permanent land ice flag.
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 5190 of file sfcsub.F.
References machine::kind_io4, machine::kind_io8, sfccyc_module::soil_type_landice, and sfccyc_module::veg_type_landice.
Referenced by sfccycle().
subroutine monitr (character(len=*) lfld, real (kind=kind_io8), dimension(ijmax) fld, real (kind=kind_io8), dimension(ijmax) slimsk, real (kind=kind_io8), dimension(ijmax) sno, integer ijmax)
Determine the maximum and minimum values of a surface field at snow-free and snow covered land, open water, and snow-free and snow covered sea ice.
Parameters
lfld The name of the surface field to monitory.
fld The surface field to monitor.
slimsk Land-sea-ice mask.
sno Snow.
ijmax Number of model points to process.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 2689 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine netcdf_err (integer, intent(in) error)
Print the error message for a given netCDF return code.
Parameters
error
Author
Xu Li NOAA/EMC
Definition at line 9151 of file sfcsub.F.
Referenced by fixrdc_tile().
subroutine newice (real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) slifcs, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len) tsffcs, integer len, integer lsoil, real (kind=kind_io8) sihnew, real (kind=kind_io8) sicnew, real (kind=kind_io8), dimension(len) sihanl, real (kind=kind_io8), dimension(len) sicanl, real (kind=kind_io8), dimension(len,4) albanl, real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) zoranl, real (kind=kind_io8), dimension(len,lsoil) smcanl, real (kind=kind_io8), dimension(len,lsoil) stcanl, real (kind=kind_io8) albsea, real (kind=kind_io8) snosea, real (kind=kind_io8) zorsea, real (kind=kind_io8) smcsea, real (kind=kind_io8) smcice, real (kind=kind_io8) tsfmin, real (kind=kind_io8) tsfice, real (kind=kind_io8) albice, real (kind=kind_io8) zorice, real (kind=kind_io8) tgice, real (kind=kind_io8), dimension(len) rla, real (kind=kind_io8), dimension(len) rlo, integer me)
Adjust surface fields when ice melts or forms.
Parameters
slianl Land-sea-ice mask.
slifcs First guess land-sea-ice mask.
tsfanl Skin temperature/SST.
tsffcs First guess skin temperature/SST.
len Number of model points to process.
lsoil Number of soil layers.
sihnew Sea ice depth for new ice.
sicnew Sea ice concentration for new ice.
sihanl Sea ice depth.
sicanl Sea ice concentration.
albanl Snow-free albedo.
snoanl Liquid equivalent snow depth.
zoranl Roughness length.
smcanl Soil moisture
stcanl Soil temperature
albsea Albedo at open water.
snosea Snow at open water.
zorsea Roughness length at open water.
smcsea Soil moisture at open water.
smcice Soil moisture at ice.
tsfmin SST at open water.
tsfice Skin temperature at ice.
albice Ice albedo.
zorice Roughness length of ice.
tgice Freezing point of salt water.
rla Model latitudes.
rlo Model longitudes.
me MPI task number.
Author
Shrinivas Moorthi
Xingen Wu
Definition at line 5674 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine qcbyfc (real (kind=kind_io8), dimension(len) tsffcs, real (kind=kind_io8), dimension(len) snofcs, real (kind=kind_io8) qctsfs, real (kind=kind_io8) qcsnos, real (kind=kind_io8) qctsfi, integer len, integer lsoil, real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) aisanl, real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len,4) albanl, real (kind=kind_io8), dimension(len) zoranl, real (kind=kind_io8), dimension(len,lsoil) smcanl, real (kind=kind_io8), dimension(len,lsoil) smcclm, real (kind=kind_io8) tsfsmx, real (kind=kind_io8) albomx, real (kind=kind_io8) zoromx, integer me)
Quality control analysis fields using the first guess.
Parameters
tsffcs First guess skin temperature/SST.
snofcs First guess snow.
qctsfs Surface temperature above which no snow allowed.
qcsnos Snow depth above which snow must exits.
qctsfi SST above which sea ice is not allowed.
len Number of model points to process.
lsoil Number of soil layers.
snoanl Snow analysis.
aisanl Ice mask.
slianl Land-sea-ice mask.
tsfanl Skin temperature/SST analysis.
albanl Snow-free albedo analysis.
zoranl Roughness length analysis.
smcanl Soil moisture analysis.
smcclm Soil moisture climatology.
tsfsmx Not used.
albomx Snow-free albedo at open water.
zoromx Roughness length at open water.
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 6763 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine qcmxice (real (kind=kind_io8), dimension(len) glacir, real (kind=kind_io8), dimension(len) amxice, integer len, integer me)
Quality control maximum ice extent.
Parameters
glacir Glacial flag
amxice Maximum ice extent.
len Number of model points to process.
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 6646 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine qcmxmn (character*8 ttl, real (kind=kind_io8), dimension(len) fld, real (kind=kind_io8), dimension(len) slimsk, real (kind=kind_io8), dimension(len) sno, logical, dimension(len) iceflg, real (kind=kind_io8) fldlmx, real (kind=kind_io8) fldlmn, real (kind=kind_io8) fldomx, real (kind=kind_io8) fldomn, real (kind=kind_io8) fldimx, real (kind=kind_io8) fldimn, real (kind=kind_io8) fldjmx, real (kind=kind_io8) fldjmn, real (kind=kind_io8) fldsmx, real (kind=kind_io8) fldsmn, real (kind=kind_io8) epsfld, real (kind=kind_io8), dimension(len) rla, real (kind=kind_io8), dimension(len) rlo, integer len, integer mode, real (kind=kind_io8) percrit, logical lgchek, integer me)
Range check a field. The check is a function of whether the point is land, water or ice.
Parameters
ttl Name of field.
fld The field array to be ranged checked.
slimsk The land-sea-ice mask.
sno Snow.
iceflg When true, check ice points.
fldlmx Maximum allowable value at snow-free land.
fldlmn Minimum allowable value at snow-free land.
fldomx Maximum allowable value at open water.
fldomn Minimum allowable value at open water.
fldimx Maximum allowable value at snow-free ice.
fldimn Minimum allowable value at snow-free ice.
fldjmx Maximum allowable value at snow covered ice.
fldjmn Minimum allowable value at snow covered ice.
fldsmx Maximum allowable value at snow covered land.
fldsmn Minimum allowable value at snow covered land.
epsfld Difference from the max/min allowable value at which the field is updated.
rla Latitude of the points to process.
rlo Longitude of the points to process.
len Number of points to process.
mode When '1', update the field. When not '1', run routine in diagnostic mode.
percrit Critical percentage of 'bad' points required for abort.
lgchek When true, abort when a critical percentage of points are outside acceptable range.
me MPI task number.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 6018 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine qcsice (real (kind=kind_io8), dimension(len) ais, real (kind=kind_io8), dimension(len) glacir, real (kind=kind_io8), dimension(len) amxice, real (kind=kind_io8) aicice, real (kind=kind_io8) aicsea, real (kind=kind_io8) sllnd, real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8), dimension(len) rla, real (kind=kind_io8), dimension(len) rlo, integer len, integer me)
Check the sea ice cover mask against the land-sea mask.
Parameters
ais Sea ice cover mask.
glacir Glacial flag
amxice Maximum ice extent.
aicice Ice indicator.
aicsea Open water indicator.
sllnd Land indicator.
slmask Land-sea-ice mask.
rla Model latitudes
rlo Model longitudes
len Number of model points to process.
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 5842 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine qcsli (real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) slifcs, integer len, integer me)
Check consistency between the forecast and analysis land-sea-ice mask.
Parameters
slianl Analysis mask.
slifcs Forecast mask.
len Number of model points to process.
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 6675 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine qcsnow (real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8), dimension(len) aisanl, real (kind=kind_io8), dimension(len) glacir, integer len, real (kind=kind_io8) snoval, logical, intent(in) landice, integer me)
Quality control snow at the model points.
Parameters
snoanl Model snow to be qc'd.
slmask Land-sea-ice mask.
aisanl Ice mask.
glacir Permanent glacial point when '1'.
len Number of model points to process.
snoval Minimum snow depth at glacial points.
landice Is the point permanent land ice?
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 5781 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine rof01 (real (kind=kind_io8), dimension(len) aisfld, integer len, character*2 op, real (kind=kind_io8) crit)
Round a field up to one or down to zero.
Parameters
aisfld The field to adjust.
len Number of model points to process.
op Operation on field.
crit Critical value above/below the field is rounded.
Author
Shrinivas Moorthi
Definition at line 4889 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by setrmsk(), and sfccycle().
subroutine scale (real (kind=kind_io8), dimension(len) fld, integer len, real (kind=kind_io8) scl)
Multiply a field by a scaling factor.
Parameters
fld The field to scale.
len Number of model points to process.
scl Scaling factor.
Author
Shrinivas Moorthi
Definition at line 5975 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine setlsi (real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8), dimension(len) aisfld, integer len, real (kind=kind_io8) aicice, real (kind=kind_io8), dimension(len) slifld)
Set land-sea-ice mask at sea ice.
Parameters
slmask The model mask on input.
aisfld The ice mask on the model grid.
len Number of model points to process.
aicice Ice concentration theshold for an ice point.
slifld The model mask with sea ice added.
Author
Shrinivas Moorthi
Definition at line 5950 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine setrmsk (integer kpds5, real (kind=kind_io8), dimension(igaul,jgaul) slmask, integer igaul, integer jgaul, real (kind=kind_io8) wlon, real (kind=kind_io8) rnlat, real (kind=kind_io8), dimension(imax,jmax) data, integer imax, integer jmax, real (kind=kind_io8), dimension(imax) rlnout, real (kind=kind_io8), dimension(jmax) rltout, logical lmask, real (kind=kind_io8), dimension(imax,jmax) rslmsk, logical gaus, real (kind=kind_io8) blno, real (kind=kind_io8) blto, integer kgds1, integer, intent(in) kpds4, logical*1, dimension(imax,jmax), intent(in) lbms)
Set the mask for the input data. (Not the model mask). The mask is determined from the input data bitmap or by interpolating a high-resolution mask to the input data grid. Note: not all data has a mask.
Parameters
kpds5 Grib parameter number.
slmask High-resolution mask.
igaul 'i' dimension of the high-res mask.
jgaul 'j' dimension of the high-res mask.
wlon Longitude of 'west' boundary of input data.
rnlat Latitude of north row of input data.
data The input data.
imax 'i' dimension of input grid.
jmax 'j' dimension of input grid.
rlnout Longitudes on input data grid.
rltout Latitudes on input data grid.
lmask True, when input data has a mask.
rslmsk The mask of the input data grid.
gaus Is high-resolution mask on a gaussian grid.
blno Corner point longitude of the high-res mask.
blto Corner point longitude of the high-res mask.
kgds1 Grib indicator for grid type.
kpds4 Grib indicator for bitmap.
lbms Bitmap of input data.
Author
Shrinivas Moorthi
Definition at line 6885 of file sfcsub.F.
References ga2la(), machine::kind_io4, machine::kind_io8, sfccyc_module::kpdabs, sfccyc_module::kpdacn, sfccyc_module::kpdais, sfccyc_module::kpdalb, sfccyc_module::kpdalf, sfccyc_module::kpdgla, sfccyc_module::kpdmxi, sfccyc_module::kpdscv, sfccyc_module::kpdslp, sfccyc_module::kpdsmc, sfccyc_module::kpdsnd, sfccyc_module::kpdsno, sfccyc_module::kpdsot, sfccyc_module::kpdtg3, sfccyc_module::kpdtsf, sfccyc_module::kpdveg, sfccyc_module::kpdvet, sfccyc_module::kpdvmn, sfccyc_module::kpdvmx, sfccyc_module::kpdwet, sfccyc_module::kpdzor, and rof01().
Referenced by fixrda(), and fixrdc().
subroutine setzro (real (kind=kind_io8), dimension(len) fld, real (kind=kind_io8) eps, integer len)
Set a field to zero if it is less than a threshold.
Parameters
fld Field to set.
eps Threshold.
len Number of model points to process.
Author
Shrinivas Moorthi
Definition at line 6442 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine sfccycle (integer lugb, integer len, integer lsoil, real (kind=kind_io8), dimension(len) sig1t, real (kind=kind_io8) deltsfc, integer iy, integer im, integer id, integer ih, real (kind=kind_io8) fh, real (kind=kind_io8), dimension(len) rla, real (kind=kind_io8), dimension(len) rlo, real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8), dimension(len) orog, real (kind=kind_io8), dimension(len) orog_uf, logical use_ufo, logical nst_anl, real (kind=kind_io8), dimension(len) sihfcs, real (kind=kind_io8), dimension(len) sicfcs, real (kind=kind_io8), dimension(len) sitfcs, real (kind=kind_io8), dimension(len) swdfcs, real (kind=kind_io8), dimension(len,lsoil) slcfcs, real (kind=kind_io8), dimension(len) vmnfcs, real (kind=kind_io8), dimension(len) vmxfcs, real (kind=kind_io8), dimension(len) slpfcs, real (kind=kind_io8), dimension(len) absfcs, real (kind=kind_io8), dimension(len) tsffcs, real (kind=kind_io8), dimension(len) snofcs, real (kind=kind_io8), dimension(len) zorfcs, real (kind=kind_io8), dimension(len,4) albfcs, real (kind=kind_io8), dimension(len) tg3fcs, real (kind=kind_io8), dimension(len) cnpfcs, real (kind=kind_io8), dimension(len,lsoil) smcfcs, real (kind=kind_io8), dimension(len,lsoil) stcfcs, real (kind=kind_io8), dimension(len) slifcs, real (kind=kind_io8), dimension(len) aisfcs, real (kind=kind_io8), dimension(len) vegfcs, real (kind=kind_io8), dimension(len) vetfcs, real (kind=kind_io8), dimension(len) sotfcs, real (kind=kind_io8), dimension(len,2) alffcs, real (kind=kind_io8), dimension (len) cvfcs, real (kind=kind_io8), dimension(len) cvbfcs, real (kind=kind_io8), dimension(len) cvtfcs, integer me, integer nlunit, integer sz_nml, character(len=*), dimension(sz_nml), intent(in) input_nml_file, integer ialb, integer isot, integer ivegsrc, character(len=*), intent(in) tile_num_ch, integer, dimension(len), intent(in) i_index, integer, dimension(len), intent(in) j_index)
Surface cycling driver routine. Update 'first guess' surface fields with either analysis or climatological data.
Parameters
lugb Fortran unit number used to read data files.
len Number of model points to process.
lsoil Number of soil layers.
sig1t Sigma level 1 temperature for dead start.
deltsfc Cycling frequency in hours.
iy Year of initial state.
im Month of initial state.
id Day of initial state.
ih Hour of initial state.
fh Forecast hour.
rla Latitude of model points.
rlo Longitude of model points.
slmask Model land-sea mask without ice flag.
orog Filtered orography on model grid.
orog_uf Unfiltered orography on model grid.
use_ufo When true, adjust sst and soil substrate temperature for differences between filtered and unfiltered terrain.
nst_anl Set to true when using nst model.
sihfcs Sea ice thickness on model grid.
sicfcs Sea ice concentration on model grid.
sitfcs Sea ice skin temperature on model grid.
swdfcs Physical snow depth on model grid.
slcfcs Liquid portion of volumentric soil moisture on model grid.
vmnfcs Minimum greenness fraction of model grid.
vmxfcs Maximum greenness fraction of model grid.
slpfcs Slope type on model grid.
absfcs Maximum snow albedo on model grid.
tsffcs Skin temperature/SST on model grid.
snofcs Liquid equivalent snow depth on model grid.
zorfcs Roughness length on model grid.
albfcs Snow-free albedo on model grid.
tg3fcs Soil substrate temperature on model grid.
cnpfcs Canopy moisture content on model grid.
smcfcs Total volumetric soil moisture on model grid.
stcfcs Soil/ice depth temperature on model grid.
slifcs Model land-sea mask including ice flag.
aisfcs Model ice mask.
vegfcs Vegetation greenness on model grid.
vetfcs Vegetation type on model grid.
sotfcs Soil type on model grid.
alffcs Fraction for strongly and weakly zenith angle dependent albedo on model grid.
cvfcs Convective cloud cover on model grid.
cvbfcs Convective cloud base on model grid.
cvtfcs Convective cloud top on model grid.
me MPI task number.
nlunit Program namelist unit number.
sz_nml Dimension of input_nml_file.
input_nml_file Name of program namelist file.
ialb Use modis albedo when '1'. Use brigleb when '0'.
isot When '1', use statsgo soil type. When '0' use zobler soil type.
ivegsrc When '1', use igbp vegetation type. When '2' use sib vegetation type.
tile_num_ch Model tile number to process.
i_index The 'i' indices of the model grid to process.
j_index The 'j' indices of the model grid to process.
Author
Shrinivas Moorthi
Definition at line 175 of file sfcsub.F.
References albocn(), analy(), anomint(), clima(), filanl(), filfcs(), fixrdc(), getscv(), getsmc(), getstc(), hmskrd(), machine::kind_io4, machine::kind_io8, sfccyc_module::kpdabs, sfccyc_module::kpdabs_0, sfccyc_module::kpdabs_1, sfccyc_module::kpdacn, sfccyc_module::kpdais, sfccyc_module::kpdalb, sfccyc_module::kpdalb_0, sfccyc_module::kpdalb_1, sfccyc_module::kpdalf, sfccyc_module::kpdgla, sfccyc_module::kpdmsk, sfccyc_module::kpdmxi, sfccyc_module::kpdscv, sfccyc_module::kpdslp, sfccyc_module::kpdsmc, sfccyc_module::kpdsnd, sfccyc_module::kpdsno, sfccyc_module::kpdsot, sfccyc_module::kpdstc, sfccyc_module::kpdtg3, sfccyc_module::kpdtsf, sfccyc_module::kpdveg, sfccyc_module::kpdvet, sfccyc_module::kpdvmn, sfccyc_module::kpdvmx, sfccyc_module::kpdwet, sfccyc_module::kpdzor, landtyp(), sfccyc_module::mdata, merge(), monitr(), newice(), qcbyfc(), qcmxice(), qcmxmn(), qcsice(), qcsli(), qcsnow(), rof01(), scale(), setlsi(), setzro(), snodpth(), snodpth2(), snosfc(), sfccyc_module::soil_type_landice, tsfcor(), usesgt(), and sfccyc_module::veg_type_landice.
Referenced by sfcdrv().
subroutine snodpth (real (kind=kind_io8), dimension(len) scvanl, real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len) snoclm, real (kind=kind_io8), dimension(len) glacir, real (kind=kind_io8) snwmax, real (kind=kind_io8) snwmin, logical, intent(in) landice, integer len, real (kind=kind_io8), dimension(len) snoanl, integer me)
Estimate snow depth at glacial, land and sea ice points.
Parameters
scvanl Snow cover.
slianl Land-sea-ice mask.
tsfanl Skin temperature.
snoclm Climatological snow depth.
glacir Permanent glacial point when '1'.
snwmax Maximum snow depth.
snwmin Minimum snow depth.
landice When true, point is permanent land ice.
len Number of model points to process.
snoanl Snow depth.
me MPI task number.
Author
Shrinivas Moorthi
Definition at line 4976 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine snodpth2 (real (kind=kind_io8), dimension(len) glacir, real (kind=kind_io8) snwmax, real (kind=kind_io8), dimension(len) snoanl, integer len, integer me)
Ensure deep snow pack at permanent glacial points.
Parameters
glacir Glacial flag
snwmax Deep snow pack depth
snoanl Model snow
len Number of model points to process.
me MPI task number.
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 9715 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine snosfc (real (kind=kind_io8), dimension(len) snoanl, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8) tsfsmx, integer len, integer me)
Check skin temperature at points with snow. If it is above a threshold, reset it to that value.
Parameters
snoanl Snow.
tsfanl Skin temperature at the model points.
tsfsmx Maximum allowable skin temperature at snow points.
len Number of model points to process.
me MPI rank
Author
Shrinivas Moorthi NOAA/EMC
Definition at line 6590 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine subst (real (kind=kind_io8), dimension(imax,jmax) data, integer imax, integer jmax, real (kind=kind_io8) dlon, real (kind=kind_io8) dlat, logical ijordr)
Take an array of data on a lat/lon based grid and rearrange it so the corner point is in the 'lower left' and adjacent points in the 'i' direction are consecutive.
Parameters
data The data to be adjusted.
imax 'i' dimension of data.
jmax 'j' dimension of data.
dlon Delta longitude of the data.
dlat Delta latitude of the data.
ijordr When false, adjacent points in the 'i' direction are consecutive. Otherwise, 'j' points are consecutive.
Author
Shrinivas Moorthi
Definition at line 3133 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by fixrda(), and fixrdc().
subroutine tsfcor (real (kind=kind_io8), dimension(len) tsfc, real (kind=kind_io8), dimension(len) orog, real (kind=kind_io8), dimension(len) slmask, real (kind=kind_io8) umask, integer len, real (kind=kind_io8) rlapse)
Adjust skin temperature or SST for terrain.
Parameters
tsfc Skin temperature/SST
orog Orography height.
slmask Model land-sea mask.
umask When '0' adjust SST, when '1' adjust skin temperature.
len Number of model points to process.
rlapse Standard atmospheric lapse rate.
Author
Shrinivas Moorthi
Definition at line 4946 of file sfcsub.F.
References machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
subroutine usesgt (real (kind=kind_io8), dimension(len) sig1t, real (kind=kind_io8), dimension(len) slianl, real (kind=kind_io8), dimension(len) tg3anl, integer len, integer lsoil, real (kind=kind_io8), dimension(len) tsfanl, real (kind=kind_io8), dimension(len,lsoil) stcanl, real (kind=kind_io8) tsfimx)
Set soil temperature and sea ice column temperature for a dead start.
Parameters
sig1t Sigma level 1 temperature for dead start.
slianl Land-sea-ice mask.
tg3anl Soil substrate temperature.
len Number of model points to process.
lsoil Number of soil layers.
tsfanl Skin temperature.
stcanl Soil/sea ice column temperature.
tsfimx Freezing point of sea water.
Author
Shrinivas Moorthi
Definition at line 6557 of file sfcsub.F.
References getstc(), machine::kind_io4, and machine::kind_io8.
Referenced by sfccycle().
Author
Generated automatically by Doxygen for global_cycle from the source code.