/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/interp_frac_cats.F90
NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/interp_frac_cats.F90 - Read the input cateogorical source data and interpolate percent of each category to the model grid.
SYNOPSIS
Functions/Subroutines
subroutine interp_frac_cats (localpet, input_file)
Read the input source data and interpolate it to the model grid.
Detailed Description
Read the input cateogorical source data and interpolate percent of each category to the model grid.
Author:
George Gayno
Date:
2022
Definition in file interp_frac_cats.F90.
Function/Subroutine Documentation
subroutine interp_frac_cats (integer, intent(in) localpet, character(len=*), intent(in) input_file)
Read the input source data and interpolate it to the model grid. Outputs the percentage of each category within a model grid box and the dominant category.
Parameters:
localpet this mpi task
input_file filename of input source data.
Author:
George Gayno
Date:
2022
Definition at line 15 of file interp_frac_cats.F90.
References utils::error_handler(), source_grid::field_names, model_grid::grid_mdl, source_grid::grid_src, model_grid::i_mdl, source_grid::i_src, model_grid::j_mdl, source_grid::j_src, model_grid::land_frac_field_mdl, model_grid::latitude_field_mdl, model_grid::longitude_field_mdl, model_grid::mask_field_mdl, utils::netcdf_err(), model_grid::num_tiles, output_frac_cats::output_driver(), and search_frac_cats().
Referenced by driver().
Author
Generated automatically by Doxygen for sfc_climo_gen from the source code.