var annotated_dup =
[
    [ "pesg", "namespacepesg.html", [
      [ "bestesg_geo", "interfacepesg_1_1bestesg__geo.html", "interfacepesg_1_1bestesg__geo" ],
      [ "bestesg_map", "interfacepesg_1_1bestesg__map.html", "interfacepesg_1_1bestesg__map" ],
      [ "gaulegh", "interfacepesg_1_1gaulegh.html", "interfacepesg_1_1gaulegh" ],
      [ "get_edges", "interfacepesg_1_1get__edges.html", "interfacepesg_1_1get__edges" ],
      [ "get_meanq", "interfacepesg_1_1get__meanq.html", "interfacepesg_1_1get__meanq" ],
      [ "get_qofv", "interfacepesg_1_1get__qofv.html", "interfacepesg_1_1get__qofv" ],
      [ "get_qx", "interfacepesg_1_1get__qx.html", "interfacepesg_1_1get__qx" ],
      [ "gtoxm_ak_dd", "interfacepesg_1_1gtoxm__ak__dd.html", "interfacepesg_1_1gtoxm__ak__dd" ],
      [ "gtoxm_ak_rr", "interfacepesg_1_1gtoxm__ak__rr.html", "interfacepesg_1_1gtoxm__ak__rr" ],
      [ "guessak_geo", "interfacepesg_1_1guessak__geo.html", "interfacepesg_1_1guessak__geo" ],
      [ "guessak_map", "interfacepesg_1_1guessak__map.html", "interfacepesg_1_1guessak__map" ],
      [ "hgrid_ak", "interfacepesg_1_1hgrid__ak.html", "interfacepesg_1_1hgrid__ak" ],
      [ "hgrid_ak_dc", "interfacepesg_1_1hgrid__ak__dc.html", "interfacepesg_1_1hgrid__ak__dc" ],
      [ "hgrid_ak_dd", "interfacepesg_1_1hgrid__ak__dd.html", "interfacepesg_1_1hgrid__ak__dd" ],
      [ "hgrid_ak_rc", "interfacepesg_1_1hgrid__ak__rc.html", "interfacepesg_1_1hgrid__ak__rc" ],
      [ "hgrid_ak_rr", "interfacepesg_1_1hgrid__ak__rr.html", "interfacepesg_1_1hgrid__ak__rr" ],
      [ "xctoxm_ak", "interfacepesg_1_1xctoxm__ak.html", "interfacepesg_1_1xctoxm__ak" ],
      [ "xctoxs", "interfacepesg_1_1xctoxs.html", "interfacepesg_1_1xctoxs" ],
      [ "xmtog_ak_dd", "interfacepesg_1_1xmtog__ak__dd.html", "interfacepesg_1_1xmtog__ak__dd" ],
      [ "xmtog_ak_rr", "interfacepesg_1_1xmtog__ak__rr.html", "interfacepesg_1_1xmtog__ak__rr" ],
      [ "xmtoxc_ak", "interfacepesg_1_1xmtoxc__ak.html", "interfacepesg_1_1xmtoxc__ak" ],
      [ "xmtoxt", "interfacepesg_1_1xmtoxt.html", "interfacepesg_1_1xmtoxt" ],
      [ "xstoxc", "interfacepesg_1_1xstoxc.html", "interfacepesg_1_1xstoxc" ],
      [ "xstoxt", "interfacepesg_1_1xstoxt.html", "interfacepesg_1_1xstoxt" ],
      [ "xttoxm", "interfacepesg_1_1xttoxm.html", "interfacepesg_1_1xttoxm" ],
      [ "xttoxs", "interfacepesg_1_1xttoxs.html", "interfacepesg_1_1xttoxs" ],
      [ "zmtozt", "interfacepesg_1_1zmtozt.html", "interfacepesg_1_1zmtozt" ],
      [ "zttozm", "interfacepesg_1_1zttozm.html", "interfacepesg_1_1zttozm" ]
    ] ],
    [ "pfun", "namespacepfun.html", [
      [ "ahav", "interfacepfun_1_1ahav.html", "interfacepfun_1_1ahav" ],
      [ "ahavh", "interfacepfun_1_1ahavh.html", "interfacepfun_1_1ahavh" ],
      [ "atanh", "interfacepfun_1_1atanh.html", "interfacepfun_1_1atanh" ],
      [ "gd", "interfacepfun_1_1gd.html", "interfacepfun_1_1gd" ],
      [ "gdi", "interfacepfun_1_1gdi.html", "interfacepfun_1_1gdi" ],
      [ "hav", "interfacepfun_1_1hav.html", "interfacepfun_1_1hav" ],
      [ "havh", "interfacepfun_1_1havh.html", "interfacepfun_1_1havh" ],
      [ "sech", "interfacepfun_1_1sech.html", "interfacepfun_1_1sech" ],
      [ "sechs", "interfacepfun_1_1sechs.html", "interfacepfun_1_1sechs" ],
      [ "sinhox", "interfacepfun_1_1sinhox.html", "interfacepfun_1_1sinhox" ],
      [ "sinhoxm", "interfacepfun_1_1sinhoxm.html", "interfacepfun_1_1sinhoxm" ],
      [ "sinox", "interfacepfun_1_1sinox.html", "interfacepfun_1_1sinox" ],
      [ "sinoxm", "interfacepfun_1_1sinoxm.html", "interfacepfun_1_1sinoxm" ]
    ] ],
    [ "pmat", null, [
      [ "inv", "interfacepmat_1_1inv.html", "interfacepmat_1_1inv" ],
      [ "invl", "interfacepmat_1_1invl.html", "interfacepmat_1_1invl" ],
      [ "invu", "interfacepmat_1_1invu.html", "interfacepmat_1_1invu" ],
      [ "l1lm", "interfacepmat_1_1l1lm.html", "interfacepmat_1_1l1lm" ],
      [ "ldlm", "interfacepmat_1_1ldlm.html", "interfacepmat_1_1ldlm" ],
      [ "ldum", "interfacepmat_1_1ldum.html", "interfacepmat_1_1ldum" ],
      [ "swpvv", "interfacepmat_1_1swpvv.html", "interfacepmat_1_1swpvv" ],
      [ "udlmm", "interfacepmat_1_1udlmm.html", "interfacepmat_1_1udlmm" ]
    ] ],
    [ "pmat2", "namespacepmat2.html", [
      [ "avco", "interfacepmat2_1_1avco.html", "interfacepmat2_1_1avco" ],
      [ "cad1b", "interfacepmat2_1_1cad1b.html", "interfacepmat2_1_1cad1b" ],
      [ "cad2b", "interfacepmat2_1_1cad2b.html", "interfacepmat2_1_1cad2b" ],
      [ "clipb", "interfacepmat2_1_1clipb.html", "interfacepmat2_1_1clipb" ],
      [ "csb1b", "interfacepmat2_1_1csb1b.html", "interfacepmat2_1_1csb1b" ],
      [ "csb2b", "interfacepmat2_1_1csb2b.html", "interfacepmat2_1_1csb2b" ],
      [ "dfco", "interfacepmat2_1_1dfco.html", "interfacepmat2_1_1dfco" ],
      [ "dfco2", "interfacepmat2_1_1dfco2.html", "interfacepmat2_1_1dfco2" ],
      [ "l1ubb", "interfacepmat2_1_1l1ubb.html", "interfacepmat2_1_1l1ubb" ],
      [ "l1ueb", "interfacepmat2_1_1l1ueb.html", "interfacepmat2_1_1l1ueb" ],
      [ "ldltb", "interfacepmat2_1_1ldltb.html", "interfacepmat2_1_1ldltb" ],
      [ "ldub", "interfacepmat2_1_1ldub.html", "interfacepmat2_1_1ldub" ],
      [ "linbv", "interfacepmat2_1_1linbv.html", "interfacepmat2_1_1linbv" ],
      [ "ltdlbv", "interfacepmat2_1_1ltdlbv.html", "interfacepmat2_1_1ltdlbv" ],
      [ "u1lbv", "interfacepmat2_1_1u1lbv.html", "interfacepmat2_1_1u1lbv" ],
      [ "u1lbx", "interfacepmat2_1_1u1lbx.html", "interfacepmat2_1_1u1lbx" ],
      [ "u1lby", "interfacepmat2_1_1u1lby.html", "interfacepmat2_1_1u1lby" ],
      [ "u1lvb", "interfacepmat2_1_1u1lvb.html", "interfacepmat2_1_1u1lvb" ],
      [ "u1lxb", "interfacepmat2_1_1u1lxb.html", "interfacepmat2_1_1u1lxb" ],
      [ "u1lyb", "interfacepmat2_1_1u1lyb.html", "interfacepmat2_1_1u1lyb" ],
      [ "udlb", "interfacepmat2_1_1udlb.html", "interfacepmat2_1_1udlb" ],
      [ "udlbv", "interfacepmat2_1_1udlbv.html", "interfacepmat2_1_1udlbv" ],
      [ "udlbx", "interfacepmat2_1_1udlbx.html", "interfacepmat2_1_1udlbx" ],
      [ "udlby", "interfacepmat2_1_1udlby.html", "interfacepmat2_1_1udlby" ],
      [ "udlvb", "interfacepmat2_1_1udlvb.html", "interfacepmat2_1_1udlvb" ],
      [ "udlxb", "interfacepmat2_1_1udlxb.html", "interfacepmat2_1_1udlxb" ],
      [ "udlyb", "interfacepmat2_1_1udlyb.html", "interfacepmat2_1_1udlyb" ],
      [ "wrtb", "interfacepmat2_1_1wrtb.html", "interfacepmat2_1_1wrtb" ]
    ] ],
    [ "pmat4", "namespacepmat4.html", [
      [ "absv", "interfacepmat4_1_1absv.html", "interfacepmat4_1_1absv" ],
      [ "axial", "interfacepmat4_1_1axial.html", "interfacepmat4_1_1axial" ],
      [ "axtoq", "interfacepmat4_1_1axtoq.html", "interfacepmat4_1_1axtoq" ],
      [ "axtorot", "interfacepmat4_1_1axtorot.html", "interfacepmat4_1_1axtorot" ],
      [ "corral", "interfacepmat4_1_1corral.html", "interfacepmat4_1_1corral" ],
      [ "cross_product", "interfacepmat4_1_1cross__product.html", "interfacepmat4_1_1cross__product" ],
      [ "ctoz", "interfacepmat4_1_1ctoz.html", "interfacepmat4_1_1ctoz" ],
      [ "det", "interfacepmat4_1_1det.html", "interfacepmat4_1_1det" ],
      [ "diag", "interfacepmat4_1_1diag.html", "interfacepmat4_1_1diag" ],
      [ "dlltoxy", "interfacepmat4_1_1dlltoxy.html", "interfacepmat4_1_1dlltoxy" ],
      [ "expmat", "interfacepmat4_1_1expmat.html", "interfacepmat4_1_1expmat" ],
      [ "gram", "interfacepmat4_1_1gram.html", "interfacepmat4_1_1gram" ],
      [ "hav", "interfacepmat4_1_1hav.html", "interfacepmat4_1_1hav" ],
      [ "huarea", "interfacepmat4_1_1huarea.html", "interfacepmat4_1_1huarea" ],
      [ "identity", "interfacepmat4_1_1identity.html", "interfacepmat4_1_1identity" ],
      [ "mobius", "interfacepmat4_1_1mobius.html", "interfacepmat4_1_1mobius" ],
      [ "mobiusi", "interfacepmat4_1_1mobiusi.html", "interfacepmat4_1_1mobiusi" ],
      [ "mulqq", "interfacepmat4_1_1mulqq.html", "interfacepmat4_1_1mulqq" ],
      [ "normalize", "interfacepmat4_1_1normalize.html", "interfacepmat4_1_1normalize" ],
      [ "normalized", "interfacepmat4_1_1normalized.html", "interfacepmat4_1_1normalized" ],
      [ "orthogonalized", "interfacepmat4_1_1orthogonalized.html", "interfacepmat4_1_1orthogonalized" ],
      [ "outer_product", "interfacepmat4_1_1outer__product.html", "interfacepmat4_1_1outer__product" ],
      [ "qtoax", "interfacepmat4_1_1qtoax.html", "interfacepmat4_1_1qtoax" ],
      [ "qtorot", "interfacepmat4_1_1qtorot.html", "interfacepmat4_1_1qtorot" ],
      [ "qtospin", "interfacepmat4_1_1qtospin.html", "interfacepmat4_1_1qtospin" ],
      [ "rottoax", "interfacepmat4_1_1rottoax.html", "interfacepmat4_1_1rottoax" ],
      [ "rottoq", "interfacepmat4_1_1rottoq.html", "interfacepmat4_1_1rottoq" ],
      [ "rowops", "interfacepmat4_1_1rowops.html", "interfacepmat4_1_1rowops" ],
      [ "sarea", "interfacepmat4_1_1sarea.html", "interfacepmat4_1_1sarea" ],
      [ "setem", "interfacepmat4_1_1setem.html", "interfacepmat4_1_1setem" ],
      [ "setmobius", "interfacepmat4_1_1setmobius.html", "interfacepmat4_1_1setmobius" ],
      [ "spintoq", "interfacepmat4_1_1spintoq.html", "interfacepmat4_1_1spintoq" ],
      [ "trace", "interfacepmat4_1_1trace.html", "interfacepmat4_1_1trace" ],
      [ "triple_product", "interfacepmat4_1_1triple__product.html", "interfacepmat4_1_1triple__product" ],
      [ "znfun", "interfacepmat4_1_1znfun.html", "interfacepmat4_1_1znfun" ],
      [ "zntay", "interfacepmat4_1_1zntay.html", "interfacepmat4_1_1zntay" ],
      [ "ztoc", "interfacepmat4_1_1ztoc.html", "interfacepmat4_1_1ztoc" ]
    ] ],
    [ "pmat5", "namespacepmat5.html", [
      [ "ctoc_schm", "interfacepmat5_1_1ctoc__schm.html", "interfacepmat5_1_1ctoc__schm" ],
      [ "ctog", "interfacepmat5_1_1ctog.html", "interfacepmat5_1_1ctog" ],
      [ "ctogr", "interfacepmat5_1_1ctogr.html", "interfacepmat5_1_1ctogr" ],
      [ "frametwist", "interfacepmat5_1_1frametwist.html", "interfacepmat5_1_1frametwist" ],
      [ "grtoc", "interfacepmat5_1_1grtoc.html", "interfacepmat5_1_1grtoc" ],
      [ "gtoc", "interfacepmat5_1_1gtoc.html", "interfacepmat5_1_1gtoc" ],
      [ "gtoframe", "interfacepmat5_1_1gtoframe.html", "interfacepmat5_1_1gtoframe" ],
      [ "ininmap", "interfacepmat5_1_1ininmap.html", "interfacepmat5_1_1ininmap" ],
      [ "inivmap", "interfacepmat5_1_1inivmap.html", "interfacepmat5_1_1inivmap" ],
      [ "paraframe", "interfacepmat5_1_1paraframe.html", "interfacepmat5_1_1paraframe" ],
      [ "plctoc", "interfacepmat5_1_1plctoc.html", "interfacepmat5_1_1plctoc" ],
      [ "plrot", "interfacepmat5_1_1plrot.html", "interfacepmat5_1_1plrot" ],
      [ "plroti", "interfacepmat5_1_1plroti.html", "interfacepmat5_1_1plroti" ]
    ] ],
    [ "psym2", "namespacepsym2.html", [
      [ "chol2", "interfacepsym2_1_1chol2.html", "interfacepsym2_1_1chol2" ],
      [ "eigensym2", "interfacepsym2_1_1eigensym2.html", "interfacepsym2_1_1eigensym2" ],
      [ "expsym2", "interfacepsym2_1_1expsym2.html", "interfacepsym2_1_1expsym2" ],
      [ "expsym2d_e", "interfacepsym2_1_1expsym2d__e.html", "interfacepsym2_1_1expsym2d__e" ],
      [ "expsym2d_t", "interfacepsym2_1_1expsym2d__t.html", "interfacepsym2_1_1expsym2d__t" ],
      [ "id2222", "interfacepsym2_1_1id2222.html", "interfacepsym2_1_1id2222" ],
      [ "invsym2", "interfacepsym2_1_1invsym2.html", "interfacepsym2_1_1invsym2" ],
      [ "logsym2", "interfacepsym2_1_1logsym2.html", "interfacepsym2_1_1logsym2" ],
      [ "sqrtsym2", "interfacepsym2_1_1sqrtsym2.html", "interfacepsym2_1_1sqrtsym2" ],
      [ "sqrtsym2d_e", "interfacepsym2_1_1sqrtsym2d__e.html", "interfacepsym2_1_1sqrtsym2d__e" ],
      [ "sqrtsym2d_t", "interfacepsym2_1_1sqrtsym2d__t.html", "interfacepsym2_1_1sqrtsym2d__t" ]
    ] ]
];