.TH "cs_nb::nb_tile_idx" 3 "Mon Apr 17 2023" "Version 1.10.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cs_nb::nb_tile_idx \- Neighboring tile descriptor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "character(1) \fBnb_tile_bndry\fP"
.br
.RI "Neighbor tile boundary (l)eft, (r)ight, (t)op, (b)ottom\&. "
.ti -1c
.RI "integer \fBnb_tile_num\fP"
.br
.RI "Neighbor tile number (1\&.\&.6) "
.in -1c
.SH "Detailed Description"
.PP 
Neighboring tile descriptor\&. 


.PP
Definition at line 11 of file nb\&.F90\&.
.SH "Field Documentation"
.PP 
.SS "character (1) cs_nb::nb_tile_idx::nb_tile_bndry"

.PP
Neighbor tile boundary (l)eft, (r)ight, (t)op, (b)ottom\&. 
.PP
Definition at line 13 of file nb\&.F90\&.
.SS "integer cs_nb::nb_tile_idx::nb_tile_num"

.PP
Neighbor tile number (1\&.\&.6) 
.PP
Definition at line 12 of file nb\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for orog_mask_tools from the source code\&.
