.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/inland.fd Directory Reference" 3 "Wed Mar 13 2024" "Version 1.13.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/inland.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinland\&.F90\fP"
.br
.RI "\fIProgram and associated routines for creating inland mask\&. \fP"
.ti -1c
.RI "file \fBnb\&.F90\fP"
.br
.RI "\fIThis module contains the subroutines that find the adjacent neighbors of a given cell, in a cubed sphere grid\&. \fP"
.in -1c
