.TH "cs_nb::nb_gp_idx" 3 "Thu Aug 4 2022" "Version 1.8.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cs_nb::nb_gp_idx \- Neighboring cell descriptor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "integer \fBgp_type\fP"
.br
.RI "Cell boundary type from bndry function\&. "
.ti -1c
.RI "integer, dimension(3, 8) \fBijt\fP"
.br
.RI "Neighboring cell indices\&. "
.in -1c
.SH "Detailed Description"
.PP 
Neighboring cell descriptor\&. 


.PP
Definition at line 17 of file nb\&.F90\&.
.SH "Field Documentation"
.PP 
.SS "integer cs_nb::nb_gp_idx::gp_type"

.PP
Cell boundary type from bndry function\&. 
.PP
Definition at line 18 of file nb\&.F90\&.
.SS "integer, dimension(3,8) cs_nb::nb_gp_idx::ijt"

.PP
Neighboring cell indices\&. 
.PP
Definition at line 19 of file nb\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for orog_mask_tools from the source code\&.
