cs_nb
NAME
cs_nb -
SYNOPSIS
Data Types
type nb_gp_idx
Neighboring cell descriptor.
type nb_tile_idx
Neighboring tile descriptor.
Public Member Functions
INTEGER function bndry (i, j)
Get boundary type from indices for global grid.
INTEGER function bndry_reg (i, j)
Get boundary type from indices for regional grid.
subroutine idx_init (cres_in)
Initialize inter-panel neighbor index for global grid.
subroutine idx_init_reg (xres_in, yres_in)
Initialize resolution module variables for regional grid.
subroutine neighbors (tile, i, j, nb)
Get neighbors of cell 'c' at (tile, i, j) for global grid.
subroutine neighbors_reg (i, j, nb)
Get neighbors of cell 'c' at (tile, i, j) for regional grid.
Data Fields
integer cres
Cubed sphere resolution.
type(nb_tile_idx), dimension(4, 6) nb_tile
Descriptor for each edge of each tile on the cubed sphere.
integer xres
x resolution of regional grid
integer yres
y resolution of regional grid
Detailed Description
Definition at line 7 of file nb.F90.
Data Type Documentation
type cs_nb::nb_gp_idx
Neighboring cell descriptor.
Definition at line 17 of file nb.F90.
Data Fields:
integer gp_type Cell boundary type from bndry function.
integer, dimension(3, 8) ijt Neighboring cell indices.
type cs_nb::nb_tile_idx
Neighboring tile descriptor.
Definition at line 11 of file nb.F90.
Data Fields:
character(1) nb_tile_bndry Neighbor tile boundary (l)eft, (r)ight, (t)op, (b)ottom.
integer nb_tile_num Neighbor tile number (1..6)
Member Function/Subroutine Documentation
INTEGER function cs_nb::bndry (integeri, integerj)
Get boundary type from indices for global grid.
Parameters:
i cell index
j cell index
Returns:
bndry cell boundary type
Author:
Ning Wang
Definition at line 106 of file nb.F90.
Referenced by neighbors().
INTEGER function cs_nb::bndry_reg (integeri, integerj)
Get boundary type from indices for regional grid.
Parameters:
i cell index
j cell index
Returns:
cell boundary type
Author:
Ning Wang
Definition at line 140 of file nb.F90.
Referenced by neighbors_reg().
subroutine cs_nb::idx_init (integercres_in)
Initialize inter-panel neighbor index for global grid.
Parameters:
cres_in cubed sphere resolution (48, 96...)
   _______1_______
  | | 1-upper, 2-bottom, 3-left, 4-right
  | |
  | |
 3| |4
  | |
  | |
  |_______________|
          2
      Figure 1. Boundary numbers.fi
Author:
Ning Wang
Definition at line 48 of file nb.F90.
Referenced by inland_mask(), and neighbors_reg().
subroutine cs_nb::idx_init_reg (integer, intent(in)xres_in, integer, intent(in)yres_in)
Initialize resolution module variables for regional grid.
Parameters:
xres_in x resolution
yres_in y resolution
Author:
Ning Wang
Definition at line 91 of file nb.F90.
Referenced by inland_mask().
subroutine cs_nb::neighbors (integertile, integeri, integerj, type(nb_gp_idx)nb)
Get neighbors of cell 'c' at (tile, i, j) for global grid.
     ______________
    | | | | ________
    | 5 | 1 | 6 | / 1 6
    |____|____|____| / \___\___
    | | | | /\2 / c / 3 /
    | 2 | c | 3 | / \/___/___/
    |____|____|____| \7 / 4 / 8 /
    | | | | \/___/___/
    | 7 | 4 | 8 |
    |____|____|____|
  
 Figure 2. Eight neighbors of cell 'c' and special cases at upper left
 cornner of the tile
Parameters:
tile tile face
i cell index
j cell index
nb neighbors
Author:
Ning Wang
Definition at line 192 of file nb.F90.
References bndry().
Referenced by mark_global_inland_rec_d(), and neighbors_reg().
subroutine cs_nb::neighbors_reg (integeri, integerj, type(nb_gp_idx)nb)
Get neighbors of cell 'c' at (tile, i, j) for regional grid.
Parameters:
i cell index
j cell index
nb neighbors
Author:
Ning Wang
Definition at line 393 of file nb.F90.
References bndry_reg(), idx_init(), and neighbors().
Referenced by mark_regional_inland_rec_d().
Field Documentation
integer cs_nb::cres
Cubed sphere resolution.
Definition at line 24 of file nb.F90.
type(nb_tile_idx), dimension(4,6) cs_nb::nb_tile
Descriptor for each edge of each tile on the cubed sphere.
Definition at line 22 of file nb.F90.
integer cs_nb::xres
x resolution of regional grid
Definition at line 25 of file nb.F90.
integer cs_nb::yres
y resolution of regional grid
Definition at line 26 of file nb.F90.
Author
Generated automatically by Doxygen for orog_mask_tools from the source code.