.TH "cs_nb" 3 "Thu Feb 15 2024" "Version 1.12.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cs_nb \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBnb_gp_idx\fP"
.br
.RI "\fINeighboring cell descriptor\&. \fP"
.ti -1c
.RI "type \fBnb_tile_idx\fP"
.br
.RI "\fINeighboring tile descriptor\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "INTEGER function \fBbndry\fP (i, j)"
.br
.RI "\fIGet boundary type from indices for global grid\&. \fP"
.ti -1c
.RI "INTEGER function \fBbndry_reg\fP (i, j)"
.br
.RI "\fIGet boundary type from indices for regional grid\&. \fP"
.ti -1c
.RI "subroutine \fBidx_init\fP (cres_in)"
.br
.RI "\fIInitialize inter-panel neighbor index for global grid\&. \fP"
.ti -1c
.RI "subroutine \fBidx_init_reg\fP (xres_in, yres_in)"
.br
.RI "\fIInitialize resolution module variables for regional grid\&. \fP"
.ti -1c
.RI "subroutine \fBneighbors\fP (tile, i, j, nb)"
.br
.RI "\fIGet neighbors of cell 'c' at (tile, i, j) for global grid\&. \fP"
.ti -1c
.RI "subroutine \fBneighbors_reg\fP (i, j, nb)"
.br
.RI "\fIGet neighbors of cell 'c' at (tile, i, j) for regional grid\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "integer \fBcres\fP"
.br
.RI "\fICubed sphere resolution\&. \fP"
.ti -1c
.RI "type(\fBnb_tile_idx\fP), dimension(4, 6) \fBnb_tile\fP"
.br
.RI "\fIDescriptor for each edge of each tile on the cubed sphere\&. \fP"
.ti -1c
.RI "integer \fBxres\fP"
.br
.RI "\fIx resolution of regional grid \fP"
.ti -1c
.RI "integer \fByres\fP"
.br
.RI "\fIy resolution of regional grid \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file nb\&.F90\&.
.SH "Data Type Documentation"
.PP 
.SH "type cs_nb::nb_gp_idx"
.PP 
Neighboring cell descriptor\&. 


.PP
Definition at line 17 of file nb\&.F90\&.
.PP
\fBData Fields:\fP
.RS 4
integer \fIgp_type\fP Cell boundary type from bndry function\&. 
.br
.PP
integer, dimension(3, 8) \fIijt\fP Neighboring cell indices\&. 
.br
.PP
.RE
.PP
.SH "type cs_nb::nb_tile_idx"
.PP 
Neighboring tile descriptor\&. 


.PP
Definition at line 11 of file nb\&.F90\&.
.PP
\fBData Fields:\fP
.RS 4
character(1) \fInb_tile_bndry\fP Neighbor tile boundary (l)eft, (r)ight, (t)op, (b)ottom\&. 
.br
.PP
integer \fInb_tile_num\fP Neighbor tile number (1\&.\&.6) 
.br
.PP
.RE
.PP
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "INTEGER function cs_nb::bndry (integeri, integerj)"

.PP
Get boundary type from indices for global grid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP cell index 
.br
\fIj\fP cell index 
.RE
.PP
\fBReturns:\fP
.RS 4
bndry cell boundary type
.RE
.PP
\fBAuthor:\fP
.RS 4
Ning Wang 
.RE
.PP

.PP
Definition at line 106 of file nb\&.F90\&.
.PP
Referenced by neighbors()\&.
.SS "INTEGER function cs_nb::bndry_reg (integeri, integerj)"

.PP
Get boundary type from indices for regional grid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP cell index 
.br
\fIj\fP cell index 
.RE
.PP
\fBReturns:\fP
.RS 4
cell boundary type
.RE
.PP
\fBAuthor:\fP
.RS 4
Ning Wang 
.RE
.PP

.PP
Definition at line 140 of file nb\&.F90\&.
.PP
Referenced by neighbors_reg()\&.
.SS "subroutine cs_nb::idx_init (integercres_in)"

.PP
Initialize inter-panel neighbor index for global grid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcres_in\fP cubed sphere resolution (48, 96\&.\&.\&.)
.RE
.PP
.PP
.nf
   _______1_______
  |               |       1-upper, 2-bottom, 3-left, 4-right 
  |               |
  |               |
 3|               |4
  |               |
  |               |
  |_______________|
          2
      Figure 1. Boundary numbers.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Ning Wang 
.RE
.PP

.PP
Definition at line 48 of file nb\&.F90\&.
.PP
Referenced by inland_mask(), and neighbors_reg()\&.
.SS "subroutine cs_nb::idx_init_reg (integer, intent(in)xres_in, integer, intent(in)yres_in)"

.PP
Initialize resolution module variables for regional grid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxres_in\fP x resolution 
.br
\fIyres_in\fP y resolution
.RE
.PP
\fBAuthor:\fP
.RS 4
Ning Wang 
.RE
.PP

.PP
Definition at line 91 of file nb\&.F90\&.
.PP
Referenced by inland_mask()\&.
.SS "subroutine cs_nb::neighbors (integertile, integeri, integerj, type(\fBnb_gp_idx\fP)nb)"

.PP
Get neighbors of cell 'c' at (tile, i, j) for global grid\&. 
.PP
.nf
     ______________
    |    |    |    |              ________
    | 5  | 1  | 6  |             /\ 1 \ 6 
    |____|____|____|            /  \___\___
    |    |    |    |           /\2 / c / 3 /
    | 2  | c  | 3  |          /  \/___/___/
    |____|____|____|          \7 / 4 / 8 /
    |    |    |    |           \/___/___/
    | 7  | 4  | 8  |       
    |____|____|____|    
  
 Figure 2.  Eight neighbors of cell 'c' and special cases at upper left
 cornner of the tile
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fItile\fP tile face 
.br
\fIi\fP cell index 
.br
\fIj\fP cell index 
.br
\fInb\fP neighbors
.RE
.PP
\fBAuthor:\fP
.RS 4
Ning Wang 
.RE
.PP

.PP
Definition at line 192 of file nb\&.F90\&.
.PP
References bndry()\&.
.PP
Referenced by mark_global_inland_rec_d(), and neighbors_reg()\&.
.SS "subroutine cs_nb::neighbors_reg (integeri, integerj, type(\fBnb_gp_idx\fP)nb)"

.PP
Get neighbors of cell 'c' at (tile, i, j) for regional grid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP cell index 
.br
\fIj\fP cell index 
.br
\fInb\fP neighbors
.RE
.PP
\fBAuthor:\fP
.RS 4
Ning Wang 
.RE
.PP

.PP
Definition at line 393 of file nb\&.F90\&.
.PP
References bndry_reg(), idx_init(), and neighbors()\&.
.PP
Referenced by mark_regional_inland_rec_d()\&.
.SH "Field Documentation"
.PP 
.SS "integer cs_nb::cres"

.PP
Cubed sphere resolution\&. 
.PP
Definition at line 24 of file nb\&.F90\&.
.SS "type(\fBnb_tile_idx\fP), dimension(4,6) cs_nb::nb_tile"

.PP
Descriptor for each edge of each tile on the cubed sphere\&. 
.PP
Definition at line 22 of file nb\&.F90\&.
.SS "integer cs_nb::xres"

.PP
x resolution of regional grid 
.PP
Definition at line 25 of file nb\&.F90\&.
.SS "integer cs_nb::yres"

.PP
y resolution of regional grid 
.PP
Definition at line 26 of file nb\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for orog_mask_tools from the source code\&.
