/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/orog_mask_tools.fd/lake.fd/find_limit.F90
NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/orog_mask_tools.fd/lake.fd/find_limit.F90 - Geo-reference utilities for a cubed-sphere grid.
SYNOPSIS
Functions/Subroutines
subroutine find_limit (p1_in, p2_in, latmin, latmax)
Given two points on a cubed-sphere grid, compute the maximum and minimum latitudinal extent of the resulting great circle.
subroutine middle (p1, p2, p)
Compute the latitude and longitude of the middle point between two given points.
Detailed Description
Geo-reference utilities for a cubed-sphere grid.
Author:
Ning Wang
Definition in file find_limit.F90.
Function/Subroutine Documentation
subroutine find_limit (real*8, dimension(2), intent(in) p1_in, real*8, dimension(2), intent(in) p2_in, real*8, intent(out) latmin, real*8, intent(out) latmax)
Given two points on a cubed-sphere grid, compute the maximum and minimum latitudinal extent of the resulting great circle.
Parameters:
p1_in Latitude and longitude of point 1.
p2_in Latitude and longitude of point 2.
latmin Minimum latitudinal extent.
latmax Maximum latitudinal extent.
Author:
Ning Wang
Definition at line 16 of file find_limit.F90.
References middle().
Referenced by cal_lake_frac_depth().
subroutine middle (real*8, dimension(2), intent(in) p1, real*8, dimension(2), intent(in) p2, real*8, dimension(2), intent(out) p)
Compute the latitude and longitude of the middle point between two given points. There are two formulae available to compute it.
One derived from a more general m-sect formula:
  xyz = sin((1-f)*theta) / sin(theta) * xyz1 +
        sin(f*theta) /sin(theta) * xyz2 ;
  where theta is the angle of xyz1, and xyz2.
  
  xyz = 0.5 / sqrt[(1+dot(xyz1,xyz2))/2] * (xyz1+xyz2)
  
and the other one is the normalized middle point of the two end points:
  xyz = 0.5 * (xyz1+xyz2), xyz = xyz / sqrt(dot(xyz,xyz))
  
Parameters:
p1 Latitude/longitude of first end point.
p2 Latitude/longitude of second end point
p Latitude/longitude of the mid-point.
Author:
Ning Wang
Date:
March, 2006
Definition at line 80 of file find_limit.F90.
Referenced by find_limit().
Author
Generated automatically by Doxygen for orog_mask_tools from the source code.