gsl_oro_data_sm_scale
NAME
gsl_oro_data_sm_scale -
SYNOPSIS
Public Member Functions
subroutine calc_gsl_oro_data_sm_scale (tile_num, res_indx, halo, duplicate_oro_data_file)
Subroutine to compute orographic statistics needed for small-scale orograhic drag (gravity wave and form drag) schemes.
real(kind=real_kind) function interp_1d (x, x1, x2, y1, y2)
Interpolates (or extrapolates) linear function y = y(x)
integer function nearest_i_east (lon_in)
Finds nearest fine-grid i index to the east of a given longitude.
integer function nearest_i_west (lon_in)
Finds nearest fine-grid i index to the west of a given longitude.
integer function nearest_j_north (lat_in)
Calculates nearest fine-grid j index to the north of a given latitude.
integer function nearest_j_south (lat_in)
Calculates nearest fine-grid j index to the south of a given latitude.
subroutine netcdf_err (err, string)
Returns netCDF error given input err code.
Data Fields
integer, parameter dbl_kind = selected_real_kind(13)
double precision
integer dimx_fine
x-dimension of fine grid
integer dimy_fine
y-dimension of fine grid
real(kind=real_kind),
dimension(:), allocatable lat1d_fine"
latitude of fine grid pts
real(kind=real_kind),
dimension(:), allocatable lon1d_fine"
longitude of fine grid pts
real(kind=real_kind), parameter p5 = 0.5_real_kind
one half
real, parameter pi = 3.1415926535897_real_kind
pi
integer, parameter real_kind = selected_real_kind(6)
single precision
Detailed Description
Definition at line 23 of file module_gsl_oro_data_sm_scale.f90.
Member Function/Subroutine Documentation
subroutine gsl_oro_data_sm_scale::calc_gsl_oro_data_sm_scale (character(len=2), intent(in)tile_num, character(len=7), intent(in)res_indx, character(len=4), intent(in)halo, logical, intent(out)duplicate_oro_data_file)
Subroutine to compute orographic statistics needed for small-scale orograhic drag (gravity wave and form drag) schemes.
Parameters:
tile_num (tile number)
res_indx (resolution)
halo (halo number)
duplicate_oro_data_file (equals .true. if min grid size <= 7.5km)
Author:
Michael Toy, NOAA/GSL
Definition at line 49 of file module_gsl_oro_data_sm_scale.f90.
References gsl_oro_data_lg_scale::nearest_i_east(), gsl_oro_data_lg_scale::nearest_i_west(), gsl_oro_data_lg_scale::nearest_j_north(), gsl_oro_data_lg_scale::nearest_j_south(), and netcdf_err().
Referenced by gsl_oro_data().
real (kind=real_kind) function gsl_oro_data_sm_scale::interp_1d (real (kind=real_kind), intent(in)x, real (kind=real_kind), intent(in)x1, real (kind=real_kind), intent(in)x2, real (kind=real_kind), intent(in)y1, real (kind=real_kind), intent(in)y2)
Interpolates (or extrapolates) linear function y = y(x)
Parameters:
x Input 'x' value
x1 Known point 1
x2 Known point 2
y1 Known y(x1)
y2 Known y(x2)
Returns:
interp_1d Interpolated y value at x
Author:
Michael Toy, NOAA/GSL
Definition at line 1246 of file module_gsl_oro_data_sm_scale.f90.
References gsl_oro_data_lg_scale::interp_1d().
integer function gsl_oro_data_sm_scale::nearest_i_east (real (kind=real_kind), intent(in)lon_in)
Finds nearest fine-grid i index to the east of a given longitude.
Parameters:
lon_in longitude (radians)
Returns:
nearest_i_east Nearest grid point i-index east of selected point
Author:
Michael Toy, NOAA/GSL
Definition at line 1116 of file module_gsl_oro_data_sm_scale.f90.
References gsl_oro_data_lg_scale::nearest_i_east().
integer function gsl_oro_data_sm_scale::nearest_i_west (real (kind=real_kind), intent(in)lon_in)
Finds nearest fine-grid i index to the west of a given longitude.
Parameters:
lon_in longitude (radians)
Returns:
nearest_i_west Nearest grid point i-index west of selected point
Author:
Michael Toy, NOAA/GSL
Definition at line 1149 of file module_gsl_oro_data_sm_scale.f90.
References gsl_oro_data_lg_scale::nearest_i_west().
integer function gsl_oro_data_sm_scale::nearest_j_north (real (kind=real_kind), intent(in)lat_in)
Calculates nearest fine-grid j index to the north of a given latitude.
Parameters:
lat_in Latitude (radians)
Returns:
nearest_j_north Nearest fine-grid j index to the north of a given latitude
Author:
Michael Toy, NOAA/GSL
Definition at line 1182 of file module_gsl_oro_data_sm_scale.f90.
References gsl_oro_data_lg_scale::nearest_j_north().
integer function gsl_oro_data_sm_scale::nearest_j_south (real (kind=real_kind), intent(in)lat_in)
Calculates nearest fine-grid j index to the south of a given latitude.
Parameters:
lat_in Latitude (radians)
Returns:
nearest_j_south Nearest fine-grid j index to the south of a given latitude
Author:
Michael Toy, NOAA/GSL
Definition at line 1211 of file module_gsl_oro_data_sm_scale.f90.
References gsl_oro_data_lg_scale::nearest_j_south().
subroutine gsl_oro_data_sm_scale::netcdf_err (integer, intent(in)err, character(len=*), intent(in)string)
Returns netCDF error given input err code.
Parameters:
err Error code from netCDF routine
string Portion of error message
Author:
Michael Toy, NOAA/GSL
Definition at line 1266 of file module_gsl_oro_data_sm_scale.f90.
Field Documentation
integer, parameter gsl_oro_data_sm_scale::dbl_kind = selected_real_kind(13)
double precision
Definition at line 28 of file module_gsl_oro_data_sm_scale.f90.
integer gsl_oro_data_sm_scale::dimx_fine
x-dimension of fine grid
Definition at line 31 of file module_gsl_oro_data_sm_scale.f90.
integer gsl_oro_data_sm_scale::dimy_fine
y-dimension of fine grid
Definition at line 32 of file module_gsl_oro_data_sm_scale.f90.
real (kind = real_kind), dimension(:), allocatable gsl_oro_data_sm_scale::lat1d_fine
latitude of fine grid pts
Definition at line 34 of file module_gsl_oro_data_sm_scale.f90.
real (kind = real_kind), dimension(:), allocatable gsl_oro_data_sm_scale::lon1d_fine
longitude of fine grid pts
Definition at line 35 of file module_gsl_oro_data_sm_scale.f90.
real (kind = real_kind), parameter gsl_oro_data_sm_scale::p5 = 0.5_real_kind
one half
Definition at line 37 of file module_gsl_oro_data_sm_scale.f90.
real, parameter gsl_oro_data_sm_scale::pi = 3.1415926535897_real_kind
pi
Definition at line 30 of file module_gsl_oro_data_sm_scale.f90.
integer, parameter gsl_oro_data_sm_scale::real_kind = selected_real_kind(6)
single precision
Definition at line 27 of file module_gsl_oro_data_sm_scale.f90.
Author
Generated automatically by Doxygen for orog_mask_tools from the source code.