.TH "/home/ed/UFS_UTILS/sorc/orog_mask_tools.fd/orog.fd/machine.f90" 3 "Tue Mar 9 2021" "Version 1.0.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/UFS_UTILS/sorc/orog_mask_tools.fd/orog.fd/machine.f90 \- Machine dependant constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBmachine::kind_evod\fP"
.br
.ti -1c
.RI "integer \fBmachine::kind_io2\fP"
.br
.ti -1c
.RI "integer \fBmachine::kind_io4\fP"
.br
.ti -1c
.RI "integer \fBmachine::kind_io8\fP"
.br
.ti -1c
.RI "real(kind=kind_evod) \fBmachine::mprec\fP"
.br
.RI "machine precision to restrict dep "
.in -1c
.SH "Detailed Description"
.PP 
Machine dependant constants\&. 


.PP
Definition in file \fBmachine\&.f90\fP\&.
.SH "Variable Documentation"
.PP 
.SS "real(kind=kind_evod) machine::mprec"

.PP
machine precision to restrict dep 
.PP
Definition at line 12 of file machine\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for orog_mask_tools from the source code\&.
