/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.F
NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.F -
Terrain maker for global spectral model.
SYNOPSIS
Functions/Subroutines
program __mtnlm7_oclsm.f__
This program creates 7 terrain-related files computed from the GMTED2010 terrain dataset.
subroutine get_index (IMN, JMN, npts, lonO, latO, DELXN, jst, jen, ilist, numx)
Determine the location of a cubed-sphere point within the high-resolution orography data.
real function get_lat_angle (dy, DEGRAD)
Convert the 'y' direction distance of a cubed-sphere grid point to the corresponding distance in latitude.
real function get_lon_angle (dx, lat, DEGRAD)
Convert the 'x' direction distance of a cubed-sphere grid point to the corresponding distance in longitude.
subroutine get_mismatch_index (im_in, jm_in, geolon_in, geolat_in, bitmap_in, num_out, lon_out, lat_out, iindx, jindx)
For unmapped land points, find the nearest land point on the input data and pass back its i/j index.
real function get_xnsum (lon1, lat1, lon2, lat2, IMN, JMN, glat, zavg, zslm, delxn)
Count the number of high-resolution orography points that are higher than the model grid box average orography height.
subroutine get_xnsum2 (lon1, lat1, lon2, lat2, IMN, JMN, glat, zavg, delxn, xnsum1, xnsum2, HC)
Count the number of high-resolution orography points that are higher than a critical value inside a model grid box (or a portion of a model grid box).
subroutine get_xnsum3 (lon1, lat1, lon2, lat2, IMN, JMN, glat, zavg, delxn, xnsum1, xnsum2, HC)
Count the number of high-resolution orography points that are higher than a critical value inside a model grid box (or a portion of a model grid box).
subroutine gg2rg (im, jm, numi, a)
Convert from a full grid to a reduced grid.
logical function inside_a_polygon (lon1, lat1, npts, lon2, lat2)
Check if a point is inside a polygon.
subroutine interpolate_mismatch (im_in, jm_in, data_in, num_out, data_out, iindx, jindx)
Replace unmapped model land points with the nearest land point on the input grid.
subroutine latlon2xyz (siz, lon, lat, x, y, z)
Convert from latitude and longitude to x,y,z coordinates.
subroutine make_mask (zslm, SLM, land_frac, GLAT, IM, JM, IMN, JMN, lon_c, lat_c)
Create the land-mask, land fraction.
subroutine makemt (ZAVG, ZSLM, ORO, SLM, VAR, VAR4, GLAT, IST, IEN, JST, JEN, IM, JM, IMN, JMN, XLAT, numi)
Create the orography, land-mask, standard deviation of orography and the convexity on a model gaussian grid.
subroutine makemt2 (ZAVG, ZSLM, ORO, SLM, VAR, VAR4, GLAT, IM, JM, IMN, JMN, lon_c, lat_c, lake_frac, land_frac)
Create the orography, land-mask, land fraction, standard deviation of orography and the convexity on a model cubed-sphere tile.
subroutine makeoa (ZAVG, VAR, GLAT, OA4, OL, IOA4, ELVMAX, ORO, oro1, XNSUM, XNSUM1, XNSUM2, XNSUM3, XNSUM4, IST, IEN, JST, JEN, IM, JM, IMN, JMN, XLAT, numi)
Create orographic asymmetry and orographic length scale on the model grid.
subroutine makeoa2 (ZAVG, zslm, VAR, GLAT, OA4, OL, IOA4, ELVMAX, ORO, oro1, XNSUM, XNSUM1, XNSUM2, XNSUM3, XNSUM4, IM, JM, IMN, JMN, lon_c, lat_c, lon_t, lat_t, dx, dy, is_south_pole, is_north_pole)
Create orographic asymmetry and orographic length scale on the model grid.
subroutine makeoa3 (ZAVG, zslm, VAR, GLAT, OA4, OL, IOA4, ELVMAX, ORO, SLM, oro1, XNSUM, XNSUM1, XNSUM2, XNSUM3, XNSUM4, IM, JM, IMN, JMN, lon_c, lat_c, lon_t, lat_t, is_south_pole, is_north_pole, IMI, JMI, OA_IN, OL_IN, slm_in, lon_in, lat_in)
Create orographic asymmetry and orographic length scale on the model grid.
subroutine makepc (ZAVG, ZSLM, THETA, GAMMA, SIGMA, GLAT, IST, IEN, JST, JEN, IM, JM, IMN, JMN, XLAT, numi)
Make the principle coordinates - slope of orography, anisotropy, angle of mountain range with respect to east.
subroutine makepc2 (ZAVG, ZSLM, THETA, GAMMA, SIGMA, GLAT, IM, JM, IMN, JMN, lon_c, lat_c, SLM)
Make the principle coordinates - slope of orography, anisotropy, angle of mountain range with respect to east.
subroutine maxmin (ia, len, tile)
Print the maximum, mininum, mean and standard deviation of an array.
subroutine minmaxj (IM, JM, A, title)
Print out the maximum and minimum values of an array and their i/j location.
subroutine minmxj (IM, JM, A, title)
Print out the maximum and minimum values of an array.
subroutine mnmxja (IM, JM, A, imax, jmax, title)
Print out the maximum and minimum values of an array.
subroutine nanc (a, l, c)
Report NaNS and NaNQ within an address range for 8-byte real words.
subroutine read_g (glob)
Read input global 30-arc second orography data.
subroutine revers (IM, JM, numi, F, WRK)
Reverse the east-west and north-south axes in a two-dimensional array.
subroutine rg2gg (im, jm, numi, a)
Convert from a reduced grid to a full grid.
subroutine spfft1 (IMAX, INCW, INCG, KMAX, W, G, IDIR)
Perform multiple fast fourier transforms.
real function spherical_angle (v1, v2, v3)
Compute spherical angle.
real function spherical_distance (theta1, phi1, theta2, phi2)
Compute a great circle distance between two points.
subroutine tersub (IMN, JMN, IM, JM, NM, NR, NF0, NF1, NW, EFAC, BLAT, OUTGRID, INPUTOROG, MASK_ONLY, MERGE_FILE)
Driver routine to compute terrain.
real function timef ()
Get the date/time for the system clock.
Detailed Description
Terrain maker for global spectral model.
Author:
Mark Iredell
Date:
92-04-16
Definition in file mtnlm7_oclsm.F.
Function/Subroutine Documentation
program __mtnlm7_oclsm.f__ ()
This program creates 7 terrain-related files computed from the GMTED2010 terrain dataset. The model physics grid parameters and spectral truncation and filter parameters are read by this program as input.
The 7 files produced are:
1.
sea-land mask on model physics grid
2.
gridded orography on model physics grid
3.
mountain std dev on model physics grid
4.
spectral orography in spectral domain
5.
unfiltered gridded orography on model physics grid
6.
grib sea-land mask on model physics grid
7.
grib gridded orography on model physics grid
The orography is only filtered for wavenumbers greater than nf0. For wavenumbers n between nf0 and nf1, the orography is filtered by the factor 1-((n-nf0)/(nf1-nf0))**2. The filtered orography will not have information beyond wavenumber nf1.
PROGRAM HISTORY LOG:
92-04-16 IREDELL
98-02-02 IREDELL FILTER
98-05-31 HONG Modified for subgrid orography used in Kim's scheme
98-12-31 HONG Modified for high-resolution GTOPO orography
99-05-31 HONG Modified for getting OL4 (mountain fraction)
00-02-10 Moorthi's modifications
00-04-11 HONG Modified for reduced grids
00-04-12 Iredell Modified for reduced grids
02-01-07 (j) modified for principal axes of orography There are now 14 files, 4 additional for lm mb
04-04-04 (j) re-Test on IST/ilen calc for sea-land mask(j)
04-09-04 minus sign here in MAKEOA IST and IEN as in MAKEMT!
05-09-05 if test on HK and HLPRIM for GAMMA SQRT
07-08-07 replace 8' with 30' incl GICE, conintue w/ S-Y. lake slm
  - 08-08-07 All input 30', UMD option, and filter as described below Quadratic filter applied by default. NF0 is normally set to an even value beyond the previous truncation, for example, for jcap=382, NF0=254+2 NF1 is set as jcap+2 (and/or nearest even), eg., for t382, NF1=382+2=384 if no filter is desired then NF1=NF0=0 and ORF=ORO but if no filter but spectral to grid (with gibbs) then NF1=jcap+2, and NF1=jcap+1
INPUT FILES:
UNIT5 - PHYSICS LONGITUDES (IM), PHYSICS LATITUDES (JM), SPECTRAL TRUNCATION (NM), RHOMBOIDAL FLAG (NR), AND FIRST AND SECOND FILTER PARAMETERS (NF0,NF1). RESPECTIVELY READ IN FREE FORMAT.
NCID - GMTED2010 USGS orography (NetCDF)
NCID - 30' UMD land cover mask. (NetCDF)
  - NCID - GICE Grumbine 30' RAMP Antarctica orog IMNx3601. (NetCDF)
UNIT25 - Ocean land-sea mask on gaussian grid
OUTPUT FILES:
UNIT51 - SEA-LAND MASK (IM,JM)
UNIT52 - GRIDDED OROGRAPHY (IM,JM)
UNIT54 - SPECTRAL OROGRAPHY ((NM+1)*((NR+1)*NM+2))
UNIT55 - UNFILTERED GRIDDED OROGRAPHY (IM,JM)
UNIT57 - GRIB GRIDDED OROGRAPHY (IM,JM)
SUBPROGRAMS CALLED:
UNIQUE:
TERSUB - MAIN SUBPROGRAM
SPLAT - COMPUTE GAUSSIAN LATITUDES OR EQUALLY-SPACED LATITUDES
LIBRARY:
SPTEZ - SPHERICAL TRANSFORM
GBYTES - UNPACK BITS
Returns:
0 for success, error code otherwise.
Definition at line 74 of file mtnlm7_oclsm.F.
References netcdf_err(), and tersub().
subroutine get_index (integer, intent(in)IMN, integer, intent(in)JMN, integernpts, real, dimension(npts), intent(in)lonO, real, dimension(npts), intent(in)latO, real, intent(in)DELXN, integer, intent(out)jst, integer, intent(out)jen, integer, dimension(imn), intent(out)ilist, integer, intent(out)numx)
Determine the location of a cubed-sphere point within the high-resolution orography data. The location is described by the range of i/j indices on the high-res grid.
Parameters:
imn 'i' dimension of the high-resolution orography data set.
jmn 'j' dimension of the high-resolution orography data set.
npts Number of vertices to describe the cubed-sphere point.
lonO The longitudes of the cubed-sphere vertices.
latO The latitudes of the cubed-sphere vertices.
delxn Resolution of the high-resolution orography data set.
jst Starting 'j' index on the high-resolution grid.
jen Ending 'j' index on the high-resolution grid.
ilist List of 'i' indices on the high-resolution grid.
numx The number of 'i' indices on the high-resolution grid.
Author:
GFDL programmer
Definition at line 1729 of file mtnlm7_oclsm.F.
Referenced by make_mask(), makemt2(), makeoa2(), makeoa3(), and makepc2().
real function get_lat_angle (realdy, realDEGRAD)
Convert the 'y' direction distance of a cubed-sphere grid point to the corresponding distance in latitude.
Parameters:
dy Distance along the 'y' direction of a cubed-sphere point.
degrad Conversion from radians to degrees.
Returns:
get_lat_angle Corresponding distance in latitude.
Author:
GFDL programmer
Definition at line 3074 of file mtnlm7_oclsm.F.
Referenced by makeoa2().
real function get_lon_angle (realdx, reallat, realDEGRAD)
Convert the 'x' direction distance of a cubed-sphere grid point to the corresponding distance in longitude.
Parameters:
dx Distance along the 'x' direction of a cubed-sphere grid point.
lat Latitude of the cubed-sphere point.
degrad Conversion from radians to degrees.
Returns:
get_lon_angle Corresponding distance in longitude.
Author:
GFDL programmer
Definition at line 3055 of file mtnlm7_oclsm.F.
Referenced by makeoa2().
subroutine get_mismatch_index (integer, intent(in)im_in, integer, intent(in)jm_in, real, dimension(im_in,jm_in), intent(in)geolon_in, real, dimension(im_in,jm_in), intent(in)geolat_in, logical*1, dimension(im_in,jm_in), intent(in)bitmap_in, integer, intent(in)num_out, real, dimension(num_out), intent(in)lon_out, real, dimension(num_out), intent(in)lat_out, integer, dimension(num_out), intent(out)iindx, integer, dimension(num_out), intent(out)jindx)
For unmapped land points, find the nearest land point on the input data and pass back its i/j index.
Parameters:
im_in 'i' dimension of input data.
jm_in 'j' dimension of input data.
geolon_in Longitude of input data.
geolat_in Latitude of input data.
bitmap_in Bitmap (mask) of input data.
num_out Number of unmapped points.
lon_out Longitude of unmapped points.
lat_out Latitude of unmapped points.
iindx 'i' indices of nearest land points on the input data.
jindx 'j' indices of nearest land points on the input data.
Author:
GFDL progammer
Definition at line 3549 of file mtnlm7_oclsm.F.
References spherical_distance().
Referenced by makeoa3().
real function get_xnsum (real, intent(in)lon1, real, intent(in)lat1, real, intent(in)lon2, real, intent(in)lat2, integer, intent(in)IMN, integer, intent(in)JMN, real, dimension(jmn), intent(in)glat, integer, dimension(imn,jmn), intent(in)zavg, integer, dimension(imn,jmn), intent(in)zslm, real, intent(in)delxn)
Count the number of high-resolution orography points that are higher than the model grid box average orography height.
Parameters:
lon1 Longitude of corner point 1 of the model grid box.
lat1 Latitude of corner point 1 of the model grid box.
lon2 Longitude of corner point 2 of the model grid box.
lat2 Latitude of corner point 2 of the model grid box.
imn 'i' dimension of the high-resolution orography data.
jmn 'j' dimension of the high-resolution orography data.
glat Latitude of each row of the high-resolution orography data.
zavg The high-resolution orography.
zslm The high-resolution land mask.
delxn Resolution of the high-res orography data.
Returns:
get_xnsum The number of high-res points above the mean orography.
Author:
GFDL Programmer
Definition at line 4634 of file mtnlm7_oclsm.F.
Referenced by makeoa2().
subroutine get_xnsum2 (reallon1, reallat1, reallon2, reallat2, integerIMN, integerJMN, real, dimension(jmn)glat, integer, dimension(imn,jmn)zavg, realdelxn, real, intent(out)xnsum1, real, intent(out)xnsum2, real, intent(out)HC)
Count the number of high-resolution orography points that are higher than a critical value inside a model grid box (or a portion of a model grid box). The critical value is a function of the standard deviation of orography.
Parameters:
lon1 Longitude of corner point 1 of the model grid box.
lat1 Latitude of corner point 1 of the model grid box.
lon2 Longitude of corner point 2 of the model grid box.
lat2 Latitude of corner point 2 of the model grid box.
imn 'i' dimension of the high-resolution orography data.
jmn 'j' dimension of the high-resolution orography data.
glat Latitude of each row of the high-resolution orography data.
zavg The high-resolution orography.
delxn Resolution of the high-res orography data.
xnsum1 The number of high-resolution orography above the critical value inside a model grid box.
xnsum2 The number of high-resolution orography points inside a model grid box.
hc Critical height.
Author:
GFDL Programmer
Definition at line 4740 of file mtnlm7_oclsm.F.
Referenced by makeoa2().
subroutine get_xnsum3 (reallon1, reallat1, reallon2, reallat2, integerIMN, integerJMN, real, dimension(jmn)glat, integer, dimension(imn,jmn)zavg, realdelxn, real, intent(out)xnsum1, real, intent(out)xnsum2, realHC)
Count the number of high-resolution orography points that are higher than a critical value inside a model grid box (or a portion of a model grid box). Unlike routine get_xnsum2(), this routine does not compute the critical value. Rather, it is passed in.
Parameters:
lon1 Longitude of corner point 1 of the model grid box.
lat1 Latitude of corner point 1 of the model grid box.
lon2 Longitude of corner point 2 of the model grid box.
lat2 Latitude of corner point 2 of the model grid box.
imn 'i' dimension of the high-resolution orography data.
jmn 'j' dimension of the high-resolution orography data.
glat Latitude of each row of the high-resolution orography data.
zavg The high-resolution orography.
delxn Resolution of the high-res orography data.
xnsum1 The number of high-resolution orography above the critical value inside a model grid box.
xnsum2 The number of high-resolution orography points inside a model grid box.
hc Critical height.
Author:
GFDL Programmer
Definition at line 4835 of file mtnlm7_oclsm.F.
Referenced by makeoa2().
subroutine gg2rg (integer, intent(in)im, integer, intent(in)jm, integer, dimension(jm), intent(in)numi, real, dimension(im,jm), intent(inout)a)
Convert from a full grid to a reduced grid.
Parameters:
im 'i' dimension of the full grid.
jm 'j' dimension of the full grid.
numi Number of 'i' points for each row of the reduced grid.
a The data to be converted.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4152 of file mtnlm7_oclsm.F.
logical function inside_a_polygon (reallon1, reallat1, integernpts, real, dimension(npts)lon2, real, dimension(npts)lat2)
Check if a point is inside a polygon.
Parameters:
lon1 Longitude of the point to check.
lat1 Latitude of the point to check.
npts Number of polygon vertices.
lon2 Longitude of the polygon vertices.
lat2 Latitude of the polygon vertices.
Returns:
inside_a_polygon When true, point is within the polygon.
Author:
GFDL programmer
Definition at line 4539 of file mtnlm7_oclsm.F.
References latlon2xyz(), and spherical_angle().
Referenced by make_mask(), makemt2(), makeoa2(), makeoa3(), and makepc2().
subroutine interpolate_mismatch (integer, intent(in)im_in, integer, intent(in)jm_in, real, dimension(im_in,jm_in), intent(in)data_in, integer, intent(in)num_out, real, dimension(num_out), intent(out)data_out, integer, dimension(num_out), intent(in)iindx, integer, dimension(num_out), intent(in)jindx)
Replace unmapped model land points with the nearest land point on the input grid.
Parameters:
im_in 'i' dimension of input grid.
jm_in 'j' dimension of input grid.
data_in Input grid data.
num_out Number of unmapped model points.
data_out Data on the model tile.
iindx 'i' indices of the nearest land points on the input grid.
jindx 'j' indices of the nearest land points on the input grid.
Author:
GFDL programmer
Definition at line 3630 of file mtnlm7_oclsm.F.
Referenced by makeoa3().
subroutine latlon2xyz (integer, intent(in)siz, real, dimension(siz), intent(in)lon, real, dimension(siz), intent(in)lat, real, dimension(siz), intent(out)x, real, dimension(siz), intent(out)y, real, dimension(siz), intent(out)z)
Convert from latitude and longitude to x,y,z coordinates.
Parameters:
siz Number of points to convert.
lon Longitude of points to convert.
lat Latitude of points to convert.
x 'x' coordinate of the converted points.
y 'y' coordinate of the converted points.
z 'z' coordinate of the converted points.
Author:
GFDL programmer
Definition at line 4467 of file mtnlm7_oclsm.F.
Referenced by inside_a_polygon().
subroutine make_mask (integer, dimension(imn,jmn)zslm, real, dimension(im,jm)SLM, real, dimension(im,jm)land_frac, real, dimension(jmn)GLAT, integerIM, integerJM, integerIMN, integerJMN, real, dimension(im+1,jm+1)lon_c, real, dimension(im+1,jm+1)lat_c)
Create the land-mask, land fraction. This routine is used for the FV3GFS model.
Parameters:
zslm The high-resolution input land-mask dataset.
slm Land-mask on the model tile.
land_frac Land fraction on the model tile.
glat Latitude of each row of the high-resolution orography and land-mask datasets.
im 'i' dimension of the model grid.
jm 'j' dimension of the model grid.
imn 'i' dimension of the hi-res input orog/mask datasets.
jmn 'j' dimension of the hi-res input orog/mask datasets.
lon_c Longitude of the model grid corner points.
lat_c Latitude on the model grid corner points.
Author:
GFDL Programmer
Definition at line 1818 of file mtnlm7_oclsm.F.
References get_index(), and inside_a_polygon().
Referenced by tersub().
subroutine makemt (integer, dimension(imn,jmn)ZAVG, integer, dimension(imn,jmn)ZSLM, dimension(im,jm)ORO, dimension(im,jm)SLM, dimension(im,jm)VAR, dimension(im,jm)VAR4, dimension(jmn)GLAT, dimension(im,jm)IST, dimension(im,jm)IEN, dimension(jm)JST, dimension(jm)JEN, IM, JM, IMN, JMN, dimension(jm)XLAT, dimension(jm)numi)
Create the orography, land-mask, standard deviation of orography and the convexity on a model gaussian grid. This routine was used for the spectral GFS model.
Parameters:
zavg The high-resolution input orography dataset.
zslm The high-resolution input land-mask dataset.
oro Orography on the model grid.
slm Land-mask on the model grid.
var Standard deviation of orography on the model grid.
var4 Convexity on the model grid.
glat Latitude of each row of the high-resolution orography and land-mask datasets.
ist This is the 'i' index of high-resolution data set at the east edge of the model grid cell. the high-resolution dataset with respect to the 'east' edge
ien This is the 'i' index of high-resolution data set at the west edge of the model grid cell.
jst This is the 'j' index of high-resolution data set at the south edge of the model grid cell.
jen This is the 'j' index of high-resolution data set at the north edge of the model grid cell.
im 'i' dimension of the model grid.
jm 'j' dimension of the model grid.
imn 'i' dimension of the hi-res input orog/mask dataset.
jmn 'j' dimension of the hi-res input orog/mask dataset.
xlat The latitude of each row of the model grid.
numi For reduced gaussian grids, the number of 'i' points for each 'j' row.
Author:
Jordan Alpert NOAA/EMC
Definition at line 1566 of file mtnlm7_oclsm.F.
Referenced by tersub().
subroutine makemt2 (integer, dimension(imn,jmn)ZAVG, integer, dimension(imn,jmn)ZSLM, real, dimension(im,jm)ORO, real, dimension(im,jm), intent(in)SLM, real, dimension(im,jm)VAR, real, dimension(im,jm)VAR4, real, dimension(jmn)GLAT, integerIM, integerJM, integerIMN, integerJMN, real, dimension(im+1,jm+1)lon_c, real, dimension(im+1,jm+1)lat_c, real, dimension(im,jm), intent(in)lake_frac, real, dimension(im,jm), intent(in)land_frac)
Create the orography, land-mask, land fraction, standard deviation of orography and the convexity on a model cubed-sphere tile. This routine is used for the FV3GFS model.
Parameters:
zavg The high-resolution input orography dataset.
zslm The high-resolution input land-mask dataset.
oro Orography on the model tile.
slm Land-mask on the model tile.
var Standard deviation of orography on the model tile.
var4 Convexity on the model tile.
glat Latitude of each row of the high-resolution orography and land-mask datasets.
im 'i' dimension of the model grid.
jm 'j' dimension of the model grid.
imn 'i' dimension of the hi-res input orog/mask datasets.
jmn 'j' dimension of the hi-res input orog/mask datasets.
lon_c Longitude of the model grid corner points.
lat_c Latitude on the model grid corner points.
lake_frac Fractional lake within the grid
land_frac Fractional land within the grid
Author:
GFDL Programmer
Definition at line 1951 of file mtnlm7_oclsm.F.
References get_index(), inside_a_polygon(), and lake_frac().
Referenced by tersub().
subroutine makeoa (integer, dimension(imn,jmn)ZAVG, dimension(im,jm)VAR, dimension(jmn)GLAT, dimension(im,jm,4)OA4, dimension(im,jm,4)OL, dimension(im,jm,4)IOA4, dimension(im,jm)ELVMAX, dimension(im,jm)ORO, dimension(im,jm)oro1, dimension(im,jm)XNSUM, dimension(im,jm)XNSUM1, dimension(im,jm)XNSUM2, dimension(im,jm)XNSUM3, dimension(im,jm)XNSUM4, dimension(im,jm)IST, dimension(im,jm)IEN, dimension(jm)JST, dimension(jm)JEN, IM, JM, IMN, JMN, dimension(jm)XLAT, dimension(jm)numi)
Create orographic asymmetry and orographic length scale on the model grid. This routine is used for the spectral GFS gaussian grid.
Parameters:
zavg The high-resolution input orography dataset.
var Standard deviation of orography on the model grid.
glat Latitude of each row of input terrain dataset.
oa4 Orographic asymmetry on the model grid. Four directional components - W/S/SW/NW
ol Orographic length scale on the model grid. Four directional components - W/S/SW/NW
ioa4 Count of oa4 values between certain thresholds.
elvmax Maximum elevation on the model grid.
oro Orography on the model grid.
oro1 Save array for model grid orography.
xnsum Number of high-resolution orography points higher than the model grid box average.
xnsum1 Number of high-resolution orography points higher than the critical height.
xnsum2 Total number of high-resolution orography points within a model grid box.
xnsum3 Same as xnsum1, except shifted by half a model grid box.
xnsum4 Same as xnsum2, except shifted by half a model grid box.
ist This is the 'i' index of high-resolution data set at the east edge of the model grid cell.
ien This is the 'i' index of high-resolution data set at the west edge of the model grid cell.
jst This is the 'j' index of high-resolution data set at the south edge of the model grid cell.
jen This is the 'j' index of high-resolution data set at the north edge of the model grid cell.
im 'i' dimension of the model grid.
jm 'j' dimension of the model grid.
imn 'i' dimension of the input terrain dataset.
jmn 'j' dimension of the input terrain dataset.
xlat The latitude of each row of the model grid.
numi For reduced gaussian grids, the number of 'i' points for each 'j' row.
Author:
Jordan Alpert NOAA/EMC
Definition at line 2727 of file mtnlm7_oclsm.F.
Referenced by tersub().
subroutine makeoa2 (integer, dimension(imn,jmn)ZAVG, integer, dimension(imn,jmn)zslm, real, dimension(im,jm)VAR, real, dimension(jmn)GLAT, real, dimension(im,jm,4)OA4, real, dimension(im,jm,4)OL, integer, dimension(im,jm,4)IOA4, real, dimension(im,jm)ELVMAX, real, dimension(im,jm)ORO, real, dimension(im,jm)oro1, real, dimension(im,jm)XNSUM, real, dimension(im,jm)XNSUM1, real, dimension(im,jm)XNSUM2, real, dimension(im,jm)XNSUM3, real, dimension(im,jm)XNSUM4, integerIM, integerJM, integerIMN, integerJMN, real, dimension(im+1,jm+1)lon_c, real, dimension(im+1,jm+1)lat_c, real, dimension(im,jm)lon_t, real, dimension(im,jm)lat_t, real, dimension(im,jm)dx, real, dimension(im,jm)dy, logical, dimension(im,jm)is_south_pole, logical, dimension(im,jm)is_north_pole)
Create orographic asymmetry and orographic length scale on the model grid. This routine is used for the cubed-sphere grid.
Parameters:
zavg High-resolution orography data.
zslm High-resolution land-mask data.
var Standard deviation of orography on the model grid.
glat Latitude of each row of input terrain dataset.
oa4 Orographic asymmetry on the model grid. Four directional components - W/S/SW/NW
ol Orographic length scale on the model grid. Four directional components - W/S/SW/NW
ioa4 Count of oa4 values between certain thresholds.
elvmax Maximum elevation within a model grid box.
oro Orography on the model grid.
oro1 Save array for model grid orography.
xnsum Not used.
xnsum1 Not used.
xnsum2 Not used.
xnsum3 Not used.
xnsum4 Not used.
im 'i' dimension of the model grid tile.
jm 'j' dimension of the model grid tile.
imn 'i' dimension of the high-resolution orography and mask data.
jmn 'j' dimension of the high-resolution orography and mask data.
lon_c Corner point longitudes of the model grid points.
lat_c Corner point latitudes of the model grid points.
lon_t Center point longitudes of the model grid points.
lat_t Center point latitudes of the model grid points.
dx Length of model grid points in the 'x' direction.
dy Length of model grid points in the 'y' direction.
is_south_pole Is the model point at the south pole?
is_north_pole is the model point at the north pole?
Author:
GFDL Programmer
Definition at line 3121 of file mtnlm7_oclsm.F.
References get_index(), get_lat_angle(), get_lon_angle(), get_xnsum(), get_xnsum2(), get_xnsum3(), and inside_a_polygon().
Referenced by tersub().
subroutine makeoa3 (integer, dimension(imn,jmn)ZAVG, integer, dimension(imn,jmn)zslm, real, dimension(im,jm)VAR, real, dimension(jmn)GLAT, real, dimension(im,jm,4)OA4, real, dimension(im,jm,4)OL, integer, dimension(im,jm,4)IOA4, real, dimension(im,jm)ELVMAX, real, dimension(im,jm)ORO, real, dimension(im,jm)SLM, real, dimension(im,jm)oro1, real, dimension(im,jm)XNSUM, real, dimension(im,jm)XNSUM1, real, dimension(im,jm)XNSUM2, real, dimension(im,jm)XNSUM3, real, dimension(im,jm)XNSUM4, integerIM, integerJM, integerIMN, integerJMN, real, dimension(im+1,jm+1)lon_c, real, dimension(im+1,jm+1)lat_c, real, dimension(im,jm)lon_t, real, dimension(im,jm)lat_t, logical, dimension(im,jm)is_south_pole, logical, dimension(im,jm)is_north_pole, integerIMI, integerJMI, real, dimension(imi,jmi,4)OA_IN, real, dimension(imi,jmi,4)OL_IN, real, dimension(imi,jmi)slm_in, real, dimension(imi,jmi)lon_in, real, dimension(imi,jmi)lat_in)
Create orographic asymmetry and orographic length scale on the model grid. This routine is used for the cubed-sphere grid. The asymmetry and length scales are interpolated from an existing gfs orography file. The maximum elevation is computed from the high-resolution orography data.
Parameters:
zavg High-resolution orography data.
zslm High-resolution land-mask data. Not used.
var Standard deviation of orography on the model grid.
glat Latitude of each row of input terrain dataset.
oa4 Orographic asymmetry on the model grid. Four directional components - W/S/SW/NW
ol Orographic length scale on the model grid. Four directional components - W/S/SW/NW
ioa4 Count of oa4 values between certain thresholds.
elvmax Maximum elevation within a model grid box.
slm Land-mask on model grid.
oro Orography on the model grid.
oro1 Save array for model grid orography.
xnsum Not used.
xnsum1 Not used.
xnsum2 Not used.
xnsum3 Not used.
xnsum4 Not used.
im 'i' dimension of the model grid tile.
jm 'j' dimension of the model grid tile.
imn 'i' dimension of the high-resolution orography and mask data.
jmn 'j' dimension of the high-resolution orography and mask data.
lon_c Corner point longitudes of the model grid points.
lat_c Corner point latitudes of the model grid points.
lon_t Center point longitudes of the model grid points.
lat_t Center point latitudes of the model grid points.
is_south_pole Not used.
is_north_pole Not used.
imi 'i' dimension of input gfs orography data.
jmi 'j' dimension of input gfs orography data.
oa_in Asymmetry on the input gfs orography data.
ol_in Length scales on the input gfs orography data.
slm_in Land-sea mask on the input gfs orography data.
lon_in Longitude on the input gfs orography data.
lat_in Latitude on the input gfs orography data.
Author:
Jordan Alpert NOAA/EMC
Definition at line 3687 of file mtnlm7_oclsm.F.
References get_index(), get_mismatch_index(), inside_a_polygon(), and interpolate_mismatch().
Referenced by tersub().
subroutine makepc (integer, dimension(imn,jmn)ZAVG, integer, dimension(imn,jmn)ZSLM, dimension(im,jm)THETA, dimension(im,jm)GAMMA, dimension(im,jm)SIGMA, dimension(jmn)GLAT, dimension(im,jm)IST, dimension(im,jm)IEN, dimension(jm)JST, dimension(jm)JEN, IM, JM, IMN, JMN, dimension(jm)XLAT, dimension(jm)numi)
Make the principle coordinates - slope of orography, anisotropy, angle of mountain range with respect to east. This routine is used for spectral GFS gaussian grids.
Parameters:
zavg The high-resolution input orography dataset.
zslm The high-resolution input land-mask dataset.
theta Angle of mountain range with respect to east for each model point.
gamma Anisotropy for each model point.
sigma Slope of orography for each model point.
glat Latitude of each row of the high-resolution orography and land-mask datasets.
ist This is the 'i' index of high-resolution data set at the east edge of the model grid cell.
ien This is the 'i' index of high-resolution data set at the west edge of the model grid cell.
jst This is the 'j' index of high-resolution data set at the south edge of the model grid cell.
jen This is the 'j' index of high-resolution data set at the north edge of the model grid cell.
im 'i' dimension of the model grid tile.
jm 'j' dimension of the model grid tile.
imn 'i' dimension of the hi-res input orog/mask datasets.
jmn 'j' dimension of the hi-res input orog/mask datasets.
xlat The latitude of each row of the model grid.
numi For reduced gaussian grids, the number of 'i' points for each 'j' row.
Author:
Jordan Alpert NOAA/EMC
Definition at line 2184 of file mtnlm7_oclsm.F.
Referenced by tersub().
subroutine makepc2 (integer, dimension(imn,jmn)ZAVG, integer, dimension(imn,jmn)ZSLM, real, dimension(im,jm)THETA, real, dimension(im,jm)GAMMA, real, dimension(im,jm)SIGMA, real, dimension(jmn)GLAT, integerIM, integerJM, integerIMN, integerJMN, real, dimension(im+1,jm+1)lon_c, real, dimension(im+1,jm+1)lat_c, real, dimension(im,jm), intent(in)SLM)
Make the principle coordinates - slope of orography, anisotropy, angle of mountain range with respect to east. This routine is used for the FV3GFS cubed-sphere grid.
Parameters:
zavg The high-resolution input orography dataset.
zslm The high-resolution input land-mask dataset.
theta Angle of mountain range with respect to east for each model point.
gamma Anisotropy for each model point.
sigma Slope of orography for each model point.
glat Latitude of each row of the high-resolution orography and land-mask datasets.
im 'i' dimension of the model grid tile.
jm 'j' dimension of the model grid tile.
imn 'i' dimension of the hi-res input orog/mask datasets.
jmn 'j' dimension of the hi-res input orog/mask datasets.
lon_c Longitude of model grid corner points.
lat_c Latitude of the model grid corner points.
SLM mask
Author:
GFDL Programmer
Definition at line 2459 of file mtnlm7_oclsm.F.
References get_index(), and inside_a_polygon().
Referenced by tersub().
subroutine maxmin (integer*2, dimension(len)ia, integerlen, character*7tile)
Print the maximum, mininum, mean and standard deviation of an array.
Parameters:
ia The array to be checked.
len The number of points to be checked.
tile A name associated with the array.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4357 of file mtnlm7_oclsm.F.
Referenced by read_g().
subroutine minmaxj (integerIM, integerJM, real(kind=4), dimension(im,jm)A, character*8title)
Print out the maximum and minimum values of an array and their i/j location. Also print out the number of undefined points.
Parameters:
im The 'i' dimension of the array.
jm The 'i' dimension of the array.
a The array to check.
title Name of the data to be checked.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4415 of file mtnlm7_oclsm.F.
subroutine minmxj (integerIM, integerJM, real, dimension(im,jm)A, character*8title)
Print out the maximum and minimum values of an array.
Parameters:
im The 'i' dimension of the array.
jm The 'i' dimension of the array.
a The array to check.
title Name of the data to be checked.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4178 of file mtnlm7_oclsm.F.
Referenced by tersub().
subroutine mnmxja (integerIM, integerJM, real, dimension(im,jm)A, integerimax, integerjmax, character*8title)
Print out the maximum and minimum values of an array. Pass back the i/j location of the maximum value.
Parameters:
im The 'i' dimension of the array.
jm The 'i' dimension of the array.
a The array to check.
imax 'i' location of maximum
jmax 'j' location of maximum
title Name of the data to be checked.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4213 of file mtnlm7_oclsm.F.
Referenced by tersub().
subroutine nanc (a, l, character*(*)c)
Report NaNS and NaNQ within an address range for 8-byte real words. This routine prints a single line for each call and prints a message and returns to the caller on detection of the FIRST NaN in the range. If no NaN values are found it returns silently.
Parameters:
A Real*8 variable or array
L Number of words to scan (length of array)
C Distinctive message set in caller to indicate where the routine was called.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4899 of file mtnlm7_oclsm.F.
subroutine read_g (integer*2, dimension(360*120,180*120), intent(out)glob)
Read input global 30-arc second orography data.
Parameters:
glob The orography data.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4324 of file mtnlm7_oclsm.F.
References maxmin(), and netcdf_err().
Referenced by tersub().
subroutine revers (IM, JM, integer, dimension(jm)numi, real, dimension(im,jm)F, real, dimension(im,jm)WRK)
Reverse the east-west and north-south axes in a two-dimensional array.
Parameters:
im 'i' dimension of the 2-d array.
jm 'j' dimension of the 2-d array.
numi Not used.
f The two-dimensional array to be processed.
wrk Two-dimensional work array.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4089 of file mtnlm7_oclsm.F.
Referenced by tersub().
subroutine rg2gg (integer, intent(in)im, integer, intent(in)jm, integer, dimension(jm), intent(in)numi, real, dimension(im,jm), intent(inout)a)
Convert from a reduced grid to a full grid.
Parameters:
im 'i' dimension of the full grid.
jm 'j' dimension of the full grid.
numi Number of 'i' points for each row of the reduced grid.
a The data to be converted.
Author:
Jordan Alpert NOAA/EMC
Definition at line 4126 of file mtnlm7_oclsm.F.
Referenced by tersub().
subroutine spfft1 (integer, intent(in)IMAX, integer, intent(in)INCW, integer, intent(in)INCG, integer, intent(in)KMAX, complex, dimension(incw,kmax), intent(inout)W, real, dimension(incg,kmax), intent(inout)G, integer, intent(in)IDIR)
Perform multiple fast fourier transforms. This subprogram performs multiple fast fourier transforms between complex amplitudes in fourier space and real values in cyclic physical space.
Subprograms called (NCEPLIB SP Library):
scrft Complex to real fourier transform
dcrft Complex to real fourier transform
srcft Real to complex fourier transform
drcft Real to complex fourier transform
Program history log: 1998-12-18 Mark Iredell
Parameters:
imax Integer number of values in the cyclic physical space. See limitations on imax in remarks below.
incw Integer first dimension of the complex amplitude array. (incw >= imax/2+1).
incg Integer first dimension of the real value array. (incg >= imax).
kmax Integer number of transforms to perform.
w Complex amplitudes on input if idir>0, and on output if idir<0.
g Real values on input if idir<0, and on output if idir>0.
idir Integer direction flag. idir>0 to transform from fourier to physical space. idir<0 to transform from physical to fourier space.
Note:
The restrictions on imax are that it must be a multiple of 1 to 25 factors of two, up to 2 factors of three, and up to 1 factor of five, seven and eleven.
Author:
Mark Iredell ORG: W/NMC23
Date:
96-02-20
Definition at line 4275 of file mtnlm7_oclsm.F.
Referenced by tersub().
real function spherical_angle (real, dimension(3)v1, real, dimension(3)v2, real, dimension(3)v3)
Compute spherical angle.
Parameters:
v1 Vector 1.
v2 Vector 2.
v3 Vector 3.
Returns:
spherical_angle Spherical Angle.
Author:
GFDL programmer
Definition at line 4489 of file mtnlm7_oclsm.F.
Referenced by inside_a_polygon().
real function spherical_distance (real, intent(in)theta1, real, intent(in)phi1, real, intent(in)theta2, real, intent(in)phi2)
Compute a great circle distance between two points.
Parameters:
theta1 Longitude of point 1.
phi1 Latitude of point 1.
theta2 Longitude of point 2.
phi2 Latitude of point2.
Returns:
spherical_distance Great circle distance.
Author:
GFDL programmer
Definition at line 3514 of file mtnlm7_oclsm.F.
Referenced by get_mismatch_index().
subroutine tersub (integerIMN, integerJMN, integerIM, integerJM, integerNM, integerNR, integerNF0, integerNF1, integerNW, integerEFAC, integerBLAT, character(len=*), intent(in)OUTGRID, character(len=*), intent(in)INPUTOROG, logical, intent(in)MASK_ONLY, character(len=*), intent(in)MERGE_FILE)
Driver routine to compute terrain.
Parameters:
IMN 'i' dimension of the input terrain dataset.
JMN 'j' dimension of the input terrain dataset.
IM 'i' dimension of the model grid tile.
JM 'j' dimension of the model grid tile.
NM Spectral truncation.
NR Rhomboidal flag.
NF0 First order spectral filter parameters.
NF1 Second order spectral filter parameters.
NW Number of waves.
EFAC Factor to adjust orography by its variance.
BLAT When less than zero, reverse latitude/ longitude for output.
OUTGRID The 'grid' file for the model tile.
INPUTOROG Input orography/GWD file on gaussian grid. When specified, will be interpolated to model tile. When not specified, program will create fields from raw high-resolution topography data.
MASK_ONLY Flag to generate the Land Mask only
MERGE_FILE Ocean merge file
Author:
Jordan Alpert NOAA/EMC
Definition at line 186 of file mtnlm7_oclsm.F.
References lake_frac(), make_mask(), makemt(), makemt2(), makeoa(), makeoa2(), makeoa3(), makepc(), makepc2(), minmxj(), mnmxja(), netcdf_err(), read_g(), read_mask(), revers(), rg2gg(), spfft1(), timef(), write_mask_netcdf(), and write_netcdf().
Referenced by __mtnlm7_oclsm.f__().
real function timef ()
Get the date/time for the system clock.
Author:
Mark Iredell
Returns:
timef
Definition at line 4947 of file mtnlm7_oclsm.F.
Referenced by tersub().
Author
Generated automatically by Doxygen for orog_mask_tools from the source code.