.TH "/home/ed/UFS_UTILS/sorc/orog_mask_tools.fd/orog.fd/netcdf_io.F90" 3 "Thu Mar 18 2021" "Version 1.0.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/UFS_UTILS/sorc/orog_mask_tools.fd/orog.fd/netcdf_io.F90 \- Write out data in netcdf format\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBnetcdf_err\fP (err, string)"
.br
.ti -1c
.RI "subroutine \fBwrite_netcdf\fP (im, jm, slm, land_frac, oro, orf, hprime, ntiles, tile, geolon, geolat, lon, lat)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Write out data in netcdf format\&. 


.PP
Definition in file \fBnetcdf_io\&.F90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for orog_mask_tools from the source code\&.
