.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/emcsfc_snow2mdl.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "emcsfc_snow2mdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/emcsfc_snow2mdl.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdriver\&.F90\fP"
.br
.RI "\fICreate a snow cover and snow depth analysis\&. \fP"
.ti -1c
.RI "file \fBgrib_utils\&.F90\fP"
.br
.RI "\fIDetermine whether file is grib or not\&. \fP"
.ti -1c
.RI "file \fBmodel_grid\&.F90\fP"
.br
.RI "\fIRead in data defining the model grid\&. \fP"
.ti -1c
.RI "file \fBprogram_setup\&.F90\fP"
.br
.RI "\fIThis module reads in data from the program's configuration\&. \fP"
.ti -1c
.RI "file \fBsnow2mdl\&.F90\fP"
.br
.RI "\fIInterpolate snow data to model grid and grib the result\&. \fP"
.ti -1c
.RI "file \fBsnowdat\&.F90\fP"
.br
.RI "\fIRead and qc afwa, nesdis/ims and autosnow snow data\&. \fP"
.in -1c
