.TH "md__lfs_h2_emc_global_noscrub_George.Gayno_ufs_utils.git_UFS_UTILS_sorc_emcsfc_snow2mdl.fd_docs_README" 3 "Mon Oct 23 2023" "Version 1.11.0" "emcsfc_snow2mdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__lfs_h2_emc_global_noscrub_George.Gayno_ufs_utils.git_UFS_UTILS_sorc_emcsfc_snow2mdl.fd_docs_README \- README 
This program blends National Ice Center snow cover and Air Force snow depth data to create a global depth analysis\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
