.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_nwp_base.f90" 3 "Tue Jan 17 2023" "Version 1.9.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_nwp_base.f90 \- Defines nwp observation data structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBmodule_nwp_base::nwpbase\fP"
.br
.ti -1c
.RI "type \fBmodule_nwp_base::nwplocation\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBmodule_nwp_base\fP"
.br
.RI "This module defines nwp observation data structure and the method to read and write observations from and to those data structures\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBmodule_nwp_base::alloc_obsbase\fP (this, numvar, ifquality)"
.br
.RI "This subroutine allocates memory for base nwp observation variables\&. "
.ti -1c
.RI "subroutine \fBmodule_nwp_base::destroy_obsbase\fP (this)"
.br
.RI "This subroutine releases memory associated with nwp observations\&. "
.ti -1c
.RI "subroutine \fBmodule_nwp_base::list_obsbase\fP (this)"
.br
.RI "This subroutine lists the contents of a base nwp observation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines nwp observation data structure\&. 


.PP
\fBAuthor:\fP
.RS 4
David Wright, University of Michigan and GLERL 
.RE
.PP
\fBDate:\fP
.RS 4
17 Aug 2020 
.RE
.PP

.PP
Definition in file \fBmodule_nwp_base\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
