.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_nwp.f90" 3 "Tue Jan 17 2023" "Version 1.9.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_nwp.f90 \- Defines FV3LAM and FVCOM forecast data structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBmodule_nwp::fcst_nwp\fP"
.br
.ti -1c
.RI "type \fBmodule_nwp::nwp_type\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBmodule_nwp\fP"
.br
.RI "This module defines FV3LAM and FVCOM forecast data structure and the method to read and write observations from and to those data structures\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBmodule_nwp::finish_nwp\fP (this, itype, wcstart)"
.br
.RI "Finish and deallocate\&. "
.ti -1c
.RI "subroutine \fBmodule_nwp::get_time_ind_nwp\fP (this, filename, instr, outindex)"
.br
.RI "This subroutine searches the FVCOM 'Times' variable and returns the matching index\&. "
.ti -1c
.RI "subroutine \fBmodule_nwp::initial_nwp\fP (this, itype, wcstart)"
.br
.RI "This subroutine defines the number of variables and their names for each NWP data type\&. "
.ti -1c
.RI "subroutine \fBmodule_nwp::list_initial_nwp\fP (this)"
.br
.RI "This subroutine lists the setup for NWP data that was done by the initial_nwp subroutine\&. "
.ti -1c
.RI "subroutine \fBmodule_nwp::read_nwp\fP (this, filename, itype, wcstart, numlon, numlat, numtimes, time_to_get, mask, sst, ice, sfcT, iceT, sfcTl, zorl, hice, ybegin, yend)"
.br
.RI "This subroutine initializes arrays to receive the NWP data, and opens the file and gets the data\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(ncio) \fBmodule_nwp::ncdata\fP"
.br
.RI "Wrapper object for netCDF data file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines FV3LAM and FVCOM forecast data structure\&. 


.PP
\fBAuthor:\fP
.RS 4
David Wright, University of Michigan and GLERL, 
.RE
.PP
\fBDate:\fP
.RS 4
17 Aug 2020 
.RE
.PP

.PP
Definition in file \fBmodule_nwp\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
