.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBatm_input_data\&.F90\fP"
.br
.RI "\fIRead atmospheric data from GRIB2, NEMSIO and NetCDF files\&. \fP"
.ti -1c
.RI "file \fBatmosphere\&.F90\fP"
.br
.RI "\fIProcess atmospheric fields\&. \fP"
.ti -1c
.RI "file \fBatmosphere_target_data\&.F90\fP"
.br
.RI "\fIDefine atmospheric target data variables\&. \fP"
.ti -1c
.RI "file \fBchgres\&.F90\fP"
.br
.RI "\fIInitialize an FV3 model run\&. \fP"
.ti -1c
.RI "file \fBgrib2_util\&.F90\fP"
.br
.RI "\fIUtilities for use when reading grib2 data\&. \fP"
.ti -1c
.RI "file \fBmodel_grid\&.F90\fP"
.br
.RI "\fISpecify input and target model grids\&. \fP"
.ti -1c
.RI "file \fBnst_input_data\&.F90\fP"
.br
.RI "\fIRead NST surface data from NEMSIO and NetCDF files\&. \fP"
.ti -1c
.RI "file \fBprogram_setup\&.F90\fP"
.br
.RI "\fISet up program execution\&. \fP"
.ti -1c
.RI "file \fBsearch_util\&.F90\fP"
.br
.RI "\fIReplace undefined surface values\&. \fP"
.ti -1c
.RI "file \fBsfc_input_data\&.F90\fP"
.br
.RI "\fIRead atmospheric and surface data from GRIB2, NEMSIO and NetCDF files\&. \fP"
.ti -1c
.RI "file \fBstatic_data\&.F90\fP"
.br
.RI "\fIProcess static surface data\&. \fP"
.ti -1c
.RI "file \fBsurface\&.F90\fP"
.br
.RI "\fIProcess land, sea/lake ice, open water/Near Sea Surface Temperature (NSST) fields\&. \fP"
.ti -1c
.RI "file \fBsurface_target_data\&.F90\fP"
.br
.RI "\fIDefine target grid surface data variables\&. \fP"
.ti -1c
.RI "file \fBthompson_mp_climo_data\&.F90\fP"
.br
.RI "\fIProcess Thompson climatological MP data\&. \fP"
.ti -1c
.RI "file \fButils\&.F90\fP"
.br
.RI "\fIContains utility routines\&. \fP"
.ti -1c
.RI "file \fBwam_climo_data\&.f90\fP"
.br
.RI "\fIProcess vertical profile climatologic data for WAM\&. \fP"
.ti -1c
.RI "file \fBwrite_data\&.F90\fP"
.br
.RI "\fIWrites the tiled and header files expected by the forecast model\&. \fP"
.in -1c
