.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/chgres.F90" 3 "Thu Feb 15 2024" "Version 1.12.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/chgres.F90 \- 
.PP
Initialize an FV3 model run\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBchgres\fP"
.br
.RI "\fIInitialize an FV3 model run\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Initialize an FV3 model run\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NOAA/EMC 
.RE
.PP

.PP
Definition in file \fBchgres\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program chgres ()"

.PP
Initialize an FV3 model run\&. Initialize an FV3 run using history or restart data from another FV3 run, the spectral GFS, and a few other models\&. Converts atmospheric, surface and nst data\&.
.PP
This file reads a configuration namelist\&.
.PP
Link the configuration namelist to \&./fort\&.41\&. Then run the program with a multiple of six mpi tasks (an ESMF library requirement for fv3 cubed sphere grids)\&.
.PP
\fBNote:\fP
.RS 4
For variable names “input” refers to the data input to the program (i\&.e\&., GRIB2, NEMSIO, NetCDF)\&. “Target” refers to the target or FV3 model grid\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NOAA/EMC 
.RE
.PP
\fBReturns:\fP
.RS 4
0 for success, error code otherwise\&. 
.RE
.PP

.PP
Definition at line 24 of file chgres\&.F90\&.
.PP
References atmosphere::atmosphere_driver(), model_grid::cleanup_input_target_grid_data(), model_grid::define_input_grid(), model_grid::define_target_grid(), utilities::error_handler(), program_setup::read_setup_namelist(), program_setup::read_varmap(), and surface::surface_driver()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
