/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/chgres.F90
NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/chgres.F90 -
Initialize an FV3 model run.
SYNOPSIS
Functions/Subroutines
program chgres
Initialize an FV3 model run.
Detailed Description
Initialize an FV3 model run.
Author:
George Gayno NOAA/EMC
Definition in file chgres.F90.
Function/Subroutine Documentation
program chgres ()
Initialize an FV3 model run. Initialize an FV3 run using history or restart data from another FV3 run, the spectral GFS, and a few other models. Converts atmospheric, surface and nst data.
This file reads a configuration namelist.
Link the configuration namelist to ./fort.41. Then run the program with a multiple of six mpi tasks (an ESMF library requirement for fv3 cubed sphere grids).
Note:
For variable names “input” refers to the data input to the program (i.e., GRIB2, NEMSIO, NetCDF). “Target” refers to the target or FV3 model grid.
Author:
George Gayno NOAA/EMC
Returns:
0 for success, error code otherwise.
Definition at line 24 of file chgres.F90.
References atmosphere::atmosphere_driver(), model_grid::cleanup_input_target_grid_data(), model_grid::define_input_grid(), model_grid::define_target_grid(), utilities::error_handler(), program_setup::read_setup_namelist(), program_setup::read_varmap(), and surface::surface_driver().
Author
Generated automatically by Doxygen for chgres_cube from the source code.