.TH "nst_input_data" 3 "Thu Feb 15 2024" "Version 1.12.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nst_input_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine, public \fBcleanup_input_nst_data\fP"
.br
.RI "\fIFree up memory associated with nst data\&. \fP"
.ti -1c
.RI "subroutine, public \fBread_input_nst_data\fP (localpet)"
.br
.RI "\fIDriver to read input grid nst data\&. \fP"
.ti -1c
.RI "subroutine \fBread_input_nst_nemsio_file\fP (localpet)"
.br
.RI "\fIRead input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file\&. \fP"
.ti -1c
.RI "subroutine \fBread_input_nst_netcdf_file\fP (localpet)"
.br
.RI "\fIRead nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "type(esmf_field), public \fBc_0_input_grid\fP"
.br
.RI "\fICoefficient 1 to calculate d(tz)/d(ts) \fP"
.ti -1c
.RI "type(esmf_field), public \fBc_d_input_grid\fP"
.br
.RI "\fICoefficient 2 to calculate d(tz)/d(ts) \fP"
.ti -1c
.RI "type(esmf_field), public \fBd_conv_input_grid\fP"
.br
.RI "\fIThickness of free convectionlayer\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBdt_cool_input_grid\fP"
.br
.RI "\fISub-layer cooling amount\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBifd_input_grid\fP"
.br
.RI "\fIModel mode index\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBqrain_input_grid\fP"
.br
.RI "\fISensible heat flux due torainfall\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBtref_input_grid\fP"
.br
.RI "\fIReference temperature\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBw_0_input_grid\fP"
.br
.RI "\fICoefficient 3 to calculated(tz)/d(ts) \fP"
.ti -1c
.RI "type(esmf_field), public \fBw_d_input_grid\fP"
.br
.RI "\fICoefficient 4 to calculated(tz)/d(ts) \fP"
.ti -1c
.RI "type(esmf_field), public \fBxs_input_grid\fP"
.br
.RI "\fISalinity content in diurnalthermocline layer\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBxt_input_grid\fP"
.br
.RI "\fIHeat content in diurnalthermocline layer\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBxtts_input_grid\fP"
.br
.RI "\fId(xt)/d(ts) \fP"
.ti -1c
.RI "type(esmf_field), public \fBxu_input_grid\fP"
.br
.RI "\fIu-current content in diurnalthermocline layer \fP"
.ti -1c
.RI "type(esmf_field), public \fBxv_input_grid\fP"
.br
.RI "\fIv-current content in diurnalthermocline layer \fP"
.ti -1c
.RI "type(esmf_field), public \fBxz_input_grid\fP"
.br
.RI "\fIDiurnal thermocline layerthickness\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBxzts_input_grid\fP"
.br
.RI "\fId(xz)/d(ts) \fP"
.ti -1c
.RI "type(esmf_field), public \fBz_c_input_grid\fP"
.br
.RI "\fISub-layer cooling thickness\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBzm_input_grid\fP"
.br
.RI "\fIOceanic mixed layer depth\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file nst_input_data\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine, public nst_input_data::cleanup_input_nst_data ()"

.PP
Free up memory associated with nst data\&. 
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 782 of file nst_input_data\&.F90\&.
.PP
Referenced by surface::surface_driver()\&.
.SS "subroutine, public nst_input_data::read_input_nst_data (integer, intent(in)localpet)"

.PP
Driver to read input grid nst data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP ESMF local persistent execution thread 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 67 of file nst_input_data\&.F90\&.
.PP
References utilities::error_handler(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file()\&.
.PP
Referenced by surface::surface_driver()\&.
.SS "subroutine nst_input_data::read_input_nst_nemsio_file (integer, intent(in)localpet)"

.PP
Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file\&. 
.PP
\fBNote:\fP
.RS 4
The spectral GFS nst data is in a separate file from the surface data\&. The fv3 surface and nst data are in a single file\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP ESMF local persistent execution thread 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 514 of file nst_input_data\&.F90\&.
.PP
References utilities::error_handler()\&.
.PP
Referenced by read_input_nst_data()\&.
.SS "subroutine nst_input_data::read_input_nst_netcdf_file (integer, intent(in)localpet)"

.PP
Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP ESMF local persistent execution thread 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 230 of file nst_input_data\&.F90\&.
.PP
References utilities::error_handler(), and sfc_input_data::read_fv3_grid_data_netcdf()\&.
.PP
Referenced by read_input_nst_data()\&.
.SH "Field Documentation"
.PP 
.SS "type(esmf_field), public nst_input_data::c_0_input_grid"

.PP
Coefficient 1 to calculate d(tz)/d(ts) 
.PP
Definition at line 39 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::c_d_input_grid"

.PP
Coefficient 2 to calculate d(tz)/d(ts) 
.PP
Definition at line 38 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::d_conv_input_grid"

.PP
Thickness of free convectionlayer\&. 
.PP
Definition at line 40 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::dt_cool_input_grid"

.PP
Sub-layer cooling amount\&. 
.PP
Definition at line 41 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::ifd_input_grid"

.PP
Model mode index\&. 0-diurnalmodel not started; 1-diurnal model 
.PP
Definition at line 42 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::qrain_input_grid"

.PP
Sensible heat flux due torainfall\&. 
.PP
Definition at line 45 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::tref_input_grid"

.PP
Reference temperature\&. 
.PP
Definition at line 46 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::w_0_input_grid"

.PP
Coefficient 3 to calculated(tz)/d(ts) 
.PP
Definition at line 48 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::w_d_input_grid"

.PP
Coefficient 4 to calculated(tz)/d(ts) 
.PP
Definition at line 47 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xs_input_grid"

.PP
Salinity content in diurnalthermocline layer\&. 
.PP
Definition at line 49 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xt_input_grid"

.PP
Heat content in diurnalthermocline layer\&. 
.PP
Definition at line 50 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xtts_input_grid"

.PP
d(xt)/d(ts) 
.PP
Definition at line 54 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xu_input_grid"

.PP
u-current content in diurnalthermocline layer 
.PP
Definition at line 51 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xv_input_grid"

.PP
v-current content in diurnalthermocline layer 
.PP
Definition at line 52 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xz_input_grid"

.PP
Diurnal thermocline layerthickness\&. 
.PP
Definition at line 53 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xzts_input_grid"

.PP
d(xz)/d(ts) 
.PP
Definition at line 55 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::z_c_input_grid"

.PP
Sub-layer cooling thickness\&. 
.PP
Definition at line 56 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::zm_input_grid"

.PP
Oceanic mixed layer depth\&. 
.PP
Definition at line 57 of file nst_input_data\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
