nst_input_data
NAME
nst_input_data -
SYNOPSIS
Public Member Functions
subroutine, public cleanup_input_nst_data
Free up memory associated with nst data.
subroutine, public read_input_nst_data (localpet)
Driver to read input grid nst data.
subroutine read_input_nst_nemsio_file (localpet)
Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file.
subroutine read_input_nst_netcdf_file (localpet)
Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history.
Data Fields
type(esmf_field), public c_0_input_grid
Coefficient 1 to calculate d(tz)/d(ts)
type(esmf_field), public c_d_input_grid
Coefficient 2 to calculate d(tz)/d(ts)
type(esmf_field), public d_conv_input_grid
Thickness of free convectionlayer.
type(esmf_field), public dt_cool_input_grid
Sub-layer cooling amount.
type(esmf_field), public ifd_input_grid
Model mode index.
type(esmf_field), public qrain_input_grid
Sensible heat flux due torainfall.
type(esmf_field), public tref_input_grid
Reference temperature.
type(esmf_field), public w_0_input_grid
Coefficient 3 to calculated(tz)/d(ts)
type(esmf_field), public w_d_input_grid
Coefficient 4 to calculated(tz)/d(ts)
type(esmf_field), public xs_input_grid
Salinity content in diurnalthermocline layer.
type(esmf_field), public xt_input_grid
Heat content in diurnalthermocline layer.
type(esmf_field), public xtts_input_grid
d(xt)/d(ts)
type(esmf_field), public xu_input_grid
u-current content in diurnalthermocline layer
type(esmf_field), public xv_input_grid
v-current content in diurnalthermocline layer
type(esmf_field), public xz_input_grid
Diurnal thermocline layerthickness.
type(esmf_field), public xzts_input_grid
d(xz)/d(ts)
type(esmf_field), public z_c_input_grid
Sub-layer cooling thickness.
type(esmf_field), public zm_input_grid
Oceanic mixed layer depth.
Detailed Description
Definition at line 1 of file nst_input_data.F90.
Member Function/Subroutine Documentation
subroutine, public nst_input_data::cleanup_input_nst_data ()
Free up memory associated with nst data.
Author:
George Gayno NCEP/EMC
Definition at line 782 of file nst_input_data.F90.
Referenced by surface::surface_driver().
subroutine, public nst_input_data::read_input_nst_data (integer, intent(in)localpet)
Driver to read input grid nst data.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 67 of file nst_input_data.F90.
References utilities::error_handler(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
Referenced by surface::surface_driver().
subroutine nst_input_data::read_input_nst_nemsio_file (integer, intent(in)localpet)
Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file.
Note:
The spectral GFS nst data is in a separate file from the surface data. The fv3 surface and nst data are in a single file.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 514 of file nst_input_data.F90.
References utilities::error_handler().
Referenced by read_input_nst_data().
subroutine nst_input_data::read_input_nst_netcdf_file (integer, intent(in)localpet)
Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 230 of file nst_input_data.F90.
References utilities::error_handler(), and sfc_input_data::read_fv3_grid_data_netcdf().
Referenced by read_input_nst_data().
Field Documentation
type(esmf_field), public nst_input_data::c_0_input_grid
Coefficient 1 to calculate d(tz)/d(ts)
Definition at line 39 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::c_d_input_grid
Coefficient 2 to calculate d(tz)/d(ts)
Definition at line 38 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::d_conv_input_grid
Thickness of free convectionlayer.
Definition at line 40 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::dt_cool_input_grid
Sub-layer cooling amount.
Definition at line 41 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::ifd_input_grid
Model mode index. 0-diurnalmodel not started; 1-diurnal model
Definition at line 42 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::qrain_input_grid
Sensible heat flux due torainfall.
Definition at line 45 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::tref_input_grid
Reference temperature.
Definition at line 46 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::w_0_input_grid
Coefficient 3 to calculated(tz)/d(ts)
Definition at line 48 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::w_d_input_grid
Coefficient 4 to calculated(tz)/d(ts)
Definition at line 47 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::xs_input_grid
Salinity content in diurnalthermocline layer.
Definition at line 49 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::xt_input_grid
Heat content in diurnalthermocline layer.
Definition at line 50 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::xtts_input_grid
d(xt)/d(ts)
Definition at line 54 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::xu_input_grid
u-current content in diurnalthermocline layer
Definition at line 51 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::xv_input_grid
v-current content in diurnalthermocline layer
Definition at line 52 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::xz_input_grid
Diurnal thermocline layerthickness.
Definition at line 53 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::xzts_input_grid
d(xz)/d(ts)
Definition at line 55 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::z_c_input_grid
Sub-layer cooling thickness.
Definition at line 56 of file nst_input_data.F90.
type(esmf_field), public nst_input_data::zm_input_grid
Oceanic mixed layer depth.
Definition at line 57 of file nst_input_data.F90.
Author
Generated automatically by Doxygen for chgres_cube from the source code.