sfc_input_data
NAME
sfc_input_data -
SYNOPSIS
Public Member Functions
subroutine, public cleanup_input_sfc_data
Free up memory associated with sfc data.
subroutine, public init_sfc_esmf_fields
Create surface input grid esmf fields.
subroutine read_fv3_grid_data_netcdf (FIELD, TILE_NUM, IMO, JMO, LMO, SFCDATA, SFCDATA_3D)
Read a record from a netcdf file.
subroutine read_grib_soil (vname, vname_file, lugb, pdt_num, dummy3d)
Read soil temperature and soil moisture fields from a GRIB2 file.
subroutine, public read_input_sfc_data (localpet)
Driver to read input grid surface data.
subroutine read_input_sfc_gaussian_nemsio_file (localpet)
Read input grid surface data from an fv3 gaussian nemsio file.
subroutine read_input_sfc_gfs_gaussian_nemsio_file (localpet)
Read input grid surface data from a spectral gfs gaussian nemsio file.
subroutine read_input_sfc_gfs_sfcio_file (localpet)
Read input grid surface data from a spectral gfs gaussian sfcio file.
subroutine read_input_sfc_grib2_file (localpet)
Read input grid surface data from a grib2 file.
subroutine read_input_sfc_netcdf_file (localpet)
Read input grid surface data from tiled 'history' files (netcdf) or gaussian netcdf files.
subroutine read_input_sfc_restart_file (localpet)
Read input grid surface data from fv3 tiled warm 'restart' files.
Data Fields
type(esmf_field), public canopy_mc_input_grid
canopy moist content
type(esmf_field), public f10m_input_grid
log((z0+10)*1/z0)
type(esmf_field), public ffmm_input_grid
log((z0+z1)*1/z0) See sfc_diff.f for details.
real icet_default = 265.0
Default value of soil and skin temperature (K) over ice.
type(esmf_field), public lai_input_grid
leaf area index
type(esmf_field), public landsea_mask_input_grid
land sea mask; 0-water, 1-land, 2-ice
integer, public lsoil_input =4
number of soil layers, no longer hardwired to allow for 7 layers of soil for the RUC LSM
type(esmf_field), public max_veg_greenness_input_grid
shdmax
type(esmf_field), public min_veg_greenness_input_grid
shdmin
type(esmf_field), public q2m_input_grid
2-m spec hum
type(esmf_field), public seaice_depth_input_grid
sea ice depth
type(esmf_field), public seaice_fract_input_grid
sea ice fraction
type(esmf_field), public seaice_skin_temp_input_grid
sea ice skin temp
type(esmf_field), public skin_temp_input_grid
skin temp/sst
type(esmf_field), public snow_depth_input_grid
snow dpeth
type(esmf_field), public snow_liq_equiv_input_grid
snow liq equiv depth
type(esmf_field), public soil_temp_input_grid
3-d soil temp
type(esmf_field), public soil_type_input_grid
soil type
type(esmf_field), public soilm_liq_input_grid
3-d liquid soil moisture
type(esmf_field), public soilm_tot_input_grid
3-d total soil moisture
type(esmf_field), public srflag_input_grid
snow/rain flag
type(esmf_field), public t2m_input_grid
2-m temperature
type(esmf_field), public tprcp_input_grid
precip
type(esmf_field), public ustar_input_grid
fric velocity
type(esmf_field), public veg_greenness_input_grid
vegetation fraction
type(esmf_field), public veg_type_input_grid
vegetation type
integer, public veg_type_landice_input = 15
NOAH land ice option defined at this veg type.
type(esmf_field), public z0_input_grid
roughness length
Detailed Description
Definition at line 1 of file sfc_input_data.F90.
Member Function/Subroutine Documentation
subroutine, public sfc_input_data::cleanup_input_sfc_data ()
Free up memory associated with sfc data.
Author:
George Gayno NCEP/EMC
Definition at line 3306 of file sfc_input_data.F90.
Referenced by surface::surface_driver().
subroutine, public sfc_input_data::init_sfc_esmf_fields ()
Create surface input grid esmf fields.
Author:
George Gayno NCEP/EMC
Definition at line 2946 of file sfc_input_data.F90.
References utilities::error_handler().
Referenced by read_input_sfc_data().
subroutine sfc_input_data::read_fv3_grid_data_netcdf (character(len=*), intent(in)FIELD, integer, intent(in)TILE_NUM, integer, intent(in)IMO, integer, intent(in)JMO, integer, intent(in)LMO, real(esmf_kind_r8), dimension(imo,jmo), intent(out), optionalSFCDATA, real(esmf_kind_r8), dimension(imo,jmo,lmo), intent(out), optionalSFCDATA_3D)
Read a record from a netcdf file.
Parameters:
field name of field to be read
tile_num grid tile number
imo i-dimension of field
jmo j-dimension of field
lmo number of vertical levels of field
sfcdata 1-d array containing field data
sfcdata_3d 3-d array containing field data
Author:
George Gayno NCEP/EMC
Definition at line 3159 of file sfc_input_data.F90.
References utilities::netcdf_err().
Referenced by nst_input_data::read_input_nst_netcdf_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
subroutine sfc_input_data::read_grib_soil (character(len=20), intent(in)vname, character(len=20), intent(in)vname_file, integer, intent(in)lugb, integer, intent(in)pdt_num, real(esmf_kind_r8), dimension(:,:,:), intent(inout)dummy3d)
Read soil temperature and soil moisture fields from a GRIB2 file.
Parameters:
vname variable name in varmap table
vname_file variable name in grib2 file
lugb logical unit number for surface grib2 file
pdt_num product definition template number.
dummy3d array of soil data
Author:
George Gayno NCEP/EMC
Definition at line 3205 of file sfc_input_data.F90.
References utilities::error_handler(), program_setup::get_var_cond(), and utilities::handle_grib_error().
Referenced by read_input_sfc_grib2_file().
subroutine, public sfc_input_data::read_input_sfc_data (integer, intent(in)localpet)
Driver to read input grid surface data.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 95 of file sfc_input_data.F90.
References init_sfc_esmf_fields(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
Referenced by surface::surface_driver().
subroutine sfc_input_data::read_input_sfc_gaussian_nemsio_file (integer, intent(in)localpet)
Read input grid surface data from an fv3 gaussian nemsio file.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 736 of file sfc_input_data.F90.
References utilities::error_handler().
Referenced by read_input_sfc_data().
subroutine sfc_input_data::read_input_sfc_gfs_gaussian_nemsio_file (integer, intent(in)localpet)
Read input grid surface data from a spectral gfs gaussian nemsio file.
Note:
Format used by gfs starting July 19, 2017.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 387 of file sfc_input_data.F90.
References utilities::error_handler().
Referenced by read_input_sfc_data().
subroutine sfc_input_data::read_input_sfc_gfs_sfcio_file (integer, intent(in)localpet)
Read input grid surface data from a spectral gfs gaussian sfcio file.
Note:
Prior to July 19, 2017.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 163 of file sfc_input_data.F90.
References utilities::error_handler().
Referenced by read_input_sfc_data().
subroutine sfc_input_data::read_input_sfc_grib2_file (integer, intent(in)localpet)
Read input grid surface data from a grib2 file.
Parameters:
localpet ESMF local persistent execution thread
Author:
Larissa Reames
Definition at line 1763 of file sfc_input_data.F90.
References utilities::check_cnwat(), utilities::check_soilt(), utilities::error_handler(), program_setup::get_var_cond(), utilities::handle_grib_error(), utilities::netcdf_err(), read_grib_soil(), search_util::search(), and utilities::to_upper().
Referenced by read_input_sfc_data().
subroutine sfc_input_data::read_input_sfc_netcdf_file (integer, intent(in)localpet)
Read input grid surface data from tiled 'history' files (netcdf) or gaussian netcdf files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 1402 of file sfc_input_data.F90.
References utilities::error_handler(), utilities::netcdf_err(), and read_fv3_grid_data_netcdf().
Referenced by read_input_sfc_data().
subroutine sfc_input_data::read_input_sfc_restart_file (integer, intent(in)localpet)
Read input grid surface data from fv3 tiled warm 'restart' files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 1085 of file sfc_input_data.F90.
References utilities::error_handler(), utilities::netcdf_err(), and read_fv3_grid_data_netcdf().
Referenced by read_input_sfc_data().
Field Documentation
type(esmf_field), public sfc_input_data::canopy_mc_input_grid
canopy moist content
Definition at line 54 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::f10m_input_grid
log((z0+10)*1/z0)
Definition at line 55 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::ffmm_input_grid
log((z0+z1)*1/z0) See sfc_diff.f for details.
Definition at line 56 of file sfc_input_data.F90.
real sfc_input_data::icet_default = 265.0
Default value of soil and skin temperature (K) over ice.
Definition at line 52 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::lai_input_grid
leaf area index
Definition at line 78 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::landsea_mask_input_grid
land sea mask; 0-water, 1-land, 2-ice
Definition at line 58 of file sfc_input_data.F90.
integer, public sfc_input_data::lsoil_input =4
number of soil layers, no longer hardwired to allow for 7 layers of soil for the RUC LSM
Definition at line 82 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::max_veg_greenness_input_grid
shdmax
Definition at line 79 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::min_veg_greenness_input_grid
shdmin
Definition at line 80 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::q2m_input_grid
2-m spec hum
Definition at line 60 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::seaice_depth_input_grid
sea ice depth
Definition at line 61 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::seaice_fract_input_grid
sea ice fraction
Definition at line 62 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::seaice_skin_temp_input_grid
sea ice skin temp
Definition at line 63 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::skin_temp_input_grid
skin temp/sst
Definition at line 64 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::snow_depth_input_grid
snow dpeth
Definition at line 65 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::snow_liq_equiv_input_grid
snow liq equiv depth
Definition at line 66 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::soil_temp_input_grid
3-d soil temp
Definition at line 67 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::soil_type_input_grid
soil type
Definition at line 68 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::soilm_liq_input_grid
3-d liquid soil moisture
Definition at line 69 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::soilm_tot_input_grid
3-d total soil moisture
Definition at line 70 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::srflag_input_grid
snow/rain flag
Definition at line 71 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::t2m_input_grid
2-m temperature
Definition at line 72 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::tprcp_input_grid
precip
Definition at line 73 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::ustar_input_grid
fric velocity
Definition at line 74 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::veg_greenness_input_grid
vegetation fraction
Definition at line 77 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::veg_type_input_grid
vegetation type
Definition at line 75 of file sfc_input_data.F90.
integer, public sfc_input_data::veg_type_landice_input = 15
NOAH land ice option defined at this veg type. Default is igbp.
Definition at line 49 of file sfc_input_data.F90.
type(esmf_field), public sfc_input_data::z0_input_grid
roughness length
Definition at line 76 of file sfc_input_data.F90.
Author
Generated automatically by Doxygen for chgres_cube from the source code.