write_data
NAME
write_data -
SYNOPSIS
Public Member Functions
subroutine, public write_fv3_atm_bndy_data_netcdf (localpet)
Writes atmospheric fields along the lateral boundary.
subroutine, public write_fv3_atm_data_netcdf (localpet)
Write atmospheric coldstart files (netcdf format).
subroutine, public write_fv3_atm_header_netcdf (localpet)
Writes atmospheric header file in netcdf format.
subroutine, public write_fv3_sfc_data_netcdf (localpet)
Writes surface and nst data into a 'coldstart' file (netcdf).
Detailed Description
Definition at line 1 of file write_data.F90.
Member Function/Subroutine Documentation
subroutine, public write_data::write_fv3_atm_bndy_data_netcdf (integer, intent(in)localpet)
Writes atmospheric fields along the lateral boundary. For regional grids only. Output in netcdf format.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 99 of file write_data.F90.
References utilities::error_handler(), and utilities::netcdf_err().
Referenced by atmosphere::atmosphere_driver().
subroutine, public write_data::write_fv3_atm_data_netcdf (integer, intent(in)localpet)
Write atmospheric coldstart files (netcdf format). Routine writes tiled files in parallel. Tile 1 is written by localpet 0; tile 2 by localpet 1, etc. The number of pets must be equal to or greater than the number of tiled files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 1197 of file write_data.F90.
References utilities::error_handler(), and utilities::netcdf_err().
Referenced by atmosphere::atmosphere_driver().
subroutine, public write_data::write_fv3_atm_header_netcdf (integer, intent(in)localpet)
Writes atmospheric header file in netcdf format.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 28 of file write_data.F90.
References utilities::netcdf_err().
Referenced by atmosphere::atmosphere_driver().
subroutine, public write_data::write_fv3_sfc_data_netcdf (integer, intent(in)localpet)
Writes surface and nst data into a 'coldstart' file (netcdf).
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 1802 of file write_data.F90.
References utilities::error_handler(), and utilities::netcdf_err().
Referenced by surface::surface_driver().
Author
Generated automatically by Doxygen for chgres_cube from the source code.