.TH "grids_io::grid_setup_type" 3 "Version 1.14.0" "regrid_sfc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grids_io::grid_setup_type
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "character(7) \fBdescriptor\fP"
.br
.RI "options: gau_inc fv3_rst "
.ti -1c
.RI "character(100) \fBdir\fP"
.br
.RI "directory "
.ti -1c
.RI "character(100) \fBdir_coord\fP"
.br
.RI "directory name for coordinate info "
.ti -1c
.RI "character(100) \fBdir_mask\fP"
.br
.RI "directory name for reading in mask "
.ti -1c
.RI "character(100) \fBfname\fP"
.br
.RI "file name "
.ti -1c
.RI "character(100) \fBfname_coord\fP"
.br
.RI "file name with coordinate info "
.ti -1c
.RI "character(100) \fBfname_mask\fP"
.br
.RI "file name for reading in mask "
.ti -1c
.RI "integer \fBires\fP"
.br
.RI "latitudinal dimension "
.ti -1c
.RI "integer \fBjres\fP"
.br
.RI "longitudinal dimension "
.ti -1c
.RI "logical \fBmask_from_input\fP"
.br
.RI "read mask from input file "
.ti -1c
.RI "character(15), dimension(1) \fBmask_variable\fP"
.br
.RI "name of variables used for mask "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBgrids_IO\&.F90\fP\&.
.SH "Field Documentation"
.PP 
.SS "character(7) grids_io::grid_setup_type::descriptor"

.PP
options: gau_inc fv3_rst 
.PP
Definition at line \fB24\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "character(100) grids_io::grid_setup_type::dir"

.PP
directory 
.PP
Definition at line \fB26\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "character(100) grids_io::grid_setup_type::dir_coord"

.PP
directory name for coordinate info 
.PP
Definition at line \fB32\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "character(100) grids_io::grid_setup_type::dir_mask"

.PP
directory name for reading in mask 
.PP
Definition at line \fB29\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "character(100) grids_io::grid_setup_type::fname"

.PP
file name 
.PP
Definition at line \fB25\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "character(100) grids_io::grid_setup_type::fname_coord"

.PP
file name with coordinate info 
.PP
Definition at line \fB31\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "character(100) grids_io::grid_setup_type::fname_mask"

.PP
file name for reading in mask 
.PP
Definition at line \fB28\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "integer grids_io::grid_setup_type::ires"

.PP
latitudinal dimension 
.PP
Definition at line \fB33\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "integer grids_io::grid_setup_type::jres"

.PP
longitudinal dimension 
.PP
Definition at line \fB34\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "logical grids_io::grid_setup_type::mask_from_input"

.PP
read mask from input file 
.PP
Definition at line \fB30\fP of file \fBgrids_IO\&.F90\fP\&.
.SS "character(15), dimension(1) grids_io::grid_setup_type::mask_variable"

.PP
name of variables used for mask 
.PP
Definition at line \fB27\fP of file \fBgrids_IO\&.F90\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for regrid_sfc from the source code\&.
