.TH "md__2scratch4_2NCEPDEV_2nems_2Brian_8Curtis_2git_2BrianCurtis-NOAA_2UFS__UTILS_2v1__14__0_2sorc_2regrid__sfc_8fd_2docs_2README" 3 "Version 1.14.0" "regrid_sfc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2scratch4_2NCEPDEV_2nems_2Brian_8Curtis_2git_2BrianCurtis-NOAA_2UFS__UTILS_2v1__14__0_2sorc_2regrid__sfc_8fd_2docs_2README \- README 
.PP
This program is used to regrid masked sfc fields using masked bi-linear interpolaton\&. It is designed for regridding of increments and states, and can regrid from/to the FV3 grid that the GFS model runs on, and the Gaussian grid used for GFS model output (i\&.e\&., history files)\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
