.TH "/scratch4/NCEPDEV/nems/Brian.Curtis/git/BrianCurtis-NOAA/UFS_UTILS/v1_14_0/sorc/regrid_sfc.fd/regridStates.F90" 3 "Version 1.14.0" "regrid_sfc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch4/NCEPDEV/nems/Brian.Curtis/git/BrianCurtis-NOAA/UFS_UTILS/v1_14_0/sorc/regrid_sfc.fd/regridStates.F90 \- Program to re-grid a list of FV3 variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBregridstates\fP"
.br
.RI "Program to re-grid a list of FV3 variables\&. "
.in -1c
.SH "Detailed Description"
.PP 
Program to re-grid a list of FV3 variables\&. 


.PP
\fBAuthor\fP
.RS 4
Clara Draper, and George Gayno Aug, 2024\&. 
.RE
.PP

.PP
Definition in file \fBregridStates\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program regridstates"

.PP
Program to re-grid a list of FV3 variables\&. Intended for use in DA applications (regridding of restarts for recentering, regridding increments)\&. 
.PP
\fBReturns\fP
.RS 4
0 for success, error code otherwise\&. 
.RE
.PP

.PP
Definition at line \fB9\fP of file \fBregridStates\&.F90\fP\&.
.PP
References \fBreadin_setup()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for regrid_sfc from the source code\&.
