.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBangles\&.F90\fP"
.br
.RI "\fIDetermine the rotation angle on center and corner points\&. \fP"
.ti -1c
.RI "file \fBcharstrings\&.F90\fP"
.br
.RI "\fIDefine required character string variables\&. \fP"
.ti -1c
.RI "file \fBcicegrid\&.F90\fP"
.br
.RI "\fIWrite the CICE6 grid file\&. \fP"
.ti -1c
.RI "file \fBdebugprint\&.F90\fP"
.br
.RI "\fIPrint debugging information\&. \fP"
.ti -1c
.RI "file \fBgen_fixgrid\&.F90\fP"
.br
.RI "\fIGenerate fixed grid files required for coupled model\&. \fP"
.ti -1c
.RI "file \fBgengrid_kinds\&.F90\fP"
.br
.RI "\fIDefine type-kind variables\&. \fP"
.ti -1c
.RI "file \fBgrdvars\&.F90\fP"
.br
.RI "\fIDefine and allocate required grid variables\&. \fP"
.ti -1c
.RI "file \fBinputnml\&.F90\fP"
.br
.RI "\fIDefine the input namelist variables\&. \fP"
.ti -1c
.RI "file \fBmapped_mask\&.F90\fP"
.br
.RI "\fICreate the mapped ocean mask files\&. \fP"
.ti -1c
.RI "file \fBpostwgts\&.F90\fP"
.br
.RI "\fICreate the ESMF weights for post\&. \fP"
.ti -1c
.RI "file \fBscripgrid\&.F90\fP"
.br
.RI "\fIWrite a SCRIP format file\&. \fP"
.ti -1c
.RI "file \fBtopoedits\&.F90\fP"
.br
.RI "\fIAdd required topo-edits to adjust the run-time MOM6 land mask\&. \fP"
.ti -1c
.RI "file \fBtripolegrid\&.F90\fP"
.br
.RI "\fIWrite the tripole grid file\&. \fP"
.ti -1c
.RI "file \fBvartypedefs\&.F90\fP"
.br
.RI "\fIDefine the variables for output\&. \fP"
.ti -1c
.RI "file \fBvertices\&.F90\fP"
.br
.RI "\fIFill the vertices for any stagger location\&. \fP"
.in -1c
