.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/machine.f90" 3 "Tue Jan 17 2023" "Version 1.9.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/machine.f90 \- Holds machine dependent constants for global_cycle\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBMACHINE\fP"
.br
.RI "Holds machine dependent constants for global_cycle\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBMACHINE::kind_dbl_prec\fP = 8"
.br
.RI "Kind type for 8-byte float point variables\&. "
.ti -1c
.RI "integer, parameter \fBMACHINE::kind_io4\fP = kind_sngl_prec"
.br
.RI "Kind type for 4-byte float point variables\&. "
.ti -1c
.RI "integer, parameter \fBMACHINE::kind_io8\fP = kind_dbl_prec"
.br
.RI "Kind type for 8-byte float point variables\&. "
.ti -1c
.RI "integer, parameter \fBMACHINE::kind_sngl_prec\fP = 4"
.br
.RI "Kind type for 4-byte float point variables\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds machine dependent constants for global_cycle\&. 


.PP
\fBAuthor:\fP
.RS 4
Mark Iredell NOAA/EMC 
.RE
.PP

.PP
Definition in file \fBmachine\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
