.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/num_parthds.f90" 3 "Tue Jan 17 2023" "Version 1.9.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/num_parthds.f90 \- Return number of threads\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnum_parthds\fP ()"
.br
.RI "Return the number of omp threads\&. "
.in -1c
.SH "Detailed Description"
.PP 
Return number of threads\&. 


.PP
\fBAuthor:\fP
.RS 4
Mark Iredell NCEP/EMC 
.RE
.PP

.PP
Definition in file \fBnum_parthds\&.f90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function num_parthds ()"

.PP
Return the number of omp threads\&. 
.PP
\fBReturns:\fP
.RS 4
num_parthds The number of threads\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
Mark Iredell NCEP/EMC 
.RE
.PP

.PP
Definition at line 10 of file num_parthds\&.f90\&.
.PP
Referenced by SFC_DRV()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
