.TH "model_grid" 3 "Thu Aug 4 2022" "Version 1.8.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model_grid \- This module defines the model grid\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBdefine_model_grid\fP (localpet, npets)"
.br
.RI "Define model grid\&. "
.ti -1c
.RI "subroutine \fBget_model_info\fP (orog_file, mask, lat2d, lon2d, idim, jdim)"
.br
.RI "Get model information\&. "
.ti -1c
.RI "subroutine, public \fBmodel_grid_cleanup\fP"
.br
.RI "Model grid cleanup\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(esmf_field), public \fBdata_field_mdl\fP"
.br
.RI "ESMF field object that holds the data interpolated to model grid\&. "
.ti -1c
.RI "type(esmf_grid), public \fBgrid_mdl\fP"
.br
.RI "ESMF grid object for the model grid\&. "
.ti -1c
.RI "character(len=5), dimension(:), allocatable, public \fBgrid_tiles\fP"
.br
.RI "Array of model grid tile names\&. "
.ti -1c
.RI "integer, public \fBi_mdl\fP"
.br
.RI "i dimension of model tile\&. "
.ti -1c
.RI "integer, public \fBij_mdl\fP"
.br
.RI "Total number of points on a model tile\&. "
.ti -1c
.RI "integer, public \fBj_mdl\fP"
.br
.RI "j dimension of model tile\&. "
.ti -1c
.RI "type(esmf_field), public \fBlatitude_field_mdl\fP"
.br
.RI "ESMF field object that holds the model grid latitude\&. "
.ti -1c
.RI "type(esmf_field), public \fBlongitude_field_mdl\fP"
.br
.RI "ESMF field object that holds the model grid longitude\&. "
.ti -1c
.RI "type(esmf_field), public \fBmask_field_mdl\fP"
.br
.RI "ESMF field object that holds the model land mask\&. "
.ti -1c
.RI "real(kind=4), public \fBmissing\fP = \-999\&."
.br
.RI "Value assigned to undefined points (i\&.e\&., ocean points for a land field)\&. "
.ti -1c
.RI "integer, public \fBnum_tiles\fP"
.br
.RI "Total number of model grid tiles\&. "
.ti -1c
.RI "type(esmf_field), public \fBvegt_field_mdl\fP"
.br
.RI "ESMF field object that holds the vegetation type on the model grid\&. "
.in -1c
.SH "Detailed Description"
.PP 
This module defines the model grid\&. 

Variables named with 'mdl' refer to the model grid\&.
.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public model_grid::define_model_grid (integer, intent(in) localpet, integer, intent(in) npets)"

.PP
Define model grid\&. Define the model grid from the mosaic and orography files\&. Create the ESMF grid object for the model grid\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP this mpi task 
.br
.br
\fInpets\fP total number of mpi tasks 
.br
 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.PP
Definition at line 54 of file model_grid\&.F90\&.
.PP
References data_field_mdl, utils::error_handler(), get_model_info(), grid_mdl, grid_tiles, i_mdl, ij_mdl, j_mdl, latitude_field_mdl, longitude_field_mdl, mask_field_mdl, program_setup::mosaic_file_mdl, utils::netcdf_err(), num_tiles, program_setup::orog_dir_mdl, program_setup::orog_files_mdl, and vegt_field_mdl\&.
.PP
Referenced by driver()\&.
.SS "subroutine model_grid::get_model_info (character(len=*), intent(in) orog_file, integer(esmf_kind_i4), dimension(idim,jdim), intent(out) mask, real(esmf_kind_r4), dimension(idim,jdim), intent(out) lat2d, real(esmf_kind_r4), dimension(idim,jdim), intent(out) lon2d, integer, intent(in) idim, integer, intent(in) jdim)"

.PP
Get model information\&. Read model land/sea mask and lat/lon from the orography file\&.
.PP
\fBParameters:\fP
.RS 4
\fIorog_file\fP the orography file 
.br
\fImask\fP land/sea mask 
.br
\fIlat2d\fP latitude 
.br
\fIlon2d\fP longitude 
.br
\fIidim\fP i dimension of the model tile 
.br
\fIjdim\fP j dimension of the model tile 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.PP
Definition at line 284 of file model_grid\&.F90\&.
.PP
References utils::error_handler(), and utils::netcdf_err()\&.
.PP
Referenced by define_model_grid()\&.
.SS "subroutine, public model_grid::model_grid_cleanup ()"

.PP
Model grid cleanup\&. Free up memory associated with this module\&.
.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.PP
Definition at line 388 of file model_grid\&.F90\&.
.PP
References data_field_mdl, grid_mdl, latitude_field_mdl, longitude_field_mdl, mask_field_mdl, and vegt_field_mdl\&.
.PP
Referenced by driver()\&.
.SH "Variable Documentation"
.PP 
.SS "type(esmf_field), public model_grid::data_field_mdl"

.PP
ESMF field object that holds the data interpolated to model grid\&. 
.PP
Definition at line 29 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), interp(), and model_grid_cleanup()\&.
.SS "type(esmf_grid), public model_grid::grid_mdl"

.PP
ESMF grid object for the model grid\&. 
.PP
Definition at line 28 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), and model_grid_cleanup()\&.
.SS "character(len=5), dimension(:), allocatable, public model_grid::grid_tiles"

.PP
Array of model grid tile names\&. 
.PP
Definition at line 18 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), and output()\&.
.SS "integer, public model_grid::i_mdl"

.PP
i dimension of model tile\&. 
.PP
Definition at line 20 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), and interp()\&.
.SS "integer, public model_grid::ij_mdl"

.PP
Total number of points on a model tile\&. 
.PP
Definition at line 22 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid()\&.
.SS "integer, public model_grid::j_mdl"

.PP
j dimension of model tile\&. 
.PP
Definition at line 21 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), and interp()\&.
.SS "type(esmf_field), public model_grid::latitude_field_mdl"

.PP
ESMF field object that holds the model grid latitude\&. 
.PP
Definition at line 33 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), interp(), and model_grid_cleanup()\&.
.SS "type(esmf_field), public model_grid::longitude_field_mdl"

.PP
ESMF field object that holds the model grid longitude\&. 
.PP
Definition at line 35 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), interp(), and model_grid_cleanup()\&.
.SS "type(esmf_field), public model_grid::mask_field_mdl"

.PP
ESMF field object that holds the model land mask\&. 
.PP
Definition at line 31 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), interp(), and model_grid_cleanup()\&.
.SS "real(kind=4), public model_grid::missing = \-999\&."

.PP
Value assigned to undefined points (i\&.e\&., ocean points for a land field)\&. 
.PP
Definition at line 25 of file model_grid\&.F90\&.
.PP
Referenced by interp(), and output()\&.
.SS "integer, public model_grid::num_tiles"

.PP
Total number of model grid tiles\&. 
.PP
Definition at line 23 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), and interp()\&.
.SS "type(esmf_field), public model_grid::vegt_field_mdl"

.PP
ESMF field object that holds the vegetation type on the model grid\&. 
.PP
Definition at line 37 of file model_grid\&.F90\&.
.PP
Referenced by define_model_grid(), interp(), and model_grid_cleanup()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for sfc_climo_gen from the source code\&.
