.TH "program_setup" 3 "Thu Aug 4 2022" "Version 1.8.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
program_setup \- Set up program execution\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBread_setup_namelist\fP (localpet)"
.br
.RI "Read program setup namelist\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBhalo\fP = 0"
.br
.RI "Number of row/cols defining the lateral boundary halo\&. "
.ti -1c
.RI "character(len=500), public \fBinput_facsf_file\fP = 'NULL'"
.br
.RI "File containing input fractional coverage data for strong zenith angle dependent albedo\&. "
.ti -1c
.RI "character(len=500), public \fBinput_leaf_area_index_file\fP = 'NULL'"
.br
.RI "File containing input leaf area index data\&. "
.ti -1c
.RI "character(len=500), public \fBinput_maximum_snow_albedo_file\fP = 'NULL'"
.br
.RI "File containing input maximum snow albedo data\&. "
.ti -1c
.RI "character(len=500), public \fBinput_slope_type_file\fP = 'NULL'"
.br
.RI "File containing input slope type data\&. "
.ti -1c
.RI "character(len=500), public \fBinput_snowfree_albedo_file\fP = 'NULL'"
.br
.RI "File containing input snow-free albedo data\&. "
.ti -1c
.RI "character(len=500), public \fBinput_soil_type_file\fP = 'NULL'"
.br
.RI "File containing input soil type data\&. "
.ti -1c
.RI "character(len=500), public \fBinput_substrate_temperature_file\fP = 'NULL'"
.br
.RI "File containing input soil substrate temperature data\&. "
.ti -1c
.RI "character(len=500), public \fBinput_vegetation_greenness_file\fP = 'NULL'"
.br
.RI "File containing input vegetation greenness data\&. "
.ti -1c
.RI "character(len=500), public \fBinput_vegetation_type_file\fP = 'NULL'"
.br
.RI "File containing input vegetation type data\&. "
.ti -1c
.RI "character(len=50), public \fBleaf_area_index_method\fP ='bilinear'"
.br
.RI "Interpolation method for leaf area index\&. "
.ti -1c
.RI "character(len=50), public \fBmaximum_snow_albedo_method\fP ='bilinear'"
.br
.RI "Interpolation method for max snow albedo\&. "
.ti -1c
.RI "character(len=500), public \fBmosaic_file_mdl\fP = 'NULL'"
.br
.RI "Model grid mosaic file\&. "
.ti -1c
.RI "character(len=500), public \fBorog_dir_mdl\fP = 'NULL'"
.br
.RI "Directory containing the model grid orography files\&. "
.ti -1c
.RI "character(len=500), dimension(6), public \fBorog_files_mdl\fP = 'NULL'"
.br
.RI "Model grid orography filenames\&. "
.ti -1c
.RI "character(len=50), public \fBsnowfree_albedo_method\fP ='bilinear'"
.br
.RI "Interpolation method for snowfree albedo\&. "
.ti -1c
.RI "character(len=50), public \fBvegetation_greenness_method\fP ='bilinear'"
.br
.RI "Interpolation method for vegetation greenness\&. "
.in -1c
.SH "Detailed Description"
.PP 
Set up program execution\&. 

Public variables:
.PP
Here 'input' indicates variables associated with the input source data and 'mdl' indicates variables associated with the fv3 model grid\&.
.PP
To not process a surface field, set its 'input_file' variable to NULL\&. However, vegetation type must always be processed as it defines landice points\&.
.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public program_setup::read_setup_namelist (integer, intent(in) localpet)"

.PP
Read program setup namelist\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP mpi task number 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.PP
Definition at line 55 of file program_setup\&.f90\&.
.PP
References halo, input_facsf_file, input_leaf_area_index_file, input_maximum_snow_albedo_file, input_slope_type_file, input_snowfree_albedo_file, input_soil_type_file, input_substrate_temperature_file, input_vegetation_greenness_file, input_vegetation_type_file, leaf_area_index_method, maximum_snow_albedo_method, mosaic_file_mdl, orog_dir_mdl, orog_files_mdl, snowfree_albedo_method, and vegetation_greenness_method\&.
.PP
Referenced by driver()\&.
.SH "Variable Documentation"
.PP 
.SS "integer, public program_setup::halo = 0"

.PP
Number of row/cols defining the lateral boundary halo\&. Used for regional nests\&. 
.PP
Definition at line 43 of file program_setup\&.f90\&.
.PP
Referenced by output(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_facsf_file = 'NULL'"

.PP
File containing input fractional coverage data for strong zenith angle dependent albedo\&. 
.PP
Definition at line 24 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_leaf_area_index_file = 'NULL'"

.PP
File containing input leaf area index data\&. 
.PP
Definition at line 23 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_maximum_snow_albedo_file = 'NULL'"

.PP
File containing input maximum snow albedo data\&. 
.PP
Definition at line 28 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_slope_type_file = 'NULL'"

.PP
File containing input slope type data\&. 
.PP
Definition at line 30 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_snowfree_albedo_file = 'NULL'"

.PP
File containing input snow-free albedo data\&. 
.PP
Definition at line 29 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_soil_type_file = 'NULL'"

.PP
File containing input soil type data\&. 
.PP
Definition at line 31 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_substrate_temperature_file = 'NULL'"

.PP
File containing input soil substrate temperature data\&. 
.PP
Definition at line 27 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_vegetation_greenness_file = 'NULL'"

.PP
File containing input vegetation greenness data\&. 
.PP
Definition at line 33 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::input_vegetation_type_file = 'NULL'"

.PP
File containing input vegetation type data\&. 
.PP
Definition at line 32 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=50), public program_setup::leaf_area_index_method ='bilinear'"

.PP
Interpolation method for leaf area index\&. Conservative or bilinear (default)\&. 
.PP
Definition at line 38 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=50), public program_setup::maximum_snow_albedo_method ='bilinear'"

.PP
Interpolation method for max snow albedo\&. Conservative or bilinear (default)\&. 
.PP
Definition at line 39 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::mosaic_file_mdl = 'NULL'"

.PP
Model grid mosaic file\&. 
.PP
Definition at line 34 of file program_setup\&.f90\&.
.PP
Referenced by model_grid::define_model_grid(), and read_setup_namelist()\&.
.SS "character(len=500), public program_setup::orog_dir_mdl = 'NULL'"

.PP
Directory containing the model grid orography files\&. 
.PP
Definition at line 35 of file program_setup\&.f90\&.
.PP
Referenced by model_grid::define_model_grid(), and read_setup_namelist()\&.
.SS "character(len=500), dimension(6), public program_setup::orog_files_mdl = 'NULL'"

.PP
Model grid orography filenames\&. 
.PP
Definition at line 36 of file program_setup\&.f90\&.
.PP
Referenced by model_grid::define_model_grid(), and read_setup_namelist()\&.
.SS "character(len=50), public program_setup::snowfree_albedo_method ='bilinear'"

.PP
Interpolation method for snowfree albedo\&. Conservative or bilinear (default)\&. 
.PP
Definition at line 40 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SS "character(len=50), public program_setup::vegetation_greenness_method ='bilinear'"

.PP
Interpolation method for vegetation greenness\&. Conservative or bilinear (default)\&. 
.PP
Definition at line 41 of file program_setup\&.f90\&.
.PP
Referenced by driver(), and read_setup_namelist()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for sfc_climo_gen from the source code\&.
