.TH "/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/sfc_climo_gen.fd/search.f90" 3 "Thu Aug 4 2022" "Version 1.8.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/sfc_climo_gen.fd/search.f90 \- Replace undefined values on the model grid with a valid value at a nearby neighbor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsearch\fP (field, mask, idim, jdim, tile, field_name)"
.br
.RI "Replace undefined values on the model grid with a valid value at a nearby neighbor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Replace undefined values on the model grid with a valid value at a nearby neighbor\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.PP
Definition in file \fBsearch\&.f90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine search (real(esmf_kind_r4), dimension(idim,jdim), intent(inout) field, integer(esmf_kind_i4), dimension(idim,jdim), intent(in) mask, integer, intent(in) idim, integer, intent(in) jdim, integer, intent(in) tile, character(len=*) field_name)"

.PP
Replace undefined values on the model grid with a valid value at a nearby neighbor\&. Undefined values are typically associated with isolated islands where there is no source data\&. Routine searches a neighborhood with a radius of 100 grid points\&. If no valid value is found, a default value is used\&. This routine works for one tile of a cubed sphere grid\&. It does not consider valid values at adjacent faces\&. That is a future upgrade\&.
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP - input: field before missing values are replaced
.IP "\(bu" 2
output: field after missing values are replaced 
.PP
.br
\fImask\fP field bitmap\&. Field defined where mask=1 
.br
\fIidim\fP i dimension of tile 
.br
\fIjdim\fP j dimension of tile 
.br
\fItile\fP tile number 
.br
\fIfield_name\fP field name 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.PP
Definition at line 24 of file search\&.f90\&.
.PP
Referenced by interp()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for sfc_climo_gen from the source code\&.
