/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/global_cycle.fd/cycle.f90
NAME
/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/global_cycle.fd/cycle.f90 - Update surface and NSST fields.
SYNOPSIS
Functions/Subroutines
subroutine ADJUST_NSST (RLA, RLO, SLMSK_TILE, SLMSK_FG_TILE, SKINT_TILE, SICET_TILE, sice_tile, SOILT_TILE, NSST, LENSFC, LSOIL, IDIM, JDIM, ZSEA1, ZSEA2, MON, DAY, DELTSFC, tf_clm_tile, tf_trd_tile, sal_clm_tile)
Read in gsi file with the updated reference temperature increments (on the gaussian grid), interpolate increments to the cubed-sphere tile, and perform required nsst adjustments and qc.
subroutine CLIMO_TREND (LATITUDE, MON, DAY, DELTSFC, DTREF)
If the tile point is an isolated water point that has no corresponding gsi water point, then tref is updated using the rtg sst climo trend.
subroutine DTZM_POINT (XT, XZ, DT_COOL, ZC, Z1, Z2, DTZM)
Compute the vertical mean of the NSST t-profile.
subroutine get_sal_clm (xlats_ij, xlons_ij, ny, nx, iy, im, id, ih, sal_clm)
Get salinity climatology at the valid time on the target grid.
subroutine get_sal_clm_ta (sal_clm_ta, xlats, xlons, nlat, nlon, mon1, mon2, wei1, wei2)
Get climatological salinity at the analysis time.
subroutine get_tf_clm (xlats_ij, xlons_ij, ny, nx, iy, im, id, ih, tf_clm, tf_trd)
Get the sst climatology at the valid time and on the target grid.
subroutine get_tf_clm_ta (tf_clm_ta, tf_clm_trend, xlats, xlons, nlat, nlon, mon1, mon2, wei1, wei2)
Get the reference temperature/sst climatology and its trend at analysis time.
subroutine get_tim_wei (iy, im, id, ih, mon1, mon2, wei1, wei2)
For a given date, determine the bounding months and the linear time interpolation weights.
subroutine intp_tile (tf_lalo, dlats_lalo, dlons_lalo, jdim_lalo, idim_lalo, tf_tile, xlats_tile, xlons_tile, jdim_tile, idim_tile)
Interpolate lon/lat grid data to the fv3 native grid (tf_lalo => tf_tile).
subroutine nsst_water_reset (nsst, ij, tf_thaw)
If the first guess was sea ice, but the analysis is open water, reset all nsst variables.
program SFC_DRV
Stand alone surface/NSST cycle driver for the cubed-sphere grid.
subroutine SFCDRV (LUGB, IDIM, JDIM, LSM, LENSFC, LSOIL, DELTSFC, IY, IM, ID, IH, FH, IALB, USE_UFO, DO_NSST, DO_SFCCYCLE, DO_LNDINC, ZSEA1, ZSEA2, ISOT, IVEGSRC, MYRANK)
Driver routine for updating the surface fields.
subroutine tf_thaw_set (tf_ij, mask_ij, itile, jtile, tice, tclm, tf_thaw, nx, ny, nset_thaw_s, nset_thaw_i, nset_thaw_c)
Set the background reference temperature (tf) for points where the ice has just melted.
real function tfreez (salinity)
Compute the freezing point of water as a function of salinity.
Detailed Description
Update surface and NSST fields.
Author:
Mark Iredell NCEP/EMC
Definition in file cycle.f90.
Function/Subroutine Documentation
subroutine ADJUST_NSST (real, dimension(lensfc), intent(inout) RLA, real, dimension(lensfc), intent(inout) RLO, real, dimension(lensfc), intent(in) SLMSK_TILE, real, dimension(lensfc), intent(in) SLMSK_FG_TILE, real, dimension(lensfc), intent(inout) SKINT_TILE, real, dimension(lensfc), intent(inout) SICET_TILE, real, dimension(lensfc), intent(inout) sice_tile, real, dimension(lensfc,lsoil), intent(inout) SOILT_TILE, type(nsst_data) NSST, integer, intent(in) LENSFC, integer, intent(in) LSOIL, integer, intent(in) IDIM, integer, intent(in) JDIM, real, intent(in) ZSEA1, real, intent(in) ZSEA2, integer, intent(in) MON, integer, intent(in) DAY, real, intent(in) DELTSFC, real, dimension(lensfc), intent(in) tf_clm_tile, real, dimension(lensfc), intent(in) tf_trd_tile, real, dimension(lensfc), intent(in) sal_clm_tile)
Read in gsi file with the updated reference temperature increments (on the gaussian grid), interpolate increments to the cubed-sphere tile, and perform required nsst adjustments and qc.
Parameters:
RLA Latitude on the cubed-sphere tile
RLO Longitude on the cubed-sphere tile
SLMSK_TILE Land-sea mask on the cubed-sphere tile
SLMSK_FG_TILE First guess land-sea mask on the cubed-sphere tile
SKINT_TILE Skin temperature on the cubed-sphere tile
SICET_TILE Ice temperature on the cubed-sphere tile
sice_tile Ice concentration on the cubed-sphere tile
SOILT_TILE Soil temperature on the cubed-sphere tile
NSST Data structure holding nsst fields
LENSFC Number of points on a tile
LSOIL Number of soil layers
IDIM 'I' dimension of a tile
JDIM 'J' dimension of a tile
ZSEA1 When running nsst model, this is the lower bound of depth of sea temperature. In whole mm.
ZSEA2 When running nsst model, this is the upper bound of depth of sea temperature. In whole mm.
MON Month
DAY Day
DELTSFC Cycling frequency in hours
tf_clm_tile Climatological reference temperature on the cubed-sphere tile.
tf_trd_tile Climatolocial reference temperature trend on the cubed-sphere tile.
sal_clm_tile Climatological salinity on the cubed-sphere tile.
Author:
Xu Li, George Gayno
Definition at line 786 of file cycle.f90.
References nsst_water_reset(), and tf_thaw_set().
subroutine CLIMO_TREND (real, intent(in) LATITUDE, integer, intent(in) MON, integer, intent(in) DAY, real, intent(in) DELTSFC, real, intent(out) DTREF)
If the tile point is an isolated water point that has no corresponding gsi water point, then tref is updated using the rtg sst climo trend. This monthly trend is sorted by latitude band.
Parameters:
LATITUDE Latitude of tile point
MON Month
DAY Day
DELTSFC Cycling frequency in hours
DTREF Monthly trend of reference temperature
Author:
Xu Li, George Gayno
Definition at line 1192 of file cycle.f90.
subroutine DTZM_POINT (real, intent(in) XT, real, intent(in) XZ, real, intent(in) DT_COOL, real, intent(in) ZC, real, intent(in) Z1, real, intent(in) Z2, real, intent(out) DTZM)
Compute the vertical mean of the NSST t-profile.
Parameters:
xt Heat content in the diurnal thermocline layer.
xz Thickness of the diurnal thermocline layer.
dt_cool Skin-layer cooling amount.
zc Thickness of skin-layer.
z1 Lower bound of depth of sea temperature.
z2 Upper bound of depth of sea temperature.
dtzm Mean of the NSST t-profile from z1 to z2.
Author:
Xu Li
Date:
2015
Definition at line 1345 of file cycle.f90.
subroutine get_sal_clm (real, dimension(nx*ny), intent(in) xlats_ij, real, dimension(nx*ny), intent(in) xlons_ij, integer, intent(in) ny, integer, intent(in) nx, integer, intent(in) iy, integer, intent(in) im, integer, intent(in) id, integer, intent(in) ih, real, dimension(nx,ny), intent(out) sal_clm)
Get salinity climatology at the valid time on the target grid.
Parameters:
xlats_ij Latitudes of target grid
xlons_ij Longitudes of target grid
ny 'j' dimension of target grid
nx 'i' dimension of target grid
iy Year
im Month
id Day
ih Hour
sal_clm Salinity climatology on the target grid at the valid time
Author:
Xu Li
Definition at line 1671 of file cycle.f90.
References get_sal_clm_ta(), get_tim_wei(), and intp_tile().
Referenced by SFCDRV().
subroutine get_sal_clm_ta (real, dimension(nlon,nlat), intent(out) sal_clm_ta, real, dimension(nlat), intent(out) xlats, real, dimension(nlon), intent(out) xlons, integer, intent(in) nlat, integer, intent(in) nlon, integer, intent(in) mon1, integer, intent(in) mon2, real, intent(in) wei1, real, intent(in) wei2)
Get climatological salinity at the analysis time.
Parameters:
nlat 'j' dimension of climatological data
nlon 'i' dimension of climatological data
mon1 First bounding month
mon2 Second bounding month
wei1 Weight of first bounding month
wei2 Weight of second bounding month
sal_clm_ta Climatological salinity at the analysis time
xlats Latitudes on the climatological grid
xlons Longitudes on the climatological grid
Author:
Xu Li
Date:
March 2019
Definition at line 1731 of file cycle.f90.
Referenced by get_sal_clm().
subroutine get_tf_clm (real, dimension(nx*ny), intent(in) xlats_ij, real, dimension(nx*ny), intent(in) xlons_ij, integer, intent(in) ny, integer, intent(in) nx, integer, intent(in) iy, integer, intent(in) im, integer, intent(in) id, integer, intent(in) ih, real, dimension(nx,ny), intent(out) tf_clm, real, dimension(nx,ny), intent(out) tf_trd)
Get the sst climatology at the valid time and on the target grid.
Parameters:
xlats_ij latitude of target grid
xlons_ij longitude of target grid
ny 'j' dimension of target grid
nx 'i' dimension of target grid
iy Year
im Month
id Day
ih Hour
tf_clm sst climatology at the valid time and on the target grid
tf_trd 6-hourly sst climatology tendency at the valid time and on the target grid.
Author:
Xu Li
Definition at line 1554 of file cycle.f90.
References get_tf_clm_ta(), get_tim_wei(), and intp_tile().
Referenced by SFCDRV().
subroutine get_tf_clm_ta (real, dimension(nlon,nlat), intent(out) tf_clm_ta, real, dimension(nlon,nlat), intent(out) tf_clm_trend, real, dimension(nlat), intent(out) xlats, real, dimension(nlon), intent(out) xlons, integer, intent(in) nlat, integer, intent(in) nlon, integer, intent(in) mon1, integer, intent(in) mon2, real, intent(in) wei1, real, intent(in) wei2)
Get the reference temperature/sst climatology and its trend at analysis time. The data is time interpolated between two bounding months.
Parameters:
tf_clm_ta Climatological tf/sst at analysis time
tf_clm_trend Climatological tf/sst trend at analysis time
xlats Latitudes on the climatological data grid
xlons Longitudes on the climatological data grid
nlat 'j' dimension on the climatological grid
nlon 'i' dimension on the climatological grid
mon1 First bounding month
mon2 Second bounding month
wei1 Weighting of first bounding month
wei2 Weighting of second bounding month
Author:
Xu Li
Date:
March 2019
Definition at line 1623 of file cycle.f90.
Referenced by get_tf_clm().
subroutine get_tim_wei (integer, intent(in) iy, integer, intent(in) im, integer, intent(in) id, integer, intent(in) ih, integer, intent(out) mon1, integer, intent(out) mon2, real, intent(out) wei1, real, intent(out) wei2)
For a given date, determine the bounding months and the linear time interpolation weights.
Parameters:
iy The year
im The month
id The day
ih The hour
mon1 First bounding month
mon2 Second bounding month
wei1 Weighting of first bounding month
wei2 Weighting of second bounding month
Author:
Xu Li
Date:
March 2019
Definition at line 1866 of file cycle.f90.
Referenced by get_sal_clm(), and get_tf_clm().
subroutine intp_tile (real, dimension(idim_lalo,jdim_lalo), intent(in) tf_lalo, real, dimension(jdim_lalo), intent(in) dlats_lalo, real, dimension(idim_lalo), intent(in) dlons_lalo, integer, intent(in) jdim_lalo, integer, intent(in) idim_lalo, real, dimension(jdim_tile*idim_tile), intent(out) tf_tile, real, dimension(jdim_tile*idim_tile), intent(in) xlats_tile, real, dimension(jdim_tile*idim_tile), intent(in) xlons_tile, integer, intent(in) jdim_tile, integer, intent(in) idim_tile)
Interpolate lon/lat grid data to the fv3 native grid (tf_lalo => tf_tile). Does not account for a mask.
Parameters:
tf_lalo (idim_lalo,idim_lalo) field on the lat/lon regular grid.
dlats_lalo (jdim_lalo) latitudes along y direction of lat/lon regular grid points.
dlons_lalo (idim_lalo) longitudes along x direction of lat/lon regular grid points.
jdim_lalo number of y dimension of tf_lalo.
idim_lalo number of x dimension of tf_lalo.
xlats_tile (jdim_tile*idim_tile) latitudes of all tile grid points.
xlons_tile (jdim_tile*idim_tile) longitudes of all tile grid points.
jdim_tile number of y dimension of tf_tile.
idim_tile number of x dimension of tf_tile.
tf_tile (jdim_tile*idim_tile) field on the cubed sphere grid.
Author:
Xu Li
Definition at line 1777 of file cycle.f90.
Referenced by get_sal_clm(), and get_tf_clm().
subroutine nsst_water_reset (type(nsst_data), intent(inout) nsst, integer, intent(in) ij, real, intent(in) tf_thaw)
If the first guess was sea ice, but the analysis is open water, reset all nsst variables.
Parameters:
nsst Data structure that holds the nsst fields
ij Index of point to be updated
tf_thaw Reference temperature for former ice points
Author:
Xu Li
Definition at line 1508 of file cycle.f90.
Referenced by ADJUST_NSST().
program SFC_DRV ()
Stand alone surface/NSST cycle driver for the cubed-sphere grid. Each cubed-sphere tile runs independently on its own mpi task. The surface update component runs with threads. The NSST update component in not threaded.
There are three main options (which can be called in combination):
1.
Update the surface fields with sfccylce (do_sfccycle = .true.)
2.
Update the land states with increments read in from file (do_lndinc = .true.) Designed to work with either: 2a. A land increment file created by the GSI on the Gaussian grid. The increments are interpolated here to the model grid, using the same method as for the NST increments. This is currently implemented for applying soil temperature increments calculated from the EnKF assimilation of T2m (but this is not a requirement - any GSI-generated soil temperature increment file can be applied here). 2b. A land increment file created by JEDI, on the native model grid (cube sphere tiles). This is currently implemented for snow depth updates for the Noah model.
3.
Update the NSST field, several options:
3a. Update the NSST TREF field using GSI increments on the Gaussian grid. All other NSST fields are cycled. Invoke this option by setting namelist variable DONST=.true. and NST_FILE to the name of the GSI increment file.
3b. Run with NSST, but postpone the TREF update. Here all NSST fields are cycled. But the NSST IFD field is used to flag points that flipped from ice to open water. To invoke this option, set DONST=.true. and NST_FILE='NULL'.
INPUT FILES:
fngrid.$NNN The cubed-sphere grid file (contains grid point latitude and longitdue).
fnorog.$NNN The cubed-sphere orography file (contains land mask and orography).
fnbgsi.$NNN The cubed-sphere input sfc/nsst restart file.
$NST_FILE Gaussian GSI file which contains NSST TREF increments
$LND_SOI_FILE Gaussian GSI file which contains soil state increments
xainc.$NNN The cubed-sphere increment file (contains increments calculated by JEDI on the native model grid).
OUTPUT FILES:
fnbgso.$NNN The updated sfc/nsst restart file.
NOTE: $NNN corresponds to (mpi rank + 1)
NAMELIST VARIABLE DEFINITIONS:
IDIM,JDIM i/j dimension of a cubed-sphere tile.
LUGB Unit number used in the sfccycle subprogram to read input datasets. Next four should match the gfs_physics_nml
LSM Integer code for LSM (as in GFS_TYPES) 1 - Noah (note: added for land_da_adjust layers, however sfcsub routine (and likely others) assume the noah lsm
LSOIL Number of soil layers.
IY,IM,ID,IH Year, month, day, and hour of initial state.
FH Forecast hour
DELTSFC Cycling frequency in hours.
IALB Use modis albedo when '1'. Use brigleb when '0'.
USE_UFO Adjust sst and soil substrate temperature for differences between the filtered and unfiltered terrain. -DONST Process NSST records. -DO_SFCCYCLE Call sfccycle routine to update surface fields -DO_LNDINC Read in land increment files, and add increments to relevant states. -DO_SOI_INC Do land increments to soil states. -DO_SNO_INC Do land increments to snow states.
ISOT Use statsgo soil type when '1'. Use zobler when '0'.
IVEGSRC Use igbp veg type when '1'. Use sib when '2'.
ZSEA1/2_MM When running with NSST model, this is the lower/ upper bound of depth of sea temperature. In whole mm.
MAX_TASKS Normally, program should be run with a number of mpi tasks equal to the number of cubed-sphere tiles being processed. However, the current parallel scripts may over-specify the number of tasks. Set this variable to not process any ranks > (max_tasks-1). -NST_FILE path/name of the gaussian GSI file which contains NSST TREF increments. -LND_SOI_FILE path/name of the gaussian GSI file which contains soil state increments.
-2005-02-03: Iredell for global_analysis -2014-11-30: xuli add nst_anl -2015-05-26: Hang Lei Added NEMSIO read/write function in the code -2017-08-08: Gayno Modify to work on cubed-sphere grid. Added processing of NSST and TREF update. Added mpi directives. -2020-02-17: Clara Draper Added soil state increments capability.
Author:
Mark Iredell NOAA/EMC
Returns:
0 for success, error code otherwise.
Definition at line 106 of file cycle.f90.
References num_parthds().
subroutine SFCDRV (integer, intent(in) LUGB, integer, intent(in) IDIM, integer, intent(in) JDIM, integer, intent(in) LSM, integer, intent(in) LENSFC, integer, intent(in) LSOIL, real, intent(in) DELTSFC, integer, intent(in) IY, integer, intent(in) IM, integer, intent(in) ID, integer, intent(in) IH, real, intent(in) FH, integer, intent(in) IALB, logical, intent(in) USE_UFO, logical, intent(in) DO_NSST, logical, intent(in) DO_SFCCYCLE, logical, intent(in) DO_LNDINC, real, intent(in) ZSEA1, real, intent(in) ZSEA2, integer, intent(in) ISOT, integer, intent(in) IVEGSRC, integer, intent(in) MYRANK)
Driver routine for updating the surface fields. This program runs in two different modes:
1.
Analysis mode (FH=0.)
This program merges climatology, analysis and forecast guess to create new surface fields. If analysis file is given, the program uses it if date of the analysis matches with IY,IM,ID,IH (see Note below).
2.
Forecast mode (FH.GT.0.)
This program interpolates climatology to the date corresponding to the forecast hour. If surface analysis file is given, for the corresponding dates, the program will use it. This is forcing-by-observation experiment.
If the date of the analysis does not match given IY,IM,ID,IH, (and FH), the program searches an old analysis by going back 6 hours, then 12 hours, then one day upto NREPMX days (parameter statement in the SUBROTINE FIXRD. Now defined as 15). This allows the user to provide non-daily analysis to be used. If matching field is not found, the forecast guess will be used.
Variable naming convention for this program:
OROG .. Orography
ALB .. Snow-free albedo
SWE .. Snow water equivalent
ZOR .. Surface roughness length
VET .. Vegetation type
TSF .. Surface skin temperature. Sea surface temp. over ocean.
TG3 .. Deep soil temperature (at 500cm)
STC .. Soil temperature (LSOIL layrs)
SMC .. Total soil moisture (LSOIL layrs)
AIS .. Sea ice mask (0 or 1)
CNP .. Canopy water content
CV .. Convective cloud cover
CVB .. Convective cloud base
CVT .. Convective cloud top
SLI .. LAND/SEA/SEA-ICE mask. (1/0/2 respectively)
VEG .. Vegetation cover
SOT .. Soil type
SIH .. Sea ice thickness
SIC .. Sea ice concentration
SND .. Snow depth
SLC .. Liquid soil moisture (LSOIL layers)
VMN .. Vegetation cover minimum
VMX .. Vegetation cover maximum
SLP .. Slope type
ABS .. Maximum snow albedo
T2M .. 2m Temperature
Q2M .. 2m Specific Humidity
TICE .. Ice Temperature
OROG_UF .. Orography unfiltered
Most fields have a blending coefficient. This controls the blending of the forecast (first guess) and interpolated climatology or analyzed fields. When it is equal to 1.0, the pure forecast is used. When the coefficient is equal to 0, the pure climatology or analysis is used. The default values are set as follows:
Variables Land Sea ---------- Surface temperature Forecast Analysis Albedo Analysis Analysis Sea-ice Analysis Analysis Snow Analysis Forecast (over sea ice) Roughness Analysis Forecast Plant resistance Analysis Analysis Soil moisture Weighted average Analysis Soil temperature Forecast Analysis Canopy waver content Forecast Forecast Convective cloud cover Forecast Forecast Convective cloud bottm Forecast Forecast Convective cloud top Forecast Forecast Vegetation greenness Analysis Analysis Vegetation type Analysis Analysis Soil type Analysis Analysis
Parameters:
LUGB Fortran unit number uses in sfccycle subprogram to read input datasets.
IDIM 'i' dimension of the cubed-sphere tile
JDIM 'j' dimension of the cubed-sphere tile
LENSFC Total numberof points for the cubed-sphere tile
LSM Integer code for the land surface model 1 - Noah
LSOIL Number of soil layers
DELTSFC Cycling frequency in hours
IY Year of initial state
IM Month of initial state
ID Day of initial state
IH Hour of initial state
FH Forecast hour
IALB Use modis albedo when '1'. Use brigleb when '0'.
USE_UFO When true, adjust SST and soil temperature for differences between the filtered and unfiltered terrain.
DO_NSST When true, process NSST records.
DO_SFCCYCLE Call sfccycle routine to update surface fields
DO_LNDINC Read in land increment files, and add increments to requested states.
ZSEA1 When running NSST model, this is the lower bound of depth of sea temperature. In whole mm.
ZSEA2 When running NSST model, this is the upper bound of depth of sea temperature. In whole mm.
ISOT Use STATSGO soil type when '1'. Use Zobler when '0'.
IVEGSRC Use IGBP vegetation type when '1'. Use SIB when '2'.
MYRANK MPI rank number
Author:
Mark Iredell, George Gayno
Definition at line 308 of file cycle.f90.
References get_sal_clm(), and get_tf_clm().
subroutine tf_thaw_set (real, dimension(nx*ny), intent(in) tf_ij, integer, dimension(nx*ny), intent(in) mask_ij, integer, intent(in) itile, integer, intent(in) jtile, real, intent(in) tice, real, intent(in) tclm, real, intent(out) tf_thaw, integer, intent(in) nx, integer, intent(in) ny, integer, intent(inout) nset_thaw_s, integer, intent(inout) nset_thaw_i, integer, intent(inout) nset_thaw_c)
Set the background reference temperature (tf) for points where the ice has just melted.
Parameters:
tf_ij Foundation temperature background on FV3 native grids.
mask_ij Mask of the tile (FV3 native grids).
itile Location index in the 'i' direction.
jtile Location index in the 'j' direction.
tice Water temperature (calulated with a salinity formula).
tclm SST climatology valid at the analysis time.
tf_thaw Foundation temperature of thawed points.
nx 'i' dimension of tf_ij
ny 'j' dimension of tf_ij
nset_thaw_s Number of foundation temperature points filled via a search.
nset_thaw_i Number of ice points filled with a calculated tice.
nset_thaw_c Number of points filled with a weighted average of tice and tclm.
Author:
Xu Li
Definition at line 1418 of file cycle.f90.
Referenced by ADJUST_NSST().
real function tfreez (real salinity)
Compute the freezing point of water as a function of salinity. Constants taken from Gill, 1982.
Date:
21 September 1994.
Author:
Robert Grumbine
Parameters:
salinity The salinity.
Returns:
tfreez The freezing point of water.
Definition at line 1933 of file cycle.f90.
Referenced by land_increments::apply_land_da_adjustments_stc().
Author
Generated automatically by Doxygen for global_cycle from the source code.