.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkinds\&.f90\fP"
.br
.RI "\fIHold specification kinds for variable declaration\&. \fP"
.ti -1c
.RI "file \fBmodule_ncio\&.f90\fP"
.br
.RI "\fIFunctions to read and write netcdf files\&. \fP"
.ti -1c
.RI "file \fBmodule_nwp\&.f90\fP"
.br
.RI "\fIDefines FV3LAM and FVCOM forecast data structure\&. \fP"
.ti -1c
.RI "file \fBprocess_FVCOM\&.f90\fP"
.br
.RI "\fIThis is the code to put lake surface temperature and aerial ice concentration from GLERL-provided FVCOM forecast files (which have already been mapped to the FV3-LAM grid) into sfc_data\&.nc\&. \fP"
.in -1c
