module_ncio::ncio
NAME
module_ncio::ncio -
SYNOPSIS
Private Member Functions
generic add_new_var => add_new_var_2d,add_new_var_3d
Add a new 2d or 3d variable to ouput file.
procedure add_new_var_2d
Add a new 2d variable to output file.
procedure add_new_var_3d
Add a new 3d variable to output file.
procedure close => close_nc
Close netCDF file.
procedure convert_theta2t_2dgrid
Convert theta T (Kelvin) to T (deg C).
generic get_att => get_att_nc_int, get_att_nc_real, get_att_nc_string
Get attribute.
procedure get_att_nc_int
Get attribute.
procedure get_att_nc_real
Get attribute.
procedure get_att_nc_string
Get attribute.
procedure get_dim => get_dim_nc
read in dimension from the nc file
generic get_var => get_var_nc_double_1d, get_var_nc_double_2d,get_var_nc_double_3d,get_var_nc_real_1d, get_var_nc_real_2d,get_var_nc_real_3d,get_var_nc_short_1d, get_var_nc_short_2d,get_var_nc_int_1d, get_var_nc_int_2d,get_var_nc_int_3d,get_var_nc_char_1d, get_var_nc_char_2d,get_var_nc_char_3d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_char
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_char_1d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_char_2d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_char_3d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_double
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_double_1d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_double_2d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_double_3d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_int
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_int_1d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_int_2d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_int_3d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_real
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_real_1d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_real_2d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_real_3d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_short
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_short_1d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure get_var_nc_short_2d
Read in a 1d, 2d, 3d, or 4d field from the nc file.
procedure handle_err
Handle netCDF errors.
procedure open => open_nc
Open netCDF file.
generic replace_var => replace_var_nc_double_1d, replace_var_nc_double_2d,replace_var_nc_double_3d,replace_var_nc_real_1d, replace_var_nc_real_2d,replace_var_nc_real_3d,replace_var_nc_int_1d, replace_var_nc_int_2d,replace_var_nc_int_3d,replace_var_nc_char_1d, replace_var_nc_char_2d,replace_var_nc_char_3d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_char
Replace character type variable.
procedure replace_var_nc_char_1d
Replace character type variable.
procedure replace_var_nc_char_2d
Replace character type variable.
procedure replace_var_nc_char_3d
Replace 3D character type variable.
procedure replace_var_nc_double
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_double_1d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_double_2d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_double_3d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_int
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_int_1d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_int_2d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_int_3d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_real
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_real_1d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_real_2d
Replace 1d, 2d, 3d, or 4d field from the nc file.
procedure replace_var_nc_real_3d
Replace 1d, 2d, 3d, or 4d field from the nc file.
Private Attributes
integer debug_level
Debug level.
character(len=40), dimension(4) dimname
Name of dims.
integer, dimension(4) ends
Counts of dims.
character(len=256) filename
Name of data file.
integer ncid
File ID.
integer ndims
Number of dims.
integer status
Return code.
integer xtype
Type of data.
Detailed Description
Definition at line 16 of file module_ncio.f90.
Member Function/Subroutine Documentation
generic module_ncio::ncio::add_new_var () [private]
Add a new 2d or 3d variable to ouput file.
Returns:
Definition at line 88 of file module_ncio.f90.
References add_new_var_2d(), and add_new_var_3d().
procedure module_ncio::ncio::add_new_var_2d () [private]
Add a new 2d variable to output file.
Returns:
Definition at line 90 of file module_ncio.f90.
Referenced by add_new_var().
procedure module_ncio::ncio::add_new_var_3d () [private]
Add a new 3d variable to output file.
Returns:
Definition at line 91 of file module_ncio.f90.
Referenced by add_new_var().
procedure module_ncio::ncio::close () [private]
Close netCDF file.
Returns:
Definition at line 28 of file module_ncio.f90.
References module_ncio::close_nc().
procedure module_ncio::ncio::convert_theta2t_2dgrid () [private]
Convert theta T (Kelvin) to T (deg C).
Returns:
Definition at line 87 of file module_ncio.f90.
generic module_ncio::ncio::get_att () [private]
Get attribute.
Returns:
Definition at line 30 of file module_ncio.f90.
References get_att_nc_int(), get_att_nc_real(), and get_att_nc_string().
procedure module_ncio::ncio::get_att_nc_int () [private]
Get attribute.
Returns:
Definition at line 31 of file module_ncio.f90.
Referenced by get_att().
procedure module_ncio::ncio::get_att_nc_real () [private]
Get attribute.
Returns:
Definition at line 32 of file module_ncio.f90.
Referenced by get_att().
procedure module_ncio::ncio::get_att_nc_string () [private]
Get attribute.
Returns:
Definition at line 33 of file module_ncio.f90.
Referenced by get_att().
procedure module_ncio::ncio::get_dim () [private]
read in dimension from the nc file
Returns:
Definition at line 29 of file module_ncio.f90.
References module_ncio::get_dim_nc().
generic module_ncio::ncio::get_var () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 34 of file module_ncio.f90.
References get_var_nc_char_1d(), get_var_nc_char_2d(), get_var_nc_char_3d(), get_var_nc_double_1d(), get_var_nc_double_2d(), get_var_nc_double_3d(), get_var_nc_int_1d(), get_var_nc_int_2d(), get_var_nc_int_3d(), get_var_nc_real_1d(), get_var_nc_real_2d(), get_var_nc_real_3d(), get_var_nc_short_1d(), and get_var_nc_short_2d().
procedure module_ncio::ncio::get_var_nc_char () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 58 of file module_ncio.f90.
procedure module_ncio::ncio::get_var_nc_char_1d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 59 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_char_2d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 60 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_char_3d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 61 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_double () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 54 of file module_ncio.f90.
procedure module_ncio::ncio::get_var_nc_double_1d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 55 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_double_2d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 56 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_double_3d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 57 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_int () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 46 of file module_ncio.f90.
procedure module_ncio::ncio::get_var_nc_int_1d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 47 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_int_2d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 48 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_int_3d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 49 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_real () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 50 of file module_ncio.f90.
procedure module_ncio::ncio::get_var_nc_real_1d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 51 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_real_2d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 52 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_real_3d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 53 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_short () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 43 of file module_ncio.f90.
procedure module_ncio::ncio::get_var_nc_short_1d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 44 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::get_var_nc_short_2d () [private]
Read in a 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 45 of file module_ncio.f90.
Referenced by get_var().
procedure module_ncio::ncio::handle_err () [private]
Handle netCDF errors.
Returns:
Definition at line 86 of file module_ncio.f90.
procedure module_ncio::ncio::open () [private]
Open netCDF file.
Returns:
Definition at line 27 of file module_ncio.f90.
References module_ncio::open_nc().
generic module_ncio::ncio::replace_var () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 62 of file module_ncio.f90.
References replace_var_nc_char_1d(), replace_var_nc_char_2d(), replace_var_nc_char_3d(), replace_var_nc_double_1d(), replace_var_nc_double_2d(), replace_var_nc_double_3d(), replace_var_nc_int_1d(), replace_var_nc_int_2d(), replace_var_nc_int_3d(), replace_var_nc_real_1d(), replace_var_nc_real_2d(), and replace_var_nc_real_3d().
procedure module_ncio::ncio::replace_var_nc_char () [private]
Replace character type variable.
Returns:
Definition at line 82 of file module_ncio.f90.
procedure module_ncio::ncio::replace_var_nc_char_1d () [private]
Replace character type variable.
Returns:
Definition at line 83 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_char_2d () [private]
Replace character type variable.
Returns:
Definition at line 84 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_char_3d () [private]
Replace 3D character type variable.
Returns:
Definition at line 85 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_double () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 78 of file module_ncio.f90.
procedure module_ncio::ncio::replace_var_nc_double_1d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 79 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_double_2d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 80 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_double_3d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 81 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_int () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 70 of file module_ncio.f90.
procedure module_ncio::ncio::replace_var_nc_int_1d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 71 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_int_2d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 72 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_int_3d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 73 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_real () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 74 of file module_ncio.f90.
procedure module_ncio::ncio::replace_var_nc_real_1d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 75 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_real_2d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 76 of file module_ncio.f90.
Referenced by replace_var().
procedure module_ncio::ncio::replace_var_nc_real_3d () [private]
Replace 1d, 2d, 3d, or 4d field from the nc file.
Returns:
Definition at line 77 of file module_ncio.f90.
Referenced by replace_var().
Field Documentation
integer module_ncio::ncio::debug_level [private]
Debug level.
Definition at line 20 of file module_ncio.f90.
character(len=40), dimension(4) module_ncio::ncio::dimname [private]
Name of dims.
Definition at line 25 of file module_ncio.f90.
integer, dimension(4) module_ncio::ncio::ends [private]
Counts of dims.
Definition at line 23 of file module_ncio.f90.
character(len=256) module_ncio::ncio::filename [private]
Name of data file.
Definition at line 17 of file module_ncio.f90.
integer module_ncio::ncio::ncid [private]
File ID.
Definition at line 18 of file module_ncio.f90.
integer module_ncio::ncio::ndims [private]
Number of dims.
Definition at line 22 of file module_ncio.f90.
integer module_ncio::ncio::status [private]
Return code.
Definition at line 19 of file module_ncio.f90.
integer module_ncio::ncio::xtype [private]
Type of data.
Definition at line 24 of file module_ncio.f90.
Author
Generated automatically by Doxygen for fvcom_tools from the source code.