.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_ncio.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_ncio.f90 \- 
.PP
Functions to read and write netcdf files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBmodule_ncio\fP"
.br
.RI "\fIFunctions to read and write netcdf files\&. \fP"
.ti -1c
.RI "type \fBmodule_ncio::ncio\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to read and write netcdf files\&. 


.PP
\fBAuthor:\fP
.RS 4
Ming Hu 
.RE
.PP
\fBDate:\fP
.RS 4
2017-11-01 
.RE
.PP

.PP
Definition in file \fBmodule_ncio\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
