.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog_gsl.fd Directory Reference" 3 "Wed Mar 13 2024" "Version 1.13.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog_gsl.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgsl_oro_data\&.f90\fP"
.br
.RI "\fICreate orographic (oro_data) files for use by GSL drag suite\&. \fP"
.ti -1c
.RI "file \fBmodule_gsl_oro_data_lg_scale\&.f90\fP"
.br
.RI "\fICalculates large-scale GWD orographic stats for FV3GFS grids\&. \fP"
.ti -1c
.RI "file \fBmodule_gsl_oro_data_sm_scale\&.f90\fP"
.br
.RI "\fICalculates small-scale GWD orographic stats for FV3GFS grids\&. \fP"
.in -1c
