/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/inland.fd/inland.F90
NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/inland.fd/inland.F90 -
Program and associated routines for creating inland mask.
SYNOPSIS
Functions/Subroutines
subroutine free_mem ()
Deallocate module arrays.
program inland_mask
This program creates the inland mask and writes it to the orography data files.
subroutine mark_global_inland (cs_res)
Create inland mask for global grid.
recursive subroutine mark_global_inland_rec_d (i, j, t, rd)
Recursively walk through neighbors marking inland points for global grid.
subroutine mark_inland_reg (cs_res)
Create inland mask for regional grid.
recursive subroutine mark_regional_inland_rec_d (i, j, t, rd)
Recursively walk through neighbors marking inland points for regional grid.
subroutine nc_opchk (stat, opname)
Check NetCDF return code and print error message.
subroutine read_orog (cs_res)
Read in orography (land fraction) data.
subroutine read_orog_reg (cs_res)
Read in orography (land fraction) data for regional grid.
subroutine write_inland (cs_res)
Write inland back to the orography data files for global grid.
subroutine write_inland_reg (cs_res)
Write inland back to the orography data files for regional grid.
Detailed Description
Program and associated routines for creating inland mask.
Author:
Ning Wang
Date:
July 1, 2020
Definition in file inland.F90.
Function/Subroutine Documentation
subroutine inland_mask::free_mem ()
Deallocate module arrays.
Definition at line 455 of file inland.F90.
Referenced by inland_mask().
program inland_mask ()
This program creates the inland mask and writes it to the orography data files.
Author:
Ning Wang
Returns:
0 for success, error otherwise.
Definition at line 9 of file inland.F90.
References free_mem(), cs_nb::idx_init(), cs_nb::idx_init_reg(), mark_global_inland(), mark_inland_reg(), read_orog(), read_orog_reg(), write_inland(), and write_inland_reg().
subroutine inland_mask::mark_global_inland (integer, intent(in)cs_res)
Create inland mask for global grid.
Parameters:
cs_res cubed sphere resolution (48, 96...)
Author:
Ning Wang
Definition at line 79 of file inland.F90.
References mark_global_inland_rec_d().
Referenced by inland_mask().
recursive subroutine inland_mask::mark_global_inland_rec_d (integer, intent(in)i, integer, intent(in)j, integer, intent(in)t, integer, intent(in)rd)
Recursively walk through neighbors marking inland points for global grid.
Parameters:
i cell index
j cell index
t tile number
rd current recursive depth (starts at 0)
Author:
Ning Wang
Definition at line 161 of file inland.F90.
References cs_nb::neighbors().
Referenced by mark_global_inland().
subroutine inland_mask::mark_inland_reg (integer, intent(in)cs_res)
Create inland mask for regional grid.
Parameters:
cs_res cubed sphere resolution (48, 96...)
Author:
Ning Wang
Definition at line 104 of file inland.F90.
References mark_regional_inland_rec_d().
Referenced by inland_mask().
recursive subroutine inland_mask::mark_regional_inland_rec_d (integer, intent(in)i, integer, intent(in)j, integer, intent(in)t, integer, intent(in)rd)
Recursively walk through neighbors marking inland points for regional grid.
Parameters:
i cell index
j cell index
t tile face
rd current recursive depth (starts at 0)
Author:
Ning Wang
Definition at line 198 of file inland.F90.
References cs_nb::neighbors_reg().
Referenced by mark_inland_reg().
subroutine inland_mask::nc_opchk (integerstat, character(len=*)opname)
Check NetCDF return code and print error message.
Parameters:
stat status code returned from NetCDF
opname description of NetCDF operation called
Author:
Ning Wang
Definition at line 467 of file inland.F90.
Referenced by read_cubed_sphere_grid(), read_cubed_sphere_reg_grid(), read_orog(), read_orog_reg(), write_inland(), write_inland_reg(), write_lakedata_to_orodata(), and write_reg_lakedata_to_orodata().
subroutine inland_mask::read_orog (integer, intent(in)cs_res)
Read in orography (land fraction) data.
Parameters:
cs_res cubed sphere resolution (48, 96...)
Author:
Ning Wang
Definition at line 232 of file inland.F90.
References nc_opchk().
Referenced by inland_mask().
subroutine inland_mask::read_orog_reg (integer, intent(in)cs_res)
Read in orography (land fraction) data for regional grid.
Parameters:
cs_res cubed sphere resolution (48, 96...)
Author:
Ning Wang
Definition at line 278 of file inland.F90.
References nc_opchk().
Referenced by inland_mask().
subroutine inland_mask::write_inland (integer, intent(in)cs_res)
Write inland back to the orography data files for global grid.
Parameters:
cs_res cubed sphere resolution (48, 96...)
Author:
Ning Wang
Definition at line 330 of file inland.F90.
References nc_opchk().
Referenced by inland_mask().
subroutine inland_mask::write_inland_reg (integer, intent(in)cs_res)
Write inland back to the orography data files for regional grid.
Parameters:
cs_res cubed sphere resolution (48, 96...)
Author:
Ning Wang
Definition at line 392 of file inland.F90.
References nc_opchk().
Referenced by inland_mask().
Author
Generated automatically by Doxygen for orog_mask_tools from the source code.