/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/interp.F90
NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/interp.F90 - Read the input source data and interpolate it to the model grid.
SYNOPSIS
Functions/Subroutines
subroutine adjust_for_landice (field, vegt, idim, jdim, field_ch)
Ensure consistent fields at land ice points.
subroutine interp (localpet, method, input_file)
Read the input source data and interpolate it to the model grid.
Detailed Description
Read the input source data and interpolate it to the model grid.
Author:
George Gayno
Date:
2018
Definition in file interp.F90.
Function/Subroutine Documentation
subroutine adjust_for_landice (real(esmf_kind_r4), dimension(idim,jdim), intent(inout) field, real(esmf_kind_i4), dimension(idim,jdim), intent(in) vegt, integer, intent(in) idim, integer, intent(in) jdim, character(len=*), intent(in) field_ch)
Ensure consistent fields at land ice points. Land ice is vegetation type 15 (variable landice). output is Model field.
Parameters:
field Model field before adjustments for land ice.
vegt Vegetation type on the model tile.
idim i dimension of model tile.
jdim j dimension of model tile.
field_ch Field name.
Author:
George Gayno NCEP/EMC
Definition at line 291 of file interp.F90.
Referenced by interp().
subroutine interp (integer localpet, type(esmf_regridmethod_flag), intent(in) method, character(len=*), intent(in) input_file)
Read the input source data and interpolate it to the model grid.
Parameters:
localpet this mpi task
method interpolation method.defined where mask=1
input_file filename of input source data.
Author:
George Gayno
Date:
2018
Definition at line 14 of file interp.F90.
References adjust_for_landice(), model_grid::data_field_mdl, utils::error_handler(), source_grid::field_names, program_setup::fract_vegsoil_type, source_grid::grid_src, model_grid::i_mdl, source_grid::i_src, model_grid::j_mdl, source_grid::j_src, model_grid::latitude_field_mdl, model_grid::longitude_field_mdl, model_grid::mask_field_mdl, model_grid::missing, utils::netcdf_err(), source_grid::num_fields, model_grid::num_tiles, source_grid::num_time_recs, output(), search(), and model_grid::vegt_field_mdl.
Referenced by driver().
Author
Generated automatically by Doxygen for sfc_climo_gen from the source code.