.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/output_frac_cats.F90" 3 "Mon Apr 17 2023" "Version 1.10.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/output_frac_cats.F90 \- Write model categorical data for a single tile\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBoutput_frac_cats\fP"
.br
.RI "Output categorical data such as vegetation type\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBoutput_frac_cats::output_driver\fP (data_one_tile, dom_cat_one_tile, lat_one_tile, lon_one_tile, i_mdl, j_mdl, num_categories, tile)"
.br
.RI "Driver routine to output model categorical data\&. "
.ti -1c
.RI "subroutine \fBoutput_frac_cats::writeit\fP (out_file, iout, jout, num_categories, latitude, longitude, data_pct, dominant_cat)"
.br
.RI "Write data to a netcdf file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Write model categorical data for a single tile\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP
\fBDate:\fP
.RS 4
2022 
.RE
.PP

.PP
Definition in file \fBoutput_frac_cats\&.F90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for sfc_climo_gen from the source code\&.
