output_frac_cats
NAME
output_frac_cats - Output categorical data such as vegetation type.
SYNOPSIS
Functions/Subroutines
subroutine, public output_driver (data_one_tile, dom_cat_one_tile, lat_one_tile, lon_one_tile, i_mdl, j_mdl, num_categories, tile)
Driver routine to output model categorical data.
subroutine writeit (out_file, iout, jout, num_categories, latitude, longitude, data_pct, dominant_cat)
Write data to a netcdf file.
Detailed Description
Output categorical data such as vegetation type.
Include percentage of each category within a model grid box and the dominant category.
Author:
George Gayno NCEP/EMC
Date:
2022
Function/Subroutine Documentation
subroutine, public output_frac_cats::output_driver (real(esmf_kind_r4), dimension(i_mdl,j_mdl,num_categories), intent(in) data_one_tile, real(esmf_kind_r4), dimension(i_mdl,j_mdl), intent(in) dom_cat_one_tile, real(esmf_kind_r4), dimension(i_mdl,j_mdl), intent(in) lat_one_tile, real(esmf_kind_r4), dimension(i_mdl,j_mdl), intent(in) lon_one_tile, integer, intent(in) i_mdl, integer, intent(in) j_mdl, integer, intent(in) num_categories, integer, intent(in) tile)
Driver routine to output model categorical data.
Parameters:
data_one_tile The percentage of each category within a model grid cell.
dom_cat_one_tile The dominant category within a model grid cell.
lat_one_tile Latitude of each model grid cell.
lon_one_tile Longitude of each model grid cell.
i_mdl i dimension of model grid.
j_mdl j dimension of model grid.
num_categories Number of categories.
tile Tile number.
Author:
George Gayno
Date:
2022
Definition at line 33 of file output_frac_cats.F90.
References source_grid::field_names, model_grid::grid_tiles, program_setup::halo, and writeit().
Referenced by interp_frac_cats().
subroutine output_frac_cats::writeit (character(len=*), intent(in) out_file, integer, intent(in) iout, integer, intent(in) jout, integer, intent(in) num_categories, real(esmf_kind_r4), dimension(iout,jout), intent(in) latitude, real(esmf_kind_r4), dimension(iout,jout), intent(in) longitude, real(esmf_kind_r4), dimension(iout,jout,num_categories), intent(in) data_pct, real(esmf_kind_r4), dimension(iout,jout), intent(in) dominant_cat)
Write data to a netcdf file.
Parameters:
out_file Output file name.
iout i-dimension of data.
jout j-dimension of data.
num_categories Number of categories.
latitude Latitude of data.
longitude Longitude of data.
data_pct Percentage of each category in each model grid cell.
dominant_cat Dominant category in each model grid cell.
Definition at line 114 of file output_frac_cats.F90.
References source_grid::day_of_rec, source_grid::field_names, utils::netcdf_err(), source_grid::num_time_recs, and source_grid::source.
Referenced by output_driver().
Author
Generated automatically by Doxygen for sfc_climo_gen from the source code.