.TH "/home/ed/UFS_UTILS/sorc/sfc_climo_gen.fd/program_setup.f90" 3 "Thu Mar 11 2021" "Version 1.0.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/UFS_UTILS/sorc/sfc_climo_gen.fd/program_setup.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBprogram_setup\fP"
.br
.RI "program setup "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBprogram_setup::read_setup_namelist\fP (localpet)"
.br
.RI "read setup namelist "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBprogram_setup::halo\fP = 0"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_facsf_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_leaf_area_index_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_maximum_snow_albedo_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_slope_type_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_snowfree_albedo_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_soil_type_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_substrate_temperature_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_vegetation_greenness_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::input_vegetation_type_file\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=50), public \fBprogram_setup::leaf_area_index_method\fP ='bilinear'"
.br
.ti -1c
.RI "character(len=50), public \fBprogram_setup::maximum_snow_albedo_method\fP ='bilinear'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::mosaic_file_mdl\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), public \fBprogram_setup::orog_dir_mdl\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=500), dimension(6), public \fBprogram_setup::orog_files_mdl\fP = 'NULL'"
.br
.ti -1c
.RI "character(len=50), public \fBprogram_setup::snowfree_albedo_method\fP ='bilinear'"
.br
.ti -1c
.RI "character(len=50), public \fBprogram_setup::vegetation_greenness_method\fP ='bilinear'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for sfc_climo_gen from the source code\&.
