.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/program_setup.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/sfc_climo_gen.fd/program_setup.f90 \- 
.PP
Program setup\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBprogram_setup\fP"
.br
.RI "\fISet up program execution\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Program setup\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno 
.RE
.PP
\fBDate:\fP
.RS 4
2018 
.RE
.PP

.PP
Definition in file \fBprogram_setup\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for sfc_climo_gen from the source code\&.
