source_grid
NAME
source_grid - Read grid specs, date information and land/sea mask for the source data that will be interpolated to the model grid.
SYNOPSIS
Functions/Subroutines
subroutine, public define_source_grid (localpet, npets, input_file)
Defines esmf grid object for source grid.
subroutine, public source_grid_cleanup
Free up memory associated with this module.
Variables
integer, dimension(:), allocatable, public day_of_rec
Day of each time record with respect to Jan 1.
character(len=50), dimension(:), allocatable, public field_names
Names of fields to be processed.
type(esmf_grid), public grid_src
ESMF grid object for the source grid.
integer, public i_src
i dimension of the source grid.
integer, public j_src
j dimension of the source grid.
integer, public num_fields
Number of fields in the file.
integer, public num_records
Number of fields times time records.
integer, public num_time_recs
Number of time records.
character(len=75), public source
Original source of the data.
Detailed Description
Read grid specs, date information and land/sea mask for the source data that will be interpolated to the model grid.
Also, sets up the ESMF grid object for the source grid. Source grid is assumed to be global lat/lon.
Author:
George Gayno
Date:
2018
Function/Subroutine Documentation
subroutine, public source_grid::define_source_grid (integer, intent(in) localpet, integer, intent(in) npets, character(len=*), intent(in) input_file)
Defines esmf grid object for source grid. Retrieves date and field information from source file.
Read date information from input source data file. Create esmf grid object for the source grid.
Parameters:
localpet mpi task number
npets total number mpi tasks
input_file file containing the source grid data.
Author:
George Gayno
Date:
2018
Definition at line 52 of file source_grid.F90.
References day_of_rec, utils::error_handler(), field_names, grid_src, i_src, j_src, utils::netcdf_err(), num_fields, num_records, num_time_recs, and source.
Referenced by driver().
subroutine, public source_grid::source_grid_cleanup ()
Free up memory associated with this module.
Author:
George Gayno
Date:
2018
Definition at line 404 of file source_grid.F90.
References day_of_rec, field_names, and grid_src.
Referenced by driver().
Variable Documentation
integer, dimension(:), allocatable, public source_grid::day_of_rec
Day of each time record with respect to Jan 1.
Definition at line 31 of file source_grid.F90.
Referenced by define_source_grid(), output(), source_grid_cleanup(), and output_frac_cats::writeit().
character(len=50), dimension(:), allocatable, public source_grid::field_names
Names of fields to be processed.
Definition at line 21 of file source_grid.F90.
Referenced by define_source_grid(), interp(), interp_frac_cats(), output(), output_frac_cats::output_driver(), source_grid_cleanup(), and output_frac_cats::writeit().
type(esmf_grid), public source_grid::grid_src
ESMF grid object for the source grid.
Definition at line 34 of file source_grid.F90.
Referenced by define_source_grid(), interp(), interp_frac_cats(), and source_grid_cleanup().
integer, public source_grid::i_src
i dimension of the source grid.
Definition at line 24 of file source_grid.F90.
Referenced by define_source_grid(), interp(), and interp_frac_cats().
integer, public source_grid::j_src
j dimension of the source grid.
Definition at line 25 of file source_grid.F90.
Referenced by define_source_grid(), interp(), and interp_frac_cats().
integer, public source_grid::num_fields
Number of fields in the file. Some files have more than one (ex: the 4-component albedo).
Definition at line 28 of file source_grid.F90.
Referenced by define_source_grid(), interp(), and output().
integer, public source_grid::num_records
Number of fields times time records.
Definition at line 26 of file source_grid.F90.
Referenced by define_source_grid(), and output().
integer, public source_grid::num_time_recs
Number of time records.
Definition at line 27 of file source_grid.F90.
Referenced by define_source_grid(), interp(), output(), and output_frac_cats::writeit().
character(len=75), public source_grid::source
Original source of the data.
Definition at line 22 of file source_grid.F90.
Referenced by define_source_grid(), output(), and output_frac_cats::writeit().
Author
Generated automatically by Doxygen for sfc_climo_gen from the source code.