.TH "/home/ed/UFS_UTILS/sorc/sfc_climo_gen.fd/utils.f90" 3 "Thu Mar 11 2021" "Version 1.0.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/UFS_UTILS/sorc/sfc_climo_gen.fd/utils.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fButils::error_handler\fP (string, rc)"
.br
.ti -1c
.RI "subroutine, public \fButils::netcdf_err\fP (err, string)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for sfc_climo_gen from the source code\&.
