/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/utils.F90
NAME
/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/utils.F90 -
Contains utility routines.
SYNOPSIS
Functions/Subroutines
subroutine error_handler (string, rc)
General error handler.
subroutine netcdf_err (err, string)
Error handler for netcdf.
subroutine to_lower (strIn)
Convert from upper to lowercase.
character(len=len(strin)) function to_upper (strIn)
Convert string from lower to uppercase.
Detailed Description
Contains utility routines.
Definition in file utils.F90.
Function/Subroutine Documentation
subroutine error_handler (character(len=*), intent(in)string, integer, intent(in)rc)
General error handler.
Parameters:
string error message
rc error status code
Definition at line 9 of file utils.F90.
Referenced by surface::adjust_soil_levels(), surface::adjust_soilt_for_terrain(), atmosphere::atmosphere_driver(), surface::calc_liq_soil_moisture(), surface::check_smois_land(), chgres(), atmosphere::compute_zh(), input_data::convert_winds(), atmosphere::convert_winds(), atmosphere::create_atm_b4adj_esmf_fields(), atmosphere::create_atm_esmf_fields(), surface::create_nst_esmf_fields(), surface::create_surface_esmf_fields(), model_grid::define_input_grid_gaussian(), model_grid::define_input_grid_gfs_grib2(), model_grid::define_input_grid_grib2(), model_grid::define_input_grid_mosaic(), model_grid::define_target_grid(), model_grid::get_model_latlons(), model_grid::get_model_mask_terrain(), static_data::get_static_fields(), input_data::handle_grib_error(), atmosphere::horiz_interp_thomp_mp_climo(), input_data::init_atm_esmf_fields(), surface::interp(), atmosphere::newpr1(), atmosphere::newps(), surface::nst_land_fill(), surface::qc_check(), input_data::read_grib_soil(), input_data::read_input_atm_gaussian_nemsio_file(), input_data::read_input_atm_gaussian_netcdf_file(), input_data::read_input_atm_gfs_gaussian_nemsio_file(), input_data::read_input_atm_gfs_sigio_file(), input_data::read_input_atm_grib2_file(), input_data::read_input_atm_restart_file(), input_data::read_input_atm_tiled_history_file(), input_data::read_input_nst_data(), input_data::read_input_nst_nemsio_file(), input_data::read_input_nst_netcdf_file(), input_data::read_input_sfc_data(), input_data::read_input_sfc_gaussian_nemsio_file(), input_data::read_input_sfc_gfs_gaussian_nemsio_file(), input_data::read_input_sfc_gfs_sfcio_file(), input_data::read_input_sfc_grib2_file(), input_data::read_input_sfc_netcdf_file(), input_data::read_input_sfc_restart_file(), program_setup::read_setup_namelist(), thompson_mp_climo_data::read_thomp_mp_climo_data(), program_setup::read_varmap(), atmosphere::read_vcoord_info(), input_data::read_winds(), surface::replace_land_sfcparams(), surface::rescale_soil_moisture(), surface::roughness(), atmosphere::vintg(), atmosphere::vintg_thomp_mp_climo(), write_fv3_atm_bndy_data_netcdf(), write_fv3_atm_data_netcdf(), and write_fv3_sfc_data_netcdf().
subroutine netcdf_err (integer, intent(in)err, character(len=*), intent(in)string)
Error handler for netcdf.
Parameters:
err error status code
string error message
Definition at line 31 of file utils.F90.
Referenced by model_grid::define_input_grid_gaussian(), model_grid::define_input_grid_grib2(), model_grid::define_input_grid_mosaic(), model_grid::define_target_grid(), model_grid::get_model_latlons(), model_grid::get_model_mask_terrain(), input_data::read_fv3_grid_data_netcdf(), input_data::read_input_atm_gaussian_netcdf_file(), input_data::read_input_atm_restart_file(), input_data::read_input_atm_tiled_history_file(), input_data::read_input_sfc_grib2_file(), input_data::read_input_sfc_netcdf_file(), input_data::read_input_sfc_restart_file(), static_data::read_static_file(), thompson_mp_climo_data::read_thomp_mp_climo_data(), write_fv3_atm_bndy_data_netcdf(), write_fv3_atm_data_netcdf(), write_fv3_atm_header_netcdf(), and write_fv3_sfc_data_netcdf().
subroutine to_lower (character(len=*), intent(inout)strIn)
Convert from upper to lowercase.
Author:
Clive Page
Adapted from http://www.star.le.ac.uk/~cgp/fortran.html (25 May 2012)
Parameters:
strIn string to convert
Definition at line 84 of file utils.F90.
Referenced by program_setup::read_setup_namelist().
character(len=len(strin)) function to_upper (character(len=*), intent(in)strIn)
Convert string from lower to uppercase.
Author:
Clive Page
Adapted from http://www.star.le.ac.uk/~cgp/fortran.html (25 May 2012)
Parameters:
strIn string to convert
Returns:
strOut string in uppercase
Definition at line 59 of file utils.F90.
Referenced by input_data::read_input_sfc_grib2_file().
Author
Generated automatically by Doxygen for chgres_cube from the source code.