.TH "/home/ed/UFS_UTILS/sorc/vcoord_gen.fd/vcoord_gen.f90" 3 "Tue Mar 9 2021" "Version 1.0.0" "vcoord_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/UFS_UTILS/sorc/vcoord_gen.fd/vcoord_gen.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBvcoord_gen\fP (levs, lupp, pbot, psig, ppre, pupp, ptop, dpbot, dpsig, dppre, dpupp, dptop, pmin, ak, bk)"
.br
.in -1c
.SH "Detailed Description"
.PP 
vcoord_gen Generates hybrid coordinate interface profiles 
.PP
\fBAuthor\fP
.RS 4
Iredell 
.RE
.PP
\fBDate\fP
.RS 4
2008-08-01 
.RE
.PP

.PP
Definition in file \fBvcoord_gen\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for vcoord_gen from the source code\&.
