grib2_util
NAME
grib2_util -
Utilities for use when reading grib2 data.
SYNOPSIS
Public Member Functions
subroutine, public convert_omega (omega, p, t, q, clb, cub)
Convert omega to vertical velocity.
elemental real function, public fpvsnew (t)
Compute saturation vapor pressure.
subroutine, public rh2spfh (rh_sphum, p, t)
Convert relative humidity to specific humidity.
subroutine, public rh2spfh_gfs (rh_sphum, p, t)
Convert relative humidity to specific humidity (GFS formula) Calculation of saturation water vapor pressure is based on GFS function fvpsnew (Phillips 1982).
Detailed Description
Utilities for use when reading grib2 data.
This module contains routines to:
convert from RH to specific humidity
convert from omega to dzdt.
George Gayno NCEP/EMC
Definition at line 12 of file grib2_util.F90.
Member Function/Subroutine Documentation
subroutine, public grib2_util::convert_omega (real(esmf_kind_r8), dimension(:,:,:), pointeromega, real(esmf_kind_r8), dimension(:,:,:), pointerp, real(esmf_kind_r8), dimension(:,:,:), pointert, real(esmf_kind_r8), dimension(:,:,:), pointerq, integer, dimension(3)clb, integer, dimension(3)cub)
Convert omega to vertical velocity.
Parameters:
omega on input, vertical velocity on output
p pressure
t temperature
q specific humidity
clb lower bounds of indices processed by this mpi task
cub upper bounds of indices processed by this mpi task
Author:
Larissa Reames
Jeff Beck
Definition at line 217 of file grib2_util.F90.
Referenced by atm_input_data::read_input_atm_grib2_file().
elemental real function, public grib2_util::fpvsnew (real(esmf_kind_r8), intent(in)t)
Compute saturation vapor pressure.
Parameters:
t temperature in Kelvin
Returns:
fpvsnew Saturation vapor pressure
Author:
N Phillips w/NMC2X2
Date:
30 dec 82
Definition at line 135 of file grib2_util.F90.
Referenced by rh2spfh_gfs().
subroutine, public grib2_util::rh2spfh (real(esmf_kind_r4), dimension(i_input,j_input), intent(inout)rh_sphum, real(esmf_kind_r8), intent(in)p, real(esmf_kind_r8), dimension(i_input,j_input), intent(in)t)
Convert relative humidity to specific humidity. Calculation of saturation water vapor pressure is based on Brock and Richardson 2001 (Meterological Measurement Systems, p. 86, equation 5.1)
Parameters:
rh_sphum rel humidity (%) on input. spec hum (kg/kg) on output.
p pressure in Pa
t temperature
Author:
Larissa Reames
Jeff Beck
Definition at line 37 of file grib2_util.F90.
Referenced by atm_input_data::read_input_atm_grib2_file().
subroutine, public grib2_util::rh2spfh_gfs (real(esmf_kind_r4), dimension(i_input,j_input), intent(inout)rh_sphum, real(esmf_kind_r8), intent(in)p, real(esmf_kind_r8), dimension(i_input,j_input), intent(in)t)
Convert relative humidity to specific humidity (GFS formula) Calculation of saturation water vapor pressure is based on GFS function fvpsnew (Phillips 1982). The model does account for the variation of the latent heat of condensation with temperature. A linear interpolation is done between values in a calculated lookup table. Ice and water are considered separately. This option provides a consistent conversion for GFS grib2 data to be ingested.
Parameters:
rh_sphum rel humidity on input. spec hum on output.
p pressure in Pa
t temperature
Author:
Jili Dong NCEP/EMC
Definition at line 80 of file grib2_util.F90.
References fpvsnew().
Referenced by atm_input_data::read_input_atm_grib2_file().
Author
Generated automatically by Doxygen for chgres_cube from the source code.