.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/thompson_mp_climo_data.F90" 3 "Wed Mar 13 2024" "Version 1.13.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/thompson_mp_climo_data.F90 \- 
.PP
Process Thompson climatological MP data\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBthompson_mp_climo_data\fP"
.br
.RI "\fIModule to read the Thompson climatological MP data file and set up the associated esmf field and grid objects\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Process Thompson climatological MP data\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NOAA/EMC 
.RE
.PP

.PP
Definition in file \fBthompson_mp_climo_data\&.F90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
