.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/write_data.F90" 3 "Wed Mar 13 2024" "Version 1.13.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/write_data.F90 \- 
.PP
Writes the tiled and header files expected by the forecast model\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBwrite_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Writes the tiled and header files expected by the forecast model\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC
.RE
.PP
Write out target grid data into appropriate files for the forecast model\&. 
.PP
Definition in file \fBwrite_data\&.F90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
