.TH "init_mod::vardefs" 3 "Thu Jun 20 2024" "Version 1.13.0" "ocnice_prep" \" -*- nroff -*-
.ad l
.nh
.SH NAME
init_mod::vardefs
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "character(len=120) \fBlong_name\fP"
.br
.RI "A variable's long name\&. "
.ti -1c
.RI "character(len=20) \fBunits\fP"
.br
.RI "A variable's unit\&. "
.ti -1c
.RI "integer \fBvar_dimen\fP"
.br
.RI "A variable's dimensionality\&. "
.ti -1c
.RI "character(len=4) \fBvar_grid\fP"
.br
.RI "A variable's input grid location\&. "
.ti -1c
.RI "character(len=20) \fBvar_name\fP"
.br
.RI "A variable's variable name\&. "
.ti -1c
.RI "character(len=20) \fBvar_pair\fP"
.br
.RI "A variable's pair\&. "
.ti -1c
.RI "character(len=4) \fBvar_pair_grid\fP"
.br
.RI "A pair variable grid\&. "
.ti -1c
.RI "character(len=20) \fBvar_remapmethod\fP"
.br
.RI "A variable's mapping method\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file init_mod\&.F90\&.
.SH "Field Documentation"
.PP 
.SS "character(len=120) init_mod::vardefs::long_name"

.PP
A variable's long name\&. 
.PP
Definition at line 18 of file init_mod\&.F90\&.
.SS "character(len= 20) init_mod::vardefs::units"

.PP
A variable's unit\&. 
.PP
Definition at line 19 of file init_mod\&.F90\&.
.SS "integer init_mod::vardefs::var_dimen"

.PP
A variable's dimensionality\&. 
.PP
Definition at line 21 of file init_mod\&.F90\&.
.SS "character(len= 4) init_mod::vardefs::var_grid"

.PP
A variable's input grid location\&. 
.PP
Definition at line 22 of file init_mod\&.F90\&.
.SS "character(len= 20) init_mod::vardefs::var_name"

.PP
A variable's variable name\&. 
.PP
Definition at line 17 of file init_mod\&.F90\&.
.SS "character(len= 20) init_mod::vardefs::var_pair"

.PP
A variable's pair\&. 
.PP
Definition at line 23 of file init_mod\&.F90\&.
.SS "character(len= 4) init_mod::vardefs::var_pair_grid"

.PP
A pair variable grid\&. 
.PP
Definition at line 24 of file init_mod\&.F90\&.
.SS "character(len= 20) init_mod::vardefs::var_remapmethod"

.PP
A variable's mapping method\&. 
.PP
Definition at line 20 of file init_mod\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ocnice_prep from the source code\&.
