.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/vcoord_gen.fd Directory Reference" 3 "Wed Mar 13 2024" "Version 1.13.0" "vcoord_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/vcoord_gen.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdriver\&.f90\fP"
.br
.RI "\fIDriver for vcoord_gen\&. \fP"
.ti -1c
.RI "file \fBmatrix_utils\&.f90\fP"
.br
.RI "\fILower and upper triangular decomposition\&. \fP"
.ti -1c
.RI "file \fBvcoord_gen\&.f90\fP"
.br
.RI "\fIGenerates hybrid coordinate interface profiles\&. \fP"
.in -1c
