.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/vcoord_gen.fd/driver.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "vcoord_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/vcoord_gen.fd/driver.f90 \- 
Driver for vcoord_gen\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBdriver\fP"
.br
.RI "\fIThis program generates hybrid coordinate parameters from fields such as surface pressure, model top and the number of vertical levels\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Driver for vcoord_gen\&. 


.PP
\fBAuthor:\fP
.RS 4
Mark Iredell 
.RE
.PP
\fBDate:\fP
.RS 4
2008-08-01 
.RE
.PP

.PP
Definition in file \fBdriver\&.f90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program driver ()"

.PP
This program generates hybrid coordinate parameters from fields such as surface pressure, model top and the number of vertical levels\&. Outputs the 'ak' and 'bk' parameters used by the forecast model to define the hybrid levels\&.
.PP
\fBReturns:\fP
.RS 4
0 for success, error code otherwise\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
Mark Iredell 
.RE
.PP
\fBDate:\fP
.RS 4
2008-08-01 
.RE
.PP

.PP
Definition at line 12 of file driver\&.f90\&.
.PP
References vcoord_gen()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for vcoord_gen from the source code\&.
