/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/grid_tools.fd/filter_topo.fd/filter_topo.F90
NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/grid_tools.fd/filter_topo.fd/filter_topo.F90 - This program does ???
SYNOPSIS
#include <netcdf.inc>
Functions/Subroutines
subroutine cart_to_latlon (np, q, xs, ys)
???
subroutine cell_center2 (q1, q2, q3, q4, e2)
???
subroutine check (status)
Check results of netCDF call.
subroutine compute_filter_constants
Compute resolution-dependent values for the filtering.
real function cos_angle (p1, p2, p3)
???
subroutine del2_cubed_sphere (is, ie, js, je, isd, ied, jsd, jed, npx, npy, ntiles, q, area, dx, dy, dxc, dyc, sin_sg, nmax, cd, zero_ocean, mask, nested, regional)
???
subroutine del4_cubed_sphere (is, ie, js, je, isd, ied, jsd, jed, npx, npy, ntiles, q, area, dx, dy, dxc, dyc, sin_sg, nmax, zero_ocean, mask, nested, regional)
???
subroutine fill_AGRID_scalar_corners (q, ng, npx, npy, isd, jsd, fill)
???
subroutine fill_AGRID_xy_corners (x, y, ng, npx, npy, isd, jsd)
???
subroutine fill_BGRID_scalar_corners (q, ng, npx, npy, isd, jsd, fill)
???
subroutine fill_cubic_grid_halo (data, data2, halo, ioff, joff, sign1, sign2)
This routine fill the halo points for the cubic grid.
subroutine fill_DGRID_xy_corners (x, y, ng, npx, npy, isd, jsd)
???
program filter_topo
This program does ???
subroutine FV3_zs_filter (is, ie, js, je, isd, ied, jsd, jed, npx, npy, npx_global, ntiles, grid_type, stretch_fac, nested, area, dxa, dya, dx, dy, dxc, dyc, sin_sg, phis, regional)
???
real function get_area (p1, p4, p2, p3, radius)
???
real function great_circle_dist (q1, q2, radius)
???
subroutine latlon2xyz (p, e)
???
subroutine mid_pt3_cart (p1, p2, e)
???
subroutine mid_pt_sphere (p1, p2, pm)
???
subroutine read_grid_file (regional)
???
subroutine read_topo_file (regional)
???
real function spherical_angle (p1, p2, p3)
???
subroutine two_delta_filter (is, ie, js, je, isd, ied, jsd, jed, npx, npy, ntiles, q, area, dx, dy, dxa, dya, dxc, dyc, sin_sg, cd, zero_ocean, check_slope, filter_type, grid_type, mask, nested, ntmax, regional)
???
subroutine write_topo_file (is, ie, js, je, ntiles, q, regional)
Replace the topo_field.
Detailed Description
This program does ???
Author:
GFDL Programmer
Definition in file filter_topo.F90.
Function/Subroutine Documentation
subroutine filter_topo::cart_to_latlon (integer, intent(in) np, real, dimension(3,np), intent(inout) q, real, dimension(np), intent(inout) xs, real, dimension(np), intent(inout) ys)
???
Parameters:
np ???
q ???
xs ???
ys ???
Author:
GFDL Programmer
Definition at line 483 of file filter_topo.F90.
Referenced by cell_center2(), and mid_pt_sphere().
subroutine filter_topo::cell_center2 (real, dimension(2), intent(in) q1, real, dimension(2), intent(in) q2, real, dimension(2), intent(in) q3, real, dimension(2), intent(in) q4, real, dimension(2), intent(out) e2)
???
Parameters:
q1 ???
q2 ???
q3 ???
q4 ???
e2 ???
Author:
GFDL Programmer
Definition at line 584 of file filter_topo.F90.
References cart_to_latlon(), and latlon2xyz().
Referenced by read_grid_file().
subroutine filter_topo::check (integer, intent(in) status)
Check results of netCDF call.
Parameters:
status return code to check
Author:
GFDL Programmer
Definition at line 1959 of file filter_topo.F90.
Referenced by global_equiv_resol(), regional_grid(), and shave_nc().
subroutine filter_topo::compute_filter_constants ()
Compute resolution-dependent values for the filtering.
Author:
GFDL Programmer
Definition at line 1975 of file filter_topo.F90.
Referenced by filter_topo().
real function filter_topo::cos_angle (real, dimension(3), intent(in) p1, real, dimension(3), intent(in) p2, real, dimension(3), intent(in) p3)
???
Parameters:
p1 ???
p2 ???
p3 ???
Returns:
???
Author:
GFDL Programmer
Definition at line 530 of file filter_topo.F90.
Referenced by read_grid_file().
subroutine filter_topo::del2_cubed_sphere (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ntiles, real, dimension(is-ng:ie+ng, js-ng:je+ng, ntiles), intent(inout) q, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) area, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dx, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dy, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dxc, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dyc, real, dimension(4,isd:ied,jsd:jed, ntiles), intent(in) sin_sg, integer, intent(in) nmax, real, intent(in) cd, logical, intent(in) zero_ocean, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) mask, logical, intent(in) nested, logical, intent(in) regional)
???
Parameters:
is ???
ie ???
js ???
je ???
isd ???
ied ???
jsd ???
jed ???
npx ???
npy ???
ntiles ???
q ???
area ???
dx ???
dy ???
dxc ???
dyc ???
sin_sg ???
nmax ???
cd ???
zero_ocean ???
mask ???
nested ???
regional ???
Author:
GFDL Programmer
Definition at line 1599 of file filter_topo.F90.
References fill_cubic_grid_halo().
subroutine filter_topo::del4_cubed_sphere (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ntiles, real, dimension(isd:ied, jsd:jed, ntiles), intent(inout) q, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) area, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dx, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dy, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dxc, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dyc, real, dimension(4,isd:ied,jsd:jed, ntiles), intent(in) sin_sg, integer, intent(in) nmax, logical, intent(in) zero_ocean, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) mask, logical, intent(in) nested, logical, intent(in) regional)
???
Parameters:
is ???
ie ???
js ???
je ???
isd ???
ied ???
jsd ???
jed ???
npx ???
npy ???
ntiles ???
q ???
area ???
dx ???
dy ???
dxc ???
dyc ???
sin_sg ???
nmax ???
zero_ocean ???
mask ???
nested ???
regional ???
Author:
GFDL Programmer
Definition at line 1722 of file filter_topo.F90.
References fill_cubic_grid_halo().
Referenced by FV3_zs_filter().
subroutine filter_topo::fill_AGRID_scalar_corners (real, dimension(isd:,jsd:,:), intent(inout) q, integer, intent(in) ng, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) isd, integer, intent(in) jsd, integer, intent(in) fill)
???
Parameters:
q ???
ng ???
npx ???
npy ???
isd ???
jsd ???
fill ???
Author:
GFDL Programmer
Definition at line 237 of file filter_topo.F90.
subroutine filter_topo::fill_AGRID_xy_corners (real, dimension(isd:,jsd:,:), intent(inout) x, real, dimension(isd:,jsd:,:), intent(inout) y, integer, intent(in) ng, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) isd, integer, intent(in) jsd)
???
Parameters:
x ???
y ???
ng ???
npx ???
npy ???
isd ???
jsd ???
Author:
GFDL Programmer
Definition at line 338 of file filter_topo.F90.
subroutine filter_topo::fill_BGRID_scalar_corners (real, dimension(isd:,jsd:,:), intent(inout) q, integer, intent(in) ng, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) isd, integer, intent(in) jsd, integer, intent(in) fill)
???
Parameters:
q ???
ng ???
npx ???
npy ???
isd ???
jsd ???
fill ???
Author:
GFDL Programmer
Definition at line 287 of file filter_topo.F90.
subroutine filter_topo::fill_cubic_grid_halo (real, dimension(1-halo:,1-halo:,:), intent(inout) data, real, dimension(1-halo:,1-halo:,:), intent(inout) data2, integer, intent(in) halo, integer, intent(in) ioff, integer, intent(in) joff, integer, intent(in) sign1, integer, intent(in) sign2)
This routine fill the halo points for the cubic grid. ioff and joff is used to distinguish T, C, E, or N-cell.
Parameters:
data ???
data2 ???
halo ???
ioff ???
joff ???
sign1 ???
sign2 ???
Author:
GFDL Programmer
Definition at line 1116 of file filter_topo.F90.
Referenced by del2_cubed_sphere(), del4_cubed_sphere(), read_grid_file(), read_topo_file(), and two_delta_filter().
subroutine filter_topo::fill_DGRID_xy_corners (real, dimension(isd:,jsd:,:), intent(inout) x, real, dimension(isd:,jsd:,:), intent(inout) y, integer, intent(in) ng, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) isd, integer, intent(in) jsd)
???
Parameters:
x ???
y ???
ng ???
npx ???
npy ???
isd ???
jsd ???
Author:
GFDL Programmer
Definition at line 370 of file filter_topo.F90.
program filter_topo ()
This program does ???
Returns:
0 for success, error code otherwise.
Author:
S-J Lin (GFDL) for filtering algorithm(s)
Zhi Liang (GFDL) who packaged it into a standalone application.
Definition at line 10 of file filter_topo.F90.
References compute_filter_constants(), utils::grid_type, utils::nested, read_grid_file(), utils::read_namelist(), read_topo_file(), utils::regional, utils::stretch_fac, and write_topo_file().
subroutine filter_topo::FV3_zs_filter (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) npx_global, integer, intent(in) ntiles, integer, intent(in) grid_type, real, intent(in) stretch_fac, logical, intent(in) nested, real, dimension(isd:ied,jsd:jed, ntiles), intent(in) area, real, dimension(isd:ied,jsd:jed, ntiles), intent(in) dxa, real, dimension(isd:ied,jsd:jed, ntiles), intent(in) dya, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dx, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dy, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dxc, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dyc, real, dimension(4,isd:ied,jsd:jed,ntiles), intent(in) sin_sg, real, dimension(isd:ied,jsd:jed,ntiles), intent(inout) phis, logical, intent(in) regional)
???
Parameters:
is ???
ie ???
js ???
je ???
isd ???
ied ???
jsd ???
jed ???
npx ???
npy ???
npx_global ???
ntiles ???
grid_type ???
stretch_fac ???
nested ???
area ???
dxa ???
dya ???
dx ???
dy ???
dxc ???
dyc ???
sin_sg ???
phis ???
regional ???
Author:
GFDL Programmer
Definition at line 1187 of file filter_topo.F90.
References del4_cubed_sphere(), and two_delta_filter().
real function filter_topo::get_area (real, dimension(2), intent(in) p1, real, dimension(2), intent(in) p4, real, dimension(2), intent(in) p2, real, dimension(2), intent(in) p3, real, intent(in), optional radius)
???
Parameters:
p1 ???
p4 ???
p2 ???
p3 ???
radius ???
Returns:
area
Author:
GFDL Programmer
Definition at line 184 of file filter_topo.F90.
References latlon2xyz(), and spherical_angle().
Referenced by read_grid_file().
real function filter_topo::great_circle_dist (real, dimension(2), intent(in) q1, real, dimension(2), intent(in) q2, real, intent(in), optional radius)
???
Parameters:
q1
q2
radius
Returns:
???
Author:
GFDL Programmer
Definition at line 82 of file filter_topo.F90.
Referenced by read_grid_file().
subroutine filter_topo::latlon2xyz (real, dimension(2), intent(in) p, real, dimension(3), intent(out) e)
???
Parameters:
p ???
e ???
Author:
GFDL Programmer
Definition at line 449 of file filter_topo.F90.
Referenced by cell_center2(), get_area(), mid_pt_sphere(), and read_grid_file().
subroutine filter_topo::mid_pt3_cart (real, dimension(3), intent(in) p1, real, dimension(3), intent(in) p2, real, dimension(3), intent(out) e)
???
Parameters:
p1 ???
p2 ???
e ???
Author:
GFDL Programmer
Definition at line 416 of file filter_topo.F90.
Referenced by mid_pt_sphere(), and read_grid_file().
subroutine filter_topo::mid_pt_sphere (real, dimension(2), intent(in) p1, real, dimension(2), intent(in) p2, real, dimension(2), intent(out) pm)
???
Parameters:
p1 ???
p2 ???
pm ???
Author:
GFDL Programmer
Definition at line 397 of file filter_topo.F90.
References cart_to_latlon(), latlon2xyz(), and mid_pt3_cart().
Referenced by read_grid_file().
subroutine filter_topo::read_grid_file (logical, intent(in) regional)
???
Parameters:
regional ???
Author:
GFDL Programmer
Definition at line 615 of file filter_topo.F90.
References cell_center2(), cos_angle(), fill_cubic_grid_halo(), utils::fill_regional_halo(), get_area(), great_circle_dist(), utils::grid_file, utils::handle_err(), latlon2xyz(), mid_pt3_cart(), mid_pt_sphere(), utils::nested, and utils::regional.
Referenced by filter_topo().
subroutine filter_topo::read_topo_file (logical, intent(in) regional)
???
Parameters:
regional ???
Author:
GFDL Programmer
Definition at line 968 of file filter_topo.F90.
References fill_cubic_grid_halo().
Referenced by filter_topo().
real function filter_topo::spherical_angle (real, dimension(3) p1, real, dimension(3) p2, real, dimension(3) p3)
???
           p3
         /
        /
       p1 ---> angle
           p2
 
Parameters:
p1 ???
p2 ???
p3 ???
Returns:
???
Author:
GFDL Programmer
Definition at line 123 of file filter_topo.F90.
Referenced by get_area().
subroutine filter_topo::two_delta_filter (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) isd, integer, intent(in) ied, integer, intent(in) jsd, integer, intent(in) jed, integer, intent(in) npx, integer, intent(in) npy, integer, intent(in) ntiles, real, dimension(isd:ied, jsd:jed,ntiles), intent(inout) q, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) area, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dx, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dy, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) dxa, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) dya, real, dimension(isd:ied+1,jsd:jed, ntiles), intent(in) dxc, real, dimension(isd:ied, jsd:jed+1, ntiles), intent(in) dyc, real, dimension(4,isd:ied,jsd:jed, ntiles), intent(in) sin_sg, real, intent(in) cd, logical, intent(in) zero_ocean, logical, intent(in) check_slope, integer, intent(in) filter_type, integer, intent(in) grid_type, real, dimension(isd:ied, jsd:jed, ntiles), intent(in) mask, logical, intent(in) nested, integer, intent(in) ntmax, logical, intent(in) regional)
???
Parameters:
is ???
ie ???
js ???
je ???
isd ???
ied ???
jsd ???
jed ???
npx ???
npy ???
ntiles ???
q ???
area ???
dx ???
dy ???
dxa ???
dya ???
dxc ???
dyc ???
sin_sg ???
cd ???
zero_ocean ???
check_slope ???
filter_type ???
grid_type ???
mask ???
nested ???
ntmax ???
regional ???
Author:
GFDL Programmer
Definition at line 1270 of file filter_topo.F90.
References fill_cubic_grid_halo().
Referenced by FV3_zs_filter().
subroutine filter_topo::write_topo_file (integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) ntiles, real, dimension(is:ie,js:je,ntiles), intent(in) q, logical, intent(in) regional)
Replace the topo_field.
Parameters:
is ???
ie ???
js ???
je ???
ntiles ???
q ???
regional ???
Author:
GFDL Programmer
Definition at line 1068 of file filter_topo.F90.
Referenced by filter_topo().
Author
Generated automatically by Doxygen for grid_tools from the source code.