.TH "pfun::sinhox" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::sinhox
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBsinhox_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sinh(x)/x\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::sinhox::sinhox_d (real(dp), intent(in) x)\fC [private]\fP"

.PP
Evaluate the symmetric real function sinh(x)/x\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP double precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
r sinh(x)/x 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 345 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
