.TH "pmat2::wrtb" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::wrtb
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBWRTB\fP (m1, m2, mah1, mah2, a)"
.br
.RI "Convenient routine for interactively writing out the real contents of a band matrix\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file pmat2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat2::wrtb::WRTB (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m1,\-mah1:mah2), intent(in) a)\fC [private]\fP"

.PP
Convenient routine for interactively writing out the real contents of a band matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm1\fP number of rows of full matrix 
.br
\fIm2\fP number of columns of full matrix 
.br
\fImah1\fP number of sub-diagonals 
.br
\fImah2\fP number of super-diagonals 
.br
\fIa\fP contents of single precision real band matrix\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1999 
.RE
.PP

.PP
Definition at line 1341 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
