.TH "pmat::udlmm" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat::udlmm
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBcudlmm\fP (a, b, ipiv)"
.br
.RI "Use l-u factors in A to back-substitute for several rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. "
.ti -1c
.RI "subroutine \fBcudlmv\fP (a, b, ipiv)"
.br
.RI "Use l-u factors in A to back-substitute for 1 rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. "
.ti -1c
.RI "subroutine \fBdudlmm\fP (a, b, ipiv)"
.br
.RI "Use l-u factors in A to back-substitute for several rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. "
.ti -1c
.RI "subroutine \fBdudlmv\fP (a, b, ipiv)"
.br
.RI "Use l-u factors in A to back-substitute for 1 rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. "
.ti -1c
.RI "subroutine \fBsudlmm\fP (a, b, ipiv)"
.br
.RI "Use l-u factors in A to back-substitute for several rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. "
.ti -1c
.RI "subroutine \fBsudlmv\fP (a, b, ipiv)"
.br
.RI "Use l-u factors in A to back-substitute for 1 rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file pmat\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat::udlmm::cudlmm (complex(dpc), dimension(:,:), intent(in) a, complex(dpc), dimension(:,:), intent(inout) b, integer(spi), dimension(:), intent(in) ipiv)\fC [private]\fP"

.PP
Use l-u factors in A to back-substitute for several rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP square matrix to be factorized 
.br
\fIb\fP rt-hand-sides vectors on input, corresponding solutions on return 
.br
\fIipiv\fP vector encoding the pivoting sequence 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 798 of file pmat\&.f90\&.
.SS "subroutine pmat::udlmm::cudlmv (complex(dpc), dimension(:,:), intent(in) a, complex(dpc), dimension(:), intent(inout) b, integer(spi), dimension(:), intent(in) ipiv)\fC [private]\fP"

.PP
Use l-u factors in A to back-substitute for 1 rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP square matrix to be factorized 
.br
\fIb\fP right-hand side vector on input, corresponding solution on return 
.br
\fIipiv\fP array encoding the pivoting sequence 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 893 of file pmat\&.f90\&.
.SS "subroutine pmat::udlmm::dudlmm (real(dp), dimension(:,:), intent(in) a, real(dp), dimension(:,:), intent(inout) b, integer(spi), dimension(:), intent(in) ipiv)\fC [private]\fP"

.PP
Use l-u factors in A to back-substitute for several rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP square matrix to be factorized 
.br
\fIb\fP rt-hand-sides vectors on input, corresponding solutions on return 
.br
\fIipiv\fP vector encoding the pivoting sequence 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 764 of file pmat\&.f90\&.
.SS "subroutine pmat::udlmm::dudlmv (real(dp), dimension(:,:), intent(in) a, real(dp), dimension(:), intent(inout) b, integer(spi), dimension(:), intent(in) ipiv)\fC [private]\fP"

.PP
Use l-u factors in A to back-substitute for 1 rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP square matrix to be factorized 
.br
\fIb\fP right-hand side vector on input, corresponding solution on return 
.br
\fIipiv\fP array encoding the pivoting sequence 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 862 of file pmat\&.f90\&.
.SS "subroutine pmat::udlmm::sudlmm (real(sp), dimension(:,:), intent(in) a, real(sp), dimension(:,:), intent(inout) b, integer(spi), dimension(:), intent(in) ipiv)\fC [private]\fP"

.PP
Use l-u factors in A to back-substitute for several rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP L-D-U factorization of linear system matrux 
.br
\fIb\fP rt-hand-sides vectors on input, corresponding solutions on return 
.br
\fIipiv\fP vector encoding the pivoting sequence 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 730 of file pmat\&.f90\&.
.SS "subroutine pmat::udlmm::sudlmv (real(sp), dimension(:,:), intent(in) a, real(sp), dimension(:), intent(inout) b, integer(spi), dimension(:), intent(in) ipiv)\fC [private]\fP"

.PP
Use l-u factors in A to back-substitute for 1 rhs in B, using ipiv to define the pivoting permutation used in the l-u decomposition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP L-D-U factorization of linear system matrix 
.br
\fIb\fP right-hand-side vector on input, corresponding solution on return 
.br
\fIipiv\fP vector encoding the pivoting sequence 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 831 of file pmat\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
