.TH "/gpfs/dell1/stmp/George.Gayno/UFS_UTILS/sorc/lsm_routines.fd/noah.fd Directory Reference" 3 "Mon Aug 16 2021" "Version 1.6.0" "noah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/gpfs/dell1/stmp/George.Gayno/UFS_UTILS/sorc/lsm_routines.fd/noah.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBset_soilveg_snippet\&.f90\fP"
.br
.RI "\fIRoutine to set Noah LSM soil and veg params needed for \fBsflx_snippet\fP\&. \fP"
.ti -1c
.RI "file \fBsflx_snippet\&.f90\fP"
.br
.RI "\fISnippets of noah model from sflx\&.F needed for land DA updates\&. \fP"
.in -1c
