.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "noah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbulk_snow_module\&.f90\fP"
.br
.RI "\fIRoutines to make DA updates to a bulk (single layer) snow model such as that in Noah\&. \fP"
.ti -1c
.RI "file \fBset_soilveg_snippet\&.f90\fP"
.br
.RI "\fIRoutine to set Noah LSM soil and veg params needed for \fBsflx_snippet\fP\&. \fP"
.ti -1c
.RI "file \fBsflx_snippet\&.f90\fP"
.br
.RI "\fISnippets of noah model from sflx\&.F needed for land DA updates\&. \fP"
.in -1c
