.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/set_soilveg_snippet.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "noah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/set_soilveg_snippet.f90 \- 
.PP
Routine to set Noah LSM soil and veg params needed for \fBsflx_snippet\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBset_soilveg_snippet_mod\fP"
.br
.RI "\fIBelow was extracted from namelist_soilveg\&.f and set_soilveg\&.f (couldn't get above to compile for doxygen) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Routine to set Noah LSM soil and veg params needed for \fBsflx_snippet\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Clara Draper 
.RE
.PP

.PP
Definition in file \fBset_soilveg_snippet\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for noah from the source code\&.
