.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/lake.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/lake.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBenclosure_cnvx\&.F90\fP"
.br
.RI "\fITest whether a point is inside a spherical convex polygon\&. \fP"
.ti -1c
.RI "file \fBfind_limit\&.F90\fP"
.br
.RI "\fIGeo-reference utilities for a cubed-sphere grid\&. \fP"
.ti -1c
.RI "file \fBlakefrac\&.F90\fP"
.br
.RI "\fICompute lake fraction and depth\&. \fP"
.in -1c
