/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog.fd/netcdf_io.F90
NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog.fd/netcdf_io.F90 -
Write out data in netcdf format.
SYNOPSIS
Functions/Subroutines
subroutine netcdf_err (err, string)
Check NetCDF error code and output the error message.
subroutine read_mask (merge_file, slm, land_frac, lake_frac, im, jm)
Read the land mask file.
subroutine write_mask_netcdf (im, jm, slm, land_frac, ntiles, tile, geolon, geolat)
Write the land mask file.
subroutine write_netcdf (im, jm, slm, land_frac, oro, orf, hprime, ntiles, tile, geolon, geolat, lon, lat)
Write out orography file in netcdf format.
Detailed Description
Write out data in netcdf format.
Author:
Jordan Alpert NOAA/EMC
Definition in file netcdf_io.F90.
Function/Subroutine Documentation
subroutine netcdf_err (integer, intent(in)err, character(len=*), intent(in)string)
Check NetCDF error code and output the error message.
Parameters:
err NetCDF error code
string The NetCDF error message
Author:
Jordan Alpert NOAA/EMC
Definition at line 218 of file netcdf_io.F90.
Referenced by __mtnlm7_oclsm.f__(), gsl_oro_data_lg_scale::calc_gsl_oro_data_lg_scale(), gsl_oro_data_sm_scale::calc_gsl_oro_data_sm_scale(), read_mask(), tersub(), write_mask_netcdf(), and write_netcdf().
subroutine read_mask (character(len=*), intent(in)merge_file, real, dimension(im,jm), intent(out)slm, real, dimension(im,jm), intent(out)land_frac, real, dimension(im,jm), intent(out)lake_frac, integer, intent(in)im, integer, intent(in)jm)
Read the land mask file.
Parameters:
merge_file path
slm Land-sea mask.
land_frac Land fraction.
lake_frac Lake fraction
im 'i' dimension of a model grid tile.
jm 'j' dimension of a model grid tile.
Author:
George Gayno NOAA/EMC
Definition at line 334 of file netcdf_io.F90.
References lake_frac(), and netcdf_err().
Referenced by tersub().
subroutine write_mask_netcdf (integer, intent(in)im, integer, intent(in)jm, real, dimension(im,jm), intent(in)slm, real, dimension(im,jm), intent(in)land_frac, integer, intent(in)ntiles, integer, intent(in)tile, real, dimension(im,jm), intent(in)geolon, real, dimension(im,jm), intent(in)geolat)
Write the land mask file.
Parameters:
im 'i' dimension of a model grid tile.
jm 'j' dimension of a model grid tile.
slm Land-sea mask.
land_frac Land fraction.
ntiles Number of tiles to output.
tile Tile number to output.
geolon Longitude on the model grid tile.
geolat Latitude on the model grid tile.
Author:
George Gayno NOAA/EMC
Definition at line 243 of file netcdf_io.F90.
References netcdf_err().
Referenced by tersub().
subroutine write_netcdf (integer, intent(in)im, integer, intent(in)jm, real, dimension(im,jm), intent(in)slm, real, dimension(im,jm), intent(in)land_frac, real, dimension(im,jm), intent(in)oro, real, dimension(im,jm), intent(in)orf, real, dimension(im,jm,14), intent(in)hprime, integer, intent(in)ntiles, integer, intent(in)tile, real, dimension(im,jm), intent(in)geolon, real, dimension(im,jm), intent(in)geolat, real, dimension(im), intent(in)lon, real, dimension(jm), intent(in)lat)
Write out orography file in netcdf format.
Parameters:
im 'i' dimension of a model grid tile.
jm 'j' dimension of a model grid tile.
slm Land-sea mask.
land_frac Land fraction.
oro Orography
orf Filtered orography. Currently the same as 'oro'.
hprime The gravity wave drag fields on the model grid tile.
ntiles Number of tiles to output.
tile Tile number to output.
geolon Longitude on the model grid tile.
geolat Latitude on the model grid tile.
lon Longitude of the first row of the model grid tile.
lat Latitude of the first column of the model grid tile.
Author:
Jordan Alpert NOAA/EMC GFDL Programmer
Definition at line 21 of file netcdf_io.F90.
References netcdf_err().
Referenced by tersub().
Author
Generated automatically by Doxygen for orog_mask_tools from the source code.