.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog_gsl.fd/gsl_oro_data.f90" 3 "Tue Jan 17 2023" "Version 1.9.0" "orog_mask_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/orog_mask_tools.fd/orog_gsl.fd/gsl_oro_data.f90 \- Create orographic (oro_data) files for use by GSL drag suite\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBgsl_oro_data\fP"
.br
.RI "Brief description of program: Creates orographic (oro_data) files needed by the GSL drag suite physics parameterization\&. "
.in -1c
.SH "Detailed Description"
.PP 
Create orographic (oro_data) files for use by GSL drag suite\&. 


.PP
\fBAuthor:\fP
.RS 4
Michael Toy, NOAA/GSL 
.RE
.PP
\fBDate:\fP
.RS 4
2021-03-12
.RE
.PP
Program GSL_ORO_DATA
.PP
This program calls subroutines which calculate the parameters required for the GSL subgrid-scale orographic gravity-wave drag (GWDO) suite on the FV3 grid\&. These parameters are for the small-scale GWD (Tsiringakis et al\&., 2017) and turbulent orographic form drag (TOFD) (Beljaars et al\&., 2004) schemes of the GSL drag suite\&. The output fields are:
.IP "\(bu" 2
stddev standard deviation of subgrid-scale topograpy
.IP "\(bu" 2
convexity convexity (kurtosis) of subgrid-scale topography
.IP "\(bu" 2
ol{1,2,3,4} orographic effective lengths of subgrid-scale topography for 4 orientations: 1-westerly, 2-southerly, 3-southwesterly, 4-northwesterly
.IP "\(bu" 2
oa{1,2,3,4} orographic asymmetries of subgrid-scale topography for 4 orientations: 1-westerly, 2-southerly, 3-southwesterly, 4-northwesterly
.PP
.PP
Note: This program works for both the global FV3GFS cubed sphere, i\&.e\&., for tiles 1 through 6, (and 7 if nested grid) (halo\&.eq\&.-999 for no halo), and for the stand-alone regional lam (tile 7 and halo\&.ne\&.-999) If a halo number is given, this is only to specify the Cxxx_grid\&.halox data used for input\&. The oro_data files are always 'halo0' output\&.
.PP
Based on code by Michael Duda provided by NCAR/MMM 
.PP
Definition in file \fBgsl_oro_data\&.f90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program gsl_oro_data ()"

.PP
Brief description of program: Creates orographic (oro_data) files needed by the GSL drag suite physics parameterization\&. 
.PP
\fBAuthor:\fP
.RS 4
Michaei Toy, NOAA/GSL 
.RE
.PP
\fBReturns:\fP
.RS 4
0 for success, error code otherwise\&. 
.RE
.PP

.PP
Definition at line 36 of file gsl_oro_data\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for orog_mask_tools from the source code\&.
