.TH "/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/cpld_gridgen.fd/gen_fixgrid.F90" 3 "Thu Aug 4 2022" "Version 1.8.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/cpld_gridgen.fd/gen_fixgrid.F90 \- Generate fixed grid files required for coupled model\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBgen_fixgrid\fP"
.br
.RI "Generate fixed grid files required for coupled model using the MOM6 super grid file and ocean mask file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Generate fixed grid files required for coupled model\&. 


.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition in file \fBgen_fixgrid\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "program gen_fixgrid ()"

.PP
Generate fixed grid files required for coupled model using the MOM6 super grid file and ocean mask file\&. It creates a master grid file which is then used to create subsequent files which are required to create the fix and IC files required for the S2S or S2SW application\&.
.PP
This executable created with this source code runs within the shell scrip cpld_gridgen\&.sh in \&.\&./\&.\&./ush, which utilizes both NCO (netCDF Operators) and ESMF command line functions\&. The shell script creates a run-time grid\&.nml from grid\&.nml\&.IN
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP
\fBReturns:\fP
.RS 4
0 for success, error code otherwise\&. 
.RE
.PP

.PP
Definition at line 16 of file gen_fixgrid\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
