.TH "machine" 3 "Version 1.14.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
machine \- Holds machine dependent constants for global_cycle\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBkind_dbl_prec\fP = 8"
.br
.RI "Kind type for 8-byte float point variables\&. "
.ti -1c
.RI "integer, parameter \fBkind_io4\fP = \fBkind_sngl_prec\fP"
.br
.RI "Kind type for 4-byte float point variables\&. "
.ti -1c
.RI "integer, parameter \fBkind_io8\fP = \fBkind_dbl_prec\fP"
.br
.RI "Kind type for 8-byte float point variables\&. "
.ti -1c
.RI "integer, parameter \fBkind_sngl_prec\fP = 4"
.br
.RI "Kind type for 4-byte float point variables\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds machine dependent constants for global_cycle\&. 


.PP
\fBAuthor\fP
.RS 4
Mark Iredell NOAA/EMC 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "integer, parameter machine::kind_dbl_prec = 8"

.PP
Kind type for 8-byte float point variables\&. 
.PP
Definition at line \fB15\fP of file \fBmachine\&.f90\fP\&.
.SS "integer, parameter machine::kind_io4 = \fBkind_sngl_prec\fP"

.PP
Kind type for 4-byte float point variables\&. 
.PP
Definition at line \fB13\fP of file \fBmachine\&.f90\fP\&.
.SS "integer, parameter machine::kind_io8 = \fBkind_dbl_prec\fP"

.PP
Kind type for 8-byte float point variables\&. 
.PP
Definition at line \fB17\fP of file \fBmachine\&.f90\fP\&.
.SS "integer, parameter machine::kind_sngl_prec = 4"

.PP
Kind type for 4-byte float point variables\&. 
.PP
Definition at line \fB11\fP of file \fBmachine\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
