/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/emcsfc_snow2mdl.fd/grib_utils.F90
NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/emcsfc_snow2mdl.fd/grib_utils.F90 -
Determine whether file is grib or not.
SYNOPSIS
Functions/Subroutines
subroutine gdt_to_gds (igdtnum, igdstmpl, igdtlen, kgds, ni, nj, res)
Convert from the grib2 grid description template array used by the ncep grib2 library, to the grib1 grid description section array used by ncep ipolates library.
subroutine grib2_check (kgds, igdstmplen)
Determine length of grib2 gds template array, which is a function of the map projection.
subroutine grib2_free (gfld)
Deallocate the grib2 gribfield pointers.
subroutine grib2_null (gfld)
Nullify the grib2 gribfield pointers.
subroutine grib_check (file_name, isgrib)
Determine whether file is grib or not.
subroutine init_grib2 (century, year, month, day, hour, kgds, lat11, latlast, lon11, lonlast, listsec0, listsec1, igds, ipdstmpl, ipdsnum, igdstmpl, igdstmplen, idefnum, ideflist, ngrdpts)
Initialize grib2 arrays required by the ncep g2 library according to grib1 gds information.
subroutine skgb2 (LUGB, ISEEK, MSEEK, LSKIP, LGRIB, I1)
Determine whether file is grib or not.
Detailed Description
Determine whether file is grib or not.
Author:
gayno org: w/np2
Date:
2007-nov-28
Definition in file grib_utils.F90.
Function/Subroutine Documentation
subroutine gdt_to_gds (integer, intent(in)igdtnum, integer, dimension(igdtlen), intent(in)igdstmpl, integer, intent(in)igdtlen, integer, dimension(200), intent(out)kgds, integer, intent(out)ni, integer, intent(out)nj, real, intent(out)res)
Convert from the grib2 grid description template array used by the ncep grib2 library, to the grib1 grid description section array used by ncep ipolates library.
Parameters:
igdtnum grib2 grid desc template number
igdstmpl grib2 grid desc template array
igdtlen grib2 grid desc template array size
kgds grib1 grid description section array used by ncep ipolates library.
ni i grid dimensions
nj j grid dimensions
res grid resolution in km
condition codes: 50 - unrecognized model grid type; fatal
Author:
George Gayno org: w/np2
Date:
2014-Sep-26
Definition at line 139 of file grib_utils.F90.
Referenced by model_grid::read_mdl_grid_info(), snowdat::readafwa(), snowdat::readautosnow(), and snowdat::readnesdis().
subroutine grib2_check (integer, dimension(200), intent(in)kgds, integer, intent(out)igdstmplen)
Determine length of grib2 gds template array, which is a function of the map projection.
Note:
call this routine before init_grib2.
Parameters:
kgds grib1 gds array
igdstmplen length of gds template array.
condition codes: 47 - unrecognized grid type; fatal
Author:
George Gayno org: w/np2
Date:
2014-Sep-28
Definition at line 350 of file grib_utils.F90.
Referenced by snow2mdl::write_grib2().
subroutine grib2_free (type(gribfield), intent(inout)gfld)
Deallocate the grib2 gribfield pointers.
Parameters:
gfld a gribfield data structure
Author:
George Gayno org: w/np2
Date:
2014-Sep-28
Definition at line 635 of file grib_utils.F90.
Referenced by snowdat::nh_climo_check(), model_grid::read_mdl_grid_info(), snowdat::readautosnow(), and snowdat::readnesdis().
subroutine grib2_null (type(gribfield), intent(inout)gfld)
Nullify the grib2 gribfield pointers.
Parameters:
gfld a gribfield data structure
Author:
George Gayno org: w/np2
Date:
2014-Sep-28
Definition at line 610 of file grib_utils.F90.
Referenced by snowdat::nh_climo_check(), model_grid::read_mdl_grid_info(), snowdat::readafwa(), snowdat::readautosnow(), and snowdat::readnesdis().
subroutine grib_check (character*(*), intent(in)file_name, integer, intent(out)isgrib)
Determine whether file is grib or not. program history log:
2007-nov-28 gayno - initial version
2011-apr-26 gayno - replace my simple-minded logic with call to w3lib routin skgb.
2014-feb-07 gayno - determine whether file is grib1 or grib2.
Parameters:
file_name - file to be checked
isgrib - '1' or '2' if grib1/2 file '0' if not grib
input files:
file to be checked, fort.11
condition codes: all fatal
bad file open, fort.11
Definition at line 23 of file grib_utils.F90.
References skgb2().
Referenced by model_grid::read_mdl_grid_info(), snowdat::readafwa(), and snowdat::readnesdis().
subroutine init_grib2 (integer, intent(in)century, integer, intent(in)year, integer, intent(in)month, integer, intent(in)day, integer, intent(in)hour, integer, dimension(200), intent(in)kgds, real, intent(in)lat11, real, intent(in)latlast, real, intent(in)lon11, real, intent(in)lonlast, integer, dimension(2), intent(out)listsec0, integer, dimension(13), intent(out)listsec1, integer, dimension(5), intent(out)igds, integer, dimension(15), intent(out)ipdstmpl, integer, intent(out)ipdsnum, integer, dimension(igdstmplen), intent(out)igdstmpl, integer, intent(in)igdstmplen, integer, intent(out)idefnum, integer, intent(out)ideflist, integer, intent(out)ngrdpts)
Initialize grib2 arrays required by the ncep g2 library according to grib1 gds information. The grib1 gds is held in the kgds array, which is used by the ncep ipolates and w3nco (grib 1) libraries.
Call routine grib2_check first to determine igdstmplen.
Parameters:
century current date/time info
year current date/time info
month current date/time info
day current date/time info
hour current date/time info
kgds grib1 gds information
igdstmplen length of grib2 gdt template.
lat11 lat of first grid point
lon11 lon of first grid point
latlast lat of last grid point
lonlast lon of last grid point
igds grib2 section 3 information.
listsec0 grib2 section 0 information.
listsec1 grib2 section 1 information.
ipdsnum grib2 pds template number
ipdstmpl grib2 pds template array
igdstmpl grib2 gds template array
idefnum information for non-reg grid, grid points in each row.
ideflist information for non-reg grid, grid points in each row.
ngrdpts number of model grid points.
Author:
George Gayno org: w/np2
Date:
2014-Sep-28
Definition at line 397 of file grib_utils.F90.
Referenced by snow2mdl::write_grib2().
subroutine skgb2 (integer, intent(in)LUGB, integer, intent(in)ISEEK, integer, intent(in)MSEEK, integer, intent(out)LSKIP, integer, intent(out)LGRIB, integer, intent(out)I1)
Determine whether file is grib or not. Based on w3nco library routine skgb.
Parameters:
lugb file unit number
iseek number of bits to skip before search.
mseek max number of bytes to search.
lskip number of bytes to skip before message
lgrib number of bytes in message. '0' if not grib.
i1 '1' or '2' if grib1/2 file. '0' if not grib.
input file:
file to be checked, unit=lugb
Author:
George Gayno org: w/np2
Date:
2014-Feb-07
Definition at line 75 of file grib_utils.F90.
Referenced by grib_check().
Author
Generated automatically by Doxygen for emcsfc_snow2mdl from the source code.