.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/emcsfc_snow2mdl.fd/snow2mdl.F90" 3 "Wed Mar 13 2024" "Version 1.13.0" "emcsfc_snow2mdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/emcsfc_snow2mdl.fd/snow2mdl.F90 \- 
.PP
Interpolate snow data to model grid and grib the result\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBsnow2mdl\fP"
.br
.RI "\fIInterpolate snow data to model grid and grib the result\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interpolate snow data to model grid and grib the result\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno org: w/np2 
.RE
.PP
\fBDate:\fP
.RS 4
2005-Dec-16 
.RE
.PP

.PP
Definition in file \fBsnow2mdl\&.F90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for emcsfc_snow2mdl from the source code\&.
