angles
NAME
angles -
SYNOPSIS
Public Member Functions
subroutine find_ang
Find the rotation angle on center (Ct) grid points.
subroutine find_angq
Find the rotation angle on corner grid (Bu) points using the full MOM6 supergrid.
real(dbl_kind) function modulo_around_point (x, xc, Lx)
Return the modulo value of x in an interval [xc-(Lx/2) xc+(Lx/2)] If Lx<=0, then it returns x without applying modulo arithmetic.
Detailed Description
Definition at line 10 of file angles.F90.
Member Function/Subroutine Documentation
subroutine angles::find_ang ()
Find the rotation angle on center (Ct) grid points.
Author:
Denise.Worthen@noaa.gov
Definition at line 131 of file angles.F90.
References modulo_around_point().
Referenced by gen_fixgrid().
subroutine angles::find_angq ()
Find the rotation angle on corner grid (Bu) points using the full MOM6 supergrid.
Author:
Denise.Worthen@noaa.gov
Definition at line 25 of file angles.F90.
References modulo_around_point().
Referenced by gen_fixgrid().
real(dbl_kind) function angles::modulo_around_point (real(dbl_kind), intent(in)x, real(dbl_kind), intent(in)xc, real(dbl_kind), intent(in)Lx)
Return the modulo value of x in an interval [xc-(Lx/2) xc+(Lx/2)] If Lx<=0, then it returns x without applying modulo arithmetic. From src/initialization/MOM_shared_initialization.F90:
Parameters:
x Value to which to apply modulo arithmetic
xc Center of modulo range
Lx Modulo range width
Returns:
x_mod Value x shifted by an integer multiple of Lx to be close to xc
Definition at line 188 of file angles.F90.
Referenced by find_ang(), and find_angq().
Author
Generated automatically by Doxygen for cpld_gridgen from the source code.