debugprint
NAME
debugprint -
SYNOPSIS
Public Member Functions
subroutine, public checkpoint
Print values at specified point.
subroutine, public checkseam
Print values across the tripole seam.
subroutine, public checkxlatlon
Print values near the poles and along the domain edges.
Detailed Description
Definition at line 8 of file debugprint.F90.
Member Function/Subroutine Documentation
subroutine, public debugprint::checkpoint ()
Print values at specified point.
Author:
Denise.Worthen@noaa.gov
Definition at line 170 of file debugprint.F90.
Referenced by gen_fixgrid().
subroutine, public debugprint::checkseam ()
Print values across the tripole seam.
Author:
Denise.Worthen@noaa.gov
Definition at line 27 of file debugprint.F90.
Referenced by gen_fixgrid().
subroutine, public debugprint::checkxlatlon ()
Print values near the poles and along the domain edges.
Author:
Denise.Worthen@noaa.gov
Definition at line 108 of file debugprint.F90.
Referenced by gen_fixgrid().
Author
Generated automatically by Doxygen for cpld_gridgen from the source code.