/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/gen_fixgrid.F90
NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/gen_fixgrid.F90 -
Generate fixed grid files required for coupled model.
SYNOPSIS
Functions/Subroutines
program gen_fixgrid
Generate fixed grid files required for coupled model using the MOM6 super grid file and ocean mask file.
Detailed Description
Generate fixed grid files required for coupled model.
Author:
Denise.Worthen@noaa.gov
Definition in file gen_fixgrid.F90.
Function/Subroutine Documentation
program gen_fixgrid ()
Generate fixed grid files required for coupled model using the MOM6 super grid file and ocean mask file. It creates a main grid file which is then used to create subsequent files which are required to create the fix and IC files required for the S2S or S2SW application.
This executable created with this source code runs within the shell scrip cpld_gridgen.sh in ../../ush, which utilizes both NCO (netCDF Operators) and ESMF command line functions. The shell script creates a run-time grid.nml from grid.nml.IN
Author:
Denise.Worthen@noaa.gov
Returns:
0 for success, error code otherwise.
Definition at line 16 of file gen_fixgrid.F90.
References topoedits::add_topoedits(), grdvars::allocate_all(), topoedits::apply_topoedits(), debugprint::checkpoint(), debugprint::checkseam(), debugprint::checkxlatlon(), vertices::fill_bottom(), vertices::fill_top(), vertices::fill_vertices(), angles::find_ang(), angles::find_angq(), mapped_mask::make_frac_land(), postwgts::make_postwgts(), inputnml::read_inputnml(), cicegrid::write_cicegrid(), scripgrid::write_scripgrid(), and tripolegrid::write_tripolegrid().
Author
Generated automatically by Doxygen for cpld_gridgen from the source code.