.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/gengrid_kinds.F90" 3 "Wed Mar 13 2024" "Version 1.13.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/gengrid_kinds.F90 \- 
.PP
Define type-kind variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBgengrid_kinds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define type-kind variables\&. 


.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov
.RE
.PP
This module defines the type-kind variables 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition in file \fBgengrid_kinds\&.F90\fP\&.
.SH "Data Type Documentation"
.PP 
.SH "module gengrid_kinds"
.PP 
Definition at line 8 of file gengrid_kinds\&.F90\&.
.PP
\fBData Fields:\fP
.RS 4
integer, parameter \fIcl\fP a long length character string 
.br
.PP
integer, parameter \fIcm\fP a medium length character string 
.br
.PP
integer, parameter \fIcs\fP a short length character string 
.br
.PP
integer, parameter \fIdbl_kind\fP 8 byte real 
.br
.PP
integer, parameter \fIint8_kind\fP 8 byte integer 
.br
.PP
integer, parameter \fIint_kind\fP 4 byte integer 
.br
.PP
integer, parameter \fIreal_kind\fP 4 byte real 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
