.TH "md__scratch1_NCEPDEV_da_George.Gayno_ufs_utils.git_UFS_UTILS.upstream_sorc_cpld_gridgen.fd_docs_README" 3 "Wed Mar 13 2024" "Version 1.13.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__scratch1_NCEPDEV_da_George.Gayno_ufs_utils.git_UFS_UTILS.upstream_sorc_cpld_gridgen.fd_docs_README \- README 
This program creates the files required for the Fix and IC files for the coupled model\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
