.TH "postwgts" 3 "Thu Feb 15 2024" "Version 1.12.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
postwgts \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBmake_postwgts\fP"
.br
.RI "\fICreate the ESMF weights files to remap velocity points from their native stagger location to the center (Ct) location\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file postwgts\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine postwgts::make_postwgts ()"

.PP
Create the ESMF weights files to remap velocity points from their native stagger location to the center (Ct) location\&. Create the ESMF weights file to remap from the Ct location to a rectilinear grid
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 24 of file postwgts\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
