.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/scripgrid.F90" 3 "Tue Jan 17 2023" "Version 1.9.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/scripgrid.F90 \- Write a SCRIP format file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBscripgrid::write_scripgrid\fP (fname, cstagger, imask)"
.br
.RI "Write a SCRIP grid file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Write a SCRIP format file\&. 


.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov
.RE
.PP
This module writes a SCRIP format file 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition in file \fBscripgrid\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public scripgrid::write_scripgrid (character(len=*), intent(in) fname, character(len=*), intent(in) cstagger, integer(int_kind), dimension(:,:), intent(in), optional imask)"

.PP
Write a SCRIP grid file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfname\fP the file name to write 
.br
\fIcstagger\fP the name of the stagger location 
.br
\fIimask\fP (optional) the land mask values
.RE
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 35 of file scripgrid\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
