vartypedefs
NAME
vartypedefs -
SYNOPSIS
Data Types
type vardefs
Public Member Functions
subroutine cicevars_typedefine
Define the variables written to the CICE grid file.
subroutine fixvars_typedefine
Define the variables written to the tripole grid file.
subroutine scripvars_typedefine
Define the variables written to any SCRIP grid file.
Data Fields
type(vardefs), dimension(maxvars) cicevars
Attribute definitions for the variables written to the CICE grid file.
type(vardefs), dimension(maxvars) fixvars
Attribute definitions for the variables written to the main tripole file.
integer, parameter maxvars = 20
The maximum number of variables written to a file.
type(vardefs), dimension(maxvars) scripvars
Attribute definitions for the variables written to any SCRIP file.
Detailed Description
Definition at line 8 of file vartypedefs.F90.
Data Type Documentation
type vartypedefs::vardefs
Definition at line 16 of file vartypedefs.F90.
Data Fields:
character(len=cm) long_name A variable's long name.
character(len=cm) unit_name A variable's unit.
character(len=cm) var_name A variable name.
character(len=2) var_type A variable's type.
character(len=cm) vertices A variable's vertices.
Member Function/Subroutine Documentation
subroutine vartypedefs::cicevars_typedefine ()
Define the variables written to the CICE grid file.
Author:
Denise.Worthen@noaa.gov
Definition at line 136 of file vartypedefs.F90.
Referenced by cicegrid::write_cicegrid().
subroutine vartypedefs::fixvars_typedefine ()
Define the variables written to the tripole grid file.
Author:
Denise.Worthen@noaa.gov
Definition at line 34 of file vartypedefs.F90.
Referenced by tripolegrid::write_tripolegrid().
subroutine vartypedefs::scripvars_typedefine ()
Define the variables written to any SCRIP grid file.
Author:
Denise.Worthen@noaa.gov
Definition at line 181 of file vartypedefs.F90.
Referenced by scripgrid::write_scripgrid().
Field Documentation
type(vardefs), dimension(maxvars) vartypedefs::cicevars
Attribute definitions for the variables written to the CICE grid file.
Definition at line 25 of file vartypedefs.F90.
type(vardefs), dimension(maxvars) vartypedefs::fixvars
Attribute definitions for the variables written to the main tripole file.
Definition at line 24 of file vartypedefs.F90.
integer, parameter vartypedefs::maxvars = 20
The maximum number of variables written to a file.
Definition at line 14 of file vartypedefs.F90.
type(vardefs), dimension(maxvars) vartypedefs::scripvars
Attribute definitions for the variables written to any SCRIP file.
Definition at line 26 of file vartypedefs.F90.
Author
Generated automatically by Doxygen for cpld_gridgen from the source code.