vertices
NAME
vertices -
SYNOPSIS
Public Member Functions
subroutine fill_bottom (iVert, jVert, lat, lon, latvert, lonvert, dlat)
Fill the vertices for a stagger location along the bottom j-row.
subroutine fill_top (iVert, jVert, lat, lon, latvert, lonvert, xlat, xlon)
Fill the vertices for a stagger location along the top j-row.
subroutine fill_vertices (jbeg, jend, iVert, jVert, lat, lon, latvert, lonvert)
Fill the vertices for any stagger location between bounding j-rows.
Detailed Description
Definition at line 13 of file vertices.F90.
Member Function/Subroutine Documentation
subroutine vertices::fill_bottom (integer, dimension(nv), intent(in)iVert, integer, dimension(nv), intent(in)jVert, real(dbl_kind), dimension(ni,nj), intent(in)lat, real(dbl_kind), dimension(ni,nj), intent(in)lon, real(dbl_kind), dimension(ni,nj,nv), intent(out)latvert, real(dbl_kind), dimension(ni,nj,nv), intent(out)lonvert, real(dbl_kind), dimension(ni), intent(in)dlat)
Fill the vertices for a stagger location along the bottom j-row.
Parameters:
iVert the i-offset applied to the i-index of a stagger grid
jVert the j-offset applied to the j-index of a stagger grid
lat the latitudes of the stagger grid which define each vertex
lon the longitudes of the stagger grid which define each vertex
dlat the approximate latitude along the bottom-most row
latvert the latitudes of each vertex
lonvert the longitudes of each vertex
Author:
Denise.Worthen@noaa.gov
Definition at line 68 of file vertices.F90.
Referenced by gen_fixgrid().
subroutine vertices::fill_top (integer, dimension(nv), intent(in)iVert, integer, dimension(nv), intent(in)jVert, real(dbl_kind), dimension(ni,nj), intent(in)lat, real(dbl_kind), dimension(ni,nj), intent(in)lon, real(dbl_kind), dimension(ni,nj,nv), intent(out)latvert, real(dbl_kind), dimension(ni,nj,nv), intent(out)lonvert, real(dbl_kind), dimension(ni), intent(in)xlat, real(dbl_kind), dimension(ni), intent(in)xlon)
Fill the vertices for a stagger location along the top j-row.
Parameters:
iVert the i-offset applied to the i-index of a stagger grid
jVert the j-offset applied to the j-index of a stagger grid
lat the latitudes of the stagger grid which define each vertex
lon the longitudes of the stagger grid which define each vertex
xlat the latitude across the tripole seam
xlon the longitude across the tripole seam
latvert the latitudes of each vertex
lonvert the longitudes of each vertex
Author:
Denise.Worthen@noaa.gov
Definition at line 114 of file vertices.F90.
Referenced by gen_fixgrid().
subroutine vertices::fill_vertices (integer, intent(in)jbeg, integer, intent(in)jend, integer, dimension(nv), intent(in)iVert, integer, dimension(nv), intent(in)jVert, real(dbl_kind), dimension(ni,nj), intent(in)lat, real(dbl_kind), dimension(ni,nj), intent(in)lon, real(dbl_kind), dimension(ni,nj,nv), intent(out)latvert, real(dbl_kind), dimension(ni,nj,nv), intent(out)lonvert)
Fill the vertices for any stagger location between bounding j-rows.
Parameters:
jbeg the beginning row
jend the ending row
iVert the i-offset applied to the i-index of a stagger grid
jVert the j-offset applied to the j-index of a stagger grid
lat the latitudes of the stagger grid which define each vertex
lon the longitudes of the stagger grid which define each vertex
latvert the latitudes of each vertex
lonvert the longitudes of each vertex
Author:
Denise.Worthen@noaa.gov
Definition at line 33 of file vertices.F90.
Referenced by gen_fixgrid().
Author
Generated automatically by Doxygen for cpld_gridgen from the source code.