.TH "atmosphere_target_data" 3 "Thu Aug 4 2022" "Version 1.8.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atmosphere_target_data \- Module to hold variables and ESMF fields associated with the target grid atmospheric data\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBcleanup_atmosphere_target_data\fP"
.br
.RI "Free up memory for fields and variables in this module\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(esmf_field), public \fBdelp_target_grid\fP"
.br
.RI "Pressure thickness\&. "
.ti -1c
.RI "type(esmf_field), public \fBdzdt_target_grid\fP"
.br
.RI "Vertical velocity\&. "
.ti -1c
.RI "integer, public \fBlev_target\fP"
.br
.RI "Number of vertical levels\&. "
.ti -1c
.RI "integer, public \fBlevp1_target\fP"
.br
.RI "Number of vertical levels plus 1\&. "
.ti -1c
.RI "integer, public \fBnvcoord_target\fP"
.br
.RI "Number of vertical coordinate variables\&. "
.ti -1c
.RI "type(esmf_field), public \fBps_target_grid\fP"
.br
.RI "Surface pressure\&. "
.ti -1c
.RI "type(esmf_field), public \fBqnifa_climo_target_grid\fP"
.br
.RI "Number concentration of ice friendly aerosols\&. "
.ti -1c
.RI "type(esmf_field), public \fBqnwfa_climo_target_grid\fP"
.br
.RI "Number concentration of water friendly aerosols\&. "
.ti -1c
.RI "type(esmf_field), public \fBtemp_target_grid\fP"
.br
.RI "Temperautre\&. "
.ti -1c
.RI "type(esmf_field), dimension(:), allocatable, public \fBtracers_target_grid\fP"
.br
.RI "Tracers\&. "
.ti -1c
.RI "type(esmf_field), public \fBu_s_target_grid\fP"
.br
.RI "U-wind, 'south' edge of grid cell\&. "
.ti -1c
.RI "type(esmf_field), public \fBu_w_target_grid\fP"
.br
.RI "U-wind, 'west' edge of grid cell\&. "
.ti -1c
.RI "type(esmf_field), public \fBv_s_target_grid\fP"
.br
.RI "V-wind, 'south' edge of grid cell\&. "
.ti -1c
.RI "type(esmf_field), public \fBv_w_target_grid\fP"
.br
.RI "V-wind, 'west' edge of grid cell\&. "
.ti -1c
.RI "real(esmf_kind_r8), dimension(:,:), allocatable, public \fBvcoord_target\fP"
.br
.RI "Vertical coordinate\&. "
.ti -1c
.RI "type(esmf_field), public \fBzh_target_grid\fP"
.br
.RI "3-d height\&. "
.in -1c
.SH "Detailed Description"
.PP 
Module to hold variables and ESMF fields associated with the target grid atmospheric data\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public atmosphere_target_data::cleanup_atmosphere_target_data ()"

.PP
Free up memory for fields and variables in this module\&. 
.PP
\fBAuthor:\fP
.RS 4
George\&.Gayno NOAA/EMC 
.RE
.PP

.PP
Definition at line 46 of file atmosphere_target_data\&.F90\&.
.PP
References delp_target_grid, dzdt_target_grid, program_setup::num_tracers, ps_target_grid, qnifa_climo_target_grid, qnwfa_climo_target_grid, temp_target_grid, tracers_target_grid, u_s_target_grid, u_w_target_grid, v_s_target_grid, v_w_target_grid, vcoord_target, and zh_target_grid\&.
.PP
Referenced by atmosphere::cleanup_all_target_atm_data()\&.
.SH "Variable Documentation"
.PP 
.SS "type(esmf_field), public atmosphere_target_data::delp_target_grid"

.PP
Pressure thickness\&. 
.PP
Definition at line 23 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::create_atm_esmf_fields(), atmosphere::newpr1(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::dzdt_target_grid"

.PP
Vertical velocity\&. 
.PP
Definition at line 24 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::create_atm_esmf_fields(), atmosphere::VINTG(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "integer, public atmosphere_target_data::lev_target"

.PP
Number of vertical levels\&. 
.PP
Definition at line 17 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by atmosphere::create_atm_esmf_fields(), atmosphere::horiz_interp_thomp_mp_climo(), atmosphere::newpr1(), atmosphere::read_vcoord_info(), atmosphere::VINTG(), atmosphere::VINTG_THOMP_MP_CLIMO(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "integer, public atmosphere_target_data::levp1_target"

.PP
Number of vertical levels plus 1\&. 
.PP
Definition at line 18 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::newpr1(), atmosphere::read_vcoord_info(), write_data::write_fv3_atm_bndy_data_netcdf(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_atm_header_netcdf()\&.
.SS "integer, public atmosphere_target_data::nvcoord_target"

.PP
Number of vertical coordinate variables\&. 
.PP
Definition at line 19 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by atmosphere::read_vcoord_info(), and write_data::write_fv3_atm_header_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::ps_target_grid"

.PP
Surface pressure\&. 
.PP
Definition at line 25 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::newpr1(), atmosphere::newps(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::qnifa_climo_target_grid"

.PP
Number concentration of ice friendly aerosols\&. 
.PP
Definition at line 33 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::horiz_interp_thomp_mp_climo(), atmosphere::VINTG_THOMP_MP_CLIMO(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::qnwfa_climo_target_grid"

.PP
Number concentration of water friendly aerosols\&. 
.PP
Definition at line 35 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::horiz_interp_thomp_mp_climo(), atmosphere::VINTG_THOMP_MP_CLIMO(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::temp_target_grid"

.PP
Temperautre\&. 
.PP
Definition at line 26 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::VINTG(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), dimension(:), allocatable, public atmosphere_target_data::tracers_target_grid"

.PP
Tracers\&. 
.PP
Definition at line 27 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::VINTG(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::u_s_target_grid"

.PP
U-wind, 'south' edge of grid cell\&. 
.PP
Definition at line 28 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::u_w_target_grid"

.PP
U-wind, 'west' edge of grid cell\&. 
.PP
Definition at line 30 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::v_s_target_grid"

.PP
V-wind, 'south' edge of grid cell\&. 
.PP
Definition at line 29 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::v_w_target_grid"

.PP
V-wind, 'west' edge of grid cell\&. 
.PP
Definition at line 31 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SS "real(esmf_kind_r8), dimension(:,:), allocatable, public atmosphere_target_data::vcoord_target"

.PP
Vertical coordinate\&. 
.PP
Definition at line 21 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::newpr1(), atmosphere::read_vcoord_info(), and write_data::write_fv3_atm_header_netcdf()\&.
.SS "type(esmf_field), public atmosphere_target_data::zh_target_grid"

.PP
3-d height\&. 
.PP
Definition at line 32 of file atmosphere_target_data\&.F90\&.
.PP
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
