atmosphere_target_data
NAME
atmosphere_target_data - Module to hold variables and ESMF fields associated with the target grid atmospheric data.
SYNOPSIS
Functions/Subroutines
subroutine, public cleanup_atmosphere_target_data
Free up memory for fields and variables in this module.
Variables
type(esmf_field), public delp_target_grid
Pressure thickness.
type(esmf_field), public dzdt_target_grid
Vertical velocity.
integer, public lev_target
Number of vertical levels.
integer, public levp1_target
Number of vertical levels plus 1.
integer, public nvcoord_target
Number of vertical coordinate variables.
type(esmf_field), public ps_target_grid
Surface pressure.
type(esmf_field), public qnifa_climo_target_grid
Number concentration of ice friendly aerosols.
type(esmf_field), public qnwfa_climo_target_grid
Number concentration of water friendly aerosols.
type(esmf_field), public temp_target_grid
Temperautre.
type(esmf_field), dimension(:), allocatable, public tracers_target_grid
Tracers.
type(esmf_field), public u_s_target_grid
U-wind, 'south' edge of grid cell.
type(esmf_field), public u_w_target_grid
U-wind, 'west' edge of grid cell.
type(esmf_field), public v_s_target_grid
V-wind, 'south' edge of grid cell.
type(esmf_field), public v_w_target_grid
V-wind, 'west' edge of grid cell.
real(esmf_kind_r8), dimension(:,:), allocatable, public vcoord_target
Vertical coordinate.
type(esmf_field), public zh_target_grid
3-d height.
Detailed Description
Module to hold variables and ESMF fields associated with the target grid atmospheric data.
Author:
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine, public atmosphere_target_data::cleanup_atmosphere_target_data ()
Free up memory for fields and variables in this module.
Author:
George.Gayno NOAA/EMC
Definition at line 46 of file atmosphere_target_data.F90.
References delp_target_grid, dzdt_target_grid, program_setup::num_tracers, ps_target_grid, qnifa_climo_target_grid, qnwfa_climo_target_grid, temp_target_grid, tracers_target_grid, u_s_target_grid, u_w_target_grid, v_s_target_grid, v_w_target_grid, vcoord_target, and zh_target_grid.
Referenced by atmosphere::cleanup_all_target_atm_data().
Variable Documentation
type(esmf_field), public atmosphere_target_data::delp_target_grid
Pressure thickness.
Definition at line 23 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::create_atm_esmf_fields(), atmosphere::newpr1(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::dzdt_target_grid
Vertical velocity.
Definition at line 24 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::create_atm_esmf_fields(), atmosphere::VINTG(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
integer, public atmosphere_target_data::lev_target
Number of vertical levels.
Definition at line 17 of file atmosphere_target_data.F90.
Referenced by atmosphere::create_atm_esmf_fields(), atmosphere::horiz_interp_thomp_mp_climo(), atmosphere::newpr1(), atmosphere::read_vcoord_info(), atmosphere::VINTG(), atmosphere::VINTG_THOMP_MP_CLIMO(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
integer, public atmosphere_target_data::levp1_target
Number of vertical levels plus 1.
Definition at line 18 of file atmosphere_target_data.F90.
Referenced by atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::newpr1(), atmosphere::read_vcoord_info(), write_data::write_fv3_atm_bndy_data_netcdf(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_atm_header_netcdf().
integer, public atmosphere_target_data::nvcoord_target
Number of vertical coordinate variables.
Definition at line 19 of file atmosphere_target_data.F90.
Referenced by atmosphere::read_vcoord_info(), and write_data::write_fv3_atm_header_netcdf().
type(esmf_field), public atmosphere_target_data::ps_target_grid
Surface pressure.
Definition at line 25 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::newpr1(), atmosphere::newps(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::qnifa_climo_target_grid
Number concentration of ice friendly aerosols.
Definition at line 33 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::horiz_interp_thomp_mp_climo(), atmosphere::VINTG_THOMP_MP_CLIMO(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::qnwfa_climo_target_grid
Number concentration of water friendly aerosols.
Definition at line 35 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::horiz_interp_thomp_mp_climo(), atmosphere::VINTG_THOMP_MP_CLIMO(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::temp_target_grid
Temperautre.
Definition at line 26 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::VINTG(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), dimension(:), allocatable, public atmosphere_target_data::tracers_target_grid
Tracers.
Definition at line 27 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::VINTG(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::u_s_target_grid
U-wind, 'south' edge of grid cell.
Definition at line 28 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::u_w_target_grid
U-wind, 'west' edge of grid cell.
Definition at line 30 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::v_s_target_grid
V-wind, 'south' edge of grid cell.
Definition at line 29 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere_target_data::v_w_target_grid
V-wind, 'west' edge of grid cell.
Definition at line 31 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::convert_winds(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
real(esmf_kind_r8), dimension(:,:), allocatable, public atmosphere_target_data::vcoord_target
Vertical coordinate.
Definition at line 21 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::newpr1(), atmosphere::read_vcoord_info(), and write_data::write_fv3_atm_header_netcdf().
type(esmf_field), public atmosphere_target_data::zh_target_grid
3-d height.
Definition at line 32 of file atmosphere_target_data.F90.
Referenced by cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
Author
Generated automatically by Doxygen for chgres_cube from the source code.