input_data
NAME
input_data - Read atmospheric, surface and nst data on the input grid.
SYNOPSIS
Functions/Subroutines
subroutine calcalpha_rotlatlon (latgrid, longrid, cenlat, cenlon, alpha)
Calculate rotation angle for rotated latlon grids.
subroutine, public check_cnwat (cnwat)
When using GEFS data, some points on the target grid have unreasonable canpy moisture content, so zero out any locations with unrealistic canopy moisture values (>0.5).
subroutine, public check_soilt (soilt, landmask, skint)
Check for and replace certain values in soil temperature.
subroutine, public cleanup_input_atm_data
Free up memory associated with atm data.
subroutine, public cleanup_input_nst_data
Free up memory associated with nst data.
subroutine, public cleanup_input_sfc_data
Free up memory associated with sfc data.
subroutine, public convert_winds
Convert winds from 2-d to 3-d components.
subroutine, public DINT2P (PPIN, XXIN, NPIN, PPOUT, XXOUT, NPOUT, LINLOG, XMSG, IER)
Pressure to presure vertical interpolation for tracers with linear or lnP interpolation.
subroutine gridrot (lov, latin1, latin2, lon, rot)
Compute grid rotation angle for non-latlon grids.
subroutine handle_grib_error (vname, lev, method, value, varnum, iret, var, var8, var3d)
Handle GRIB2 read error based on the user selected method in the varmap file.
subroutine init_atm_esmf_fields
Create atmospheric esmf fields.
subroutine, public init_sfc_esmf_fields
Create surface input grid esmf fields.
recursive subroutine, public quicksort (a, first, last)
Sort an array of values.
subroutine READ_FV3_GRID_DATA_NETCDF (FIELD, TILE_NUM, IMO, JMO, LMO, SFCDATA, SFCDATA_3D)
Read a record from a netcdf file.
subroutine read_grib_soil (vname, vname_file, lugb, pdt_num, dummy3d)
Read soil temperature and soil moisture fields from a GRIB2 file.
subroutine, public read_input_atm_data (localpet)
Read input grid atmospheric data driver.
subroutine read_input_atm_gaussian_nemsio_file (localpet)
Read input grid atmospheric fv3 gaussian nemsio files.
subroutine read_input_atm_gaussian_netcdf_file (localpet)
Read fv3 netcdf gaussian history file.
subroutine read_input_atm_gfs_gaussian_nemsio_file (localpet)
Read input atmospheric data from spectral gfs (global gaussian in nemsio format.
subroutine read_input_atm_gfs_sigio_file (localpet)
Read input atmospheric data from spectral gfs (old sigio format).
subroutine read_input_atm_grib2_file (localpet)
Read input grid atmospheric fv3gfs grib2 files.
subroutine read_input_atm_restart_file (localpet)
Read input grid fv3 atmospheric data 'warm' restart files.
subroutine read_input_atm_tiled_history_file (localpet)
Read input grid fv3 atmospheric tiled history files in netcdf format.
subroutine, public read_input_nst_data (localpet)
Driver to read input grid nst data.
subroutine read_input_nst_nemsio_file (localpet)
Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file.
subroutine read_input_nst_netcdf_file (localpet)
Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history.
subroutine, public read_input_sfc_data (localpet)
Driver to read input grid surface data.
subroutine read_input_sfc_gaussian_nemsio_file (localpet)
Read input grid surface data from an fv3 gaussian nemsio file.
subroutine read_input_sfc_gfs_gaussian_nemsio_file (localpet)
Read input grid surface data from a spectral gfs gaussian nemsio file.
subroutine read_input_sfc_gfs_sfcio_file (localpet)
Read input grid surface data from a spectral gfs gaussian sfcio file.
subroutine read_input_sfc_grib2_file (localpet)
Read input grid surface data from a grib2 file.
subroutine read_input_sfc_netcdf_file (localpet)
Read input grid surface data from tiled 'history' files (netcdf) or gaussian netcdf files.
subroutine read_input_sfc_restart_file (localpet)
Read input grid surface data from fv3 tiled warm 'restart' files.
subroutine read_winds (u, v, localpet, octet_23, rlevs, lugb, pdt_num)
Read winds from a grib2 file.
Variables
type(esmf_field), public c_0_input_grid
Coefficient 1 to calculate d(tz)/d(ts)
type(esmf_field), public c_d_input_grid
Coefficient 2 to calculate d(tz)/d(ts)
type(esmf_field), public canopy_mc_input_grid
canopy moist content
type(esmf_field), public d_conv_input_grid
Thickness of free convection layer.
type(esmf_field) dpres_input_grid
pressure thickness
type(esmf_field), public dt_cool_input_grid
Sub-layer cooling amount.
type(esmf_field), public dzdt_input_grid
vert velocity
type(esmf_field), public f10m_input_grid
log((z0+10)*1/z0)
type(esmf_field), public ffmm_input_grid
log((z0+z1)*1/z0) See sfc_diff.f for details.
integer, parameter icet_default = 265.0
Default value of soil and skin temperature (K) over ice.
type(esmf_field), public ifd_input_grid
Model mode index.
type(esmf_field), public lai_input_grid
leaf area index
type(esmf_field), public landsea_mask_input_grid
land sea mask; 0-water, 1-land, 2-ice
integer, public lev_input
number of atmospheric layers
integer, public levp1_input
number of atmos layer interfaces
integer, public lsoil_input =4
number of soil layers, no longer hardwired to allow for 7 layers of soil for the RUC LSM
type(esmf_field), public max_veg_greenness_input_grid
shdmax
type(esmf_field), public min_veg_greenness_input_grid
shdmin
type(esmf_field), public pres_input_grid
3-d pressure
type(esmf_field), public ps_input_grid
surface pressure
type(esmf_field), public q2m_input_grid
2-m spec hum
type(esmf_field), public qrain_input_grid
Sensible heat flux due to rainfall.
type(esmf_field), public seaice_depth_input_grid
sea ice depth
type(esmf_field), public seaice_fract_input_grid
sea ice fraction
type(esmf_field), public seaice_skin_temp_input_grid
sea ice skin temp
type(esmf_field), public skin_temp_input_grid
skin temp/sst
character(len=50), dimension(:), allocatable, private slevs
The atmospheric levels in the GRIB2 input file.
type(esmf_field), public snow_depth_input_grid
snow dpeth
type(esmf_field), public snow_liq_equiv_input_grid
snow liq equiv depth
type(esmf_field), public soil_temp_input_grid
3-d soil temp
type(esmf_field), public soil_type_input_grid
soil type
type(esmf_field), public soilm_liq_input_grid
3-d liquid soil moisture
type(esmf_field), public soilm_tot_input_grid
3-d total soil moisture
type(esmf_field), public srflag_input_grid
snow/rain flag
type(esmf_field), public t2m_input_grid
2-m temperature
type(esmf_field), public temp_input_grid
temperature
type(esmf_field), public terrain_input_grid
terrain height
type(esmf_field), public tprcp_input_grid
precip
type(esmf_field), dimension(:), allocatable, public tracers_input_grid
tracers
type(esmf_field), public tref_input_grid
Reference temperature.
type(esmf_field), public u_input_grid
u/v wind at grid
type(esmf_field), public ustar_input_grid
fric velocity
type(esmf_field), public v_input_grid
box center
type(esmf_field), public veg_greenness_input_grid
vegetation fraction
type(esmf_field), public veg_type_input_grid
vegetation type
integer, public veg_type_landice_input = 15
NOAH land ice option defined at this veg type.
type(esmf_field), public w_0_input_grid
Coefficient 3 to calculate d(tz)/d(ts)
type(esmf_field), public w_d_input_grid
Coefficient 4 to calculate d(tz)/d(ts)
type(esmf_field), public wind_input_grid
3-component wind
type(esmf_field), public xs_input_grid
Salinity content in diurnal thermocline layer.
type(esmf_field), public xt_input_grid
Heat content in diurnal thermocline layer.
type(esmf_field), public xtts_input_grid
d(xt)/d(ts)
type(esmf_field), public xu_input_grid
u-current content in diurnal thermocline layer
type(esmf_field), public xv_input_grid
v-current content in diurnal thermocline layer
type(esmf_field), public xz_input_grid
Diurnal thermocline layer thickness.
type(esmf_field), public xzts_input_grid
d(xz)/d(ts)
type(esmf_field), public z0_input_grid
roughness length
type(esmf_field), public z_c_input_grid
Sub-layer cooling thickness.
type(esmf_field), public zm_input_grid
Oceanic mixed layer depth.
Detailed Description
Read atmospheric, surface and nst data on the input grid.
Supported formats include fv3 tiled 'restart' files, fv3 tiled 'history' files, fv3 gaussian history files, spectral gfs gaussian nemsio files, and spectral gfs sigio/sfcio files.
Public variables are defined below: 'input' indicates field associated with the input grid.
Author:
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine input_data::calcalpha_rotlatlon (real(esmf_kind_r8), dimension(i_input,j_input), intent(in) latgrid, real(esmf_kind_r8), dimension(i_input,j_input), intent(in) longrid, real(esmf_kind_r4), intent(in) cenlat, real(esmf_kind_r4), intent(in) cenlon, real(esmf_kind_r4), dimension(i_input,j_input), intent(out) alpha)
Calculate rotation angle for rotated latlon grids. Needed to convert to earth-relative winds.
Parameters:
latgrid grid latitudes
longrid grid longitudes
cenlat center latitude
cenlon center longitude
alpha grid rotation angle
Author:
Larissa Reames
Definition at line 7098 of file input_data.F90.
References model_grid::i_input, and model_grid::j_input.
Referenced by read_winds().
subroutine, public input_data::check_cnwat (real(esmf_kind_r8), dimension(i_input,j_input), intent(inout) cnwat)
When using GEFS data, some points on the target grid have unreasonable canpy moisture content, so zero out any locations with unrealistic canopy moisture values (>0.5).
Parameters:
cnwat [input] 2-dimensional canopy moisture content
Author:
Larissa Reames CIMMS/NSSL
Definition at line 7491 of file input_data.F90.
References model_grid::i_input, and model_grid::j_input.
Referenced by read_input_sfc_grib2_file().
subroutine, public input_data::check_soilt (real(esmf_kind_r8), dimension(i_input,j_input,lsoil_input), intent(inout) soilt, integer(esmf_kind_i4), dimension(i_input,j_input), intent(in) landmask, real(esmf_kind_r8), dimension(i_input,j_input), intent(in) skint)
Check for and replace certain values in soil temperature. At open water points (landmask=0) use skin temperature as a filler value. At land points (landmask=1) with excessive soil temperature, replace soil temperature with skin temperature. In GEFSv12.0 data there are some erroneous missing values at land points which this corrects. At sea ice points (landmask=2), store a default ice column temperature because grib2 files do not have ice column temperature which FV3 expects at these points.
Parameters:
soilt [inout] 3-dimensional soil temperature arrray
landmask [in] landmask of the input grid
skint [in] 2-dimensional skin temperature array
Author:
Larissa Reames CIMMS/NSSL
Definition at line 7461 of file input_data.F90.
References model_grid::i_input, icet_default, model_grid::j_input, and lsoil_input.
Referenced by read_input_sfc_grib2_file().
subroutine, public input_data::cleanup_input_atm_data ()
Free up memory associated with atm data.
Author:
George Gayno NCEP/EMC
Definition at line 7313 of file input_data.F90.
References dzdt_input_grid, program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, tracers_input_grid, and wind_input_grid.
Referenced by atmosphere::atmosphere_driver().
subroutine, public input_data::cleanup_input_nst_data ()
Free up memory associated with nst data.
Author:
George Gayno NCEP/EMC
Definition at line 7338 of file input_data.F90.
References c_0_input_grid, c_d_input_grid, d_conv_input_grid, dt_cool_input_grid, ifd_input_grid, landsea_mask_input_grid, qrain_input_grid, tref_input_grid, w_0_input_grid, w_d_input_grid, xs_input_grid, xt_input_grid, xtts_input_grid, xu_input_grid, xv_input_grid, xz_input_grid, xzts_input_grid, z_c_input_grid, and zm_input_grid.
Referenced by surface::surface_driver().
subroutine, public input_data::cleanup_input_sfc_data ()
Free up memory associated with sfc data.
Author:
George Gayno NCEP/EMC
Definition at line 7371 of file input_data.F90.
References canopy_mc_input_grid, program_setup::convert_nst, f10m_input_grid, ffmm_input_grid, program_setup::lai_from_climo, lai_input_grid, landsea_mask_input_grid, max_veg_greenness_input_grid, min_veg_greenness_input_grid, program_setup::minmax_vgfrc_from_climo, q2m_input_grid, seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_greenness_input_grid, veg_type_input_grid, program_setup::vgfrc_from_climo, and z0_input_grid.
Referenced by surface::surface_driver().
subroutine, public input_data::convert_winds ()
Convert winds from 2-d to 3-d components.
Author:
George Gayno NCEP/EMC
Definition at line 6981 of file input_data.F90.
References error_handler(), model_grid::latitude_input_grid, model_grid::longitude_input_grid, u_input_grid, v_input_grid, and wind_input_grid.
Referenced by read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
subroutine, public input_data::DINT2P (real*8, dimension(npin) PPIN, real*8, dimension(npin) XXIN, integer NPIN, real*8, dimension(npout) PPOUT, real*8, dimension(npout) XXOUT, integer NPOUT, integer LINLOG, real*8 XMSG, integer IER)
Pressure to presure vertical interpolation for tracers with linear or lnP interpolation. Input tracers on pres levels are interpolated to the target output pressure levels. The matching levels of input and output will keep the same. Extrapolation is also allowed but needs caution. The routine is mostly for GFSV16 combined grib2 input when spfh has missing levels in low and mid troposphere from U/T/HGT/DZDT.
Parameters:
ppin 1d input pres levs
xxin 1d input tracer
npin number of input levs
ppout 1d target pres levs
xxout 1d interpolated tracer
npout number of target levs
linlog interp method.1:linear;not 1:log;neg:extrp allowed
xmsg fill values of missing levels (-999.0)
ier error status. non 0: failed interpolation
Author:
Jili Dong NCEP/EMC
Date:
2021/07/30
Definition at line 7529 of file input_data.F90.
subroutine input_data::gridrot (real(esmf_kind_r4), intent(in) lov, real(esmf_kind_r4), intent(in) latin1, real(esmf_kind_r4), intent(in) latin2, real(esmf_kind_r8), dimension(i_input,j_input), intent(in) lon, real(esmf_kind_r4), dimension(i_input,j_input), intent(inout) rot) [private]
Compute grid rotation angle for non-latlon grids.
Note:
The original gridrot subroutine was specific to polar stereographic grids. We need to compute it for Lambert Conformal grids. So we need lat1,lat2. This follows the ncl_ncarg source code: ncl_ncarg-6.6.2/ni/src/ncl/GetGrids.c
Parameters:
lov orientation angle
latin1 first tangent latitude
latin2 second tangent latitude
lon longitude
rot rotation angle
Author:
Larissa Reames
Definition at line 7057 of file input_data.F90.
References model_grid::i_input, and model_grid::j_input.
Referenced by read_winds().
subroutine input_data::handle_grib_error (character(len=20), intent(in) vname, character(len=20), intent(in) lev, character(len=20), intent(in) method, real(esmf_kind_r4), intent(in) value, integer, intent(in) varnum, integer, intent(inout) iret, real(esmf_kind_r4), dimension(:,:), intent(inout), optional var, real(esmf_kind_r8), dimension(:,:), intent(inout), optional var8, real(esmf_kind_r8), dimension(:,:,:), intent(inout), optional var3d)
Handle GRIB2 read error based on the user selected method in the varmap file.
Parameters:
vname grib2 variable name
lev grib2 variable level
method how missing data is handled
value fill value for missing data
varnum grib2 variable number
iret return status code
var 4-byte array of corrected data
var8 8-byte array of corrected data
var3d 3-d array of corrected data
Author:
Larissa Reames
Definition at line 7147 of file input_data.F90.
References error_handler(), and program_setup::read_from_input.
Referenced by read_grib_soil(), read_input_atm_grib2_file(), read_input_sfc_grib2_file(), and read_winds().
subroutine input_data::init_atm_esmf_fields () [private]
Create atmospheric esmf fields.
Author:
George Gayno NCEP/EMC
Definition at line 445 of file input_data.F90.
References dzdt_input_grid, error_handler(), model_grid::input_grid, lev_input, program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, program_setup::tracers_input, tracers_input_grid, u_input_grid, v_input_grid, and wind_input_grid.
Referenced by read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
subroutine, public input_data::init_sfc_esmf_fields ()
Create surface input grid esmf fields.
Author:
George Gayno NCEP/EMC
Definition at line 539 of file input_data.F90.
References canopy_mc_input_grid, error_handler(), f10m_input_grid, ffmm_input_grid, model_grid::input_grid, program_setup::lai_from_climo, lai_input_grid, landsea_mask_input_grid, lsoil_input, max_veg_greenness_input_grid, min_veg_greenness_input_grid, program_setup::minmax_vgfrc_from_climo, q2m_input_grid, seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_greenness_input_grid, veg_type_input_grid, program_setup::vgfrc_from_climo, and z0_input_grid.
Referenced by read_input_sfc_data().
recursive subroutine, public input_data::quicksort (real*8, dimension(*) a, integer first, integer last)
Sort an array of values.
Parameters:
a the sorted array
first the first value of sorted array
last the last value of sorted array
Author:
Jili Dong NOAA/EMC
Definition at line 7422 of file input_data.F90.
Referenced by read_input_atm_grib2_file().
subroutine input_data::READ_FV3_GRID_DATA_NETCDF (character(len=*), intent(in) FIELD, integer, intent(in) TILE_NUM, integer, intent(in) IMO, integer, intent(in) JMO, integer, intent(in) LMO, real(esmf_kind_r8), dimension(imo,jmo), intent(out), optional SFCDATA, real(esmf_kind_r8), dimension(imo,jmo,lmo), intent(out), optional SFCDATA_3D) [private]
Read a record from a netcdf file.
Parameters:
field name of field to be read
tile_num grid tile number
imo i-dimension of field
jmo j-dimension of field
lmo number of vertical levels of field
sfcdata 1-d array containing field data
sfcdata_3d 3-d array containing field data
Author:
George Gayno NCEP/EMC
Definition at line 6758 of file input_data.F90.
References program_setup::data_dir_input_grid, netcdf_err(), and program_setup::sfc_files_input_grid.
subroutine input_data::read_grib_soil (character(len=20), intent(in) vname, character(len=20), intent(in) vname_file, integer, intent(in) lugb, integer, intent(in) pdt_num, real(esmf_kind_r8), dimension(:,:,:), intent(inout) dummy3d) [private]
Read soil temperature and soil moisture fields from a GRIB2 file.
Parameters:
vname variable name in varmap table
vname_file variable name in grib2 file
lugb logical unit number for surface grib2 file
pdt_num product definition template number.
dummy3d array of soil data
Author:
George Gayno NCEP/EMC
Definition at line 7212 of file input_data.F90.
References error_handler(), program_setup::get_var_cond(), handle_grib_error(), model_grid::i_input, and model_grid::j_input.
Referenced by read_input_sfc_grib2_file().
subroutine, public input_data::read_input_atm_data (integer, intent(in) localpet)
Read input grid atmospheric data driver.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 149 of file input_data.F90.
References program_setup::input_type, read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
Referenced by atmosphere::atmosphere_driver().
subroutine input_data::read_input_atm_gaussian_nemsio_file (integer, intent(in) localpet) [private]
Read input grid atmospheric fv3 gaussian nemsio files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 1239 of file input_data.F90.
References program_setup::atm_files_input_grid, convert_winds(), program_setup::data_dir_input_grid, dpres_input_grid, dzdt_input_grid, error_handler(), model_grid::i_input, init_atm_esmf_fields(), model_grid::input_grid, model_grid::j_input, lev_input, levp1_input, program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, program_setup::tracers_input, tracers_input_grid, u_input_grid, and v_input_grid.
Referenced by read_input_atm_data().
subroutine input_data::read_input_atm_gaussian_netcdf_file (integer, intent(in) localpet) [private]
Read fv3 netcdf gaussian history file. Each task reads a horizontal slice.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 1781 of file input_data.F90.
References program_setup::atm_files_input_grid, convert_winds(), program_setup::data_dir_input_grid, dpres_input_grid, dzdt_input_grid, error_handler(), model_grid::i_input, init_atm_esmf_fields(), model_grid::input_grid, model_grid::j_input, lev_input, levp1_input, netcdf_err(), program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, program_setup::tracers_input, tracers_input_grid, u_input_grid, and v_input_grid.
Referenced by read_input_atm_data().
subroutine input_data::read_input_atm_gfs_gaussian_nemsio_file (integer, intent(in) localpet)
Read input atmospheric data from spectral gfs (global gaussian in nemsio format. Starting July 19, 2017).
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 986 of file input_data.F90.
References program_setup::atm_files_input_grid, convert_winds(), program_setup::data_dir_input_grid, dzdt_input_grid, error_handler(), model_grid::i_input, init_atm_esmf_fields(), model_grid::j_input, lev_input, levp1_input, program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, program_setup::tracers_input, tracers_input_grid, u_input_grid, and v_input_grid.
Referenced by read_input_atm_data().
subroutine input_data::read_input_atm_gfs_sigio_file (integer, intent(in) localpet) [private]
Read input atmospheric data from spectral gfs (old sigio format).
Note:
Format used prior to July 19, 2017.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 747 of file input_data.F90.
References program_setup::atm_files_input_grid, convert_winds(), program_setup::data_dir_input_grid, dzdt_input_grid, error_handler(), model_grid::i_input, init_atm_esmf_fields(), model_grid::j_input, lev_input, levp1_input, program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, program_setup::tracers_input, tracers_input_grid, u_input_grid, and v_input_grid.
Referenced by read_input_atm_data().
subroutine input_data::read_input_atm_grib2_file (integer, intent(in) localpet)
Read input grid atmospheric fv3gfs grib2 files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 2456 of file input_data.F90.
References grib2_util::convert_omega(), convert_winds(), program_setup::data_dir_input_grid, dzdt_input_grid, error_handler(), program_setup::external_model, program_setup::get_var_cond(), program_setup::grib2_file_input_grid, handle_grib_error(), model_grid::i_input, init_atm_esmf_fields(), model_grid::j_input, lev_input, levp1_input, pres_input_grid, ps_input_grid, quicksort(), read_winds(), grib2_util::rh2spfh(), grib2_util::rh2spfh_gfs(), slevs, temp_input_grid, terrain_input_grid, program_setup::tracers, program_setup::tracers_input, tracers_input_grid, u_input_grid, and v_input_grid.
Referenced by read_input_atm_data().
subroutine input_data::read_input_atm_restart_file (integer, intent(in) localpet) [private]
Read input grid fv3 atmospheric data 'warm' restart files.
Note:
Routine reads tiled files in parallel. Tile 1 is read by localpet 0; tile 2 by localpet 1, etc. The number of pets must be equal to or greater than the number of tiled files.
 Logic only tested with global input data of six tiles.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 1522 of file input_data.F90.
References program_setup::atm_core_files_input_grid, program_setup::atm_tracer_files_input_grid, convert_winds(), program_setup::data_dir_input_grid, dpres_input_grid, dzdt_input_grid, error_handler(), model_grid::i_input, init_atm_esmf_fields(), model_grid::input_grid, model_grid::j_input, lev_input, levp1_input, netcdf_err(), model_grid::num_tiles_input_grid, program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, program_setup::tracers_input, tracers_input_grid, u_input_grid, and v_input_grid.
Referenced by read_input_atm_data().
subroutine input_data::read_input_atm_tiled_history_file (integer, intent(in) localpet)
Read input grid fv3 atmospheric tiled history files in netcdf format.
Note:
Routine reads tiled files in parallel. Tile 1 is read by localpet 0; tile 2 by localpet 1, etc. The number of pets must be equal to or greater than the number of tiled files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 2165 of file input_data.F90.
References program_setup::atm_files_input_grid, convert_winds(), program_setup::data_dir_input_grid, dpres_input_grid, dzdt_input_grid, error_handler(), model_grid::i_input, init_atm_esmf_fields(), model_grid::input_grid, model_grid::j_input, lev_input, levp1_input, netcdf_err(), model_grid::num_tiles_input_grid, program_setup::num_tracers_input, pres_input_grid, ps_input_grid, temp_input_grid, terrain_input_grid, program_setup::tracers_input, tracers_input_grid, u_input_grid, and v_input_grid.
Referenced by read_input_atm_data().
subroutine, public input_data::read_input_nst_data (integer, intent(in) localpet)
Driver to read input grid nst data.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 219 of file input_data.F90.
References c_0_input_grid, c_d_input_grid, d_conv_input_grid, dt_cool_input_grid, error_handler(), ifd_input_grid, model_grid::input_grid, program_setup::input_type, qrain_input_grid, read_input_nst_nemsio_file(), read_input_nst_netcdf_file(), tref_input_grid, w_0_input_grid, w_d_input_grid, xs_input_grid, xt_input_grid, xtts_input_grid, xu_input_grid, xv_input_grid, xz_input_grid, xzts_input_grid, z_c_input_grid, and zm_input_grid.
Referenced by surface::surface_driver().
subroutine input_data::read_input_nst_nemsio_file (integer, intent(in) localpet) [private]
Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file.
Note:
The spectral GFS nst data is in a separate file from the surface data. The fv3 surface and nst data are in a single file.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 6482 of file input_data.F90.
References c_0_input_grid, c_d_input_grid, d_conv_input_grid, program_setup::data_dir_input_grid, dt_cool_input_grid, error_handler(), model_grid::i_input, ifd_input_grid, program_setup::input_type, model_grid::j_input, program_setup::nst_files_input_grid, qrain_input_grid, program_setup::sfc_files_input_grid, tref_input_grid, w_0_input_grid, w_d_input_grid, xs_input_grid, xt_input_grid, xtts_input_grid, xu_input_grid, xv_input_grid, xz_input_grid, xzts_input_grid, z_c_input_grid, and zm_input_grid.
Referenced by read_input_nst_data().
subroutine input_data::read_input_nst_netcdf_file (integer, intent(in) localpet)
Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 6198 of file input_data.F90.
References c_0_input_grid, c_d_input_grid, d_conv_input_grid, dt_cool_input_grid, error_handler(), model_grid::i_input, ifd_input_grid, program_setup::input_type, model_grid::j_input, lsoil_input, model_grid::num_tiles_input_grid, qrain_input_grid, tref_input_grid, w_0_input_grid, w_d_input_grid, xs_input_grid, xt_input_grid, xtts_input_grid, xu_input_grid, xv_input_grid, xz_input_grid, xzts_input_grid, z_c_input_grid, and zm_input_grid.
Referenced by read_input_nst_data().
subroutine, public input_data::read_input_sfc_data (integer, intent(in) localpet)
Driver to read input grid surface data.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 381 of file input_data.F90.
References init_sfc_esmf_fields(), program_setup::input_type, read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
Referenced by surface::surface_driver().
subroutine input_data::read_input_sfc_gaussian_nemsio_file (integer, intent(in) localpet) [private]
Read input grid surface data from an fv3 gaussian nemsio file.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 3986 of file input_data.F90.
References canopy_mc_input_grid, program_setup::data_dir_input_grid, error_handler(), f10m_input_grid, ffmm_input_grid, model_grid::i_input, model_grid::j_input, landsea_mask_input_grid, lsoil_input, q2m_input_grid, seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, program_setup::sfc_files_input_grid, skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_type_input_grid, and z0_input_grid.
Referenced by read_input_sfc_data().
subroutine input_data::read_input_sfc_gfs_gaussian_nemsio_file (integer, intent(in) localpet)
Read input grid surface data from a spectral gfs gaussian nemsio file.
Note:
Format used by gfs starting July 19, 2017.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 3637 of file input_data.F90.
References canopy_mc_input_grid, program_setup::data_dir_input_grid, error_handler(), f10m_input_grid, ffmm_input_grid, model_grid::i_input, model_grid::j_input, landsea_mask_input_grid, lsoil_input, q2m_input_grid, seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, program_setup::sfc_files_input_grid, skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_type_input_grid, and z0_input_grid.
Referenced by read_input_sfc_data().
subroutine input_data::read_input_sfc_gfs_sfcio_file (integer, intent(in) localpet)
Read input grid surface data from a spectral gfs gaussian sfcio file.
Note:
Prior to July 19, 2017.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 3413 of file input_data.F90.
References canopy_mc_input_grid, program_setup::data_dir_input_grid, error_handler(), f10m_input_grid, ffmm_input_grid, model_grid::i_input, model_grid::j_input, landsea_mask_input_grid, lsoil_input, q2m_input_grid, seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, program_setup::sfc_files_input_grid, skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_type_input_grid, veg_type_landice_input, and z0_input_grid.
Referenced by read_input_sfc_data().
subroutine input_data::read_input_sfc_grib2_file (integer, intent(in) localpet) [private]
Read input grid surface data from a grib2 file.
Parameters:
localpet ESMF local persistent execution thread
Author:
Larissa Reames
Definition at line 5013 of file input_data.F90.
References canopy_mc_input_grid, check_cnwat(), check_soilt(), error_handler(), f10m_input_grid, ffmm_input_grid, handle_grib_error(), model_grid::input_grid_type, lai_input_grid, landsea_mask_input_grid, lsoil_input, max_veg_greenness_input_grid, min_veg_greenness_input_grid, netcdf_err(), q2m_input_grid, read_grib_soil(), seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, search_util::search(), skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, program_setup::sotyp_from_climo, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_greenness_input_grid, veg_type_input_grid, program_setup::vgtyp_from_climo, and z0_input_grid.
Referenced by read_input_sfc_data().
subroutine input_data::read_input_sfc_netcdf_file (integer, intent(in) localpet) [private]
Read input grid surface data from tiled 'history' files (netcdf) or gaussian netcdf files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 4652 of file input_data.F90.
References canopy_mc_input_grid, program_setup::data_dir_input_grid, error_handler(), f10m_input_grid, ffmm_input_grid, model_grid::i_input, program_setup::input_type, model_grid::j_input, landsea_mask_input_grid, lsoil_input, netcdf_err(), model_grid::num_tiles_input_grid, program_setup::orog_dir_input_grid, program_setup::orog_files_input_grid, q2m_input_grid, seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, program_setup::sfc_files_input_grid, skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_type_input_grid, and z0_input_grid.
Referenced by read_input_sfc_data().
subroutine input_data::read_input_sfc_restart_file (integer, intent(in) localpet) [private]
Read input grid surface data from fv3 tiled warm 'restart' files.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 4335 of file input_data.F90.
References canopy_mc_input_grid, program_setup::data_dir_input_grid, error_handler(), f10m_input_grid, ffmm_input_grid, model_grid::i_input, model_grid::j_input, landsea_mask_input_grid, lsoil_input, netcdf_err(), model_grid::num_tiles_input_grid, program_setup::orog_dir_input_grid, program_setup::orog_files_input_grid, q2m_input_grid, seaice_depth_input_grid, seaice_fract_input_grid, seaice_skin_temp_input_grid, program_setup::sfc_files_input_grid, skin_temp_input_grid, snow_depth_input_grid, snow_liq_equiv_input_grid, soil_temp_input_grid, soil_type_input_grid, soilm_liq_input_grid, soilm_tot_input_grid, srflag_input_grid, t2m_input_grid, terrain_input_grid, tprcp_input_grid, ustar_input_grid, veg_type_input_grid, and z0_input_grid.
Referenced by read_input_sfc_data().
subroutine input_data::read_winds (real(esmf_kind_r8), dimension(:,:,:), intent(inout), allocatable u, real(esmf_kind_r8), dimension(:,:,:), intent(inout), allocatable v, integer, intent(in) localpet, integer, intent(in) octet_23, real(esmf_kind_r8), dimension(lev_input), intent(in) rlevs, integer, intent(in) lugb, integer, intent(in) pdt_num) [private]
Read winds from a grib2 file. Rotate winds to be earth relative if necessary.
Parameters:
u u-component wind
v v-component wind
localpet ESMF local persistent execution thread
octet_23 Section 4/Octet 23 - Type of first fixed surface.
rlevs Array of atmospheric level values
lugb Logical unit number of GRIB2 file.
pdt_num Product definition template number.
Author:
Larissa Reames
Definition at line 6806 of file input_data.F90.
References calcalpha_rotlatlon(), error_handler(), program_setup::get_var_cond(), gridrot(), handle_grib_error(), model_grid::i_input, model_grid::j_input, model_grid::jp1_input, model_grid::latitude_input_grid, lev_input, model_grid::longitude_input_grid, and slevs.
Referenced by read_input_atm_grib2_file().
Variable Documentation
type(esmf_field), public input_data::c_0_input_grid
Coefficient 1 to calculate d(tz)/d(ts)
Definition at line 110 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::c_d_input_grid
Coefficient 2 to calculate d(tz)/d(ts)
Definition at line 109 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::canopy_mc_input_grid
canopy moist content
Definition at line 74 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::d_conv_input_grid
Thickness of free convection layer.
Definition at line 111 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field) input_data::dpres_input_grid [private]
pressure thickness
Definition at line 53 of file input_data.F90.
Referenced by read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::dt_cool_input_grid
Sub-layer cooling amount.
Definition at line 112 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::dzdt_input_grid
vert velocity
Definition at line 52 of file input_data.F90.
Referenced by atmosphere::atmosphere_driver(), cleanup_input_atm_data(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::f10m_input_grid
log((z0+10)*1/z0)
Definition at line 75 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::ffmm_input_grid
log((z0+z1)*1/z0) See sfc_diff.f for details.
Definition at line 76 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
integer, parameter input_data::icet_default = 265.0 [private]
Default value of soil and skin temperature (K) over ice.
Definition at line 72 of file input_data.F90.
Referenced by check_soilt().
type(esmf_field), public input_data::ifd_input_grid
Model mode index. 0-diurnal model not started; 1-diurnal model started.
Definition at line 113 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::lai_input_grid
leaf area index
Definition at line 98 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), and read_input_sfc_grib2_file().
type(esmf_field), public input_data::landsea_mask_input_grid
land sea mask; 0-water, 1-land, 2-ice
Definition at line 78 of file input_data.F90.
Referenced by cleanup_input_nst_data(), cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
integer, public input_data::lev_input
number of atmospheric layers
Definition at line 64 of file input_data.F90.
Referenced by atmosphere::create_atm_b4adj_esmf_fields(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), read_input_atm_tiled_history_file(), read_winds(), atmosphere::VINTG(), and atmosphere::VINTG_WAM().
integer, public input_data::levp1_input
number of atmos layer interfaces
Definition at line 65 of file input_data.F90.
Referenced by read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
integer, public input_data::lsoil_input =4
number of soil layers, no longer hardwired to allow for 7 layers of soil for the RUC LSM
Definition at line 102 of file input_data.F90.
Referenced by surface::adjust_soil_levels(), check_soilt(), init_sfc_esmf_fields(), read_input_nst_netcdf_file(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::max_veg_greenness_input_grid
shdmax
Definition at line 99 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), and read_input_sfc_grib2_file().
type(esmf_field), public input_data::min_veg_greenness_input_grid
shdmin
Definition at line 100 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), and read_input_sfc_grib2_file().
type(esmf_field), public input_data::pres_input_grid
3-d pressure
Definition at line 54 of file input_data.F90.
Referenced by atmosphere::atmosphere_driver(), cleanup_input_atm_data(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::ps_input_grid
surface pressure
Definition at line 55 of file input_data.F90.
Referenced by atmosphere::atmosphere_driver(), cleanup_input_atm_data(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::q2m_input_grid
2-m spec hum
Definition at line 80 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::qrain_input_grid
Sensible heat flux due to rainfall.
Definition at line 115 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::seaice_depth_input_grid
sea ice depth
Definition at line 81 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::seaice_fract_input_grid
sea ice fraction
Definition at line 82 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::seaice_skin_temp_input_grid
sea ice skin temp
Definition at line 83 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::skin_temp_input_grid
skin temp/sst
Definition at line 84 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
character(len=50), dimension(:), allocatable, private input_data::slevs [private]
The atmospheric levels in the GRIB2 input file.
Definition at line 105 of file input_data.F90.
Referenced by read_input_atm_grib2_file(), and read_winds().
type(esmf_field), public input_data::snow_depth_input_grid
snow dpeth
Definition at line 85 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::snow_liq_equiv_input_grid
snow liq equiv depth
Definition at line 86 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::soil_temp_input_grid
3-d soil temp
Definition at line 87 of file input_data.F90.
Referenced by surface::adjust_soil_levels(), cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::soil_type_input_grid
soil type
Definition at line 88 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::soilm_liq_input_grid
3-d liquid soil moisture
Definition at line 89 of file input_data.F90.
Referenced by surface::adjust_soil_levels(), cleanup_input_sfc_data(), init_sfc_esmf_fields(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::soilm_tot_input_grid
3-d total soil moisture
Definition at line 90 of file input_data.F90.
Referenced by surface::adjust_soil_levels(), cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::srflag_input_grid
snow/rain flag
Definition at line 91 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::t2m_input_grid
2-m temperature
Definition at line 92 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::temp_input_grid
temperature
Definition at line 57 of file input_data.F90.
Referenced by atmosphere::atmosphere_driver(), cleanup_input_atm_data(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::terrain_input_grid
terrain height
Definition at line 56 of file input_data.F90.
Referenced by atmosphere::atmosphere_driver(), cleanup_input_atm_data(), cleanup_input_sfc_data(), init_atm_esmf_fields(), init_sfc_esmf_fields(), surface::interp(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), read_input_atm_tiled_history_file(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::tprcp_input_grid
precip
Definition at line 93 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), dimension(:), allocatable, public input_data::tracers_input_grid
tracers
Definition at line 62 of file input_data.F90.
Referenced by atmosphere::atmosphere_driver(), cleanup_input_atm_data(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::tref_input_grid
Reference temperature.
Definition at line 116 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::u_input_grid
u/v wind at grid
Definition at line 59 of file input_data.F90.
Referenced by convert_winds(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::ustar_input_grid
fric velocity
Definition at line 94 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::v_input_grid
box center
Definition at line 60 of file input_data.F90.
Referenced by convert_winds(), init_atm_esmf_fields(), read_input_atm_gaussian_nemsio_file(), read_input_atm_gaussian_netcdf_file(), read_input_atm_gfs_gaussian_nemsio_file(), read_input_atm_gfs_sigio_file(), read_input_atm_grib2_file(), read_input_atm_restart_file(), and read_input_atm_tiled_history_file().
type(esmf_field), public input_data::veg_greenness_input_grid
vegetation fraction
Definition at line 97 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), and read_input_sfc_grib2_file().
type(esmf_field), public input_data::veg_type_input_grid
vegetation type
Definition at line 95 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
integer, public input_data::veg_type_landice_input = 15
NOAH land ice option defined at this veg type. Default is igbp.
Definition at line 69 of file input_data.F90.
Referenced by surface::interp(), and read_input_sfc_gfs_sfcio_file().
type(esmf_field), public input_data::w_0_input_grid
Coefficient 3 to calculate d(tz)/d(ts)
Definition at line 118 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::w_d_input_grid
Coefficient 4 to calculate d(tz)/d(ts)
Definition at line 117 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::wind_input_grid
3-component wind
Definition at line 61 of file input_data.F90.
Referenced by atmosphere::atmosphere_driver(), cleanup_input_atm_data(), convert_winds(), and init_atm_esmf_fields().
type(esmf_field), public input_data::xs_input_grid
Salinity content in diurnal thermocline layer.
Definition at line 119 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::xt_input_grid
Heat content in diurnal thermocline layer.
Definition at line 120 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::xtts_input_grid
d(xt)/d(ts)
Definition at line 124 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::xu_input_grid
u-current content in diurnal thermocline layer
Definition at line 121 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::xv_input_grid
v-current content in diurnal thermocline layer
Definition at line 122 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::xz_input_grid
Diurnal thermocline layer thickness.
Definition at line 123 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::xzts_input_grid
d(xz)/d(ts)
Definition at line 125 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::z0_input_grid
roughness length
Definition at line 96 of file input_data.F90.
Referenced by cleanup_input_sfc_data(), init_sfc_esmf_fields(), surface::interp(), read_input_sfc_gaussian_nemsio_file(), read_input_sfc_gfs_gaussian_nemsio_file(), read_input_sfc_gfs_sfcio_file(), read_input_sfc_grib2_file(), read_input_sfc_netcdf_file(), and read_input_sfc_restart_file().
type(esmf_field), public input_data::z_c_input_grid
Sub-layer cooling thickness.
Definition at line 126 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
type(esmf_field), public input_data::zm_input_grid
Oceanic mixed layer depth.
Definition at line 127 of file input_data.F90.
Referenced by cleanup_input_nst_data(), surface::interp(), read_input_nst_data(), read_input_nst_nemsio_file(), and read_input_nst_netcdf_file().
Author
Generated automatically by Doxygen for chgres_cube from the source code.