.TH "/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/chgres_cube.fd/input_data.F90" 3 "Thu Aug 4 2022" "Version 1.8.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/chgres_cube.fd/input_data.F90 \- Read atmospheric and surface data from GRIB2, NEMSIO and NetCDF files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBinput_data\fP"
.br
.RI "Read atmospheric, surface and nst data on the input grid\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBinput_data::calcalpha_rotlatlon\fP (latgrid, longrid, cenlat, cenlon, alpha)"
.br
.RI "Calculate rotation angle for rotated latlon grids\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::check_cnwat\fP (cnwat)"
.br
.RI "When using GEFS data, some points on the target grid have unreasonable canpy moisture content, so zero out any locations with unrealistic canopy moisture values (>0\&.5)\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::check_soilt\fP (soilt, landmask, skint)"
.br
.RI "Check for and replace certain values in soil temperature\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::cleanup_input_atm_data\fP"
.br
.RI "Free up memory associated with atm data\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::cleanup_input_nst_data\fP"
.br
.RI "Free up memory associated with nst data\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::cleanup_input_sfc_data\fP"
.br
.RI "Free up memory associated with sfc data\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::convert_winds\fP"
.br
.RI "Convert winds from 2-d to 3-d components\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::DINT2P\fP (PPIN, XXIN, NPIN, PPOUT, XXOUT, NPOUT, LINLOG, XMSG, IER)"
.br
.RI "Pressure to presure vertical interpolation for tracers with linear or lnP interpolation\&. "
.ti -1c
.RI "subroutine \fBinput_data::gridrot\fP (lov, latin1, latin2, lon, rot)"
.br
.RI "Compute grid rotation angle for non-latlon grids\&. "
.ti -1c
.RI "subroutine \fBinput_data::handle_grib_error\fP (vname, lev, method, value, varnum, iret, var, var8, var3d)"
.br
.RI "Handle GRIB2 read error based on the user selected method in the varmap file\&. "
.ti -1c
.RI "subroutine \fBinput_data::init_atm_esmf_fields\fP"
.br
.RI "Create atmospheric esmf fields\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::init_sfc_esmf_fields\fP"
.br
.RI "Create surface input grid esmf fields\&. "
.ti -1c
.RI "recursive subroutine, public \fBinput_data::quicksort\fP (a, first, last)"
.br
.RI "Sort an array of values\&. "
.ti -1c
.RI "subroutine \fBinput_data::READ_FV3_GRID_DATA_NETCDF\fP (FIELD, TILE_NUM, IMO, JMO, LMO, SFCDATA, SFCDATA_3D)"
.br
.RI "Read a record from a netcdf file\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_grib_soil\fP (vname, vname_file, lugb, pdt_num, dummy3d)"
.br
.RI "Read soil temperature and soil moisture fields from a GRIB2 file\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::read_input_atm_data\fP (localpet)"
.br
.RI "Read input grid atmospheric data driver\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_atm_gaussian_nemsio_file\fP (localpet)"
.br
.RI "Read input grid atmospheric fv3 gaussian nemsio files\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_atm_gaussian_netcdf_file\fP (localpet)"
.br
.RI "Read fv3 netcdf gaussian history file\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_atm_gfs_gaussian_nemsio_file\fP (localpet)"
.br
.RI "Read input atmospheric data from spectral gfs (global gaussian in nemsio format\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_atm_gfs_sigio_file\fP (localpet)"
.br
.RI "Read input atmospheric data from spectral gfs (old sigio format)\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_atm_grib2_file\fP (localpet)"
.br
.RI "Read input grid atmospheric fv3gfs grib2 files\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_atm_restart_file\fP (localpet)"
.br
.RI "Read input grid fv3 atmospheric data 'warm' restart files\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_atm_tiled_history_file\fP (localpet)"
.br
.RI "Read input grid fv3 atmospheric tiled history files in netcdf format\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::read_input_nst_data\fP (localpet)"
.br
.RI "Driver to read input grid nst data\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_nst_nemsio_file\fP (localpet)"
.br
.RI "Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_nst_netcdf_file\fP (localpet)"
.br
.RI "Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history\&. "
.ti -1c
.RI "subroutine, public \fBinput_data::read_input_sfc_data\fP (localpet)"
.br
.RI "Driver to read input grid surface data\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_sfc_gaussian_nemsio_file\fP (localpet)"
.br
.RI "Read input grid surface data from an fv3 gaussian nemsio file\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_sfc_gfs_gaussian_nemsio_file\fP (localpet)"
.br
.RI "Read input grid surface data from a spectral gfs gaussian nemsio file\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_sfc_gfs_sfcio_file\fP (localpet)"
.br
.RI "Read input grid surface data from a spectral gfs gaussian sfcio file\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_sfc_grib2_file\fP (localpet)"
.br
.RI "Read input grid surface data from a grib2 file\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_sfc_netcdf_file\fP (localpet)"
.br
.RI "Read input grid surface data from tiled 'history' files (netcdf) or gaussian netcdf files\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_input_sfc_restart_file\fP (localpet)"
.br
.RI "Read input grid surface data from fv3 tiled warm 'restart' files\&. "
.ti -1c
.RI "subroutine \fBinput_data::read_winds\fP (u, v, localpet, octet_23, rlevs, lugb, pdt_num)"
.br
.RI "Read winds from a grib2 file\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(esmf_field), public \fBinput_data::c_0_input_grid\fP"
.br
.RI "Coefficient 1 to calculate d(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::c_d_input_grid\fP"
.br
.RI "Coefficient 2 to calculate d(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::canopy_mc_input_grid\fP"
.br
.RI "canopy moist content "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::d_conv_input_grid\fP"
.br
.RI "Thickness of free convection layer\&. "
.ti -1c
.RI "type(esmf_field) \fBinput_data::dpres_input_grid\fP"
.br
.RI "pressure thickness "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::dt_cool_input_grid\fP"
.br
.RI "Sub-layer cooling amount\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::dzdt_input_grid\fP"
.br
.RI "vert velocity "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::f10m_input_grid\fP"
.br
.RI "log((z0+10)*1/z0) "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::ffmm_input_grid\fP"
.br
.RI "log((z0+z1)*1/z0) See sfc_diff\&.f for details\&. "
.ti -1c
.RI "integer, parameter \fBinput_data::icet_default\fP = 265\&.0"
.br
.RI "Default value of soil and skin temperature (K) over ice\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::ifd_input_grid\fP"
.br
.RI "Model mode index\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::lai_input_grid\fP"
.br
.RI "leaf area index "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::landsea_mask_input_grid\fP"
.br
.RI "land sea mask; 0-water, 1-land, 2-ice "
.ti -1c
.RI "integer, public \fBinput_data::lev_input\fP"
.br
.RI "number of atmospheric layers "
.ti -1c
.RI "integer, public \fBinput_data::levp1_input\fP"
.br
.RI "number of atmos layer interfaces "
.ti -1c
.RI "integer, public \fBinput_data::lsoil_input\fP =4"
.br
.RI "number of soil layers, no longer hardwired to allow for 7 layers of soil for the RUC LSM "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::max_veg_greenness_input_grid\fP"
.br
.RI "shdmax "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::min_veg_greenness_input_grid\fP"
.br
.RI "shdmin "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::pres_input_grid\fP"
.br
.RI "3-d pressure "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::ps_input_grid\fP"
.br
.RI "surface pressure "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::q2m_input_grid\fP"
.br
.RI "2-m spec hum "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::qrain_input_grid\fP"
.br
.RI "Sensible heat flux due to rainfall\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::seaice_depth_input_grid\fP"
.br
.RI "sea ice depth "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::seaice_fract_input_grid\fP"
.br
.RI "sea ice fraction "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::seaice_skin_temp_input_grid\fP"
.br
.RI "sea ice skin temp "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::skin_temp_input_grid\fP"
.br
.RI "skin temp/sst "
.ti -1c
.RI "character(len=50), dimension(:), allocatable, private \fBinput_data::slevs\fP"
.br
.RI "The atmospheric levels in the GRIB2 input file\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::snow_depth_input_grid\fP"
.br
.RI "snow dpeth "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::snow_liq_equiv_input_grid\fP"
.br
.RI "snow liq equiv depth "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::soil_temp_input_grid\fP"
.br
.RI "3-d soil temp "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::soil_type_input_grid\fP"
.br
.RI "soil type "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::soilm_liq_input_grid\fP"
.br
.RI "3-d liquid soil moisture "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::soilm_tot_input_grid\fP"
.br
.RI "3-d total soil moisture "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::srflag_input_grid\fP"
.br
.RI "snow/rain flag "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::t2m_input_grid\fP"
.br
.RI "2-m temperature "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::temp_input_grid\fP"
.br
.RI "temperature "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::terrain_input_grid\fP"
.br
.RI "terrain height "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::tprcp_input_grid\fP"
.br
.RI "precip "
.ti -1c
.RI "type(esmf_field), dimension(:), allocatable, public \fBinput_data::tracers_input_grid\fP"
.br
.RI "tracers "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::tref_input_grid\fP"
.br
.RI "Reference temperature\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::u_input_grid\fP"
.br
.RI "u/v wind at grid "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::ustar_input_grid\fP"
.br
.RI "fric velocity "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::v_input_grid\fP"
.br
.RI "box center "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::veg_greenness_input_grid\fP"
.br
.RI "vegetation fraction "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::veg_type_input_grid\fP"
.br
.RI "vegetation type "
.ti -1c
.RI "integer, public \fBinput_data::veg_type_landice_input\fP = 15"
.br
.RI "NOAH land ice option defined at this veg type\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::w_0_input_grid\fP"
.br
.RI "Coefficient 3 to calculate d(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::w_d_input_grid\fP"
.br
.RI "Coefficient 4 to calculate d(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::wind_input_grid\fP"
.br
.RI "3-component wind "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::xs_input_grid\fP"
.br
.RI "Salinity content in diurnal thermocline layer\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::xt_input_grid\fP"
.br
.RI "Heat content in diurnal thermocline layer\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::xtts_input_grid\fP"
.br
.RI "d(xt)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::xu_input_grid\fP"
.br
.RI "u-current content in diurnal thermocline layer "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::xv_input_grid\fP"
.br
.RI "v-current content in diurnal thermocline layer "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::xz_input_grid\fP"
.br
.RI "Diurnal thermocline layer thickness\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::xzts_input_grid\fP"
.br
.RI "d(xz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::z0_input_grid\fP"
.br
.RI "roughness length "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::z_c_input_grid\fP"
.br
.RI "Sub-layer cooling thickness\&. "
.ti -1c
.RI "type(esmf_field), public \fBinput_data::zm_input_grid\fP"
.br
.RI "Oceanic mixed layer depth\&. "
.in -1c
.SH "Detailed Description"
.PP 
Read atmospheric and surface data from GRIB2, NEMSIO and NetCDF files\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition in file \fBinput_data\&.F90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
