program_setup
NAME
program_setup - This module contains code to read the setup namelist file, handle the varmap file for GRIB2 data, and calculate the soil parameters.
SYNOPSIS
Functions/Subroutines
subroutine calc_soil_params (num_soil_cats, smlow, smhigh, satdk, maxsmc, bb, satpsi, satdw, refsmc, drysmc, wltsmc)
Compute soil parameters.
subroutine, public calc_soil_params_driver (localpet)
Driver routine to compute soil parameters for each soil type.
subroutine, public get_var_cond (var_name, this_miss_var_method, this_miss_var_value, this_field_var_name, loc)
Search the variable mapping table to find conditions for handling missing variables.
subroutine, public read_setup_namelist (filename)
Reads program configuration namelist.
subroutine, public read_varmap
Reads the variable mapping table, which is required for initializing with GRIB2 data.
Variables
character(len=500), dimension(7), public atm_core_files_input_grid = 'NULL'
File names of input atmospheric restart core files.
character(len=500), dimension(6), public atm_files_input_grid = 'NULL'
File names of input atmospheric data.
character(len=500), dimension(6), public atm_tracer_files_input_grid = 'NULL'
File names of input atmospheric restart tracer files.
character(len=500), public atm_weight_file ='NULL'
File containing pre-computed weights to horizontally interpolate atmospheric fields.
real, dimension(:), allocatable, public bb_target
Soil 'b' parameter, target grid.
character(len=20), dimension(:), allocatable, public chgres_var_names
Varmap table variable name as recognized by this program.
logical, public convert_atm = .false.
Convert atmospheric data when true.
logical, public convert_nst = .false.
Convert nst data when true.
logical, public convert_sfc = .false.
Convert sfc data when true.
character(len=6), public cres_target_grid = 'NULL'
Target grid resolution, i.e., C768.
integer, public cycle_day = -999
Cycle day.
integer, public cycle_hour = -999
Cycle hour.
integer, public cycle_mon = -999
Cycle month.
integer, public cycle_year = -999
Cycle year.
character(len=500), public data_dir_input_grid = 'NULL'
Directory containing input atm or sfc files.
real, dimension(:), allocatable, public drysmc_input
Air dry soil moisture content input grid.
real, dimension(:), allocatable, public drysmc_target
Air dry soil moisture content target grid.
character(len=20), public external_model ='GFS'
The model that the input data is derived from.
character(len=20), dimension(:), allocatable, public field_var_names
The GRIB2 variable name in the varmap table.
character(len=500), public fix_dir_target_grid = 'NULL'
Directory containing target grid pre-computed fixed data (ex: soil type).
character(len=500), public geogrid_file_input_grid = 'NULL'
Name of 'geogrid' file, which contains static surface fields on the input grid.
character(len=500), public grib2_file_input_grid = 'NULL'
REQUIRED.
integer, public halo_blend = 0
Number of row/cols of blending halo, where model tendencies and lateral boundary tendencies are applied.
integer, public halo_bndy = 0
Number of row/cols of lateral halo, where pure lateral bndy conditions are applied (regional target grids).
character(len=25), public input_type ='restart'
Input data type:
logical, public lai_from_climo = .true.
If false, interpolate leaf area index from the input data to the target grid instead of using data from static data.
integer, parameter, public max_tracers =100
Maximum number of atmospheric tracers processed.
real, dimension(:), allocatable, public maxsmc_input
Maximum soil moisture content input grid.
real, dimension(:), allocatable, public maxsmc_target
Maximum soil moisture content target grid.
logical, public minmax_vgfrc_from_climo = .true.
If false, interpolate min/max vegetation fraction from the input data to the target grid instead of using data from static data.
character(len=20), dimension(:), allocatable, public missing_var_methods
Method to replace missing GRIB2 input records.
real, dimension(:), allocatable, public missing_var_values
If input GRIB2 record is missing, the variable is set to this value.
character(len=500), public mosaic_file_input_grid = 'NULL'
Input grid mosaic file.
character(len=500), public mosaic_file_target_grid = 'NULL'
Target grid mosaic file.
integer, public nsoill_out = 4
Number of soil levels desired in the output data.
character(len=500), public nst_files_input_grid = 'NULL'
File name of input nst data.
integer, public num_tracers
Number of atmospheric tracers to be processed.
integer, public num_tracers_input
Number of atmospheric tracers in input file.
character(len=500), public orog_dir_input_grid = 'NULL'
Directory containing the input grid orography files.
character(len=500), public orog_dir_target_grid = 'NULL'
Directory containing the target grid orography files.
character(len=500), dimension(6), public orog_files_input_grid = 'NULL'
Input grid orography files.
character(len=500), dimension(6), public orog_files_target_grid = 'NULL'
Target grid orography files.
logical, dimension(:), allocatable, public read_from_input
When false, variable was not read from GRIB2 input file.
real, dimension(:), allocatable, public refsmc_input
Reference soil moisture content input grid (onset of soil moisture stress).
real, dimension(:), allocatable, public refsmc_target
Reference soil moisture content target grid (onset of soil moisture stress).
integer, public regional = 0
For regional target grids.
real, dimension(:), allocatable, public satpsi_target
Saturated soil potential, target grid.
character(len=500), dimension(6), public sfc_files_input_grid = 'NULL'
File names containing input surface data.
logical, public sotyp_from_climo = .true.
If false, interpolate soil type from the input data to the target grid instead of using data from static data.
logical, public tg3_from_soil = .false.
If false, use lowest level soil temperature for the base soil temperature instead of using data from static data.
character(len=500), public thomp_mp_climo_file = 'NULL'
Path/name to the Thompson MP climatology file.
character(len=20), dimension(max_tracers), public tracers ='NULL'
Name of each atmos tracer to be processed.
character(len=20), dimension(max_tracers), public tracers_input ='NULL'
Name of each atmos tracer record in the input file.
logical, public use_thomp_mp_climo =.false.
When true, read and process Thompson MP climatological tracers.
character(len=500), public varmap_file = 'NULL'
REQUIRED.
character(len=500), public vcoord_file_target_grid = 'NULL'
Vertical coordinate definition file.
logical, public vgfrc_from_climo = .true.
If false, interpolate vegetation fraction from the input data to the target grid instead of using data from static data.
logical, public vgtyp_from_climo = .true.
If false, interpolate vegetation type from the input data to the target grid instead of using data from static data.
logical, public wam_cold_start = .false.
When true, cold start for whole atmosphere model.
real, dimension(:), allocatable, public wltsmc_input
Plant wilting point soil moisture content input grid.
real, dimension(:), allocatable, public wltsmc_target
Plant wilting point soil moisture content target grid.
Detailed Description
This module contains code to read the setup namelist file, handle the varmap file for GRIB2 data, and calculate the soil parameters.
Author:
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine program_setup::calc_soil_params (integer, intent(in) num_soil_cats, real, intent(in) smlow, real, intent(in) smhigh, real, dimension(num_soil_cats), intent(in) satdk, real, dimension(num_soil_cats), intent(in) maxsmc, real, dimension(num_soil_cats), intent(in) bb, real, dimension(num_soil_cats), intent(in) satpsi, real, dimension(num_soil_cats), intent(out) satdw, real, dimension(num_soil_cats), intent(out) refsmc, real, dimension(num_soil_cats), intent(out) drysmc, real, dimension(num_soil_cats), intent(out) wltsmc) [private]
Compute soil parameters. These will be used to rescale soil moisture differences in soil type between the input grid and target model grid.
Parameters:
num_soil_cats number of soil type categories
smlow reference parameter for wltsmc
smhigh reference parameter for refsmc
satdk saturated soil moisture hydraulic conductivity
maxsmc maximum soil moisture (porosity)
bb soil 'b' parameter
satpsi saturated soil potential
satdw saturated soil diffusivity/conductivity coefficient
refsmc onset of soil moisture stress (field capacity)
drysmc air dry soil moisture limit
wltsmc plant soil moisture wilting point
Author:
George Gayno NCEP/EMC
Definition at line 677 of file program_setup.F90.
Referenced by calc_soil_params_driver().
subroutine, public program_setup::calc_soil_params_driver (integer, intent(in) localpet)
Driver routine to compute soil parameters for each soil type. Works for Zobler and STATSGO soil categories.
The calculations are those used in the Noah Land Surface Model. For more information see Implementation of Noah land surface model advances in the National Centers for Environmental Prediction operational mesoscale Eta model.
For more details about the soil parameters/properties see Coupling an Advanced Land Surface–Hydrology Model with the Penn State–NCAR MM5 Modeling System. Part I: Model Implementation and Sensitivity.
The original source for soil properties is here:
Cosby, B. J., G. M. Hornberger, R. B. Clapp, and T. R. Ginn, 1984: A statistical exploration of the relationships of soil moisture characteristics to the physical properties of soils. Water Resour. Res.,20, 682–690.
The parameters in this subroutine were copied from https://github.com/HelinWei-NOAA/ccpp-physics/blob/master/physics/set_soilveg.f values need to be kept in sync with set_soilveg.f.
For more information about these parameters see https://github.com/HelinWei-NOAA/ccpp-physics/blob/master/physics/sflx.f.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 516 of file program_setup.F90.
References bb_target, calc_soil_params(), drysmc_input, drysmc_target, input_type, maxsmc_input, maxsmc_target, refsmc_input, refsmc_target, satpsi_target, wltsmc_input, and wltsmc_target.
Referenced by surface::surface_driver().
subroutine, public program_setup::get_var_cond (character(len=20), intent(in) var_name, character(len=20), intent(out), optional this_miss_var_method, real(esmf_kind_r4), intent(out), optional this_miss_var_value, character(len=20), intent(out), optional this_field_var_name, integer, intent(out), optional loc)
Search the variable mapping table to find conditions for handling missing variables. Only applicable when using GRIB2 data as input.
Parameters:
var_name table variable name to search for
this_miss_var_method the method used to replace missing data
this_miss_var_value the value used to replace missing data
this_field_var_name name of variable in output file. not currently implemented.
loc variable table location index
Author:
Larissa Reames
Jeff Beck
Definition at line 445 of file program_setup.F90.
References chgres_var_names, field_var_names, missing_var_methods, and missing_var_values.
Referenced by input_data::read_grib_soil(), input_data::read_input_atm_grib2_file(), and input_data::read_winds().
subroutine, public program_setup::read_setup_namelist (character(len=*), intent(in), optional filename)
Reads program configuration namelist.
Parameters:
filename the name of the configuration file (defaults to ./fort.41).
Author:
George Gayno NCEP/EMC
Definition at line 151 of file program_setup.F90.
References atm_core_files_input_grid, atm_files_input_grid, atm_tracer_files_input_grid, atm_weight_file, convert_atm, convert_nst, convert_sfc, cres_target_grid, cycle_day, cycle_hour, cycle_mon, cycle_year, data_dir_input_grid, error_handler(), external_model, fix_dir_target_grid, geogrid_file_input_grid, grib2_file_input_grid, halo_blend, halo_bndy, input_type, lai_from_climo, max_tracers, minmax_vgfrc_from_climo, mosaic_file_input_grid, mosaic_file_target_grid, nsoill_out, nst_files_input_grid, num_tracers, num_tracers_input, orog_dir_input_grid, orog_dir_target_grid, orog_files_input_grid, orog_files_target_grid, regional, sfc_files_input_grid, sotyp_from_climo, tg3_from_soil, thomp_mp_climo_file, to_lower(), tracers, tracers_input, use_thomp_mp_climo, varmap_file, vcoord_file_target_grid, vgfrc_from_climo, vgtyp_from_climo, and wam_cold_start.
Referenced by chgres().
subroutine, public program_setup::read_varmap ()
Reads the variable mapping table, which is required for initializing with GRIB2 data. The varmap files has entries that look like this:
dzdt dzdt set_to_fill 0 D
These are the chgres_var_name, field_var_name, missing_var_method, missing_var_value, var_type.
The missing_var_method is one of:
set_to_fill
skip
stop
The var_type is one of:
T - tracer.
D - variables processed by atmosphere subroutine that are not tracers.
S - variables processed by surface subroutine that are not tracers.
Author:
Larissa Reames
Jeff Beck
Definition at line 374 of file program_setup.F90.
References chgres_var_names, error_handler(), field_var_names, input_type, missing_var_methods, missing_var_values, num_tracers, num_tracers_input, read_from_input, thomp_mp_climo_file, tracers_input, and varmap_file.
Referenced by chgres().
Variable Documentation
character(len=500), dimension(7), public program_setup::atm_core_files_input_grid = 'NULL'
File names of input atmospheric restart core files. Only used for 'restart' input type.
Definition at line 20 of file program_setup.F90.
Referenced by input_data::read_input_atm_restart_file(), and read_setup_namelist().
character(len=500), dimension(6), public program_setup::atm_files_input_grid = 'NULL'
File names of input atmospheric data. Not used for 'grib2' or 'restart' input types.
Definition at line 16 of file program_setup.F90.
Referenced by model_grid::define_input_grid_gaussian(), input_data::read_input_atm_gaussian_nemsio_file(), input_data::read_input_atm_gaussian_netcdf_file(), input_data::read_input_atm_gfs_gaussian_nemsio_file(), input_data::read_input_atm_gfs_sigio_file(), input_data::read_input_atm_tiled_history_file(), and read_setup_namelist().
character(len=500), dimension(6), public program_setup::atm_tracer_files_input_grid = 'NULL'
File names of input atmospheric restart tracer files. Only used for 'restart' input type.
Definition at line 21 of file program_setup.F90.
Referenced by input_data::read_input_atm_restart_file(), and read_setup_namelist().
character(len=500), public program_setup::atm_weight_file ='NULL'
File containing pre-computed weights to horizontally interpolate atmospheric fields.
Definition at line 39 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), and read_setup_namelist().
real, dimension(:), allocatable, public program_setup::bb_target
Soil 'b' parameter, target grid.
Definition at line 132 of file program_setup.F90.
Referenced by surface::calc_liq_soil_moisture(), and calc_soil_params_driver().
character(len=20), dimension(:), allocatable, public program_setup::chgres_var_names
Varmap table variable name as recognized by this program.
Definition at line 76 of file program_setup.F90.
Referenced by get_var_cond(), and read_varmap().
logical, public program_setup::convert_atm = .false.
Convert atmospheric data when true.
Definition at line 91 of file program_setup.F90.
Referenced by chgres(), model_grid::define_input_grid_gaussian(), and read_setup_namelist().
logical, public program_setup::convert_nst = .false.
Convert nst data when true.
Definition at line 92 of file program_setup.F90.
Referenced by input_data::cleanup_input_sfc_data(), surface::interp(), read_setup_namelist(), surface::regrid_many(), surface::surface_driver(), and write_data::write_fv3_sfc_data_netcdf().
logical, public program_setup::convert_sfc = .false.
Convert sfc data when true.
Definition at line 93 of file program_setup.F90.
Referenced by chgres(), model_grid::define_input_grid_gaussian(), and read_setup_namelist().
character(len=6), public program_setup::cres_target_grid = 'NULL'
Target grid resolution, i.e., C768.
Definition at line 38 of file program_setup.F90.
Referenced by read_setup_namelist(), and static_data::read_static_file().
integer, public program_setup::cycle_day = -999
Cycle day.
Definition at line 83 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), read_setup_namelist(), static_data::read_static_file(), and thompson_mp_climo_data::read_thomp_mp_climo_data().
integer, public program_setup::cycle_hour = -999
Cycle hour.
Definition at line 84 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), read_setup_namelist(), static_data::read_static_file(), and thompson_mp_climo_data::read_thomp_mp_climo_data().
integer, public program_setup::cycle_mon = -999
Cycle month.
Definition at line 82 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), read_setup_namelist(), static_data::read_static_file(), and thompson_mp_climo_data::read_thomp_mp_climo_data().
integer, public program_setup::cycle_year = -999
Cycle year.
Definition at line 81 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), and read_setup_namelist().
character(len=500), public program_setup::data_dir_input_grid = 'NULL'
Directory containing input atm or sfc files.
Definition at line 22 of file program_setup.F90.
Referenced by model_grid::define_input_grid_gaussian(), model_grid::define_input_grid_grib2(), input_data::READ_FV3_GRID_DATA_NETCDF(), input_data::read_input_atm_gaussian_nemsio_file(), input_data::read_input_atm_gaussian_netcdf_file(), input_data::read_input_atm_gfs_gaussian_nemsio_file(), input_data::read_input_atm_gfs_sigio_file(), input_data::read_input_atm_grib2_file(), input_data::read_input_atm_restart_file(), input_data::read_input_atm_tiled_history_file(), input_data::read_input_nst_nemsio_file(), input_data::read_input_sfc_gaussian_nemsio_file(), input_data::read_input_sfc_gfs_gaussian_nemsio_file(), input_data::read_input_sfc_gfs_sfcio_file(), input_data::read_input_sfc_netcdf_file(), input_data::read_input_sfc_restart_file(), and read_setup_namelist().
real, dimension(:), allocatable, public program_setup::drysmc_input
Air dry soil moisture content input grid.
Definition at line 124 of file program_setup.F90.
Referenced by calc_soil_params_driver(), and surface::rescale_soil_moisture().
real, dimension(:), allocatable, public program_setup::drysmc_target
Air dry soil moisture content target grid.
Definition at line 125 of file program_setup.F90.
Referenced by calc_soil_params_driver(), and surface::rescale_soil_moisture().
character(len=20), public program_setup::external_model ='GFS'
The model that the input data is derived from. Current supported options are: 'GFS', 'HRRR', 'NAM', 'RAP'. Default: 'GFS'
Definition at line 54 of file program_setup.F90.
Referenced by input_data::read_input_atm_grib2_file(), read_setup_namelist(), and surface::search_many().
character(len=20), dimension(:), allocatable, public program_setup::field_var_names
The GRIB2 variable name in the varmap table.
Definition at line 78 of file program_setup.F90.
Referenced by get_var_cond(), and read_varmap().
character(len=500), public program_setup::fix_dir_target_grid = 'NULL'
Directory containing target grid pre-computed fixed data (ex: soil type).
Definition at line 23 of file program_setup.F90.
Referenced by read_setup_namelist(), and static_data::read_static_file().
character(len=500), public program_setup::geogrid_file_input_grid = 'NULL'
Name of 'geogrid' file, which contains static surface fields on the input grid. GRIB2 option only.
Definition at line 28 of file program_setup.F90.
Referenced by read_setup_namelist().
character(len=500), public program_setup::grib2_file_input_grid = 'NULL'
REQUIRED. File name of grib2 input data. Assumes atmospheric and surface data are in a single file.
Definition at line 27 of file program_setup.F90.
Referenced by model_grid::define_input_grid_grib2(), input_data::read_input_atm_grib2_file(), and read_setup_namelist().
integer, public program_setup::halo_blend = 0
Number of row/cols of blending halo, where model tendencies and lateral boundary tendencies are applied. Regional target grids only.
Definition at line 88 of file program_setup.F90.
Referenced by read_setup_namelist(), and write_data::write_fv3_atm_bndy_data_netcdf().
integer, public program_setup::halo_bndy = 0
Number of row/cols of lateral halo, where pure lateral bndy conditions are applied (regional target grids).
Definition at line 87 of file program_setup.F90.
Referenced by read_setup_namelist(), write_data::write_fv3_atm_bndy_data_netcdf(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_sfc_data_netcdf().
character(len=25), public program_setup::input_type ='restart'
Input data type:
'restart' for fv3 tiled warm restart files (netcdf).
'history' for fv3 tiled history files (netcdf).
'gaussian_nemsio' for fv3 gaussian nemsio files;
'gaussian_netcdf' for fv3 gaussian netcdf files.
'grib2' for grib2 files.
'gfs_gaussian_nemsio' for spectral gfs gaussian nemsio files
'gfs_sigio' for spectral gfs gfs sigio/sfcio files.
Definition at line 40 of file program_setup.F90.
Referenced by calc_soil_params_driver(), model_grid::define_input_grid(), model_grid::define_input_grid_gaussian(), input_data::read_input_atm_data(), input_data::read_input_nst_data(), input_data::read_input_nst_nemsio_file(), input_data::read_input_nst_netcdf_file(), input_data::read_input_sfc_data(), input_data::read_input_sfc_netcdf_file(), read_setup_namelist(), read_varmap(), surface::search_many(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
logical, public program_setup::lai_from_climo = .true.
If false, interpolate leaf area index from the input data to the target grid instead of using data from static data. Default: True.
Definition at line 116 of file program_setup.F90.
Referenced by input_data::cleanup_input_sfc_data(), input_data::init_sfc_esmf_fields(), surface::interp(), read_setup_namelist(), and write_data::write_fv3_sfc_data_netcdf().
integer, parameter, public program_setup::max_tracers =100
Maximum number of atmospheric tracers processed.
Definition at line 56 of file program_setup.F90.
Referenced by read_setup_namelist().
real, dimension(:), allocatable, public program_setup::maxsmc_input
Maximum soil moisture content input grid.
Definition at line 126 of file program_setup.F90.
Referenced by calc_soil_params_driver(), and surface::rescale_soil_moisture().
real, dimension(:), allocatable, public program_setup::maxsmc_target
Maximum soil moisture content target grid.
Definition at line 127 of file program_setup.F90.
Referenced by surface::calc_liq_soil_moisture(), calc_soil_params_driver(), and surface::rescale_soil_moisture().
logical, public program_setup::minmax_vgfrc_from_climo = .true.
If false, interpolate min/max vegetation fraction from the input data to the target grid instead of using data from static data. Use with caution as vegetation categories can vary. Default: True.
Definition at line 112 of file program_setup.F90.
Referenced by input_data::cleanup_input_sfc_data(), input_data::init_sfc_esmf_fields(), surface::interp(), and read_setup_namelist().
character(len=20), dimension(:), allocatable, public program_setup::missing_var_methods
Method to replace missing GRIB2 input records.
Definition at line 74 of file program_setup.F90.
Referenced by get_var_cond(), and read_varmap().
real, dimension(:), allocatable, public program_setup::missing_var_values
If input GRIB2 record is missing, the variable is set to this value.
Definition at line 134 of file program_setup.F90.
Referenced by get_var_cond(), and read_varmap().
character(len=500), public program_setup::mosaic_file_input_grid = 'NULL'
Input grid mosaic file. Only used for 'restart' or 'history' input type.
Definition at line 24 of file program_setup.F90.
Referenced by model_grid::define_input_grid_mosaic(), and read_setup_namelist().
character(len=500), public program_setup::mosaic_file_target_grid = 'NULL'
Target grid mosaic file.
Definition at line 25 of file program_setup.F90.
Referenced by model_grid::define_target_grid(), and read_setup_namelist().
integer, public program_setup::nsoill_out = 4
Number of soil levels desired in the output data. chgres_cube can interpolate from 9 input to 4 output levels. DEFAULT: 4.
Definition at line 89 of file program_setup.F90.
Referenced by model_grid::define_target_grid(), and read_setup_namelist().
character(len=500), public program_setup::nst_files_input_grid = 'NULL'
File name of input nst data. Only used for input_type 'gfs_gaussian_nemsio'.
Definition at line 26 of file program_setup.F90.
Referenced by input_data::read_input_nst_nemsio_file(), and read_setup_namelist().
integer, public program_setup::num_tracers
Number of atmospheric tracers to be processed.
Definition at line 57 of file program_setup.F90.
Referenced by atmosphere_target_data::cleanup_atmosphere_target_data(), atmosphere::compute_zh(), atmosphere::create_atm_esmf_fields(), atmosphere::newps(), read_setup_namelist(), read_varmap(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_atm_header_netcdf().
integer, public program_setup::num_tracers_input
Number of atmospheric tracers in input file.
Definition at line 58 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), input_data::cleanup_input_atm_data(), atmosphere::cleanup_target_atm_b4adj_data(), atmosphere::create_atm_b4adj_esmf_fields(), input_data::init_atm_esmf_fields(), input_data::read_input_atm_gaussian_nemsio_file(), input_data::read_input_atm_gaussian_netcdf_file(), input_data::read_input_atm_gfs_gaussian_nemsio_file(), input_data::read_input_atm_gfs_sigio_file(), input_data::read_input_atm_restart_file(), input_data::read_input_atm_tiled_history_file(), read_setup_namelist(), read_varmap(), and atmosphere::VINTG().
character(len=500), public program_setup::orog_dir_input_grid = 'NULL'
Directory containing the input grid orography files. Only used for 'restart' or 'history' input types.
Definition at line 31 of file program_setup.F90.
Referenced by model_grid::define_input_grid_mosaic(), input_data::read_input_sfc_netcdf_file(), input_data::read_input_sfc_restart_file(), and read_setup_namelist().
character(len=500), public program_setup::orog_dir_target_grid = 'NULL'
Directory containing the target grid orography files.
Definition at line 33 of file program_setup.F90.
Referenced by model_grid::define_target_grid(), and read_setup_namelist().
character(len=500), dimension(6), public program_setup::orog_files_input_grid = 'NULL'
Input grid orography files. Only used for 'restart' or 'history' input types.
Definition at line 32 of file program_setup.F90.
Referenced by model_grid::define_input_grid_mosaic(), input_data::read_input_sfc_netcdf_file(), input_data::read_input_sfc_restart_file(), and read_setup_namelist().
character(len=500), dimension(6), public program_setup::orog_files_target_grid = 'NULL'
Target grid orography files.
Definition at line 34 of file program_setup.F90.
Referenced by model_grid::define_target_grid(), and read_setup_namelist().
logical, dimension(:), allocatable, public program_setup::read_from_input
When false, variable was not read from GRIB2 input file.
Definition at line 60 of file program_setup.F90.
Referenced by input_data::handle_grib_error(), and read_varmap().
real, dimension(:), allocatable, public program_setup::refsmc_input
Reference soil moisture content input grid (onset of soil moisture stress).
Definition at line 128 of file program_setup.F90.
Referenced by calc_soil_params_driver(), and surface::rescale_soil_moisture().
real, dimension(:), allocatable, public program_setup::refsmc_target
Reference soil moisture content target grid (onset of soil moisture stress).
Definition at line 129 of file program_setup.F90.
Referenced by calc_soil_params_driver(), and surface::rescale_soil_moisture().
integer, public program_setup::regional = 0
For regional target grids. When '1' remove boundary halo region from atmospheric/surface data and output atmospheric boundary file. When '2' output boundary file only. Default is '0' (global grids).
Definition at line 85 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), read_setup_namelist(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_sfc_data_netcdf().
real, dimension(:), allocatable, public program_setup::satpsi_target
Saturated soil potential, target grid.
Definition at line 133 of file program_setup.F90.
Referenced by surface::calc_liq_soil_moisture(), and calc_soil_params_driver().
character(len=500), dimension(6), public program_setup::sfc_files_input_grid = 'NULL'
File names containing input surface data. Not used for 'grib2' input type.
Definition at line 35 of file program_setup.F90.
Referenced by model_grid::define_input_grid_gaussian(), input_data::READ_FV3_GRID_DATA_NETCDF(), input_data::read_input_nst_nemsio_file(), input_data::read_input_sfc_gaussian_nemsio_file(), input_data::read_input_sfc_gfs_gaussian_nemsio_file(), input_data::read_input_sfc_gfs_sfcio_file(), input_data::read_input_sfc_netcdf_file(), input_data::read_input_sfc_restart_file(), and read_setup_namelist().
logical, public program_setup::sotyp_from_climo = .true.
If false, interpolate soil type from the input data to the target grid instead of using data from static data. Use with caution as the code assumes input soil type use STATSGO soil categories. Default: True.
Definition at line 102 of file program_setup.F90.
Referenced by surface::interp(), input_data::read_input_sfc_grib2_file(), and read_setup_namelist().
logical, public program_setup::tg3_from_soil = .false.
If false, use lowest level soil temperature for the base soil temperature instead of using data from static data. Default: False.
Definition at line 119 of file program_setup.F90.
Referenced by surface::interp(), and read_setup_namelist().
character(len=500), public program_setup::thomp_mp_climo_file = 'NULL'
Path/name to the Thompson MP climatology file.
Definition at line 37 of file program_setup.F90.
Referenced by read_setup_namelist(), thompson_mp_climo_data::read_thomp_mp_climo_data(), and read_varmap().
character(len=20), dimension(max_tracers), public program_setup::tracers ='NULL'
Name of each atmos tracer to be processed. These names will be used to identify the tracer records in the output files. Follows the convention in the field table. FOR GRIB2 FILES: Not used. Tracers instead taken from the varmap file.
Definition at line 63 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), atmosphere::compute_zh(), atmosphere::create_atm_b4adj_esmf_fields(), atmosphere::create_atm_esmf_fields(), atmosphere::newps(), input_data::read_input_atm_grib2_file(), read_setup_namelist(), atmosphere::VINTG(), atmosphere::VINTG_WAM(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
character(len=20), dimension(max_tracers), public program_setup::tracers_input ='NULL'
Name of each atmos tracer record in the input file. May be different from value in 'tracers'. FOR GRIB2 FILES: Not used. Tracers instead taken from the varmap file.
Definition at line 69 of file program_setup.F90.
Referenced by input_data::init_atm_esmf_fields(), input_data::read_input_atm_gaussian_nemsio_file(), input_data::read_input_atm_gaussian_netcdf_file(), input_data::read_input_atm_gfs_gaussian_nemsio_file(), input_data::read_input_atm_gfs_sigio_file(), input_data::read_input_atm_grib2_file(), input_data::read_input_atm_restart_file(), input_data::read_input_atm_tiled_history_file(), read_setup_namelist(), and read_varmap().
logical, public program_setup::use_thomp_mp_climo =.false.
When true, read and process Thompson MP climatological tracers. False, when 'thomp_mp_climo_file' is NULL.
Definition at line 122 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), read_setup_namelist(), write_data::write_fv3_atm_bndy_data_netcdf(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_atm_header_netcdf().
character(len=500), public program_setup::varmap_file = 'NULL'
REQUIRED. Full path of the relevant varmap file.
Definition at line 15 of file program_setup.F90.
Referenced by read_setup_namelist(), and read_varmap().
character(len=500), public program_setup::vcoord_file_target_grid = 'NULL'
Vertical coordinate definition file.
Definition at line 36 of file program_setup.F90.
Referenced by read_setup_namelist(), and atmosphere::read_vcoord_info().
logical, public program_setup::vgfrc_from_climo = .true.
If false, interpolate vegetation fraction from the input data to the target grid instead of using data from static data. Use with caution as vegetation categories can vary. Default: True.
Definition at line 107 of file program_setup.F90.
Referenced by input_data::cleanup_input_sfc_data(), input_data::init_sfc_esmf_fields(), surface::interp(), and read_setup_namelist().
logical, public program_setup::vgtyp_from_climo = .true.
If false, interpolate vegetation type from the input data to the target grid instead of using data from static data. Use with caution as vegetation categories can vary. Default: True.
Definition at line 98 of file program_setup.F90.
Referenced by surface::interp(), input_data::read_input_sfc_grib2_file(), and read_setup_namelist().
logical, public program_setup::wam_cold_start = .false.
When true, cold start for whole atmosphere model.
Definition at line 94 of file program_setup.F90.
Referenced by atmosphere::atmosphere_driver(), and read_setup_namelist().
real, dimension(:), allocatable, public program_setup::wltsmc_input
Plant wilting point soil moisture content input grid.
Definition at line 130 of file program_setup.F90.
Referenced by calc_soil_params_driver(), and surface::rescale_soil_moisture().
real, dimension(:), allocatable, public program_setup::wltsmc_target
Plant wilting point soil moisture content target grid.
Definition at line 131 of file program_setup.F90.
Referenced by calc_soil_params_driver(), and surface::rescale_soil_moisture().
Author
Generated automatically by Doxygen for chgres_cube from the source code.