thompson_mp_climo_data
NAME
thompson_mp_climo_data - Module to read the Thompson climatological MP data file and set up the associated esmf field and grid objects.
SYNOPSIS
Functions/Subroutines
subroutine, public cleanup_thomp_mp_climo_input_data
Free up memory associated with this module.
subroutine, public read_thomp_mp_climo_data
Read Thompson climatological MP data file and time interpolate data to current cycle time.
Variables
integer i_thomp_mp_climo
i-dimension of Thompson climo data
integer j_thomp_mp_climo
j-dimension of Thompson climo data
integer, public lev_thomp_mp_climo
number of vert lvls of Thompson climo data
type(esmf_field), public qnifa_climo_input_grid
number concentration of ice friendly nuclei.
type(esmf_field), public qnwfa_climo_input_grid
number concentration of water friendly nuclei.
type(esmf_grid) thomp_mp_climo_grid
esmf grid object for Thompson data grid
type(esmf_field), public thomp_pres_climo_input_grid
3-d pressure of the Thompson climo data points
Detailed Description
Module to read the Thompson climatological MP data file and set up the associated esmf field and grid objects.
Author:
George Gayno NOAA/EMC
Function/Subroutine Documentation
subroutine, public thompson_mp_climo_data::cleanup_thomp_mp_climo_input_data ()
Free up memory associated with this module.
Author:
George Gayno NOAA/EMC
Definition at line 328 of file thompson_mp_climo_data.F90.
References qnifa_climo_input_grid, qnwfa_climo_input_grid, thomp_mp_climo_grid, and thomp_pres_climo_input_grid.
Referenced by atmosphere::horiz_interp_thomp_mp_climo().
subroutine, public thompson_mp_climo_data::read_thomp_mp_climo_data ()
Read Thompson climatological MP data file and time interpolate data to current cycle time.
Author:
George Gayno NOAA/EMC
Definition at line 50 of file thompson_mp_climo_data.F90.
References program_setup::cycle_day, program_setup::cycle_hour, program_setup::cycle_mon, error_handler(), i_thomp_mp_climo, j_thomp_mp_climo, lev_thomp_mp_climo, netcdf_err(), qnifa_climo_input_grid, qnwfa_climo_input_grid, program_setup::thomp_mp_climo_file, thomp_mp_climo_grid, and thomp_pres_climo_input_grid.
Referenced by atmosphere::atmosphere_driver().
Variable Documentation
integer thompson_mp_climo_data::i_thomp_mp_climo [private]
i-dimension of Thompson climo data
Definition at line 20 of file thompson_mp_climo_data.F90.
Referenced by read_thomp_mp_climo_data().
integer thompson_mp_climo_data::j_thomp_mp_climo [private]
j-dimension of Thompson climo data
Definition at line 22 of file thompson_mp_climo_data.F90.
Referenced by read_thomp_mp_climo_data().
integer, public thompson_mp_climo_data::lev_thomp_mp_climo
number of vert lvls of Thompson climo data
Definition at line 24 of file thompson_mp_climo_data.F90.
Referenced by atmosphere::horiz_interp_thomp_mp_climo(), read_thomp_mp_climo_data(), and atmosphere::VINTG_THOMP_MP_CLIMO().
type(esmf_field), public thompson_mp_climo_data::qnifa_climo_input_grid
number concentration of ice friendly nuclei.
Definition at line 30 of file thompson_mp_climo_data.F90.
Referenced by cleanup_thomp_mp_climo_input_data(), atmosphere::horiz_interp_thomp_mp_climo(), and read_thomp_mp_climo_data().
type(esmf_field), public thompson_mp_climo_data::qnwfa_climo_input_grid
number concentration of water friendly nuclei.
Definition at line 33 of file thompson_mp_climo_data.F90.
Referenced by cleanup_thomp_mp_climo_input_data(), atmosphere::horiz_interp_thomp_mp_climo(), and read_thomp_mp_climo_data().
type(esmf_grid) thompson_mp_climo_data::thomp_mp_climo_grid [private]
esmf grid object for Thompson data grid
Definition at line 27 of file thompson_mp_climo_data.F90.
Referenced by cleanup_thomp_mp_climo_input_data(), and read_thomp_mp_climo_data().
type(esmf_field), public thompson_mp_climo_data::thomp_pres_climo_input_grid
3-d pressure of the Thompson climo data points
Definition at line 36 of file thompson_mp_climo_data.F90.
Referenced by cleanup_thomp_mp_climo_input_data(), atmosphere::horiz_interp_thomp_mp_climo(), and read_thomp_mp_climo_data().
Author
Generated automatically by Doxygen for chgres_cube from the source code.