.TH "/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/global_equiv_resol.fd Directory Reference" 3 "Mon May 2 2022" "Version 1.5.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/global_equiv_resol.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBglobal_equiv_resol\&.f90\fP"
.br
.RI "\fICompute the global equivalent resolution for regional grids\&. \fP"
.in -1c
