.TH "pfun::atanh" 3 "Version 1.14.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::atanh
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBatanh_d\fP (t)"
.br
.RI "Hyperbolic arc-tangent for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBatanh_s\fP (t)"
.br
.RI "Hyperbolic arc-tangent for single precision real\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB25\fP of file \fBpfun\&.f90\fP\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::atanh::atanh_d (real(dp), intent(in) t)"

.PP
Hyperbolic arc-tangent for double precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP double precision real argument 
.RE
.PP
\fBReturns\fP
.RS 4
a hyperbolic arc-tangent of t 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line \fB215\fP of file \fBpfun\&.f90\fP\&.
.PP
References \fBpietc::o2\fP, \fBpietc::o3\fP, \fBpietc::o5\fP, \fBpietc::t\fP, and \fBpietc::u1\fP\&.
.SS "real(sp) function pfun::atanh::atanh_s (real(sp), intent(in) t)"

.PP
Hyperbolic arc-tangent for single precision real\&. (compilers now have this)
.PP
\fBParameters\fP
.RS 4
\fIt\fP single precision real argument 
.RE
.PP
\fBReturns\fP
.RS 4
a hyperbolic arc-tangent of t 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line \fB197\fP of file \fBpfun\&.f90\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
