.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/bulk_snow_module.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "noah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/bulk_snow_module.f90 \- 
Routines to make DA updates to a bulk (single layer) snow model such as that in Noah\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBbulk_snow_module\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Routines to make DA updates to a bulk (single layer) snow model such as that in Noah\&. 


.PP
\fBAuthor:\fP
.RS 4
Clara Draper 
.RE
.PP

.PP
Definition in file \fBbulk_snow_module\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for noah from the source code\&.
