.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/sflx_snippet.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "noah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/sflx_snippet.f90 \- 
.PP
Snippets of noah model from sflx\&.F needed for land DA updates\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBsflx_snippet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Snippets of noah model from sflx\&.F needed for land DA updates\&. 


.PP
\fBAuthor:\fP
.RS 4
Clara Draper 
.RE
.PP

.PP
Definition in file \fBsflx_snippet\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for noah from the source code\&.
