.TH "md__2scratch4_2NCEPDEV_2nems_2Brian_8Curtis_2git_2BrianCurtis-NOAA_2UFS__UTILS_2v1__14__0_2sorc_2emcsfc__ice__blend_8fd_2docs_2README" 3 "Version 1.14.0" "emcsfc_ice_blend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2scratch4_2NCEPDEV_2nems_2Brian_8Curtis_2git_2BrianCurtis-NOAA_2UFS__UTILS_2v1__14__0_2sorc_2emcsfc__ice__blend_8fd_2docs_2README \- README 
.PP
This program blends National Ice Center sea ice cover and EMC sea ice concentration data to create a global sea ice analysis\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
