surface_target_data
NAME
surface_target_data - Module to hold ESMF fields associated with the target grid surface data.
SYNOPSIS
Functions/Subroutines
subroutine, public cleanup_target_nst_data
Free up memory once the target grid nst fields are no longer needed.
subroutine, public cleanup_target_sfc_data
Free up memory once the target grid surface fields are no longer needed.
Variables
type(esmf_field), public c_0_target_grid
Coefficient 1 to calculate d(tz)/d(ts).
type(esmf_field), public c_d_target_grid
Coefficient 2 to calculate d(tz)/d(ts).
type(esmf_field), public canopy_mc_target_grid
Canopy moisture content.
type(esmf_field), public d_conv_target_grid
Thickness of free convection layer.
type(esmf_field), public dt_cool_target_grid
Sub-layer cooling amount.
type(esmf_field), public f10m_target_grid
log((z0+10)*1/z0) See sfc_diff.f for details.
type(esmf_field), public ffmm_target_grid
log((z0+z1)*1/z0) See sfc_diff.f for details.
type(esmf_field), public ifd_target_grid
Model mode index.
type(esmf_field), public lai_target_grid
Leaf area index.
type(esmf_field), public q2m_target_grid
2-m specific humidity.
type(esmf_field), public qrain_target_grid
Sensible heat flux due to rainfall.
type(esmf_field), public seaice_depth_target_grid
Sea ice depth.
type(esmf_field), public seaice_fract_target_grid
Sea ice fraction.
type(esmf_field), public seaice_skin_temp_target_grid
Sea ice skin temperature.
type(esmf_field), public skin_temp_target_grid
Skin temperature/sst.
type(esmf_field), public snow_depth_target_grid
Physical snow depth.
type(esmf_field), public snow_liq_equiv_target_grid
Liquid equivalent snow depth.
type(esmf_field), public soil_temp_target_grid
3-d soil temperature.
type(esmf_field), public soilm_liq_target_grid
3-d liquid soil moisture.
type(esmf_field), public soilm_tot_target_grid
3-d total soil moisture.
type(esmf_field), public srflag_target_grid
Snow/rain flag.
type(esmf_field), public t2m_target_grid
2-m temperatrure.
type(esmf_field), public tprcp_target_grid
Precipitation.
type(esmf_field), public tref_target_grid
Reference temperature.
type(esmf_field), public ustar_target_grid
Friction velocity.
type(esmf_field), public w_0_target_grid
Coefficient 3 to calculate d(tz)/d(ts).
type(esmf_field), public w_d_target_grid
Coefficient 4 to calculate d(tz)/d(ts).
type(esmf_field), public xs_target_grid
Salinity content in diurnal thermocline layer.
type(esmf_field), public xt_target_grid
Heat content in diurnal thermocline layer.
type(esmf_field), public xtts_target_grid
d(xt)/d(ts).
type(esmf_field), public xu_target_grid
u-current content in diurnal thermocline layer.
type(esmf_field), public xv_target_grid
v-current content in diurnal thermocline layer.
type(esmf_field), public xz_target_grid
Diurnal thermocline layer thickness.
type(esmf_field), public xzts_target_grid
d(xz)/d(ts).
type(esmf_field), public z0_target_grid
Roughness length.
type(esmf_field), public z_c_target_grid
Sub-layer cooling thickness.
type(esmf_field), public zm_target_grid
Oceanic mixed layer depth.
Detailed Description
Module to hold ESMF fields associated with the target grid surface data.
Author:
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine, public surface_target_data::cleanup_target_nst_data ()
Free up memory once the target grid nst fields are no longer needed.
Author:
George Gayno NOAA/EMC
Definition at line 145 of file surface_target_data.F90.
References c_0_target_grid, c_d_target_grid, d_conv_target_grid, dt_cool_target_grid, ifd_target_grid, qrain_target_grid, tref_target_grid, w_0_target_grid, w_d_target_grid, xs_target_grid, xt_target_grid, xtts_target_grid, xu_target_grid, xv_target_grid, xz_target_grid, xzts_target_grid, z_c_target_grid, and zm_target_grid.
Referenced by surface::surface_driver().
subroutine, public surface_target_data::cleanup_target_sfc_data ()
Free up memory once the target grid surface fields are no longer needed.
Author:
George Gayno NOAA/EMC
Definition at line 112 of file surface_target_data.F90.
References canopy_mc_target_grid, f10m_target_grid, ffmm_target_grid, lai_target_grid, q2m_target_grid, seaice_depth_target_grid, seaice_fract_target_grid, seaice_skin_temp_target_grid, skin_temp_target_grid, snow_depth_target_grid, snow_liq_equiv_target_grid, soil_temp_target_grid, soilm_liq_target_grid, soilm_tot_target_grid, srflag_target_grid, t2m_target_grid, tprcp_target_grid, ustar_target_grid, and z0_target_grid.
Referenced by surface::cleanup_all_target_sfc_data().
Variable Documentation
type(esmf_field), public surface_target_data::c_0_target_grid
Coefficient 1 to calculate d(tz)/d(ts).
Definition at line 62 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::c_d_target_grid
Coefficient 2 to calculate d(tz)/d(ts).
Definition at line 60 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::canopy_mc_target_grid
Canopy moisture content.
Definition at line 18 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::d_conv_target_grid
Thickness of free convection layer.
Definition at line 64 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::dt_cool_target_grid
Sub-layer cooling amount.
Definition at line 66 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::f10m_target_grid
log((z0+10)*1/z0) See sfc_diff.f for details.
Definition at line 20 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::ffmm_target_grid
log((z0+z1)*1/z0) See sfc_diff.f for details.
Definition at line 23 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::ifd_target_grid
Model mode index. 0-diurnal model not started; 1-diurnal model started.
Definition at line 68 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), surface::regrid_many(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::lai_target_grid
Leaf area index.
Definition at line 56 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::q2m_target_grid
2-m specific humidity.
Definition at line 26 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::qrain_target_grid
Sensible heat flux due to rainfall.
Definition at line 71 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::seaice_depth_target_grid
Sea ice depth.
Definition at line 28 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::seaice_fract_target_grid
Sea ice fraction.
Definition at line 30 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::seaice_skin_temp_target_grid
Sea ice skin temperature.
Definition at line 32 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::skin_temp_target_grid
Skin temperature/sst.
Definition at line 34 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::nst_land_fill(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::snow_depth_target_grid
Physical snow depth.
Definition at line 40 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::snow_liq_equiv_target_grid
Liquid equivalent snow depth.
Definition at line 38 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::soil_temp_target_grid
3-d soil temperature.
Definition at line 42 of file surface_target_data.F90.
Referenced by surface::adjust_soilt_for_terrain(), surface::calc_liq_soil_moisture(), cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::soilm_liq_target_grid
3-d liquid soil moisture.
Definition at line 44 of file surface_target_data.F90.
Referenced by surface::calc_liq_soil_moisture(), cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::soilm_tot_target_grid
3-d total soil moisture.
Definition at line 46 of file surface_target_data.F90.
Referenced by surface::calc_liq_soil_moisture(), cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::qc_check(), surface::rescale_soil_moisture(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::srflag_target_grid
Snow/rain flag.
Definition at line 36 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::t2m_target_grid
2-m temperatrure.
Definition at line 48 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::tprcp_target_grid
Precipitation.
Definition at line 50 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::tref_target_grid
Reference temperature.
Definition at line 73 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::ustar_target_grid
Friction velocity.
Definition at line 52 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::w_0_target_grid
Coefficient 3 to calculate d(tz)/d(ts).
Definition at line 77 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::w_d_target_grid
Coefficient 4 to calculate d(tz)/d(ts).
Definition at line 75 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::xs_target_grid
Salinity content in diurnal thermocline layer.
Definition at line 79 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::xt_target_grid
Heat content in diurnal thermocline layer.
Definition at line 82 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::xtts_target_grid
d(xt)/d(ts).
Definition at line 93 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::xu_target_grid
u-current content in diurnal thermocline layer.
Definition at line 85 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::xv_target_grid
v-current content in diurnal thermocline layer.
Definition at line 88 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::xz_target_grid
Diurnal thermocline layer thickness.
Definition at line 91 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::xzts_target_grid
d(xz)/d(ts).
Definition at line 95 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::z0_target_grid
Roughness length.
Definition at line 54 of file surface_target_data.F90.
Referenced by cleanup_target_sfc_data(), surface::create_surface_esmf_fields(), surface::interp(), surface::roughness(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::z_c_target_grid
Sub-layer cooling thickness.
Definition at line 97 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public surface_target_data::zm_target_grid
Oceanic mixed layer depth.
Definition at line 99 of file surface_target_data.F90.
Referenced by cleanup_target_nst_data(), surface::create_nst_esmf_fields(), surface::interp(), surface::nst_land_fill(), and write_data::write_fv3_sfc_data_netcdf().
Author
Generated automatically by Doxygen for chgres_cube from the source code.