.TH "surface::realptr_3d" 3 "Tue Jan 17 2023" "Version 1.9.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
surface::realptr_3d
.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "real(esmf_kind_r8), dimension(:,:,:), pointer \fBp\fP"
.br
.RI "array of 3d pointers "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file surface\&.F90\&.
.SH "Field Documentation"
.PP 
.SS "real(esmf_kind_r8), dimension(:,:,:), pointer surface::realptr_3d::p\fC [private]\fP"

.PP
array of 3d pointers pointer to hold array of 3d pointers 
.PP
Definition at line 87 of file surface\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
