wam_gtd7bk_mod
NAME
wam_gtd7bk_mod - Use moduke for blockdata gtd7bk.
SYNOPSIS
Variables
integer imr
define version
character *4, dimension(3) isdate
define date
character *4, dimension(2) istime
define time
character *4, dimension(2) name
define data name
real, dimension(50) pa1
block space data for he denisity
real, dimension(50) pa2
block space data for he denisity
real, dimension(50) pa3
block space data for he denisity
real, dimension(50) paa1
block space data for semiannual mult sam
real, dimension(50) paa2
block space data for semiannual mult sam
real, dimension(10) pavgm
block space data for middle atmosphere averages
real, dimension(50) pb1
block space data for o density
real, dimension(50) pb2
block space data for o density
real, dimension(50) pb3
block space data for o density
real, dimension(50) pc1
block space data for n2 density
real, dimension(50) pc2
block space data for n2 density
real, dimension(50) pc3
block space data for n2 density
real, dimension(50) pd1
block space data for tlb
real, dimension(50) pd2
block space data for tlb
real, dimension(50) pd3
block space data for tlb
real, dimension(10, 8) pdm
block space data for lower boundary
real, dimension(50) pe1
block space data for o2 density
real, dimension(50) pe2
block space data for o2 density
real, dimension(50) pe3
block space data for o2 density
real, dimension(50) pf1
block space data for ar density
real, dimension(50) pf2
block space data for ar density
real, dimension(50) pf3
block space data for ar density
real, dimension(50) pg1
block space data for h density
real, dimension(50) pg2
block space data for h density
real, dimension(50) pg3
block space data for h density
real, dimension(50) ph1
block space data for n density
real, dimension(50) ph2
block space data for n density
real, dimension(50) ph3
block space data for n density
real, dimension(50) pi1
block space data for hot o density
real, dimension(50) pi2
block space data for hot o density
real, dimension(50) pi3
block space data for hot o density
real, dimension(50) pj1
block space data for s param
real, dimension(50) pj2
block space data for s param
real, dimension(50) pj3
block space data for s param
real, dimension(50) pk1
block space data for turbo
real, dimension(50) pl1
block space data for tn1(2)
real, dimension(50) pl2
block space data for tn1(2)
real, dimension(50) pm1
block space data for tn1(3)
real, dimension(50) pm2
block space data for tn1(3)
real, dimension(50) pn1
block space data for tn1(4)
real, dimension(50) pn2
block space data for tn1(4)
real, dimension(50) po1
block space data for tn1(5) tn2(1)
real, dimension(50) po2
block space data for tn1(5) tn2(1)
real, dimension(50) pp1
block space data for tn2(2)
real, dimension(50) pp2
block space data for tn2(2)
real, dimension(50) pq1
block space data for tn2(3)
real, dimension(50) pq2
block space data for tn2(3)
real, dimension(50) pr1
block space data for tn2(4) tn3(1)
real, dimension(2, 151) pr151
define pressures
real, dimension(50) pr2
block space data for tn2(4) tn3(1)
real, dimension(2, 65) pr65
define pressures
real, dimension(50) ps1
block space data for tn3(2)
real, dimension(50) ps2
block space data for tn3(2)
real, dimension(50) pt1
block space data for temperature
real, dimension(50) pt2
block space data for temperature
real, dimension(50) pt3
block space data for temperature
real, dimension(10) ptm
block space data for lower boundary
real, dimension(50) pu1
block space data for tn3(3)
real, dimension(50) pu2
block space data for tn3(3)
real, dimension(50) pv1
block space data for tn3(4)
real, dimension(50) pv2
block space data for tn3(4)
real, dimension(50) pw1
block space data for tn3(5) surface temperature tsl
real, dimension(50) pw2
block space data for tn3(5) surface temperature tsl
real, dimension(50) px1
block space data for tgn3(2) surface grad tslg
real, dimension(50) px2
block space data for tgn3(2) surface grad tslg
real, dimension(50) py1
block space data for tgn2(1) tgn1(2)
real, dimension(50) py2
block space data for tgn2(1) tgn1(2)
real, dimension(50) pz1
block space data for tgn3(1) tgn2(2)
real, dimension(50) pz2
block space data for tgn3(1) tgn2(2)
Detailed Description
Use moduke for blockdata gtd7bk.
All variables originalyl in blockdata used for this packahe are getting from NRLMSISE-00. NRLMSISE-00 is an empirical, global reference atmospheric model of the Earth from ground to space. It models the temperatures and densities of the atmosphere's components. NRL stands for the US Naval Research Laboratory. MSIS stands for mass spectrometer and incoherent scatter radar, the two primary data sources for development of earlier versions of the model. E indicates that the model extends from the ground through exosphere and 00 is the year of release in 2000. Over the years since introduction, NRLMSISE-00 has become the standard for international space research. (wikipedia)
Author:
Hann-Ming Henry Juang
Variable Documentation
integer wam_gtd7bk_mod::imr
define version
Definition at line 106 of file wam_climo_data.f90.
Referenced by ghp7(), gtd7(), gtd7d(), gts7(), and meters().
character*4, dimension(3) wam_gtd7bk_mod::isdate
define date
Definition at line 102 of file wam_climo_data.f90.
character*4, dimension(2) wam_gtd7bk_mod::istime
define time
Definition at line 103 of file wam_climo_data.f90.
character*4, dimension(2) wam_gtd7bk_mod::name
define data name
Definition at line 104 of file wam_climo_data.f90.
real, dimension(50) wam_gtd7bk_mod::pa1
block space data for he denisity
Definition at line 35 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pa2
block space data for he denisity
Definition at line 36 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pa3
block space data for he denisity
Definition at line 37 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::paa1
block space data for semiannual mult sam
Definition at line 94 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::paa2
block space data for semiannual mult sam
Definition at line 95 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(10) wam_gtd7bk_mod::pavgm
block space data for middle atmosphere averages
Definition at line 100 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pb1
block space data for o density
Definition at line 38 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pb2
block space data for o density
Definition at line 39 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pb3
block space data for o density
Definition at line 40 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pc1
block space data for n2 density
Definition at line 41 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pc2
block space data for n2 density
Definition at line 42 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pc3
block space data for n2 density
Definition at line 43 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pd1
block space data for tlb
Definition at line 44 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pd2
block space data for tlb
Definition at line 45 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pd3
block space data for tlb
Definition at line 46 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(10,8) wam_gtd7bk_mod::pdm
block space data for lower boundary
Definition at line 98 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(50) wam_gtd7bk_mod::pe1
block space data for o2 density
Definition at line 47 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pe2
block space data for o2 density
Definition at line 48 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pe3
block space data for o2 density
Definition at line 49 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pf1
block space data for ar density
Definition at line 50 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pf2
block space data for ar density
Definition at line 51 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pf3
block space data for ar density
Definition at line 52 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pg1
block space data for h density
Definition at line 53 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pg2
block space data for h density
Definition at line 54 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pg3
block space data for h density
Definition at line 55 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::ph1
block space data for n density
Definition at line 56 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::ph2
block space data for n density
Definition at line 57 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::ph3
block space data for n density
Definition at line 58 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pi1
block space data for hot o density
Definition at line 59 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pi2
block space data for hot o density
Definition at line 60 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pi3
block space data for hot o density
Definition at line 61 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pj1
block space data for s param
Definition at line 62 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pj2
block space data for s param
Definition at line 63 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pj3
block space data for s param
Definition at line 64 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pk1
block space data for turbo
Definition at line 65 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pl1
block space data for tn1(2)
Definition at line 66 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pl2
block space data for tn1(2)
Definition at line 67 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pm1
block space data for tn1(3)
Definition at line 68 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pm2
block space data for tn1(3)
Definition at line 69 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pn1
block space data for tn1(4)
Definition at line 70 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pn2
block space data for tn1(4)
Definition at line 71 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::po1
block space data for tn1(5) tn2(1)
Definition at line 72 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::po2
block space data for tn1(5) tn2(1)
Definition at line 73 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pp1
block space data for tn2(2)
Definition at line 74 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pp2
block space data for tn2(2)
Definition at line 75 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pq1
block space data for tn2(3)
Definition at line 76 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pq2
block space data for tn2(3)
Definition at line 77 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pr1
block space data for tn2(4) tn3(1)
Definition at line 78 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(2,151) wam_gtd7bk_mod::pr151
define pressures
Definition at line 109 of file wam_climo_data.f90.
real, dimension(50) wam_gtd7bk_mod::pr2
block space data for tn2(4) tn3(1)
Definition at line 79 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(2,65) wam_gtd7bk_mod::pr65
define pressures
Definition at line 108 of file wam_climo_data.f90.
real, dimension(50) wam_gtd7bk_mod::ps1
block space data for tn3(2)
Definition at line 80 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::ps2
block space data for tn3(2)
Definition at line 81 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pt1
block space data for temperature
Definition at line 32 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pt2
block space data for temperature
Definition at line 33 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pt3
block space data for temperature
Definition at line 34 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(10) wam_gtd7bk_mod::ptm
block space data for lower boundary
Definition at line 97 of file wam_climo_data.f90.
Referenced by gts7().
real, dimension(50) wam_gtd7bk_mod::pu1
block space data for tn3(3)
Definition at line 82 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pu2
block space data for tn3(3)
Definition at line 83 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pv1
block space data for tn3(4)
Definition at line 84 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pv2
block space data for tn3(4)
Definition at line 85 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pw1
block space data for tn3(5) surface temperature tsl
Definition at line 86 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pw2
block space data for tn3(5) surface temperature tsl
Definition at line 87 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::px1
block space data for tgn3(2) surface grad tslg
Definition at line 88 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::px2
block space data for tgn3(2) surface grad tslg
Definition at line 89 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::py1
block space data for tgn2(1) tgn1(2)
Definition at line 90 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::py2
block space data for tgn2(1) tgn1(2)
Definition at line 91 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pz1
block space data for tgn3(1) tgn2(2)
Definition at line 92 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(50) wam_gtd7bk_mod::pz2
block space data for tgn3(1) tgn2(2)
Definition at line 93 of file wam_climo_data.f90.
Referenced by gtd7().
Author
Generated automatically by Doxygen for chgres_cube from the source code.