module_nwp_base::nwpbase
NAME
module_nwp_base::nwpbase -
SYNOPSIS
Inherits module_nwp_base::nwplocation.
Private Member Functions
procedure alloc => alloc_obsbase
Allocate memory for observations.
procedure destroy => destroy_obsbase
Release memory.
procedure list => list_obsbase
List contents of obs.
Private Attributes
logical ifquality
do these obs include quality info? GLM has flash_quality_flag.
type(nwpbase), pointer next => NULL()
Pointer.
integer numvar
number of variables in this obs type.
real(r_kind), dimension(:),
allocatable obs"
Observations.
integer, dimension(:), allocatable quality
if so, quality flags.
real(r_single) time
observation time.
Detailed Description
Definition at line 34 of file module_nwp_base.f90.
Member Function/Subroutine Documentation
procedure module_nwp_base::nwpbase::alloc () [private]
Allocate memory for observations.
Returns:
Definition at line 45 of file module_nwp_base.f90.
References module_nwp_base::alloc_obsbase().
procedure module_nwp_base::nwpbase::destroy () [private]
Release memory.
Returns:
Definition at line 46 of file module_nwp_base.f90.
References module_nwp_base::destroy_obsbase().
procedure module_nwp_base::nwpbase::list () [private]
List contents of obs.
Returns:
Definition at line 44 of file module_nwp_base.f90.
References module_nwp_base::list_obsbase().
Field Documentation
logical module_nwp_base::nwpbase::ifquality [private]
do these obs include quality info? GLM has flash_quality_flag.
Definition at line 41 of file module_nwp_base.f90.
type(nwpbase), pointer module_nwp_base::nwpbase::next => NULL() [private]
Pointer.
Definition at line 36 of file module_nwp_base.f90.
integer module_nwp_base::nwpbase::numvar [private]
number of variables in this obs type.
Definition at line 38 of file module_nwp_base.f90.
real(r_kind), dimension(:), allocatable module_nwp_base::nwpbase::obs [private]
Observations.
Definition at line 40 of file module_nwp_base.f90.
integer, dimension(:), allocatable module_nwp_base::nwpbase::quality [private]
if so, quality flags.
Definition at line 42 of file module_nwp_base.f90.
real(r_single) module_nwp_base::nwpbase::time [private]
observation time.
Definition at line 37 of file module_nwp_base.f90.
Author
Generated automatically by Doxygen for fvcom_tools from the source code.