module_nwp_base
NAME
module_nwp_base -
This module defines nwp observation data structure and the method to read and write observations from and to those data structures.
SYNOPSIS
Data Types
type nwpbase
type nwplocation
Private Member Functions
subroutine alloc_obsbase (this, numvar, ifquality)
This subroutine allocates memory for base nwp observation variables.
subroutine destroy_obsbase (this)
This subroutine releases memory associated with nwp observations.
subroutine list_obsbase (this)
This subroutine lists the contents of a base nwp observation.
Detailed Description
This module defines nwp observation data structure and the method to read and write observations from and to those data structures.
It is used by ingest_FVCOM.f90.
This script is strongly based upon Eric James' (ESRL/GSL) work with HRRR/WRF.
Author:
David Wright, University of Michigan and GLERL
Date:
17 Aug 2020
Definition at line 14 of file module_nwp_base.f90.
Member Function/Subroutine Documentation
subroutine module_nwp_base::alloc_obsbase (class(nwpbase)this, integer, intent(in)numvar, logical, intent(in), optionalifquality) [private]
This subroutine allocates memory for base nwp observation variables.
Parameters:
this the base nwp obervation
numvar number of variables in this ob type
ifquality does this observation include quality information?
Author:
David Wright, University of Michigan and GLERL
Date:
17 Aug 2020
Definition at line 88 of file module_nwp_base.f90.
Referenced by module_nwp_base::nwpbase::alloc().
subroutine module_nwp_base::destroy_obsbase (class(nwpbase)this) [private]
This subroutine releases memory associated with nwp observations.
Parameters:
this the base nwp obervation
Author:
David Wright, University of Michigan and GLERL
Date:
17 Aug 2020
Definition at line 119 of file module_nwp_base.f90.
Referenced by module_nwp_base::nwpbase::destroy().
subroutine module_nwp_base::list_obsbase (class(nwpbase)this) [private]
This subroutine lists the contents of a base nwp observation.
Parameters:
this the base nwp obervation
Author:
David Wright, University of Michigan and GLERL
Date:
17 Aug 2020
Definition at line 56 of file module_nwp_base.f90.
Referenced by module_nwp_base::nwpbase::list().
Author
Generated automatically by Doxygen for fvcom_tools from the source code.