#################################################################
# Baseline tests are conducted for both ocean and ice, mapping
# 1/4deg source restart files for ocean and ice to two lower
# resolution destination warmstart (1deg and 1/2deg). The source
# files are assumed to have the filenames ocean.nc and ice.nc
# The files produced will be ocean.mx[dest res].nc and ice.mx[des res].nc
# The program needs to execute twice, once for ocean and once for ice
#
# The source restarts were obtained for the baseline test from
# https://noaa-ufs-gefsv13replay-pds.s3.amazonaws.com/2021/03/2021032206/
# The required single mom6 file was created using
# ncks -O -v Temp,Salt,h,u replay-2021032206/MOM.res.nc ocean.nc
# ncks -v v,sfc -A replay-2021032206/MOM.res_1.nc ocean.nc
#################################################################

# SRC resolution | file type | DST resolution

mx025 | ocean | mx050
mx025 | ocean | mx100

mx025 | ice | mx050
mx025 | ice | mx100

# The utility can be used to generate higher-resolution warmstarts using
# a lower resolution file. To do this, manually configure the path in rt.sh
# to point to your platform-local input source (INPUT_ROOT). Then uncomment
# the following lines and run the utility.

#mx100 | ocean | mx025
#mx100 | ice   | mx025
