.TH "md__lfs_h2_emc_global_noscrub_George.Gayno_ufs_utils.git_UFS_UTILS_sorc_emcsfc_ice_blend.fd_docs_README" 3 "Mon Oct 23 2023" "Version 1.11.0" "emcsfc_ice_blend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__lfs_h2_emc_global_noscrub_George.Gayno_ufs_utils.git_UFS_UTILS_sorc_emcsfc_ice_blend.fd_docs_README \- README 
This program blends National Ice Center sea ice cover and EMC sea ice concentration data to create a global sea ice analysis\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
