.TH "debugprint" 3 "Wed Mar 13 2024" "Version 1.13.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debugprint \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine, public \fBcheckpoint\fP"
.br
.RI "\fIPrint values at specified point\&. \fP"
.ti -1c
.RI "subroutine, public \fBcheckseam\fP"
.br
.RI "\fIPrint values across the tripole seam\&. \fP"
.ti -1c
.RI "subroutine, public \fBcheckxlatlon\fP"
.br
.RI "\fIPrint values near the poles and along the domain edges\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file debugprint\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine, public debugprint::checkpoint ()"

.PP
Print values at specified point\&. 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 170 of file debugprint\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.
.SS "subroutine, public debugprint::checkseam ()"

.PP
Print values across the tripole seam\&. 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 27 of file debugprint\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.
.SS "subroutine, public debugprint::checkxlatlon ()"

.PP
Print values near the poles and along the domain edges\&. 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 108 of file debugprint\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
