.TH "grdvars" 3 "Wed Mar 13 2024" "Version 1.13.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grdvars \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBallocate_all\fP"
.br
.RI "\fIAllocate grid variables\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBangle\fP"
.br
.RI "\fIThe rotation angle on Bu points\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBanglet\fP"
.br
.RI "\fIThe rotation angle on Ct points (opposite sense from angle) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBangq\fP"
.br
.RI "\fIThe grid rotation angle at the Bu (or corner) grid points of the super grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBareact\fP"
.br
.RI "\fIThe grid areas of the Ct grid cell in m2\&. \fP"
.ti -1c
.RI "logical \fBdebug\fP"
.br
.RI "\fIflag indicating whether grid information should be printed for debugging purposes Default is false \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:), 
.br
allocatable \fBdlatbu\fP"
.br
.RI "\fIThe latitude spacing between Bu points at the grid bottom\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:), 
.br
allocatable \fBdlatcv\fP"
.br
.RI "\fIThe latitude spacing between Cv points at the grid bottom\&. \fP"
.ti -1c
.RI "logical \fBdo_postwgts\fP"
.br
.RI "\fIflag indicating whether then ESMF weights to regrid from the tripole grid to a rectilinear grid should be generated\&. \fP"
.ti -1c
.RI "real(real_kind), dimension(:,:), 
.br
allocatable \fBdp4\fP"
.br
.RI "\fIThe ocean depth from a MOM6 topog file, stored as real*4 (m) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBdp8\fP"
.br
.RI "\fIThe ocean depth from a MOM6 topog file, stored as real*8 (m) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBdx\fP"
.br
.RI "\fIThe grid cell width in meters of the supergrid in the x-direction (i-dimension) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBdy\fP"
.br
.RI "\fIThe grid cell width in meters of the supergrid in the y-direction (j-dimension) \fP"
.ti -1c
.RI "logical \fBeditmask\fP"
.br
.RI "\fIflag indicating whether the MOM6 land mask should be edited\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBhte\fP"
.br
.RI "\fIThe grid cell width in centimeters of the CICE6 grid in the y-direction (j-dimension) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBhtn\fP"
.br
.RI "\fIThe grid cell width in centimeters of the CICE6 grid in the x-direction (i-dimension) \fP"
.ti -1c
.RI "integer(int_kind), dimension(2) \fBipole\fP"
.br
.RI "\fIthe i-index for both pole locations along the top-most row \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP) \fBivertbu\fP"
.br
.RI "\fIThe i-offsets of the Ct grid at each Bu(i,j) which determine the 4 vertices of each Bu grid point in i\&. \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP), parameter \fBivertct\fP = (/0, -1, -1, 0/)"
.br
.RI "\fIThe i-offsets of the Bu grid at each Ct(i,j) which determine the 4 vertices of each Ct grid grid point in i\&. \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP) \fBivertcu\fP"
.br
.RI "\fIThe i-offsets of the Cv grid at each Cu(i,j) which determine the 4 vertices of each Cu grid point in i\&. \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP) \fBivertcv\fP"
.br
.RI "\fIThe i-offsets of the Cu grid at each Cv(i,j) which determine the 4 vertices of each Cv grid point in i\&. \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP) \fBjvertbu\fP"
.br
.RI "\fIThe j-offsets of the Ct grid at each Bu(i,j) which determine the 4 vertices of each Bu grid point in j\&. \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP), parameter \fBjvertct\fP = (/0, 0, -1, -1/)"
.br
.RI "\fIThe j-offsets of the Bu grid at each Ct(i,j) which determine the 4 vertices of each Ct grid point in j\&. \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP) \fBjvertcu\fP"
.br
.RI "\fIThe j-offsets of the Cv grid at each Cu(i,j) which determine the 4 vertices of each Cu grid point in j\&. \fP"
.ti -1c
.RI "integer, dimension(\fBnv\fP) \fBjvertcv\fP"
.br
.RI "\fIThe j-offsets of the Cu grid at each Cv(i,j) which determine the 4 vertices of each Cv grid point in j\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBlatbu\fP"
.br
.RI "\fIThe latitude of the corner points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBlatbu_vert\fP"
.br
.RI "\fIThe latitudes of the 4 vertices of each Bu grid point\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBlatct\fP"
.br
.RI "\fIThe latitude of the center (tracer) grid points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBlatct_vert\fP"
.br
.RI "\fIThe latitudes of the 4 vertices of each Ct grid point\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBlatcu\fP"
.br
.RI "\fIThe latitude of the u-velocity grid points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBlatcu_vert\fP"
.br
.RI "\fIThe latitudes of the 4 vertices of each Cu grid point\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBlatcv\fP"
.br
.RI "\fIThe latitude of the v-velocity grid points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBlatcv_vert\fP"
.br
.RI "\fIThe latitudes of the 4 vertices of each Cv grid point\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBlonbu\fP"
.br
.RI "\fIThe longitude of the corner points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBlonbu_vert\fP"
.br
.RI "\fIThe longitudes of the 4 vertices of each Bu grid point\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBlonct\fP"
.br
.RI "\fIThe longitude of the center (tracer) grid points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBlonct_vert\fP"
.br
.RI "\fIThe longitudes of the 4 vertices of each Ct grid point\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBloncu\fP"
.br
.RI "\fIThe longitude of the u-velocity grid points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBloncu_vert\fP"
.br
.RI "\fIThe longitudes of the 4 vertices of each Cu grid point\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBloncv\fP"
.br
.RI "\fIThe longitude of the v-velocity grid points on the C-grid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:,:), 
.br
allocatable \fBloncv_vert\fP"
.br
.RI "\fIThe longitudes of the 4 vertices of each Cv grid point\&. \fP"
.ti -1c
.RI "real(kind=real_kind), parameter \fBmasking_depth\fP = 0\&.0"
.br
.RI "\fIThe masking depth for MOM6\&. \fP"
.ti -1c
.RI "real(kind=real_kind), parameter \fBmaximum_depth\fP = 6500\&.0"
.br
.RI "\fIThe maximum depth for MOM6\&. \fP"
.ti -1c
.RI "real(kind=real_kind), parameter \fBmaximum_lat\fP = 88\&.0"
.br
.RI "\fIThe maximum latitude for water points for WW3\&. \fP"
.ti -1c
.RI "real(kind=real_kind), parameter \fBminimum_depth\fP = 9\&.5"
.br
.RI "\fIThe minimum depth for MOM6\&. \fP"
.ti -1c
.RI "integer, parameter \fBncoord\fP = 2*4\&."
.br
.RI "\fIthe number of coord pairs (lat,lon) for each of 4 stagger locations \fP"
.ti -1c
.RI "integer \fBni\fP"
.br
.RI "\fIi-dimension of output grid \fP"
.ti -1c
.RI "integer \fBnj\fP"
.br
.RI "\fIj-dimension of output grid \fP"
.ti -1c
.RI "integer \fBnpx\fP"
.br
.RI "\fIi or j-dimension of fv3 tile \fP"
.ti -1c
.RI "integer, parameter \fBnv\fP = 4\&."
.br
.RI "\fIthe number of vertices for each stagger location \fP"
.ti -1c
.RI "integer, parameter \fBnvars\fP = \fBncoord\fP + \fBnverts\fP"
.br
.RI "\fIthe total number of cooridinate variables \fP"
.ti -1c
.RI "integer, parameter \fBnverts\fP = 2*4\&."
.br
.RI "\fIthe number of coord pairs (lat,lon) for the vertices of each stagger location \fP"
.ti -1c
.RI "integer \fBnx\fP"
.br
.RI "\fIi-dimension of MOM6 supergrid \fP"
.ti -1c
.RI "integer \fBny\fP"
.br
.RI "\fIj-dimension of MOM6 supergrid \fP"
.ti -1c
.RI "logical \fBroottask\fP"
.br
.RI "\fIflag indicating whether this is the roottask \fP"
.ti -1c
.RI "real(dbl_kind) \fBsg_maxlat\fP"
.br
.RI "\fIthe maximum latitute present in the supergrid file \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBulat\fP"
.br
.RI "\fIThe latitude points (on the Bu grid) for CICE6 (radians) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBulon\fP"
.br
.RI "\fIThe longitude points (on the Bu grid) for CICE6 (radians) \fP"
.ti -1c
.RI "real(real_kind), dimension(:,:), 
.br
allocatable \fBwet4\fP"
.br
.RI "\fIThe ocean mask from a MOM6 mask file, stored as real*4 (nd) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBwet8\fP"
.br
.RI "\fIThe ocean mask from a MOM6 mask file, stored as real*8 (nd) \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBx\fP"
.br
.RI "\fIThe longitudes of the MOM6 supergrid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:), 
.br
allocatable \fBxlatct\fP"
.br
.RI "\fIThe latitude of the Ct grid points on the opposite side of the tripole seam\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:), 
.br
allocatable \fBxlatcu\fP"
.br
.RI "\fIThe latitude of the Cu grid points on the opposite side of the tripole seam\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:), 
.br
allocatable \fBxlonct\fP"
.br
.RI "\fIThe longitude of the Ct grid points on the opposite side of the tripole seam\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:), 
.br
allocatable \fBxloncu\fP"
.br
.RI "\fIThe longitude of the Cu grid points on the opposite side of the tripole seam\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBxsgp1\fP"
.br
.RI "\fIThe longitudes of the super-grid replicated across the tripole seam\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBy\fP"
.br
.RI "\fIThe latitudes of the MOM6 supergrid\&. \fP"
.ti -1c
.RI "real(dbl_kind), dimension(:,:), 
.br
allocatable \fBysgp1\fP"
.br
.RI "\fIThe latitudes of the super-grid replicated across the tripole seam\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file grdvars\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine grdvars::allocate_all ()"

.PP
Allocate grid variables\&. 
.PP
\fBAuthor:\fP
.RS 4
Denise Worthen 
.RE
.PP

.PP
Definition at line 173 of file grdvars\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.
.SH "Field Documentation"
.PP 
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::angle"

.PP
The rotation angle on Bu points\&. 
.PP
Definition at line 105 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::anglet"

.PP
The rotation angle on Ct points (opposite sense from angle) 
.PP
Definition at line 103 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::angq"

.PP
The grid rotation angle at the Bu (or corner) grid points of the super grid\&. 
.PP
Definition at line 71 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::areact"

.PP
The grid areas of the Ct grid cell in m2\&. 
.PP
Definition at line 102 of file grdvars\&.F90\&.
.SS "logical grdvars::debug"

.PP
flag indicating whether grid information should be printed for debugging purposes Default is false 
.PP
Definition at line 23 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:), allocatable grdvars::dlatbu"

.PP
The latitude spacing between Bu points at the grid bottom\&. 
.PP
Definition at line 136 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:), allocatable grdvars::dlatcv"

.PP
The latitude spacing between Cv points at the grid bottom\&. 
.PP
Definition at line 138 of file grdvars\&.F90\&.
.SS "logical grdvars::do_postwgts"

.PP
flag indicating whether then ESMF weights to regrid from the tripole grid to a rectilinear grid should be generated\&. Default is false\&. 
.PP
Definition at line 26 of file grdvars\&.F90\&.
.SS "real(real_kind), dimension(:,:), allocatable grdvars::dp4"

.PP
The ocean depth from a MOM6 topog file, stored as real*4 (m) 
.PP
Definition at line 146 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::dp8"

.PP
The ocean depth from a MOM6 topog file, stored as real*8 (m) 
.PP
Definition at line 148 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::dx"

.PP
The grid cell width in meters of the supergrid in the x-direction (i-dimension) 
.PP
Definition at line 74 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::dy"

.PP
The grid cell width in meters of the supergrid in the y-direction (j-dimension) 
.PP
Definition at line 76 of file grdvars\&.F90\&.
.SS "logical grdvars::editmask"

.PP
flag indicating whether the MOM6 land mask should be edited\&. Default is false 
.PP
Definition at line 21 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::hte"

.PP
The grid cell width in centimeters of the CICE6 grid in the y-direction (j-dimension) 
.PP
Definition at line 158 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::htn"

.PP
The grid cell width in centimeters of the CICE6 grid in the x-direction (i-dimension) 
.PP
Definition at line 156 of file grdvars\&.F90\&.
.SS "integer(int_kind), dimension(2) grdvars::ipole"

.PP
the i-index for both pole locations along the top-most row 
.PP
Definition at line 41 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP) grdvars::ivertbu"

.PP
The i-offsets of the Ct grid at each Bu(i,j) which determine the 4 vertices of each Bu grid point in i\&. 
.PP
Definition at line 62 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP), parameter grdvars::ivertct = (/0, -1, -1, 0/)"

.PP
The i-offsets of the Bu grid at each Ct(i,j) which determine the 4 vertices of each Ct grid grid point in i\&. 
.PP
Definition at line 44 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP) grdvars::ivertcu"

.PP
The i-offsets of the Cv grid at each Cu(i,j) which determine the 4 vertices of each Cu grid point in i\&. 
.PP
Definition at line 56 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP) grdvars::ivertcv"

.PP
The i-offsets of the Cu grid at each Cv(i,j) which determine the 4 vertices of each Cv grid point in i\&. 
.PP
Definition at line 50 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP) grdvars::jvertbu"

.PP
The j-offsets of the Ct grid at each Bu(i,j) which determine the 4 vertices of each Bu grid point in j\&. 
.PP
Definition at line 65 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP), parameter grdvars::jvertct = (/0, 0, -1, -1/)"

.PP
The j-offsets of the Bu grid at each Ct(i,j) which determine the 4 vertices of each Ct grid point in j\&. 
.PP
Definition at line 47 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP) grdvars::jvertcu"

.PP
The j-offsets of the Cv grid at each Cu(i,j) which determine the 4 vertices of each Cu grid point in j\&. 
.PP
Definition at line 59 of file grdvars\&.F90\&.
.SS "integer, dimension(\fBnv\fP) grdvars::jvertcv"

.PP
The j-offsets of the Cu grid at each Cv(i,j) which determine the 4 vertices of each Cv grid point in j\&. 
.PP
Definition at line 53 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::latbu"

.PP
The latitude of the corner points on the C-grid\&. These are equivalent to u,v velocity grid points on the B-grid 
.PP
Definition at line 96 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::latbu_vert"

.PP
The latitudes of the 4 vertices of each Bu grid point\&. 
.PP
Definition at line 122 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::latct"

.PP
The latitude of the center (tracer) grid points on the C-grid\&. 
.PP
Definition at line 84 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::latct_vert"

.PP
The latitudes of the 4 vertices of each Ct grid point\&. 
.PP
Definition at line 107 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::latcu"

.PP
The latitude of the u-velocity grid points on the C-grid\&. 
.PP
Definition at line 92 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::latcu_vert"

.PP
The latitudes of the 4 vertices of each Cu grid point\&. 
.PP
Definition at line 117 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::latcv"

.PP
The latitude of the v-velocity grid points on the C-grid\&. 
.PP
Definition at line 88 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::latcv_vert"

.PP
The latitudes of the 4 vertices of each Cv grid point\&. 
.PP
Definition at line 112 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::lonbu"

.PP
The longitude of the corner points on the C-grid\&. These are equivalent to u,v velocity grid points on the B-grid 
.PP
Definition at line 99 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::lonbu_vert"

.PP
The longitudes of the 4 vertices of each Bu grid point\&. 
.PP
Definition at line 124 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::lonct"

.PP
The longitude of the center (tracer) grid points on the C-grid\&. 
.PP
Definition at line 86 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::lonct_vert"

.PP
The longitudes of the 4 vertices of each Ct grid point\&. 
.PP
Definition at line 109 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::loncu"

.PP
The longitude of the u-velocity grid points on the C-grid\&. 
.PP
Definition at line 94 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::loncu_vert"

.PP
The longitudes of the 4 vertices of each Cu grid point\&. 
.PP
Definition at line 119 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::loncv"

.PP
The longitude of the v-velocity grid points on the C-grid\&. 
.PP
Definition at line 90 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:,:), allocatable grdvars::loncv_vert"

.PP
The longitudes of the 4 vertices of each Cv grid point\&. 
.PP
Definition at line 114 of file grdvars\&.F90\&.
.SS "real(kind=real_kind), parameter grdvars::masking_depth = 0\&.0"

.PP
The masking depth for MOM6\&. Depths shallower than minimum_depth but deeper than masking_depth are rounded to minimum_depth 
.PP
Definition at line 163 of file grdvars\&.F90\&.
.SS "real(kind=real_kind), parameter grdvars::maximum_depth = 6500\&.0"

.PP
The maximum depth for MOM6\&. 
.PP
Definition at line 162 of file grdvars\&.F90\&.
.SS "real(kind=real_kind), parameter grdvars::maximum_lat = 88\&.0"

.PP
The maximum latitude for water points for WW3\&. 
.PP
Definition at line 166 of file grdvars\&.F90\&.
.SS "real(kind=real_kind), parameter grdvars::minimum_depth = 9\&.5"

.PP
The minimum depth for MOM6\&. 
.PP
Definition at line 161 of file grdvars\&.F90\&.
.SS "integer, parameter grdvars::ncoord = 2*4\&."

.PP
the number of coord pairs (lat,lon) for each of 4 stagger locations 
.PP
Definition at line 32 of file grdvars\&.F90\&.
.SS "integer grdvars::ni"

.PP
i-dimension of output grid 
.PP
Definition at line 14 of file grdvars\&.F90\&.
.SS "integer grdvars::nj"

.PP
j-dimension of output grid 
.PP
Definition at line 15 of file grdvars\&.F90\&.
.SS "integer grdvars::npx"

.PP
i or j-dimension of fv3 tile 
.PP
Definition at line 16 of file grdvars\&.F90\&.
.SS "integer, parameter grdvars::nv = 4\&."

.PP
the number of vertices for each stagger location 
.PP
Definition at line 31 of file grdvars\&.F90\&.
.SS "integer, parameter grdvars::nvars = \fBncoord\fP + \fBnverts\fP"

.PP
the total number of cooridinate variables 
.PP
Definition at line 36 of file grdvars\&.F90\&.
.SS "integer, parameter grdvars::nverts = 2*4\&."

.PP
the number of coord pairs (lat,lon) for the vertices of each stagger location 
.PP
Definition at line 34 of file grdvars\&.F90\&.
.SS "integer grdvars::nx"

.PP
i-dimension of MOM6 supergrid 
.PP
Definition at line 18 of file grdvars\&.F90\&.
.SS "integer grdvars::ny"

.PP
j-dimension of MOM6 supergrid 
.PP
Definition at line 19 of file grdvars\&.F90\&.
.SS "logical grdvars::roottask"

.PP
flag indicating whether this is the roottask 
.PP
Definition at line 29 of file grdvars\&.F90\&.
.SS "real(dbl_kind) grdvars::sg_maxlat"

.PP
the maximum latitute present in the supergrid file 
.PP
Definition at line 39 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::ulat"

.PP
The latitude points (on the Bu grid) for CICE6 (radians) 
.PP
Definition at line 154 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::ulon"

.PP
The longitude points (on the Bu grid) for CICE6 (radians) 
.PP
Definition at line 152 of file grdvars\&.F90\&.
.SS "real(real_kind), dimension(:,:), allocatable grdvars::wet4"

.PP
The ocean mask from a MOM6 mask file, stored as real*4 (nd) 
.PP
Definition at line 141 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::wet8"

.PP
The ocean mask from a MOM6 mask file, stored as real*8 (nd) 
.PP
Definition at line 143 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::x"

.PP
The longitudes of the MOM6 supergrid\&. 
.PP
Definition at line 69 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:), allocatable grdvars::xlatct"

.PP
The latitude of the Ct grid points on the opposite side of the tripole seam\&. 
.PP
Definition at line 130 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:), allocatable grdvars::xlatcu"

.PP
The latitude of the Cu grid points on the opposite side of the tripole seam\&. 
.PP
Definition at line 134 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:), allocatable grdvars::xlonct"

.PP
The longitude of the Ct grid points on the opposite side of the tripole seam\&. 
.PP
Definition at line 128 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:), allocatable grdvars::xloncu"

.PP
The longitude of the Cu grid points on the opposite side of the tripole seam\&. 
.PP
Definition at line 132 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::xsgp1"

.PP
The longitudes of the super-grid replicated across the tripole seam\&. 
.PP
Definition at line 78 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::y"

.PP
The latitudes of the MOM6 supergrid\&. 
.PP
Definition at line 70 of file grdvars\&.F90\&.
.SS "real(dbl_kind), dimension(:,:), allocatable grdvars::ysgp1"

.PP
The latitudes of the super-grid replicated across the tripole seam\&. 
.PP
Definition at line 80 of file grdvars\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
