.TH "mapped_mask" 3 "Wed Mar 13 2024" "Version 1.13.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mapped_mask \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBmake_frac_land\fP (src, wgt)"
.br
.RI "\fIUse ESMF weights to map the ocean land mask to the FV3 tiles and write the mapped mask to 6 tile files\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file mapped_mask\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine mapped_mask::make_frac_land (character(len=*), intent(in)src, character(len=*), intent(in)wgt)"

.PP
Use ESMF weights to map the ocean land mask to the FV3 tiles and write the mapped mask to 6 tile files\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsrc\fP a SCRIP file containing the land mask for the ocean domain 
.br
\fIwgt\fP a file containing the ESMF weights to regrid from the ocean domain to the FV3 tile domain
.RE
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 26 of file mapped_mask\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
