.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/vartypedefs.F90" 3 "Wed Mar 13 2024" "Version 1.13.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/cpld_gridgen.fd/vartypedefs.F90 \- 
.PP
Define the variables for output\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBvartypedefs::vardefs\fP"
.br
.ti -1c
.RI "module \fBvartypedefs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define the variables for output\&. 


.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov
.RE
.PP
This module defines the attributes for variables written to the tripole, cice and scrip grid files 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition in file \fBvartypedefs\&.F90\fP\&.
.SH "Data Type Documentation"
.PP 
.SH "type vartypedefs::vardefs"
.PP 
Definition at line 16 of file vartypedefs\&.F90\&.
.PP
\fBData Fields:\fP
.RS 4
character(len=cm) \fIlong_name\fP A variable's long name\&. 
.br
.PP
character(len=cm) \fIunit_name\fP A variable's unit\&. 
.br
.PP
character(len=cm) \fIvar_name\fP A variable name\&. 
.br
.PP
character(len=2) \fIvar_type\fP A variable's type\&. 
.br
.PP
character(len=cm) \fIvertices\fP A variable's vertices\&. 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
