.TH "vertices" 3 "Wed Mar 13 2024" "Version 1.13.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertices \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBfill_bottom\fP (iVert, jVert, lat, lon, latvert, lonvert, dlat)"
.br
.RI "\fIFill the vertices for a stagger location along the bottom j-row\&. \fP"
.ti -1c
.RI "subroutine \fBfill_top\fP (iVert, jVert, lat, lon, latvert, lonvert, xlat, xlon)"
.br
.RI "\fIFill the vertices for a stagger location along the top j-row\&. \fP"
.ti -1c
.RI "subroutine \fBfill_vertices\fP (jbeg, jend, iVert, jVert, lat, lon, latvert, lonvert)"
.br
.RI "\fIFill the vertices for any stagger location between bounding j-rows\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file vertices\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine vertices::fill_bottom (integer, dimension(nv), intent(in)iVert, integer, dimension(nv), intent(in)jVert, real(dbl_kind), dimension(ni,nj), intent(in)lat, real(dbl_kind), dimension(ni,nj), intent(in)lon, real(dbl_kind), dimension(ni,nj,nv), intent(out)latvert, real(dbl_kind), dimension(ni,nj,nv), intent(out)lonvert, real(dbl_kind), dimension(ni), intent(in)dlat)"

.PP
Fill the vertices for a stagger location along the bottom j-row\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiVert\fP the i-offset applied to the i-index of a stagger grid 
.br
\fIjVert\fP the j-offset applied to the j-index of a stagger grid 
.br
\fIlat\fP the latitudes of the stagger grid which define each vertex 
.br
\fIlon\fP the longitudes of the stagger grid which define each vertex 
.br
\fIdlat\fP the approximate latitude along the bottom-most row 
.br
\fIlatvert\fP the latitudes of each vertex 
.br
\fIlonvert\fP the longitudes of each vertex 
.RE
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 68 of file vertices\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.
.SS "subroutine vertices::fill_top (integer, dimension(nv), intent(in)iVert, integer, dimension(nv), intent(in)jVert, real(dbl_kind), dimension(ni,nj), intent(in)lat, real(dbl_kind), dimension(ni,nj), intent(in)lon, real(dbl_kind), dimension(ni,nj,nv), intent(out)latvert, real(dbl_kind), dimension(ni,nj,nv), intent(out)lonvert, real(dbl_kind), dimension(ni), intent(in)xlat, real(dbl_kind), dimension(ni), intent(in)xlon)"

.PP
Fill the vertices for a stagger location along the top j-row\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiVert\fP the i-offset applied to the i-index of a stagger grid 
.br
\fIjVert\fP the j-offset applied to the j-index of a stagger grid 
.br
\fIlat\fP the latitudes of the stagger grid which define each vertex 
.br
\fIlon\fP the longitudes of the stagger grid which define each vertex 
.br
\fIxlat\fP the latitude across the tripole seam 
.br
\fIxlon\fP the longitude across the tripole seam 
.br
\fIlatvert\fP the latitudes of each vertex 
.br
\fIlonvert\fP the longitudes of each vertex 
.RE
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 114 of file vertices\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.
.SS "subroutine vertices::fill_vertices (integer, intent(in)jbeg, integer, intent(in)jend, integer, dimension(nv), intent(in)iVert, integer, dimension(nv), intent(in)jVert, real(dbl_kind), dimension(ni,nj), intent(in)lat, real(dbl_kind), dimension(ni,nj), intent(in)lon, real(dbl_kind), dimension(ni,nj,nv), intent(out)latvert, real(dbl_kind), dimension(ni,nj,nv), intent(out)lonvert)"

.PP
Fill the vertices for any stagger location between bounding j-rows\&. 
.PP
\fBParameters:\fP
.RS 4
\fIjbeg\fP the beginning row 
.br
\fIjend\fP the ending row 
.br
\fIiVert\fP the i-offset applied to the i-index of a stagger grid 
.br
\fIjVert\fP the j-offset applied to the j-index of a stagger grid 
.br
\fIlat\fP the latitudes of the stagger grid which define each vertex 
.br
\fIlon\fP the longitudes of the stagger grid which define each vertex 
.br
\fIlatvert\fP the latitudes of each vertex 
.br
\fIlonvert\fP the longitudes of each vertex 
.RE
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 33 of file vertices\&.F90\&.
.PP
Referenced by gen_fixgrid()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
