.TH "/gpfs/dell1/stmp/George.Gayno/UFS_UTILS/sorc/gblevents.fd Directory Reference" 3 "Mon Aug 16 2021" "Version 1.6.0" "gblevents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/gpfs/dell1/stmp/George.Gayno/UFS_UTILS/sorc/gblevents.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgblevents\&.f\fP"
.br
.RI "\fIPre/Post processing of of prepbufr events\&. \fP"
.in -1c
