.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/gblevents.fd Directory Reference" 3 "Wed Mar 13 2024" "Version 1.13.0" "gblevents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/gblevents.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgblevents\&.f\fP"
.br
.RI "\fIPre/Post processing of of prepbufr events\&. \fP"
.in -1c
