.TH "md__lfs_h2_emc_global_noscrub_George.Gayno_ufs_utils.git_UFS_UTILS_sorc_sfc_climo_gen.fd_docs_README" 3 "Mon Oct 23 2023" "Version 1.11.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__lfs_h2_emc_global_noscrub_George.Gayno_ufs_utils.git_UFS_UTILS_sorc_sfc_climo_gen.fd_docs_README \- README 
This program creates climatological surface fields on the model grid, such as soil type and albedo\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
