atmosphere
NAME
atmosphere - Process atmospheric fields.
SYNOPSIS
Functions/Subroutines
subroutine, public atmosphere_driver (localpet)
Driver routine to process for atmospheric fields.
subroutine cleanup_target_atm_b4adj_data
Cleanup atmospheric field (before adjustment) objects.
subroutine cleanup_target_atm_data
Cleanup target grid atmospheric field objects.
subroutine compute_zh
Compute vertical level height.
subroutine convert_winds
Convert 3-d component winds to u and v.
subroutine create_atm_b4adj_esmf_fields
Create target grid field objects to hold data before vertical interpolation.
subroutine create_atm_esmf_fields
Create target grid field objects.
subroutine horiz_interp_thomp_mp_climo
Horizontally interpolate thompson microphysics data to the target model grid.
subroutine newpr1 (localpet)
Computes 3-D pressure given an adjusted surface pressure.
subroutine newps (localpet)
Computes adjusted surface pressure given a new terrain height.
subroutine read_vcoord_info
Reads model vertical coordinate definition file (as specified by namelist variable vcoord_file_target_grid).
subroutine rsearch (IM, KM1, IXZ1, KXZ1, Z1, KM2, IXZ2, KXZ2, Z2, IXL2, KXL2, L2)
Search for a surrounding real interval.
subroutine terp3 (IM, IXZ1, IXQ1, IXZ2, IXQ2, NM, NXQ1, NXQ2, KM1, KXZ1, KXQ1, Z1, Q1, KM2, KXZ2, KXQ2, Z2, Q2)
Cubically interpolate in one dimension.
subroutine vintg
Vertically interpolate upper-air fields.
subroutine vintg_thomp_mp_climo
Vertically interpolate atmospheric fields to target FV3 grid.
Variables
type(esmf_field), public delp_target_grid
pressure thickness
type(esmf_field) dzdt_b4adj_target_grid
vertical vel before vert adj
type(esmf_field), public dzdt_target_grid
vertical velocity
integer, public lev_target
num vertical levels
integer, public levp1_target
num levels plus 1
integer, public nvcoord_target
num vertical coordinate variables
type(esmf_field) pres_b4adj_target_grid
3-d pres before terrain adj
type(esmf_field) pres_target_grid
3-d pressure
type(esmf_field) ps_b4adj_target_grid
sfc pres before terrain adj
type(esmf_field), public ps_target_grid
surface pressure
type(esmf_field) qnifa_climo_b4adj_target_grid
number concentration of ice friendly aerosols before vert adj
type(esmf_field), public qnifa_climo_target_grid
number concentration of ice friendly aerosols on target horiz/vert grid.
type(esmf_field) qnwfa_climo_b4adj_target_grid
number concentration of water friendly aerosols before vert adj
type(esmf_field), public qnwfa_climo_target_grid
number concentration of water friendly aerosols on target horiz/vert grid.
type(esmf_field) temp_b4adj_target_grid
temp before vert adj
type(esmf_field), public temp_target_grid
temperautre
type(esmf_field) terrain_interp_to_target_grid
Input grid terrain interpolated to target grid.
type(esmf_field) thomp_pres_climo_b4adj_target_grid
pressure of each level on target grid
type(esmf_field), dimension(:), allocatable tracers_b4adj_target_grid
tracers before vert adj
type(esmf_field), dimension(:), allocatable, public tracers_target_grid
tracers
type(esmf_field), public u_s_target_grid
u-wind, 'south' edge
type(esmf_field), public u_w_target_grid
u-wind, 'west' edge
type(esmf_field), public v_s_target_grid
v-wind, 'south' edge
type(esmf_field), public v_w_target_grid
v-wind, 'west' edge
real(esmf_kind_r8), dimension(:,:), allocatable, public vcoord_target
vertical coordinate
type(esmf_field) wind_b4adj_target_grid
3-d wind before vert adj
type(esmf_field) wind_s_target_grid
3-d wind, 'south' edge
type(esmf_field) wind_target_grid
3-d wind, grid box center
type(esmf_field) wind_w_target_grid
3-d wind, 'west' edge
type(esmf_field), public zh_target_grid
3-d height
Detailed Description
Process atmospheric fields.
Horizontally interpolate from input to target FV3 grid using ESMF regridding. Adjust surface pressure according to terrain differences between input and target grid. Vertically interpolate to target FV3 grid vertical levels. Processing based on the spectral GFS version of CHGRES.
For variables 'b4adj' indicates fields on the target grid before vertical adjustment. 'target' indicates data on target grid. 'input' indicates data on input grid. '_s' indicates fields on the 'south' edge of the grid box. '_w' indicate fields on the 'west' edge of the grid box. Otherwise, fields are at the center of the grid box.
Author
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine, public atmosphere::atmosphere_driver (integer, intent(in) localpet)
Driver routine to process for atmospheric fields.
Parameters
localpet ESMF local persistent execution thread
Author
George Gayno
Definition at line 110 of file atmosphere.F90.
References program_setup::atm_weight_file, input_data::cleanup_input_atm_data(), cleanup_target_atm_b4adj_data(), cleanup_target_atm_data(), compute_zh(), convert_winds(), create_atm_b4adj_esmf_fields(), create_atm_esmf_fields(), dzdt_b4adj_target_grid, input_data::dzdt_input_grid, error_handler(), horiz_interp_thomp_mp_climo(), newpr1(), newps(), program_setup::num_tracers, pres_b4adj_target_grid, input_data::pres_input_grid, ps_b4adj_target_grid, input_data::ps_input_grid, input_data::read_input_atm_data(), thompson_mp_climo_data::read_thomp_mp_climo_data(), read_vcoord_info(), program_setup::regional, temp_b4adj_target_grid, input_data::temp_input_grid, input_data::terrain_input_grid, terrain_interp_to_target_grid, program_setup::tracers, tracers_b4adj_target_grid, input_data::tracers_input_grid, program_setup::use_thomp_mp_climo, vintg(), vintg_thomp_mp_climo(), wind_b4adj_target_grid, input_data::wind_input_grid, wind_s_target_grid, wind_target_grid, wind_w_target_grid, write_fv3_atm_bndy_data_netcdf(), write_fv3_atm_data_netcdf(), and write_fv3_atm_header_netcdf().
Referenced by chgres().
subroutine atmosphere::cleanup_target_atm_b4adj_data [private]
Cleanup atmospheric field (before adjustment) objects.
Author
George Gayno
Definition at line 1932 of file atmosphere.F90.
References dzdt_b4adj_target_grid, program_setup::num_tracers, pres_b4adj_target_grid, ps_b4adj_target_grid, temp_b4adj_target_grid, terrain_interp_to_target_grid, tracers_b4adj_target_grid, and wind_b4adj_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::cleanup_target_atm_data [private]
Cleanup target grid atmospheric field objects.
Author
George Gayno
Definition at line 1957 of file atmosphere.F90.
References delp_target_grid, dzdt_target_grid, program_setup::num_tracers, pres_target_grid, ps_target_grid, qnifa_climo_target_grid, qnwfa_climo_target_grid, temp_target_grid, tracers_target_grid, u_s_target_grid, u_w_target_grid, v_s_target_grid, v_w_target_grid, wind_s_target_grid, wind_target_grid, wind_w_target_grid, and zh_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::compute_zh [private]
Compute vertical level height.
Author
George Gayno
Definition at line 1842 of file atmosphere.F90.
References error_handler(), levp1_target, program_setup::num_tracers, ps_target_grid, temp_target_grid, model_grid::terrain_target_grid, program_setup::tracers, tracers_target_grid, vcoord_target, and zh_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::convert_winds [private]
Convert 3-d component winds to u and v.
Author
George Gayno
Definition at line 645 of file atmosphere.F90.
References error_handler(), model_grid::latitude_s_target_grid, model_grid::latitude_w_target_grid, model_grid::longitude_s_target_grid, model_grid::longitude_w_target_grid, u_s_target_grid, u_w_target_grid, v_s_target_grid, v_w_target_grid, wind_s_target_grid, and wind_w_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::create_atm_b4adj_esmf_fields
Create target grid field objects to hold data before vertical interpolation. These will be defined with the same number of vertical levels as the input grid.
Author
George Gayno
Definition at line 432 of file atmosphere.F90.
References dzdt_b4adj_target_grid, error_handler(), input_data::lev_input, program_setup::num_tracers, pres_b4adj_target_grid, ps_b4adj_target_grid, model_grid::target_grid, temp_b4adj_target_grid, terrain_interp_to_target_grid, program_setup::tracers, tracers_b4adj_target_grid, and wind_b4adj_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::create_atm_esmf_fields [private]
Create target grid field objects.
Author
George Gayno
Definition at line 506 of file atmosphere.F90.
References delp_target_grid, dzdt_target_grid, error_handler(), lev_target, levp1_target, program_setup::num_tracers, pres_target_grid, ps_target_grid, model_grid::target_grid, temp_target_grid, program_setup::tracers, tracers_target_grid, u_s_target_grid, u_w_target_grid, v_s_target_grid, v_w_target_grid, wind_s_target_grid, wind_target_grid, wind_w_target_grid, and zh_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::horiz_interp_thomp_mp_climo [private]
Horizontally interpolate thompson microphysics data to the target model grid.
Author
George Gayno
Definition at line 1132 of file atmosphere.F90.
References thompson_mp_climo_data::cleanup_thomp_mp_climo_input_data(), error_handler(), lev_target, thompson_mp_climo_data::lev_thomp_mp_climo, qnifa_climo_b4adj_target_grid, thompson_mp_climo_data::qnifa_climo_input_grid, qnifa_climo_target_grid, qnwfa_climo_b4adj_target_grid, thompson_mp_climo_data::qnwfa_climo_input_grid, qnwfa_climo_target_grid, model_grid::target_grid, thomp_pres_climo_b4adj_target_grid, and thompson_mp_climo_data::thomp_pres_climo_input_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::newpr1 (integer, intent(in) localpet) [private]
Computes 3-D pressure given an adjusted surface pressure. PROGRAM HISTORY LOG:
 2005-04-11 HANN_MING HENRY JUANG hybrid sigma, sigma-p, and sigma-
PRGMMR: JUANG ORG: W/NMC23 DATE: 2005-04-11
PRGMMR: Fanglin Yang ORG: W/NMC23 DATE: 2006-11-28
PRGMMR: S. Moorthi ORG: NCEP/EMC DATE: 2006-12-12
PRGMMR: S. Moorthi ORG: NCEP/EMC DATE: 2007-01-02
INPUT ARGUMENT LIST:
 IM INTEGER NUMBER OF POINTS TO COMPUTE
 KM INTEGER NUMBER OF LEVELS
 IDVC INTEGER VERTICAL COORDINATE ID
 (1 FOR SIGMA AND 2 FOR HYBRID)
 IDSL INTEGER TYPE OF SIGMA STRUCTURE
 (1 FOR PHILLIPS OR 2 FOR MEAN)
 NVCOORD INTEGER NUMBER OF VERTICAL COORDINATES
 VCOORD REAL (KM+1,NVCOORD) VERTICAL COORDINATE VALUES
 FOR IDVC=1, NVCOORD=1: SIGMA INTERFACE
 FOR IDVC=2, NVCOORD=2: HYBRID INTERFACE A AND B
 FOR IDVC=3, NVCOORD=3: JUANG GENERAL HYBRID INTERFACE AK REAL (KM+1) HYBRID INTERFACE A
 BK REAL (KM+1) HYBRID INTERFACE B
 PS REAL (IX) SURFACE PRESSURE (PA)
 OUTPUT ARGUMENT LIST:
 PM REAL (IX,KM) MID-LAYER PRESSURE (PA)
 DP REAL (IX,KM) LAYER DELTA PRESSURE (PA)
Parameters
localpet ESMF local persistent execution thread
Author
Hann Ming Henry Juang, Juang, Fanglin Yang, S. Moorthi
Definition at line 789 of file atmosphere.F90.
References delp_target_grid, error_handler(), lev_target, levp1_target, pres_target_grid, ps_target_grid, and vcoord_target.
Referenced by atmosphere_driver().
subroutine atmosphere::newps (integer, intent(in) localpet) [private]
Computes adjusted surface pressure given a new terrain height. Computes a new surface pressure given a new orography. The new pressure is computed assuming a hydrostatic balance and a constant temperature lapse rate. Below ground, the lapse rate is assumed to be -6.5 k/km.
program history log:
91-10-31 mark iredell
2018-apr adapt for fv3. george gayno
Parameters
localpet ESMF local persistent execution thread
Author
Mark Iredell, George Gayno
Date
92-10-31
Definition at line 900 of file atmosphere.F90.
References error_handler(), program_setup::num_tracers, pres_b4adj_target_grid, ps_b4adj_target_grid, ps_target_grid, temp_b4adj_target_grid, terrain_interp_to_target_grid, model_grid::terrain_target_grid, program_setup::tracers, and tracers_b4adj_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::read_vcoord_info [private]
Reads model vertical coordinate definition file (as specified by namelist variable vcoord_file_target_grid).
Author
George Gayno
Definition at line 1097 of file atmosphere.F90.
References error_handler(), lev_target, levp1_target, nvcoord_target, program_setup::vcoord_file_target_grid, and vcoord_target.
Referenced by atmosphere_driver().
subroutine atmosphere::rsearch (integer, intent(in) IM, integer, intent(in) KM1, integer, intent(in) IXZ1, integer, intent(in) KXZ1, real(esmf_kind_r8), dimension(1+(im-1)*ixz1+(km1-1)*kxz1), intent(in) Z1, integer, intent(in) KM2, integer, intent(in) IXZ2, integer, intent(in) KXZ2, real(esmf_kind_r8), dimension(1+(im-1)*ixz2+(km2-1)*kxz2), intent(in) Z2, integer, intent(in) IXL2, integer, intent(in) KXL2, integer, dimension(1+(im-1)*ixl2+(km2-1)*kxl2), intent(out) L2) [private]
Search for a surrounding real interval. This subprogram searches monotonic sequences of real numbers for intervals that surround a given search set of real numbers. The sequences may be monotonic in either direction; the real numbers may be single or double precision; the input sequences and sets and the output locations may be arbitrarily dimensioned.
If the array z1 is dimensioned (im,km1), then the skip numbers are ixz1=1 and kxz1=im; if it is dimensioned (km1,im), then the skip numbers are ixz1=km1 and kxz1=1; if it is dimensioned (im,jm,km1), then the skip numbers are ixz1=1 and kxz1=im*jm; etcetera. Similar examples apply to the skip numbers for z2 and l2.
Returned values of 0 or km1 indicate that the given search value
 is outside the range of the sequence.
If a search value is identical to one of the sequence values then the location returned points to the identical value. If the sequence is not strictly monotonic and a search value is identical to more than one of the sequence values, then the location returned may point to any of the identical values.
to be exact, for each i from 1 to im and for each k from 1 to km2, z=z2(1+(i-1)*ixz2+(k-1)*kxz2) is the search value and l=l2(1+(i-1)*ixl2+(k-1)*kxl2) is the location returned. if l=0, then z is less than the start point z1(1+(i-1)*ixz1) for ascending sequences (or greater than for descending sequences). if l=km1, then z is greater than or equal to the end point z1(1+(i-1)*ixz1+(km1-1)*kxz1) for ascending sequences (or less than or equal to for descending sequences). otherwise z is between the values z1(1+(i-1)*ixz1+(l-1)*kxz1) and z1(1+(i-1)*ixz1+(l-0)*kxz1) and may equal the former.
Parameters
im integer number of sequences to search
km1 integer number of points in each sequence
ixz1 integer sequence skip number for z1
kxz1 integer point skip number for z1
z1 real (1+(im-1)*ixz1+(km1-1)*kxz1)
 sequence values to search
 (z1 must be monotonic in either direction)
km2 integer number of points to search for
 in each respective sequence
ixz2 integer sequence skip number for z2
kxz2 integer point skip number for z2
z2 real (1+(im-1)*ixz2+(km2-1)*kxz2)
 set of values to search for
 (z2 need not be monotonic)
ixl2 integer sequence skip number for l2
kxl2 integer point skip number for l2
l2 integer (1+(im-1)*ixl2+(km2-1)*kxl2)
 interval locations having values from 0 to km1
 (z2 will be between z1(l2) and z1(l2+1))
Author
Mark Iredell
Date
98-05-01
Definition at line 1794 of file atmosphere.F90.
Referenced by terp3().
subroutine atmosphere::terp3 (integer IM, integer IXZ1, integer IXQ1, integer IXZ2, integer IXQ2, integer NM, integer NXQ1, integer NXQ2, integer KM1, integer KXZ1, integer KXQ1, real(esmf_kind_r8), dimension(1+(im-1)*ixz1+(km1-1)*kxz1) Z1, real(esmf_kind_r8), dimension(1+(im-1)*ixq1+(km1-1)*kxq1+(nm-1)*nxq1) Q1, integer KM2, integer KXZ2, integer KXQ2, real(esmf_kind_r8), dimension(1+(im-1)*ixz2+(km2-1)*kxz2) Z2, real(esmf_kind_r8), dimension(1+(im-1)*ixq2+(km2-1)*kxq2+(nm-1)*nxq2) Q2)
Cubically interpolate in one dimension. Interpolate field(s) in one dimension along the column(s). The interpolation is cubic lagrangian with a monotonic constraint in the center of the domain. In the outer intervals it is linear. Outside the domain, fields are held constant.
PROGRAM HISTORY LOG:
98-05-01 MARK IREDELL
1999-01-04 IREDELL USE ESSL SEARCH
Parameters
im integer number of columns
ixz1 integer column skip number for z1
ixq1 integer column skip number for q1
ixz2 integer column skip number for z2
ixq2 integer column skip number for q2
nm integer number of fields per column
nxq1 integer field skip number for q1
nxq2 integer field skip number for q2
km1 integer number of input points
kxz1 integer point skip number for z1
kxq1 integer point skip number for q1
z1 real (1+(im-1)*ixz1+(km1-1)*kxz1)
 input coordinate values in which to interpolate
 (z1 must be strictly monotonic in either direction)
q1 real (1+(im-1)*ixq1+(km1-1)*kxq1+(nm-1)*nxq1)
 input fields to interpolate
km2 integer number of output points
kxz2 integer point skip number for z2
kxq2 integer point skip number for q2
z2 real (1+(im-1)*ixz2+(km2-1)*kxz2)
 output coordinate values to which to interpolate
 (z2 need not be monotonic)
q2 real (1+(im-1)*ixq2+(km2-1)*kxq2+(nm-1)*nxq2)
 output interpolated fields
Author
Mark Iredell
Date
98-05-01
Definition at line 1600 of file atmosphere.F90.
References rsearch().
Referenced by vintg(), and vintg_thomp_mp_climo().
subroutine atmosphere::vintg [private]
Vertically interpolate upper-air fields. Vertically interpolate upper-air fields. Wind, temperature, humidity and other tracers are interpolated. The interpolation is cubic lagrangian in log pressure with a monotonic constraint in the center of the domain. In the outer intervals it is linear in log pressure. Outside the domain, fields are generally held constant, except for temperature and humidity below the input domain, where the temperature lapse rate is held fixed at -6.5 k/km and the relative humidity is held constant. This routine expects fields ordered from bottom to top of atmosphere.
Author
Mark Iredell
Date
92-10-31
Definition at line 1367 of file atmosphere.F90.
References dzdt_b4adj_target_grid, dzdt_target_grid, error_handler(), input_data::lev_input, lev_target, program_setup::num_tracers, pres_b4adj_target_grid, pres_target_grid, temp_b4adj_target_grid, temp_target_grid, terp3(), program_setup::tracers, tracers_b4adj_target_grid, tracers_target_grid, wind_b4adj_target_grid, and wind_target_grid.
Referenced by atmosphere_driver().
subroutine atmosphere::vintg_thomp_mp_climo [private]
Vertically interpolate atmospheric fields to target FV3 grid. Vertically interpolate thompson microphysics climo tracers to the target model levels.
Author
George Gayno
Definition at line 1244 of file atmosphere.F90.
References error_handler(), lev_target, thompson_mp_climo_data::lev_thomp_mp_climo, pres_target_grid, qnifa_climo_b4adj_target_grid, qnifa_climo_target_grid, qnwfa_climo_b4adj_target_grid, qnwfa_climo_target_grid, terp3(), and thomp_pres_climo_b4adj_target_grid.
Referenced by atmosphere_driver().
Variable Documentation
type(esmf_field), public atmosphere::delp_target_grid
pressure thickness
Definition at line 65 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), create_atm_esmf_fields(), newpr1(), and write_fv3_atm_data_netcdf().
type(esmf_field) atmosphere::dzdt_b4adj_target_grid [private]
vertical vel before vert adj
Definition at line 67 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_b4adj_data(), create_atm_b4adj_esmf_fields(), and vintg().
type(esmf_field), public atmosphere::dzdt_target_grid
vertical velocity
Definition at line 66 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), create_atm_esmf_fields(), vintg(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
integer, public atmosphere::lev_target
num vertical levels
Definition at line 59 of file atmosphere.F90.
Referenced by create_atm_esmf_fields(), horiz_interp_thomp_mp_climo(), newpr1(), read_vcoord_info(), vintg(), vintg_thomp_mp_climo(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
integer, public atmosphere::levp1_target
num levels plus 1
Definition at line 60 of file atmosphere.F90.
Referenced by compute_zh(), create_atm_esmf_fields(), newpr1(), read_vcoord_info(), write_fv3_atm_bndy_data_netcdf(), write_fv3_atm_data_netcdf(), and write_fv3_atm_header_netcdf().
integer, public atmosphere::nvcoord_target
num vertical coordinate variables
Definition at line 61 of file atmosphere.F90.
Referenced by read_vcoord_info(), and write_fv3_atm_header_netcdf().
type(esmf_field) atmosphere::pres_b4adj_target_grid [private]
3-d pres before terrain adj
Definition at line 73 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_b4adj_data(), create_atm_b4adj_esmf_fields(), newps(), and vintg().
type(esmf_field) atmosphere::pres_target_grid [private]
3-d pressure
Definition at line 72 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), create_atm_esmf_fields(), newpr1(), vintg(), and vintg_thomp_mp_climo().
type(esmf_field) atmosphere::ps_b4adj_target_grid [private]
sfc pres before terrain adj
Definition at line 71 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_b4adj_data(), create_atm_b4adj_esmf_fields(), and newps().
type(esmf_field), public atmosphere::ps_target_grid
surface pressure
Definition at line 70 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), compute_zh(), create_atm_esmf_fields(), newpr1(), newps(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field) atmosphere::qnifa_climo_b4adj_target_grid [private]
number concentration of ice friendly aerosols before vert adj
Definition at line 89 of file atmosphere.F90.
Referenced by horiz_interp_thomp_mp_climo(), and vintg_thomp_mp_climo().
type(esmf_field), public atmosphere::qnifa_climo_target_grid
number concentration of ice friendly aerosols on target horiz/vert grid.
Definition at line 91 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), horiz_interp_thomp_mp_climo(), vintg_thomp_mp_climo(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field) atmosphere::qnwfa_climo_b4adj_target_grid [private]
number concentration of water friendly aerosols before vert adj
Definition at line 94 of file atmosphere.F90.
Referenced by horiz_interp_thomp_mp_climo(), and vintg_thomp_mp_climo().
type(esmf_field), public atmosphere::qnwfa_climo_target_grid
number concentration of water friendly aerosols on target horiz/vert grid.
Definition at line 96 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), horiz_interp_thomp_mp_climo(), vintg_thomp_mp_climo(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field) atmosphere::temp_b4adj_target_grid [private]
temp before vert adj
Definition at line 75 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_b4adj_data(), create_atm_b4adj_esmf_fields(), newps(), and vintg().
type(esmf_field), public atmosphere::temp_target_grid
temperautre
Definition at line 74 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), compute_zh(), create_atm_esmf_fields(), vintg(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field) atmosphere::terrain_interp_to_target_grid [private]
Input grid terrain interpolated to target grid.
Definition at line 76 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_b4adj_data(), create_atm_b4adj_esmf_fields(), and newps().
type(esmf_field) atmosphere::thomp_pres_climo_b4adj_target_grid [private]
pressure of each level on target grid
Definition at line 99 of file atmosphere.F90.
Referenced by horiz_interp_thomp_mp_climo(), and vintg_thomp_mp_climo().
type(esmf_field), dimension(:), allocatable atmosphere::tracers_b4adj_target_grid [private]
tracers before vert adj
Definition at line 69 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_b4adj_data(), create_atm_b4adj_esmf_fields(), newps(), and vintg().
type(esmf_field), dimension(:), allocatable, public atmosphere::tracers_target_grid
tracers
Definition at line 68 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), compute_zh(), create_atm_esmf_fields(), vintg(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere::u_s_target_grid
u-wind, 'south' edge
Definition at line 77 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), convert_winds(), create_atm_esmf_fields(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere::u_w_target_grid
u-wind, 'west' edge
Definition at line 82 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), convert_winds(), create_atm_esmf_fields(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere::v_s_target_grid
v-wind, 'south' edge
Definition at line 78 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), convert_winds(), create_atm_esmf_fields(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
type(esmf_field), public atmosphere::v_w_target_grid
v-wind, 'west' edge
Definition at line 83 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), convert_winds(), create_atm_esmf_fields(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
real(esmf_kind_r8), dimension(:,:), allocatable, public atmosphere::vcoord_target
vertical coordinate
Definition at line 63 of file atmosphere.F90.
Referenced by compute_zh(), newpr1(), read_vcoord_info(), and write_fv3_atm_header_netcdf().
type(esmf_field) atmosphere::wind_b4adj_target_grid [private]
3-d wind before vert adj
Definition at line 80 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_b4adj_data(), create_atm_b4adj_esmf_fields(), and vintg().
type(esmf_field) atmosphere::wind_s_target_grid [private]
3-d wind, 'south' edge
Definition at line 81 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_data(), convert_winds(), and create_atm_esmf_fields().
type(esmf_field) atmosphere::wind_target_grid [private]
3-d wind, grid box center
Definition at line 79 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_data(), create_atm_esmf_fields(), and vintg().
type(esmf_field) atmosphere::wind_w_target_grid [private]
3-d wind, 'west' edge
Definition at line 84 of file atmosphere.F90.
Referenced by atmosphere_driver(), cleanup_target_atm_data(), convert_winds(), and create_atm_esmf_fields().
type(esmf_field), public atmosphere::zh_target_grid
3-d height
Definition at line 85 of file atmosphere.F90.
Referenced by cleanup_target_atm_data(), compute_zh(), create_atm_esmf_fields(), write_fv3_atm_bndy_data_netcdf(), and write_fv3_atm_data_netcdf().
Author
Generated automatically by Doxygen for chgres_cube from the source code.