gettemp_mod
NAME
gettemp_mod - Use moduke for common blocks.
SYNOPSIS
Variables
real apd
parameter calcumate for magnetic activity
real apdf
the same as apd
real, dimension(4) apt
daily magnetic activity
real c2tloc
cosine of 2 time location
real c3tloc
cosine of 3 time location
real ctloc
cosine of the location
real day
day in a year
real db01
diffusive density at zlb for g01
real db04
diffusive density at zlb for g4
real db14
diffusive density at zlb for g14
real db16
diffusive density at zlb for g18
real db28
diffusive density at zlb for g28
real db32
diffusive density at zlb for g32
real db40
diffusive density at zlb for g40
real db48
diffusive density at zlb for g48
real dd
diffusive density at alt
real df
the difference of f10.7 effect
real dfa
the difference to reference value
real dm01
mixed density at alt01
real dm04
mixed density at alt04
real dm14
mixed density at alt14
real dm16
mixed density at alt16
real dm28
mixed density at alt28
real dm32
mixed density at alt32
real dm40
mixed density at alt40
real g0
initial gradient variations
real gsurf
surface gravitation force at given latitude
integer isw
indix for sw
integer iyr
integer for a given year
real, dimension(150, 9) pd
he density
real, dimension(25, 2) pdl
turbo
real, dimension(9, 4) plg
Legendre polynomial points.
real, dimension(100, 10) pma
middle and low temperature
real, dimension(150) ps
s parameter
real, dimension(150) pt
temperature
real, dimension(100, 4) ptl
upper temperature
real re
referenced height related to gsurf
real rl
correction to specified mixing ratio at ground
real s
scale inverse to temperature difference
real s2tloc
sine of 2 time location
real s3tloc
sine of 3 time location
real, dimension(100) sam
semiannual mult sam
real stloc
sine of the location
real, dimension(25) sw
weighting
real, dimension(25) swc
weighting
real t0
initial temperature
real, dimension(2) tgn1
temperature gradient at node 1 (~mesosphere)
real, dimension(2) tgn2
temperature gradient at node 2 (~stratosphere)
real, dimension(2) tgn3
temperature gradient at node 3 (~troposphere)
real tinfg
startinf referenced point for tt
real tlb
labeled temperature
real, dimension(5) tn1
temperature at node 1 (~mesosphere)
real, dimension(4) tn2
temperature at node 2 (~stratosphere)
real, dimension(5) tn3
temperature at node 3 (~troposphere)
real tr12
try factor 1 or 2
real, dimension(15) tt
referenced temperature
real xlong
a given longitude
real z0
initial height
real za
joining altitude of bates and spline
Detailed Description
Use moduke for common blocks.
All variables under this module are originalyl in common block used for subroutine gettemp and others in this package.
Author:
Hann-Ming Henry Juang
Variable Documentation
real gettemp_mod::apd
parameter calcumate for magnetic activity
Definition at line 941 of file wam_climo_data.f90.
Referenced by globe7().
real gettemp_mod::apdf
the same as apd
Definition at line 942 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real, dimension(4) gettemp_mod::apt
daily magnetic activity
Definition at line 943 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::c2tloc
cosine of 2 time location
Definition at line 934 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::c3tloc
cosine of 3 time location
Definition at line 936 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::ctloc
cosine of the location
Definition at line 932 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::day
day in a year
Definition at line 938 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::db01
diffusive density at zlb for g01
Definition at line 889 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::db04
diffusive density at zlb for g4
Definition at line 883 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::db14
diffusive density at zlb for g14
Definition at line 896 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::db16
diffusive density at zlb for g18
Definition at line 884 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::db28
diffusive density at zlb for g28
Definition at line 885 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::db32
diffusive density at zlb for g32
Definition at line 886 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::db40
diffusive density at zlb for g40
Definition at line 887 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::db48
diffusive density at zlb for g48
Definition at line 888 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::dd
diffusive density at alt
Definition at line 895 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real gettemp_mod::df
the difference of f10.7 effect
Definition at line 939 of file wam_climo_data.f90.
Referenced by globe7().
real gettemp_mod::dfa
the difference to reference value
Definition at line 940 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::dm01
mixed density at alt01
Definition at line 922 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::dm04
mixed density at alt04
Definition at line 917 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::dm14
mixed density at alt14
Definition at line 923 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::dm16
mixed density at alt16
Definition at line 918 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::dm28
mixed density at alt28
Definition at line 919 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real gettemp_mod::dm32
mixed density at alt32
Definition at line 920 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::dm40
mixed density at alt40
Definition at line 921 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::g0
initial gradient variations
Definition at line 893 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::gsurf
surface gravitation force at given latitude
Definition at line 925 of file wam_climo_data.f90.
Referenced by densm(), densu(), ghp7(), gtd7(), and scalh().
integer gettemp_mod::isw
indix for sw
Definition at line 946 of file wam_climo_data.f90.
Referenced by globe7(), gtd7(), and tselec().
integer gettemp_mod::iyr
integer for a given year
Definition at line 947 of file wam_climo_data.f90.
Referenced by globe7().
real, dimension(150,9) gettemp_mod::pd
he density
Definition at line 907 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(25,2) gettemp_mod::pdl
turbo
Definition at line 909 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(9,4) gettemp_mod::plg
Legendre polynomial points.
Definition at line 931 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real, dimension(100,10) gettemp_mod::pma
middle and low temperature
Definition at line 911 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(150) gettemp_mod::ps
s parameter
Definition at line 908 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(150) gettemp_mod::pt
temperature
Definition at line 906 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(100,4) gettemp_mod::ptl
upper temperature
Definition at line 910 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real gettemp_mod::re
referenced height related to gsurf
Definition at line 926 of file wam_climo_data.f90.
Referenced by densm(), densu(), ghp7(), gtd7(), and scalh().
real gettemp_mod::rl
correction to specified mixing ratio at ground
Definition at line 894 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::s
scale inverse to temperature difference
Definition at line 882 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::s2tloc
sine of 2 time location
Definition at line 935 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::s3tloc
sine of 3 time location
Definition at line 937 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real, dimension(100) gettemp_mod::sam
semiannual mult sam
Definition at line 912 of file wam_climo_data.f90.
Referenced by gtd7().
real gettemp_mod::stloc
sine of the location
Definition at line 933 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real, dimension(25) gettemp_mod::sw
weighting
Definition at line 914 of file wam_climo_data.f90.
Referenced by glob7s(), globe7(), gtd7(), gts7(), tselec(), and vtst7().
real, dimension(25) gettemp_mod::swc
weighting
Definition at line 915 of file wam_climo_data.f90.
Referenced by glob7s(), globe7(), tselec(), and vtst7().
real gettemp_mod::t0
initial temperature
Definition at line 891 of file wam_climo_data.f90.
Referenced by gts7().
real, dimension(2) gettemp_mod::tgn1
temperature gradient at node 1 (~mesosphere)
Definition at line 902 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(2) gettemp_mod::tgn2
temperature gradient at node 2 (~stratosphere)
Definition at line 903 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(2) gettemp_mod::tgn3
temperature gradient at node 3 (~troposphere)
Definition at line 904 of file wam_climo_data.f90.
Referenced by gtd7().
real gettemp_mod::tinfg
startinf referenced point for tt
Definition at line 928 of file wam_climo_data.f90.
Referenced by globe7().
real gettemp_mod::tlb
labeled temperature
Definition at line 881 of file wam_climo_data.f90.
Referenced by gts7().
real, dimension(5) gettemp_mod::tn1
temperature at node 1 (~mesosphere)
Definition at line 899 of file wam_climo_data.f90.
Referenced by gtd7(), and gts7().
real, dimension(4) gettemp_mod::tn2
temperature at node 2 (~stratosphere)
Definition at line 900 of file wam_climo_data.f90.
Referenced by gtd7().
real, dimension(5) gettemp_mod::tn3
temperature at node 3 (~troposphere)
Definition at line 901 of file wam_climo_data.f90.
Referenced by gtd7().
real gettemp_mod::tr12
try factor 1 or 2
Definition at line 897 of file wam_climo_data.f90.
Referenced by gts7().
real, dimension(15) gettemp_mod::tt
referenced temperature
Definition at line 929 of file wam_climo_data.f90.
Referenced by globe7().
real gettemp_mod::xlong
a given longitude
Definition at line 944 of file wam_climo_data.f90.
Referenced by glob7s(), and globe7().
real gettemp_mod::z0
initial height
Definition at line 892 of file wam_climo_data.f90.
Referenced by gts7().
real gettemp_mod::za
joining altitude of bates and spline
Definition at line 890 of file wam_climo_data.f90.
Referenced by gts7().
Author
Generated automatically by Doxygen for chgres_cube from the source code.