.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/chgres_cube.fd/nst_input_data.F90" 3 "Mon Oct 23 2023" "Version 1.11.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/chgres_cube.fd/nst_input_data.F90 \- Read NST surface data from NEMSIO and NetCDF files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBnst_input_data::cleanup_input_nst_data\fP"
.br
.RI "Free up memory associated with nst data\&. "
.ti -1c
.RI "subroutine, public \fBnst_input_data::read_input_nst_data\fP (localpet)"
.br
.RI "Driver to read input grid nst data\&. "
.ti -1c
.RI "subroutine \fBnst_input_data::read_input_nst_nemsio_file\fP (localpet)"
.br
.RI "Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file\&. "
.ti -1c
.RI "subroutine \fBnst_input_data::read_input_nst_netcdf_file\fP (localpet)"
.br
.RI "Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::c_0_input_grid\fP"
.br
.RI "Coefficient 1 to calculate d(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::c_d_input_grid\fP"
.br
.RI "Coefficient 2 to calculate d(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::d_conv_input_grid\fP"
.br
.RI "Thickness of free convectionlayer\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::dt_cool_input_grid\fP"
.br
.RI "Sub-layer cooling amount\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::ifd_input_grid\fP"
.br
.RI "Model mode index\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::qrain_input_grid\fP"
.br
.RI "Sensible heat flux due torainfall\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::tref_input_grid\fP"
.br
.RI "Reference temperature\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::w_0_input_grid\fP"
.br
.RI "Coefficient 3 to calculated(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::w_d_input_grid\fP"
.br
.RI "Coefficient 4 to calculated(tz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::xs_input_grid\fP"
.br
.RI "Salinity content in diurnalthermocline layer\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::xt_input_grid\fP"
.br
.RI "Heat content in diurnalthermocline layer\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::xtts_input_grid\fP"
.br
.RI "d(xt)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::xu_input_grid\fP"
.br
.RI "u-current content in diurnalthermocline layer "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::xv_input_grid\fP"
.br
.RI "v-current content in diurnalthermocline layer "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::xz_input_grid\fP"
.br
.RI "Diurnal thermocline layerthickness\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::xzts_input_grid\fP"
.br
.RI "d(xz)/d(ts) "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::z_c_input_grid\fP"
.br
.RI "Sub-layer cooling thickness\&. "
.ti -1c
.RI "type(esmf_field), public \fBnst_input_data::zm_input_grid\fP"
.br
.RI "Oceanic mixed layer depth\&. "
.in -1c
.SH "Detailed Description"
.PP 
Read NST surface data from NEMSIO and NetCDF files\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition in file \fBnst_input_data\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public nst_input_data::cleanup_input_nst_data ()"

.PP
Free up memory associated with nst data\&. 
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 783 of file nst_input_data\&.F90\&.
.SS "subroutine, public nst_input_data::read_input_nst_data (integer, intent(in) localpet)"

.PP
Driver to read input grid nst data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP ESMF local persistent execution thread 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 68 of file nst_input_data\&.F90\&.
.PP
References model_grid::input_grid, and program_setup::input_type\&.
.SS "subroutine nst_input_data::read_input_nst_nemsio_file (integer, intent(in) localpet)"

.PP
Read input grid nst data from fv3 gaussian nemsio history file or spectral GFS nemsio file\&. 
.PP
\fBNote:\fP
.RS 4
The spectral GFS nst data is in a separate file from the surface data\&. The fv3 surface and nst data are in a single file\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP ESMF local persistent execution thread 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 515 of file nst_input_data\&.F90\&.
.PP
References program_setup::data_dir_input_grid, model_grid::i_input, program_setup::input_type, model_grid::j_input, program_setup::nst_files_input_grid, and program_setup::sfc_files_input_grid\&.
.SS "subroutine nst_input_data::read_input_nst_netcdf_file (integer, intent(in) localpet)"

.PP
Read nst data from these netcdf formatted fv3 files: tiled history, tiled warm restart, and gaussian history\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP ESMF local persistent execution thread 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 231 of file nst_input_data\&.F90\&.
.PP
References model_grid::i_input, program_setup::input_type, model_grid::j_input, and model_grid::num_tiles_input_grid\&.
.SH "Variable Documentation"
.PP 
.SS "type(esmf_field), public nst_input_data::c_0_input_grid"

.PP
Coefficient 1 to calculate d(tz)/d(ts) 
.PP
Definition at line 39 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::c_d_input_grid"

.PP
Coefficient 2 to calculate d(tz)/d(ts) 
.PP
Definition at line 38 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::d_conv_input_grid"

.PP
Thickness of free convectionlayer\&. 
.PP
Definition at line 40 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::dt_cool_input_grid"

.PP
Sub-layer cooling amount\&. 
.PP
Definition at line 41 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::ifd_input_grid"

.PP
Model mode index\&. 0-diurnalmodel not started; 1-diurnal model 
.PP
Definition at line 42 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::qrain_input_grid"

.PP
Sensible heat flux due torainfall\&. 
.PP
Definition at line 45 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::tref_input_grid"

.PP
Reference temperature\&. 
.PP
Definition at line 46 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::w_0_input_grid"

.PP
Coefficient 3 to calculated(tz)/d(ts) 
.PP
Definition at line 48 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::w_d_input_grid"

.PP
Coefficient 4 to calculated(tz)/d(ts) 
.PP
Definition at line 47 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xs_input_grid"

.PP
Salinity content in diurnalthermocline layer\&. 
.PP
Definition at line 49 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xt_input_grid"

.PP
Heat content in diurnalthermocline layer\&. 
.PP
Definition at line 50 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xtts_input_grid"

.PP
d(xt)/d(ts) 
.PP
Definition at line 54 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xu_input_grid"

.PP
u-current content in diurnalthermocline layer 
.PP
Definition at line 51 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xv_input_grid"

.PP
v-current content in diurnalthermocline layer 
.PP
Definition at line 52 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xz_input_grid"

.PP
Diurnal thermocline layerthickness\&. 
.PP
Definition at line 53 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::xzts_input_grid"

.PP
d(xz)/d(ts) 
.PP
Definition at line 55 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::z_c_input_grid"

.PP
Sub-layer cooling thickness\&. 
.PP
Definition at line 56 of file nst_input_data\&.F90\&.
.SS "type(esmf_field), public nst_input_data::zm_input_grid"

.PP
Oceanic mixed layer depth\&. 
.PP
Definition at line 57 of file nst_input_data\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
