.TH "program_setup" 3 "Thu Feb 15 2024" "Version 1.12.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
program_setup \- 
.PP
This module contains code to read the setup namelist file, handle the varmap file for GRIB2 data, and calculate the soil parameters\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine, public \fBcalc_soil_params_driver\fP (localpet)"
.br
.RI "\fIDriver routine to compute soil parameters for each soil type\&. \fP"
.ti -1c
.RI "subroutine, public \fBget_var_cond\fP (var_name, this_miss_var_method, this_miss_var_value, this_field_var_name, loc)"
.br
.RI "\fISearch the variable mapping table to find conditions for handling missing variables\&. \fP"
.ti -1c
.RI "subroutine, public \fBread_setup_namelist\fP (filename)"
.br
.RI "\fIReads program configuration namelist\&. \fP"
.ti -1c
.RI "subroutine, public \fBread_varmap\fP"
.br
.RI "\fIReads the variable mapping table, which is required for initializing with GRIB2 data\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "character(len=500), dimension(7), 
.br
public \fBatm_core_files_input_grid\fP = 'NULL'"
.br
.RI "\fIFile names of input atmospheric restart core files\&. \fP"
.ti -1c
.RI "character(len=500), dimension(6), 
.br
public \fBatm_files_input_grid\fP = 'NULL'"
.br
.RI "\fIFile names of input atmospheric data\&. \fP"
.ti -1c
.RI "character(len=500), dimension(6), 
.br
public \fBatm_tracer_files_input_grid\fP = 'NULL'"
.br
.RI "\fIFile names of input atmospheric restart tracer files\&. \fP"
.ti -1c
.RI "character(len=500), public \fBatm_weight_file\fP ='NULL'"
.br
.RI "\fIFile containing pre-computed weights to horizontally interpolate atmospheric fields\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBbb_target\fP"
.br
.RI "\fISoil 'b' parameter, target grid\&. \fP"
.ti -1c
.RI "character(len=20), dimension(:), 
.br
allocatable, public \fBchgres_var_names\fP"
.br
.RI "\fIVarmap table variable name as recognized by this program\&. \fP"
.ti -1c
.RI "logical, public \fBconvert_atm\fP = \&.false\&."
.br
.RI "\fIConvert atmospheric data when true\&. \fP"
.ti -1c
.RI "logical, public \fBconvert_nst\fP = \&.false\&."
.br
.RI "\fIConvert nst data when true\&. \fP"
.ti -1c
.RI "logical, public \fBconvert_sfc\fP = \&.false\&."
.br
.RI "\fIConvert sfc data when true\&. \fP"
.ti -1c
.RI "character(len=15), public \fBcres_target_grid\fP = 'NULL'"
.br
.RI "\fITarget grid resolution, i\&.e\&., C768\&. \fP"
.ti -1c
.RI "integer, public \fBcycle_day\fP = -999"
.br
.RI "\fICycle day\&. \fP"
.ti -1c
.RI "integer, public \fBcycle_hour\fP = -999"
.br
.RI "\fICycle hour\&. \fP"
.ti -1c
.RI "integer, public \fBcycle_mon\fP = -999"
.br
.RI "\fICycle month\&. \fP"
.ti -1c
.RI "integer, public \fBcycle_year\fP = -999"
.br
.RI "\fICycle year\&. \fP"
.ti -1c
.RI "character(len=500), public \fBdata_dir_input_grid\fP = 'NULL'"
.br
.RI "\fIDirectory containing input atm or sfc files\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBdrysmc_input\fP"
.br
.RI "\fIAir dry soil moisture content input grid\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBdrysmc_target\fP"
.br
.RI "\fIAir dry soil moisture content target grid\&. \fP"
.ti -1c
.RI "character(len=20), public \fBexternal_model\fP ='GFS'"
.br
.RI "\fIThe model that the input data is derived from\&. \fP"
.ti -1c
.RI "character(len=20), dimension(:), 
.br
allocatable, public \fBfield_var_names\fP"
.br
.RI "\fIThe GRIB2 variable name in the varmap table\&. \fP"
.ti -1c
.RI "character(len=500), public \fBfix_dir_target_grid\fP = 'NULL'"
.br
.RI "\fIDirectory containing target grid pre-computed fixed data (ex: soil type)\&. \fP"
.ti -1c
.RI "character(len=500), public \fBgeogrid_file_input_grid\fP = 'NULL'"
.br
.RI "\fIName of 'geogrid' file, which contains static surface fields on the input grid\&. \fP"
.ti -1c
.RI "character(len=500), public \fBgrib2_file_input_grid\fP = 'NULL'"
.br
.RI "\fIREQUIRED\&. \fP"
.ti -1c
.RI "integer, public \fBhalo_blend\fP = 0"
.br
.RI "\fINumber of row/cols of blending halo, where model tendencies and lateral boundary tendencies are applied\&. \fP"
.ti -1c
.RI "integer, public \fBhalo_bndy\fP = 0"
.br
.RI "\fINumber of row/cols of lateral halo, where pure lateral bndy conditions are applied (regional target grids)\&. \fP"
.ti -1c
.RI "character(len=25), public \fBinput_type\fP ='restart'"
.br
.RI "\fIInput data type: \fP"
.ti -1c
.RI "logical, public \fBlai_from_climo\fP = \&.true\&."
.br
.RI "\fIIf false, interpolate leaf area index from the input data to the target grid instead of using data from static data\&. \fP"
.ti -1c
.RI "integer, parameter, public \fBmax_tracers\fP =100"
.br
.RI "\fIMaximum number of atmospheric tracers processed\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBmaxsmc_input\fP"
.br
.RI "\fIMaximum soil moisture content input grid\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBmaxsmc_target\fP"
.br
.RI "\fIMaximum soil moisture content target grid\&. \fP"
.ti -1c
.RI "logical, public \fBminmax_vgfrc_from_climo\fP = \&.true\&."
.br
.RI "\fIIf false, interpolate min/max vegetation fraction from the input data to the target grid instead of using data from static data\&. \fP"
.ti -1c
.RI "character(len=20), dimension(:), 
.br
allocatable, public \fBmissing_var_methods\fP"
.br
.RI "\fIMethod to replace missing GRIB2 input records\&. \fP"
.ti -1c
.RI "real(kind=esmf_kind_r4), 
.br
dimension(:), allocatable, 
.br
public \fBmissing_var_values\fP"
.br
.RI "\fIIf input GRIB2 record is missing, the variable is set to this value\&. \fP"
.ti -1c
.RI "character(len=500), public \fBmosaic_file_input_grid\fP = 'NULL'"
.br
.RI "\fIInput grid mosaic file\&. \fP"
.ti -1c
.RI "character(len=500), public \fBmosaic_file_target_grid\fP = 'NULL'"
.br
.RI "\fITarget grid mosaic file\&. \fP"
.ti -1c
.RI "integer, public \fBnsoill_out\fP = 4"
.br
.RI "\fINumber of soil levels desired in the output data\&. \fP"
.ti -1c
.RI "character(len=500), public \fBnst_files_input_grid\fP = 'NULL'"
.br
.RI "\fIFile name of input nst data\&. \fP"
.ti -1c
.RI "integer, public \fBnum_tracers\fP"
.br
.RI "\fINumber of atmospheric tracers to be processed\&. \fP"
.ti -1c
.RI "integer, public \fBnum_tracers_input\fP"
.br
.RI "\fINumber of atmospheric tracers in input file\&. \fP"
.ti -1c
.RI "character(len=500), public \fBorog_dir_input_grid\fP = 'NULL'"
.br
.RI "\fIDirectory containing the input grid orography files\&. \fP"
.ti -1c
.RI "character(len=500), public \fBorog_dir_target_grid\fP = 'NULL'"
.br
.RI "\fIDirectory containing the target grid orography files\&. \fP"
.ti -1c
.RI "character(len=500), dimension(6), 
.br
public \fBorog_files_input_grid\fP = 'NULL'"
.br
.RI "\fIInput grid orography files\&. \fP"
.ti -1c
.RI "character(len=500), dimension(6), 
.br
public \fBorog_files_target_grid\fP = 'NULL'"
.br
.RI "\fITarget grid orography files\&. \fP"
.ti -1c
.RI "logical, dimension(:), 
.br
allocatable, public \fBread_from_input\fP"
.br
.RI "\fIWhen false, variable was not read from GRIB2 input file\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBrefsmc_input\fP"
.br
.RI "\fIReference soil moisture content input grid (onset of soil moisture stress)\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBrefsmc_target\fP"
.br
.RI "\fIReference soil moisture content target grid (onset of soil moisture stress)\&. \fP"
.ti -1c
.RI "integer, public \fBregional\fP = 0"
.br
.RI "\fIFor regional target grids\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBsatpsi_target\fP"
.br
.RI "\fISaturated soil potential, target grid\&. \fP"
.ti -1c
.RI "character(len=500), dimension(6), 
.br
public \fBsfc_files_input_grid\fP = 'NULL'"
.br
.RI "\fIFile names containing input surface data\&. \fP"
.ti -1c
.RI "logical, public \fBsotyp_from_climo\fP = \&.true\&."
.br
.RI "\fIIf false, interpolate soil type from the input data to the target grid instead of using data from static data\&. \fP"
.ti -1c
.RI "logical, public \fBtg3_from_soil\fP = \&.false\&."
.br
.RI "\fIIf false, use lowest level soil temperature for the base soil temperature instead of using data from static data\&. \fP"
.ti -1c
.RI "character(len=500), public \fBthomp_mp_climo_file\fP = 'NULL'"
.br
.RI "\fIPath/name to the Thompson MP climatology file\&. \fP"
.ti -1c
.RI "character(len=20), dimension(\fBmax_tracers\fP), 
.br
public \fBtracers\fP ='NULL'"
.br
.RI "\fIName of each atmos tracer to be processed\&. \fP"
.ti -1c
.RI "character(len=20), dimension(\fBmax_tracers\fP), 
.br
public \fBtracers_input\fP ='NULL'"
.br
.RI "\fIName of each atmos tracer record in the input file\&. \fP"
.ti -1c
.RI "logical, public \fBuse_thomp_mp_climo\fP =\&.false\&."
.br
.RI "\fIWhen true, read and process Thompson MP climatological tracers\&. \fP"
.ti -1c
.RI "character(len=500), public \fBvarmap_file\fP = 'NULL'"
.br
.RI "\fIREQUIRED\&. \fP"
.ti -1c
.RI "character(len=500), public \fBvcoord_file_target_grid\fP = 'NULL'"
.br
.RI "\fIVertical coordinate definition file\&. \fP"
.ti -1c
.RI "logical, public \fBvgfrc_from_climo\fP = \&.true\&."
.br
.RI "\fIIf false, interpolate vegetation fraction from the input data to the target grid instead of using data from static data\&. \fP"
.ti -1c
.RI "logical, public \fBvgtyp_from_climo\fP = \&.true\&."
.br
.RI "\fIIf false, interpolate vegetation type from the input data to the target grid instead of using data from static data\&. \fP"
.ti -1c
.RI "logical, public \fBwam_cold_start\fP = \&.false\&."
.br
.RI "\fIWhen true, cold start for whole atmosphere model\&. \fP"
.ti -1c
.RI "character(len=500), public \fBwam_parm_file\fP ='msis21\&.parm'"
.br
.RI "\fIFull path to msis21\&.parm for WAM initialization\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBwltsmc_input\fP"
.br
.RI "\fIPlant wilting point soil moisture content input grid\&. \fP"
.ti -1c
.RI "real, dimension(:), 
.br
allocatable, public \fBwltsmc_target\fP"
.br
.RI "\fIPlant wilting point soil moisture content target grid\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBcalc_soil_params\fP (num_soil_cats, smlow, smhigh, satdk, maxsmc, bb, satpsi, satdw, refsmc, drysmc, wltsmc)"
.br
.RI "\fICompute soil parameters\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This module contains code to read the setup namelist file, handle the varmap file for GRIB2 data, and calculate the soil parameters\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 9 of file program_setup\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine program_setup::calc_soil_params (integer, intent(in)num_soil_cats, real, intent(in)smlow, real, intent(in)smhigh, real, dimension(num_soil_cats), intent(in)satdk, real, dimension(num_soil_cats), intent(in)maxsmc, real, dimension(num_soil_cats), intent(in)bb, real, dimension(num_soil_cats), intent(in)satpsi, real, dimension(num_soil_cats), intent(out)satdw, real, dimension(num_soil_cats), intent(out)refsmc, real, dimension(num_soil_cats), intent(out)drysmc, real, dimension(num_soil_cats), intent(out)wltsmc)\fC [private]\fP"

.PP
Compute soil parameters\&. These will be used to rescale soil moisture differences in soil type between the input grid and target model grid\&.
.PP
\fBParameters:\fP
.RS 4
\fInum_soil_cats\fP number of soil type categories 
.br
\fIsmlow\fP reference parameter for wltsmc 
.br
\fIsmhigh\fP reference parameter for refsmc 
.br
\fIsatdk\fP saturated soil moisture hydraulic conductivity 
.br
\fImaxsmc\fP maximum soil moisture (porosity) 
.br
\fIbb\fP soil 'b' parameter 
.br
\fIsatpsi\fP saturated soil potential 
.br
\fIsatdw\fP saturated soil diffusivity/conductivity coefficient 
.br
\fIrefsmc\fP onset of soil moisture stress (field capacity) 
.br
\fIdrysmc\fP air dry soil moisture limit 
.br
\fIwltsmc\fP plant soil moisture wilting point 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 676 of file program_setup\&.F90\&.
.PP
Referenced by calc_soil_params_driver()\&.
.SS "subroutine, public program_setup::calc_soil_params_driver (integer, intent(in)localpet)"

.PP
Driver routine to compute soil parameters for each soil type\&. Works for Zobler and STATSGO soil categories\&.
.PP
The calculations are those used in the Noah Land Surface Model\&. For more information see \fCImplementation of Noah land surface model advances in the National Centers for Environmental Prediction operational mesoscale Eta model\fP\&.
.PP
For more details about the soil parameters/properties see \fCCoupling an Advanced Land Surface–Hydrology Model with the Penn State–NCAR MM5 Modeling System\&. Part I: Model Implementation and Sensitivity\fP\&.
.PP
The original source for soil properties is here:
.PP
Cosby, B\&. J\&., G\&. M\&. Hornberger, R\&. B\&. Clapp, and T\&. R\&. Ginn, 1984: \fCA statistical exploration of the relationships of soil moisture characteristics to the physical properties of soils\fP\&. Water Resour\&. Res\&.,20, 682–690\&.
.PP
The parameters in this subroutine were copied from https://github.com/HelinWei-NOAA/ccpp-physics/blob/master/physics/set_soilveg.f values need to be kept in sync with set_soilveg\&.f\&.
.PP
For more information about these parameters see https://github.com/HelinWei-NOAA/ccpp-physics/blob/master/physics/sflx.f\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocalpet\fP ESMF local persistent execution thread 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 516 of file program_setup\&.F90\&.
.PP
References calc_soil_params()\&.
.PP
Referenced by surface::surface_driver()\&.
.SS "subroutine, public program_setup::get_var_cond (character(len=20), intent(in)var_name, character(len=20), intent(out), optionalthis_miss_var_method, real(esmf_kind_r4), intent(out), optionalthis_miss_var_value, character(len=20), intent(out), optionalthis_field_var_name, integer, intent(out), optionalloc)"

.PP
Search the variable mapping table to find conditions for handling missing variables\&. Only applicable when using GRIB2 data as input\&.
.PP
\fBParameters:\fP
.RS 4
\fIvar_name\fP table variable name to search for 
.br
\fIthis_miss_var_method\fP the method used to replace missing data 
.br
\fIthis_miss_var_value\fP the value used to replace missing data 
.br
\fIthis_field_var_name\fP name of variable in output file\&. not currently implemented\&. 
.br
\fIloc\fP variable table location index 
.RE
.PP
\fBAuthor:\fP
.RS 4
Larissa Reames 
.PP
Jeff Beck 
.RE
.PP

.PP
Definition at line 445 of file program_setup\&.F90\&.
.PP
Referenced by sfc_input_data::read_grib_soil(), atm_input_data::read_input_atm_grib2_file(), sfc_input_data::read_input_sfc_grib2_file(), and atm_input_data::read_winds()\&.
.SS "subroutine, public program_setup::read_setup_namelist (character(len=*), intent(in), optionalfilename)"

.PP
Reads program configuration namelist\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP The name of the configuration file (defaults to \&./fort\&.41)\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 153 of file program_setup\&.F90\&.
.PP
References utilities::error_handler(), and utilities::to_lower()\&.
.PP
Referenced by chgres()\&.
.SS "subroutine, public program_setup::read_varmap ()"

.PP
Reads the variable mapping table, which is required for initializing with GRIB2 data\&. The varmap files has entries that look like this:
.PP
.PP
.nf
dzdt dzdt set_to_fill 0 D
.fi
.PP
.PP
These are the chgres_var_name, field_var_name, missing_var_method, missing_var_value, var_type\&.
.PP
The missing_var_method is one of:
.IP "\(bu" 2
set_to_fill
.IP "\(bu" 2
skip
.IP "\(bu" 2
stop
.PP
.PP
The var_type is one of:
.IP "\(bu" 2
T - tracer\&.
.IP "\(bu" 2
D - variables processed by atmosphere subroutine that are not tracers\&.
.IP "\(bu" 2
S - variables processed by surface subroutine that are not tracers\&.
.PP
.PP
\fBAuthor:\fP
.RS 4
Larissa Reames 
.PP
Jeff Beck 
.RE
.PP

.PP
Definition at line 375 of file program_setup\&.F90\&.
.PP
References utilities::error_handler()\&.
.PP
Referenced by chgres()\&.
.SH "Field Documentation"
.PP 
.SS "character(len=500), dimension(7), public program_setup::atm_core_files_input_grid = 'NULL'"

.PP
File names of input atmospheric restart core files\&. Only used for 'restart' input type\&. 
.PP
Definition at line 23 of file program_setup\&.F90\&.
.SS "character(len=500), dimension(6), public program_setup::atm_files_input_grid = 'NULL'"

.PP
File names of input atmospheric data\&. Not used for 'grib2' or 'restart' input types\&. 
.PP
Definition at line 19 of file program_setup\&.F90\&.
.SS "character(len=500), dimension(6), public program_setup::atm_tracer_files_input_grid = 'NULL'"

.PP
File names of input atmospheric restart tracer files\&. Only used for 'restart' input type\&. 
.PP
Definition at line 24 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::atm_weight_file ='NULL'"

.PP
File containing pre-computed weights to horizontally interpolate atmospheric fields\&. 
.PP
Definition at line 42 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::bb_target"

.PP
Soil 'b' parameter, target grid\&. 
.PP
Definition at line 136 of file program_setup\&.F90\&.
.SS "character(len=20), dimension(:), allocatable, public program_setup::chgres_var_names"

.PP
Varmap table variable name as recognized by this program\&. 
.PP
Definition at line 79 of file program_setup\&.F90\&.
.SS "logical, public program_setup::convert_atm = \&.false\&."

.PP
Convert atmospheric data when true\&. 
.PP
Definition at line 95 of file program_setup\&.F90\&.
.SS "logical, public program_setup::convert_nst = \&.false\&."

.PP
Convert nst data when true\&. 
.PP
Definition at line 96 of file program_setup\&.F90\&.
.SS "logical, public program_setup::convert_sfc = \&.false\&."

.PP
Convert sfc data when true\&. 
.PP
Definition at line 97 of file program_setup\&.F90\&.
.SS "character(len=15), public program_setup::cres_target_grid = 'NULL'"

.PP
Target grid resolution, i\&.e\&., C768\&. 
.PP
Definition at line 41 of file program_setup\&.F90\&.
.SS "integer, public program_setup::cycle_day = -999"

.PP
Cycle day\&. 
.PP
Definition at line 87 of file program_setup\&.F90\&.
.SS "integer, public program_setup::cycle_hour = -999"

.PP
Cycle hour\&. 
.PP
Definition at line 88 of file program_setup\&.F90\&.
.SS "integer, public program_setup::cycle_mon = -999"

.PP
Cycle month\&. 
.PP
Definition at line 86 of file program_setup\&.F90\&.
.SS "integer, public program_setup::cycle_year = -999"

.PP
Cycle year\&. 
.PP
Definition at line 85 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::data_dir_input_grid = 'NULL'"

.PP
Directory containing input atm or sfc files\&. 
.PP
Definition at line 25 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::drysmc_input"

.PP
Air dry soil moisture content input grid\&. 
.PP
Definition at line 128 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::drysmc_target"

.PP
Air dry soil moisture content target grid\&. 
.PP
Definition at line 129 of file program_setup\&.F90\&.
.SS "character(len=20), public program_setup::external_model ='GFS'"

.PP
The model that the input data is derived from\&. Current supported options are: 'GFS', 'HRRR', 'NAM', 'RAP'\&. Default: 'GFS' 
.PP
Definition at line 57 of file program_setup\&.F90\&.
.SS "character(len=20), dimension(:), allocatable, public program_setup::field_var_names"

.PP
The GRIB2 variable name in the varmap table\&. 
.PP
Definition at line 81 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::fix_dir_target_grid = 'NULL'"

.PP
Directory containing target grid pre-computed fixed data (ex: soil type)\&. 
.PP
Definition at line 26 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::geogrid_file_input_grid = 'NULL'"

.PP
Name of 'geogrid' file, which contains static surface fields on the input grid\&. GRIB2 option only\&. 
.PP
Definition at line 31 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::grib2_file_input_grid = 'NULL'"

.PP
REQUIRED\&. File name of grib2 input data\&. Assumes atmospheric and surface data are in a single file\&. 
.PP
Definition at line 30 of file program_setup\&.F90\&.
.SS "integer, public program_setup::halo_blend = 0"

.PP
Number of row/cols of blending halo, where model tendencies and lateral boundary tendencies are applied\&. Regional target grids only\&. 
.PP
Definition at line 92 of file program_setup\&.F90\&.
.SS "integer, public program_setup::halo_bndy = 0"

.PP
Number of row/cols of lateral halo, where pure lateral bndy conditions are applied (regional target grids)\&. 
.PP
Definition at line 91 of file program_setup\&.F90\&.
.SS "character(len=25), public program_setup::input_type ='restart'"

.PP
Input data type: 
.IP "\(bu" 2
'restart' for fv3 tiled warm restart files (netcdf)\&.
.IP "\(bu" 2
'history' for fv3 tiled history files (netcdf)\&.
.IP "\(bu" 2
'gaussian_nemsio' for fv3 gaussian nemsio files;
.IP "\(bu" 2
'gaussian_netcdf' for fv3 gaussian netcdf files\&.
.IP "\(bu" 2
'grib2' for grib2 files\&.
.IP "\(bu" 2
'gfs_gaussian_nemsio' for spectral gfs gaussian nemsio files
.IP "\(bu" 2
'gfs_sigio' for spectral gfs gfs sigio/sfcio files\&. 
.PP

.PP
Definition at line 43 of file program_setup\&.F90\&.
.SS "logical, public program_setup::lai_from_climo = \&.true\&."

.PP
If false, interpolate leaf area index from the input data to the target grid instead of using data from static data\&. Default: True\&. 
.PP
Definition at line 120 of file program_setup\&.F90\&.
.SS "integer, parameter, public program_setup::max_tracers =100"

.PP
Maximum number of atmospheric tracers processed\&. 
.PP
Definition at line 59 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::maxsmc_input"

.PP
Maximum soil moisture content input grid\&. 
.PP
Definition at line 130 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::maxsmc_target"

.PP
Maximum soil moisture content target grid\&. 
.PP
Definition at line 131 of file program_setup\&.F90\&.
.SS "logical, public program_setup::minmax_vgfrc_from_climo = \&.true\&."

.PP
If false, interpolate min/max vegetation fraction from the input data to the target grid instead of using data from static data\&. Use with caution as vegetation categories can vary\&. Default: True\&. 
.PP
Definition at line 116 of file program_setup\&.F90\&.
.SS "character(len=20), dimension(:), allocatable, public program_setup::missing_var_methods"

.PP
Method to replace missing GRIB2 input records\&. 
.PP
Definition at line 77 of file program_setup\&.F90\&.
.SS "real(kind=esmf_kind_r4), dimension(:), allocatable, public program_setup::missing_var_values"

.PP
If input GRIB2 record is missing, the variable is set to this value\&. 
.PP
Definition at line 138 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::mosaic_file_input_grid = 'NULL'"

.PP
Input grid mosaic file\&. Only used for 'restart' or 'history' input type\&. 
.PP
Definition at line 27 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::mosaic_file_target_grid = 'NULL'"

.PP
Target grid mosaic file\&. 
.PP
Definition at line 28 of file program_setup\&.F90\&.
.SS "integer, public program_setup::nsoill_out = 4"

.PP
Number of soil levels desired in the output data\&. chgres_cube can interpolate from 9 input to 4 output levels\&. DEFAULT: 4\&. 
.PP
Definition at line 93 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::nst_files_input_grid = 'NULL'"

.PP
File name of input nst data\&. Only used for input_type 'gfs_gaussian_nemsio'\&. 
.PP
Definition at line 29 of file program_setup\&.F90\&.
.SS "integer, public program_setup::num_tracers"

.PP
Number of atmospheric tracers to be processed\&. 
.PP
Definition at line 60 of file program_setup\&.F90\&.
.SS "integer, public program_setup::num_tracers_input"

.PP
Number of atmospheric tracers in input file\&. 
.PP
Definition at line 61 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::orog_dir_input_grid = 'NULL'"

.PP
Directory containing the input grid orography files\&. Only used for 'restart' or 'history' input types\&. 
.PP
Definition at line 34 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::orog_dir_target_grid = 'NULL'"

.PP
Directory containing the target grid orography files\&. 
.PP
Definition at line 36 of file program_setup\&.F90\&.
.SS "character(len=500), dimension(6), public program_setup::orog_files_input_grid = 'NULL'"

.PP
Input grid orography files\&. Only used for 'restart' or 'history' input types\&. 
.PP
Definition at line 35 of file program_setup\&.F90\&.
.SS "character(len=500), dimension(6), public program_setup::orog_files_target_grid = 'NULL'"

.PP
Target grid orography files\&. 
.PP
Definition at line 37 of file program_setup\&.F90\&.
.SS "logical, dimension(:), allocatable, public program_setup::read_from_input"

.PP
When false, variable was not read from GRIB2 input file\&. 
.PP
Definition at line 63 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::refsmc_input"

.PP
Reference soil moisture content input grid (onset of soil moisture stress)\&. 
.PP
Definition at line 132 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::refsmc_target"

.PP
Reference soil moisture content target grid (onset of soil moisture stress)\&. 
.PP
Definition at line 133 of file program_setup\&.F90\&.
.SS "integer, public program_setup::regional = 0"

.PP
For regional target grids\&. When '1' remove boundary halo region from atmospheric/surface data and output atmospheric boundary file\&. When '2' output boundary file only\&. Default is '0' (global grids)\&. 
.PP
Definition at line 89 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::satpsi_target"

.PP
Saturated soil potential, target grid\&. 
.PP
Definition at line 137 of file program_setup\&.F90\&.
.SS "character(len=500), dimension(6), public program_setup::sfc_files_input_grid = 'NULL'"

.PP
File names containing input surface data\&. Not used for 'grib2' input type\&. 
.PP
Definition at line 38 of file program_setup\&.F90\&.
.SS "logical, public program_setup::sotyp_from_climo = \&.true\&."

.PP
If false, interpolate soil type from the input data to the target grid instead of using data from static data\&. Use with caution as the code assumes input soil type use STATSGO soil categories\&. Default: True\&. 
.PP
Definition at line 106 of file program_setup\&.F90\&.
.SS "logical, public program_setup::tg3_from_soil = \&.false\&."

.PP
If false, use lowest level soil temperature for the base soil temperature instead of using data from static data\&. Default: False\&. 
.PP
Definition at line 123 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::thomp_mp_climo_file = 'NULL'"

.PP
Path/name to the Thompson MP climatology file\&. 
.PP
Definition at line 40 of file program_setup\&.F90\&.
.SS "character(len=20), dimension(\fBmax_tracers\fP), public program_setup::tracers ='NULL'"

.PP
Name of each atmos tracer to be processed\&. These names will be used to identify the tracer records in the output files\&. Follows the convention in the field table\&. FOR GRIB2 FILES: Not used\&. Tracers instead taken from the varmap file\&. 
.PP
Definition at line 66 of file program_setup\&.F90\&.
.SS "character(len=20), dimension(\fBmax_tracers\fP), public program_setup::tracers_input ='NULL'"

.PP
Name of each atmos tracer record in the input file\&. May be different from value in 'tracers'\&. FOR GRIB2 FILES: Not used\&. Tracers instead taken from the varmap file\&. 
.PP
Definition at line 72 of file program_setup\&.F90\&.
.SS "logical, public program_setup::use_thomp_mp_climo =\&.false\&."

.PP
When true, read and process Thompson MP climatological tracers\&. False, when 'thomp_mp_climo_file' is NULL\&. 
.PP
Definition at line 126 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::varmap_file = 'NULL'"

.PP
REQUIRED\&. Full path of the relevant varmap file\&. 
.PP
Definition at line 18 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::vcoord_file_target_grid = 'NULL'"

.PP
Vertical coordinate definition file\&. 
.PP
Definition at line 39 of file program_setup\&.F90\&.
.SS "logical, public program_setup::vgfrc_from_climo = \&.true\&."

.PP
If false, interpolate vegetation fraction from the input data to the target grid instead of using data from static data\&. Use with caution as vegetation categories can vary\&. Default: True\&. 
.PP
Definition at line 111 of file program_setup\&.F90\&.
.SS "logical, public program_setup::vgtyp_from_climo = \&.true\&."

.PP
If false, interpolate vegetation type from the input data to the target grid instead of using data from static data\&. Use with caution as vegetation categories can vary\&. Default: True\&. 
.PP
Definition at line 102 of file program_setup\&.F90\&.
.SS "logical, public program_setup::wam_cold_start = \&.false\&."

.PP
When true, cold start for whole atmosphere model\&. 
.PP
Definition at line 98 of file program_setup\&.F90\&.
.SS "character(len=500), public program_setup::wam_parm_file ='msis21\&.parm'"

.PP
Full path to msis21\&.parm for WAM initialization\&. 
.PP
Definition at line 83 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::wltsmc_input"

.PP
Plant wilting point soil moisture content input grid\&. 
.PP
Definition at line 134 of file program_setup\&.F90\&.
.SS "real, dimension(:), allocatable, public program_setup::wltsmc_target"

.PP
Plant wilting point soil moisture content target grid\&. 
.PP
Definition at line 135 of file program_setup\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
