.TH "search_util" 3 "Mon Oct 23 2023" "Version 1.11.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
search_util \- Replace undefined values with a valid value\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBsearch\fP (field, mask, idim, jdim, tile, field_num, latitude, terrain_land, soilt_climo)"
.br
.RI "Replace undefined surface values\&. "
.ti -1c
.RI "subroutine \fBsst_guess\fP (latitude, sst)"
.br
.RI "Set default Sea Surface Temperature (SST) based on latitude\&. "
.in -1c
.SH "Detailed Description"
.PP 
Replace undefined values with a valid value\&. 

This can happen for an isolated lake or island that is unresolved by the input grid\&.
.PP
Searches for the nearest valid land/non-land data where the input and target fv3 land-mask differ\&. Example: when the target FV3 grid depicts an island that is not resolved by the input data\&. If nearby valid data is not found, a default value is used\&.
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public search_util::search (real(esmf_kind_r8), dimension(idim,jdim), intent(inout) field, integer(esmf_kind_i8), dimension(idim,jdim), intent(in) mask, integer, intent(in) idim, integer, intent(in) jdim, integer, intent(in) tile, integer, intent(in) field_num, real(esmf_kind_r8), dimension(idim,jdim), intent(in), optional latitude, real(esmf_kind_r8), dimension(idim,jdim), intent(in), optional terrain_land, real(esmf_kind_r8), dimension(idim,jdim), intent(in), optional soilt_climo)"

.PP
Replace undefined surface values\&. Replace undefined values on the model grid with a valid value at a nearby neighbor\&. Undefined values are typically associated with isolated islands where there is no source data\&.
.PP
Routine searches a neighborhood with a radius of 100 grid points\&. If no valid value is found, a default value is used\&.
.PP
This routine works for one tile of a cubed sphere grid\&. It does not consider valid values at adjacent faces\&. That is a future upgrade\&.
.PP
\fBParameters:\fP
.RS 4
\fIfield\fP On input/output, surface data with undefined/no undefined values\&. 
.br
\fImask\fP land-mask of surface data\&. 
.br
\fIidim\fP 'i' dimension of tile 
.br
\fIjdim\fP 'j' dimension of tile 
.br
\fItile\fP tile number 
.br
\fIfield_num\fP surface field number 
.br
\fIlatitude\fP latitude of the surface data 
.br
\fIterrain_land\fP terrain height 
.br
\fIsoilt_climo\fP climatological soil type 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 47 of file search_util\&.F90\&.
.PP
References sst_guess()\&.
.PP
Referenced by surface::interp(), sfc_input_data::read_input_sfc_grib2_file(), and surface::search_many()\&.
.SS "subroutine search_util::sst_guess (real(esmf_kind_r8), intent(in) latitude, real(esmf_kind_r8), intent(out) sst)"

.PP
Set default Sea Surface Temperature (SST) based on latitude\&. Based loosely on the average annual SST values from \&./am/cfs_oi2sst1x1monclim19822001\&.grb
.PP
The temperature in the polar and tropical regions is set to 273\&.16 and 300\&.0 Kelvin respectively\&. Polar regions are poleward of 60 degrees\&. Tropical regions are within 30 degrees of the equator\&. In mid-latitudes, a linear change with latitude is used\&.
.PP
\fBParameters:\fP
.RS 4
\fIlatitude\fP Latitude in decimal degrees 
.br
\fIsst\fP Default SST in Kelvin 
.RE
.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition at line 235 of file search_util\&.F90\&.
.PP
Referenced by search()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
