.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/search_util.F90" 3 "Tue Jan 17 2023" "Version 1.9.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/search_util.F90 \- Replace undefined surface values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsearch_util\fP"
.br
.RI "Replace undefined values with a valid value\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBsearch_util::search\fP (field, mask, idim, jdim, tile, field_num, latitude, terrain_land, soilt_climo)"
.br
.RI "Replace undefined surface values\&. "
.ti -1c
.RI "subroutine \fBsearch_util::sst_guess\fP (latitude, sst)"
.br
.RI "Set default Sea Surface Temperature (SST) based on latitude\&. "
.in -1c
.SH "Detailed Description"
.PP 
Replace undefined surface values\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NCEP/EMC 
.RE
.PP

.PP
Definition in file \fBsearch_util\&.F90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
