static_data
NAME
static_data - Reads static surface climatological data for the target FV3 grid (such as soil type and vegetation type).
SYNOPSIS
Functions/Subroutines
subroutine, public cleanup_static_fields
Free up memory for fields in this module.
subroutine, public create_static_fields
Create ESMF fields for static target grid data.
subroutine, public get_static_fields (localpet)
Driver routine to read/time interpolate static/climo fields on the fv3 target grid.
subroutine read_static_file (field, i_target, j_target, tile, data_one_tile, max_data_one_tile, min_data_one_tile)
Read static climatological data file.
Variables
type(esmf_field), public alnsf_target_grid
near ir black sky albedo
type(esmf_field), public alnwf_target_grid
near ir white sky albedo
type(esmf_field), public alvsf_target_grid
visible black sky albedo
type(esmf_field), public alvwf_target_grid
visible white sky albedo
type(esmf_field), public facsf_target_grid
fractional coverage for strong zenith angle dependent albedo
type(esmf_field), public facwf_target_grid
fractional coverage for weak zenith angle dependent albedo
type(esmf_field), public max_veg_greenness_target_grid
maximum annual greenness fraction
type(esmf_field), public min_veg_greenness_target_grid
minimum annual greenness fraction
type(esmf_field), public mxsno_albedo_target_grid
maximum snow albedo
type(esmf_field), public slope_type_target_grid
slope type
type(esmf_field), public soil_type_target_grid
soil type
type(esmf_field), public substrate_temp_target_grid
soil subtrate temperature
type(esmf_field), public veg_greenness_target_grid
vegetation greenness fraction
type(esmf_field), public veg_type_target_grid
vegetation type
Detailed Description
Reads static surface climatological data for the target FV3 grid (such as soil type and vegetation type).
Time interpolates time-varying fields, such as monthly plant greenness, to the model run time. Data for each target FV3 resolution resides in the ‘fixed’ directory. Set path via the fix_dir_target_grid namelist variable.
Author:
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine, public static_data::cleanup_static_fields ()
Free up memory for fields in this module.
Author:
George Gayno NCEP/EMC
Definition at line 510 of file static_data.F90.
References alnsf_target_grid, alnwf_target_grid, alvsf_target_grid, alvwf_target_grid, facsf_target_grid, facwf_target_grid, max_veg_greenness_target_grid, min_veg_greenness_target_grid, mxsno_albedo_target_grid, slope_type_target_grid, soil_type_target_grid, substrate_temp_target_grid, veg_greenness_target_grid, and veg_type_target_grid.
Referenced by surface::surface_driver().
subroutine, public static_data::create_static_fields ()
Create ESMF fields for static target grid data.
Author:
George Gayno NCEP/EMC
Definition at line 399 of file static_data.F90.
References alnsf_target_grid, alnwf_target_grid, alvsf_target_grid, alvwf_target_grid, facsf_target_grid, facwf_target_grid, max_veg_greenness_target_grid, min_veg_greenness_target_grid, mxsno_albedo_target_grid, slope_type_target_grid, soil_type_target_grid, substrate_temp_target_grid, model_grid::target_grid, veg_greenness_target_grid, and veg_type_target_grid.
Referenced by get_static_fields().
subroutine, public static_data::get_static_fields (integer, intent(in) localpet)
Driver routine to read/time interpolate static/climo fields on the fv3 target grid.
Parameters:
localpet ESMF local persistent execution thread
Author:
George Gayno NCEP/EMC
Definition at line 50 of file static_data.F90.
References alnsf_target_grid, alnwf_target_grid, alvsf_target_grid, alvwf_target_grid, create_static_fields(), facsf_target_grid, facwf_target_grid, model_grid::i_target, model_grid::j_target, max_veg_greenness_target_grid, min_veg_greenness_target_grid, mxsno_albedo_target_grid, model_grid::num_tiles_target_grid, read_static_file(), slope_type_target_grid, soil_type_target_grid, substrate_temp_target_grid, veg_greenness_target_grid, and veg_type_target_grid.
Referenced by surface::surface_driver().
subroutine static_data::read_static_file (character(len=*), intent(in) field, integer, intent(in) i_target, integer, intent(in) j_target, integer, intent(in) tile, real(esmf_kind_r8), dimension(i_target,j_target), intent(out) data_one_tile, real(esmf_kind_r8), dimension(i_target,j_target), intent(out), optional max_data_one_tile, real(esmf_kind_r8), dimension(i_target,j_target), intent(out), optional min_data_one_tile)
Read static climatological data file.
Parameters:
field the name of the surface field to be processed
i_target the 'i' dimension of the target model tile
j_target the 'j' dimension of the target model tile
tile the tile number of be processed
data_one_tile the processed surface data on the tile
max_data_one_tile for fields with multiple time periods, the max yearly value on the tile
min_data_one_tile for fields with multiple time periods, the min yearly value on the tile
Author:
George Gayno NCEP/EMC
Definition at line 264 of file static_data.F90.
References program_setup::cres_target_grid, program_setup::cycle_day, program_setup::cycle_hour, program_setup::cycle_mon, program_setup::fix_dir_target_grid, and model_grid::tiles_target_grid.
Referenced by get_static_fields().
Variable Documentation
type(esmf_field), public static_data::alnsf_target_grid
near ir black sky albedo
Definition at line 25 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::alnwf_target_grid
near ir white sky albedo
Definition at line 26 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::alvsf_target_grid
visible black sky albedo
Definition at line 23 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::alvwf_target_grid
visible white sky albedo
Definition at line 24 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::facsf_target_grid
fractional coverage for strong zenith angle dependent albedo
Definition at line 27 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::facwf_target_grid
fractional coverage for weak zenith angle dependent albedo
Definition at line 28 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::max_veg_greenness_target_grid
maximum annual greenness fraction
Definition at line 29 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::min_veg_greenness_target_grid
minimum annual greenness fraction
Definition at line 30 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::mxsno_albedo_target_grid
maximum snow albedo
Definition at line 31 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::slope_type_target_grid
slope type
Definition at line 32 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::soil_type_target_grid
soil type
Definition at line 33 of file static_data.F90.
Referenced by surface::calc_liq_soil_moisture(), cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::interp(), surface::qc_check(), surface::rescale_soil_moisture(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::substrate_temp_target_grid
soil subtrate temperature
Definition at line 34 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::interp(), surface::qc_check(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::veg_greenness_target_grid
vegetation greenness fraction
Definition at line 35 of file static_data.F90.
Referenced by cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::interp(), surface::qc_check(), surface::rescale_soil_moisture(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public static_data::veg_type_target_grid
vegetation type
Definition at line 36 of file static_data.F90.
Referenced by surface::adjust_soilt_for_terrain(), surface::calc_liq_soil_moisture(), cleanup_static_fields(), create_static_fields(), get_static_fields(), surface::interp(), surface::qc_check(), surface::rescale_soil_moisture(), surface::roughness(), and write_data::write_fv3_sfc_data_netcdf().
Author
Generated automatically by Doxygen for chgres_cube from the source code.