surface
NAME
surface - Process surface and nst fields.
SYNOPSIS
Functions/Subroutines
subroutine adjust_soil_levels (localpet)
Adjust soil levels of the input grid if there is a mismatch between input and target grids.
subroutine adjust_soilt_for_terrain
Adjust soil temperature for changes in terrain height between the input and target grids.
subroutine calc_liq_soil_moisture
Compute liquid portion of the total soil moisture.
subroutine check_smois_land
Check soil mositure.
subroutine cleanup_target_nst_data
Free up memory once the target grid nst fields are no longer needed.
subroutine cleanup_target_sfc_data
Free up memory once the target grid surface fields are no longer needed.
subroutine create_nst_esmf_fields
Create ESMF fields for the target grid nst variables.
subroutine create_surface_esmf_fields
Create ESMF fields for the target grid surface variables.
real function frh2o (TKELV, SMC, SH2O, SMCMAX, BEXP, PSIS)
Calculate supercooled soil moisture.
subroutine ij_to_i_j (ij, itile, jtile, i, j)
Convert 1d index to 2d indices.
subroutine interp (localpet)
Horizontally interpolate surface fields from input to target FV3 grid using esmf routines.
subroutine nst_land_fill
nst is not active at land or sea ice points.
subroutine qc_check
Perform some quality control checks before output.
subroutine replace_land_sfcparams (localpet)
Replace bad surface points.
subroutine rescale_soil_moisture
Adjust soil moisture for changes in soil type between the input and target grids.
subroutine roughness
Set roughness length at land and sea ice.
subroutine, public surface_driver (localpet)
Driver routine to process surface/nst data.
Variables
real, parameter, private blim = 5.5
soil 'b' parameter limit
type(esmf_field), public c_0_target_grid
Coefficient 1 to calculate d(tz)/d(ts)
type(esmf_field), public c_d_target_grid
Coefficient 2 to calculate d(tz)/d(ts)
type(esmf_field), public canopy_mc_target_grid
canopy moisture content
type(esmf_field), public d_conv_target_grid
Thickness of free convection layer.
type(esmf_field), public dt_cool_target_grid
Sub-layer cooling amount.
type(esmf_field), public f10m_target_grid
log((z0+10)*1/z0) See sfc_diff.f for details
type(esmf_field), public ffmm_target_grid
log((z0+z1)*1/z0) See sfc_diff.f for details
real, parameter, private frz_h2o = 273.15
melting pt water
real, parameter, private frz_ice = 271.21
melting pt sea ice
real, parameter, private grav = 9.81
gravity
real, parameter, private hlice = 3.335E5
latent heat of fusion
type(esmf_field), public ifd_target_grid
Model mode index.
type(esmf_field), public lai_target_grid
leaf area index
type(esmf_field), public q2m_target_grid
2-m specific humidity
type(esmf_field), public qrain_target_grid
Sensible heat flux due to rainfall.
type(esmf_field), public seaice_depth_target_grid
sea ice depth
type(esmf_field), public seaice_fract_target_grid
sea ice fraction
type(esmf_field), public seaice_skin_temp_target_grid
sea ice skin temperature
type(esmf_field), public skin_temp_target_grid
skin temperature/sst
type(esmf_field), public snow_depth_target_grid
physical snow depth
type(esmf_field), public snow_liq_equiv_target_grid
liquid equiv snow depth
type(esmf_field), public soil_temp_target_grid
3-d soil temperature
type(esmf_field) soil_type_from_input_grid
soil type interpolated from input grid
type(esmf_field), public soilm_liq_target_grid
3-d liquid soil moisture
type(esmf_field), public soilm_tot_target_grid
3-d total soil moisture
type(esmf_field), public srflag_target_grid
snow/rain flag
type(esmf_field), public t2m_target_grid
2-m temperatrure
type(esmf_field) terrain_from_input_grid
terrain height interpolated from input grid
type(esmf_field) terrain_from_input_grid_land
terrain height interpolated from input grid at all land points
type(esmf_field), public tprcp_target_grid
precip
type(esmf_field), public tref_target_grid
reference temperature
type(esmf_field), public ustar_target_grid
friction velocity
integer, parameter veg_type_landice_target = 15
Vegetation type category that defines permanent land ice points.
type(esmf_field), public w_0_target_grid
Coefficient 3 to calculate d(tz)/d(ts)
type(esmf_field), public w_d_target_grid
Coefficient 4 to calculate d(tz)/d(ts)
type(esmf_field), public xs_target_grid
Salinity content in diurnal thermocline layer.
type(esmf_field), public xt_target_grid
Heat content in diurnal thermocline layer.
type(esmf_field), public xtts_target_grid
d(xt)/d(ts)
type(esmf_field), public xu_target_grid
u-current content in diurnal thermocline layer
type(esmf_field), public xv_target_grid
v-current content in diurnal thermocline layer
type(esmf_field), public xz_target_grid
Diurnal thermocline layer thickness.
type(esmf_field), public xzts_target_grid
d(xz)/d(ts)
type(esmf_field), public z0_target_grid
roughness length
type(esmf_field), public z_c_target_grid
Sub-layer cooling thickness.
type(esmf_field), public zm_target_grid
Oceanic mixed layer depth.
Detailed Description
Process surface and nst fields.
Interpolates fields from the input to target grids. Adjusts soil temperature according to differences in input and target grid terrain. Rescales soil moisture for soil type differences between input and target grid. Computes frozen portion of total soil moisture.
Assumes the input land data are Noah LSM-based, and the fv3 run will use the Noah LSM. NSST fields are not available when using GRIB2 input data.
Public variables are defined below. 'target' indicates field associated with the target grid. 'input' indicates field associated with the input grid.
Author
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine surface::adjust_soil_levels (integer, intent(in) localpet)
Adjust soil levels of the input grid if there is a mismatch between input and target grids. Presently can only convert from 9 to 4 levels.
Parameters
localpet ESMF local persistent execution thread
Author
Larissa Reames
Jeff Beck
Definition at line 3564 of file surface.F90.
References error_handler(), model_grid::i_input, model_grid::input_grid, model_grid::j_input, input_data::lsoil_input, model_grid::lsoil_target, input_data::soil_temp_input_grid, input_data::soilm_liq_input_grid, and input_data::soilm_tot_input_grid.
Referenced by surface_driver().
subroutine surface::adjust_soilt_for_terrain
Adjust soil temperature for changes in terrain height between the input and target grids.
Author
George Gayno NOAA/EMC
Definition at line 3488 of file surface.F90.
References error_handler(), model_grid::landmask_target_grid, soil_temp_target_grid, terrain_from_input_grid, model_grid::terrain_target_grid, veg_type_landice_target, and static_data::veg_type_target_grid.
Referenced by surface_driver().
subroutine surface::calc_liq_soil_moisture
Compute liquid portion of the total soil moisture.
Author
George Gayno NOAA/EMC
Definition at line 2522 of file surface.F90.
References program_setup::bb_target, blim, error_handler(), frh2o(), frz_h2o, grav, hlice, model_grid::landmask_target_grid, program_setup::maxsmc_target, program_setup::satpsi_target, soil_temp_target_grid, static_data::soil_type_target_grid, soilm_liq_target_grid, soilm_tot_target_grid, veg_type_landice_target, and static_data::veg_type_target_grid.
Referenced by surface_driver().
subroutine surface::check_smois_land
Check soil mositure. When using vegetation type from the input data instead of the orography file, there are frequently points with ~0 soil moisture at land points. For these points, set values in all relevant target grid surface arrays to fill values (done in check_smois_land) then run the search routine again to fill with appropriate values from nearby points (done in replace_land_sfcparams).
Author
Larissa Reames
Jeff Beck
Definition at line 2795 of file surface.F90.
References static_data::alnsf_target_grid, static_data::alnwf_target_grid, static_data::alvsf_target_grid, static_data::alvwf_target_grid, canopy_mc_target_grid, error_handler(), static_data::facsf_target_grid, static_data::facwf_target_grid, model_grid::landmask_target_grid, static_data::max_veg_greenness_target_grid, static_data::min_veg_greenness_target_grid, static_data::mxsno_albedo_target_grid, static_data::slope_type_target_grid, soil_temp_target_grid, static_data::soil_type_target_grid, soilm_tot_target_grid, static_data::veg_greenness_target_grid, veg_type_landice_target, and static_data::veg_type_target_grid.
subroutine surface::cleanup_target_nst_data [private]
Free up memory once the target grid nst fields are no longer needed.
Author
George Gayno NOAA/EMC
Definition at line 4824 of file surface.F90.
References c_0_target_grid, c_d_target_grid, d_conv_target_grid, dt_cool_target_grid, ifd_target_grid, qrain_target_grid, tref_target_grid, w_0_target_grid, w_d_target_grid, xs_target_grid, xt_target_grid, xtts_target_grid, xu_target_grid, xv_target_grid, xz_target_grid, xzts_target_grid, z_c_target_grid, and zm_target_grid.
Referenced by surface_driver().
subroutine surface::cleanup_target_sfc_data [private]
Free up memory once the target grid surface fields are no longer needed.
Author
George Gayno NOAA/EMC
Definition at line 4788 of file surface.F90.
References canopy_mc_target_grid, f10m_target_grid, ffmm_target_grid, q2m_target_grid, seaice_depth_target_grid, seaice_fract_target_grid, seaice_skin_temp_target_grid, skin_temp_target_grid, snow_depth_target_grid, snow_liq_equiv_target_grid, soil_temp_target_grid, soil_type_from_input_grid, soilm_liq_target_grid, soilm_tot_target_grid, srflag_target_grid, t2m_target_grid, terrain_from_input_grid, terrain_from_input_grid_land, tprcp_target_grid, ustar_target_grid, and z0_target_grid.
Referenced by surface_driver().
subroutine surface::create_nst_esmf_fields
Create ESMF fields for the target grid nst variables.
Author
George Gayno
Definition at line 4615 of file surface.F90.
References c_0_target_grid, c_d_target_grid, d_conv_target_grid, dt_cool_target_grid, error_handler(), ifd_target_grid, qrain_target_grid, model_grid::target_grid, tref_target_grid, w_0_target_grid, w_d_target_grid, xs_target_grid, xt_target_grid, xtts_target_grid, xu_target_grid, xv_target_grid, xz_target_grid, xzts_target_grid, z_c_target_grid, and zm_target_grid.
Referenced by surface_driver().
subroutine surface::create_surface_esmf_fields
Create ESMF fields for the target grid surface variables.
Author
George Gayno NOAA/EMC
Definition at line 4278 of file surface.F90.
References canopy_mc_target_grid, error_handler(), f10m_target_grid, ffmm_target_grid, lai_target_grid, model_grid::lsoil_target, q2m_target_grid, seaice_depth_target_grid, seaice_fract_target_grid, seaice_skin_temp_target_grid, skin_temp_target_grid, snow_depth_target_grid, snow_liq_equiv_target_grid, soil_temp_target_grid, soil_type_from_input_grid, soilm_liq_target_grid, soilm_tot_target_grid, srflag_target_grid, t2m_target_grid, model_grid::target_grid, terrain_from_input_grid, tprcp_target_grid, ustar_target_grid, and z0_target_grid.
Referenced by surface_driver().
real function surface::frh2o (real(esmf_kind_r8) TKELV, real(esmf_kind_r8) SMC, real(esmf_kind_r8) SH2O, real SMCMAX, real BEXP, real PSIS)
Calculate supercooled soil moisture. Calculate amount of supercooled liquid soil water content if temperature is below 273.15K. Requires Newton-type iteration to solve the nonlinear implicit equation given in eqn 17 of Koren et. al (1999, JGR, VOL 104(D16), 19569-19585).
New version (June 2001): Much faster and more accurate Newton iteration achieved by first taking log of eqn cited above -- less than 4 (typically 1 or 2) iterations achieves convergence. Also, explicit 1-step solution option for special case of parameter ck=0, which reduces the original implicit equation to a simpler explicit form, known as the 'Flerchinger eqn'. Improved handling of solution in the limit of freezing point temperature.
Parameters
tkelv Temperature (Kelvin)
smc Total soil moisture content (volumetric)
sh2O Liquid soil moisture content (volumetric)
smcmax Saturation soil moisture content
bexp Soil type 'b' parameter
psis Saturated soil matric potential
Returns
frh2O Supercooled liquid water content
Author
George Gayno NOAA/EMC
Date
2005-05-20
Definition at line 3182 of file surface.F90.
References blim, frz_h2o, grav, and hlice.
Referenced by calc_liq_soil_moisture().
subroutine surface::ij_to_i_j (integer(esmf_kind_i4), intent(in) ij, integer, intent(in) itile, integer, intent(in) jtile, integer, intent(out) i, integer, intent(out) j)
Convert 1d index to 2d indices.
Parameters
ij the 1d index
itile i-dimension of the tile
jtile j-dimension of the tile
i the 'i' index
j the 'j' index
Author
George Gayno NOAA/EMC
Definition at line 4759 of file surface.F90.
Referenced by interp().
subroutine surface::interp (integer, intent(in) localpet)
Horizontally interpolate surface fields from input to target FV3 grid using esmf routines.
Parameters
localpet ESMF local persistent execution thread
Author
George Gayno NOAA/EMC
Definition at line 309 of file surface.F90.
References input_data::c_0_input_grid, c_0_target_grid, input_data::c_d_input_grid, c_d_target_grid, input_data::canopy_mc_input_grid, canopy_mc_target_grid, program_setup::convert_nst, input_data::d_conv_input_grid, d_conv_target_grid, input_data::dt_cool_input_grid, dt_cool_target_grid, error_handler(), program_setup::external_model, input_data::f10m_input_grid, f10m_target_grid, input_data::ffmm_input_grid, ffmm_target_grid, model_grid::i_target, input_data::ifd_input_grid, ifd_target_grid, ij_to_i_j(), model_grid::input_grid, program_setup::input_type, model_grid::j_target, program_setup::lai_from_climo, input_data::lai_input_grid, lai_target_grid, model_grid::landmask_target_grid, input_data::landsea_mask_input_grid, model_grid::latitude_target_grid, model_grid::lsoil_target, input_data::max_veg_greenness_input_grid, static_data::max_veg_greenness_target_grid, input_data::min_veg_greenness_input_grid, static_data::min_veg_greenness_target_grid, program_setup::minmax_vgfrc_from_climo, model_grid::num_tiles_target_grid, input_data::q2m_input_grid, q2m_target_grid, input_data::qrain_input_grid, qrain_target_grid, input_data::seaice_depth_input_grid, seaice_depth_target_grid, input_data::seaice_fract_input_grid, seaice_fract_target_grid, input_data::seaice_skin_temp_input_grid, seaice_skin_temp_target_grid, model_grid::seamask_target_grid, search_util::search(), input_data::skin_temp_input_grid, skin_temp_target_grid, input_data::snow_depth_input_grid, snow_depth_target_grid, input_data::snow_liq_equiv_input_grid, snow_liq_equiv_target_grid, input_data::soil_temp_input_grid, soil_temp_target_grid, soil_type_from_input_grid, input_data::soil_type_input_grid, static_data::soil_type_target_grid, input_data::soilm_tot_input_grid, soilm_tot_target_grid, program_setup::sotyp_from_climo, input_data::srflag_input_grid, srflag_target_grid, static_data::substrate_temp_target_grid, input_data::t2m_input_grid, t2m_target_grid, model_grid::target_grid, terrain_from_input_grid, terrain_from_input_grid_land, input_data::terrain_input_grid, program_setup::tg3_from_soil, input_data::tprcp_input_grid, tprcp_target_grid, input_data::tref_input_grid, tref_target_grid, input_data::ustar_input_grid, ustar_target_grid, input_data::veg_greenness_input_grid, static_data::veg_greenness_target_grid, input_data::veg_type_input_grid, input_data::veg_type_landice_input, veg_type_landice_target, static_data::veg_type_target_grid, program_setup::vgfrc_from_climo, program_setup::vgtyp_from_climo, input_data::w_0_input_grid, w_0_target_grid, input_data::w_d_input_grid, w_d_target_grid, input_data::xs_input_grid, xs_target_grid, input_data::xt_input_grid, xt_target_grid, input_data::xtts_input_grid, xtts_target_grid, input_data::xu_input_grid, xu_target_grid, input_data::xv_input_grid, xv_target_grid, input_data::xz_input_grid, xz_target_grid, input_data::xzts_input_grid, xzts_target_grid, input_data::z0_input_grid, z0_target_grid, input_data::z_c_input_grid, z_c_target_grid, input_data::zm_input_grid, and zm_target_grid.
Referenced by surface_driver().
subroutine surface::nst_land_fill
nst is not active at land or sea ice points. Set nst fields to flag values at these points.
Author
George Gayno NOAA/EMC
Definition at line 4069 of file surface.F90.
References c_0_target_grid, c_d_target_grid, d_conv_target_grid, dt_cool_target_grid, error_handler(), ifd_target_grid, model_grid::landmask_target_grid, qrain_target_grid, skin_temp_target_grid, tref_target_grid, w_0_target_grid, w_d_target_grid, xs_target_grid, xt_target_grid, xtts_target_grid, xu_target_grid, xv_target_grid, xz_target_grid, xzts_target_grid, z_c_target_grid, and zm_target_grid.
Referenced by surface_driver().
subroutine surface::qc_check
Perform some quality control checks before output.
Author
George Gayno NOAA/EMC
Definition at line 3734 of file surface.F90.
References static_data::alnsf_target_grid, static_data::alnwf_target_grid, static_data::alvsf_target_grid, static_data::alvwf_target_grid, canopy_mc_target_grid, error_handler(), static_data::facsf_target_grid, static_data::facwf_target_grid, frz_ice, model_grid::landmask_target_grid, static_data::max_veg_greenness_target_grid, static_data::min_veg_greenness_target_grid, static_data::mxsno_albedo_target_grid, seaice_depth_target_grid, seaice_fract_target_grid, seaice_skin_temp_target_grid, skin_temp_target_grid, static_data::slope_type_target_grid, snow_depth_target_grid, snow_liq_equiv_target_grid, soil_temp_target_grid, static_data::soil_type_target_grid, soilm_liq_target_grid, soilm_tot_target_grid, static_data::substrate_temp_target_grid, static_data::veg_greenness_target_grid, veg_type_landice_target, and static_data::veg_type_target_grid.
Referenced by surface_driver().
subroutine surface::replace_land_sfcparams (integer, intent(in) localpet)
Replace bad surface points. When using vegetation type from the input data instead of the orography file, there are frequently points with ~0 soil moisture at land points. For these points, set values in all relevant target grid surface arrays to fill values (done in check_smois_land) then run the search routine again to fill with appropriate values from nearby points (done in replace_land_sfcparams).
Parameters
localpet ESMF local persistent execution thread
Author
Larissa Reames
Jeff Beck
Definition at line 2979 of file surface.F90.
References static_data::alnsf_target_grid, static_data::alnwf_target_grid, static_data::alvsf_target_grid, static_data::alvwf_target_grid, canopy_mc_target_grid, error_handler(), static_data::facsf_target_grid, static_data::facwf_target_grid, model_grid::i_target, model_grid::j_target, model_grid::landmask_target_grid, model_grid::lsoil_target, static_data::max_veg_greenness_target_grid, static_data::min_veg_greenness_target_grid, static_data::mxsno_albedo_target_grid, search_util::search(), static_data::slope_type_target_grid, soil_temp_target_grid, static_data::soil_type_target_grid, soilm_tot_target_grid, static_data::veg_greenness_target_grid, and static_data::veg_type_target_grid.
subroutine surface::rescale_soil_moisture
Adjust soil moisture for changes in soil type between the input and target grids. Works for Noah land model only. Required to preserve latent/sensible heat fluxes.
Author
George Gayno NOAA/EMC
Definition at line 3320 of file surface.F90.
References program_setup::drysmc_input, program_setup::drysmc_target, error_handler(), model_grid::landmask_target_grid, program_setup::maxsmc_input, program_setup::maxsmc_target, program_setup::refsmc_input, program_setup::refsmc_target, soil_type_from_input_grid, static_data::soil_type_target_grid, soilm_tot_target_grid, static_data::veg_greenness_target_grid, veg_type_landice_target, static_data::veg_type_target_grid, program_setup::wltsmc_input, and program_setup::wltsmc_target.
Referenced by surface_driver().
subroutine surface::roughness
Set roughness length at land and sea ice. At land, roughness is set from a lookup table based on the vegetation type. At sea ice, roughness is set to 1 cm.
Author
George Gayno NOAA/EMC
Definition at line 3680 of file surface.F90.
References error_handler(), model_grid::landmask_target_grid, static_data::veg_type_target_grid, and z0_target_grid.
Referenced by surface_driver().
subroutine, public surface::surface_driver (integer, intent(in) localpet)
Driver routine to process surface/nst data.
Parameters
localpet ESMF local persistent execution thread
Author
George Gayno NCEP/EMC
Definition at line 150 of file surface.F90.
References adjust_soil_levels(), adjust_soilt_for_terrain(), calc_liq_soil_moisture(), program_setup::calc_soil_params_driver(), input_data::cleanup_input_nst_data(), input_data::cleanup_input_sfc_data(), static_data::cleanup_static_fields(), cleanup_target_nst_data(), cleanup_target_sfc_data(), program_setup::convert_nst, create_nst_esmf_fields(), create_surface_esmf_fields(), static_data::get_static_fields(), interp(), nst_land_fill(), qc_check(), input_data::read_input_nst_data(), input_data::read_input_sfc_data(), rescale_soil_moisture(), roughness(), program_setup::sotyp_from_climo, program_setup::vgtyp_from_climo, and write_fv3_sfc_data_netcdf().
Referenced by chgres().
Variable Documentation
real, parameter, private surface::blim = 5.5 [private]
soil 'b' parameter limit
Definition at line 130 of file surface.F90.
Referenced by calc_liq_soil_moisture(), and frh2o().
type(esmf_field), public surface::c_0_target_grid
Coefficient 1 to calculate d(tz)/d(ts)
Definition at line 80 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::c_d_target_grid
Coefficient 2 to calculate d(tz)/d(ts)
Definition at line 78 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::canopy_mc_target_grid
canopy moisture content
Definition at line 36 of file surface.F90.
Referenced by check_smois_land(), cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), replace_land_sfcparams(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::d_conv_target_grid
Thickness of free convection layer.
Definition at line 82 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::dt_cool_target_grid
Sub-layer cooling amount.
Definition at line 84 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::f10m_target_grid
log((z0+10)*1/z0) See sfc_diff.f for details
Definition at line 38 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::ffmm_target_grid
log((z0+z1)*1/z0) See sfc_diff.f for details
Definition at line 41 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
real, parameter, private surface::frz_h2o = 273.15 [private]
melting pt water
Definition at line 132 of file surface.F90.
Referenced by calc_liq_soil_moisture(), and frh2o().
real, parameter, private surface::frz_ice = 271.21 [private]
melting pt sea ice
Definition at line 134 of file surface.F90.
Referenced by qc_check().
real, parameter, private surface::grav = 9.81 [private]
gravity
Definition at line 136 of file surface.F90.
Referenced by calc_liq_soil_moisture(), and frh2o().
real, parameter, private surface::hlice = 3.335E5 [private]
latent heat of fusion
Definition at line 138 of file surface.F90.
Referenced by calc_liq_soil_moisture(), and frh2o().
type(esmf_field), public surface::ifd_target_grid
Model mode index. 0-diurnal model not started; 1-diurnal model started.
Definition at line 86 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::lai_target_grid
leaf area index
Definition at line 74 of file surface.F90.
Referenced by create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::q2m_target_grid
2-m specific humidity
Definition at line 44 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::qrain_target_grid
Sensible heat flux due to rainfall.
Definition at line 89 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::seaice_depth_target_grid
sea ice depth
Definition at line 46 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::seaice_fract_target_grid
sea ice fraction
Definition at line 48 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::seaice_skin_temp_target_grid
sea ice skin temperature
Definition at line 50 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::skin_temp_target_grid
skin temperature/sst
Definition at line 52 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), nst_land_fill(), qc_check(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::snow_depth_target_grid
physical snow depth
Definition at line 58 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::snow_liq_equiv_target_grid
liquid equiv snow depth
Definition at line 56 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::soil_temp_target_grid
3-d soil temperature
Definition at line 60 of file surface.F90.
Referenced by adjust_soilt_for_terrain(), calc_liq_soil_moisture(), check_smois_land(), cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), replace_land_sfcparams(), and write_fv3_sfc_data_netcdf().
type(esmf_field) surface::soil_type_from_input_grid [private]
soil type interpolated from input grid
Definition at line 120 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and rescale_soil_moisture().
type(esmf_field), public surface::soilm_liq_target_grid
3-d liquid soil moisture
Definition at line 62 of file surface.F90.
Referenced by calc_liq_soil_moisture(), cleanup_target_sfc_data(), create_surface_esmf_fields(), qc_check(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::soilm_tot_target_grid
3-d total soil moisture
Definition at line 64 of file surface.F90.
Referenced by calc_liq_soil_moisture(), check_smois_land(), cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), qc_check(), replace_land_sfcparams(), rescale_soil_moisture(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::srflag_target_grid
snow/rain flag
Definition at line 54 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::t2m_target_grid
2-m temperatrure
Definition at line 66 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
type(esmf_field) surface::terrain_from_input_grid [private]
terrain height interpolated from input grid
Definition at line 123 of file surface.F90.
Referenced by adjust_soilt_for_terrain(), cleanup_target_sfc_data(), create_surface_esmf_fields(), and interp().
type(esmf_field) surface::terrain_from_input_grid_land [private]
terrain height interpolated from input grid at all land points
Definition at line 126 of file surface.F90.
Referenced by cleanup_target_sfc_data(), and interp().
type(esmf_field), public surface::tprcp_target_grid
precip
Definition at line 68 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::tref_target_grid
reference temperature
Definition at line 91 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::ustar_target_grid
friction velocity
Definition at line 70 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), and write_fv3_sfc_data_netcdf().
integer, parameter surface::veg_type_landice_target = 15 [private]
Vegetation type category that defines permanent land ice points. The Noah LSM land ice physics are applied at these points.
Definition at line 29 of file surface.F90.
Referenced by adjust_soilt_for_terrain(), calc_liq_soil_moisture(), check_smois_land(), interp(), qc_check(), and rescale_soil_moisture().
type(esmf_field), public surface::w_0_target_grid
Coefficient 3 to calculate d(tz)/d(ts)
Definition at line 95 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::w_d_target_grid
Coefficient 4 to calculate d(tz)/d(ts)
Definition at line 93 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::xs_target_grid
Salinity content in diurnal thermocline layer.
Definition at line 97 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::xt_target_grid
Heat content in diurnal thermocline layer.
Definition at line 100 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::xtts_target_grid
d(xt)/d(ts)
Definition at line 111 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::xu_target_grid
u-current content in diurnal thermocline layer
Definition at line 103 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::xv_target_grid
v-current content in diurnal thermocline layer
Definition at line 106 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::xz_target_grid
Diurnal thermocline layer thickness.
Definition at line 109 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::xzts_target_grid
d(xz)/d(ts)
Definition at line 113 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::z0_target_grid
roughness length
Definition at line 72 of file surface.F90.
Referenced by cleanup_target_sfc_data(), create_surface_esmf_fields(), interp(), roughness(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::z_c_target_grid
Sub-layer cooling thickness.
Definition at line 115 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
type(esmf_field), public surface::zm_target_grid
Oceanic mixed layer depth.
Definition at line 117 of file surface.F90.
Referenced by cleanup_target_nst_data(), create_nst_esmf_fields(), interp(), nst_land_fill(), and write_fv3_sfc_data_netcdf().
Author
Generated automatically by Doxygen for chgres_cube from the source code.