.TH "thompson_mp_climo_data" 3 "Thu Feb 15 2024" "Version 1.12.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thompson_mp_climo_data \- 
.PP
Module to read the Thompson climatological MP data file and set up the associated esmf field and grid objects\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine, public \fBcleanup_thomp_mp_climo_input_data\fP"
.br
.RI "\fIFree up memory associated with this module\&. \fP"
.ti -1c
.RI "subroutine, public \fBread_thomp_mp_climo_data\fP"
.br
.RI "\fIRead Thompson climatological MP data file and time interpolate data to current cycle time\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "integer, public \fBlev_thomp_mp_climo\fP"
.br
.RI "\fInumber of vert lvls of Thompson climo data \fP"
.ti -1c
.RI "type(esmf_field), public \fBqnifa_climo_input_grid\fP"
.br
.RI "\fInumber concentration of ice friendly nuclei\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBqnwfa_climo_input_grid\fP"
.br
.RI "\fInumber concentration of water friendly nuclei\&. \fP"
.ti -1c
.RI "type(esmf_field), public \fBthomp_pres_climo_input_grid\fP"
.br
.RI "\fI3-d pressure of the Thompson climo data points \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "integer \fBi_thomp_mp_climo\fP"
.br
.RI "\fIi-dimension of Thompson climo data \fP"
.ti -1c
.RI "integer \fBj_thomp_mp_climo\fP"
.br
.RI "\fIj-dimension of Thompson climo data \fP"
.ti -1c
.RI "type(esmf_grid) \fBthomp_mp_climo_grid\fP"
.br
.RI "\fIesmf grid object for Thompson data grid \fP"
.in -1c
.SH "Detailed Description"
.PP 
Module to read the Thompson climatological MP data file and set up the associated esmf field and grid objects\&. 


.PP
\fBAuthor:\fP
.RS 4
George Gayno NOAA/EMC 
.RE
.PP

.PP
Definition at line 9 of file thompson_mp_climo_data\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine, public thompson_mp_climo_data::cleanup_thomp_mp_climo_input_data ()"

.PP
Free up memory associated with this module\&. 
.PP
\fBAuthor:\fP
.RS 4
George Gayno NOAA/EMC 
.RE
.PP

.PP
Definition at line 328 of file thompson_mp_climo_data\&.F90\&.
.PP
Referenced by atmosphere::horiz_interp_thomp_mp_climo()\&.
.SS "subroutine, public thompson_mp_climo_data::read_thomp_mp_climo_data ()"

.PP
Read Thompson climatological MP data file and time interpolate data to current cycle time\&. 
.PP
\fBAuthor:\fP
.RS 4
George Gayno NOAA/EMC 
.RE
.PP

.PP
Definition at line 50 of file thompson_mp_climo_data\&.F90\&.
.PP
References utilities::error_handler(), and utilities::netcdf_err()\&.
.PP
Referenced by atmosphere::atmosphere_driver()\&.
.SH "Field Documentation"
.PP 
.SS "integer thompson_mp_climo_data::i_thomp_mp_climo\fC [private]\fP"

.PP
i-dimension of Thompson climo data 
.PP
Definition at line 21 of file thompson_mp_climo_data\&.F90\&.
.SS "integer thompson_mp_climo_data::j_thomp_mp_climo\fC [private]\fP"

.PP
j-dimension of Thompson climo data 
.PP
Definition at line 23 of file thompson_mp_climo_data\&.F90\&.
.SS "integer, public thompson_mp_climo_data::lev_thomp_mp_climo"

.PP
number of vert lvls of Thompson climo data 
.PP
Definition at line 25 of file thompson_mp_climo_data\&.F90\&.
.SS "type(esmf_field), public thompson_mp_climo_data::qnifa_climo_input_grid"

.PP
number concentration of ice friendly nuclei\&. 
.PP
Definition at line 31 of file thompson_mp_climo_data\&.F90\&.
.SS "type(esmf_field), public thompson_mp_climo_data::qnwfa_climo_input_grid"

.PP
number concentration of water friendly nuclei\&. 
.PP
Definition at line 34 of file thompson_mp_climo_data\&.F90\&.
.SS "type(esmf_grid) thompson_mp_climo_data::thomp_mp_climo_grid\fC [private]\fP"

.PP
esmf grid object for Thompson data grid 
.PP
Definition at line 28 of file thompson_mp_climo_data\&.F90\&.
.SS "type(esmf_field), public thompson_mp_climo_data::thomp_pres_climo_input_grid"

.PP
3-d pressure of the Thompson climo data points 
.PP
Definition at line 37 of file thompson_mp_climo_data\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
