.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/utils.F90" 3 "Tue Jan 17 2023" "Version 1.9.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/chgres_cube.fd/utils.F90 \- Contains utility routines\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fButilities::check_cnwat\fP (cnwat, i_input, j_input)"
.br
.RI "When using GEFS data, some points on the target grid have unreasonable canpy moisture content, so zero out any locations with unrealistic canopy moisture values (>0\&.5)\&. "
.ti -1c
.RI "subroutine \fButilities::check_soilt\fP (soilt, landmask, skint, ICET_DEFAULT, i_input, j_input, lsoil_input)"
.br
.RI "Check for and replace certain values in soil temperature\&. "
.ti -1c
.RI "subroutine \fButilities::DINT2P\fP (PPIN, XXIN, NPIN, PPOUT, XXOUT, NPOUT, LINLOG, XMSG, IER)"
.br
.RI "Pressure to presure vertical interpolation for tracers with linear or lnP interpolation\&. "
.ti -1c
.RI "subroutine \fButilities::error_handler\fP (string, rc)"
.br
.RI "General error handler\&. "
.ti -1c
.RI "subroutine \fButilities::handle_grib_error\fP (vname, lev, method, value, varnum, read_from_input, iret, var, var8, var3d)"
.br
.RI "Handle GRIB2 read error based on the user selected method in the varmap file\&. "
.ti -1c
.RI "subroutine \fButilities::netcdf_err\fP (err, string)"
.br
.RI "Error handler for netcdf\&. "
.ti -1c
.RI "recursive subroutine \fButilities::quicksort\fP (a, first, last)"
.br
.RI "Sort an array of values\&. "
.ti -1c
.RI "subroutine \fButilities::to_lower\fP (strIn)"
.br
.RI "Convert from upper to lowercase\&. "
.ti -1c
.RI "character(len=len(strin)) function \fButilities::to_upper\fP (strIn)"
.br
.RI "Convert string from lower to uppercase\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains utility routines\&. 


.PP
Definition in file \fButils\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine utilities::check_cnwat (real(esmf_kind_r8), dimension(i_input,j_input), intent(inout) cnwat, integer, intent(in) i_input, integer, intent(in) j_input)"

.PP
When using GEFS data, some points on the target grid have unreasonable canpy moisture content, so zero out any locations with unrealistic canopy moisture values (>0\&.5)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcnwat\fP [input] 2-dimensional canopy moisture content 
.br
\fIi_input\fP [in] i-dimension of input grid 
.br
\fIj_input\fP [in] j-dimension of input grid 
.RE
.PP
\fBAuthor:\fP
.RS 4
Larissa Reames CIMMS/NSSL 
.RE
.PP

.PP
Definition at line 265 of file utils\&.F90\&.
.SS "subroutine utilities::check_soilt (real(esmf_kind_r8), dimension(i_input,j_input,lsoil_input), intent(inout) soilt, integer(esmf_kind_i4), dimension(i_input,j_input), intent(in) landmask, real(esmf_kind_r8), dimension(i_input,j_input), intent(in) skint, real, intent(in) ICET_DEFAULT, integer, intent(in) i_input, integer, intent(in) j_input, integer, intent(in) lsoil_input)"

.PP
Check for and replace certain values in soil temperature\&. At open water points (landmask=0) use skin temperature as a filler value\&. At land points (landmask=1) with excessive soil temperature, replace soil temperature with skin temperature\&. In GEFSv12\&.0 data there are some erroneous missing values at land points which this corrects\&. At sea ice points (landmask=2), store a default ice column temperature because grib2 files do not have ice column temperature which FV3 expects at these points\&.
.PP
\fBParameters:\fP
.RS 4
\fIsoilt\fP [inout] 3-dimensional soil temperature arrray 
.br
\fIlandmask\fP [in] landmask of the input grid 
.br
\fIskint\fP [in] 2-dimensional skin temperature array 
.br
\fIICET_DEFAULT\fP [in] Default temperature to apply at ice points 
.br
\fIi_input\fP [in] i-dimension of input grid 
.br
\fIj_input\fP [in] j-dimension of input grid 
.br
\fIlsoil_input\fP [in] soil layers dimension of input grid 
.RE
.PP
\fBAuthor:\fP
.RS 4
Larissa Reames CIMMS/NSSL 
.RE
.PP

.PP
Definition at line 230 of file utils\&.F90\&.
.SS "subroutine utilities::DINT2P (real*8, dimension(npin) PPIN, real*8, dimension(npin) XXIN, integer NPIN, real*8, dimension(npout) PPOUT, real*8, dimension(npout) XXOUT, integer NPOUT, integer LINLOG, real*8 XMSG, integer IER)"

.PP
Pressure to presure vertical interpolation for tracers with linear or lnP interpolation\&. Input tracers on pres levels are interpolated to the target output pressure levels\&. The matching levels of input and output will keep the same\&. Extrapolation is also allowed but needs caution\&. The routine is mostly for GFSV16 combined grib2 input when spfh has missing levels in low and mid troposphere from U/T/HGT/DZDT\&.
.PP
\fBParameters:\fP
.RS 4
\fIppin\fP 1d input pres levs 
.br
\fIxxin\fP 1d input tracer 
.br
\fInpin\fP number of input levs 
.br
\fIppout\fP 1d target pres levs 
.br
\fIxxout\fP 1d interpolated tracer 
.br
\fInpout\fP number of target levs 
.br
\fIlinlog\fP interp method\&.1:linear;not 1:log;neg:extrp allowed 
.br
\fIxmsg\fP fill values of missing levels (-999\&.0) 
.br
\fIier\fP error status\&. non 0: failed interpolation 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jili Dong NCEP/EMC 
.br
 
.RE
.PP
\fBDate:\fP
.RS 4
2021/07/30 
.RE
.PP

.PP
Definition at line 301 of file utils\&.F90\&.
.SS "subroutine utilities::error_handler (character(len=*), intent(in) string, integer, intent(in) rc)"

.PP
General error handler\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP error message 
.br
\fIrc\fP error status code 
.RE
.PP

.PP
Definition at line 13 of file utils\&.F90\&.
.SS "subroutine utilities::handle_grib_error (character(len=20), intent(in) vname, character(len=20), intent(in) lev, character(len=20), intent(in) method, real(esmf_kind_r4), intent(in) value, integer, intent(in) varnum, logical, dimension(:), intent(inout) read_from_input, integer, intent(inout) iret, real(esmf_kind_r4), dimension(:,:), intent(inout), optional var, real(esmf_kind_r8), dimension(:,:), intent(inout), optional var8, real(esmf_kind_r8), dimension(:,:,:), intent(inout), optional var3d)"

.PP
Handle GRIB2 read error based on the user selected method in the varmap file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvname\fP grib2 variable name 
.br
\fIlev\fP grib2 variable level 
.br
\fImethod\fP how missing data is handled 
.br
\fIvalue\fP fill value for missing data 
.br
\fIvarnum\fP grib2 variable number 
.br
\fIiret\fP return status code 
.br
\fIvar\fP 4-byte array of corrected data 
.br
\fIvar8\fP 8-byte array of corrected data 
.br
\fIvar3d\fP 3-d array of corrected data 
.br
\fIread_from_input\fP logical array indicating if variable was read in 
.RE
.PP
\fBAuthor:\fP
.RS 4
Larissa Reames 
.RE
.PP

.PP
Definition at line 121 of file utils\&.F90\&.
.SS "subroutine utilities::netcdf_err (integer, intent(in) err, character(len=*), intent(in) string)"

.PP
Error handler for netcdf\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerr\fP error status code 
.br
\fIstring\fP error message 
.RE
.PP

.PP
Definition at line 35 of file utils\&.F90\&.
.SS "recursive subroutine utilities::quicksort (real*8, dimension(*) a, integer first, integer last)"

.PP
Sort an array of values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP the sorted array 
.br
\fIfirst\fP the first value of sorted array 
.br
\fIlast\fP the last value of sorted array 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jili Dong NOAA/EMC 
.RE
.PP

.PP
Definition at line 187 of file utils\&.F90\&.
.SS "subroutine utilities::to_lower (character(len=*), intent(inout) strIn)"

.PP
Convert from upper to lowercase\&. 
.PP
\fBAuthor:\fP
.RS 4
Clive Page
.RE
.PP
Adapted from http://www.star.le.ac.uk/~cgp/fortran.html (25 May 2012)
.PP
\fBParameters:\fP
.RS 4
\fIstrIn\fP string to convert 
.RE
.PP

.PP
Definition at line 88 of file utils\&.F90\&.
.SS "character(len=len(strin)) function utilities::to_upper (character(len=*), intent(in) strIn)"

.PP
Convert string from lower to uppercase\&. 
.PP
\fBAuthor:\fP
.RS 4
Clive Page
.RE
.PP
Adapted from http://www.star.le.ac.uk/~cgp/fortran.html (25 May 2012)
.PP
\fBParameters:\fP
.RS 4
\fIstrIn\fP string to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
strOut string in uppercase 
.RE
.PP

.PP
Definition at line 63 of file utils\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
