.TH "wam_gtd7bk_mod" 3 "Tue Jan 17 2023" "Version 1.9.0" "chgres_cube" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wam_gtd7bk_mod \- Use moduke for blockdata gtd7bk\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBimr\fP"
.br
.RI "define version "
.ti -1c
.RI "character *4, dimension(3) \fBisdate\fP"
.br
.RI "define date "
.ti -1c
.RI "character *4, dimension(2) \fBistime\fP"
.br
.RI "define time "
.ti -1c
.RI "character *4, dimension(2) \fBname\fP"
.br
.RI "define data name "
.ti -1c
.RI "real, dimension(50) \fBpa1\fP"
.br
.RI "block space data for he denisity "
.ti -1c
.RI "real, dimension(50) \fBpa2\fP"
.br
.RI "block space data for he denisity "
.ti -1c
.RI "real, dimension(50) \fBpa3\fP"
.br
.RI "block space data for he denisity "
.ti -1c
.RI "real, dimension(50) \fBpaa1\fP"
.br
.RI "block space data for semiannual mult sam "
.ti -1c
.RI "real, dimension(50) \fBpaa2\fP"
.br
.RI "block space data for semiannual mult sam "
.ti -1c
.RI "real, dimension(10) \fBpavgm\fP"
.br
.RI "block space data for middle atmosphere averages "
.ti -1c
.RI "real, dimension(50) \fBpb1\fP"
.br
.RI "block space data for o density "
.ti -1c
.RI "real, dimension(50) \fBpb2\fP"
.br
.RI "block space data for o density "
.ti -1c
.RI "real, dimension(50) \fBpb3\fP"
.br
.RI "block space data for o density "
.ti -1c
.RI "real, dimension(50) \fBpc1\fP"
.br
.RI "block space data for n2 density "
.ti -1c
.RI "real, dimension(50) \fBpc2\fP"
.br
.RI "block space data for n2 density "
.ti -1c
.RI "real, dimension(50) \fBpc3\fP"
.br
.RI "block space data for n2 density "
.ti -1c
.RI "real, dimension(50) \fBpd1\fP"
.br
.RI "block space data for tlb "
.ti -1c
.RI "real, dimension(50) \fBpd2\fP"
.br
.RI "block space data for tlb "
.ti -1c
.RI "real, dimension(50) \fBpd3\fP"
.br
.RI "block space data for tlb "
.ti -1c
.RI "real, dimension(10, 8) \fBpdm\fP"
.br
.RI "block space data for lower boundary "
.ti -1c
.RI "real, dimension(50) \fBpe1\fP"
.br
.RI "block space data for o2 density "
.ti -1c
.RI "real, dimension(50) \fBpe2\fP"
.br
.RI "block space data for o2 density "
.ti -1c
.RI "real, dimension(50) \fBpe3\fP"
.br
.RI "block space data for o2 density "
.ti -1c
.RI "real, dimension(50) \fBpf1\fP"
.br
.RI "block space data for ar density "
.ti -1c
.RI "real, dimension(50) \fBpf2\fP"
.br
.RI "block space data for ar density "
.ti -1c
.RI "real, dimension(50) \fBpf3\fP"
.br
.RI "block space data for ar density "
.ti -1c
.RI "real, dimension(50) \fBpg1\fP"
.br
.RI "block space data for h density "
.ti -1c
.RI "real, dimension(50) \fBpg2\fP"
.br
.RI "block space data for h density "
.ti -1c
.RI "real, dimension(50) \fBpg3\fP"
.br
.RI "block space data for h density "
.ti -1c
.RI "real, dimension(50) \fBph1\fP"
.br
.RI "block space data for n density "
.ti -1c
.RI "real, dimension(50) \fBph2\fP"
.br
.RI "block space data for n density "
.ti -1c
.RI "real, dimension(50) \fBph3\fP"
.br
.RI "block space data for n density "
.ti -1c
.RI "real, dimension(50) \fBpi1\fP"
.br
.RI "block space data for hot o density "
.ti -1c
.RI "real, dimension(50) \fBpi2\fP"
.br
.RI "block space data for hot o density "
.ti -1c
.RI "real, dimension(50) \fBpi3\fP"
.br
.RI "block space data for hot o density "
.ti -1c
.RI "real, dimension(50) \fBpj1\fP"
.br
.RI "block space data for s param "
.ti -1c
.RI "real, dimension(50) \fBpj2\fP"
.br
.RI "block space data for s param "
.ti -1c
.RI "real, dimension(50) \fBpj3\fP"
.br
.RI "block space data for s param "
.ti -1c
.RI "real, dimension(50) \fBpk1\fP"
.br
.RI "block space data for turbo "
.ti -1c
.RI "real, dimension(50) \fBpl1\fP"
.br
.RI "block space data for tn1(2) "
.ti -1c
.RI "real, dimension(50) \fBpl2\fP"
.br
.RI "block space data for tn1(2) "
.ti -1c
.RI "real, dimension(50) \fBpm1\fP"
.br
.RI "block space data for tn1(3) "
.ti -1c
.RI "real, dimension(50) \fBpm2\fP"
.br
.RI "block space data for tn1(3) "
.ti -1c
.RI "real, dimension(50) \fBpn1\fP"
.br
.RI "block space data for tn1(4) "
.ti -1c
.RI "real, dimension(50) \fBpn2\fP"
.br
.RI "block space data for tn1(4) "
.ti -1c
.RI "real, dimension(50) \fBpo1\fP"
.br
.RI "block space data for tn1(5) tn2(1) "
.ti -1c
.RI "real, dimension(50) \fBpo2\fP"
.br
.RI "block space data for tn1(5) tn2(1) "
.ti -1c
.RI "real, dimension(50) \fBpp1\fP"
.br
.RI "block space data for tn2(2) "
.ti -1c
.RI "real, dimension(50) \fBpp2\fP"
.br
.RI "block space data for tn2(2) "
.ti -1c
.RI "real, dimension(50) \fBpq1\fP"
.br
.RI "block space data for tn2(3) "
.ti -1c
.RI "real, dimension(50) \fBpq2\fP"
.br
.RI "block space data for tn2(3) "
.ti -1c
.RI "real, dimension(50) \fBpr1\fP"
.br
.RI "block space data for tn2(4) tn3(1) "
.ti -1c
.RI "real, dimension(2, 151) \fBpr151\fP"
.br
.RI "define pressures "
.ti -1c
.RI "real, dimension(50) \fBpr2\fP"
.br
.RI "block space data for tn2(4) tn3(1) "
.ti -1c
.RI "real, dimension(2, 65) \fBpr65\fP"
.br
.RI "define pressures "
.ti -1c
.RI "real, dimension(50) \fBps1\fP"
.br
.RI "block space data for tn3(2) "
.ti -1c
.RI "real, dimension(50) \fBps2\fP"
.br
.RI "block space data for tn3(2) "
.ti -1c
.RI "real, dimension(50) \fBpt1\fP"
.br
.RI "block space data for temperature "
.ti -1c
.RI "real, dimension(50) \fBpt2\fP"
.br
.RI "block space data for temperature "
.ti -1c
.RI "real, dimension(50) \fBpt3\fP"
.br
.RI "block space data for temperature "
.ti -1c
.RI "real, dimension(10) \fBptm\fP"
.br
.RI "block space data for lower boundary "
.ti -1c
.RI "real, dimension(50) \fBpu1\fP"
.br
.RI "block space data for tn3(3) "
.ti -1c
.RI "real, dimension(50) \fBpu2\fP"
.br
.RI "block space data for tn3(3) "
.ti -1c
.RI "real, dimension(50) \fBpv1\fP"
.br
.RI "block space data for tn3(4) "
.ti -1c
.RI "real, dimension(50) \fBpv2\fP"
.br
.RI "block space data for tn3(4) "
.ti -1c
.RI "real, dimension(50) \fBpw1\fP"
.br
.RI "block space data for tn3(5) surface temperature tsl "
.ti -1c
.RI "real, dimension(50) \fBpw2\fP"
.br
.RI "block space data for tn3(5) surface temperature tsl "
.ti -1c
.RI "real, dimension(50) \fBpx1\fP"
.br
.RI "block space data for tgn3(2) surface grad tslg "
.ti -1c
.RI "real, dimension(50) \fBpx2\fP"
.br
.RI "block space data for tgn3(2) surface grad tslg "
.ti -1c
.RI "real, dimension(50) \fBpy1\fP"
.br
.RI "block space data for tgn2(1) tgn1(2) "
.ti -1c
.RI "real, dimension(50) \fBpy2\fP"
.br
.RI "block space data for tgn2(1) tgn1(2) "
.ti -1c
.RI "real, dimension(50) \fBpz1\fP"
.br
.RI "block space data for tgn3(1) tgn2(2) "
.ti -1c
.RI "real, dimension(50) \fBpz2\fP"
.br
.RI "block space data for tgn3(1) tgn2(2) "
.in -1c
.SH "Detailed Description"
.PP 
Use moduke for blockdata gtd7bk\&. 

All variables originalyl in blockdata used for this packahe are getting from NRLMSISE-00\&. NRLMSISE-00 is an empirical, global reference atmospheric model of the Earth from ground to space\&. It models the temperatures and densities of the atmosphere's components\&. NRL stands for the US Naval Research Laboratory\&. MSIS stands for mass spectrometer and incoherent scatter radar, the two primary data sources for development of earlier versions of the model\&. E indicates that the model extends from the ground through exosphere and 00 is the year of release in 2000\&. Over the years since introduction, NRLMSISE-00 has become the standard for international space research\&. (wikipedia)
.PP
\fBAuthor:\fP
.RS 4
Hann-Ming Henry Juang 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "integer wam_gtd7bk_mod::imr"

.PP
define version 
.PP
Definition at line 106 of file wam_climo_data\&.f90\&.
.PP
Referenced by ghp7(), gtd7(), gtd7d(), gts7(), and meters()\&.
.SS "character*4, dimension(3) wam_gtd7bk_mod::isdate"

.PP
define date 
.PP
Definition at line 102 of file wam_climo_data\&.f90\&.
.SS "character*4, dimension(2) wam_gtd7bk_mod::istime"

.PP
define time 
.PP
Definition at line 103 of file wam_climo_data\&.f90\&.
.SS "character*4, dimension(2) wam_gtd7bk_mod::name"

.PP
define data name 
.PP
Definition at line 104 of file wam_climo_data\&.f90\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pa1"

.PP
block space data for he denisity 
.PP
Definition at line 35 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pa2"

.PP
block space data for he denisity 
.PP
Definition at line 36 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pa3"

.PP
block space data for he denisity 
.PP
Definition at line 37 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::paa1"

.PP
block space data for semiannual mult sam 
.PP
Definition at line 94 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::paa2"

.PP
block space data for semiannual mult sam 
.PP
Definition at line 95 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(10) wam_gtd7bk_mod::pavgm"

.PP
block space data for middle atmosphere averages 
.PP
Definition at line 100 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pb1"

.PP
block space data for o density 
.PP
Definition at line 38 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pb2"

.PP
block space data for o density 
.PP
Definition at line 39 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pb3"

.PP
block space data for o density 
.PP
Definition at line 40 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pc1"

.PP
block space data for n2 density 
.PP
Definition at line 41 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pc2"

.PP
block space data for n2 density 
.PP
Definition at line 42 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pc3"

.PP
block space data for n2 density 
.PP
Definition at line 43 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pd1"

.PP
block space data for tlb 
.PP
Definition at line 44 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pd2"

.PP
block space data for tlb 
.PP
Definition at line 45 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pd3"

.PP
block space data for tlb 
.PP
Definition at line 46 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(10,8) wam_gtd7bk_mod::pdm"

.PP
block space data for lower boundary 
.PP
Definition at line 98 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7(), and gts7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pe1"

.PP
block space data for o2 density 
.PP
Definition at line 47 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pe2"

.PP
block space data for o2 density 
.PP
Definition at line 48 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pe3"

.PP
block space data for o2 density 
.PP
Definition at line 49 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pf1"

.PP
block space data for ar density 
.PP
Definition at line 50 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pf2"

.PP
block space data for ar density 
.PP
Definition at line 51 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pf3"

.PP
block space data for ar density 
.PP
Definition at line 52 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pg1"

.PP
block space data for h density 
.PP
Definition at line 53 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pg2"

.PP
block space data for h density 
.PP
Definition at line 54 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pg3"

.PP
block space data for h density 
.PP
Definition at line 55 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::ph1"

.PP
block space data for n density 
.PP
Definition at line 56 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::ph2"

.PP
block space data for n density 
.PP
Definition at line 57 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::ph3"

.PP
block space data for n density 
.PP
Definition at line 58 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pi1"

.PP
block space data for hot o density 
.PP
Definition at line 59 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pi2"

.PP
block space data for hot o density 
.PP
Definition at line 60 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pi3"

.PP
block space data for hot o density 
.PP
Definition at line 61 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pj1"

.PP
block space data for s param 
.PP
Definition at line 62 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pj2"

.PP
block space data for s param 
.PP
Definition at line 63 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pj3"

.PP
block space data for s param 
.PP
Definition at line 64 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pk1"

.PP
block space data for turbo 
.PP
Definition at line 65 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pl1"

.PP
block space data for tn1(2) 
.PP
Definition at line 66 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pl2"

.PP
block space data for tn1(2) 
.PP
Definition at line 67 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pm1"

.PP
block space data for tn1(3) 
.PP
Definition at line 68 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pm2"

.PP
block space data for tn1(3) 
.PP
Definition at line 69 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pn1"

.PP
block space data for tn1(4) 
.PP
Definition at line 70 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pn2"

.PP
block space data for tn1(4) 
.PP
Definition at line 71 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::po1"

.PP
block space data for tn1(5) tn2(1) 
.PP
Definition at line 72 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::po2"

.PP
block space data for tn1(5) tn2(1) 
.PP
Definition at line 73 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pp1"

.PP
block space data for tn2(2) 
.PP
Definition at line 74 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pp2"

.PP
block space data for tn2(2) 
.PP
Definition at line 75 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pq1"

.PP
block space data for tn2(3) 
.PP
Definition at line 76 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pq2"

.PP
block space data for tn2(3) 
.PP
Definition at line 77 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pr1"

.PP
block space data for tn2(4) tn3(1) 
.PP
Definition at line 78 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(2,151) wam_gtd7bk_mod::pr151"

.PP
define pressures 
.PP
Definition at line 109 of file wam_climo_data\&.f90\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pr2"

.PP
block space data for tn2(4) tn3(1) 
.PP
Definition at line 79 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(2,65) wam_gtd7bk_mod::pr65"

.PP
define pressures 
.PP
Definition at line 108 of file wam_climo_data\&.f90\&.
.SS "real, dimension(50) wam_gtd7bk_mod::ps1"

.PP
block space data for tn3(2) 
.PP
Definition at line 80 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::ps2"

.PP
block space data for tn3(2) 
.PP
Definition at line 81 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pt1"

.PP
block space data for temperature 
.PP
Definition at line 32 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pt2"

.PP
block space data for temperature 
.PP
Definition at line 33 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pt3"

.PP
block space data for temperature 
.PP
Definition at line 34 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(10) wam_gtd7bk_mod::ptm"

.PP
block space data for lower boundary 
.PP
Definition at line 97 of file wam_climo_data\&.f90\&.
.PP
Referenced by gts7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pu1"

.PP
block space data for tn3(3) 
.PP
Definition at line 82 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pu2"

.PP
block space data for tn3(3) 
.PP
Definition at line 83 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pv1"

.PP
block space data for tn3(4) 
.PP
Definition at line 84 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pv2"

.PP
block space data for tn3(4) 
.PP
Definition at line 85 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pw1"

.PP
block space data for tn3(5) surface temperature tsl 
.PP
Definition at line 86 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pw2"

.PP
block space data for tn3(5) surface temperature tsl 
.PP
Definition at line 87 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::px1"

.PP
block space data for tgn3(2) surface grad tslg 
.PP
Definition at line 88 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::px2"

.PP
block space data for tgn3(2) surface grad tslg 
.PP
Definition at line 89 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::py1"

.PP
block space data for tgn2(1) tgn1(2) 
.PP
Definition at line 90 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::py2"

.PP
block space data for tgn2(1) tgn1(2) 
.PP
Definition at line 91 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pz1"

.PP
block space data for tgn3(1) tgn2(2) 
.PP
Definition at line 92 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SS "real, dimension(50) wam_gtd7bk_mod::pz2"

.PP
block space data for tgn3(1) tgn2(2) 
.PP
Definition at line 93 of file wam_climo_data\&.f90\&.
.PP
Referenced by gtd7()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for chgres_cube from the source code\&.
