/home/ed/UFS_UTILS/sorc/chgres_cube.fd/write_data.F90
NAME
/home/ed/UFS_UTILS/sorc/chgres_cube.fd/write_data.F90 - Write model coldstart files.
SYNOPSIS
Functions/Subroutines
subroutine write_fv3_atm_bndy_data_netcdf (localpet)
Writes atmospheric fields along the lateral boundary.
subroutine write_fv3_atm_data_netcdf (localpet)
Write atmospheric coldstart files (netcdf format).
subroutine write_fv3_atm_header_netcdf (localpet)
Writes atmospheric header file in netcdf format.
subroutine write_fv3_sfc_data_netcdf (localpet)
Writes surface and nst data into a 'coldstart' file (netcdf).
Detailed Description
Write model coldstart files.
Author
George Gayno NCEP/EMC
Write out target grid data into appropriate files for the forecast model.
Definition in file write_data.F90.
Function/Subroutine Documentation
subroutine write_fv3_atm_bndy_data_netcdf (integer, intent(in) localpet)
Writes atmospheric fields along the lateral boundary. For regional grids only. Output in netcdf format.
Parameters
localpet ESMF local persistent execution thread
Author
George Gayno NCEP/EMC
Definition at line 88 of file write_data.F90.
References atmosphere::dzdt_target_grid, error_handler(), program_setup::halo_blend, program_setup::halo_bndy, model_grid::i_target, program_setup::input_type, model_grid::ip1_target, model_grid::j_target, model_grid::jp1_target, atmosphere::lev_target, atmosphere::levp1_target, netcdf_err(), program_setup::num_tracers, atmosphere::ps_target_grid, atmosphere::qnifa_climo_target_grid, atmosphere::qnwfa_climo_target_grid, atmosphere::temp_target_grid, program_setup::tracers, atmosphere::tracers_target_grid, atmosphere::u_s_target_grid, atmosphere::u_w_target_grid, program_setup::use_thomp_mp_climo, atmosphere::v_s_target_grid, atmosphere::v_w_target_grid, and atmosphere::zh_target_grid.
Referenced by atmosphere::atmosphere_driver().
subroutine write_fv3_atm_data_netcdf (integer, intent(in) localpet)
Write atmospheric coldstart files (netcdf format). Routine writes tiled files in parallel. Tile 1 is written by localpet 0; tile 2 by localpet 1, etc. The number of pets must be equal to or greater than the number of tiled files.
Parameters
localpet ESMF local persistent execution thread
Author
George Gayno NCEP/EMC
Definition at line 1194 of file write_data.F90.
References atmosphere::delp_target_grid, atmosphere::dzdt_target_grid, error_handler(), program_setup::halo_bndy, model_grid::i_target, program_setup::input_type, model_grid::ip1_target, model_grid::j_target, model_grid::jp1_target, model_grid::latitude_s_target_grid, model_grid::latitude_target_grid, model_grid::latitude_w_target_grid, atmosphere::lev_target, atmosphere::levp1_target, model_grid::longitude_s_target_grid, model_grid::longitude_target_grid, model_grid::longitude_w_target_grid, netcdf_err(), model_grid::num_tiles_target_grid, program_setup::num_tracers, atmosphere::ps_target_grid, atmosphere::qnifa_climo_target_grid, atmosphere::qnwfa_climo_target_grid, program_setup::regional, atmosphere::temp_target_grid, program_setup::tracers, atmosphere::tracers_target_grid, atmosphere::u_s_target_grid, atmosphere::u_w_target_grid, program_setup::use_thomp_mp_climo, atmosphere::v_s_target_grid, atmosphere::v_w_target_grid, and atmosphere::zh_target_grid.
Referenced by atmosphere::atmosphere_driver().
subroutine write_fv3_atm_header_netcdf (integer, intent(in) localpet)
Writes atmospheric header file in netcdf format.
Parameters
localpet ESMF local persistent execution thread
Author
George Gayno NCEP/EMC
Definition at line 15 of file write_data.F90.
References atmosphere::levp1_target, netcdf_err(), program_setup::num_tracers, atmosphere::nvcoord_target, program_setup::use_thomp_mp_climo, and atmosphere::vcoord_target.
Referenced by atmosphere::atmosphere_driver().
subroutine write_fv3_sfc_data_netcdf (integer, intent(in) localpet)
Writes surface and nst data into a 'coldstart' file (netcdf).
Parameters
localpet ESMF local persistent execution thread
Author
George Gayno NCEP/EMC
Definition at line 1807 of file write_data.F90.
References static_data::alnsf_target_grid, static_data::alnwf_target_grid, static_data::alvsf_target_grid, static_data::alvwf_target_grid, surface::c_0_target_grid, surface::c_d_target_grid, surface::canopy_mc_target_grid, program_setup::convert_nst, surface::d_conv_target_grid, surface::dt_cool_target_grid, error_handler(), surface::f10m_target_grid, static_data::facsf_target_grid, static_data::facwf_target_grid, surface::ffmm_target_grid, program_setup::halo_bndy, model_grid::i_target, surface::ifd_target_grid, model_grid::j_target, program_setup::lai_from_climo, surface::lai_target_grid, model_grid::landmask_target_grid, model_grid::latitude_target_grid, model_grid::longitude_target_grid, model_grid::lsoil_target, static_data::max_veg_greenness_target_grid, static_data::min_veg_greenness_target_grid, static_data::mxsno_albedo_target_grid, netcdf_err(), model_grid::num_tiles_target_grid, surface::q2m_target_grid, surface::qrain_target_grid, program_setup::regional, surface::seaice_depth_target_grid, surface::seaice_fract_target_grid, surface::seaice_skin_temp_target_grid, surface::skin_temp_target_grid, static_data::slope_type_target_grid, surface::snow_depth_target_grid, surface::snow_liq_equiv_target_grid, surface::soil_temp_target_grid, static_data::soil_type_target_grid, surface::soilm_liq_target_grid, surface::soilm_tot_target_grid, surface::srflag_target_grid, static_data::substrate_temp_target_grid, surface::t2m_target_grid, surface::tprcp_target_grid, surface::tref_target_grid, surface::ustar_target_grid, static_data::veg_greenness_target_grid, static_data::veg_type_target_grid, surface::w_0_target_grid, surface::w_d_target_grid, surface::xs_target_grid, surface::xt_target_grid, surface::xtts_target_grid, surface::xu_target_grid, surface::xv_target_grid, surface::xz_target_grid, surface::xzts_target_grid, surface::z0_target_grid, surface::z_c_target_grid, and surface::zm_target_grid.
Referenced by surface::surface_driver().
Author
Generated automatically by Doxygen for chgres_cube from the source code.