.TH "/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/grid_tools.fd/global_equiv_resol.fd/global_equiv_resol.f90" 3 "Thu Aug 4 2022" "Version 1.8.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/stmp/george.gayno/UFS_UTILS.tag/sorc/grid_tools.fd/global_equiv_resol.fd/global_equiv_resol.f90 \- Compute the global equivalent resolution for regional grids\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcheck\fP (status)"
.br
.RI "Check results of netCDF call\&. "
.ti -1c
.RI "program \fBglobal_equiv_resol\fP"
.br
.RI "Compute the global equivalent resolution for regional grids using the average model grid cell size in meters squared\&. "
.in -1c
.SH "Detailed Description"
.PP 
Compute the global equivalent resolution for regional grids\&. 


.PP
\fBAuthor:\fP
.RS 4
Gerard Ketefian NOAA/GSL 
.RE
.PP

.PP
Definition in file \fBglobal_equiv_resol\&.f90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine check (integer, intent(in) status)"

.PP
Check results of netCDF call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP return code to check 
.RE
.PP
\fBAuthor:\fP
.RS 4
Gerard Ketefian NOAA/GSL 
.RE
.PP

.PP
Definition at line 193 of file global_equiv_resol\&.f90\&.
.SS "program global_equiv_resol ()"

.PP
Compute the global equivalent resolution for regional grids using the average model grid cell size in meters squared\&. 
.IP "\(bu" 2
RES(in km) = (360 degrees / 4*CRES) * 111 km
.PP
.PP
Using the average cell size the equivalent global resolution is:
.PP
.IP "\(bu" 2
CRES = NINT((2*PI*RADIUS_OF_EARTH)/(4*AVG_CELL_SIZE)
.PP
.PP
\fBAuthor:\fP
.RS 4
Gerard Ketefian NOAA/GSL 
.RE
.PP
\fBReturns:\fP
.RS 4
0 for success, error code otherwise 
.RE
.PP

.PP
Definition at line 16 of file global_equiv_resol\&.f90\&.
.PP
References check()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
