.TH "pesg::get_meanq" 3 "Thu Aug 4 2022" "Version 1.8.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::get_meanq
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBget_meanqd\fP (ngh, lam, xg, wg, ak, ma, q, qdak, qdma, ga, gadak, gadma, ff)"
.br
.RI "For a parameter vector, ak and a map-space domain-parameter vector, ma, return the lambda-parameterized quality diagnostic, Q, and the geographic domain-parameter vector ga\&. "
.ti -1c
.RI "subroutine \fBget_meanqs\fP (n, ngh, lam, xg, wg, aks, mas, qs, ff)"
.br
.RI "Like getmeanqd, except for n different values, aks, of ak and n different values, mas of ma, and without any of the derivatives\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file pesg\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pesg::get_meanq::get_meanqd (integer(spi), intent(in) ngh, real(dp), intent(in) lam, real(dp), dimension(ngh), intent(in) xg, real(dp), dimension(ngh), intent(in) wg, real(dp), dimension(2), intent(in) ak, real(dp), dimension(2), intent(in) ma, real(dp), intent(out) q, real(dp), dimension(2), intent(out) qdak, real(dp), dimension(2), intent(out) qdma, real(dp), dimension(2), intent(out) ga, real(dp), dimension(2,2), intent(out) gadak, real(dp), dimension(2,2), intent(out) gadma, logical, intent(out) ff)\fC [private]\fP"

.PP
For a parameter vector, ak and a map-space domain-parameter vector, ma, return the lambda-parameterized quality diagnostic, Q, and the geographic domain-parameter vector ga\&. Lambda is given by lam <1\&. Also, return the derivatives, qdak and qdma, of Q wrt ak and ma, and the derivatives gadak and gadma, of ga wrt ak and ma\&.
.PP
The domain averages of Q are accurately computed by bi-Gauss-Legendre quadrature over the positive quadrant of the domain (exploiting the symmetry) of the four constituent terms, v1, v2, v3, v4, from which the mean Q is computed using a quadratic formula of these constituents\&. The number of Gauss points in eaxh half-interval is ngh, and the nodes themselves are, in proportion to the half-interval, at xg\&. the normalized gauss weights are wg\&.
.PP
If a failure occurs, colmputations cease immediately and a failure flag, FF, is raised on return\&.
.PP
\fBParameters:\fP
.RS 4
\fIngh\fP 
.br
\fIlam\fP Lambda 
.br
\fIxg\fP 
.br
\fIwg\fP 
.br
\fIak\fP parameter vector 
.br
\fIma\fP map-space domain-parameter vector 
.br
\fIq\fP lambda-parameterized quality diagnostic 
.br
\fIqdak\fP derivatives value 
.br
\fIqdma\fP derivatives value 
.br
\fIga\fP geographic domain-parameter vector 
.br
\fIgadak\fP 
.br
\fIgadma\fP 
.br
\fIff\fP error flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 603 of file pesg\&.f90\&.
.SS "subroutine pesg::get_meanq::get_meanqs (integer(spi), intent(in) n, integer(spi), intent(in) ngh, real(dp), intent(in) lam, real(dp), dimension(ngh), intent(in) xg, real(dp), dimension(ngh), intent(in) wg, real(dp), dimension(2,n), intent(in) aks, real(dp), dimension(2,n), intent(in) mas, real(dp), dimension(n), intent(out) qs, logical, intent(out) ff)\fC [private]\fP"

.PP
Like getmeanqd, except for n different values, aks, of ak and n different values, mas of ma, and without any of the derivatives\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP 
.br
\fIngh\fP 
.br
\fIlam\fP 
.br
\fIxg\fP 
.br
\fIwg\fP 
.br
\fIaks\fP 
.br
\fImas\fP 
.br
\fIqs\fP 
.br
\fIff\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 681 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
