.TH "pesg::xstoxc" 3 "Thu Aug 4 2022" "Version 1.8.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::xstoxc
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBxstoxc\fP (xs, xc, xcd)"
.br
.RI "Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar\&. "
.ti -1c
.RI "subroutine \fBxstoxc1\fP (xs, xc, xcd, xcdd)"
.br
.RI "Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file pesg\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pesg::xstoxc::xstoxc (real(dp), dimension(2), intent(in) xs, real(dp), dimension(3), intent(out) xc, real(dp), dimension(3,2), intent(out) xcd)\fC [private]\fP"

.PP
Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar\&. xcd=d(xc)/d(xs) is the jacobian matrix, encoding distortion and metric\&.
.PP
\fBParameters:\fP
.RS 4
\fIxs\fP Stereographic map coordinates 
.br
\fIxc\fP Cartesian earth-centered 3-vector 
.br
\fIxcd\fP Value of jacobian matrix, encoding distortion and metric 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 85 of file pesg\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pesg::xstoxc::xstoxc1 (real(dp), dimension(2), intent(in) xs, real(dp), dimension(3), intent(out) xc, real(dp), dimension(3,2), intent(out) xcd, real(dp), dimension(3,2,2), intent(out) xcdd)\fC [private]\fP"

.PP
Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar\&. xcd=d(xc)/d(xs) is the jacobian matrix, encoding distortion and metric\&. xcdd is the further derivative, wrt xs, of xcd\&.
.PP
\fBParameters:\fP
.RS 4
\fIxs\fP Stereographic map coordinates 
.br
\fIxc\fP Cartesian earth-centered 3-vector 
.br
\fIxcd\fP Jacobian matrix, encoding distortion and metric 
.br
\fIxcdd\fP Further derivative, wrt xs, of xcd 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 107 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
