.TH "psym2::invsym2" 3 "Thu Aug 4 2022" "Version 1.8.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psym2::invsym2
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBinvsym2\fP (em, z)"
.br
.RI "Get the inverse of a 2*2 matrix (need not be symmetric in this case)\&. "
.ti -1c
.RI "subroutine \fBinvsym2d\fP (em, z, zd)"
.br
.RI "Get the inverse, z,of a 2*2 symmetric matrix, em, and its derivative, zd, with respect to symmetric variations of its components\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file psym2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine psym2::invsym2::invsym2 (real(dp), dimension(2,2), intent(in) em, real(dp), dimension(2,2), intent(out) z)\fC [private]\fP"

.PP
Get the inverse of a 2*2 matrix (need not be symmetric in this case)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIem\fP 2*2 matrix 
.br
\fIz\fP inverse of a 2*2 matrix 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 112 of file psym2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine psym2::invsym2::invsym2d (real(dp), dimension(2,2), intent(in) em, real(dp), dimension(2,2), intent(out) z, real(dp), dimension(2,2,2,2), intent(out) zd)\fC [private]\fP"

.PP
Get the inverse, z,of a 2*2 symmetric matrix, em, and its derivative, zd, with respect to symmetric variations of its components\&. I\&.e\&., for a symmetric infinitesimal change, delta_em, in em, the resulting infinitesimal change in z would be: 
.PP
.nf
delta_z(i,j) = matmul(zd(i,j,:,:),delta_em)
.fi
.PP
.PP
\fBParameters:\fP
.RS 4
\fIem\fP 2*2 symmetric matrix 
.br
\fIz\fP inverse of a 2*2 symmetric matrix 
.br
\fIzd\fP derivative of the 2*2 symmetric matrix 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 132 of file psym2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
