.TH "cstgeo" 3 "Thu Aug 4 2022" "Version 1.8.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cstgeo \- Constants for orientation and stretching of map\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real(sp), dimension(3, 3) \fBrotm\fP"
.br
.RI "Orthogonal rotation matrix\&. "
.ti -1c
.RI "real(sp) \fBsc\fP"
.br
.RI "Schmidt stretching factor\&. "
.ti -1c
.RI "real(sp) \fBsci\fP"
.br
.RI "Schmidt inverse stretching factor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Constants for orientation and stretching of map\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real(sp), dimension(3,3) cstgeo::rotm"

.PP
Orthogonal rotation matrix\&. 
.PP
Definition at line 10 of file pmat5\&.f90\&.
.SS "real(sp) cstgeo::sc"

.PP
Schmidt stretching factor\&. 
.PP
Definition at line 11 of file pmat5\&.f90\&.
.SS "real(sp) cstgeo::sci"

.PP
Schmidt inverse stretching factor\&. 
.PP
Definition at line 12 of file pmat5\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
