.TH "pesg::xctoxs" 3 "Mon Apr 17 2023" "Version 1.10.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::xctoxs
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBxctoxs\fP (xc, xs)"
.br
.RI "Inverse of xstoxc\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file pesg\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pesg::xctoxs::xctoxs (real(dp), dimension(3), intent(in) xc, real(dp), dimension(2), intent(out) xs)\fC [private]\fP"

.PP
Inverse of xstoxc\&. I\&.e\&., cartesians to stereographic\&.
.PP
\fBParameters:\fP
.RS 4
\fIxc\fP Earth-centered cartesian unit 3-vector 
.br
\fIxs\fP Stereographic map coordinates 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 68 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
