.TH "pesg::xttoxm" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::xttoxm
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBxttoxm\fP (a, xt, xm, ff)"
.br
.RI "Inverse of xmtoxt\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file pesg\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pesg::xttoxm::xttoxm (real(dp), intent(in) a, real(dp), dimension(2), intent(in) xt, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff)\fC [private]\fP"

.PP
Inverse of xmtoxt\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Mapping parameter controlling grid line spacing profile 
.br
.br
\fIxt\fP Gnomonic plane coordinates 
.br
.br
\fIxm\fP Map coordinates 
.br
\fIff\fP Failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 235 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
