.TH "pesg::zmtozt" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::zmtozt
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBzmtozt\fP (a, zm, zt, ztd, ff)"
.br
.RI "Evaluate the function, zt = tan(sqrt(A)*z)/sqrt(A), and its derivative, ztd, for positive and negative A and for the limiting case, A --> 0\&. "
.ti -1c
.RI "subroutine \fBzmtozt1\fP (a, zm, zt, ztd, zt1, ztd1, ff)"
.br
.RI "Like zmtozt, but also, get the derivative with respect to a, zt1 of zt, and ztd1 of ztd\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file pesg\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pesg::zmtozt::zmtozt (real(dp), intent(in) a, real(dp), intent(in) zm, real(dp), intent(out) zt, real(dp), intent(out) ztd, logical, intent(out) ff)\fC [private]\fP"

.PP
Evaluate the function, zt = tan(sqrt(A)*z)/sqrt(A), and its derivative, ztd, for positive and negative A and for the limiting case, A --> 0\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Mapping parameter controlling grid line spacing profile 
.br
\fIzm\fP Scalar value of single map plane coordinate 
.br
\fIzt\fP Scalar value of single gnomonic plane coordinate 
.br
\fIztd\fP Derivative of gnomonic coordinate, d(zt)/d(zm) 
.br
\fIff\fP Failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 323 of file pesg\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pesg::zmtozt::zmtozt1 (real(dp), intent(in) a, real(dp), intent(in) zm, real(dp), intent(out) zt, real(dp), intent(out) ztd, real(dp), intent(out) zt1, real(dp), intent(out) ztd1, logical, intent(out) ff)\fC [private]\fP"

.PP
Like zmtozt, but also, get the derivative with respect to a, zt1 of zt, and ztd1 of ztd\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Mapping parameter controlling grid line spacing profile 
.br
\fIzm\fP Single map plane coordinate 
.br
\fIzt\fP Single gnomonic plane coordinate 
.br
\fIztd\fP Derivative wrt zm of zt, d(zt)/d(zm) 
.br
\fIzt1\fP Derivative wrt a of zt, d(zt)/da 
.br
\fIztd1\fP Derivative wrt a of ztd, d^2(zt)/(d(zm)da) 
.br
\fIff\fP Failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 348 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
