.TH "pesg::gtoxm_ak_dd" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::gtoxm_ak_dd
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBgtoxm_ak_dd_g\fP (A, K, pdlat, pdlon, pdazi, delx, dely, dlat, dlon, xm, ff)"
.br
.RI "Like gtoxm_ak_rr_g, except lat, lon, azimuth, are expressed in degrees\&. "
.ti -1c
.RI "subroutine \fBgtoxm_ak_dd_m\fP (A, K, pdlat, pdlon, pdazi, dlat, dlon, xm, ff)"
.br
.RI "Like gtoxm_ak_rr_m, except lat, lon, azimuth, are expressed in degrees\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file pesg\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pesg::gtoxm_ak_dd::gtoxm_ak_dd_g (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), intent(in) dlat, real(dp), intent(in) dlon, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff)\fC [private]\fP"

.PP
Like gtoxm_ak_rr_g, except lat, lon, azimuth, are expressed in degrees\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP parameter of the ESG mapping 
.br
\fIk\fP parameter of the ESG mapping 
.br
\fIpdlat\fP degrees latitude defining mapping projection center 
.br
\fIpdlon\fP degrees longitude defining mapping projection center 
.br
\fIpdazi\fP Azimuth of mapping orientation at its center 
.br
\fIdelx\fP central x-spacing of the grid in radians 
.br
\fIdely\fP central y-spacing of the grid in radians 
.br
\fIdlat\fP degrees latitude of a point to be mapped 
.br
\fIdlon\fP degrees longitude of a point to be mapped 
.br
\fIxm\fP 2-vector image of the point in center-relative grid units 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1984 of file pesg\&.f90\&.
.SS "subroutine pesg::gtoxm_ak_dd::gtoxm_ak_dd_m (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) dlat, real(dp), intent(in) dlon, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff)\fC [private]\fP"

.PP
Like gtoxm_ak_rr_m, except lat, lon, azimuth, are expressed in degrees\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP parameter of the ESG mapping 
.br
\fIk\fP parameter of the ESG mapping 
.br
\fIpdlat\fP degrees latitude defining mapping center 
.br
\fIpdlon\fP degrees longitude defining mapping center 
.br
\fIpdazi\fP Azimuth of mapping orientation at its center 
.br
\fIdlat\fP degrees latitude of point to be mapped 
.br
\fIdlon\fP degrees longitude of point to be mapped 
.br
\fIxm\fP 2-vector center-relative map space image of the point 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1955 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
