.TH "pesg::hgrid_ak_rr" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::hgrid_ak_rr
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBhgrid_ak_rr\fP (lx, ly, nx, ny, A, K, plat, plon, pazi, delx, dely, glat, glon, garea, ff)"
.br
.RI "Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians)\&. "
.ti -1c
.RI "subroutine \fBhgrid_ak_rr_c\fP (lx, ly, nx, ny, a, k, plat, plon, pazi, delx, dely, glat, glon, garea, dx, dy, angle_dx, angle_dy, ff)"
.br
.RI "Use a and k as the parameters of an extended Schmidt-transformed gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file pesg\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pesg::hgrid_ak_rr::hgrid_ak_rr (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(lx:lx+nx  ,ly:ly+ny  ), intent(out) glat, real(dp), dimension(lx:lx+nx  ,ly:ly+ny  ), intent(out) glon, real(dp), dimension(lx:lx+nx\-1,ly:ly+ny\-1), intent(out) garea, logical, intent(out) ff)\fC [private]\fP"

.PP
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians)\&. Assume the radius of the earth is unity, and using the central mapping point as the coordinate origin, set up the grid with central x-spacing delx and y-spacing dely\&. The grid index location of the left-lower corner of the domain is (lx,ly) (typically both NEGATIVE)\&. The numbers of the grid spaces in x and y directions are nx and ny\&. (Note that, for a centered rectangular grid lx and ly are negative and, in magnitude, half the values of nx and ny respectively\&.) Return the latitude and longitude, in radians again, of the grid points thus defined in the arrays, glat and glon, and return a rectangular array, garea, of dimensions nx-1 by ny-1, that contains the areas of each of the grid cells
.PP
If all goes well, return a lowered failure flag, ff=\&.false\&. \&. But if, for some reason, it is not possible to complete this task, return the raised failure flag, ff=\&.TRUE\&. \&.
.PP
\fBParameters:\fP
.RS 4
\fIlx\fP center-relative grid index in x of left edge of the domain 
.br
\fIly\fP center-relative grid index in y of lower edge of the domain 
.br
\fInx\fP number of grid spaces in x 
.br
\fIny\fP number of grid spaces in y 
.br
\fIA\fP parameter of the ESG mapping centered at (plat,plon) 
.br
\fIK\fP parameter of the ESG mapping centered at (plat,plon) 
.br
\fIplat\fP latitude of projection center of mapping (radians) 
.br
\fIplon\fP longitude of projection center of mapping (radians) 
.br
\fIpazi\fP azimuth of orientation of mapping at its center 
.br
\fIdelx\fP central x-spacing of the grid (radians) 
.br
\fIdely\fP central y-spacing of the grid (radians) 
.br
\fIglat\fP grid points' latitudes 
.br
\fIglon\fP grid points' longitudes 
.br
\fIgarea\fP array of grid-cell areas (steradians) 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1220 of file pesg\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pesg::hgrid_ak_rr::hgrid_ak_rr_c (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) a, real(dp), intent(in) k, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(lx:lx+nx  ,ly:ly+ny  ), intent(out) glat, real(dp), dimension(lx:lx+nx  ,ly:ly+ny  ), intent(out) glon, real(dp), dimension(lx:lx+nx\-1,ly:ly+ny\-1), intent(out) garea, real(dp), dimension(lx:lx+nx\-1,ly:ly+ny  ), intent(out) dx, real(dp), dimension(lx:lx+nx  ,ly:ly+ny\-1), intent(out) dy, real(dp), dimension(lx:lx+nx  ,ly:ly+ny  ), intent(out) angle_dx, real(dp), dimension(lx:lx+nx  ,ly:ly+ny  ), intent(out) angle_dy, logical, intent(out) ff)\fC [private]\fP"

.PP
Use a and k as the parameters of an extended Schmidt-transformed gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians)\&. Using the central mapping point as the coordinate origin, set up the grid with central x-spacing delx and y-spacing dely in nondimensional units, (i\&.e\&., as if the earth had unit radius) and with the location of the left- lower corner of the grid at center-relative grid index pair, (lx,ly) and with the number of the grid spaces in x and y directions given by nx and ny\&. (Note that, for a centered rectangular grid lx and ly are negative and, in magnitude, half the values of nx and ny respectively\&.) Return the latitude and longitude, again, in radians, of the grid pts thus defined in the arrays, glat and glon; return a rectangular array, garea, of dimensions nx-1 by ny-1, that contains the areas of each of the grid cells in nondimensional 'steradian' units\&.
.PP
In this version, these grid cell areas are computed by 2D integrating the scalar jacobian of the transformation, using a 4th-order centered scheme\&. The estimated grid steps, dx and dy, are returned at the grid cell edges, using the same 4th-order scheme to integrate the 1D projected jacobian\&. The angles, relative to local east and north, are returned respectively as angle_dx and angle_dy at grid cell corners, in radians counterclockwise\&.
.PP
if all goes well, return a \&.FALSE\&. failure flag, ff\&. If, for some reason, it is not possible to complete this task, return the failure flag as \&.TRUE\&.
.PP
\fBParameters:\fP
.RS 4
\fIlx\fP center-relative x grid index for left edge of the domain 
.br
\fIly\fP center-relative y grid index for lower edge of the domain 
.br
\fInx\fP numbers of the grid spaces in x 
.br
\fIny\fP numbers of the grid spaces in y 
.br
\fIa\fP Extended Schmidt Gnomonic parameter 
.br
\fIk\fP Extended Schmidt Gnomonic parameter 
.br
\fIplat\fP latitude of the projection center of the mapping (radians) 
.br
\fIplon\fP longitude of the projection center of the mapping (radians) 
.br
\fIpazi\fP azimuth of the orientation of the mapping at its center 
.br
\fIdelx\fP central x-spacing of the grid (radians) 
.br
\fIdely\fP central y-spacing of the grid (radians) 
.br
\fIglat\fP grid points' latitudes (radians) 
.br
\fIglon\fP grid points' longitudes (radians) 
.br
\fIgarea\fP array of grid-cell areas (steradians) 
.br
\fIdx\fP grid steps in x at grid cell edges (radians) 
.br
\fIdy\fP grid steps in y at grid cell edges (radians) 
.br
\fIangle_dx\fP x angles relative to local east (radians) 
.br
\fIangle_dy\fP y angles relative to local north (radians) 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1337 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
