.TH "pfun::atanh" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::atanh
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBatanh_d\fP (t)"
.br
.RI "Hyperbolic arc-tangent for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBatanh_s\fP (t)"
.br
.RI "Hyperbolic arc-tangent for single precision real\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::atanh::atanh_d (real(dp), intent(in) t)\fC [private]\fP"

.PP
Hyperbolic arc-tangent for double precision real\&. 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP double precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
a hyperbolic arc-tangent of t 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 216 of file pfun\&.f90\&.
.SS "real(sp) function pfun::atanh::atanh_s (real(sp), intent(in) t)\fC [private]\fP"

.PP
Hyperbolic arc-tangent for single precision real\&. (compilers now have this)
.PP
\fBParameters:\fP
.RS 4
\fIt\fP single precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
a hyperbolic arc-tangent of t 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 198 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
