.TH "pfun" 3 "Tue Mar 9 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun \- This module is for ???  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBahav\fP"
.br
.ti -1c
.RI "interface \fBahavh\fP"
.br
.ti -1c
.RI "interface \fBatanh\fP"
.br
.ti -1c
.RI "interface \fBgd\fP"
.br
.ti -1c
.RI "interface \fBgdi\fP"
.br
.ti -1c
.RI "interface \fBhav\fP"
.br
.ti -1c
.RI "interface \fBhavh\fP"
.br
.ti -1c
.RI "interface \fBsech\fP"
.br
.ti -1c
.RI "interface \fBsechs\fP"
.br
.ti -1c
.RI "interface \fBsinhox\fP"
.br
.ti -1c
.RI "interface \fBsinhoxm\fP"
.br
.ti -1c
.RI "interface \fBsinox\fP"
.br
.ti -1c
.RI "interface \fBsinoxm\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "real(dp) function \fBahav_d\fP (a)"
.br
.RI "Arc-haversine function for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBahav_s\fP (a)"
.br
.RI "Arc-haversine function for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBahavh_d\fP (a)"
.br
.RI "Hyperbolic arc-haversine for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBahavh_s\fP (a)"
.br
.RI "Hyperbolic arc-haversine for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBatanh_d\fP (t)"
.br
.RI "??? "
.ti -1c
.RI "real(sp) function \fBatanh_s\fP (t)"
.br
.RI "??? "
.ti -1c
.RI "real(dp) function \fBgd_d\fP (x)"
.br
.RI "??? "
.ti -1c
.RI "real(sp) function \fBgd_s\fP (x)"
.br
.RI "??? "
.ti -1c
.RI "real(dp) function \fBgdi_d\fP (y)"
.br
.RI "Inverse Gudermannian function for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBgdi_s\fP (y)"
.br
.RI "Inverse Gudermannian function for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBhav_d\fP (t)"
.br
.RI "Haversine function for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBhav_s\fP (t)"
.br
.RI "Haversine function for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBhavh_d\fP (t)"
.br
.RI "Hyperbolic-haversine for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBhavh_s\fP (t)"
.br
.RI "Hyperbolic-haversine for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBsech_d\fP (x)"
.br
.RI "??? "
.ti -1c
.RI "real(sp) function \fBsech_s\fP (x)"
.br
.RI "??? "
.ti -1c
.RI "real(dp) function \fBsechs_d\fP (x)"
.br
.RI "??? "
.ti -1c
.RI "real(sp) function \fBsechs_s\fP (x)"
.br
.RI "??? "
.ti -1c
.RI "real(dp) function \fBsinhox_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sinh(x)/x\&. "
.ti -1c
.RI "real(dp) function \fBsinhoxm_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sinh(x)/x-1\&. "
.ti -1c
.RI "real(dp) function \fBsinox_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sin(x)/x\&. "
.ti -1c
.RI "real(dp) function \fBsinoxm_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sin(x)/x-1\&. "
.in -1c
.SH "Detailed Description"
.PP 
This module is for ??? 


.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::ahav_d (real(dp), intent(in) a)"

.PP
Arc-haversine function for double precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
t ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 154 of file pfun\&.f90\&.
.PP
References pietc::u2\&.
.SS "real(sp) function pfun::ahav_s (real(sp), intent(in) a)"

.PP
Arc-haversine function for single precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
t ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 141 of file pfun\&.f90\&.
.SS "real(dp) function pfun::ahavh_d (real(dp), intent(in) a)"

.PP
Hyperbolic arc-haversine for double precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
t ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 182 of file pfun\&.f90\&.
.PP
References pietc::u2\&.
.SS "real(sp) function pfun::ahavh_s (real(sp), intent(in) a)"

.PP
Hyperbolic arc-haversine for single precision real\&. 
.PP
\fBNote\fP
.RS 4
The minus sign in the hyperbolic arc-haversine definition\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIa\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
t ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 169 of file pfun\&.f90\&.
.SS "real(dp) function pfun::atanh_d (real(dp), intent(in) t)"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIt\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
a ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 213 of file pfun\&.f90\&.
.PP
References pietc::o2, pietc::o3, pietc::o5, and pietc::u1\&.
.SS "real(sp) function pfun::atanh_s (real(sp), intent(in) t)"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIt\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
a ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 195 of file pfun\&.f90\&.
.SS "real(dp) function pfun::gd_d (real(dp), intent(in) x)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
y ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 51 of file pfun\&.f90\&.
.SS "real(sp) function pfun::gd_s (real(sp), intent(in) x)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
y ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 38 of file pfun\&.f90\&.
.SS "real(dp) function pfun::gdi_d (real(dp), intent(in) y)\fC [private]\fP"

.PP
Inverse Gudermannian function for double precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
x ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 75 of file pfun\&.f90\&.
.SS "real(sp) function pfun::gdi_s (real(sp), intent(in) y)\fC [private]\fP"

.PP
Inverse Gudermannian function for single precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
x ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 63 of file pfun\&.f90\&.
.SS "real(dp) function pfun::hav_d (real(dp), intent(in) t)"

.PP
Haversine function for double precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
a ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 100 of file pfun\&.f90\&.
.PP
References pietc::o2\&.
.SS "real(sp) function pfun::hav_s (real(sp), intent(in) t)\fC [private]\fP"

.PP
Haversine function for single precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
a ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 87 of file pfun\&.f90\&.
.SS "real(dp) function pfun::havh_d (real(dp), intent(in) t)"

.PP
Hyperbolic-haversine for double precision real\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
a ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 128 of file pfun\&.f90\&.
.PP
References pietc::o2\&.
.SS "real(sp) function pfun::havh_s (real(sp), intent(in) t)"

.PP
Hyperbolic-haversine for single precision real\&. 
.PP
\fBNote\fP
.RS 4
The minus sign in the hyperbolic-haversine definition\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
a ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 115 of file pfun\&.f90\&.
.SS "real(dp) function pfun::sech_d (real(dp), intent(in) x)"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
r ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 248 of file pfun\&.f90\&.
.PP
References pietc::u1, and pietc::u2\&.
.SS "real(sp) function pfun::sech_s (real(sp), intent(in) x)"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
t ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 231 of file pfun\&.f90\&.
.SS "real(dp) function pfun::sechs_d (real(dp), intent(in) x)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
r ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 276 of file pfun\&.f90\&.
.SS "real(sp) function pfun::sechs_s (real(sp), intent(in) x)"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
r ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 264 of file pfun\&.f90\&.
.SS "real(dp) function pfun::sinhox_d (real(dp), intent(in) x)"

.PP
Evaluate the symmetric real function sinh(x)/x\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
r ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 342 of file pfun\&.f90\&.
.PP
References pietc::u1\&.
.SS "real(dp) function pfun::sinhoxm_d (real(dp), intent(in) x)"

.PP
Evaluate the symmetric real function sinh(x)/x-1\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
r ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 322 of file pfun\&.f90\&.
.PP
References pietc::u1\&.
.SS "real(dp) function pfun::sinox_d (real(dp), intent(in) x)"

.PP
Evaluate the symmetric real function sin(x)/x\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
r ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 308 of file pfun\&.f90\&.
.PP
References pietc::u1\&.
.SS "real(dp) function pfun::sinoxm_d (real(dp), intent(in) x)\fC [private]\fP"

.PP
Evaluate the symmetric real function sin(x)/x-1\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
r ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 288 of file pfun\&.f90\&.
.PP
References pietc::u1\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
