.TH "pfun::gd" 3 "Wed Mar 13 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::gd \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBgd_d\fP (x)"
.br
.RI "\fIGudermannian function (related to Mercator map projections) \fP"
.ti -1c
.RI "real(sp) function \fBgd_s\fP (x)"
.br
.RI "\fIGudermannian function (related to Mercator map projections) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::gd::gd_d (real(dp), intent(in)x)\fC [private]\fP"

.PP
Gudermannian function (related to Mercator map projections) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP double precision real argument of function 
.RE
.PP
\fBReturns:\fP
.RS 4
y Gudermannian function of x 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 53 of file pfun\&.f90\&.
.SS "real(sp) function pfun::gd::gd_s (real(sp), intent(in)x)\fC [private]\fP"

.PP
Gudermannian function (related to Mercator map projections) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP single precision real argument of function 
.RE
.PP
\fBReturns:\fP
.RS 4
y Gudermannian function of x 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 40 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
