.TH "pfun::gd" 3 "Thu Mar 11 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::gd
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBgd_d\fP (x)"
.br
.RI "??? "
.ti -1c
.RI "real(sp) function \fBgd_s\fP (x)"
.br
.RI "??? "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::gd::gd_d (real(dp), intent(in) x)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
y ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 51 of file pfun\&.f90\&.
.SS "real(sp) function pfun::gd::gd_s (real(sp), intent(in) x)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIx\fP ??? 
.RE
.PP
\fBReturns\fP
.RS 4
y ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.br
 
.RE
.PP

.PP
Definition at line 38 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
