.TH "pfun::ahavh" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::ahavh
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBahavh_d\fP (a)"
.br
.RI "Hyperbolic arc-haversine for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBahavh_s\fP (a)"
.br
.RI "Hyperbolic arc-haversine for single precision real\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::ahavh::ahavh_d (real(dp), intent(in) a)\fC [private]\fP"

.PP
Hyperbolic arc-haversine for double precision real\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP double precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
t hyperbolic arc-haversine of a 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 185 of file pfun\&.f90\&.
.SS "real(sp) function pfun::ahavh::ahavh_s (real(sp), intent(in) a)\fC [private]\fP"

.PP
Hyperbolic arc-haversine for single precision real\&. 
.PP
\fBNote:\fP
.RS 4
The minus sign in the hyperbolic arc-haversine definition\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIa\fP single precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
t hyperbolic arc-haversine of a 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 172 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
