.TH "pfun::sech" 3 "Wed Mar 13 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::sech \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBsech_d\fP (x)"
.br
.RI "\fIHyperbolic secant for double precision real\&. \fP"
.ti -1c
.RI "real(sp) function \fBsech_s\fP (x)"
.br
.RI "\fIHyperbolic secant for single precision real\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::sech::sech_d (real(dp), intent(in)x)\fC [private]\fP"

.PP
Hyperbolic secant for double precision real\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP double precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
r hyperbolic secant of x 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 250 of file pfun\&.f90\&.
.SS "real(sp) function pfun::sech::sech_s (real(sp), intent(in)x)\fC [private]\fP"

.PP
Hyperbolic secant for single precision real\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP single precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
r hyperbolic secant of x 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 233 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
