.TH "pfun::ahav" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::ahav
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBahav_d\fP (a)"
.br
.RI "Arc-haversine function for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBahav_s\fP (a)"
.br
.RI "Arc-haversine function for single precision real\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::ahav::ahav_d (real(dp), intent(in) a)\fC [private]\fP"

.PP
Arc-haversine function for double precision real\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP double precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
t arc-haversine function of a 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 157 of file pfun\&.f90\&.
.SS "real(sp) function pfun::ahav::ahav_s (real(sp), intent(in) a)\fC [private]\fP"

.PP
Arc-haversine function for single precision real\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP single precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
t arc-haversine function of a 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 144 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
