pietc
NAME
pietc - Some of the commonly used constants (pi etc) mainly for double-precision subroutines.
SYNOPSIS
Variables
complex(dpc), parameter c0 =(u0, u0)
complex zero
complex(dpc), parameter c1 =(u1, u0)
complex one
complex(dpc), parameter ci =(u0, u1)
complex i=sqrt(-1)
complex(dpc), parameter cipi =ci*pi
complex i*pi
real(dp), parameter dtor =pi/180
Degrees to radians.
real(dp), parameter euler =0.57721566490153286060651209008240243104215933593992359880e0_dp
Euler-Mascheroni constant.
logical, parameter f =.false.
for pain-relief in logical ops
complex(dpc), parameter mc1 =-c1
complex minus-one
complex(dpc), parameter mci =-ci
complex minus-i
real(dp), parameter mo2 =-o2
minus-half
real(dp), parameter mo3 =-o3
minus-third
real(dp), parameter mo4 =-o4
minus-fourth
real(dp), parameter mo5 =-o5
minus-fifth
real(dp), parameter mo6 =-o6
minus-sixth
real(dp), parameter ms10 =-s10
minus-sine(10 deg)
real(dp), parameter ms11 =-s11
minus-sine(90/8 deg)
real(dp), parameter ms13 =-s13
minus-sine(90/7 deg)
real(dp), parameter ms15 =-s15
minus-sine(15 deg)
real(dp), parameter ms18 =-s18
minus-sine(18 deg)
real(dp), parameter ms20 =-s20
minus-sine(20 deg)
real(dp), parameter ms22 =-s22
minus-sine(22.5 deg)
real(dp), parameter ms26 =-s26
minus-sine(90*2/7 deg)
real(dp), parameter ms30 =-s30
minus-sine(30 deg)
real(dp), parameter ms34 =-s34
minus-sine(90*3/8 deg)
real(dp), parameter ms36 =-s36
minus-sine(36 deg)
real(dp), parameter ms39 =-s39
minus-sine(90*3/7 deg)
real(dp), parameter ms40 =-s40
minus-sine(40 deg)
real(dp), parameter ms45 =-s45
minus-sine(45 deg)
real(dp), parameter ms50 =-s50
minus-sine(50 deg)
real(dp), parameter ms51 =-s51
minus-sine(90*4/7 deg)
real(dp), parameter ms54 =-s54
minus-sine(54 deg)
real(dp), parameter ms56 =-s56
minus-sine(90*5/8 deg)
real(dp), parameter ms60 =-s60
minus-sine(60 deg)
real(dp), parameter ms64 =-s64
minus-sine(90*5/7 deg)
real(dp), parameter ms68 =-s68
minus-sine(67.5 deg)
real(dp), parameter ms70 =-s70
minus-sine(70 deg)
real(dp), parameter ms72 =-s72
minus-sine(72 deg)
real(dp), parameter ms75 =-s75
minus-sine(75 deg)
real(dp), parameter ms77 =-s77
minus-sine(90*6/7 deg)
real(dp), parameter ms79 =-s79
minus-sine(90*7/8 deg)
real(dp), parameter ms80 =-s80
minus-sine(80 deg)
real(dp), parameter mu1 =-u1
minus-one
real(dp), parameter mu2 =-u2
minus-two
real(dp), parameter mu3 =-u3
minus-three
real(dp), parameter mu4 =-u4
minus-four
real(dp), parameter mu5 =-u5
minus-five
real(dp), parameter mu6 =-u6
minus-six
real(dp), parameter o2 =u1/u2
half
real(dp), parameter o3 =u1/u3
third
real(dp), parameter o4 =u1/u4
fourth
real(dp), parameter o5 =u1/u5
fifth
real(dp), parameter o6 =u1/u6
sixth
real(dp), parameter or2 =u1/r2
1.
real(dp), parameter or3 =u1/r3
1.
real(dp), parameter or5 =u1/r5
1.
real(dp), parameter phi =1.6180339887498948482045868343656381177203091798057628621354e0_dp
Golden number.
real(dp), parameter pi =3.1415926535897932384626433832795028841971693993751058209749e0_dp
Pi.
real(dp), parameter pi2 =6.2831853071795864769252867665590057683943387987502116419498e0_dp
Pi*2.
real(dp), parameter pih =1.5707963267948966192313216916397514420985846996875529104874e0_dp
pi*half
real(dp), parameter r2 =1.4142135623730950488016887242096980785696718753769480731766e0_dp
Square root of 2.
real(dp), parameter r3 =1.7320508075688772935274463415058723669428052538103806280558e0_dp
Square root of 3.
real(dp), parameter r5 =2.2360679774997896964091736687312762354406183596115257242708e0_dp
Square root of 5.
real(dp), parameter rpi =1.7724538509055160272981674833411451827975494561223871282138e0_dp
square root of pi
real(dp), parameter rtod =180/pi
radians to degrees
real(dp), parameter s10 =.173648177666930348851716626769314796000375677184069387236241e0_dp
sine(10 deg)
real(dp), parameter s11 =.195090322016128267848284868477022240927691617751954807754502e0_dp
sine(90/8 deg)
real(dp), parameter s13 =.222520933956314404288902564496794759466355568764544955311987e0_dp
sine(90/7 deg)
real(dp), parameter s15 =.258819045102520762348898837624048328349068901319930513814003e0_dp
sine(15 deg)
real(dp), parameter s18 =.309016994374947424102293417182819058860154589902881431067724e0_dp
sine(18 deg)
real(dp), parameter s20 =.342020143325668733044099614682259580763083367514160628465048e0_dp
sine(20 deg)
real(dp), parameter s22 =.382683432365089771728459984030398866761344562485627041433800e0_dp
sine(22.5 deg)
real(dp), parameter s26 =.433883739117558120475768332848358754609990727787459876444547e0_dp
sine(90*2/7 deg)
real(dp), parameter s30 =o2
sine(30 deg)
real(dp), parameter s34 =.555570233019602224742830813948532874374937190754804045924153e0_dp
sine(90*3/8 deg)
real(dp), parameter s36 =.587785252292473129168705954639072768597652437643145991072272e0_dp
sine(36 deg)
real(dp), parameter s39 =.623489801858733530525004884004239810632274730896402105365549e0_dp
sine(90*3/7 deg)
real(dp), parameter s40 =.642787609686539326322643409907263432907559884205681790324977e0_dp
sine(40 deg)
real(dp), parameter s45 =or2
sine(45 deg)
real(dp), parameter s50 =.766044443118978035202392650555416673935832457080395245854045e0_dp
sine(50 deg)
real(dp), parameter s51 =.781831482468029808708444526674057750232334518708687528980634e0_dp
sine(90*4/7 deg)
real(dp), parameter s54 =.809016994374947424102293417182819058860154589902881431067724e0_dp
sine(54 deg)
real(dp), parameter s56 =.831469612302545237078788377617905756738560811987249963446124e0_dp
sine(90*5/8 deg)
real(dp), parameter s60 =r3*o2
sine(60 deg)
real(dp), parameter s64 =.900968867902419126236102319507445051165919162131857150053562e0_dp
sine(90*5/7 deg)
real(dp), parameter s68 =.923879532511286756128183189396788286822416625863642486115097e0_dp
sine(67.5 deg)
real(dp), parameter s70 =.939692620785908384054109277324731469936208134264464633090286e0_dp
sine(70 deg)
real(dp), parameter s72 =.951056516295153572116439333379382143405698634125750222447305e0_dp
sine(72 deg)
real(dp), parameter s75 =.965925826289068286749743199728897367633904839008404550402343e0_dp
sine(75 deg)
real(dp), parameter s77 =.974927912181823607018131682993931217232785800619997437648079e0_dp
sine(90*6/7 deg)
real(dp), parameter s79 =.980785280403230449126182236134239036973933730893336095002916e0_dp
sine(90*7/8 deg)
real(dp), parameter s80 =.984807753012208059366743024589523013670643251719842418790025e0_dp
sine(80 deg)
logical, parameter t =.true.
for pain-relief in logical ops
real(dp), parameter u0 =0_dp
zero
real(dp), parameter u1 =1_dp
one
real(dp), parameter u2 =2_dp
two
real(dp), parameter u3 =3_dp
three
real(dp), parameter u4 =4_dp
four
real(dp), parameter u5 =5_dp
five
real(dp), parameter u6 =6_dp
six
complex(dpc), parameter z000 =c1
exp(2*pi*i*0)
complex(dpc), parameter z010 =( s80, s10)
exp(2*pi*i/36)
complex(dpc), parameter z011 =( s79, s11)
exp(2*pi*i/32)
complex(dpc), parameter z013 =( s77, s13)
exp(2*pi*i/28)
complex(dpc), parameter z015 =( s75, s15)
exp(2*pi*i/24)
complex(dpc), parameter z018 =( s72, s18)
exp(2*pi*i/20)
complex(dpc), parameter z020 =( s70, s20)
exp(2*pi*i/18)
complex(dpc), parameter z022 =( s68, s22)
exp(2*pi*i/16)
complex(dpc), parameter z026 =( s64, s26)
exp(2*pi*i/14)
complex(dpc), parameter z030 =( s60, s30)
exp(2*pi*i/12)
complex(dpc), parameter z034 =( s56, s34)
exp(2*pi*i*3/32)
complex(dpc), parameter z036 =( s54, s36)
exp(2*pi*i/10)
complex(dpc), parameter z039 =( s51, s39)
exp(2*pi*i*3/28)
complex(dpc), parameter z040 =( s50, s40)
exp(2*pi*i/9)
complex(dpc), parameter z045 =( s45, s45)
exp(2*pi*i/8)
complex(dpc), parameter z050 =( s40, s50)
exp(2*pi*i*5/36)
complex(dpc), parameter z051 =( s39, s51)
exp(2*pi*i/7)
complex(dpc), parameter z054 =( s36, s54)
exp(2*pi*i*3/20)
complex(dpc), parameter z056 =( s34, s56)
exp(2*pi*i*5/32)
complex(dpc), parameter z060 =( s30, s60)
exp(2*pi*i/6)
complex(dpc), parameter z064 =( s26, s64)
exp(2*pi*i*5/28)
complex(dpc), parameter z068 =( s22, s68)
exp(2*pi*i*3/16)
complex(dpc), parameter z070 =( s20, s70)
exp(2*pi*i*7/36)
complex(dpc), parameter z072 =( s18, s72)
exp(2*pi*i/5)
complex(dpc), parameter z075 =( s15, s75)
exp(2*pi*i*5/24)
complex(dpc), parameter z077 =( s13, s77)
exp(2*pi*i*3/14)
complex(dpc), parameter z079 =( s11, s79)
exp(2*pi*i*7/32)
complex(dpc), parameter z080 =( s10, s80)
exp(2*pi*i*2/9)
complex(dpc), parameter z090 =ci
exp(2*pi*i/4)
complex(dpc), parameter z100 =(ms10, s80)
exp(2*pi*i*5/18)
complex(dpc), parameter z101 =(ms11, s79)
exp(2*pi*i*9/32)
complex(dpc), parameter z103 =(ms13, s77)
exp(2*pi*i*2/7)
complex(dpc), parameter z105 =(ms15, s75)
exp(2*pi*i*7/24)
complex(dpc), parameter z108 =(ms18, s72)
exp(2*pi*i*3/10)
complex(dpc), parameter z110 =(ms20, s70)
exp(2*pi*i*11/36)
complex(dpc), parameter z112 =(ms22, s68)
exp(2*pi*i*5/16)
complex(dpc), parameter z116 =(ms26, s64)
exp(2*pi*i*9/28)
complex(dpc), parameter z120 =(ms30, s60)
exp(2*pi*i/3)
complex(dpc), parameter z124 =(ms34, s56)
exp(2*pi*i*11/32)
complex(dpc), parameter z126 =(ms36, s54)
exp(2*pi*i*7/20)
complex(dpc), parameter z129 =(ms39, s51)
exp(2*pi*i*5/14)
complex(dpc), parameter z130 =(ms40, s50)
exp(2*pi*i*13/36)
complex(dpc), parameter z135 =(ms45, s45)
exp(2*pi*i*3/8)
complex(dpc), parameter z140 =(ms50, s40)
exp(2*pi*i*7/18)
complex(dpc), parameter z141 =(ms51, s39)
exp(2*pi*i*11/28)
complex(dpc), parameter z144 =(ms54, s36)
exp(2*pi*i*2/5)
complex(dpc), parameter z146 =(ms56, s34)
exp(2*pi*i*13/32)
complex(dpc), parameter z150 =(ms60, s30)
exp(2*pi*i*5/12)
complex(dpc), parameter z154 =(ms64, s26)
exp(2*pi*i*3/7)
complex(dpc), parameter z158 =(ms68, s22)
exp(2*pi*i*7/16)
complex(dpc), parameter z160 =(ms70, s20)
exp(2*pi*i*4/9)
complex(dpc), parameter z162 =(ms72, s18)
exp(2*pi*i*9/20)
complex(dpc), parameter z165 =(ms75, s15)
exp(2*pi*i*11/24)
complex(dpc), parameter z167 =(ms77, s13)
exp(2*pi*i*13/28)
complex(dpc), parameter z169 =(ms79, s11)
exp(2*pi*i*15/32)
complex(dpc), parameter z170 =(ms80, s10)
exp(2*pi*i*17/36)
complex(dpc), parameter z180 =-z000
exp(2*pi*i/2)
complex(dpc), parameter z190 =-z010
exp(2*pi*i*19/36)
complex(dpc), parameter z191 =-z011
exp(2*pi*i*17/32)
complex(dpc), parameter z193 =-z013
exp(2*pi*i*15/28)
complex(dpc), parameter z195 =-z015
exp(2*pi*i*13/24)
complex(dpc), parameter z198 =-z018
exp(2*pi*i*11/20)
complex(dpc), parameter z200 =-z020
exp(2*pi*i*5/9)
complex(dpc), parameter z202 =-z022
exp(2*pi*i*9/16)
complex(dpc), parameter z206 =-z026
exp(2*pi*i*4/7)
complex(dpc), parameter z210 =-z030
exp(2*pi*i*7/12)
complex(dpc), parameter z214 =-z034
exp(2*pi*i*19/32)
complex(dpc), parameter z216 =-z036
exp(2*pi*i*3/5)
complex(dpc), parameter z219 =-z039
exp(2*pi*i*17/28)
complex(dpc), parameter z220 =-z040
exp(2*pi*i*11/18)
complex(dpc), parameter z225 =-z045
exp(2*pi*i*5/8)
complex(dpc), parameter z230 =-z050
exp(2*pi*i*23/36)
complex(dpc), parameter z231 =-z051
exp(2*pi*i*9/14)
complex(dpc), parameter z234 =-z054
exp(2*pi*i*13/20)
complex(dpc), parameter z236 =-z056
exp(2*pi*i*21/32)
complex(dpc), parameter z240 =-z060
exp(2*pi*i*2/3)
complex(dpc), parameter z244 =-z064
exp(2*pi*i*19/28)
complex(dpc), parameter z248 =-z068
exp(2*pi*i*11/16)
complex(dpc), parameter z250 =-z070
exp(2*pi*i*25/36)
complex(dpc), parameter z252 =-z072
exp(2*pi*i*7/10)
complex(dpc), parameter z255 =-z075
exp(2*pi*i*17/24)
complex(dpc), parameter z257 =-z077
exp(2*pi*i*5/7)
complex(dpc), parameter z259 =-z079
exp(2*pi*i*23/32)
complex(dpc), parameter z260 =-z080
exp(2*pi*i*13/18)
complex(dpc), parameter z270 =-z090
exp(2*pi*i*3/4)
complex(dpc), parameter z280 =-z100
exp(2*pi*i*7/9)
complex(dpc), parameter z281 =-z101
exp(2*pi*i*25/32)
complex(dpc), parameter z283 =-z103
exp(2*pi*i*11/14)
complex(dpc), parameter z285 =-z105
exp(2*pi*i*19/24)
complex(dpc), parameter z288 =-z108
exp(2*pi*i*4/5)
complex(dpc), parameter z290 =-z110
exp(2*pi*i*29/36)
complex(dpc), parameter z292 =-z112
exp(2*pi*i*13/16)
complex(dpc), parameter z296 =-z116
exp(2*pi*i*23/28)
complex(dpc), parameter z300 =-z120
exp(2*pi*i*5/6)
complex(dpc), parameter z304 =-z124
exp(2*pi*i*27/32)
complex(dpc), parameter z306 =-z126
exp(2*pi*i*17/20)
complex(dpc), parameter z309 =-z129
exp(2*pi*i*6/7)
complex(dpc), parameter z310 =-z130
exp(2*pi*i*31/36)
complex(dpc), parameter z315 =-z135
exp(2*pi*i*7/8)
complex(dpc), parameter z320 =-z140
exp(2*pi*i*8/9)
complex(dpc), parameter z321 =-z141
exp(2*pi*i*25/28)
complex(dpc), parameter z324 =-z144
exp(2*pi*i*9/10)
complex(dpc), parameter z326 =-z146
exp(2*pi*i*29/32)
complex(dpc), parameter z330 =-z150
exp(2*pi*i*11/12)
complex(dpc), parameter z334 =-z154
exp(2*pi*i*13/14)
complex(dpc), parameter z338 =-z158
exp(2*pi*i*15/16)
complex(dpc), parameter z340 =-z160
exp(2*pi*i*17/18)
complex(dpc), parameter z342 =-z162
exp(2*pi*i*19/20)
complex(dpc), parameter z345 =-z165
exp(2*pi*i*23/24)
complex(dpc), parameter z347 =-z167
exp(2*pi*i*27/28)
complex(dpc), parameter z349 =-z169
exp(2*pi*i*31/32)
complex(dpc), parameter z350 =-z170
exp(2*pi*i*35/36)
Detailed Description
Some of the commonly used constants (pi etc) mainly for double-precision subroutines.
ms10 etc are needed to satisfy the some (eg., gnu fortran) compilers' more rigorous standards regarding the way 'data' statements are initialized. Zero and the first few units are u0,u1,u2, etc., their reciprocals being, o2,o3 etc and their square roots, r2,r3. Reciprocal roots are or2,or3 etc.
Author:
R. J. Purser
Date:
2014
Variable Documentation
complex(dpc), parameter pietc::c0 =(u0, u0)
complex zero
Definition at line 112 of file pietc.f90.
Referenced by pmat::cldumf(), and pmat2::clib_c().
complex(dpc), parameter pietc::c1 =(u1, u0)
complex one
Definition at line 113 of file pietc.f90.
Referenced by pmat::cinvmtf(), pmat::cldumf(), pmat::cudlmm(), and pmat::cudlmv().
complex(dpc), parameter pietc::ci =(u0, u1)
complex i=sqrt(-1)
Definition at line 115 of file pietc.f90.
complex(dpc), parameter pietc::cipi =ci*pi
complex i*pi
Definition at line 117 of file pietc.f90.
real(dp), parameter pietc::dtor =pi/180
Degrees to radians.
Definition at line 54 of file pietc.f90.
Referenced by pmat5::dgtoc(), pmat5::dgtocd(), pmat5::dgtocdd(), pmat5::dininmap(), pmat5::dinivmap(), pesg::get_edges(), pesg::gtoxm_ak_dd_g(), pesg::gtoxm_ak_dd_m(), pesg::hgrid_ak_dc(), pesg::hgrid_ak_dd(), pesg::hgrid_ak_dd_c(), regional_grid(), pesg::xmtog_ak_dd_g(), and pesg::xmtog_ak_dd_m().
real(dp), parameter pietc::euler =0.57721566490153286060651209008240243104215933593992359880e0_dp
Euler-Mascheroni constant.
Definition at line 53 of file pietc.f90.
logical, parameter pietc::f =.false.
for pain-relief in logical ops
Definition at line 18 of file pietc.f90.
Referenced by pmat::sl1lmf(), pmat::sldlmf(), pmat::sldumf(), pesg::xctoxm_ak(), pesg::zmtozt(), and pesg::zttozm().
complex(dpc), parameter pietc::mc1 =-c1
complex minus-one
Definition at line 114 of file pietc.f90.
complex(dpc), parameter pietc::mci =-ci
complex minus-i
Definition at line 116 of file pietc.f90.
real(dp), parameter pietc::mo2 =-o2
minus-half
Definition at line 37 of file pietc.f90.
real(dp), parameter pietc::mo3 =-o3
minus-third
Definition at line 38 of file pietc.f90.
real(dp), parameter pietc::mo4 =-o4
minus-fourth
Definition at line 39 of file pietc.f90.
real(dp), parameter pietc::mo5 =-o5
minus-fifth
Definition at line 40 of file pietc.f90.
real(dp), parameter pietc::mo6 =-o6
minus-sixth
Definition at line 41 of file pietc.f90.
real(dp), parameter pietc::ms10 =-s10
minus-sine(10 deg)
Definition at line 85 of file pietc.f90.
real(dp), parameter pietc::ms11 =-s11
minus-sine(90/8 deg)
Definition at line 86 of file pietc.f90.
real(dp), parameter pietc::ms13 =-s13
minus-sine(90/7 deg)
Definition at line 87 of file pietc.f90.
real(dp), parameter pietc::ms15 =-s15
minus-sine(15 deg)
Definition at line 88 of file pietc.f90.
real(dp), parameter pietc::ms18 =-s18
minus-sine(18 deg)
Definition at line 89 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::ms20 =-s20
minus-sine(20 deg)
Definition at line 90 of file pietc.f90.
real(dp), parameter pietc::ms22 =-s22
minus-sine(22.5 deg)
Definition at line 91 of file pietc.f90.
real(dp), parameter pietc::ms26 =-s26
minus-sine(90*2/7 deg)
Definition at line 92 of file pietc.f90.
real(dp), parameter pietc::ms30 =-s30
minus-sine(30 deg)
Definition at line 93 of file pietc.f90.
real(dp), parameter pietc::ms34 =-s34
minus-sine(90*3/8 deg)
Definition at line 94 of file pietc.f90.
real(dp), parameter pietc::ms36 =-s36
minus-sine(36 deg)
Definition at line 95 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::ms39 =-s39
minus-sine(90*3/7 deg)
Definition at line 96 of file pietc.f90.
real(dp), parameter pietc::ms40 =-s40
minus-sine(40 deg)
Definition at line 97 of file pietc.f90.
real(dp), parameter pietc::ms45 =-s45
minus-sine(45 deg)
Definition at line 98 of file pietc.f90.
real(dp), parameter pietc::ms50 =-s50
minus-sine(50 deg)
Definition at line 99 of file pietc.f90.
real(dp), parameter pietc::ms51 =-s51
minus-sine(90*4/7 deg)
Definition at line 100 of file pietc.f90.
real(dp), parameter pietc::ms54 =-s54
minus-sine(54 deg)
Definition at line 101 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::ms56 =-s56
minus-sine(90*5/8 deg)
Definition at line 102 of file pietc.f90.
real(dp), parameter pietc::ms60 =-s60
minus-sine(60 deg)
Definition at line 103 of file pietc.f90.
real(dp), parameter pietc::ms64 =-s64
minus-sine(90*5/7 deg)
Definition at line 104 of file pietc.f90.
real(dp), parameter pietc::ms68 =-s68
minus-sine(67.5 deg)
Definition at line 105 of file pietc.f90.
real(dp), parameter pietc::ms70 =-s70
minus-sine(70 deg)
Definition at line 106 of file pietc.f90.
real(dp), parameter pietc::ms72 =-s72
minus-sine(72 deg)
Definition at line 107 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::ms75 =-s75
minus-sine(75 deg)
Definition at line 108 of file pietc.f90.
real(dp), parameter pietc::ms77 =-s77
minus-sine(90*6/7 deg)
Definition at line 109 of file pietc.f90.
real(dp), parameter pietc::ms79 =-s79
minus-sine(90*7/8 deg)
Definition at line 110 of file pietc.f90.
real(dp), parameter pietc::ms80 =-s80
minus-sine(80 deg)
Definition at line 111 of file pietc.f90.
real(dp), parameter pietc::mu1 =-u1
minus-one
Definition at line 21 of file pietc.f90.
real(dp), parameter pietc::mu2 =-u2
minus-two
Definition at line 23 of file pietc.f90.
real(dp), parameter pietc::mu3 =-u3
minus-three
Definition at line 25 of file pietc.f90.
real(dp), parameter pietc::mu4 =-u4
minus-four
Definition at line 27 of file pietc.f90.
real(dp), parameter pietc::mu5 =-u5
minus-five
Definition at line 29 of file pietc.f90.
real(dp), parameter pietc::mu6 =-u6
minus-six
Definition at line 31 of file pietc.f90.
real(dp), parameter pietc::o2 =u1/u2
half
Definition at line 32 of file pietc.f90.
Referenced by pfun::atanh_d(), pfun::atanh_s(), pmat4::axial33_d(), psym2::eigensym2(), psym2::eigensym2d(), pmat4::expmat(), pmat4::expmatd(), pmat4::expmatdd(), psym2::expsym2d(), pesg::get_qx(), pesg::get_qxd(), pfun::hav_d(), pmat4::hav_d(), pfun::hav_s(), pfun::havh_d(), pfun::havh_s(), psym2::logsym2d(), psym2::sqrtsym2d_e(), psym2::sqrtsym2d_t(), and pesg::xttoxs1().
real(dp), parameter pietc::o3 =u1/u3
third
Definition at line 33 of file pietc.f90.
Referenced by pfun::atanh_d(), and pesg::zmtozt1().
real(dp), parameter pietc::o4 =u1/u4
fourth
Definition at line 34 of file pietc.f90.
real(dp), parameter pietc::o5 =u1/u5
fifth
Definition at line 35 of file pietc.f90.
Referenced by pfun::atanh_d(), pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::o6 =u1/u6
sixth
Definition at line 36 of file pietc.f90.
real(dp), parameter pietc::or2 =u1/r2
1. /root of two
Definition at line 49 of file pietc.f90.
real(dp), parameter pietc::or3 =u1/r3
1. /root of three
Definition at line 50 of file pietc.f90.
real(dp), parameter pietc::or5 =u1/r5
1. /root of five
Definition at line 51 of file pietc.f90.
real(dp), parameter pietc::phi =1.6180339887498948482045868343656381177203091798057628621354e0_dp
Golden number.
Definition at line 52 of file pietc.f90.
real(dp), parameter pietc::pi =3.1415926535897932384626433832795028841971693993751058209749e0_dp
Pi.
Definition at line 42 of file pietc.f90.
real(dp), parameter pietc::pi2 =6.2831853071795864769252867665590057683943387987502116419498e0_dp
Pi*2.
Definition at line 43 of file pietc.f90.
real(dp), parameter pietc::pih =1.5707963267948966192313216916397514420985846996875529104874e0_dp
pi*half
Definition at line 44 of file pietc.f90.
Referenced by pesg::gaulegh(), and pesg::zmtozt().
real(dp), parameter pietc::r2 =1.4142135623730950488016887242096980785696718753769480731766e0_dp
Square root of 2.
Definition at line 46 of file pietc.f90.
real(dp), parameter pietc::r3 =1.7320508075688772935274463415058723669428052538103806280558e0_dp
Square root of 3.
Definition at line 47 of file pietc.f90.
real(dp), parameter pietc::r5 =2.2360679774997896964091736687312762354406183596115257242708e0_dp
Square root of 5.
Definition at line 48 of file pietc.f90.
real(dp), parameter pietc::rpi =1.7724538509055160272981674833411451827975494561223871282138e0_dp
square root of pi
Definition at line 45 of file pietc.f90.
real(dp), parameter pietc::rtod =180/pi
radians to degrees
Definition at line 55 of file pietc.f90.
Referenced by pmat5::dctog(), pesg::get_meanqd(), pesg::guessak_map(), pesg::hgrid_ak_c(), pesg::hgrid_ak_dd(), pesg::hgrid_ak_dd_c(), regional_grid(), pesg::xmtog_ak_dd_g(), and pesg::xmtog_ak_dd_m().
real(dp), parameter pietc::s10 =.173648177666930348851716626769314796000375677184069387236241e0_dp
sine(10 deg)
Definition at line 57 of file pietc.f90.
real(dp), parameter pietc::s11 =.195090322016128267848284868477022240927691617751954807754502e0_dp
sine(90/8 deg)
Definition at line 58 of file pietc.f90.
real(dp), parameter pietc::s13 =.222520933956314404288902564496794759466355568764544955311987e0_dp
sine(90/7 deg)
Definition at line 59 of file pietc.f90.
real(dp), parameter pietc::s15 =.258819045102520762348898837624048328349068901319930513814003e0_dp
sine(15 deg)
Definition at line 60 of file pietc.f90.
real(dp), parameter pietc::s18 =.309016994374947424102293417182819058860154589902881431067724e0_dp
sine(18 deg)
Definition at line 61 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::s20 =.342020143325668733044099614682259580763083367514160628465048e0_dp
sine(20 deg)
Definition at line 62 of file pietc.f90.
real(dp), parameter pietc::s22 =.382683432365089771728459984030398866761344562485627041433800e0_dp
sine(22.5 deg)
Definition at line 63 of file pietc.f90.
real(dp), parameter pietc::s26 =.433883739117558120475768332848358754609990727787459876444547e0_dp
sine(90*2/7 deg)
Definition at line 64 of file pietc.f90.
real(dp), parameter pietc::s30 =o2
sine(30 deg)
Definition at line 65 of file pietc.f90.
real(dp), parameter pietc::s34 =.555570233019602224742830813948532874374937190754804045924153e0_dp
sine(90*3/8 deg)
Definition at line 66 of file pietc.f90.
real(dp), parameter pietc::s36 =.587785252292473129168705954639072768597652437643145991072272e0_dp
sine(36 deg)
Definition at line 67 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::s39 =.623489801858733530525004884004239810632274730896402105365549e0_dp
sine(90*3/7 deg)
Definition at line 68 of file pietc.f90.
real(dp), parameter pietc::s40 =.642787609686539326322643409907263432907559884205681790324977e0_dp
sine(40 deg)
Definition at line 69 of file pietc.f90.
real(dp), parameter pietc::s45 =or2
sine(45 deg)
Definition at line 70 of file pietc.f90.
real(dp), parameter pietc::s50 =.766044443118978035202392650555416673935832457080395245854045e0_dp
sine(50 deg)
Definition at line 71 of file pietc.f90.
real(dp), parameter pietc::s51 =.781831482468029808708444526674057750232334518708687528980634e0_dp
sine(90*4/7 deg)
Definition at line 72 of file pietc.f90.
real(dp), parameter pietc::s54 =.809016994374947424102293417182819058860154589902881431067724e0_dp
sine(54 deg)
Definition at line 73 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::s56 =.831469612302545237078788377617905756738560811987249963446124e0_dp
sine(90*5/8 deg)
Definition at line 74 of file pietc.f90.
real(dp), parameter pietc::s60 =r3*o2
sine(60 deg)
Definition at line 75 of file pietc.f90.
real(dp), parameter pietc::s64 =.900968867902419126236102319507445051165919162131857150053562e0_dp
sine(90*5/7 deg)
Definition at line 76 of file pietc.f90.
real(dp), parameter pietc::s68 =.923879532511286756128183189396788286822416625863642486115097e0_dp
sine(67.5 deg)
Definition at line 77 of file pietc.f90.
real(dp), parameter pietc::s70 =.939692620785908384054109277324731469936208134264464633090286e0_dp
sine(70 deg)
Definition at line 78 of file pietc.f90.
real(dp), parameter pietc::s72 =.951056516295153572116439333379382143405698634125750222447305e0_dp
sine(72 deg)
Definition at line 79 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::s75 =.965925826289068286749743199728897367633904839008404550402343e0_dp
sine(75 deg)
Definition at line 80 of file pietc.f90.
real(dp), parameter pietc::s77 =.974927912181823607018131682993931217232785800619997437648079e0_dp
sine(90*6/7 deg)
Definition at line 81 of file pietc.f90.
real(dp), parameter pietc::s79 =.980785280403230449126182236134239036973933730893336095002916e0_dp
sine(90*7/8 deg)
Definition at line 82 of file pietc.f90.
real(dp), parameter pietc::s80 =.984807753012208059366743024589523013670643251719842418790025e0_dp
sine(80 deg)
Definition at line 83 of file pietc.f90.
logical, parameter pietc::t =.true.
for pain-relief in logical ops
Definition at line 17 of file pietc.f90.
Referenced by pfun::ahav_s(), pfun::ahavh_s(), pfun::atanh_s(), pfun::hav_s(), pmat4::hav_s(), pfun::havh_s(), pmat::iinvf(), pmat5::plrot(), pmat5::plroti(), and pmat::sldumf().
real(dp), parameter pietc::u0 =0_dp
zero
Definition at line 19 of file pietc.f90.
Referenced by pmat2::AVCO(), pmat4::axial3_d(), psym2::chol2(), pmat::cldumf(), pmat2::clib_d(), pmat4::corral(), pmat4::ctoz(), pmat2::DAVCO(), pmat5::dctocd(), pmat5::dctocdd(), pmat5::dctog(), pmat5::dctogr(), pmat2::DDFCO(), pmat2::DDFCO2(), pmat4::det_d(), pmat5::dgrtocd(), pmat5::dgrtocdd(), pmat5::dgtocd(), pmat5::dgtocdd(), pmat4::diagn_d(), pmat4::diagn_s(), pmat5::dininmap(), pmat5::dinivmap(), pmat::dinvl(), pmat::dl1lmf(), pmat2::DL1UBB(), pmat2::DL1UEB(), pmat::dldlmf(), pmat2::DLDLTB(), pmat2::DLDUB(), pmat::dldumf(), pmat4::dtarea_d(), psym2::eigensym2(), psym2::eigensym2d(), pmat4::expmat(), pmat4::expmatd(), pmat4::expmatdd(), psym2::expsym2d_e(), pesg::gaulegh(), pesg::get_edges(), pesg::get_meanqd(), pesg::get_meanqs(), pesg::get_qxd(), pmat4::gram_d(), pmat4::graml_d(), pmat5::gtoframev(), pesg::gtoxm_ak_rr_m(), pesg::hgrid_ak_rc(), pesg::hgrid_ak_rr(), pesg::hgrid_ak_rr_c(), psym2::logsym2(), psym2::logsym2d(), pmat4::normalize_d(), pmat4::normalized_d(), pmat4::plaingram_d(), pmat4::rottoq(), pmat4::rowgram(), pmat4::sarea_d(), psym2::sqrtsym2d_e(), psym2::sqrtsym2d_t(), pesg::xmtog_ak_rr_m(), pesg::xmtoxt(), pesg::xmtoxt1(), pesg::xstoxc1(), pesg::xttoxs(), pesg::xttoxs1(), pesg::zmtozt(), pmat4::znfun(), and pesg::zttozm().
real(dp), parameter pietc::u1 =1_dp
one
Definition at line 20 of file pietc.f90.
Referenced by pfun::atanh_d(), pfun::atanh_s(), pmat2::AVCO(), pmat::cldumf(), pmat4::corral(), pmat4::ctoz(), pmat2::DAVCO(), pmat5::dctoc(), pmat5::dctocd(), pmat5::dctocdd(), pmat2::DDFCO(), pmat2::DDFCO2(), pmat::dinvl(), pmat::dl1lmf(), pmat2::DL1UBB(), pmat2::DL1UEB(), pmat::dldlmf(), pmat2::DLDLTB(), pmat2::DLDUB(), pmat::dldumf(), pmat4::dtarea_d(), pmat::dudlmm(), pmat::dudlmv(), psym2::eigensym2(), psym2::eigensym2d(), pmat4::expmat(), pmat4::expmatd(), pmat4::expmatdd(), psym2::expsym2d_t(), pesg::gaulegh(), pesg::get_qofv(), pesg::get_qofvd(), pesg::get_qsofvs(), pmat4::gram_d(), pmat5::gtoframev(), pesg::gtoxm_ak_rr_m(), pesg::hgrid_ak_rc(), pesg::hgrid_ak_rr(), pesg::hgrid_ak_rr_c(), psym2::logsym2d(), pmat4::normalize_d(), pmat4::rottoq(), pmat4::rowgram(), pfun::sech_d(), pfun::sech_s(), pfun::sinhox_d(), pfun::sinhoxm_d(), pfun::sinox_d(), pfun::sinoxm_d(), psym2::sqrtsym2d(), psym2::sqrtsym2d_e(), psym2::sqrtsym2d_t(), pesg::xctoxs(), pesg::xmtog_ak_rr_m(), pesg::xstoxc(), pesg::xstoxc1(), pesg::xstoxt(), pesg::xttoxs(), pesg::xttoxs1(), pesg::zmtozt(), and pesg::zttozm().
real(dp), parameter pietc::u2 =2_dp
two
Definition at line 22 of file pietc.f90.
Referenced by pfun::ahav_d(), pfun::ahav_s(), pfun::ahavh_d(), pfun::ahavh_s(), pmat5::dctoc(), pmat5::dctocd(), pmat5::dctocdd(), pmat4::dlltoxy_d(), pmat4::expmat(), pmat4::expmatd(), pmat4::expmatdd(), pesg::gaulegh(), pesg::get_qofvd(), pesg::get_qx(), pesg::get_qxd(), pmat4::rottoq(), pfun::sech_d(), pfun::sech_s(), pesg::xstoxc(), pesg::xstoxc1(), pesg::xstoxt(), pesg::xttoxs1(), pmat4::znfun(), and pmat4::zntay().
real(dp), parameter pietc::u3 =3_dp
three
Definition at line 24 of file pietc.f90.
Referenced by pmat4::znfun().
real(dp), parameter pietc::u4 =4_dp
four
Definition at line 26 of file pietc.f90.
real(dp), parameter pietc::u5 =5_dp
five
Definition at line 28 of file pietc.f90.
Referenced by pesg::bestesg_geo(), and pesg::bestesg_map().
real(dp), parameter pietc::u6 =6_dp
six
Definition at line 30 of file pietc.f90.
complex(dpc), parameter pietc::z000 =c1
exp(2*pi*i*0)
Definition at line 119 of file pietc.f90.
complex(dpc), parameter pietc::z010 =( s80, s10)
exp(2*pi*i/36)
Definition at line 120 of file pietc.f90.
complex(dpc), parameter pietc::z011 =( s79, s11)
exp(2*pi*i/32)
Definition at line 121 of file pietc.f90.
complex(dpc), parameter pietc::z013 =( s77, s13)
exp(2*pi*i/28)
Definition at line 122 of file pietc.f90.
complex(dpc), parameter pietc::z015 =( s75, s15)
exp(2*pi*i/24)
Definition at line 123 of file pietc.f90.
complex(dpc), parameter pietc::z018 =( s72, s18)
exp(2*pi*i/20)
Definition at line 124 of file pietc.f90.
complex(dpc), parameter pietc::z020 =( s70, s20)
exp(2*pi*i/18)
Definition at line 125 of file pietc.f90.
complex(dpc), parameter pietc::z022 =( s68, s22)
exp(2*pi*i/16)
Definition at line 126 of file pietc.f90.
complex(dpc), parameter pietc::z026 =( s64, s26)
exp(2*pi*i/14)
Definition at line 127 of file pietc.f90.
complex(dpc), parameter pietc::z030 =( s60, s30)
exp(2*pi*i/12)
Definition at line 128 of file pietc.f90.
complex(dpc), parameter pietc::z034 =( s56, s34)
exp(2*pi*i*3/32)
Definition at line 129 of file pietc.f90.
complex(dpc), parameter pietc::z036 =( s54, s36)
exp(2*pi*i/10)
Definition at line 130 of file pietc.f90.
complex(dpc), parameter pietc::z039 =( s51, s39)
exp(2*pi*i*3/28)
Definition at line 131 of file pietc.f90.
complex(dpc), parameter pietc::z040 =( s50, s40)
exp(2*pi*i/9)
Definition at line 132 of file pietc.f90.
complex(dpc), parameter pietc::z045 =( s45, s45)
exp(2*pi*i/8)
Definition at line 133 of file pietc.f90.
complex(dpc), parameter pietc::z050 =( s40, s50)
exp(2*pi*i*5/36)
Definition at line 134 of file pietc.f90.
complex(dpc), parameter pietc::z051 =( s39, s51)
exp(2*pi*i/7)
Definition at line 135 of file pietc.f90.
complex(dpc), parameter pietc::z054 =( s36, s54)
exp(2*pi*i*3/20)
Definition at line 136 of file pietc.f90.
complex(dpc), parameter pietc::z056 =( s34, s56)
exp(2*pi*i*5/32)
Definition at line 137 of file pietc.f90.
complex(dpc), parameter pietc::z060 =( s30, s60)
exp(2*pi*i/6)
Definition at line 138 of file pietc.f90.
complex(dpc), parameter pietc::z064 =( s26, s64)
exp(2*pi*i*5/28)
Definition at line 139 of file pietc.f90.
complex(dpc), parameter pietc::z068 =( s22, s68)
exp(2*pi*i*3/16)
Definition at line 140 of file pietc.f90.
complex(dpc), parameter pietc::z070 =( s20, s70)
exp(2*pi*i*7/36)
Definition at line 141 of file pietc.f90.
complex(dpc), parameter pietc::z072 =( s18, s72)
exp(2*pi*i/5)
Definition at line 142 of file pietc.f90.
complex(dpc), parameter pietc::z075 =( s15, s75)
exp(2*pi*i*5/24)
Definition at line 143 of file pietc.f90.
complex(dpc), parameter pietc::z077 =( s13, s77)
exp(2*pi*i*3/14)
Definition at line 144 of file pietc.f90.
complex(dpc), parameter pietc::z079 =( s11, s79)
exp(2*pi*i*7/32)
Definition at line 145 of file pietc.f90.
complex(dpc), parameter pietc::z080 =( s10, s80)
exp(2*pi*i*2/9)
Definition at line 146 of file pietc.f90.
complex(dpc), parameter pietc::z090 =ci
exp(2*pi*i/4)
Definition at line 147 of file pietc.f90.
complex(dpc), parameter pietc::z100 =(ms10, s80)
exp(2*pi*i*5/18)
Definition at line 148 of file pietc.f90.
complex(dpc), parameter pietc::z101 =(ms11, s79)
exp(2*pi*i*9/32)
Definition at line 149 of file pietc.f90.
complex(dpc), parameter pietc::z103 =(ms13, s77)
exp(2*pi*i*2/7)
Definition at line 150 of file pietc.f90.
complex(dpc), parameter pietc::z105 =(ms15, s75)
exp(2*pi*i*7/24)
Definition at line 151 of file pietc.f90.
complex(dpc), parameter pietc::z108 =(ms18, s72)
exp(2*pi*i*3/10)
Definition at line 152 of file pietc.f90.
complex(dpc), parameter pietc::z110 =(ms20, s70)
exp(2*pi*i*11/36)
Definition at line 153 of file pietc.f90.
complex(dpc), parameter pietc::z112 =(ms22, s68)
exp(2*pi*i*5/16)
Definition at line 154 of file pietc.f90.
complex(dpc), parameter pietc::z116 =(ms26, s64)
exp(2*pi*i*9/28)
Definition at line 155 of file pietc.f90.
complex(dpc), parameter pietc::z120 =(ms30, s60)
exp(2*pi*i/3)
Definition at line 156 of file pietc.f90.
complex(dpc), parameter pietc::z124 =(ms34, s56)
exp(2*pi*i*11/32)
Definition at line 157 of file pietc.f90.
complex(dpc), parameter pietc::z126 =(ms36, s54)
exp(2*pi*i*7/20)
Definition at line 158 of file pietc.f90.
complex(dpc), parameter pietc::z129 =(ms39, s51)
exp(2*pi*i*5/14)
Definition at line 159 of file pietc.f90.
complex(dpc), parameter pietc::z130 =(ms40, s50)
exp(2*pi*i*13/36)
Definition at line 160 of file pietc.f90.
complex(dpc), parameter pietc::z135 =(ms45, s45)
exp(2*pi*i*3/8)
Definition at line 161 of file pietc.f90.
complex(dpc), parameter pietc::z140 =(ms50, s40)
exp(2*pi*i*7/18)
Definition at line 162 of file pietc.f90.
complex(dpc), parameter pietc::z141 =(ms51, s39)
exp(2*pi*i*11/28)
Definition at line 163 of file pietc.f90.
complex(dpc), parameter pietc::z144 =(ms54, s36)
exp(2*pi*i*2/5)
Definition at line 164 of file pietc.f90.
complex(dpc), parameter pietc::z146 =(ms56, s34)
exp(2*pi*i*13/32)
Definition at line 165 of file pietc.f90.
complex(dpc), parameter pietc::z150 =(ms60, s30)
exp(2*pi*i*5/12)
Definition at line 166 of file pietc.f90.
complex(dpc), parameter pietc::z154 =(ms64, s26)
exp(2*pi*i*3/7)
Definition at line 167 of file pietc.f90.
complex(dpc), parameter pietc::z158 =(ms68, s22)
exp(2*pi*i*7/16)
Definition at line 168 of file pietc.f90.
complex(dpc), parameter pietc::z160 =(ms70, s20)
exp(2*pi*i*4/9)
Definition at line 169 of file pietc.f90.
complex(dpc), parameter pietc::z162 =(ms72, s18)
exp(2*pi*i*9/20)
Definition at line 170 of file pietc.f90.
complex(dpc), parameter pietc::z165 =(ms75, s15)
exp(2*pi*i*11/24)
Definition at line 171 of file pietc.f90.
complex(dpc), parameter pietc::z167 =(ms77, s13)
exp(2*pi*i*13/28)
Definition at line 172 of file pietc.f90.
complex(dpc), parameter pietc::z169 =(ms79, s11)
exp(2*pi*i*15/32)
Definition at line 173 of file pietc.f90.
complex(dpc), parameter pietc::z170 =(ms80, s10)
exp(2*pi*i*17/36)
Definition at line 174 of file pietc.f90.
complex(dpc), parameter pietc::z180 =-z000
exp(2*pi*i/2)
Definition at line 175 of file pietc.f90.
complex(dpc), parameter pietc::z190 =-z010
exp(2*pi*i*19/36)
Definition at line 176 of file pietc.f90.
complex(dpc), parameter pietc::z191 =-z011
exp(2*pi*i*17/32)
Definition at line 177 of file pietc.f90.
complex(dpc), parameter pietc::z193 =-z013
exp(2*pi*i*15/28)
Definition at line 178 of file pietc.f90.
complex(dpc), parameter pietc::z195 =-z015
exp(2*pi*i*13/24)
Definition at line 179 of file pietc.f90.
complex(dpc), parameter pietc::z198 =-z018
exp(2*pi*i*11/20)
Definition at line 180 of file pietc.f90.
complex(dpc), parameter pietc::z200 =-z020
exp(2*pi*i*5/9)
Definition at line 181 of file pietc.f90.
complex(dpc), parameter pietc::z202 =-z022
exp(2*pi*i*9/16)
Definition at line 182 of file pietc.f90.
complex(dpc), parameter pietc::z206 =-z026
exp(2*pi*i*4/7)
Definition at line 183 of file pietc.f90.
complex(dpc), parameter pietc::z210 =-z030
exp(2*pi*i*7/12)
Definition at line 184 of file pietc.f90.
complex(dpc), parameter pietc::z214 =-z034
exp(2*pi*i*19/32)
Definition at line 185 of file pietc.f90.
complex(dpc), parameter pietc::z216 =-z036
exp(2*pi*i*3/5)
Definition at line 186 of file pietc.f90.
complex(dpc), parameter pietc::z219 =-z039
exp(2*pi*i*17/28)
Definition at line 187 of file pietc.f90.
complex(dpc), parameter pietc::z220 =-z040
exp(2*pi*i*11/18)
Definition at line 188 of file pietc.f90.
complex(dpc), parameter pietc::z225 =-z045
exp(2*pi*i*5/8)
Definition at line 189 of file pietc.f90.
complex(dpc), parameter pietc::z230 =-z050
exp(2*pi*i*23/36)
Definition at line 190 of file pietc.f90.
complex(dpc), parameter pietc::z231 =-z051
exp(2*pi*i*9/14)
Definition at line 191 of file pietc.f90.
complex(dpc), parameter pietc::z234 =-z054
exp(2*pi*i*13/20)
Definition at line 192 of file pietc.f90.
complex(dpc), parameter pietc::z236 =-z056
exp(2*pi*i*21/32)
Definition at line 193 of file pietc.f90.
complex(dpc), parameter pietc::z240 =-z060
exp(2*pi*i*2/3)
Definition at line 194 of file pietc.f90.
complex(dpc), parameter pietc::z244 =-z064
exp(2*pi*i*19/28)
Definition at line 195 of file pietc.f90.
complex(dpc), parameter pietc::z248 =-z068
exp(2*pi*i*11/16)
Definition at line 196 of file pietc.f90.
complex(dpc), parameter pietc::z250 =-z070
exp(2*pi*i*25/36)
Definition at line 197 of file pietc.f90.
complex(dpc), parameter pietc::z252 =-z072
exp(2*pi*i*7/10)
Definition at line 198 of file pietc.f90.
complex(dpc), parameter pietc::z255 =-z075
exp(2*pi*i*17/24)
Definition at line 199 of file pietc.f90.
complex(dpc), parameter pietc::z257 =-z077
exp(2*pi*i*5/7)
Definition at line 200 of file pietc.f90.
complex(dpc), parameter pietc::z259 =-z079
exp(2*pi*i*23/32)
Definition at line 201 of file pietc.f90.
complex(dpc), parameter pietc::z260 =-z080
exp(2*pi*i*13/18)
Definition at line 202 of file pietc.f90.
complex(dpc), parameter pietc::z270 =-z090
exp(2*pi*i*3/4)
Definition at line 203 of file pietc.f90.
complex(dpc), parameter pietc::z280 =-z100
exp(2*pi*i*7/9)
Definition at line 204 of file pietc.f90.
complex(dpc), parameter pietc::z281 =-z101
exp(2*pi*i*25/32)
Definition at line 205 of file pietc.f90.
complex(dpc), parameter pietc::z283 =-z103
exp(2*pi*i*11/14)
Definition at line 206 of file pietc.f90.
complex(dpc), parameter pietc::z285 =-z105
exp(2*pi*i*19/24)
Definition at line 207 of file pietc.f90.
complex(dpc), parameter pietc::z288 =-z108
exp(2*pi*i*4/5)
Definition at line 208 of file pietc.f90.
complex(dpc), parameter pietc::z290 =-z110
exp(2*pi*i*29/36)
Definition at line 209 of file pietc.f90.
complex(dpc), parameter pietc::z292 =-z112
exp(2*pi*i*13/16)
Definition at line 210 of file pietc.f90.
complex(dpc), parameter pietc::z296 =-z116
exp(2*pi*i*23/28)
Definition at line 211 of file pietc.f90.
complex(dpc), parameter pietc::z300 =-z120
exp(2*pi*i*5/6)
Definition at line 212 of file pietc.f90.
complex(dpc), parameter pietc::z304 =-z124
exp(2*pi*i*27/32)
Definition at line 213 of file pietc.f90.
complex(dpc), parameter pietc::z306 =-z126
exp(2*pi*i*17/20)
Definition at line 214 of file pietc.f90.
complex(dpc), parameter pietc::z309 =-z129
exp(2*pi*i*6/7)
Definition at line 215 of file pietc.f90.
complex(dpc), parameter pietc::z310 =-z130
exp(2*pi*i*31/36)
Definition at line 216 of file pietc.f90.
complex(dpc), parameter pietc::z315 =-z135
exp(2*pi*i*7/8)
Definition at line 217 of file pietc.f90.
complex(dpc), parameter pietc::z320 =-z140
exp(2*pi*i*8/9)
Definition at line 218 of file pietc.f90.
complex(dpc), parameter pietc::z321 =-z141
exp(2*pi*i*25/28)
Definition at line 219 of file pietc.f90.
complex(dpc), parameter pietc::z324 =-z144
exp(2*pi*i*9/10)
Definition at line 220 of file pietc.f90.
complex(dpc), parameter pietc::z326 =-z146
exp(2*pi*i*29/32)
Definition at line 221 of file pietc.f90.
complex(dpc), parameter pietc::z330 =-z150
exp(2*pi*i*11/12)
Definition at line 222 of file pietc.f90.
complex(dpc), parameter pietc::z334 =-z154
exp(2*pi*i*13/14)
Definition at line 223 of file pietc.f90.
complex(dpc), parameter pietc::z338 =-z158
exp(2*pi*i*15/16)
Definition at line 224 of file pietc.f90.
complex(dpc), parameter pietc::z340 =-z160
exp(2*pi*i*17/18)
Definition at line 225 of file pietc.f90.
complex(dpc), parameter pietc::z342 =-z162
exp(2*pi*i*19/20)
Definition at line 226 of file pietc.f90.
complex(dpc), parameter pietc::z345 =-z165
exp(2*pi*i*23/24)
Definition at line 227 of file pietc.f90.
complex(dpc), parameter pietc::z347 =-z167
exp(2*pi*i*27/28)
Definition at line 228 of file pietc.f90.
complex(dpc), parameter pietc::z349 =-z169
exp(2*pi*i*31/32)
Definition at line 229 of file pietc.f90.
complex(dpc), parameter pietc::z350 =-z170
exp(2*pi*i*35/36)
Definition at line 230 of file pietc.f90.
Author
Generated automatically by Doxygen for grid_tools from the source code.