.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90 \- 
.PP
Standard integer, real, and complex single and double precision kinds\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBpkind\fP"
.br
.RI "\fIStandard integer, real, and complex single and double precision kinds\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Standard integer, real, and complex single and double precision kinds\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition in file \fBpkind\&.f90\fP\&.
.SH "Data Type Documentation"
.PP 
.SH "module pkind"
.PP 
Standard integer, real, and complex single and double precision kinds\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 7 of file pkind\&.f90\&.
.PP
\fBData Fields:\fP
.RS 4
integer, parameter \fIdp\fP Double precision real kind\&. 
.br
.PP
integer, parameter \fIdpc\fP Double precision real kind\&. 
.br
.PP
integer, parameter \fIdpi\fP Double precision integer kind\&. 
.br
.PP
integer, parameter \fIsp\fP Single precision real kind\&. 
.br
.PP
integer, parameter \fIspc\fP Single precision real kind\&. 
.br
.PP
integer, parameter \fIspi\fP Single precision integer kind\&. 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
