.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90 \- Standard integer, real, and complex single and double precision kinds\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBpkind\fP"
.br
.RI "Standard integer, real, and complex single and double precision kinds\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBpkind::dp\fP =selected_real_kind(15, 300)"
.br
.RI "Double precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::dpc\fP =dp"
.br
.RI "Double precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::dpi\fP =selected_int_kind(12)"
.br
.RI "Double precision integer kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::sp\fP =selected_real_kind(6, 30)"
.br
.RI "Single precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::spc\fP =sp"
.br
.RI "Single precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::spi\fP =selected_int_kind(6)"
.br
.RI "Single precision integer kind\&. "
.in -1c
.SH "Detailed Description"
.PP 
Standard integer, real, and complex single and double precision kinds\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition in file \fBpkind\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
