.TH "/home/ed/UFS_UTILS/sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90" 3 "Thu Mar 11 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ed/UFS_UTILS/sorc/grid_tools.fd/regional_esg_grid.fd/pkind.f90
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBpkind::dp\fP =selected_real_kind(15, 300)"
.br
.RI "Double precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::dpc\fP =dp"
.br
.RI "Double precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::dpi\fP =selected_int_kind(12)"
.br
.RI "Double precision integer kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::sp\fP =selected_real_kind(6, 30)"
.br
.RI "Single precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::spc\fP =sp"
.br
.RI "Single precision real kind\&. "
.ti -1c
.RI "integer, parameter \fBpkind::spi\fP =selected_int_kind(6)"
.br
.RI "Single precision integer kind\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "integer, parameter pkind::dp =selected_real_kind(15, 300)"

.PP
Double precision real kind\&. 
.PP
Definition at line 6 of file pkind\&.f90\&.
.SS "integer, parameter pkind::dpc =dp"

.PP
Double precision real kind\&. 
.PP
Definition at line 8 of file pkind\&.f90\&.
.SS "integer, parameter pkind::dpi =selected_int_kind(12)"

.PP
Double precision integer kind\&. 
.PP
Definition at line 4 of file pkind\&.f90\&.
.SS "integer, parameter pkind::sp =selected_real_kind(6, 30)"

.PP
Single precision real kind\&. 
.PP
Definition at line 5 of file pkind\&.f90\&.
.SS "integer, parameter pkind::spc =sp"

.PP
Single precision real kind\&. 
.PP
Definition at line 7 of file pkind\&.f90\&.
.SS "integer, parameter pkind::spi =selected_int_kind(6)"

.PP
Single precision integer kind\&. 
.PP
Definition at line 3 of file pkind\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
