.TH "pmat4::mobiusi" 3 "Thu Mar 11 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::mobiusi
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBzmobiusi\fP (aa, bb, cc, dd, zz, infz, zw, infw)"
.br
.RI "Perform the inverse of the mobius transformation with coefficients, {aa,bb,cc,dd}\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file pmat4\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat4::mobiusi::zmobiusi (complex(dpc), intent(in) aa, complex(dpc), intent(in) bb, complex(dpc), intent(in) cc, complex(dpc), intent(in) dd, complex(dpc), intent(in) zz, logical, intent(in) infz, complex(dpc), intent(out) zw, logical, intent(out) infw)\fC [private]\fP"

.PP
Perform the inverse of the mobius transformation with coefficients, {aa,bb,cc,dd}\&. 
.PP
\fBParameters\fP
.RS 4
\fIaa\fP Mobius transformation coefficients 
.br
\fIbb\fP Mobius transformation coefficients 
.br
\fIcc\fP Mobius transformation coefficients 
.br
\fIdd\fP Mobius transformation coefficients 
.br
\fIzz\fP ??? 
.br
\fIinfz\fP ??? 
.br
\fIzw\fP Inversed output 
.br
\fIinfw\fP ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 2282 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
