.TH "pmat::inv" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat::inv
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBcinvmt\fP (a)"
.br
.RI "Invert complex matrix in place\&. "
.ti -1c
.RI "subroutine \fBcinvmtf\fP (a, ff)"
.br
.RI "Invert a complex matrix in place, or flag if process fails\&. "
.ti -1c
.RI "subroutine \fBclinmmt\fP (a, b)"
.br
.RI "Invert complex linear system with multiple right-hand side vectors\&. "
.ti -1c
.RI "subroutine \fBclinmmtf\fP (a, b, ff)"
.br
.RI "Invert linear system with multiple right-hand side vectors, or flag failure\&. "
.ti -1c
.RI "subroutine \fBclinmvt\fP (a, b)"
.br
.RI "Invert linear system with single right-hand side vector\&. "
.ti -1c
.RI "subroutine \fBclinmvtf\fP (a, b, ff)"
.br
.RI "Invert complex linear system with single right-hand side vector\&. "
.ti -1c
.RI "subroutine \fBdinvmt\fP (a)"
.br
.RI "Invert double precision matrix in place\&. "
.ti -1c
.RI "subroutine \fBdinvmtf\fP (a, ff)"
.br
.RI "Invert a double precision matrix in place, or flag if process fails\&. "
.ti -1c
.RI "subroutine \fBdlinmmt\fP (a, b)"
.br
.RI "Invert linear system with multiple right-hand side vectors\&. "
.ti -1c
.RI "subroutine \fBdlinmmtf\fP (a, b, ff)"
.br
.RI "Invert linear system with multiple right-hand side vectors, or flag failure\&. "
.ti -1c
.RI "subroutine \fBdlinmvt\fP (a, b)"
.br
.RI "Invert linear system with single right-hand side vector\&. "
.ti -1c
.RI "subroutine \fBdlinmvtf\fP (a, b, ff)"
.br
.RI "Invert linear system with single right-hand side vector\&. "
.ti -1c
.RI "subroutine \fBiinvf\fP (imat, ff)"
.br
.RI "Invert integer square matrix, imat, if possible, but flag ff=\&.true\&. "
.ti -1c
.RI "subroutine \fBsinvmt\fP (a)"
.br
.RI "Invert single precision matrix in place\&. "
.ti -1c
.RI "subroutine \fBsinvmtf\fP (a, ff)"
.br
.RI "Invert a single precision matrix in place, or flag if process fails\&. "
.ti -1c
.RI "subroutine \fBslinmmt\fP (a, b)"
.br
.RI "Invert linear system with multiple right-hand side vectors\&. "
.ti -1c
.RI "subroutine \fBslinmmtf\fP (a, b, ff)"
.br
.RI "Invert linear system with multiple right-hand side vectors, or flag failure\&. "
.ti -1c
.RI "subroutine \fBslinmvt\fP (a, b)"
.br
.RI "Invert linear system with single right-hand side vector\&. "
.ti -1c
.RI "subroutine \fBslinmvtf\fP (a, b, ff)"
.br
.RI "Invert linear system with single right-hand side vector\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file pmat\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat::inv::cinvmt (complex(dpc), dimension(:,:), intent(inout) a)\fC [private]\fP"

.PP
Invert complex matrix in place\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP matrix 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 104 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::cinvmtf (complex(dpc), dimension(:,:), intent(inout) a, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert a complex matrix in place, or flag if process fails\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP matrix 
.br
\fIff\fP flag for error condition 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 191 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::clinmmt (complex(dpc), dimension(:,:), intent(inout) a, complex(dpc), dimension(:,:), intent(inout) b)\fC [private]\fP"

.PP
Invert complex linear system with multiple right-hand side vectors\&. Complex double precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vectors, output solution vectors 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 256 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::clinmmtf (complex(dpc), dimension(:,:), intent(inout) a, complex(dpc), dimension(:,:), intent(inout) b, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert linear system with multiple right-hand side vectors, or flag failure\&. Complex double precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vectors, output solution vectors 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 320 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::clinmvt (complex(dpc), dimension(:,:), intent(inout) a, complex(dpc), dimension(:), intent(inout) b)\fC [private]\fP"

.PP
Invert linear system with single right-hand side vector\&. Complex double precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vector, output solution vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 372 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::clinmvtf (complex(dpc), dimension(:,:), intent(inout) a, complex(dpc), dimension(:), intent(inout) b, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert complex linear system with single right-hand side vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vector, output solution vector 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 430 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::dinvmt (real(dp), dimension(:,:), intent(inout) a)\fC [private]\fP"

.PP
Invert double precision matrix in place\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP matrix 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 93 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::dinvmtf (real(dp), dimension(:,:), intent(inout) a, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert a double precision matrix in place, or flag if process fails\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP matrix 
.br
\fIff\fP flag for error condition 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 154 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::dlinmmt (real(dp), dimension(:,:), intent(inout) a, real(dp), dimension(:,:), intent(inout) b)\fC [private]\fP"

.PP
Invert linear system with multiple right-hand side vectors\&. Double precision version
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vectors, output solution vectors 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 243 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::dlinmmtf (real(dp), dimension(:,:), intent(inout) a, real(dp), dimension(:,:), intent(inout) b, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert linear system with multiple right-hand side vectors, or flag failure\&. Double precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vectors, output solution vectors 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 295 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::dlinmvt (real(dp), dimension(:,:), intent(inout) a, real(dp), dimension(:), intent(inout) b)\fC [private]\fP"

.PP
Invert linear system with single right-hand side vector\&. Double precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vector, output solution vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 358 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::dlinmvtf (real(dp), dimension(:,:), intent(inout) a, real(dp), dimension(:), intent(inout) b, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert linear system with single right-hand side vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vector, output solution vector 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 408 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::iinvf (integer(spi), dimension(:,:), intent(inout) imat, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert integer square matrix, imat, if possible, but flag ff=\&.true\&. if not possible\&. (Determinant of imat must be +1 or -1)
.PP
\fBParameters:\fP
.RS 4
\fIimat\fP integer square matrix 
.br
\fIff\fP error flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 452 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::sinvmt (real(sp), dimension(:,:), intent(inout) a)\fC [private]\fP"

.PP
Invert single precision matrix in place\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP matrix 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 82 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::sinvmtf (real(sp), dimension(:,:), intent(inout) a, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert a single precision matrix in place, or flag if process fails\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP matrix 
.br
\fIff\fP flag for error condition 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 116 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::slinmmt (real(sp), dimension(:,:), intent(inout) a, real(sp), dimension(:,:), intent(inout) b)\fC [private]\fP"

.PP
Invert linear system with multiple right-hand side vectors\&. Single precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vectors, output solution vectors 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 230 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::slinmmtf (real(sp), dimension(:,:), intent(inout) a, real(sp), dimension(:,:), intent(inout) b, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert linear system with multiple right-hand side vectors, or flag failure\&. Single precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vectors, output solution vectors 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 270 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::slinmvt (real(sp), dimension(:,:), intent(inout) a, real(sp), dimension(:), intent(inout) b)\fC [private]\fP"

.PP
Invert linear system with single right-hand side vector\&. Single precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vector, output solution vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 344 of file pmat\&.f90\&.
.SS "subroutine pmat::inv::slinmvtf (real(sp), dimension(:,:), intent(inout) a, real(sp), dimension(:), intent(inout) b, logical, intent(out) ff)\fC [private]\fP"

.PP
Invert linear system with single right-hand side vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Invertible system matrix, destroyed on output 
.br
\fIb\fP input RHS vector, output solution vector 
.br
\fIff\fP failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 386 of file pmat\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
