.TH "pmat4::diag" 3 "Thu Mar 11 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::diag
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function, dimension(size(a), size(a)) \fBdiagn_d\fP (a)"
.br
.RI "Calculation for diagn_d function\&. "
.ti -1c
.RI "integer(spi) function, dimension(size(a), size(a)) \fBdiagn_i\fP (a)"
.br
.RI "Calculation for diagn_i function\&. "
.ti -1c
.RI "real(sp) function, dimension(size(a), size(a)) \fBdiagn_s\fP (a)"
.br
.RI "Calculation for diagn_s function\&. "
.ti -1c
.RI "real(dp) function, dimension(size(b, 1)) \fBdiagnn_d\fP (b)"
.br
.RI "Calculation for diagnn_d function\&. "
.ti -1c
.RI "integer(spi) function, dimension(size(b, 1)) \fBdiagnn_i\fP (b)"
.br
.RI "Calculation for diagnn_i function\&. "
.ti -1c
.RI "real(sp) function, dimension(size(b, 1)) \fBdiagnn_s\fP (b)"
.br
.RI "Calculation for diagnn_s function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file pmat4\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function, dimension(size(a),size(a)) pmat4::diag::diagn_d (real(dp), dimension(:), intent(in) a)\fC [private]\fP"

.PP
Calculation for diagn_d function\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP real type input value 
.RE
.PP
\fBReturns\fP
.RS 4
b result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 487 of file pmat4\&.f90\&.
.SS "integer(spi) function, dimension(size(a),size(a)) pmat4::diag::diagn_i (integer(spi), dimension(:), intent(in) a)\fC [private]\fP"

.PP
Calculation for diagn_i function\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP input value 
.RE
.PP
\fBReturns\fP
.RS 4
b result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 502 of file pmat4\&.f90\&.
.SS "real(sp) function, dimension(size(a),size(a)) pmat4::diag::diagn_s (real(sp), dimension(:), intent(in) a)\fC [private]\fP"

.PP
Calculation for diagn_s function\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP real type input value 
.RE
.PP
\fBReturns\fP
.RS 4
b result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 472 of file pmat4\&.f90\&.
.SS "real(dp) function, dimension(size(b,1)) pmat4::diag::diagnn_d (real(dp), dimension(:,:), intent(in) b)\fC [private]\fP"

.PP
Calculation for diagnn_d function\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP real type input value 
.RE
.PP
\fBReturns\fP
.RS 4
a result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 530 of file pmat4\&.f90\&.
.SS "integer(spi) function, dimension(size(b,1)) pmat4::diag::diagnn_i (integer(spi), dimension(:,:), intent(in) b)\fC [private]\fP"

.PP
Calculation for diagnn_i function\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP integer type input value 
.RE
.PP
\fBReturns\fP
.RS 4
a result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 544 of file pmat4\&.f90\&.
.SS "real(sp) function, dimension(size(b,1)) pmat4::diag::diagnn_s (real(sp), dimension(:,:), intent(in) b)\fC [private]\fP"

.PP
Calculation for diagnn_s function\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP real type input value 
.RE
.PP
\fBReturns\fP
.RS 4
a result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 516 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
