.TH "pmat4::dlltoxy" 3 "Tue Mar 9 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::dlltoxy
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBdlltoxy_d\fP (rlat, drlat, drlon, x2)"
.br
.RI "Calculate dlltoxy_d\&. "
.ti -1c
.RI "subroutine \fBdlltoxy_s\fP (rlat, drlat, drlon, x2)"
.br
.RI "Calculate dlltoxy_s\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file pmat4\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat4::dlltoxy::dlltoxy_d (real(dp), intent(in) rlat, real(dp), intent(in) drlat, real(dp), intent(in) drlon, real(dp), dimension(2), intent(out) x2)\fC [private]\fP"

.PP
Calculate dlltoxy_d\&. 
.PP
\fBParameters\fP
.RS 4
\fIrlat\fP latitude 
.br
\fIdrlat\fP latitude 
.br
\fIdrlon\fP longitudes 
.br
\fIx2\fP output 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 901 of file pmat4\&.f90\&.
.SS "subroutine pmat4::dlltoxy::dlltoxy_s (real(sp), intent(in) rlat, real(sp), intent(in) drlat, real(sp), intent(in) drlon, real(sp), dimension(2), intent(out) x2)\fC [private]\fP"

.PP
Calculate dlltoxy_s\&. 
.PP
\fBParameters\fP
.RS 4
\fIrlat\fP latitude 
.br
\fIdrlat\fP latitude 
.br
\fIdrlon\fP longitudes 
.br
\fIx2\fP output 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 884 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
