pmat5
NAME
pmat5 - Utility routines for orienting the globe and basic geographical mappings.
SYNOPSIS
Data Types
interface ctoc_schm
interface ctog
interface ctogr
interface frametwist
interface grtoc
interface gtoc
interface gtoframe
interface ininmap
interface inivmap
interface paraframe
interface plctoc
interface plrot
interface plroti
Functions/Subroutines
subroutine dctoc (s, xc1, xc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s.
subroutine dctocd (s, xc1, xc2, dxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, and its jacobian, dxc2.
subroutine dctocdd (s, xc1, xc2, dxc2, ddxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, its jacobian, dxc2, and its 2nd derivative, ddxc2.
subroutine dctog (xe, dlat, dlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine dctogr (xe, rlat, rlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (radians) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine dgrtoc (rlat, rlon, xe)
Transform 'Geographical' to 'Cartesian' coordinates.
subroutine dgrtocd (rlat, rlon, xe, dxedlat, dxedlon)
Transform 'Geographical' to 'Cartesian' coordinates, together with the partial derivatives of cartesians wrt latitude and longitude.
subroutine dgrtocdd (rlat, rlon, xe, dxedlat, dxedlon, ddxedlatdlat, ddxedlatdlon, ddxedlondlon)
Transform 'Geographical' to 'Cartesian' coordinates, together with the 1st and 2nd partial derivatives of cartesians wrt latitude and longitude.
subroutine dgtoc (dlat, dlon, xe)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine dgtocd (dlat, dlon, xe, dxedlat, dxedlon)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine dgtocdd (dlat, dlon, xe, dxedlat, dxedlon, ddxedlatdlat, ddxedlatdlon, ddxedlondlon)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine dininmap (alon0, alat0, rot3)
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) on the projection axis.
subroutine dinivmap (alon0, alat0, rot3)
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) at the viewing nadir.
subroutine dplrot (rot3, n, x, y, z)
Apply a constant rotation to a three dimensional polyline.
subroutine dplroti (rot3, n, x, y, z)
Invert the rotation of a three-dimensional polyline.
subroutine, public frametwist (xp, yp, zp, xv, yv, zv, twist)
Given a principal cartesian orthonormal frame, {xp,yp,zp} (i.e., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V.
subroutine gtoframem (plat, plon, orth)
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth.
subroutine gtoframev (plat, plon, xp, yp, zp)
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates.
subroutine, public paraframe (xp, yp, zp, xv, yv, zv)
Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V.
subroutine, public plctoc (s, n, x, y, z)
Perform Schmidt transformation with scaling parameter s to a polyline.
subroutine, public plrot (rot3, n, x, y, z)
Apply a constant rotation to a three dimensional polyline.
subroutine, public plroti (rot3, n, x, y, z)
Invert the rotation of a three-dimensional polyline.
subroutine sctoc (s, xc1, xc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s.
subroutine sctocd (s, xc1, xc2, dxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, and its jacobian, dxc2.
subroutine sctocdd (s, xc1, xc2, dxc2, ddxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, its jacobian, dxc2, and its 2nd derivative, ddxc2.
subroutine sctog (xe, dlat, dlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine sctogr (xe, rlat, rlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (radians) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine sframetwist (sxp, syp, szp, sxv, syv, szv, stwist)
Given a principal cartesian orthonormal frame, {xp,yp,zp} (i.e., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V.
subroutine sgrtoc (rlat, rlon, xe)
Transform 'Geographical' to 'Cartesian' coordinates.
subroutine sgrtocd (rlat, rlon, xe, dxedlat, dxedlon)
Transform 'Geographical' to 'Cartesian' coordinates, together with the partial derivatives of cartesians wrt latitude and longitude.
subroutine sgrtocdd (rlat, rlon, xe, dxedlat, dxedlon, ddxedlatdlat, ddxedlatdlon, ddxedlondlon)
Transform 'Geographical' to 'Cartesian' coordinates, together with the 1st and 2nd partial derivatives of cartesians wrt latitude and longitude.
subroutine sgtoc (dlat, dlon, xe)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine sgtocd (dlat, dlon, xe, dxedlat, dxedlon)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine sgtocdd (dlat, dlon, xe, dxedlat, dxedlon, ddxedlatdlat, ddxedlatdlon, ddxedlondlon)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian.
subroutine sgtoframem (splat, splon, sorth)
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth.
subroutine sgtoframev (splat, splon, sxp, syp, szp)
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates.
subroutine sininmap (alon0, alat0, rot3)
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) on the projection axis.
subroutine sinivmap (alon0, alat0, rot3)
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) at the viewing nadir.
subroutine sparaframe (sxp, syp, szp, sxv, syv, szv)
Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V.
Detailed Description
Utility routines for orienting the globe and basic geographical mappings.
Author:
R. J. Purser
Function/Subroutine Documentation
subroutine pmat5::dctoc (real(dp), intent(in) s, real(dp), dimension(3), intent(inout) xc1, real(dp), dimension(3), intent(inout) xc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s.
Parameters:
s Schmidt scaling parameter.
xc1 input cartesian 3-vector.
xc2 output cartesian unit 3-vector.
Author:
R. J. Purser
Definition at line 916 of file pmat5.f90.
References pietc::u1, and pietc::u2.
subroutine pmat5::dctocd (real(dp), intent(in) s, real(dp), dimension(3), intent(inout) xc1, real(dp), dimension(3), intent(inout) xc2, real(dp), dimension(3,3), intent(out) dxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, and its jacobian, dxc2.
Parameters:
s Schmidt scaling parameter.
xc1 input cartesian 3-vector.
xc2 output cartesian unit 3-vector.
dxc2 jacobian 1st derivative, d(xc2)/d(xc1).
Author:
R. J. Purser
Definition at line 947 of file pmat5.f90.
References pietc::u0, pietc::u1, and pietc::u2.
subroutine pmat5::dctocdd (real(dp), intent(in) s, real(dp), dimension(3), intent(inout) xc1, real(dp), dimension(3), intent(inout) xc2, real(dp), dimension(3,3), intent(out) dxc2, real(dp), dimension(3,3,3), intent(out) ddxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, its jacobian, dxc2, and its 2nd derivative, ddxc2.
Parameters:
s Schmidt scaling parameter.
xc1 input cartesian 3-vector.
xc2 output cartesian unit 3-vector.
dxc2 jacobian 1st derivative, d(xc2)/d(xc1).
ddxc2 2nd derivative, d^2(xc2)/(d(xc1)d(xc1)).
Author:
R. J. Purser
Definition at line 988 of file pmat5.f90.
References pietc::u0, pietc::u1, and pietc::u2.
subroutine pmat5::dctog (real(dp), dimension(3), intent(in) xe, real(dp), intent(out) dlat, real(dp), intent(out) dlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Double precision version.
Parameters:
xe Earth-centered cartesian unit 3-vector.
dlat degrees latitude.
dlon degrees longitude.
Author:
R. J. Purser
Definition at line 398 of file pmat5.f90.
References pietc::rtod, and pietc::u0.
subroutine pmat5::dctogr (real(dp), dimension(3), intent(in) xe, real(dp), intent(out) rlat, real(dp), intent(out) rlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (radians) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Double precision version.
Parameters:
xe Earth-centered cartesian unit 3-vector.
rlat radians latitude.
rlon radians longitude.
Author:
R. J. Purser
Definition at line 198 of file pmat5.f90.
References pietc::u0.
subroutine pmat5::dgrtoc (real(dp), intent(in) rlat, real(dp), intent(in) rlon, real(dp), dimension(3), intent(out) xe) [private]
Transform 'Geographical' to 'Cartesian' coordinates. Double proecision version.
Parameters:
rlat Latitude (radians) of point.
rlon Longitude (radians) of point.
xe Earth-centered cartesian unit 3-vector of point.
Author:
R. J. Purser
Definition at line 237 of file pmat5.f90.
subroutine pmat5::dgrtocd (real(dp), intent(in) rlat, real(dp), intent(in) rlon, real(dp), dimension(3), intent(out) xe, real(dp), dimension(3), intent(out) dxedlat, real(dp), dimension(3), intent(out) dxedlon) [private]
Transform 'Geographical' to 'Cartesian' coordinates, together with the partial derivatives of cartesians wrt latitude and longitude. Double precision version.
Parameters:
rlat Latitude (radians) of point.
rlon Longitude (radians) of point.
xe Earth-centered cartesian unit 3-vector of point.
dxedlat Derivative, d(xe)/d(rlat).
dxedlon Derivative, d(xe)/d(rlon).
Author:
R. J. Purser
Definition at line 280 of file pmat5.f90.
References pietc::u0.
Referenced by sgrtocd().
subroutine pmat5::dgrtocdd (real(dp), intent(in) rlat, real(dp), intent(in) rlon, real(dp), dimension(3), intent(out) xe, real(dp), dimension(3), intent(out) dxedlat, real(dp), dimension(3), intent(out) dxedlon, real(dp), dimension(3), intent(out) ddxedlatdlat, real(dp), dimension(3), intent(out) ddxedlatdlon, real(dp), dimension(3), intent(out) ddxedlondlon) [private]
Transform 'Geographical' to 'Cartesian' coordinates, together with the 1st and 2nd partial derivatives of cartesians wrt latitude and longitude. Double precision version.
Parameters:
rlat Latitude (radians) of point.
rlon Longitude (radians) of point.
xe Earth-centered cartesian unit 3-vector of point.
dxedlat Derivative, d(xe)/d(rlat).
dxedlon Derivative, d(xe)/d(rlon).
ddxedlatdlat Derivative, d^2(xe)/(d(rlat)d(rlat)).
ddxedlatdlon Derivative, d^2(xe)/(d(rlat)d(rlon)).
ddxedlondlon Derivative, d^2(xe)/(d(rlon)d(rlon)).
Author:
R. J. Purser
Definition at line 340 of file pmat5.f90.
References pietc::u0.
subroutine pmat5::dgtoc (real(dp), intent(in) dlat, real(dp), intent(in) dlon, real(dp), dimension(3), intent(out) xe)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Double precision version.
Parameters:
dlat degrees latitude.
dlon degrees longitude.
xe cartesian unit 3-vector.
Author:
R. J. Purser
Definition at line 445 of file pmat5.f90.
References pietc::dtor.
subroutine pmat5::dgtocd (real(dp), intent(in) dlat, real(dp), intent(in) dlon, real(dp), dimension(3), intent(out) xe, real(dp), dimension(3), intent(out) dxedlat, real(dp), dimension(3), intent(out) dxedlon) [private]
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Also, return the partial derivatives of xe wrt latitude and longitude. Double precision version.
Parameters:
dlat degrees latitude.
dlon degrees longitude.
xe cartesian unit 3-vector.
dxedlat derivative, d(xe)/d(dlat).
dxedlon derivative, d(xe)/d(dlon).
Author:
R. J. Purser
Definition at line 496 of file pmat5.f90.
References pietc::dtor, and pietc::u0.
Referenced by sgtocd().
subroutine pmat5::dgtocdd (real(dp), intent(in) dlat, real(dp), intent(in) dlon, real(dp), dimension(3), intent(out) xe, real(dp), dimension(3), intent(out) dxedlat, real(dp), dimension(3), intent(out) dxedlon, real(dp), dimension(3), intent(out) ddxedlatdlat, real(dp), dimension(3), intent(out) ddxedlatdlon, real(dp), dimension(3), intent(out) ddxedlondlon) [private]
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Also, return the 1st and 2nd partial derivatives of xe wrt latitude and longitude. Double precision version.
Parameters:
dlat degrees latitude.
dlon degrees longitude.
xe cartesian unit 3-vector.
dxedlat d(xe)/d(dlat).
dxedlon d(xe)/d(dlon).
ddxedlatdlat derivative, d^2(xe)/(d(dlat)d(dlat)).
ddxedlatdlon derivative, d^2(xe)/(d(dlat)d(dlon)).
ddxedlondlon derivative, d^2(xe)/(d(dlon)d(dlon)).
Author:
R. J. Purser
Definition at line 565 of file pmat5.f90.
References pietc::dtor, and pietc::u0.
Referenced by sgrtocdd(), and sgtocdd().
subroutine pmat5::dininmap (real(dp), intent(in) alon0, real(dp), intent(in) alat0, real(dp), dimension(3,3), intent(out) rot3)
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) on the projection axis. Double precision version.
Parameters:
alon0 geographical longitude (degrees) of projection center.
alat0 geographical latitude (degrees) of projection center.
rot3 rotation matrix.
Author:
R. J. Purser
Definition at line 86 of file pmat5.f90.
References pietc::dtor, and pietc::u0.
subroutine pmat5::dinivmap (real(dp), intent(in) alon0, real(dp), intent(in) alat0, real(dp), dimension(3,3), intent(out) rot3)
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) at the viewing nadir. Double precision version.
Parameters:
alon0 geographical longitude (degrees) of viewing nadir.
alat0 geographical latitude (degrees) of viewing nadir.
rot3 rotation matrix.
Author:
R. J. Purser
Definition at line 140 of file pmat5.f90.
References pietc::dtor, and pietc::u0.
subroutine pmat5::dplrot (real(dp), dimension(3,3), intent(in) rot3, integer, intent(in) n, real(dp), dimension(n), intent(inout) x, real(dp), dimension(n), intent(inout) y, real(dp), dimension(n), intent(inout) z) [private]
Apply a constant rotation to a three dimensional polyline.
Parameters:
rot3 rotation matrix.
n number of points in the polyline.
x cartesian components of the three dimensional polyline.
y cartesian components of the three dimensional polyline.
z cartesian components of the three dimensional polyline.
Author:
R. J. Purser
Definition at line 1084 of file pmat5.f90.
subroutine pmat5::dplroti (real(dp), dimension(3,3), intent(in) rot3, integer, intent(in) n, real(dp), dimension(n), intent(inout) x, real(dp), dimension(n), intent(inout) y, real(dp), dimension(n), intent(inout) z) [private]
Invert the rotation of a three-dimensional polyline.
Parameters:
rot3 rotation to be inverted.
n number of points in the polyline.
x cartesian components of the three dimensional polyline.
y cartesian components of the three dimensional polyline.
z cartesian components of the three dimensional polyline.
Author:
R. J. Purser
Definition at line 1106 of file pmat5.f90.
subroutine, public pmat5::frametwist (real(dp), dimension(3), intent(in) xp, real(dp), dimension(3), intent(in) yp, real(dp), dimension(3), intent(in) zp, real(dp), dimension(3), intent(in) xv, real(dp), dimension(3), intent(in) yv, real(dp), dimension(3), intent(in) zv, real(dp), intent(out) twist)
Given a principal cartesian orthonormal frame, {xp,yp,zp} (i.e., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V. Note that, by symmetry, transposing P and V leads to the opposite twist. Double precision version.
Parameters:
xp P-frame cartesian X-vector.
yp P-frame cartesian Y-vector.
zp P-frame cartesian Z-vector.
xv V-frame cartesian X-vector.
yv V-frame cartesian Y-vector.
zv V-frame cartesian Z-vector.
twist relative rotation angle (radians) of frames.
Author:
R. J. Purser
Definition at line 778 of file pmat5.f90.
subroutine pmat5::gtoframem (real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), dimension(3,3), intent(out) orth) [private]
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth. Double precision version.
Parameters:
plat latitude (degrees) of point.
plon longitude (degrees) of point.
orth orthonormal matrix.
Author:
R. J. Purser
Definition at line 617 of file pmat5.f90.
References gtoframev().
Referenced by sgtoframem().
subroutine pmat5::gtoframev (real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), dimension(3), intent(out) xp, real(dp), dimension(3), intent(out) yp, real(dp), dimension(3), intent(out) zp) [private]
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates. Double precision version.
Parameters:
plat latitude (degrees) of point.
plon longitude (degrees) of point.
xp unit X-basis vector of cartesian frame.
yp unit Y-basis vector of cartesian frame.
zp unit Z-basis vector of cartesian frame.
Author:
R. J. Purser
Definition at line 662 of file pmat5.f90.
References pietc::u0, and pietc::u1.
Referenced by gtoframem(), and sgtoframev().
subroutine, public pmat5::paraframe (real(dp), dimension(3), intent(in) xp, real(dp), dimension(3), intent(in) yp, real(dp), dimension(3), intent(in) zp, real(dp), dimension(3), intent(out) xv, real(dp), dimension(3), intent(out) yv, real(dp), dimension(3), intent(in) zv)
Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V. Double precision version.
Parameters:
xp reference orthonormal P-frame cartesian X-vector.
yp reference orthonormal P-frame cartesian Y-vector.
zp reference orthonormal P-frame cartesian Z-vector.
xv V-frame cartesian X-vector.
yv V-frame cartesian Y-vector.
zv dependent point zenith, V-frame cartesian Z-vector.
Author:
R. J. Purser
Definition at line 719 of file pmat5.f90.
subroutine, public pmat5::plctoc (real(sp), intent(in) s, integer, intent(in) n, real(sp), dimension(n), intent(inout) x, real(sp), dimension(n), intent(inout) y, real(sp), dimension(n), intent(inout) z)
Perform Schmidt transformation with scaling parameter s to a polyline.
Parameters:
s Schmidt scaling parameter.
n number of points in the polyline.
x cartesian components of the three dimensional polyline.
y cartesian components of the three dimensional polyline.
z cartesian components of the three dimensional polyline.
Author:
R. J. Purser
Definition at line 1128 of file pmat5.f90.
subroutine, public pmat5::plrot (real(sp), dimension(3,3), intent(in) rot3, integer, intent(in) n, real(sp), dimension(n), intent(inout) x, real(sp), dimension(n), intent(inout) y, real(sp), dimension(n), intent(inout) z)
Apply a constant rotation to a three dimensional polyline.
Parameters:
rot3 rotation matrix.
n number of points in the polyline.
x cartesian components of the three dimensional polyline.
y cartesian components of the three dimensional polyline.
z cartesian components of the three dimensional polyline.
Author:
R. J. Purser
Definition at line 1040 of file pmat5.f90.
References pietc::t.
subroutine, public pmat5::plroti (real(sp), dimension(3,3), intent(in) rot3, integer, intent(in) n, real(sp), dimension(n), intent(inout) x, real(sp), dimension(n), intent(inout) y, real(sp), dimension(n), intent(inout) z)
Invert the rotation of a three-dimensional polyline.
Parameters:
rot3 rotation to be inverted.
n number of points in the polyline.
x cartesian components of the three dimensional polyline.
y cartesian components of the three dimensional polyline.
z cartesian components of the three dimensional polyline.
Author:
R. J. Purser
Definition at line 1062 of file pmat5.f90.
References pietc::t.
subroutine pmat5::sctoc (real(sp), intent(in) s, real(sp), dimension(3), intent(inout) xc1, real(sp), dimension(3), intent(inout) xc2) [private]
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s.
Parameters:
s Schmidt scaling parameter
xc1 input cartesian 3-vector
xc2 output cartesian unit 3-vector
Author:
R. J. Purser
Definition at line 795 of file pmat5.f90.
subroutine pmat5::sctocd (real(sp), intent(in) s, real(sp), dimension(3), intent(inout) xc1, real(sp), dimension(3), intent(inout) xc2, real(sp), dimension(3,3), intent(out) dxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, and its jacobian, dxc2.
Parameters:
s Schmidt scaling parameter.
xc1 input cartesian 3-vector.
xc2 output cartesian unit 3-vector.
dxc2 jacobian 1st derivative, d(xc2)/d(xc1).
Author:
R. J. Purser
Definition at line 825 of file pmat5.f90.
subroutine pmat5::sctocdd (real(sp), intent(in) s, real(sp), dimension(3), intent(inout) xc1, real(sp), dimension(3), intent(inout) xc2, real(sp), dimension(3,3), intent(out) dxc2, real(sp), dimension(3,3,3), intent(out) ddxc2)
Evaluate Schmidt transformation, xc1 --> xc2, with scaling parameter s, its jacobian, dxc2, and its 2nd derivative, ddxc2.
Parameters:
s Schmidt scaling parameter.
xc1 input cartesian 3-vector.
xc2 output cartesian unit 3-vector.
dxc2 jacobian 1st derivative, d(xc2)/d(xc1).
ddxc2 2nd derivative, d^2(xc2)/(d(xc1)d(xc1)).
Author:
R. J. Purser
Definition at line 866 of file pmat5.f90.
subroutine pmat5::sctog (real(sp), dimension(3), intent(in) xe, real(sp), intent(out) dlat, real(sp), intent(out) dlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Single precision version.
Parameters:
xe Earth-centered cartesian unit 3-vector.
dlat degrees latitude.
dlon degrees longitude.
Author:
R. J. Purser
Date:
1994
Definition at line 373 of file pmat5.f90.
subroutine pmat5::sctogr (real(sp), dimension(3), intent(in) xe, real(sp), intent(out) rlat, real(sp), intent(out) rlon)
Transform 'Cartesian' to 'Geographical' coordinates, where the geographical coordinates refer to latitude and longitude (radians) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Single precision version.
Parameters:
xe Earth-centered cartesian unit 3-vector.
rlat radians latitude.
rlon radians longitude.
Author:
R. J. Purser
Definition at line 173 of file pmat5.f90.
subroutine pmat5::sframetwist (real(sp), dimension(3), intent(in) sxp, real(sp), dimension(3), intent(in) syp, real(sp), dimension(3), intent(in) szp, real(sp), dimension(3), intent(in) sxv, real(sp), dimension(3), intent(in) syv, real(sp), dimension(3), intent(in) szv, real(sp), intent(out) stwist)
Given a principal cartesian orthonormal frame, {xp,yp,zp} (i.e., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V. Note that, by symmetry, transposing P and V leads to the opposite twist. Single precision version.
Parameters:
sxp P-frame cartesian X-vector.
syp P-frame cartesian Y-vector.
szp P-frame cartesian Z-vector.
sxv V-frame cartesian X-vector.
syv V-frame cartesian Y-vector.
szv V-frame cartesian Z-vector.
stwist relative rotation angle (radians) of frames.
Author:
R. J. Purser
Definition at line 751 of file pmat5.f90.
subroutine pmat5::sgrtoc (real(sp), intent(in) rlat, real(sp), intent(in) rlon, real(sp), dimension(3), intent(out) xe)
Transform 'Geographical' to 'Cartesian' coordinates. Single proecision version.
Parameters:
rlat Latitude (radians) of point.
rlon Longitude (radians) of point.
xe Earth-centered cartesian unit 3-vector of point.
Author:
R. J. Purser
Definition at line 220 of file pmat5.f90.
subroutine pmat5::sgrtocd (real(sp), intent(in) rlat, real(sp), intent(in) rlon, real(sp), dimension(3), intent(out) xe, real(sp), dimension(3), intent(out) dxedlat, real(sp), dimension(3), intent(out) dxedlon) [private]
Transform 'Geographical' to 'Cartesian' coordinates, together with the partial derivatives of cartesians wrt latitude and longitude. Single precision version.
Parameters:
rlat Latitude (radians) of point.
rlon Longitude (radians) of point.
xe Earth-centered cartesian unit 3-vector of point.
dxedlat Derivative, d(xe)/d(rlat).
dxedlon Derivative, d(xe)/d(rlon).
Author:
R. J. Purser
Definition at line 257 of file pmat5.f90.
References dgrtocd().
subroutine pmat5::sgrtocdd (real(sp), intent(in) rlat, real(sp), intent(in) rlon, real(sp), dimension(3), intent(out) xe, real(sp), dimension(3), intent(out) dxedlat, real(sp), dimension(3), intent(out) dxedlon, real(sp), dimension(3), intent(out) ddxedlatdlat, real(sp), dimension(3), intent(out) ddxedlatdlon, real(sp), dimension(3), intent(out) ddxedlondlon)
Transform 'Geographical' to 'Cartesian' coordinates, together with the 1st and 2nd partial derivatives of cartesians wrt latitude and longitude. Single precision version.
Parameters:
rlat Latitude (radians) of point.
rlon Longitude (radians) of point.
xe Earth-centered cartesian unit 3-vector of point.
dxedlat Derivative, d(xe)/d(rlat).
dxedlon Derivative, d(xe)/d(rlon).
ddxedlatdlat Derivative, d^2(xe)/(d(rlat)d(rlat)).
ddxedlatdlon Derivative, d^2(xe)/(d(rlat)d(rlon)).
ddxedlondlon Derivative, d^2(xe)/(d(rlon)d(rlon)).
Author:
R. J. Purser
Definition at line 307 of file pmat5.f90.
References dgtocdd().
subroutine pmat5::sgtoc (real(sp), intent(in) dlat, real(sp), intent(in) dlon, real(sp), dimension(3), intent(out) xe)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Single precision version.
Parameters:
dlat degrees latitude.
dlon degrees longitude.
xe Earth-centered cartesian unit 3-vector.
Author:
R. J. Purser
Date:
1994
Definition at line 423 of file pmat5.f90.
subroutine pmat5::sgtocd (real(sp), intent(in) dlat, real(sp), intent(in) dlon, real(sp), dimension(3), intent(out) xe, real(sp), dimension(3), intent(out) dxedlat, real(sp), dimension(3), intent(out) dxedlon)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Also, return the partial derivatives of xe wrt latitude and longitude. Single precision version.
Parameters:
dlat degrees latitude.
dlon degrees longitude.
xe cartesian unit 3-vector.
dxedlat derivative, d(xe)/d(dlat).
dxedlon derivative, d(xe)/d(dlon).
Author:
R. J. Purser
Definition at line 470 of file pmat5.f90.
References dgtocd().
subroutine pmat5::sgtocdd (real(sp), intent(in) dlat, real(sp), intent(in) dlon, real(sp), dimension(3), intent(out) xe, real(sp), dimension(3), intent(out) dxedlat, real(sp), dimension(3), intent(out) dxedlon, real(sp), dimension(3), intent(out) ddxedlatdlat, real(sp), dimension(3), intent(out) ddxedlatdlon, real(sp), dimension(3), intent(out) ddxedlondlon)
Transform 'Geographical' to 'Cartesian' coordinates, where the geographical coordinates refer to latitude and longitude (degrees) and cartesian coordinates are standard earth-centered cartesian coordinates: xe(3) pointing north, xe(1) pointing to the 0-meridian. Also, return the 1st and 2nd partial derivatives of xe wrt latitude and longitude. Single precision version.
Parameters:
dlat degrees latitude.
dlon degrees longitude.
xe cartesian unit 3-vector.
dxedlat derivative, d(xe)/d(dlat).
dxedlon derivative, d(xe)/d(dlon).
ddxedlatdlat derivative, d^2(xe)/(d(dlat)d(dlat)).
ddxedlatdlon derivative, d^2(xe)/(d(dlat)d(dlon)).
ddxedlondlon derivative, d^2(xe)/(d(dlon)d(dlon)).
Author:
R. J. Purser
Definition at line 528 of file pmat5.f90.
References dgtocdd().
subroutine pmat5::sgtoframem (real(sp), intent(in) splat, real(sp), intent(in) splon, real(sp), dimension(3,3), intent(out) sorth)
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth. Single precision version.
Parameters:
splat latitude (degrees) of point.
splon longitude (degrees) of point.
sorth orthonormal matrix.
Author:
R. J. Purser
Definition at line 600 of file pmat5.f90.
References gtoframem().
subroutine pmat5::sgtoframev (real(sp), intent(in) splat, real(sp), intent(in) splon, real(sp), dimension(3), intent(out) sxp, real(sp), dimension(3), intent(out) syp, real(sp), dimension(3), intent(out) szp) [private]
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates. Single precision version.
Parameters:
splat latitude (degrees) of point.
splon longitude (degrees) of point.
sxp xp unit X-basis vector of cartesian frame.
syp yp unit Y-basis vector of cartesian frame.
szp zp unit Z-basis vector of cartesian frame.
Author:
R. J. Purser
Definition at line 637 of file pmat5.f90.
References gtoframev().
subroutine pmat5::sininmap (real(sp), intent(in) alon0, real(sp), intent(in) alat0, real(sp), dimension(3,3), intent(out) rot3) [private]
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) on the projection axis. Single precision version.
Parameters:
alon0 geographical longitude (degrees) of projection center.
alat0 geographical latitude (degrees) of projection center.
rot3 rotation matrix.
Author:
R. J. Purser
Date:
1995
Definition at line 64 of file pmat5.f90.
subroutine pmat5::sinivmap (real(sp), intent(in) alon0, real(sp), intent(in) alat0, real(sp), dimension(3,3), intent(out) rot3)
Initialize the rotation matrix ROT3 needed to transform standard earth-centered cartesian components to the alternative cartesian frame oriented so as to put geographical point (ALAT0,ALON0) at the viewing nadir. Single precision version.
Parameters:
alon0 geographical longitude (degrees) of viewing nadir.
alat0 geographical latitude (degrees) of viewing nadir.
rot3 rotation matrix.
Author:
R. J. Purser
Date:
1995
Definition at line 108 of file pmat5.f90.
subroutine pmat5::sparaframe (real(sp), dimension(3), intent(in) sxp, real(sp), dimension(3), intent(in) syp, real(sp), dimension(3), intent(in) szp, real(sp), dimension(3), intent(out) sxv, real(sp), dimension(3), intent(out) syv, real(sp), dimension(3), intent(in) szv)
Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V. Single precision version.
Parameters:
sxp reference orthonormal P-frame cartesian X-vector.
syp reference orthonormal P-frame cartesian Y-vector.
szp reference orthonormal P-frame cartesian Z-vector.
sxv V-frame cartesian X-vector.
syv V-frame cartesian Y-vector.
szv dependent point zenith, V-frame cartesian Z-vector.
Author:
R. J. Purser
Definition at line 696 of file pmat5.f90.
Author
Generated automatically by Doxygen for grid_tools from the source code.