.TH "pmat2::wrtb" 3 "Tue Mar 9 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::wrtb
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBwrtb\fP (m1, m2, mah1, mah2, a)"
.br
.RI "??? "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file pmat2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat2::wrtb::wrtb (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m1,\-mah1:mah2), intent(in) a)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIm1\fP 
.br
\fIm2\fP 
.br
\fImah1\fP 
.br
\fImah2\fP 
.br
\fIa\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate\fP
.RS 4
1999 
.RE
.PP

.PP
Definition at line 1321 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
