.TH "pmat4::trace" 3 "Fri Mar 26 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::trace
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBtrace_d\fP (b)"
.br
.RI "Calculation for trace_d function\&. "
.ti -1c
.RI "integer(spi) function \fBtrace_i\fP (b)"
.br
.RI "Calculation for trace_i function\&. "
.ti -1c
.RI "real(sp) function \fBtrace_s\fP (b)"
.br
.RI "Calculation for trace_s function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file pmat4\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pmat4::trace::trace_d (real(dp), dimension(:,:), intent(in) b)\fC [private]\fP"

.PP
Calculation for trace_d function\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP real type input value 
.RE
.PP
\fBReturns\fP
.RS 4
s result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 569 of file pmat4\&.f90\&.
.SS "integer(spi) function pmat4::trace::trace_i (integer(spi), dimension(:,:), intent(in) b)\fC [private]\fP"

.PP
Calculation for trace_i function\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP input value 
.RE
.PP
\fBReturns\fP
.RS 4
s result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 581 of file pmat4\&.f90\&.
.SS "real(sp) function pmat4::trace::trace_s (real(sp), dimension(:,:), intent(in) b)\fC [private]\fP"

.PP
Calculation for trace_s function\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP real type input value 
.RE
.PP
\fBReturns\fP
.RS 4
s result 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 557 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
