.TH "pmat2::udlxb" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::udlxb
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBUDLXB\fP (mx, mah1, mah2, my, v, a)"
.br
.RI "Back-substitution step of parallel linear inversion involving Banded matrix and row-X-Vectors\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file pmat2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat2::udlxb::UDLXB (integer(spi), intent(in) mx, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) my, real(sp), dimension(mx,my), intent(inout) v, real(sp), dimension(mx,\-mah1:mah2), intent(in) a)\fC [private]\fP"

.PP
Back-substitution step of parallel linear inversion involving Banded matrix and row-X-Vectors\&. 
.PP
\fBParameters:\fP
.RS 4
\fImx\fP the number of rows assumed for A and length of X-vectors stored in V 
.br
\fImah1\fP the left half-bandwidth of fortran array A 
.br
\fImah2\fP the right half-bandwidth of fortran array A 
.br
\fImy\fP number of parallel X-vectors inverted 
.br
\fIv\fP input as right-hand-side vectors, output as solution vectors 
.br
\fIa\fP encodes the (L)*(D**-1)*(U) factorization of the linear-system matrix, as supplied by subroutine LDUB 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1994 
.RE
.PP

.PP
Definition at line 1099 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
