.TH "pmat4::rottoax" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::rottoax
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBrottoax\fP (orth33, ax3)"
.br
.RI "Assuming that given orth33 is a 3*3 proper rotation matrix, derive an axial 3-vector, ax3, such that orth33 is implied by ax3 when the latter is interpreted as encoding a rotation (as in subroutine axtorot)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file pmat4\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat4::rottoax::rottoax (real(dp), dimension(3,3), intent(in) orth33, real(dp), dimension(3), intent(out) ax3)\fC [private]\fP"

.PP
Assuming that given orth33 is a 3*3 proper rotation matrix, derive an axial 3-vector, ax3, such that orth33 is implied by ax3 when the latter is interpreted as encoding a rotation (as in subroutine axtorot)\&. Note that such ax3 are not unique -- adding any multiple of 2*pi times the parallel unit vector leads to the same orth33\&.
.PP
\fBParameters:\fP
.RS 4
\fIorth33\fP 3*3 proper rotation matrix 
.br
\fIax3\fP axial 3-vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1518 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
