.TH "pmat4::axtoq" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::axtoq
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBaxtoq\fP (v, q)"
.br
.RI "Go from an axial 3-vector to its equivalent quaternion\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 98 of file pmat4\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat4::axtoq::axtoq (real(dp), dimension(3), intent(in) v, real(dp), dimension(0:3), intent(out) q)\fC [private]\fP"

.PP
Go from an axial 3-vector to its equivalent quaternion\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP axial 3-vector 
.br
\fIq\fP quaternion 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1658 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
