.TH "pmat4::hav" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::hav
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBhav_d\fP (t)"
.br
.RI "Haversine function in double precision\&. "
.ti -1c
.RI "real(sp) function \fBhav_s\fP (t)"
.br
.RI "Haversine function in single precision\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file pmat4\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pmat4::hav::hav_d (real(dp), intent(in) t)\fC [private]\fP"

.PP
Haversine function in double precision\&. 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP input argument 
.RE
.PP
\fBReturns:\fP
.RS 4
a result 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 964 of file pmat4\&.f90\&.
.SS "real(sp) function pmat4::hav::hav_s (real(sp), intent(in) t)\fC [private]\fP"

.PP
Haversine function in single precision\&. 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP input argument 
.RE
.PP
\fBReturns:\fP
.RS 4
a result 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 951 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
