.TH "pmat5::frametwist" 3 "Thu Feb 15 2024" "Version 1.12.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat5::frametwist \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBframetwist\fP (xp, yp, zp, xv, yv, zv, twist)"
.br
.RI "\fIGiven a principal cartesian orthonormal frame, {xp,yp,zp} (i\&.e\&., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V\&. \fP"
.ti -1c
.RI "subroutine \fBsframetwist\fP (sxp, syp, szp, sxv, syv, szv, stwist)"
.br
.RI "\fIGiven a principal cartesian orthonormal frame, {xp,yp,zp} (i\&.e\&., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file pmat5\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat5::frametwist::frametwist (real(dp), dimension(3), intent(in)xp, real(dp), dimension(3), intent(in)yp, real(dp), dimension(3), intent(in)zp, real(dp), dimension(3), intent(in)xv, real(dp), dimension(3), intent(in)yv, real(dp), dimension(3), intent(in)zv, real(dp), intent(out)twist)\fC [private]\fP"

.PP
Given a principal cartesian orthonormal frame, {xp,yp,zp} (i\&.e\&., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V\&. Note that, by symmetry, transposing P and V leads to the opposite twist\&. Double precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIxp\fP P-frame cartesian X-vector\&. 
.br
\fIyp\fP P-frame cartesian Y-vector\&. 
.br
\fIzp\fP P-frame cartesian Z-vector\&. 
.br
\fIxv\fP V-frame cartesian X-vector\&. 
.br
\fIyv\fP V-frame cartesian Y-vector\&. 
.br
\fIzv\fP V-frame cartesian Z-vector\&. 
.br
\fItwist\fP relative rotation angle (radians) of frames\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 777 of file pmat5\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat5::frametwist::sframetwist (real(sp), dimension(3), intent(in)sxp, real(sp), dimension(3), intent(in)syp, real(sp), dimension(3), intent(in)szp, real(sp), dimension(3), intent(in)sxv, real(sp), dimension(3), intent(in)syv, real(sp), dimension(3), intent(in)szv, real(sp), intent(out)stwist)\fC [private]\fP"

.PP
Given a principal cartesian orthonormal frame, {xp,yp,zp} (i\&.e\&., at P with Earth-centered cartesians, zp), and another similar frame {xv,yv,zv} at V with Earth-centered cartesians zv, find the relative rotation angle, 'twist' by which the frame at V is rotated in the counterclockwise sense relative to the parallel-transportation of P's frame to V\&. Note that, by symmetry, transposing P and V leads to the opposite twist\&. Single precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIsxp\fP P-frame cartesian X-vector\&. 
.br
\fIsyp\fP P-frame cartesian Y-vector\&. 
.br
\fIszp\fP P-frame cartesian Z-vector\&. 
.br
\fIsxv\fP V-frame cartesian X-vector\&. 
.br
\fIsyv\fP V-frame cartesian Y-vector\&. 
.br
\fIszv\fP V-frame cartesian Z-vector\&. 
.br
\fIstwist\fP relative rotation angle (radians) of frames\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 750 of file pmat5\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
