pmat2
NAME
pmat2 - Routines dealing with the operations of banded matrices.
SYNOPSIS
Data Types
interface avco
interface cad1b
interface cad2b
interface clipb
interface csb1b
interface csb2b
interface dfco
interface dfco2
interface l1ubb
interface l1ueb
interface ldltb
interface ldub
interface linbv
interface ltdlbv
interface u1lbv
interface u1lbx
interface u1lby
interface u1lvb
interface u1lxb
interface u1lyb
interface udlb
interface udlbv
interface udlbx
interface udlby
interface udlvb
interface udlxb
interface udlyb
interface wrtb
Functions/Subroutines
subroutine, public avco (na, nb, za, zb, z0, a, b)
Compute one row of the coefficients for the compact mid-interval interpolation scheme characterized by matrix equation of the form, A.t = B.s (*) Where s is the vector of 'source' values, t the staggered 'target' values.
subroutine, public cad1b (m1, mah1, mah2, mirror2, a)
Incorporate operand symmetry and clip near end-1 of a band matrix operator.
subroutine, public cad2b (m1, m2, mah1, mah2, mirror2, a)
Incorporate symmetry and clip near end-2 of a band matrix.
pure subroutine clib (m1, m2, mah1, mah2, a)
Clip (set to zero) the unused values in a banded matrix representation.
pure subroutine clib_c (m1, m2, mah1, mah2, a)
Clip (set to zero) the unused values in a banded matrix representation.
pure subroutine clib_d (m1, m2, mah1, mah2, a)
Clip (set to zero) the unused values in a banded matrix representation.
subroutine, public csb1b (m1, mah1, mah2, mirror2, a)
Like cad1b, but for antisymmetric operand.
subroutine, public csb2b (m1, m2, mah1, mah2, mirror2, a)
Incorporate operand antisymmetry and clip near end-2 of a band matrix.
subroutine davco (na, nb, za, zb, z0, a, b)
Double precision version of subroutine avco for midpoint interpolation.
subroutine ddfco (na, nb, za, zb, z0, a, b)
Double precision version of dfco for compact differentiation coefficients.
subroutine ddfco2 (na, nb, za, zb, z0, a, b)
Double precision version of DFCO2 to get 2nd-derivative coefficients.
subroutine, public dfco (na, nb, za, zb, z0, a, b)
Compute one row of the coefficients for either the compact differencing or quadrature scheme characterized by matrix equation of the form, A.d = B.c (*) In either case, d is the derivative (or density) of cumulative c.
subroutine, public dfco2 (na, nb, za, zb, z0, a, b)
Compute one row of the coefficients for either the compact second- differencing scheme characterized by matrix equation of the form, A.d = B.c (*) Where d is the second-derivative of c.
subroutine dl1ubb (m, mah1, mah2, mbh1, mbh2, a, b)
Double precision version of L1UBB.
subroutine dl1ueb (m, mah1, mah2, mbh1, mbh2, a, b)
Double precision version of L1UEB.
subroutine dldltb (m, mah1, a)
[L]*[D]*[L^T] factoring of symmetric matrix A (root-free Cholesky).
subroutine dldub (m, mah1, mah2, a)
[L]*[D]*[U] factoring of double precision band-matrix.
subroutine dltdlbv (m, mah1, a, v)
Like udlbv, except assuming a is the ltdl decomposition of a SYMMETRIC banded matrix, with only the non-upper part provided (to avoid redundancy)
subroutine dudlb (m, mah1, mah2, a)
[U]*[D]*[L] factoring of double precision band matrix A [U] is upper triangular with unit main diagonal [D] is a diagonal matrix [L] is lower triangular with unit main diagonal
subroutine dudlbv (m, mah1, mah2, a, v)
Back-substitution step of linear inversion involving banded LDU factored matrix and input vector, v.
subroutine, public l1ubb (m, mah1, mah2, mbh1, mbh2, a, b)
[L]*[D]*[U] factoring of band-matrix [A], modify [B] --> [D**-1]*[B] [L] lower triangular with unit main diagonal [D] diagonal matrix [U] upper triangular with unit main diagonal [B] associated band matrix with same number of rows as [A] lower triangular elements of [A] by [D**-1]*[L]*[D], the upper by [U], replace matrix [B] by [D**-1]*[B].
subroutine, public l1ueb (m, mah1, mah2, mbh1, mbh2, a, b)
Form the [L]*[D]*[U] decomposition of asymmetric band-matrix [A] replace all but row zero of the lower triangular elements of [A] by [D**-1]*[L]*[D], the upper by [U], replace matrix [B] by [D**-1]*[B].
subroutine, public ldltb (m, mah1, a)
[L]*[D]*[L^T] factoring of symmetric band matrix A (root-free Cholesky).
subroutine, public ldub (m, mah1, mah2, a)
[L]*[D]*[U] factoring of single precision band-matrix.
subroutine, public linbv (m, mah1, mah2, a, v)
Solve LINear system with square Banded-matrix and vector V.
subroutine, public ltdlbv (m, mah1, a, v)
Like udlbv, except assuming a is the ldlt decomposition of a SYMMETRIC banded matrix, with only the non-upper part provided (to avoid redundancy)
subroutine tavco (xa, xb, a, b)
Simplified computation of compact midpoint interpolation coefficients.
subroutine tdfco (xa, xb, a, b)
Simplified computation of compact differencing coefficients to get derivatives d from cumulatives c, or vice-versa.
subroutine tdfco2 (xa, xb, a, b)
Simplified computation of compact 2nd-derivative coefficients.
subroutine, public u1lbv (m, mah1, mah2, a, v)
Back-substitution step ((U**-1)*(L**-1)) of linear inversion involving special Banded matrix and right-Vector.
subroutine, public u1lbx (mx, mah1, mah2, my, a, v)
Special back-substitution step of parallel linear inversion involving Banded matrix and X-right-Vectors.
subroutine, public u1lby (my, mah1, mah2, mx, a, v)
Special Back-substitution step of parallel linear inversion involving Banded matrix and Y-right-Vectors.
subroutine, public u1lvb (m, mah1, mah2, v, a)
Special Back-substitution step of linear inversion involving left-Vector and Banded matrix.
subroutine, public u1lxb (mx, mah1, mah2, my, v, a)
Special Back-substitution step of parallel linear inversion involving Banded matrix and X-left-Vectors.
subroutine, public u1lyb (my, mah1, mah2, mx, v, a)
Special Back-substitution step of parallel linear inversion involving special Banded matrix and Y-left-Vectors.
subroutine, public udlb (m, mah1, mah2, a)
[U]*[D]*[L] factoring of single precision band matrix A [U] is upper triangular with unit main diagonal [D] is a diagonal matrix [L] is lower triangular with unit main diagonal
subroutine, public udlbv (m, mah1, mah2, a, v)
Back-substitution step of linear inversion involving banded LDU factored matrix and input vector, v.
subroutine, public udlbx (mx, mah1, mah2, my, a, v)
Back-substitution step of parallel linear inversion involving Banded matrix and X-Vectors.
subroutine, public udlby (my, mah1, mah2, mx, a, v)
Back-substitution step of parallel linear inversion involving Banded matrix and Y-Vectors.
subroutine, public udlvb (m, mah1, mah2, v, a)
Back-substitution step of linear inversion involving row-Vector and Banded matrix.
subroutine, public udlxb (mx, mah1, mah2, my, v, a)
Back-substitution step of parallel linear inversion involving Banded matrix and row-X-Vectors.
subroutine, public udlyb (my, mah1, mah2, mx, v, a)
BACk-substitution step of parallel linear inversion involving Banded matrix and row-Y-Vectors.
subroutine, public wrtb (m1, m2, mah1, mah2, a)
Convenient routine for interactively writing out the real contents of a band matrix.
Variables
real(dp), parameter zero =0
Double precision real zero.
Detailed Description
Routines dealing with the operations of banded matrices.
The three special routines allow the construction of compact or conventional interpolation and differencing stencils to a general order of accuracy. These are:
avco() Averaging, or interpolating;
dfco() Differentiating (once);
dfco2() Differentiating (twice).
Other routines provide the tools for applying compact schemes, and for the construction and application of recursive filters.
Last modified (Purser): January 6th 2005 added nonredundant ldltb and ltdlbv routines for symmetric matrices, and remove obsolescent routines.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994/1999
Function/Subroutine Documentation
subroutine, public pmat2::avco (integer(spi), intent(in) na, integer(spi), intent(in) nb, real(sp), dimension(na), intent(in) za, real(sp), dimension(nb), intent(in) zb, real(sp), intent(in) z0, real(sp), dimension(na), intent(out) a, real(sp), dimension(nb), intent(out) b)
Compute one row of the coefficients for the compact mid-interval interpolation scheme characterized by matrix equation of the form, A.t = B.s (*) Where s is the vector of 'source' values, t the staggered 'target' values.
Parameters:
na number of t-points operated on by this row of the A of (*)
nb number of s-points operated on by this row of the B of (*)
za coordinates of t-points used in this row of (*)
zb coordinates of s-points used in this row of (*)
z0 nominal point of application of this row of (*)
a the NA coefficients A for this scheme
b the NB coefficients B for this scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 100 of file pmat2.f90.
References pietc::u0, and pietc::u1.
subroutine, public pmat2::cad1b (integer(spi), intent(in) m1, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mirror2, real(sp), dimension(0:m1-1,-mah1:mah2), intent(inout) a)
Incorporate operand symmetry and clip near end-1 of a band matrix operator.
Parameters:
m1 Size of implied full matrix
mah1 Left semi-bandwidths (subdiagonals) of A.
mah2 Right semi-bandwidths (superdiagonals) of A.
mirror2 2*location of symmetry axis relative to end-1 operand element.
a Input operator, output as symmetrized and clipped at end-1 Note: although m2 is not used here, it IS used in companion routines cad2b and csb2b; it is retained in the interests of uniformity.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 426 of file pmat2.f90.
subroutine, public pmat2::cad2b (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mirror2, real(sp), dimension(1-m1:0,m1-m2-mah1:m1-m2+mah2), intent(inout) a)
Incorporate symmetry and clip near end-2 of a band matrix.
Parameters:
m1 Number of rows of full matrix A
m2 Number of columns of implied full matrix A
mah1 Left semi-bandwidths (subdiagonals) of A.
mah2 Right semi-bandwidths (superdiagonals) of A.
mirror2 2*location of symmetry axis relative to end-2 operand element.
a Input operator, output as symmetrized and clipped at end-2.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 477 of file pmat2.f90.
pure subroutine pmat2::clib (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m1,-mah1:mah2), intent(inout) a) [private]
Clip (set to zero) the unused values in a banded matrix representation.
Parameters:
m1 number of matrix rows
m2 number of matrix columns
mah1 number of subdiagonals
mah2 number of superdiagonals
a single precision matrix elements, stored compactly as rows
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 370 of file pmat2.f90.
pure subroutine pmat2::clib_c (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, complex(dpc), dimension(m1,-mah1:mah2), intent(inout) a)
Clip (set to zero) the unused values in a banded matrix representation.
Parameters:
m1 number of matrix rows
m2 number of matrix columns
mah1 number of subdiagonals
mah2 number of superdiagonals
a complex matrix elements, stored compactly as rows
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 406 of file pmat2.f90.
References pietc::c0.
pure subroutine pmat2::clib_d (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(dp), dimension(m1,-mah1:mah2), intent(inout) a)
Clip (set to zero) the unused values in a banded matrix representation.
Parameters:
m1 number of matrix rows
m2 number of matrix columns
mah1 number of subdiagonals
mah2 number of superdiagonals
a double precision matrix elements, stored compactly as rows
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 388 of file pmat2.f90.
References pietc::u0.
subroutine, public pmat2::csb1b (integer(spi), intent(in) m1, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mirror2, real(sp), dimension(0:m1-1,-mah1:mah2), intent(inout) a)
Like cad1b, but for antisymmetric operand.
Parameters:
m1 Size of implied full matrix
mah1 Left semi-bandwidths (subdiagonals) of A.
mah2 Right semi-bandwidths (superdiagonals) of A.
mirror2 2*location of symmetry axis relative to end-1 operand element.
a Input operator, output as clipped antisymmetric at end-1.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 451 of file pmat2.f90.
subroutine, public pmat2::csb2b (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mirror2, real(sp), dimension(1-m1:0,m1-m2-mah1:m1-m2+mah2), intent(inout) a)
Incorporate operand antisymmetry and clip near end-2 of a band matrix.
Parameters:
m1 Number of rows of matrix A
m2 Number of columns of matrix A
mah1 Left semi-bandwidths (subdiagonals) of A.
mah2 Right semi-bandwidths (superdiagonals) of A.
mirror2 2*location of symmetry axis relative to end-2 operand element.
a Input operator, output as antisymmetrized and clipped at end-2.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 504 of file pmat2.f90.
subroutine pmat2::davco (integer(spi), intent(in) na, integer(spi), intent(in) nb, real(dp), dimension(na), intent(in) za, real(dp), dimension(nb), intent(in) zb, real(dp), intent(in) z0, real(dp), dimension(na), intent(out) a, real(dp), dimension(nb), intent(out) b)
Double precision version of subroutine avco for midpoint interpolation.
Parameters:
na number of target points involved in formula
nb number of source points involved in formula
za coordinates of target points
zb coordinates of source points
z0 nominal point of application of compact interpolation formula
a the coefficients A for this scheme
b the coefficients B for this scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 134 of file pmat2.f90.
References pietc::u0, and pietc::u1.
Referenced by tavco().
subroutine pmat2::ddfco (integer(spi), intent(in) na, integer(spi), intent(in) nb, real(dp), dimension(na), intent(in) za, real(dp), dimension(nb), intent(in) zb, real(dp), intent(in) z0, real(dp), dimension(na), intent(out) a, real(dp), dimension(nb), intent(out) b)
Double precision version of dfco for compact differentiation coefficients.
Parameters:
na number of A coefficients multiplying derivatives
nb number of B coefficients multiplying cumulatives
za coordinates of the density (d) points
zb coordinates of the cumulative (c) points
z0 nominal point of application of the compact formula
a the A-coefficients for this scheme
b the B-coefficients for this scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 225 of file pmat2.f90.
References pietc::u0, and pietc::u1.
Referenced by tdfco().
subroutine pmat2::ddfco2 (integer(spi), intent(in) na, integer(spi), intent(in) nb, real(dp), dimension(na), intent(in) za, real(dp), dimension(nb), intent(in) zb, real(dp), intent(in) z0, real(dp), dimension(na), intent(out) a, real(dp), dimension(nb), intent(out) b)
Double precision version of DFCO2 to get 2nd-derivative coefficients.
Parameters:
na number of 2nd-derivative (d) points in compact formula
nb number of source points (c)
za coordinates of 2nd-derivative points
zb coordinates of source points
z0 nominal coordinate of application
a coefficients A for derivative points
b coefficients B for source points
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 318 of file pmat2.f90.
References pietc::u0, and pietc::u1.
Referenced by tdfco2().
subroutine, public pmat2::dfco (integer(spi), intent(in) na, integer(spi), intent(in) nb, real(sp), dimension(na), intent(in) za, real(sp), dimension(nb), intent(in) zb, real(sp), intent(in) z0, real(sp), dimension(na), intent(out) a, real(sp), dimension(nb), intent(out) b)
Compute one row of the coefficients for either the compact differencing or quadrature scheme characterized by matrix equation of the form, A.d = B.c (*) In either case, d is the derivative (or density) of cumulative c.
Parameters:
na number of d-points operated on by this row of the A of (*)
nb number of c-points operated on by this row of the B of (*)
za coordinates of d-points used in this row of (*)
zb coordinates of c-points used in this row of (*)
z0 nominal point of application of this row of (*)
A the A-coefficients for this scheme
B the B-coefficients for this scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 190 of file pmat2.f90.
subroutine, public pmat2::dfco2 (integer(spi), intent(in) na, integer(spi), intent(in) nb, real(sp), dimension(na), intent(in) za, real(sp), dimension(nb), intent(in) zb, real(sp), intent(in) z0, real(sp), dimension(na), intent(out) a, real(sp), dimension(nb), intent(out) b)
Compute one row of the coefficients for either the compact second- differencing scheme characterized by matrix equation of the form, A.d = B.c (*) Where d is the second-derivative of c.
Parameters:
na number of d-points operated on by this row of the A of (*)
nb number of c-points operated on by this row of the B of (*)
za coordinates of d-points used in this row of (*)
zb coordinates of c-points used in this row of (*)
z0 nominal point of application of this row of (*)
a the NA coefficients A for this scheme
b the NB coefficients B for this scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 283 of file pmat2.f90.
subroutine pmat2::dl1ubb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mbh1, integer(spi), intent(in) mbh2, real(dp), dimension(m,-mah1:mah2), intent(inout) a, real(dp), dimension(m,-mbh1:mbh2), intent(inout) b)
Double precision version of L1UBB.
Parameters:
m Number of rows of A and B
mah1 left half-width of fortran array A
mah2 right half-width of fortran array A
mbh1 left half-width of fortran array B
mbh2 left half-width of fortran array B
a Input double precision band matrix A; output factors encoded as [D**-1 * L * D]+[U-I]
b Input double precision band matrix B; output [D**-1 B]
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 771 of file pmat2.f90.
References pietc::u0, and pietc::u1.
subroutine pmat2::dl1ueb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mbh1, integer(spi), intent(in) mbh2, real(dp), dimension(0:,-mah1:), intent(inout) a, real(dp), dimension(:,-mbh1:), intent(inout) b)
Double precision version of L1UEB.
Parameters:
m number of rows of band matrices A and B
mah1 number of subdiagonals of A
mah2 number of superdiagonals of A
mbh1 number of subdiagonals of B
mbh2 number of superdiagonals of B
a Input matrix A; output encoded L, D, U, factors
b Input matrix B; output D**-1 * B
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 855 of file pmat2.f90.
References pietc::u0, and pietc::u1.
subroutine pmat2::dldltb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, real(dp), dimension(m,-mah1:0), intent(inout) a)
[L]*[D]*[L^T] factoring of symmetric matrix A (root-free Cholesky). [L] is lower triangular with unit main diagonal [D] is a diagonal matrix
Parameters:
m size of symmetric matrix A
mah1 semi-bandwidth of matrix A
a input lower (left) part of symmetric A; output its factors encoded as [L-I]+[D**-1]
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 645 of file pmat2.f90.
References pietc::u0, and pietc::u1.
subroutine pmat2::dldub (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(dp), dimension(m,-mah1:mah2), intent(inout) a)
[L]*[D]*[U] factoring of double precision band-matrix. [L] is lower triangular with unit main diagonal [D] is a diagonal matrix [U] is upper triangular with unit main diagonal
Parameters:
m The number of rows of array A
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
a input as the asymmetric band matrix, [A]. On output, it contains the factors in the encoding, [L-I]+[D**-1]+[U-I], I=identity.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 571 of file pmat2.f90.
References pietc::u0, and pietc::u1.
Referenced by dudlb().
subroutine pmat2::dltdlbv (integer(spi), intent(in) m, integer(spi), intent(in) mah1, real(dp), dimension(m,-mah1:0), intent(in) a, real(dp), dimension(m), intent(inout) v) [private]
Like udlbv, except assuming a is the ltdl decomposition of a SYMMETRIC banded matrix, with only the non-upper part provided (to avoid redundancy)
Parameters:
m the number of rows assumed for A and for V
mah1 the left half-bandwidth of fortran array A
a encodes the (L)*(D**-1)*(U) factorization of the linear-system matrix, as supplied by subroutine LDUB
v input as right-hand-side vector, output as solution vector
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 980 of file pmat2.f90.
subroutine pmat2::dudlb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(dp), dimension(m,-mah1:mah2), intent(inout) a) [private]
[U]*[D]*[L] factoring of double precision band matrix A [U] is upper triangular with unit main diagonal [D] is a diagonal matrix [L] is lower triangular with unit main diagonal
Parameters:
m number of rows of A
mah1 number of subdiagonals of A
mah2 number of superdiagonals of A
a Input double precision band matrix A; output its factors encoded as [U-I]+[D**-1]+[L-I]
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 704 of file pmat2.f90.
References dldub().
subroutine pmat2::dudlbv (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(dp), dimension(m,-mah1:mah2), intent(in) a, real(dp), dimension(m), intent(inout) v) [private]
Back-substitution step of linear inversion involving banded LDU factored matrix and input vector, v. Output vector is [U**-1]*[D**-1]*[L**-1]*v
Parameters:
m the number of rows assumed for A and for V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
a encodes the L*D*U factorization of the linear-system matrix, as supplied by subroutine LDUB, in double precision
v input as right-hand-side vector, output as solution vector
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 921 of file pmat2.f90.
subroutine, public pmat2::l1ubb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mbh1, integer(spi), intent(in) mbh2, real(sp), dimension(m,-mah1:mah2), intent(inout) a, real(sp), dimension(m,-mbh1:mbh2), intent(inout) b)
[L]*[D]*[U] factoring of band-matrix [A], modify [B] --> [D**-1]*[B] [L] lower triangular with unit main diagonal [D] diagonal matrix [U] upper triangular with unit main diagonal [B] associated band matrix with same number of rows as [A] lower triangular elements of [A] by [D**-1]*[L]*[D], the upper by [U], replace matrix [B] by [D**-1]*[B].
Parameters:
m Number of rows of A and B
mah1 number of subdiagonals of A
mah2 number of superdiagonals of A
mbh1 number of subdiagonals of B
mbh2 number of superdiagonals of B
a input as band matrix, output as lower and upper triangulars with 1s implicitly assumed to lie on the main diagonal. The product of these triangular matrices is [D**-1]*[A], where [D] is a diagonal matrix.
b Input single precision band matrix B; output [D**-1 B]
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1996
Definition at line 733 of file pmat2.f90.
subroutine, public pmat2::l1ueb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mbh1, integer(spi), intent(in) mbh2, real(sp), dimension(0:m,-mah1:mah2), intent(inout) a, real(sp), dimension(m,-mbh1:mbh2), intent(inout) b)
Form the [L]*[D]*[U] decomposition of asymmetric band-matrix [A] replace all but row zero of the lower triangular elements of [A] by [D**-1]*[L]*[D], the upper by [U], replace matrix [B] by [D**-1]*[B]. This is a special adaptation of L1UBB used to process quadrature weights for QEDBV etc in which the initial quadrature value is provided as input instead of being implicitly assumed zero (which is the case for QZDBV etc).
Parameters:
m number of rows of B, one less than the rows of A (which has 'row 0')
mah1 left half-width of fortran array A
mah2 right half-width of fortran array A
mbh1 left half-width of fortran array B
mbh2 right half-width of fortran array B
a input as band matrix, output as lower and upper triangulars with 1s implicitly assumed to lie on the main diagonal. The product of these triangular matrices is [D**-1]*[A], where [D] is a diagonal matrix.
b in as band matrix, out as same but premultiplied by diagonal [D**-1]
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1998
Definition at line 818 of file pmat2.f90.
subroutine, public pmat2::ldltb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, real(sp), dimension(m,-mah1:0), intent(inout) a)
[L]*[D]*[L^T] factoring of symmetric band matrix A (root-free Cholesky). [L] is lower triangular with unit main diagonal [D] is a diagonal matrix.
Parameters:
m size of symmetric matrix A
mah1 semi-bandwidth of matrix A
a input lower (left) part of symmetric A; output its factors encoded as [L-I]+[D**-1]
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 609 of file pmat2.f90.
subroutine, public pmat2::ldub (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m,-mah1:mah2), intent(inout) a)
[L]*[D]*[U] factoring of single precision band-matrix. [L] is lower triangular with unit main diagonal [D] is a diagonal matrix [U] is upper triangular with unit main diagonal
Parameters:
m The number of rows of array A
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
a input as the asymmetric band matrix, [A]. On output, it contains the factors in the encoding, [L-I]+[D**-1]+[U-I], I=identity.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 532 of file pmat2.f90.
subroutine, public pmat2::linbv (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m,-mah1:mah2), intent(inout) a, real(sp), dimension(m), intent(inout) v)
Solve LINear system with square Banded-matrix and vector V.
Parameters:
m order of matrix A
mah1 left half-bandwidth of A
mah2 right half-bandwidth of A
a system matrix on input, its [L]*[D**-1]*[U] factorization on exit
v vector of right-hand-sides on input, solution vector on exit
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 1323 of file pmat2.f90.
subroutine, public pmat2::ltdlbv (integer(spi), intent(in) m, integer(spi), intent(in) mah1, real(sp), dimension(m,-mah1:0), intent(in) a, real(sp), dimension(m), intent(inout) v)
Like udlbv, except assuming a is the ldlt decomposition of a SYMMETRIC banded matrix, with only the non-upper part provided (to avoid redundancy)
Parameters:
m the number of rows assumed for A and for V
mah1 the left half-bandwidth of fortran array A
a encodes the L*D*L^T factorization of the linear-system matrix, as supplied by subroutine LDLTB
v input as right-hand-side vector, output as solution vector
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 950 of file pmat2.f90.
subroutine pmat2::tavco (real(dp), dimension(:), intent(in) xa, real(dp), dimension(:), intent(in) xb, real(dp), dimension(:), intent(out) a, real(dp), dimension(:), intent(out) b)
Simplified computation of compact midpoint interpolation coefficients.
Parameters:
xa coordinates of target points relative to point of application
xb coordinates of source points relative to point of application
a the coefficients A for this scheme
b the coefficients B for this scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 165 of file pmat2.f90.
References davco(), and zero.
subroutine pmat2::tdfco (real(dp), dimension(:), intent(in) xa, real(dp), dimension(:), intent(in) xb, real(dp), dimension(:), intent(out) a, real(dp), dimension(:), intent(out) b)
Simplified computation of compact differencing coefficients to get derivatives d from cumulatives c, or vice-versa.
Parameters:
xa coordinates, relative to point of application, of d values
xb coordinates, relatuve to point of application, of c values
a the coefficients, A, for this scheme
b the coefficients, B, for this scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 258 of file pmat2.f90.
References ddfco(), and zero.
subroutine pmat2::tdfco2 (real(dp), dimension(:), intent(in) xa, real(dp), dimension(:), intent(in) xb, real(dp), dimension(:), intent(out) a, real(dp), dimension(:), intent(out) b)
Simplified computation of compact 2nd-derivative coefficients.
Parameters:
xa Relative coordinates of derivatives
xb Relative coordinates of source points
a coefficients A for the derivatives in compact scheme
b coefficients B for source values in the compact scheme
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 350 of file pmat2.f90.
References ddfco2(), and zero.
subroutine, public pmat2::u1lbv (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m,-mah1:mah2), intent(in) a, real(sp), dimension(m), intent(inout) v)
Back-substitution step ((U**-1)*(L**-1)) of linear inversion involving special Banded matrix and right-Vector.
Parameters:
m the number of rows assumed for A and for V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
a encodes the [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB
v input as right-hand-side vector, output as solution vector
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1996
Definition at line 1155 of file pmat2.f90.
subroutine, public pmat2::u1lbx (integer(spi), intent(in) mx, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) my, real(sp), dimension(mx,-mah1:mah2), intent(in) a, real(sp), dimension(mx,my), intent(inout) v)
Special back-substitution step of parallel linear inversion involving Banded matrix and X-right-Vectors.
Parameters:
mx the number of rows assumed for A and length of X-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
my number of parallel X-vectors inverted
a encodes the [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB
v input as right-hand-side vectors, output as solution vectors
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1996
Definition at line 1186 of file pmat2.f90.
subroutine, public pmat2::u1lby (integer(spi), intent(in) my, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mx, real(sp), dimension(my,-mah1:mah2), intent(in) a, real(sp), dimension(mx,my), intent(inout) v)
Special Back-substitution step of parallel linear inversion involving Banded matrix and Y-right-Vectors.
Parameters:
my the number of rows assumed for A and length of Y-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
mx number of parallel Y-vectors inverted
a encodes the [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB
v input as right-hand-side vectors, output as solution vectors
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1996
Definition at line 1214 of file pmat2.f90.
subroutine, public pmat2::u1lvb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m), intent(inout) v, real(sp), dimension(m,-mah1:mah2), intent(in) a)
Special Back-substitution step of linear inversion involving left-Vector and Banded matrix.
Parameters:
m the number of rows assumed for A and columns for V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
v input as right-hand-side row-vector, output as solution vector
a encodes the special [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1996
Definition at line 1240 of file pmat2.f90.
subroutine, public pmat2::u1lxb (integer(spi), intent(in) mx, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) my, real(sp), dimension(mx,my), intent(inout) v, real(sp), dimension(mx,-mah1:mah2), intent(in) a)
Special Back-substitution step of parallel linear inversion involving Banded matrix and X-left-Vectors.
Parameters:
mx the number of rows assumed for A and length of X-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
my number of parallel X-vectors inverted
v input as right-hand-side vectors, output as solution vectors
a encodes the special [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1996
Definition at line 1271 of file pmat2.f90.
subroutine, public pmat2::u1lyb (integer(spi), intent(in) my, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mx, real(sp), dimension(mx,my), intent(inout) v, real(sp), dimension(my,-mah1:mah2), intent(in) a)
Special Back-substitution step of parallel linear inversion involving special Banded matrix and Y-left-Vectors.
Parameters:
my the number of rows assumed for A and length of Y-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
mx number of parallel Y-vectors inverted
v input as right-hand-side vectors, output as solution vectors
a encodes the [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1996
Definition at line 1299 of file pmat2.f90.
subroutine, public pmat2::udlb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m,-mah1:mah2), intent(inout) a)
[U]*[D]*[L] factoring of single precision band matrix A [U] is upper triangular with unit main diagonal [D] is a diagonal matrix [L] is lower triangular with unit main diagonal
Parameters:
m number of rows of A
mah1 number of subdiagonals of A
mah2 number of superdiagonals of A
a Input single precision band matrix A; output its factors encoded as [U-I]+[D**-1]+[L-I]
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 683 of file pmat2.f90.
subroutine, public pmat2::udlbv (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m,-mah1:mah2), intent(in) a, real(sp), dimension(m), intent(inout) v)
Back-substitution step of linear inversion involving banded LDU factored matrix and input vector, v. Output vector is [U**-1]*[D**-1]*[L**-1]*v
Parameters:
m the number of rows assumed for A and for V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
a encodes the L*D*U factorization of the linear-system matrix, as supplied by subroutine LDUB, in single precision
v input as right-hand-side vector, output as solution vector
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 892 of file pmat2.f90.
subroutine, public pmat2::udlbx (integer(spi), intent(in) mx, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) my, real(sp), dimension(mx,-mah1:mah2), intent(in) a, real(sp), dimension(mx,my), intent(inout) v)
Back-substitution step of parallel linear inversion involving Banded matrix and X-Vectors.
Parameters:
mx the number of rows assumed for A and length of X-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
my number of parallel X-vectors inverted
a encodes the (L)*(D**-1)*(U) factorization of the linear-system matrix, as supplied by subroutine LDUB or, if N=NA, by LDUB
v input as right-hand-side vectors, output as solution vectors
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 1011 of file pmat2.f90.
subroutine, public pmat2::udlby (integer(spi), intent(in) my, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mx, real(sp), dimension(my,-mah1:mah2), intent(in) a, real(sp), dimension(mx,my), intent(inout) v)
Back-substitution step of parallel linear inversion involving Banded matrix and Y-Vectors.
Parameters:
my the number of rows assumed for A and length of Y-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
mx number of parallel Y-vectors inverted
a encodes the (L)*(D**-1)*(U) factorization of the linear-system matrix, as supplied by subroutine LDUB or, if N=NA, by LDUB
v input as right-hand-side vectors, output as solution vectors
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 1040 of file pmat2.f90.
subroutine, public pmat2::udlvb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m), intent(inout) v, real(sp), dimension(m,-mah1:mah2), intent(in) a)
Back-substitution step of linear inversion involving row-Vector and Banded matrix.
Parameters:
m the number of rows assumed for A and columns for V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
v input as right-hand-side row-vector, output as solution vector
a encodes the (L)*(D**-1)*(U) factorization of the linear-system matrix, as supplied by subroutine LDUB
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 1067 of file pmat2.f90.
subroutine, public pmat2::udlxb (integer(spi), intent(in) mx, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) my, real(sp), dimension(mx,my), intent(inout) v, real(sp), dimension(mx,-mah1:mah2), intent(in) a)
Back-substitution step of parallel linear inversion involving Banded matrix and row-X-Vectors.
Parameters:
mx the number of rows assumed for A and length of X-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
my number of parallel X-vectors inverted
v input as right-hand-side vectors, output as solution vectors
a encodes the (L)*(D**-1)*(U) factorization of the linear-system matrix, as supplied by subroutine LDUB
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 1099 of file pmat2.f90.
subroutine, public pmat2::udlyb (integer(spi), intent(in) my, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mx, real(sp), dimension(mx,my), intent(inout) v, real(sp), dimension(my,-mah1:mah2), intent(in) a)
BACk-substitution step of parallel linear inversion involving Banded matrix and row-Y-Vectors.
Parameters:
my the number of rows assumed for A and length of Y-vectors stored in V
mah1 the left half-bandwidth of fortran array A
mah2 the right half-bandwidth of fortran array A
mx number of parallel Y-vectors inverted
v input as right-hand-side vectors, output as solution vectors
a encodes the (L)*(D**-1)*(U) factorization of the linear-system matrix, as supplied by subroutine LDUB
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1994
Definition at line 1128 of file pmat2.f90.
subroutine, public pmat2::wrtb (integer(spi), intent(in) m1, integer(spi), intent(in) m2, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m1,-mah1:mah2), intent(in) a)
Convenient routine for interactively writing out the real contents of a band matrix.
Parameters:
m1 number of rows of full matrix
m2 number of columns of full matrix
mah1 number of sub-diagonals
mah2 number of super-diagonals
a contents of single precision real band matrix.
Author:
R. J. Purser, Tsukasa Fujita (JMA)
Date:
1999
Definition at line 1341 of file pmat2.f90.
Variable Documentation
real(dp), parameter pmat2::zero =0 [private]
Double precision real zero.
Definition at line 54 of file pmat2.f90.
Referenced by tavco(), tdfco(), and tdfco2().
Author
Generated automatically by Doxygen for grid_tools from the source code.