.TH "pmat2::u1lyb" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::u1lyb
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBu1lyb\fP (my, mah1, mah2, mx, v, a)"
.br
.RI "Special Back-substitution step of parallel linear inversion involving special Banded matrix and Y-left-Vectors\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file pmat2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat2::u1lyb::u1lyb (integer(spi), intent(in) my, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, integer(spi), intent(in) mx, real(sp), dimension(mx,my), intent(inout) v, real(sp), dimension(my,\-mah1:mah2), intent(in) a)\fC [private]\fP"

.PP
Special Back-substitution step of parallel linear inversion involving special Banded matrix and Y-left-Vectors\&. 
.PP
\fBParameters:\fP
.RS 4
\fImy\fP the number of rows assumed for A and length of Y-vectors stored in V 
.br
\fImah1\fP the left half-bandwidth of fortran array A 
.br
\fImah2\fP the right half-bandwidth of fortran array A 
.br
\fImx\fP number of parallel Y-vectors inverted 
.br
\fIv\fP input as right-hand-side vectors, output as solution vectors 
.br
\fIa\fP encodes the [L]*[U] factorization of the linear-system matrix, as supplied by subroutine L1UBB 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1996 
.RE
.PP

.PP
Definition at line 1299 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
