.TH "pmat::swpvv" 3 "Thu Mar 25 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat::swpvv
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBcswpvv\fP (d, e)"
.br
.RI "??? "
.ti -1c
.RI "subroutine \fBdswpvv\fP (d, e)"
.br
.RI "??? "
.ti -1c
.RI "subroutine \fBsswpvv\fP (d, e)"
.br
.RI "??? "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file pmat\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat::swpvv::cswpvv (complex(dpc), dimension(:), intent(inout) d, complex(dpc), dimension(:), intent(inout) e)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fId\fP vector 
.br
\fIe\fP vector 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 71 of file pmat\&.f90\&.
.SS "subroutine pmat::swpvv::dswpvv (real(dp), dimension(:), intent(inout) d, real(dp), dimension(:), intent(inout) e)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fId\fP vector 
.br
\fIe\fP vector 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 60 of file pmat\&.f90\&.
.SS "subroutine pmat::swpvv::sswpvv (real(sp), dimension(:), intent(inout) d, real(sp), dimension(:), intent(inout) e)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fId\fP vector 
.br
\fIe\fP vector 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 49 of file pmat\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
