.TH "pmat2::ldltb" 3 "Tue Mar 9 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::ldltb
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBldltb\fP (m, mah1, a)"
.br
.RI "??? "
.ti -1c
.RI "subroutine \fBdldltb\fP (m, mah1, a)"
.br
.RI "??? "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file pmat2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat2::ldltb::ldltb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, real(sp), dimension(m,\-mah1:0), intent(inout) a)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIm\fP ??? 
.br
\fImah1\fP ??? 
.br
\fIa\fP ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate\fP
.RS 4
1999 
.RE
.PP

.PP
Definition at line 603 of file pmat2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat2::ldltb::dldltb (integer(spi), intent(in) m, integer(spi), intent(in) mah1, real(dp), dimension(m,\-mah1:0), intent(inout) a)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIm\fP ??? 
.br
\fImah1\fP ??? 
.br
\fIa\fP ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate\fP
.RS 4
1999 
.RE
.PP

.PP
Definition at line 637 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
