.TH "pmat4::mulqq" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::mulqq
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function, dimension(0:3) \fBmulqq\fP (a, b)"
.br
.RI "Multiply quaternions, a*b, assuming operation performed from right to left\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file pmat4\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "real(dp) function, dimension(0:3) pmat4::mulqq::mulqq (real(dp), dimension(0:3), intent(in) a, real(dp), dimension(0:3), intent(in) b)\fC [private]\fP"

.PP
Multiply quaternions, a*b, assuming operation performed from right to left\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP input quaternion 
.br
\fIb\fP input quaternion 
.RE
.PP
\fBReturns:\fP
.RS 4
c result quaternion a*b 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1709 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
