.TH "pmat::l1lm" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat::l1lm
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBdL1Lm\fP"
.br
.ti -1c
.RI "\fBdL1Lmf\fP"
.br
.ti -1c
.RI "\fBsL1Lm\fP"
.br
.ti -1c
.RI "\fBsL1Lmf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file pmat\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
