.TH "pmat::ldlm" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat::ldlm
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBdLdLm\fP"
.br
.ti -1c
.RI "\fBdLdLmf\fP"
.br
.ti -1c
.RI "\fBsLdLm\fP"
.br
.ti -1c
.RI "\fBsLdLmf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file pmat\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
