.TH "pmat2::linbv" 3 "Thu Jun 20 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::linbv
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBlinbv\fP (m, mah1, mah2, a, v)"
.br
.RI "Solve LINear system with square Banded-matrix and vector V\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file pmat2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat2::linbv::linbv (integer(spi), intent(in) m, integer(spi), intent(in) mah1, integer(spi), intent(in) mah2, real(sp), dimension(m,\-mah1:mah2), intent(inout) a, real(sp), dimension(m), intent(inout) v)\fC [private]\fP"

.PP
Solve LINear system with square Banded-matrix and vector V\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP order of matrix A 
.br
\fImah1\fP left half-bandwidth of A 
.br
\fImah2\fP right half-bandwidth of A 
.br
\fIa\fP system matrix on input, its [L]*[D**-1]*[U] factorization on exit 
.br
\fIv\fP vector of right-hand-sides on input, solution vector on exit 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1994 
.RE
.PP

.PP
Definition at line 1323 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
