.TH "pmat5::paraframe" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat5::paraframe
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBparaframe\fP (xp, yp, zp, xv, yv, zv)"
.br
.RI "Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V\&. "
.ti -1c
.RI "subroutine \fBsparaframe\fP (sxp, syp, szp, sxv, syv, szv)"
.br
.RI "Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file pmat5\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat5::paraframe::paraframe (real(dp), dimension(3), intent(in) xp, real(dp), dimension(3), intent(in) yp, real(dp), dimension(3), intent(in) zp, real(dp), dimension(3), intent(out) xv, real(dp), dimension(3), intent(out) yv, real(dp), dimension(3), intent(in) zv)\fC [private]\fP"

.PP
Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V\&. Double precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIxp\fP reference orthonormal P-frame cartesian X-vector\&. 
.br
\fIyp\fP reference orthonormal P-frame cartesian Y-vector\&. 
.br
\fIzp\fP reference orthonormal P-frame cartesian Z-vector\&. 
.br
\fIxv\fP V-frame cartesian X-vector\&. 
.br
\fIyv\fP V-frame cartesian Y-vector\&. 
.br
\fIzv\fP dependent point zenith, V-frame cartesian Z-vector\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 719 of file pmat5\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat5::paraframe::sparaframe (real(sp), dimension(3), intent(in) sxp, real(sp), dimension(3), intent(in) syp, real(sp), dimension(3), intent(in) szp, real(sp), dimension(3), intent(out) sxv, real(sp), dimension(3), intent(out) syv, real(sp), dimension(3), intent(in) szv)\fC [private]\fP"

.PP
Take a principal reference orthonormal frame, {xp,yp,zp} and a dependent point defined by unit vector, zv, and complete the V-frame cartesian components, {xv,yv}, that are the result of parallel-transport of {xp,yp} along the geodesic between P and V\&. Single precision version\&.
.PP
\fBParameters:\fP
.RS 4
\fIsxp\fP reference orthonormal P-frame cartesian X-vector\&. 
.br
\fIsyp\fP reference orthonormal P-frame cartesian Y-vector\&. 
.br
\fIszp\fP reference orthonormal P-frame cartesian Z-vector\&. 
.br
\fIsxv\fP V-frame cartesian X-vector\&. 
.br
\fIsyv\fP V-frame cartesian Y-vector\&. 
.br
\fIszv\fP dependent point zenith, V-frame cartesian Z-vector\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 696 of file pmat5\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
