.TH "pmat2::dfco" 3 "Thu Feb 15 2024" "Version 1.12.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat2::dfco \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBdfco\fP (na, nb, za, zb, z0, a, b)"
.br
.RI "\fICompute one row of the coefficients for either the compact differencing or quadrature scheme characterized by matrix equation of the form, A\&.d = B\&.c (*) In either case, d is the derivative (or density) of cumulative c\&. \fP"
.ti -1c
.RI "subroutine \fBddfco\fP (na, nb, za, zb, z0, a, b)"
.br
.RI "\fIDouble precision version of dfco for compact differentiation coefficients\&. \fP"
.ti -1c
.RI "subroutine \fBtdfco\fP (xa, xb, a, b)"
.br
.RI "\fISimplified computation of compact differencing coefficients to get derivatives d from cumulatives c, or vice-versa\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file pmat2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat2::dfco::dfco (integer(spi), intent(in)na, integer(spi), intent(in)nb, real(sp), dimension(na), intent(in)za, real(sp), dimension(nb), intent(in)zb, real(sp), intent(in)z0, real(sp), dimension(na), intent(out)a, real(sp), dimension(nb), intent(out)b)\fC [private]\fP"

.PP
Compute one row of the coefficients for either the compact differencing or quadrature scheme characterized by matrix equation of the form, A\&.d = B\&.c (*) In either case, d is the derivative (or density) of cumulative c\&. 
.PP
\fBParameters:\fP
.RS 4
\fIna\fP number of d-points operated on by this row of the A of (*) 
.br
\fInb\fP number of c-points operated on by this row of the B of (*) 
.br
\fIza\fP coordinates of d-points used in this row of (*) 
.br
\fIzb\fP coordinates of c-points used in this row of (*) 
.br
\fIz0\fP nominal point of application of this row of (*) 
.br
\fIA\fP the A-coefficients for this scheme 
.br
\fIB\fP the B-coefficients for this scheme 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1999 
.RE
.PP

.PP
Definition at line 189 of file pmat2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pmat2::dfco::ddfco (integer(spi), intent(in)na, integer(spi), intent(in)nb, real(dp), dimension(na), intent(in)za, real(dp), dimension(nb), intent(in)zb, real(dp), intent(in)z0, real(dp), dimension(na), intent(out)a, real(dp), dimension(nb), intent(out)b)\fC [private]\fP"

.PP
Double precision version of dfco for compact differentiation coefficients\&. 
.PP
\fBParameters:\fP
.RS 4
\fIna\fP number of A coefficients multiplying derivatives 
.br
\fInb\fP number of B coefficients multiplying cumulatives 
.br
\fIza\fP coordinates of the density (d) points 
.br
\fIzb\fP coordinates of the cumulative (c) points 
.br
\fIz0\fP nominal point of application of the compact formula 
.br
\fIa\fP the A-coefficients for this scheme 
.br
\fIb\fP the B-coefficients for this scheme 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1999 
.RE
.PP

.PP
Definition at line 224 of file pmat2\&.f90\&.
.PP
Referenced by pmat2::tdfco()\&.
.SS "subroutine pmat2::dfco::tdfco (real(dp), dimension(:), intent(in)xa, real(dp), dimension(:), intent(in)xb, real(dp), dimension(:), intent(out)a, real(dp), dimension(:), intent(out)b)\fC [private]\fP"

.PP
Simplified computation of compact differencing coefficients to get derivatives d from cumulatives c, or vice-versa\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxa\fP coordinates, relative to point of application, of d values 
.br
\fIxb\fP coordinates, relatuve to point of application, of c values 
.br
\fIa\fP the coefficients, A, for this scheme 
.br
\fIb\fP the coefficients, B, for this scheme 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1999 
.RE
.PP

.PP
Definition at line 257 of file pmat2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
