.TH "pmat4::zntay" 3 "Fri Mar 26 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::zntay
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBzntay\fP (n, z, zn)"
.br
.RI "??? "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 104 of file pmat4\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat4::zntay::zntay (integer(spi), intent(in) n, real(dp), intent(in) z, real(dp), intent(out) zn)\fC [private]\fP"

.PP
??? 
.PP
\fBParameters\fP
.RS 4
\fIn\fP ??? 
.br
\fIz\fP ??? 
.br
\fIzn\fP ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1873 of file pmat4\&.f90\&.
.PP
References pietc::u2\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
