.TH "psym2::sqrtsym2" 3 "Mon Oct 23 2023" "Version 1.11.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psym2::sqrtsym2
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBsqrtsym2\fP (em, z)"
.br
.RI "Get the sqrt of a symmetric positive-definite 2*2 matrix\&. "
.ti -1c
.RI "subroutine \fBsqrtsym2d\fP (x, z, zd)"
.br
.RI "General routine to evaluate z=sqrt(x), and the symmetric derivative, zd = dz/dx, where x is a symmetric 2*2 positive-definite matrix\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file psym2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine psym2::sqrtsym2::sqrtsym2 (real(dp), dimension(2,2), intent(in) em, real(dp), dimension(2,2), intent(out) z)\fC [private]\fP"

.PP
Get the sqrt of a symmetric positive-definite 2*2 matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fIem\fP 2*2 symmetric matrix 
.br
\fIz\fP sqrt of a symmetric positive-definite 2*2 matrix 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 150 of file psym2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine psym2::sqrtsym2::sqrtsym2d (real(dp), dimension(2,2), intent(in) x, real(dp), dimension(2,2), intent(out) z, real(dp), dimension(2,2,2,2), intent(out) zd)\fC [private]\fP"

.PP
General routine to evaluate z=sqrt(x), and the symmetric derivative, zd = dz/dx, where x is a symmetric 2*2 positive-definite matrix\&. If the eigenvalues are very close together, extract their geometric mean for 'preconditioning' a scaled version, px, of x, whose sqrt, and hence its derivative, can be easily obtained by the series expansion method\&. Otherwise, use the eigen-method (which entails dividing by the difference in the eignevalues to get zd, and which therefore fails when the eigenvalues become too similar)\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP symmetric 2*2 positive-definite matrix 
.br
\fIz\fP sqrt(x) result 
.br
\fIzd\fP symmetric derivative 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 177 of file psym2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
