.TH "psym2::expsym2" 3 "Fri Mar 26 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psym2::expsym2
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBexpsym2\fP (em, expem)"
.br
.RI "Get the exp of a symmetric 2*2 matrix\&. "
.ti -1c
.RI "subroutine \fBexpsym2d\fP (x, z, zd)"
.br
.RI "Sub Process for process symmetric 2*2 matrix\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file psym2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine psym2::expsym2::expsym2 (real(dp), dimension(2,2), intent(in) em, real(dp), dimension(2,2), intent(out) expem)\fC [private]\fP"

.PP
Get the exp of a symmetric 2*2 matrix\&. 
.PP
\fBParameters\fP
.RS 4
\fIem\fP symmetric 2*2 matrix 
.br
\fIexpem\fP exp of a symmetric 2*2 matrix 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 276 of file psym2\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine psym2::expsym2::expsym2d (real(dp), dimension(2,2), intent(in) x, real(dp), dimension(2,2), intent(out) z, real(dp), dimension(2,2,2,2), intent(out) zd)\fC [private]\fP"

.PP
Sub Process for process symmetric 2*2 matrix\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP symmetric 2*2 positive-definite matrix 
.br
\fIz\fP ??? 
.br
\fIzd\fP symmetric derivative 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 293 of file psym2\&.f90\&.
.PP
References pietc::o2\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
