.TH "psym2::id2222" 3 "Thu Mar 25 2021" "Version 1.0.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psym2::id2222
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBid2222\fP (em)"
.br
.RI "General routine for Effective identity\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file psym2\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine psym2::id2222::id2222 (real(dp), dimension(2,2,2,2), intent(out) em)\fC [private]\fP"

.PP
General routine for Effective identity\&. 
.PP
\fBParameters\fP
.RS 4
\fIem\fP ??? 
.RE
.PP
\fBAuthor\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 436 of file psym2\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
