.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/psym2.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/psym2.f90 \- 
.PP
Matrix routines\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBpsym2::chol2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::eigensym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::expsym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::expsym2d_e\fP"
.br
.ti -1c
.RI "interface \fBpsym2::expsym2d_t\fP"
.br
.ti -1c
.RI "interface \fBpsym2::id2222\fP"
.br
.ti -1c
.RI "interface \fBpsym2::invsym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::logsym2\fP"
.br
.ti -1c
.RI "module \fBpsym2\fP"
.br
.RI "\fIA suite of routines to perform the eigen-decomposition of symmetric 2*2 matrices and to deliver basic analytic functions, and the derivatives of these functions, of such matrices\&. \fP"
.ti -1c
.RI "interface \fBpsym2::sqrtsym2\fP"
.br
.ti -1c
.RI "interface \fBpsym2::sqrtsym2d_e\fP"
.br
.ti -1c
.RI "interface \fBpsym2::sqrtsym2d_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Matrix routines\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP
\fBDate:\fP
.RS 4
September 2018 
.RE
.PP

.PP
Definition in file \fBpsym2\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
