.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/kinds.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/kinds.f90 \- 
Hold specification kinds for variable declaration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBkinds\fP"
.br
.RI "\fIModule to hold specification kinds for variable declaration\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Hold specification kinds for variable declaration\&. 


.PP
\fBAuthor:\fP
.RS 4
David Wright, University of Michigan 
.RE
.PP

.PP
Definition in file \fBkinds\&.f90\fP\&.
.SH "Data Type Documentation"
.PP 
.SH "module kinds"
.PP 
Module to hold specification kinds for variable declaration\&. 

This module is based on (copied from) Paul vanDelst's type_kinds module found in the community radiative transfer model
.PP
\fBAuthor:\fP
.RS 4
David Wright, University of Michigan 
.RE
.PP

.PP
Definition at line 11 of file kinds\&.f90\&.
.PP
\fBData Fields:\fP
.RS 4
real(\fBr_kind\fP), parameter, public \fIdrmissing\fP Fill value for double real missing data\&. 
.br
.PP
integer, parameter, public \fIi_byte\fP generic specification kind for default byte\&. 
.br
.PP
integer, parameter, public \fIi_kind\fP generic specification kind for default integer\&. 
.br
.PP
integer, parameter, public \fIi_short\fP generic specification kind for default short\&. 
.br
.PP
real(\fBi_kind\fP), parameter, public \fIimissing\fP Fill value for integer missing data\&. 
.br
.PP
integer, parameter, public \fIlen_sta_name\fP Name length\&. 
.br
.PP
integer, parameter, public \fIr_kind\fP generic specification kind for default floating point 
.br
.PP
integer, parameter, public \fIr_single\fP specification kind for single precision (4-byte) real variable\&. 
.br
.PP
real(\fBr_single\fP), parameter, public \fIrmissing\fP Fill value for single real missing data\&. 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
