.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/kinds.f90" 3 "Thu Jun 20 2024" "Version 1.13.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/kinds.f90 \- Hold specification kinds for variable declaration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBkinds\fP"
.br
.RI "Module to hold specification kinds for variable declaration\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(r_kind), parameter, public \fBkinds::drmissing\fP =\-99999\&.0"
.br
.RI "Fill value for double real missing data\&. "
.ti -1c
.RI "integer, parameter, public \fBkinds::i_byte\fP = 1"
.br
.RI "generic specification kind for default byte\&. "
.ti -1c
.RI "integer, parameter, public \fBkinds::i_kind\fP = 4"
.br
.RI "generic specification kind for default integer\&. "
.ti -1c
.RI "integer, parameter, public \fBkinds::i_short\fP = 2"
.br
.RI "generic specification kind for default short\&. "
.ti -1c
.RI "real(i_kind), parameter, public \fBkinds::imissing\fP =\-99999"
.br
.RI "Fill value for integer missing data\&. "
.ti -1c
.RI "integer, parameter, public \fBkinds::len_sta_name\fP = 8"
.br
.RI "Name length\&. "
.ti -1c
.RI "integer, parameter, public \fBkinds::r_kind\fP = 8"
.br
.RI "generic specification kind for default floating point "
.ti -1c
.RI "integer, parameter, public \fBkinds::r_single\fP = 4"
.br
.RI "specification kind for single precision (4-byte) real variable\&. "
.ti -1c
.RI "real(r_single), parameter, public \fBkinds::rmissing\fP =\-99999\&.0"
.br
.RI "Fill value for single real missing data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Hold specification kinds for variable declaration\&. 


.PP
\fBAuthor:\fP
.RS 4
David Wright, University of Michigan 
.RE
.PP

.PP
Definition in file \fBkinds\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
