module_nwp::fcst_nwp
NAME
module_nwp::fcst_nwp -
SYNOPSIS
Private Member Functions
procedure finish => finish_nwp
Finish and deallocate.
procedure get_time_ind => get_time_ind_nwp
Get time ind.
procedure initial => initial_nwp
Defines vars and names.
procedure list_initial => list_initial_nwp
List the setup.
procedure read_n => read_nwp
Initialize arrays, get data.
Private Attributes
character(len=6) datatype
Data type.
integer datelen
Length of date string.
character(len=20), allocatable dimnamedate
String dimension name.
character(len=20), allocatable dimnameew
East/West dimension name.
character(len=20), allocatable dimnamens
North/South dimension name.
character(len=20), allocatable dimnametime
Time dimension name.
integer i_hice
Index of ice thickness.
integer i_ice
Index of ice var.
integer i_icet
Index of ice temp var.
integer i_mask
Is var visible (always 1).
integer i_sfct
Index of sst temp var.
integer i_sfctl
Index of sfcTl.
integer i_sst
Index of sst var.
integer i_zorl
Index of surface roughness.
character(len=20), allocatable latname
Latitude name.
character(len=20), allocatable lonname
Longitude name.
integer numvar
Number of variabls.
real(r_single), dimension(:,:,:),
allocatable nwp_hice_c"
cold start ice thickness
real(r_single), dimension(:,:),
allocatable nwp_hice_w"
warm start ice thickness
real(r_single), dimension(:,:,:),
allocatable nwp_ice_c"
cold start over water ice concentration 3d array
real(r_single), dimension(:,:),
allocatable nwp_ice_w"
warm start over water ice concentration 3d array
real(r_single), dimension(:,:,:),
allocatable nwp_icet_c"
cold start ice skin temperature 3d array
real(r_single), dimension(:,:),
allocatable nwp_icet_w"
warm start ice skin temperature 3d array
real(r_single), dimension(:,:),
allocatable nwp_mask_c"
cold start land/water mask 3d array
real(r_single), dimension(:,:),
allocatable nwp_mask_w"
warm start land/water mask 3d array
real(r_single), dimension(:,:,:),
allocatable nwp_sfct_c"
cold start skin temperature 3d array
real(r_single), dimension(:,:),
allocatable nwp_sfct_w"
warm start skin temperature 3d array
real(r_single), dimension(:,:),
allocatable nwp_sfctl_w"
warm start skin temperature 3d array
real(r_single), dimension(:,:,:),
allocatable nwp_sst_c"
cold start sst 3d array
real(r_single), dimension(:,:),
allocatable nwp_sst_w"
warm start sst 3d array
real(r_single), dimension(:,:,:),
allocatable nwp_zorl_c"
cold start surface roughness
real(r_single), dimension(:,:),
allocatable nwp_zorl_w"
warm start surface roughness
character(len=1), dimension(:,:),
allocatable times"
Array of times in FVCOM.
character(len=20), dimension(:),
allocatable varnames"
Variable names.
integer xlat
Number of latitudes.
integer xlon
Number of longitudes.
integer xtime
Number of times.
Detailed Description
Definition at line 26 of file module_nwp.f90.
Member Function/Subroutine Documentation
procedure module_nwp::fcst_nwp::finish () [private]
Finish and deallocate.
Returns:
Definition at line 72 of file module_nwp.f90.
References module_nwp::finish_nwp().
procedure module_nwp::fcst_nwp::get_time_ind () [private]
Get time ind.
Returns:
Definition at line 71 of file module_nwp.f90.
References module_nwp::get_time_ind_nwp().
procedure module_nwp::fcst_nwp::initial () [private]
Defines vars and names.
Returns:
Definition at line 68 of file module_nwp.f90.
References module_nwp::initial_nwp().
procedure module_nwp::fcst_nwp::list_initial () [private]
List the setup.
Returns:
Definition at line 69 of file module_nwp.f90.
References module_nwp::list_initial_nwp().
procedure module_nwp::fcst_nwp::read_n () [private]
Initialize arrays, get data.
Returns:
Definition at line 70 of file module_nwp.f90.
References module_nwp::read_nwp().
Field Documentation
character(len=6) module_nwp::fcst_nwp::datatype [private]
Data type.
Definition at line 27 of file module_nwp.f90.
integer module_nwp::fcst_nwp::datelen [private]
Length of date string.
Definition at line 32 of file module_nwp.f90.
character(len=20), allocatable module_nwp::fcst_nwp::dimnamedate [private]
String dimension name.
Definition at line 47 of file module_nwp.f90.
character(len=20), allocatable module_nwp::fcst_nwp::dimnameew [private]
East/West dimension name.
Definition at line 44 of file module_nwp.f90.
character(len=20), allocatable module_nwp::fcst_nwp::dimnamens [private]
North/South dimension name.
Definition at line 45 of file module_nwp.f90.
character(len=20), allocatable module_nwp::fcst_nwp::dimnametime [private]
Time dimension name.
Definition at line 46 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_hice [private]
Index of ice thickness.
Definition at line 40 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_ice [private]
Index of ice var.
Definition at line 35 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_icet [private]
Index of ice temp var.
Definition at line 37 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_mask [private]
Is var visible (always 1).
Definition at line 33 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_sfct [private]
Index of sst temp var.
Definition at line 36 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_sfctl [private]
Index of sfcTl.
Definition at line 38 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_sst [private]
Index of sst var.
Definition at line 34 of file module_nwp.f90.
integer module_nwp::fcst_nwp::i_zorl [private]
Index of surface roughness.
Definition at line 39 of file module_nwp.f90.
character(len=20), allocatable module_nwp::fcst_nwp::latname [private]
Latitude name.
Definition at line 42 of file module_nwp.f90.
character(len=20), allocatable module_nwp::fcst_nwp::lonname [private]
Longitude name.
Definition at line 43 of file module_nwp.f90.
integer module_nwp::fcst_nwp::numvar [private]
Number of variabls.
Definition at line 28 of file module_nwp.f90.
real(r_single), dimension(:,:,:), allocatable module_nwp::fcst_nwp::nwp_hice_c [private]
cold start ice thickness
Definition at line 56 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_hice_w [private]
warm start ice thickness
Definition at line 65 of file module_nwp.f90.
real(r_single), dimension(:,:,:), allocatable module_nwp::fcst_nwp::nwp_ice_c [private]
cold start over water ice concentration 3d array
Definition at line 52 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_ice_w [private]
warm start over water ice concentration 3d array
Definition at line 60 of file module_nwp.f90.
real(r_single), dimension(:,:,:), allocatable module_nwp::fcst_nwp::nwp_icet_c [private]
cold start ice skin temperature 3d array
Definition at line 54 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_icet_w [private]
warm start ice skin temperature 3d array
Definition at line 62 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_mask_c [private]
cold start land/water mask 3d array
Definition at line 50 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_mask_w [private]
warm start land/water mask 3d array
Definition at line 58 of file module_nwp.f90.
real(r_single), dimension(:,:,:), allocatable module_nwp::fcst_nwp::nwp_sfct_c [private]
cold start skin temperature 3d array
Definition at line 53 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_sfct_w [private]
warm start skin temperature 3d array
Definition at line 61 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_sfctl_w [private]
warm start skin temperature 3d array
Definition at line 63 of file module_nwp.f90.
real(r_single), dimension(:,:,:), allocatable module_nwp::fcst_nwp::nwp_sst_c [private]
cold start sst 3d array
Definition at line 51 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_sst_w [private]
warm start sst 3d array
Definition at line 59 of file module_nwp.f90.
real(r_single), dimension(:,:,:), allocatable module_nwp::fcst_nwp::nwp_zorl_c [private]
cold start surface roughness
Definition at line 55 of file module_nwp.f90.
real(r_single), dimension(:,:), allocatable module_nwp::fcst_nwp::nwp_zorl_w [private]
warm start surface roughness
Definition at line 64 of file module_nwp.f90.
character(len=1), dimension(:,:), allocatable module_nwp::fcst_nwp::times [private]
Array of times in FVCOM.
Definition at line 48 of file module_nwp.f90.
character(len=20), dimension(:), allocatable module_nwp::fcst_nwp::varnames [private]
Variable names.
Definition at line 41 of file module_nwp.f90.
integer module_nwp::fcst_nwp::xlat [private]
Number of latitudes.
Definition at line 29 of file module_nwp.f90.
integer module_nwp::fcst_nwp::xlon [private]
Number of longitudes.
Definition at line 30 of file module_nwp.f90.
integer module_nwp::fcst_nwp::xtime [private]
Number of times.
Definition at line 31 of file module_nwp.f90.
Author
Generated automatically by Doxygen for fvcom_tools from the source code.