.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_nwp.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/fvcom_tools.fd/module_nwp.f90 \- 
.PP
Defines FV3LAM and FVCOM forecast data structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBmodule_nwp::fcst_nwp\fP"
.br
.ti -1c
.RI "module \fBmodule_nwp\fP"
.br
.RI "\fIThis module defines FV3LAM and FVCOM forecast data structure and the method to read and write observations from and to those data structures\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines FV3LAM and FVCOM forecast data structure\&. 


.PP
\fBAuthor:\fP
.RS 4
David Wright, University of Michigan and GLERL, 
.RE
.PP
\fBDate:\fP
.RS 4
17 Aug 2020 
.RE
.PP

.PP
Definition in file \fBmodule_nwp\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
