.TH "module_nwp::fcst_nwp" 3 "Tue Jan 17 2023" "Version 1.9.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
module_nwp::fcst_nwp
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBmodule_nwp::nwp_type\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBfinish\fP => \fBfinish_nwp\fP"
.br
.RI "Finish and deallocate\&. "
.ti -1c
.RI "procedure \fBget_time_ind\fP => \fBget_time_ind_nwp\fP"
.br
.RI "Get time ind\&. "
.ti -1c
.RI "procedure \fBinitial\fP => \fBinitial_nwp\fP"
.br
.RI "Defines vars and names\&. "
.ti -1c
.RI "procedure \fBlist_initial\fP => \fBlist_initial_nwp\fP"
.br
.RI "List the setup\&. "
.ti -1c
.RI "procedure \fBread_n\fP => \fBread_nwp\fP"
.br
.RI "Initialize arrays, get data\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(\fBnwpbase\fP), pointer \fBhead\fP => NULL()"
.br
.RI "Pointer to head of list\&. "
.ti -1c
.RI "type(\fBnwpbase\fP), pointer \fBtail\fP => NULL()"
.br
.RI "Pointer to tail of list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file module_nwp\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure module_nwp::fcst_nwp::finish ()\fC [private]\fP"

.PP
Finish and deallocate\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 83 of file module_nwp\&.f90\&.
.SS "procedure module_nwp::fcst_nwp::get_time_ind ()\fC [private]\fP"

.PP
Get time ind\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 82 of file module_nwp\&.f90\&.
.SS "procedure module_nwp::fcst_nwp::initial ()\fC [private]\fP"

.PP
Defines vars and names\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 79 of file module_nwp\&.f90\&.
.SS "procedure module_nwp::fcst_nwp::list_initial ()\fC [private]\fP"

.PP
List the setup\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 80 of file module_nwp\&.f90\&.
.SS "procedure module_nwp::fcst_nwp::read_n ()\fC [private]\fP"

.PP
Initialize arrays, get data\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 81 of file module_nwp\&.f90\&.
.SH "Field Documentation"
.PP 
.SS "type(\fBnwpbase\fP), pointer module_nwp::fcst_nwp::head => NULL()\fC [private]\fP"

.PP
Pointer to head of list\&. 
.PP
Definition at line 76 of file module_nwp\&.f90\&.
.SS "type(\fBnwpbase\fP), pointer module_nwp::fcst_nwp::tail => NULL()\fC [private]\fP"

.PP
Pointer to tail of list\&. 
.PP
Definition at line 77 of file module_nwp\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
