module_ncio
NAME
module_ncio - Functions to read and write netcdf files.
SYNOPSIS
Data Types
type ncio
Functions/Subroutines
subroutine add_new_var_2d (this, varname, dname1, dname2, lname, units, dtype)
Add a new variable to sfc_data.nc with dimensions (yaxis_1, xaxis_1).
subroutine add_new_var_3d (this, varname, dname1, dname2, dname3, lname, units, dtype)
Add a new variable to sfc_data.nc with dimensions (Time, yaxis_1, xaxis_1).
subroutine close_nc (this)
Close a netcdf file.
subroutine convert_theta2t_2dgrid (this, nx, ny, ps, t2)
Convert theta T (Kelvin) to T (deg C).
subroutine get_att_nc_int (this, attname, ival)
Get integer attribute in wrf netcdf file.
subroutine get_att_nc_real (this, attname, rval)
Get attribute in wrf netcdf file.
subroutine get_att_nc_string (this, attname, string)
Get string attribute in wrf netcdf file.
subroutine get_dim_nc (this, dimname, dimvalue)
Get dimensions in netcdf file.
subroutine get_var_nc_char (this, varname, ilength, field)
Read in character type variable.
subroutine get_var_nc_char_1d (this, varname, nd1, field)
Read in 1D character type variable.
subroutine get_var_nc_char_2d (this, varname, nd1, nd2, field)
Read in 2D character type variable.
subroutine get_var_nc_char_3d (this, varname, nd1, nd2, nd3, field)
Read in 3D character type variable.
subroutine get_var_nc_double (this, varname, ilength, field)
Read in double type variable.
subroutine get_var_nc_double_1d (this, varname, nd1, field)
Read in 1D double type variable.
subroutine get_var_nc_double_2d (this, varname, nd1, nd2, field)
Read in 2D double type variable.
subroutine get_var_nc_double_3d (this, varname, nd1, nd2, nd3, field)
Read in 3D double type field.
subroutine get_var_nc_int (this, varname, ilength, field)
Read in integer type variable.
subroutine get_var_nc_int_1d (this, varname, nd1, field)
Read in 1D integer variable.
subroutine get_var_nc_int_2d (this, varname, nd1, nd2, field)
Read in 2D integer type variable.
subroutine get_var_nc_int_3d (this, varname, nd1, nd2, nd3, field)
Read in 3D integer type variable.
subroutine get_var_nc_real (this, varname, ilength, field)
Read in real type variable.
subroutine get_var_nc_real_1d (this, varname, nd1, field)
Read in 1D real type variable.
subroutine get_var_nc_real_2d (this, varname, nd1, nd2, field)
Read in 2D real type variable.
subroutine get_var_nc_real_3d (this, varname, nd1, nd2, nd3, field)
Read in 3D real type variable.
subroutine get_var_nc_short (this, varname, ilength, field)
Read in short type variable.
subroutine get_var_nc_short_1d (this, varname, nd1, field)
Read in 1D short type variable.
subroutine get_var_nc_short_2d (this, varname, nd1, nd2, field)
Read in 2D short type variable.
subroutine handle_err (this, status)
Handle netCDF errors.
subroutine open_nc (this, filename, action, debug_level)
Open a netcdf file, set initial debug level.
subroutine replace_var_nc_char (this, varname, ilength, field)
Replace character type variable.
subroutine replace_var_nc_char_1d (this, varname, nd1, field)
Replace 1D character type variable.
subroutine replace_var_nc_char_2d (this, varname, nd1, nd2, field)
Replace 2D character type variable.
subroutine replace_var_nc_char_3d (this, varname, nd1, nd2, nd3, field)
Replace 3D character type variable.
subroutine replace_var_nc_double (this, varname, ilength, field)
Replace double type variable.
subroutine replace_var_nc_double_1d (this, varname, nd1, field)
Replace 1D double type variable.
subroutine replace_var_nc_double_2d (this, varname, nd1, nd2, field)
Replace 2D double type variable.
subroutine replace_var_nc_double_3d (this, varname, nd1, nd2, nd3, field)
Replace 3D double type variable.
subroutine replace_var_nc_int (this, varname, ilength, field)
Replace integer type variable.
subroutine replace_var_nc_int_1d (this, varname, nd1, field)
Replace 1D integer type variable.
subroutine replace_var_nc_int_2d (this, varname, nd1, nd2, field)
Replace 2D integer type variable.
subroutine replace_var_nc_int_3d (this, varname, nd1, nd2, nd3, field)
Replace 3D integer type variable.
subroutine replace_var_nc_real (this, varname, ilength, field)
Replace real type variable.
subroutine replace_var_nc_real_1d (this, varname, nd1, field)
Replace 1D real type variable.
subroutine replace_var_nc_real_2d (this, varname, nd1, nd2, field)
Replace 2D real type variable.
subroutine replace_var_nc_real_3d (this, varname, nd1, nd2, nd3, field)
Replace 3D real type variable.
Detailed Description
Functions to read and write netcdf files.
Author:
Ming Hu
Date:
2017-11-01
Function/Subroutine Documentation
subroutine module_ncio::add_new_var_2d (class(ncio) this, character(len=*), intent(in) varname, character(len=*), intent(in) dname1, character(len=*), intent(in) dname2, character(len=*), intent(in) lname, character(len=*), intent(in) units, character(len=*), intent(in) dtype) [private]
Add a new variable to sfc_data.nc with dimensions (yaxis_1, xaxis_1).
Parameters:
this instance of an ncio class
varname Name of variable to be created in netcdf file
dname1 1st dimension name
dname2 2nd dimension name
lname long name output for netcdf variable
units units to use in netcdf variable
dtype data type of netcdf variable
Author:
David.M.Wright org: UM/GLERL
Date:
2021-10-07
Definition at line 2575 of file module_ncio.f90.
Referenced by module_ncio::ncio::add_new_var().
subroutine module_ncio::add_new_var_3d (class(ncio) this, character(len=*), intent(in) varname, character(len=*), intent(in) dname1, character(len=*), intent(in) dname2, character(len=*), intent(in) dname3, character(len=*), intent(in) lname, character(len=*), intent(in) units, character(len=*), intent(in) dtype) [private]
Add a new variable to sfc_data.nc with dimensions (Time, yaxis_1, xaxis_1).
Parameters:
this instance of an ncio class
varname Name of variable to be created in netcdf file
dname1 1st dimension name
dname2 2nd dimension name
dname3 3rd dimension name
lname long name output for netcdf variable
units units to use in netcdf variable
dtype date type of netcdf variable
Author:
David.M.Wright org: UM/GLERL
Date:
2020-09-01
Definition at line 2518 of file module_ncio.f90.
Referenced by module_ncio::ncio::add_new_var().
subroutine module_ncio::close_nc (class(ncio) this) [private]
Close a netcdf file.
Parameters:
this instance of an ncio class
Author:
Ming Hu org: GSD/AMB
Date:
2017-04-10
Definition at line 141 of file module_ncio.f90.
subroutine module_ncio::convert_theta2t_2dgrid (class(ncio) this, integer nx, integer ny, real, dimension(nx,ny), intent(in) ps, real, dimension(nx,ny), intent(inout) t2)
Convert theta T (Kelvin) to T (deg C).
Parameters:
this instance of an ncio class
nx number of grid points in x-dir
ny number of grid points in y-dir
ps Pressure (Pa)
t2 Pot. Temperature (Kelvin)
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2481 of file module_ncio.f90.
subroutine module_ncio::get_att_nc_int (class(ncio) this, character(len=*), intent(in) attname, integer, intent(out) ival) [private]
Get integer attribute in wrf netcdf file.
Parameters:
this instance of an ncio class
attname name of the attribute to get
ival value of attribute.
Author:
Ming Hu org: GSD/AMB
Date:
2017-10-04
Definition at line 187 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_att().
subroutine module_ncio::get_att_nc_real (class(ncio) this, character(len=*), intent(in) attname, real, intent(out) rval) [private]
Get attribute in wrf netcdf file.
Parameters:
this instance of an ncio class
attname name of the attribute to get
rval return value
Author:
Ming Hu org: GSD/AMB
Date:
2017-10-04
Definition at line 163 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_att().
subroutine module_ncio::get_att_nc_string (class(ncio) this, character(len=*), intent(in) attname, character(len=*), intent(out) string) [private]
Get string attribute in wrf netcdf file.
Parameters:
this instance of an ncio class
attname name of the attribute to get
string value of attribute.
Author:
Ming Hu org: GSD/AMB
Date:
2017-10-04
Definition at line 211 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_att().
subroutine module_ncio::get_dim_nc (class(ncio) this, character(len=*), intent(in) dimname, integer, intent(out) dimvalue) [private]
Get dimensions in netcdf file.
Parameters:
this instance of an ncio class
dimname name of the dimension
dimvalue length of the dimension
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 236 of file module_ncio.f90.
subroutine module_ncio::get_var_nc_char (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, character, dimension(ilength), intent(out) field)
Read in character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength size of array
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2354 of file module_ncio.f90.
subroutine module_ncio::get_var_nc_char_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, character, dimension(nd1), intent(out) field)
Read in 1D character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2210 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_char_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, character, dimension(nd1,nd2), intent(out) field)
Read in 2D character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2248 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_char_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, character, dimension(nd1,nd2,nd3), intent(out) field)
Read in 3D character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2300 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_double (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, real(8), dimension(ilength), intent(out) field)
Read in double type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength size of array
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1390 of file module_ncio.f90.
subroutine module_ncio::get_var_nc_double_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, real(8), dimension(nd1), intent(out) field)
Read in 1D double type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 lenth of first dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1244 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_double_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, real(8), dimension(nd1,nd2), intent(out) field)
Read in 2D double type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1282 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_double_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, real(8), dimension(nd1,nd2,nd3), intent(out) field)
Read in 3D double type field.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1334 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_int (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, integer, dimension(ilength), intent(out) field)
Read in integer type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength size of array
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1904 of file module_ncio.f90.
subroutine module_ncio::get_var_nc_int_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, dimension(nd1), intent(out) field)
Read in 1D integer variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1755 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_int_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, dimension(nd1,nd2), intent(out) field)
Read in 2D integer type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1793 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_int_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, integer, dimension(nd1,nd2,nd3), intent(out) field)
Read in 3D integer type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1848 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_real (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, real(4), dimension(ilength), intent(out) field)
Read in real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength size of array
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1646 of file module_ncio.f90.
subroutine module_ncio::get_var_nc_real_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, real(4), dimension(nd1), intent(out) field)
Read in 1D real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1497 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_real_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, real(4), dimension(nd1,nd2), intent(out) field)
Read in 2D real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1535 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_real_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, real(4), dimension(nd1,nd2,nd3), intent(out) field)
Read in 3D real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1590 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_short (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, integer(2), dimension(ilength), intent(out) field)
Read in short type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength size of array
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2104 of file module_ncio.f90.
subroutine module_ncio::get_var_nc_short_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer(2), dimension(nd1), intent(out) field)
Read in 1D short type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2013 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::get_var_nc_short_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer(2), dimension(nd1,nd2), intent(out) field)
Read in 2D short type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field output variable
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2051 of file module_ncio.f90.
Referenced by module_ncio::ncio::get_var().
subroutine module_ncio::handle_err (class(ncio) this, integer, intent(in) status)
Handle netCDF errors.
Parameters:
this instance of an ncio class
status return code from neCDF
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 2461 of file module_ncio.f90.
subroutine module_ncio::open_nc (class(ncio) this, character(len=*), intent(in) filename, character(len=1), intent(in) action, integer, intent(in), optional debug_level) [private]
Open a netcdf file, set initial debug level.
Parameters:
this instance of an ncio class
filename the file to open
action 'r' for read, 'w' for write
debug_level set to non-zero for some verbose output
Author:
Ming Hu
Date:
2017-11-01
Definition at line 104 of file module_ncio.f90.
subroutine module_ncio::replace_var_nc_char (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, character, dimension(ilength), intent(in) field)
Replace character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength length of array
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 398 of file module_ncio.f90.
subroutine module_ncio::replace_var_nc_char_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, character, dimension(nd1), intent(in) field) [private]
Replace 1D character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 264 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_char_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, character, dimension(nd1,nd2), intent(in) field)
Replace 2D character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 300 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_char_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, character, dimension(nd1,nd2,nd3), intent(in) field)
Replace 3D character type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 348 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_double (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, real(8), dimension(ilength), intent(in) field)
Replace double type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength size of array
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 894 of file module_ncio.f90.
subroutine module_ncio::replace_var_nc_double_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, real(8), dimension(nd1), intent(in) field)
Replace 1D double type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 749 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_double_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, real(8), dimension(nd1,nd2), intent(in) field)
Replace 2D double type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 787 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_double_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, real(8), dimension(nd1,nd2,nd3), intent(in) field)
Replace 3D double type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 838 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_int (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, integer, dimension(ilength), intent(in) field)
Replace integer type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength size of array
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1138 of file module_ncio.f90.
subroutine module_ncio::replace_var_nc_int_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, dimension(nd1), intent(in) field)
Replace 1D integer type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 lenth of first dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1000 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_int_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, dimension(nd1,nd2), intent(in) field)
Replace 2D integer type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1035 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_int_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, integer, dimension(nd1,nd2,nd3), intent(in) field)
Replace 3D integer type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 1086 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_real (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) ilength, real(4), dimension(ilength), intent(in) field)
Replace real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
ilength length of array
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 643 of file module_ncio.f90.
subroutine module_ncio::replace_var_nc_real_1d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, real(4), dimension(nd1), intent(in) field)
Replace 1D real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 505 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_real_2d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, real(4), dimension(nd1,nd2), intent(in) field)
Replace 2D real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 540 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
subroutine module_ncio::replace_var_nc_real_3d (class(ncio) this, character(len=*), intent(in) varname, integer, intent(in) nd1, integer, intent(in) nd2, integer, intent(in) nd3, real(4), dimension(nd1,nd2,nd3), intent(in) field)
Replace 3D real type variable.
Parameters:
this instance of an ncio class
varname name of the variable
nd1 length of first dimension
nd2 length of second dimension
nd3 length of third dimension
field replacement field
Author:
Ming Hu org: GSD/AMB
Date:
2017-11-01
Definition at line 588 of file module_ncio.f90.
Referenced by module_ncio::ncio::replace_var().
Author
Generated automatically by Doxygen for fvcom_tools from the source code.