.TH "module_nwp::nwp_type" 3 "Tue Jan 17 2023" "Version 1.9.0" "fvcom_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
module_nwp::nwp_type
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBmodule_nwp::fcst_nwp\fP\&.
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "character(len=6) \fBdatatype\fP"
.br
.RI "Data type\&. "
.ti -1c
.RI "integer \fBdatelen\fP"
.br
.RI "Length of date string\&. "
.ti -1c
.RI "character(len=20), allocatable \fBdimnamedate\fP"
.br
.RI "String dimension name\&. "
.ti -1c
.RI "character(len=20), allocatable \fBdimnameew\fP"
.br
.RI "East/West dimension name\&. "
.ti -1c
.RI "character(len=20), allocatable \fBdimnamens\fP"
.br
.RI "North/South dimension name\&. "
.ti -1c
.RI "character(len=20), allocatable \fBdimnametime\fP"
.br
.RI "Time dimension name\&. "
.ti -1c
.RI "integer \fBi_hice\fP"
.br
.RI "Index of ice thickness\&. "
.ti -1c
.RI "integer \fBi_ice\fP"
.br
.RI "Index of ice var\&. "
.ti -1c
.RI "integer \fBi_icet\fP"
.br
.RI "Index of ice temp var\&. "
.ti -1c
.RI "integer \fBi_mask\fP"
.br
.RI "Is var visible (always 1)\&. "
.ti -1c
.RI "integer \fBi_sfct\fP"
.br
.RI "Index of sst temp var\&. "
.ti -1c
.RI "integer \fBi_sfctl\fP"
.br
.RI "Index of sfcTl\&. "
.ti -1c
.RI "integer \fBi_sst\fP"
.br
.RI "Index of sst var\&. "
.ti -1c
.RI "integer \fBi_zorl\fP"
.br
.RI "Index of surface roughness\&. "
.ti -1c
.RI "character(len=20), allocatable \fBlatname\fP"
.br
.RI "Latitude name\&. "
.ti -1c
.RI "character(len=20), allocatable \fBlonname\fP"
.br
.RI "Longitude name\&. "
.ti -1c
.RI "integer \fBnumvar\fP"
.br
.RI "Number of variabls\&. "
.ti -1c
.RI "real(r_kind), dimension(:,:,:), allocatable \fBnwp_hice_c\fP"
.br
.RI "cold start ice thickness "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_hice_w\fP"
.br
.RI "warm start ice thickness "
.ti -1c
.RI "real(r_kind), dimension(:,:,:), allocatable \fBnwp_ice_c\fP"
.br
.RI "cold start over water ice concentration 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_ice_w\fP"
.br
.RI "warm start over water ice concentration 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:,:), allocatable \fBnwp_icet_c\fP"
.br
.RI "cold start ice skin temperature 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_icet_w\fP"
.br
.RI "warm start ice skin temperature 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_mask_c\fP"
.br
.RI "cold start land/water mask 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_mask_w\fP"
.br
.RI "warm start land/water mask 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:,:), allocatable \fBnwp_sfct_c\fP"
.br
.RI "cold start skin temperature 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_sfct_w\fP"
.br
.RI "warm start skin temperature 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_sfctl_w\fP"
.br
.RI "warm start skin temperature 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:,:), allocatable \fBnwp_sst_c\fP"
.br
.RI "cold start sst 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_sst_w\fP"
.br
.RI "warm start sst 3d array "
.ti -1c
.RI "real(r_kind), dimension(:,:,:), allocatable \fBnwp_zorl_c\fP"
.br
.RI "cold start surface roughness "
.ti -1c
.RI "real(r_kind), dimension(:,:), allocatable \fBnwp_zorl_w\fP"
.br
.RI "warm start surface roughness "
.ti -1c
.RI "character(len=1), dimension(:,:), allocatable \fBtimes\fP"
.br
.RI "Array of times in FVCOM\&. "
.ti -1c
.RI "character(len=20), dimension(:), allocatable \fBvarnames\fP"
.br
.RI "Variable names\&. "
.ti -1c
.RI "integer \fBxlat\fP"
.br
.RI "Number of latitudes\&. "
.ti -1c
.RI "integer \fBxlon\fP"
.br
.RI "Number of longitudes\&. "
.ti -1c
.RI "integer \fBxtime\fP"
.br
.RI "Number of times\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file module_nwp\&.f90\&.
.SH "Field Documentation"
.PP 
.SS "character(len=6) module_nwp::nwp_type::datatype\fC [private]\fP"

.PP
Data type\&. 
.PP
Definition at line 29 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::datelen\fC [private]\fP"

.PP
Length of date string\&. 
.PP
Definition at line 34 of file module_nwp\&.f90\&.
.SS "character(len=20), allocatable module_nwp::nwp_type::dimnamedate\fC [private]\fP"

.PP
String dimension name\&. 
.PP
Definition at line 49 of file module_nwp\&.f90\&.
.SS "character(len=20), allocatable module_nwp::nwp_type::dimnameew\fC [private]\fP"

.PP
East/West dimension name\&. 
.PP
Definition at line 46 of file module_nwp\&.f90\&.
.SS "character(len=20), allocatable module_nwp::nwp_type::dimnamens\fC [private]\fP"

.PP
North/South dimension name\&. 
.PP
Definition at line 47 of file module_nwp\&.f90\&.
.SS "character(len=20), allocatable module_nwp::nwp_type::dimnametime\fC [private]\fP"

.PP
Time dimension name\&. 
.PP
Definition at line 48 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_hice\fC [private]\fP"

.PP
Index of ice thickness\&. 
.PP
Definition at line 42 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_ice\fC [private]\fP"

.PP
Index of ice var\&. 
.PP
Definition at line 37 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_icet\fC [private]\fP"

.PP
Index of ice temp var\&. 
.PP
Definition at line 39 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_mask\fC [private]\fP"

.PP
Is var visible (always 1)\&. 
.PP
Definition at line 35 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_sfct\fC [private]\fP"

.PP
Index of sst temp var\&. 
.PP
Definition at line 38 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_sfctl\fC [private]\fP"

.PP
Index of sfcTl\&. 
.PP
Definition at line 40 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_sst\fC [private]\fP"

.PP
Index of sst var\&. 
.PP
Definition at line 36 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::i_zorl\fC [private]\fP"

.PP
Index of surface roughness\&. 
.PP
Definition at line 41 of file module_nwp\&.f90\&.
.SS "character(len=20), allocatable module_nwp::nwp_type::latname\fC [private]\fP"

.PP
Latitude name\&. 
.PP
Definition at line 44 of file module_nwp\&.f90\&.
.SS "character(len=20), allocatable module_nwp::nwp_type::lonname\fC [private]\fP"

.PP
Longitude name\&. 
.PP
Definition at line 45 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::numvar\fC [private]\fP"

.PP
Number of variabls\&. 
.PP
Definition at line 30 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:,:), allocatable module_nwp::nwp_type::nwp_hice_c\fC [private]\fP"

.PP
cold start ice thickness 
.PP
Definition at line 58 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_hice_w\fC [private]\fP"

.PP
warm start ice thickness 
.PP
Definition at line 67 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:,:), allocatable module_nwp::nwp_type::nwp_ice_c\fC [private]\fP"

.PP
cold start over water ice concentration 3d array 
.PP
Definition at line 54 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_ice_w\fC [private]\fP"

.PP
warm start over water ice concentration 3d array 
.PP
Definition at line 62 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:,:), allocatable module_nwp::nwp_type::nwp_icet_c\fC [private]\fP"

.PP
cold start ice skin temperature 3d array 
.PP
Definition at line 56 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_icet_w\fC [private]\fP"

.PP
warm start ice skin temperature 3d array 
.PP
Definition at line 64 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_mask_c\fC [private]\fP"

.PP
cold start land/water mask 3d array 
.PP
Definition at line 52 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_mask_w\fC [private]\fP"

.PP
warm start land/water mask 3d array 
.PP
Definition at line 60 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:,:), allocatable module_nwp::nwp_type::nwp_sfct_c\fC [private]\fP"

.PP
cold start skin temperature 3d array 
.PP
Definition at line 55 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_sfct_w\fC [private]\fP"

.PP
warm start skin temperature 3d array 
.PP
Definition at line 63 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_sfctl_w\fC [private]\fP"

.PP
warm start skin temperature 3d array 
.PP
Definition at line 65 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:,:), allocatable module_nwp::nwp_type::nwp_sst_c\fC [private]\fP"

.PP
cold start sst 3d array 
.PP
Definition at line 53 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_sst_w\fC [private]\fP"

.PP
warm start sst 3d array 
.PP
Definition at line 61 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:,:), allocatable module_nwp::nwp_type::nwp_zorl_c\fC [private]\fP"

.PP
cold start surface roughness 
.PP
Definition at line 57 of file module_nwp\&.f90\&.
.SS "real(r_kind), dimension(:,:), allocatable module_nwp::nwp_type::nwp_zorl_w\fC [private]\fP"

.PP
warm start surface roughness 
.PP
Definition at line 66 of file module_nwp\&.f90\&.
.SS "character(len=1), dimension(:,:), allocatable module_nwp::nwp_type::times\fC [private]\fP"

.PP
Array of times in FVCOM\&. 
.PP
Definition at line 50 of file module_nwp\&.f90\&.
.SS "character(len=20), dimension(:), allocatable module_nwp::nwp_type::varnames\fC [private]\fP"

.PP
Variable names\&. 
.PP
Definition at line 43 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::xlat\fC [private]\fP"

.PP
Number of latitudes\&. 
.PP
Definition at line 31 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::xlon\fC [private]\fP"

.PP
Number of longitudes\&. 
.PP
Definition at line 32 of file module_nwp\&.f90\&.
.SS "integer module_nwp::nwp_type::xtime\fC [private]\fP"

.PP
Number of times\&. 
.PP
Definition at line 33 of file module_nwp\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for fvcom_tools from the source code\&.
