#!/bin/sh

set -eux

case $1 in
  "cray" )
     FCMP=ftn
     FFLAGS="-O3 -fp-model precise" ;;
  "wcoss" )
     FCMP=ifort
     FFLAGS="-O3 -fp-model precise ${NETCDF_FFLAGS} ${NETCDF_LDFLAGS_F}" ;;
  "wcoss_dell_p3" )
     FCMP=ifort
     FFLAGS="-O3 -fp-model precise ${NETCDF_FFLAGS} ${NETCDF_LDFLAGS_F}" ;;
  "jet" )
     FCMP=ifort
     FFLAGS="-O3 -fp-model precise -I$NETCDF/include -L$NETCDF/lib -lnetcdff -lnetcdf" ;;
  "hera" )
     FCMP=ifort
     FFLAGS="-O3 -fp-model precise -I$NETCDF/include -L$NETCDF/lib -lnetcdff -lnetcdf" ;;
  "linux.gnu" )
     FCMP=gfortran
     FFLAGS="-O3 -I$NETCDF/include -L$NETCDF/lib -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -ldl -lz" ;;
  "linux.intel" )
     FCMP=ifort
     FFLAGS="-O3 -I$NETCDF/include -L$NETCDF/lib -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -ldl -lz" ;;
  *)
     echo "SHAVE UTILITY BUILD NOT TESTED ON MACHINE $1"
     exit 1 ;;
esac

EXEC=../../../../exec/shave.x
rm -f $EXEC
$FCMP -o $EXEC shave_nc.F90 $FFLAGS
rc=$?

if [ $rc -ne 0 ]; then
  echo "ERROR BUILDING SHAVE UTILITY"
  exit $rc
else
  exit 0
fi
