#################################################################
# Baseline configurations
# By default, for each listed OCN resolution, mapped ocean masks will
# be generated for C12,C24,C48,C96,C192,C384,C768 and C1152. For C3072
# resources and memory will need to be increased. See rt.sh notes.
# If a list of ATM resolutions is included below, limit ATM resolutions
# to those listed
#################################################################

# TEST_NAME | ATMRESLIST
#  mx025 |
#  mx050 |
#  mx100 |
   mx100 | 96
#  mx500 | 12,24
#  mx900 | 12,24
