.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpesg\&.f90\fP"
.br
.RI "\fIRoutines to perform ESG regional grid mappings\&. \fP"
.ti -1c
.RI "file \fBpfun\&.f90\fP"
.br
.RI "\fIRoutine evaluating useful functions not always available in Fortran\&. \fP"
.ti -1c
.RI "file \fBpietc\&.f90\fP"
.br
.RI "\fIDouble-precision constants\&. \fP"
.ti -1c
.RI "file \fBpietc_s\&.f90\fP"
.br
.RI "\fISingle precision constants\&. \fP"
.ti -1c
.RI "file \fBpkind\&.f90\fP"
.br
.RI "\fIStandard integer, real, and complex single and double precision kinds\&. \fP"
.ti -1c
.RI "file \fBpmat\&.f90\fP"
.br
.RI "\fIUtility routines for various linear inversions and Cholesky\&. \fP"
.ti -1c
.RI "file \fBpmat2\&.f90\fP"
.br
.RI "\fIRoutines dealing with the operations of banded matrices\&. \fP"
.ti -1c
.RI "file \fBpmat4\&.f90\fP"
.br
.RI "\fIEuclidean geometry, geometric (stereographic) projections, related transformations (Mobius)\&. \fP"
.ti -1c
.RI "file \fBpmat5\&.f90\fP"
.br
.RI "\fIHandy geographical transformations\&. \fP"
.ti -1c
.RI "file \fBpsym2\&.f90\fP"
.br
.RI "\fIMatrix routines\&. \fP"
.ti -1c
.RI "file \fBregional_esg_grid\&.f90\fP"
.br
.RI "\fICompute geo-referencing parameters for the Extended Schmidt Gnomonic (ESG) regional grid\&. \fP"
.in -1c
