.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pesg.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pesg.f90 \- 
.PP
Routines to perform ESG regional grid mappings\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBpesg::bestesg_geo\fP"
.br
.ti -1c
.RI "interface \fBpesg::bestesg_map\fP"
.br
.ti -1c
.RI "interface \fBpesg::gaulegh\fP"
.br
.ti -1c
.RI "interface \fBpesg::get_edges\fP"
.br
.ti -1c
.RI "interface \fBpesg::get_meanq\fP"
.br
.ti -1c
.RI "interface \fBpesg::get_qofv\fP"
.br
.ti -1c
.RI "interface \fBpesg::get_qx\fP"
.br
.ti -1c
.RI "interface \fBpesg::gtoxm_ak_dd\fP"
.br
.ti -1c
.RI "interface \fBpesg::gtoxm_ak_rr\fP"
.br
.ti -1c
.RI "interface \fBpesg::guessak_geo\fP"
.br
.ti -1c
.RI "interface \fBpesg::guessak_map\fP"
.br
.ti -1c
.RI "interface \fBpesg::hgrid_ak\fP"
.br
.ti -1c
.RI "interface \fBpesg::hgrid_ak_dc\fP"
.br
.ti -1c
.RI "interface \fBpesg::hgrid_ak_dd\fP"
.br
.ti -1c
.RI "interface \fBpesg::hgrid_ak_rc\fP"
.br
.ti -1c
.RI "interface \fBpesg::hgrid_ak_rr\fP"
.br
.ti -1c
.RI "module \fBpesg\fP"
.br
.RI "\fISuite of routines to perform the 2-parameter family of Extended Schmidt Gnomonic (ESG) regional grid mappings, and to optimize the the two parameters, A and K, of those mappings for a given rectangular domain's principal (median) semi-arcs with respect to a domain-averaged measure of distortion\&. \fP"
.ti -1c
.RI "interface \fBpesg::xctoxm_ak\fP"
.br
.ti -1c
.RI "interface \fBpesg::xctoxs\fP"
.br
.ti -1c
.RI "interface \fBpesg::xmtog_ak_dd\fP"
.br
.ti -1c
.RI "interface \fBpesg::xmtog_ak_rr\fP"
.br
.ti -1c
.RI "interface \fBpesg::xmtoxc_ak\fP"
.br
.ti -1c
.RI "interface \fBpesg::xmtoxt\fP"
.br
.ti -1c
.RI "interface \fBpesg::xstoxc\fP"
.br
.ti -1c
.RI "interface \fBpesg::xstoxt\fP"
.br
.ti -1c
.RI "interface \fBpesg::xttoxm\fP"
.br
.ti -1c
.RI "interface \fBpesg::xttoxs\fP"
.br
.ti -1c
.RI "interface \fBpesg::zmtozt\fP"
.br
.ti -1c
.RI "interface \fBpesg::zttozm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Routines to perform ESG regional grid mappings\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP
\fBDate:\fP
.RS 4
May 2020 
.RE
.PP

.PP
Definition in file \fBpesg\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
