.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pmat2.f90" 3 "Thu Feb 15 2024" "Version 1.12.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pmat2.f90 \- 
.PP
Routines dealing with the operations of banded matrices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBpmat2::avco\fP"
.br
.ti -1c
.RI "interface \fBpmat2::cad1b\fP"
.br
.ti -1c
.RI "interface \fBpmat2::cad2b\fP"
.br
.ti -1c
.RI "interface \fBpmat2::clipb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::csb1b\fP"
.br
.ti -1c
.RI "interface \fBpmat2::csb2b\fP"
.br
.ti -1c
.RI "interface \fBpmat2::dfco\fP"
.br
.ti -1c
.RI "interface \fBpmat2::dfco2\fP"
.br
.ti -1c
.RI "interface \fBpmat2::l1ubb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::l1ueb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::ldltb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::ldub\fP"
.br
.ti -1c
.RI "interface \fBpmat2::linbv\fP"
.br
.ti -1c
.RI "interface \fBpmat2::ltdlbv\fP"
.br
.ti -1c
.RI "module \fBpmat2\fP"
.br
.RI "\fIRoutines dealing with the operations of banded matrices\&. \fP"
.ti -1c
.RI "interface \fBpmat2::u1lbv\fP"
.br
.ti -1c
.RI "interface \fBpmat2::u1lbx\fP"
.br
.ti -1c
.RI "interface \fBpmat2::u1lby\fP"
.br
.ti -1c
.RI "interface \fBpmat2::u1lvb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::u1lxb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::u1lyb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::udlb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::udlbv\fP"
.br
.ti -1c
.RI "interface \fBpmat2::udlbx\fP"
.br
.ti -1c
.RI "interface \fBpmat2::udlby\fP"
.br
.ti -1c
.RI "interface \fBpmat2::udlvb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::udlxb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::udlyb\fP"
.br
.ti -1c
.RI "interface \fBpmat2::wrtb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Routines dealing with the operations of banded matrices\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, Tsukasa Fujita (JMA) 
.RE
.PP
\fBDate:\fP
.RS 4
1994/1999 
.RE
.PP

.PP
Definition in file \fBpmat2\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
