pmat::ldum
NAME
pmat::ldum -
SYNOPSIS
Private Member Functions
subroutine cldum (a, ipiv, d)
Perform L*D*U decomposition, with pivoting, of square matrix.
subroutine cldumf (a, ipiv, d, ff)
Perform l-d-u decomposition of square matrix a in place with pivoting.
subroutine dldum (a, ipiv, d)
Perform L*D*U decomposition, with pivoting, of square matrix.
subroutine dldumf (a, ipiv, d, ff)
Perform l-d-u decomposition of square matrix a in place with pivoting.
subroutine sldum (a, ipiv, d)
Perform L*D*U decomposition, with pivoting, of square matrix.
subroutine sldumf (a, ipiv, d, ff)
Perform l-d-u decomposition of square matrix a in place with pivoting.
Detailed Description
Definition at line 27 of file pmat.f90.
Member Function/Subroutine Documentation
subroutine pmat::ldum::cldum (complex(dpc), dimension(:,:), intent(inout)a, integer(spi), dimension(:), intent(out)ipiv, complex(dpc), intent(out)d) [private]
Perform L*D*U decomposition, with pivoting, of square matrix. Complex double precision version.
Parameters:
a input square matrix, output L,D,U factors
d determinant sign change indicator (+1 or -1)
ipiv vector of pivots
Author:
R. J. Purser
Definition at line 508 of file pmat.f90.
subroutine pmat::ldum::cldumf (complex(dpc), dimension(:,:), intent(inout)a, integer(spi), dimension(:), intent(out)ipiv, complex(dpc), intent(out)d, logical, intent(out)ff) [private]
Perform l-d-u decomposition of square matrix a in place with pivoting. Complex double precision version.
Parameters:
a square matrix to be factorized
ipiv vector encoding the pivoting sequence
d indicator for possible sign change of determinant
ff,: failure flag, set to .true. when determinant of a vanishes.
Author:
R. J. Purser
Definition at line 659 of file pmat.f90.
Referenced by pmat::cinvmtf(), pmat::cldum(), pmat::clinmmtf(), and pmat::clinmvtf().
subroutine pmat::ldum::dldum (real(dp), dimension(:,:), intent(inout)a, integer(spi), dimension(:), intent(out)ipiv, real(dp), intent(out)d) [private]
Perform L*D*U decomposition, with pivoting, of square matrix. Double precision version.
Parameters:
a input square matrix, output L,D,U factors
d determinant sign change indicator (+1 or -1)
ipiv vector of pivots
Author:
R. J. Purser
Definition at line 492 of file pmat.f90.
subroutine pmat::ldum::dldumf (real(dp), dimension(:,:), intent(inout)a, integer, dimension(:), intent(out)ipiv, real(dp), intent(out)d, logical(spi), intent(out)ff) [private]
Perform l-d-u decomposition of square matrix a in place with pivoting. Double precision version.
Parameters:
a square matrix to be factorized
ipiv vector encoding the pivoting sequence
d indicator for possible sign change of determinant
ff,: failure flag, set to .true. when determinant of a vanishes.
Author:
R. J. Purser
Definition at line 592 of file pmat.f90.
Referenced by pmat::dinvmtf(), pmat::dldum(), pmat::dlinmmtf(), and pmat::dlinmvtf().
subroutine pmat::ldum::sldum (real(sp), dimension(:,:), intent(inout)a, integer(spi), dimension(:), intent(out)ipiv, real(sp), intent(out)d) [private]
Perform L*D*U decomposition, with pivoting, of square matrix. Single precision version.
Parameters:
a input square matrix, output L,D,U factors
d determinant sign change indicator (+1 or -1)
ipiv vector of pivots
Author:
R. J. Purser
Definition at line 476 of file pmat.f90.
subroutine pmat::ldum::sldumf (real(sp), dimension(:,:), intent(inout)a, integer(spi), dimension(:), intent(out)ipiv, real(sp), intent(out)d, logical, intent(out)ff) [private]
Perform l-d-u decomposition of square matrix a in place with pivoting. Single precision version.
Parameters:
a square matrix to be factorized
ipiv vector encoding the pivoting sequence
d indicator for possible sign change of determinant
ff,: failure flag, set to .true. when determinant of a vanishes.
Author:
R. J. Purser
Definition at line 525 of file pmat.f90.
Referenced by pmat::sinvmtf(), pmat::sldum(), pmat::slinmmtf(), and pmat::slinmvtf().
Author
Generated automatically by Doxygen for grid_tools from the source code.