.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/machine.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/machine.f90 \- 
.PP
Holds machine dependent constants for global_cycle\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBmachine\fP"
.br
.RI "\fIHolds machine dependent constants for global_cycle\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Holds machine dependent constants for global_cycle\&. 


.PP
\fBAuthor:\fP
.RS 4
Mark Iredell NOAA/EMC 
.RE
.PP

.PP
Definition in file \fBmachine\&.f90\fP\&.
.SH "Data Type Documentation"
.PP 
.SH "module machine"
.PP 
Holds machine dependent constants for global_cycle\&. 


.PP
\fBAuthor:\fP
.RS 4
Mark Iredell NOAA/EMC 
.RE
.PP

.PP
Definition at line 7 of file machine\&.f90\&.
.PP
\fBData Fields:\fP
.RS 4
integer, parameter \fIkind_dbl_prec\fP Kind type for 8-byte float point variables\&. 
.br
.PP
integer, parameter \fIkind_io4\fP Kind type for 4-byte float point variables\&. 
.br
.PP
integer, parameter \fIkind_io8\fP Kind type for 8-byte float point variables\&. 
.br
.PP
integer, parameter \fIkind_sngl_prec\fP Kind type for 4-byte float point variables\&. 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
