.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/num_parthds.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/num_parthds.f90 \- 
.PP
Return number of threads\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnum_parthds\fP ()"
.br
.RI "\fIReturn the number of omp threads\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Return number of threads\&. 


.PP
\fBAuthor:\fP
.RS 4
Mark Iredell NCEP/EMC 
.RE
.PP

.PP
Definition in file \fBnum_parthds\&.f90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function num_parthds ()"

.PP
Return the number of omp threads\&. 
.PP
\fBReturns:\fP
.RS 4
num_parthds The number of threads\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
Mark Iredell NCEP/EMC 
.RE
.PP

.PP
Definition at line 9 of file num_parthds\&.f90\&.
.PP
Referenced by sfc_drv(), and sfcdrv()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
