.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/read_write_data.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "global_cycle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/global_cycle.fd/read_write_data.f90 \- 
.PP
Contains utility routines that read and write data\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBread_write_data::nsst_data\fP"
.br
.ti -1c
.RI "module \fBread_write_data\fP"
.br
.RI "\fIThis module contains routines that read and write data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains utility routines that read and write data\&. 


.PP
\fBAuthor:\fP
.RS 4
Xu Li, Hang Lei, George Gayno NOAA/EMC 
.RE
.PP

.PP
Definition in file \fBread_write_data\&.f90\fP\&.
.SH "Data Type Documentation"
.PP 
.SH "type read_write_data::nsst_data"
.PP 
Definition at line 16 of file read_write_data\&.f90\&.
.PP
\fBData Fields:\fP
.RS 4
real, dimension(:), allocatable \fIc_0\fP 
.br
.PP
real, dimension(:), allocatable \fIc_d\fP 
.br
.PP
real, dimension(:), allocatable \fId_conv\fP 
.br
.PP
real, dimension(:), allocatable \fIdt_cool\fP 
.br
.PP
real, dimension(:), allocatable \fIifd\fP 
.br
.PP
real, dimension(:), allocatable \fIqrain\fP 
.br
.PP
real, dimension(:), allocatable \fItfinc\fP 
.br
.PP
real, dimension(:), allocatable \fItref\fP 
.br
.PP
real, dimension(:), allocatable \fIw_0\fP 
.br
.PP
real, dimension(:), allocatable \fIw_d\fP 
.br
.PP
real, dimension(:), allocatable \fIxs\fP 
.br
.PP
real, dimension(:), allocatable \fIxt\fP 
.br
.PP
real, dimension(:), allocatable \fIxtts\fP 
.br
.PP
real, dimension(:), allocatable \fIxu\fP 
.br
.PP
real, dimension(:), allocatable \fIxv\fP 
.br
.PP
real, dimension(:), allocatable \fIxz\fP 
.br
.PP
real, dimension(:), allocatable \fIxzts\fP 
.br
.PP
real, dimension(:), allocatable \fIz_c\fP 
.br
.PP
real, dimension(:), allocatable \fIzm\fP 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for global_cycle from the source code\&.
