module_nwp
NAME
module_nwp -
This module defines FV3LAM and FVCOM forecast data structure and the method to read and write observations from and to those data structures.
SYNOPSIS
Data Types
type fcst_nwp
Private Member Functions
subroutine finish_nwp (this, itype, wcstart)
Finish and deallocate.
subroutine get_time_ind_nwp (this, filename, instr, outindex)
This subroutine searches the FVCOM 'Times' variable and returns the matching index.
subroutine initial_nwp (this, itype, wcstart)
This subroutine defines the number of variables and their names for each NWP data type.
subroutine list_initial_nwp (this)
This subroutine lists the setup for NWP data that was done by the initial_nwp subroutine.
subroutine read_nwp (this, filename, itype, wcstart, numlon, numlat, numtimes, time_to_get, mask, sst, ice, sfcT, iceT, sfcTl, zorl, hice, ybegin, yend)
This subroutine initializes arrays to receive the NWP data, and opens the file and gets the data.
Private Attributes
type(ncio) ncdata
Wrapper object for netCDF data file.
Detailed Description
This module defines FV3LAM and FVCOM forecast data structure and the method to read and write observations from and to those data structures.
It is used by ingest_FVCOM.f90.
This script is strongly based upon Eric James' (ESRL/GSL) work with HRRR/WRF to get FVCOM data into the model.
Author:
David Wright, University of Michigan and GLERL,
Date:
17 Aug 2020
Definition at line 15 of file module_nwp.f90.
Member Function/Subroutine Documentation
subroutine module_nwp::finish_nwp (class(fcst_nwp)this, character(len=6), intent(in)itype, character(len=4), intent(in)wcstart) [private]
Finish and deallocate.
Parameters:
this fcst_nwp object
itype either ' FVCOM' or 'FV3LAM'
wcstart either 'warm' or 'cold'.
Author:
David Wright, University of Michigan and GLERL
Definition at line 439 of file module_nwp.f90.
Referenced by module_nwp::fcst_nwp::finish().
subroutine module_nwp::get_time_ind_nwp (class(fcst_nwp)this, character(len=*), intent(in)filename, character(len=*), intent(in)instr, integer, intent(out)outindex) [private]
This subroutine searches the FVCOM 'Times' variable and returns the matching index.
Parameters:
this fcst_nwp ojbect
filename netcdf file name
instr string of requested time
outindex int index that matches instr
Author:
David Wright, University of Michigan and GLERL
Definition at line 487 of file module_nwp.f90.
Referenced by module_nwp::fcst_nwp::get_time_ind().
subroutine module_nwp::initial_nwp (class(fcst_nwp)this, character(len=6), intent(in)itype, character(len=4), intent(in)wcstart) [private]
This subroutine defines the number of variables and their names for each NWP data type. The indices of the variables are also defined for later reference.
Parameters:
this fcst_nwp object
itype either ' FVCOM' or 'FV3LAM'.
wcstart either 'warm' or 'cold'.
Author:
David Wright, University of Michigan and GLERL
Definition at line 88 of file module_nwp.f90.
Referenced by module_nwp::fcst_nwp::initial().
subroutine module_nwp::list_initial_nwp (class(fcst_nwp)this) [private]
This subroutine lists the setup for NWP data that was done by the initial_nwp subroutine.
Parameters:
this fcst_nwp object
Author:
David Wright, University of Michigan and GLERL
Definition at line 214 of file module_nwp.f90.
Referenced by module_nwp::fcst_nwp::list_initial().
subroutine module_nwp::read_nwp (class(fcst_nwp)this, character(len=*), intent(in)filename, character(len=6), intent(in)itype, character(len=4), intent(in)wcstart, integer, intent(inout)numlon, integer, intent(inout)numlat, integer, intent(inout)numtimes, integer, intent(in)time_to_get, real(r_single), dimension(:,:), intent(inout)mask, real(r_single), dimension(:,:), intent(inout)sst, real(r_single), dimension(:,:), intent(inout)ice, real(r_single), dimension(:,:), intent(inout)sfcT, real(r_single), dimension(:,:), intent(inout)iceT, real(r_single), dimension(:,:), intent(inout)sfcTl, real(r_single), dimension(:,:), intent(inout)zorl, real(r_single), dimension(:,:), intent(inout)hice, integer, intent(in)ybegin, integer, intent(in)yend) [private]
This subroutine initializes arrays to receive the NWP data, and opens the file and gets the data.
Parameters:
this fcst_nwp ojbect
filename netcdf file name
itype either ' FVCOM' or 'FV3LAM'
wcstart either 'warm' or 'cold'.
numlon number of grid points in x-direction
numlat number of grid poinst in y-direction
numtimes length of time dimension
time_to_get integer of time dimension to read in
mask Water points mask
sst Water surface temperature
ice Ice concentration (%)
sfcT Skin Temperature
iceT Ice Skin Temperature
sfcTl Skin Temperature in restart file
zorl Surface roughness length
hice Ice thickness
ybegin Start grid point in Y direction for the domain
yend End grid point in Y direction for the domain
Author:
David Wright, University of Michigan and GLERL
Definition at line 258 of file module_nwp.f90.
Referenced by module_nwp::fcst_nwp::read_n().
Field Documentation
type(ncio) module_nwp::ncdata [private]
Wrapper object for netCDF data file.
Definition at line 75 of file module_nwp.f90.
Author
Generated automatically by Doxygen for fvcom_tools from the source code.