.TH "pesg::zttozm" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::zttozm
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBzttozm\fP (a, zt, zm, ff)"
.br
.RI "Inverse of zmtozt\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file pesg\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pesg::zttozm::zttozm (real(dp), intent(in) a, real(dp), intent(in) zt, real(dp), intent(out) zm, logical, intent(out) ff)\fC [private]\fP"

.PP
Inverse of zmtozt\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Mapping parameter controlling grid line spacing profile 
.br
\fIzt\fP Scalar value of single gnomonic plane coordinate 
.br
\fIzm\fP Scalar value of single map plane coordinate 
.br
\fIff\fP Failure flag 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 299 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
