pesg
NAME
pesg - Suite of routines to perform the 2-parameter family of Extended Schmidt Gnomonic (ESG) regional grid mappings, and to optimize the the two parameters, A and K, of those mappings for a given rectangular domain's principal (median) semi-arcs with respect to a domain-averaged measure of distortion.
SYNOPSIS
Data Types
interface bestesg_geo
interface bestesg_map
interface gaulegh
interface get_edges
interface get_meanq
interface get_qofv
interface get_qx
interface gtoxm_ak_dd
interface gtoxm_ak_rr
interface guessak_geo
interface guessak_map
interface hgrid_ak
interface hgrid_ak_dc
interface hgrid_ak_dd
interface hgrid_ak_rc
interface hgrid_ak_rr
interface xctoxm_ak
interface xctoxs
interface xmtog_ak_dd
interface xmtog_ak_rr
interface xmtoxc_ak
interface xmtoxt
interface xstoxc
interface xstoxt
interface xttoxm
interface xttoxs
interface zmtozt
interface zttozm
Functions/Subroutines
subroutine, public bestesg_geo (lam, garcx, garcy, a, k, marcx, marcy, q, ff)
Get the best Extended Schmidt Gnomonic parameter, (a,k), for the given geographical half-spans, garcx and garcy, as well as the corresponding map-space half-spans, garcx and garcy (in degrees) and the quality diagnostic, Q(lam) for this optimal parameter choice.
subroutine, public bestesg_map (lam, marcx, marcy, a, k, garcx, garcy, q, ff)
Get the best Extended Schmidt Gnomonic parameter, (a,k), for the given map-coordinate half-spans, marcx and marcy, as well as the corresponding geographical half-spans, garcx and garcy (in degrees) and the quality diagnostic, Q(lam) for this optimal parameter choice.
subroutine gaulegh (m, x, w)
This Gauss-Legendre quadrature integrates exactly any even polynomial up to degree m*4-2 in the half-interval [0,1].
subroutine, public get_edges (arcx, arcy, edgex, edgey)
For angles (degrees) of the arcs spanning the halfwidths between the region's center and its x and y edges, get the two cartesian vectors that represent the locations of these edge midpoints in the positive x and y directions.
subroutine get_meanqd (ngh, lam, xg, wg, ak, ma, q, qdak, qdma, ga, gadak, gadma, ff)
For a parameter vector, ak and a map-space domain-parameter vector, ma, return the lambda-parameterized quality diagnostic, Q, and the geographic domain-parameter vector ga.
subroutine get_meanqs (n, ngh, lam, xg, wg, aks, mas, qs, ff)
Like getmeanqd, except for n different values, aks, of ak and n different values, mas of ma, and without any of the derivatives.
subroutine get_qofv (lam, v1, v2, v3, v4, q)
The quadratic quantity Q depends linearly on v1 and v4 (which are already quadratic diagnostics of EL) and quadratically on v2 and v3 (which are linear diagnostics of EL).
subroutine get_qofvd (lam, v2, v3, v1d, v2d, v3d, v4d, qd)
Like get_qofv, but for (only) the 2-vector derivatives of Q.
subroutine get_qsofvs (n, lam, v1s, v2s, v3s, v4s, qs)
General util to convert value.
subroutine get_qx (j0, v1, v2, v3, v4)
From a jacobian matrix, j0, get a sufficient set of v.
subroutine get_qxd (j0, j0d, v1, v2, v3, v4, v1d, v2d, v3d, v4d)
From a jacobian matrix, j0, and its derivative, j0d, get a sufficient set of v.
subroutine gtoxm_ak_dd_g (A, K, pdlat, pdlon, pdazi, delx, dely, dlat, dlon, xm, ff)
Like gtoxm_ak_rr_g, except lat, lon, azimuth, are expressed in degrees.
subroutine gtoxm_ak_dd_m (A, K, pdlat, pdlon, pdazi, dlat, dlon, xm, ff)
Like gtoxm_ak_rr_m, except lat, lon, azimuth, are expressed in degrees.
subroutine gtoxm_ak_rr_g (A, K, plat, plon, pazi, delx, dely, lat, lon, xm, ff)
Given the map specification (angles in radians), the grid spacing (in map-space units) and the sample lat-lon (in radian), return the the image in map space in a 2-vector in grid units.
subroutine gtoxm_ak_rr_m (A, K, plat, plon, pazi, lat, lon, xm, ff)
Given the map specification (angles in radians), the grid spacing (in map-space units) and the sample lat-lon (in radian), return the the image in map space in a 2-vector in grid units.
subroutine guessak_geo (asp, arc, ak)
Given an aspect ratio, asp<=1, and major semi-axis, arc, in geographical (degree) units measured along the rectangle's median, return a first guess for the parameter vector, ak, approximately optimal for the domain of the given dimensions.
subroutine guessak_map (asp, tmarcx, ak)
Given an aspect ratio, asp<=1, and major semi-axis, arc, in map-space nondimensional units, return a first guess for the parameter vector, ak, approximately optimal for the domain of the given dimensions.
subroutine, public hgrid_ak (lx, ly, nx, ny, a, k, plat, plon, pazi, re, delxre, delyre, glat, glon, garea, ff)
Like hgrid_ak_rr_c except the argument list includes the earth radius, re, and this is used to express the map-space grid increments in the dimensional units, delxre, delyre on entry, and to express the grid cell areas, garea, in dimensional units upon return.
subroutine hgrid_ak_c (lx, ly, nx, ny, a, k, plat, plon, pazi, re, delxre, delyre, glat, glon, garea, dx, dy, dangle_dx, dangle_dy, ff)
Like hgrid_ak_rr_c except the argument list includes the earth radius, re, and this is used to express the map-space grid increments in the dimensional units, delxre, delyre on entry, and to express the grid cell areas, garea, and the x- and y- grid steps, dx and dy, in dimensional units upon return.
subroutine, public hgrid_ak_dc (lx, ly, nx, ny, a, k, pdlat, pdlon, pdazi, delx, dely, xc, xcd, garea, ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (pdlat,pdlon) and twisted about this center by an azimuth angle of pdazi counterclockwise (these angles in degrees).
subroutine, public hgrid_ak_dd (lx, ly, nx, ny, a, k, pdlat, pdlon, pdazi, delx, dely, gdlat, gdlon, garea, ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (pdlat,pdlon) and twisted about this center by an azimuth angle of pdazi counterclockwise (these angles in degrees).
subroutine hgrid_ak_dd_c (lx, ly, nx, ny, a, k, pdlat, pdlon, pdazi, delx, dely, gdlat, gdlon, garea, dx, dy, dangle_dx, dangle_dy, ff)
Like hgrid_ak_rr_c, except all the angle arguments (but not delx,dely) are in degrees instead of radians.
subroutine, public hgrid_ak_rc (lx, ly, nx, ny, A, K, plat, plon, pazi, delx, dely, xc, xcd, garea, ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians).
subroutine, public hgrid_ak_rr (lx, ly, nx, ny, A, K, plat, plon, pazi, delx, dely, glat, glon, garea, ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians).
subroutine hgrid_ak_rr_c (lx, ly, nx, ny, a, k, plat, plon, pazi, delx, dely, glat, glon, garea, dx, dy, angle_dx, angle_dy, ff)
Use a and k as the parameters of an extended Schmidt-transformed gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians).
subroutine, public xctoxm_ak (a, k, xc, xm, ff)
Inverse mapping of xmtoxc_ak.
subroutine xctoxs (xc, xs)
Inverse of xstoxc.
subroutine xmtog_ak_dd_g (A, K, pdlat, pdlon, pdazi, delx, dely, xm, dlat, dlon, ff)
Like xmtog_ak_rr_g, except lat, lon, azimuth, are expressed in degrees.
subroutine xmtog_ak_dd_m (A, K, pdlat, pdlon, pdazi, xm, dlat, dlon, ff)
Like xmtog_ak_rr_m, except lat, lon, azimuth, are expressed in degrees.
subroutine xmtog_ak_rr_g (A, K, plat, plon, pazi, delx, dely, xm, lat, lon, ff)
For an ESG map with parameters, (A,K), and geographical orientation, given by plon,plat,pazi (radians), and given a point in grid-space units as the 2-vector, xm, return the geographical coordinates, lat, lon, (radians) of this point.
subroutine xmtog_ak_rr_m (A, K, plat, plon, pazi, xm, lat, lon, ff)
Given the ESG map specified by parameters (A,K) and geographical center and orientation, plat,plon,pazi (radians), and a position, in map-space coordinates given by the 2-vector, xm, return the geographical coordinates, lat and lon (radians).
subroutine, public xmtoxc_ak (a, k, xm, xc, xcd, ff)
Assuming the A-K parameterization of the Extended Schmidt-transformed Gnomonic (ESG) mapping, and given a map-space 2-vector, xm, find the corresponding cartesian unit 3-vector and its derivative wrt xm, jacobian matrix, xcd.
subroutine xmtoxc_vak (ak, xm, xc, xcd, ff)
Assuming the vector AK parameterization of the Extended Schmidt-transformed Gnomonic (ESG) mapping with parameter vector, and given a map-space 2-vector, xm, find the corresponding cartesian unit 3-vector and its derivative wrt xm, the Jacobian matrix, xcd.
subroutine xmtoxc_vak1 (ak, xm, xc, xcd, xc1, xcd1, ff)
Like xmtoxc_vak, _ak, but also return derivatives wrt ak.
subroutine xmtoxt (a, xm, xt, xtd, ff)
Like zmtozt, but for 2-vector xm and xt, and 2*2 diagonal Jacobian xtd.
subroutine xmtoxt1 (a, xm, xt, xtd, xt1, xtd1, ff)
Like zmtozt1, but for 2-vector xm and xt, and 2*2 diagonal Jacobian xtd Also, the derivatives, wrt a, of these quantities.
subroutine xstoxc (xs, xc, xcd)
Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar.
subroutine xstoxc1 (xs, xc, xcd, xcdd)
Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar.
subroutine xstoxt (k, xs, xt, ff)
Inverse of xttoxs.
subroutine xttoxm (a, xt, xm, ff)
Inverse of xmtoxt.
subroutine xttoxs (k, xt, xs, xsd, ff)
Scaled gnomonic plane xt to standard stereographic plane xs.
subroutine xttoxs1 (k, xt, xs, xsd, xsdd, xs1, xsd1, ff)
Like xttoxs, but also, return the derivatives, wrt K, of xs and xsd.
subroutine zmtozt (a, zm, zt, ztd, ff)
Evaluate the function, zt = tan(sqrt(A)*z)/sqrt(A), and its derivative, ztd, for positive and negative A and for the limiting case, A --> 0.
subroutine zmtozt1 (a, zm, zt, ztd, zt1, ztd1, ff)
Like zmtozt, but also, get the derivative with respect to a, zt1 of zt, and ztd1 of ztd.
subroutine zttozm (a, zt, zm, ff)
Inverse of zmtozt.
Detailed Description
Suite of routines to perform the 2-parameter family of Extended Schmidt Gnomonic (ESG) regional grid mappings, and to optimize the the two parameters, A and K, of those mappings for a given rectangular domain's principal (median) semi-arcs with respect to a domain-averaged measure of distortion.
This criterion is itself endowed with a parameter, lam (for 'lambda' in [0,1) ) which gives weight to additional weight areal inhomogeneities instead of treating all distortion components equally.
Author:
R. J. Purser
Function/Subroutine Documentation
subroutine, public pesg::bestesg_geo (real(dp), intent(in) lam, real(dp), intent(in) garcx, real(dp), intent(in) garcy, real(dp), intent(out) a, real(dp), intent(out) k, real(dp), intent(out) marcx, real(dp), intent(out) marcy, real(dp), intent(out) q, logical, intent(out) ff)
Get the best Extended Schmidt Gnomonic parameter, (a,k), for the given geographical half-spans, garcx and garcy, as well as the corresponding map-space half-spans, garcx and garcy (in degrees) and the quality diagnostic, Q(lam) for this optimal parameter choice. If this process fails for any reason, the failure is alerted by a raised flag, FF, and the other output arguments must then be taken to be meaningless.
The diagnostic Q measures the variance over the domain of a local measure of grid distortion. A logarithmic measure of local grid deformation is give by L=log(J^t.J)/2, where J is the mapping Jacobian matrix, dX/dx, where X is the cartesian unit 3-vector representation of the image of the mapping of the map-coordinate 2-vector, x. The Frobenius squared-norm, Trace(L*L), of L is the basis for the simplest (lam=0) definition of the variance of L, but (Trace(L))**2 is another. Here, we weight both contributions, by lam and (1-lam) respectively, with 0 <= lam <1, to compute the variance Q(lam,a,k), and search for the (a,k) that minimizes this Q.
The domain averages are computed by double Gauss-Legendre quadrature (i.e., in both the x and y directions), but restricted to a mere quadrant of the domain (since bilateral symmetry pertains across both domain medians, yielding a domain mean L that is strictly diagonal.
Parameters:
lam
garcx map-space half-spans
garcy map-space half-spans
a Extended Schmidt Gnomonic parameter
k Extended Schmidt Gnomonic parameter
marcx
marcy
q
ff failure flag
Author:
R. J. Purser
Definition at line 902 of file pesg.f90.
References pietc::ms18, pietc::ms36, pietc::ms54, pietc::ms72, pietc::o5, pietc::s18, pietc::s36, pietc::s54, pietc::s72, and pietc::u5.
subroutine, public pesg::bestesg_map (real(dp), intent(in) lam, real(dp), intent(in) marcx, real(dp), intent(in) marcy, real(dp), intent(out) a, real(dp), intent(out) k, real(dp), intent(out) garcx, real(dp), intent(out) garcy, real(dp), intent(out) q, logical, intent(out) ff)
Get the best Extended Schmidt Gnomonic parameter, (a,k), for the given map-coordinate half-spans, marcx and marcy, as well as the corresponding geographical half-spans, garcx and garcy (in degrees) and the quality diagnostic, Q(lam) for this optimal parameter choice. If this process fails for any reason, the failure is alerted by a raised flag, FF, and the other output arguments must then be taken to be meaningless.
The diagnostic Q measures the variance over the domain of a local measure of grid distortion. A logarithmic measure of local grid deformation is give by L=log(J^t.J)/2, where J is the mapping Jacobian matrix, dX/dx, where X is the cartesian unit 3-vector representation of the image of the mapping of the map-coordinate 2-vector, x. The Frobenius squared-norm, Trace(L*L), of L is the basis for the simplest (lam=0) definition of the variance of L, but (Trace(L))**2 is another. Here, we weight both contributions, by lam and (1-lam) respectively, with 0 <= lam <1, to compute the variance Q(lam,a,k), and search for the (a,k) that minimizes this Q.
The domain averages are computed by double Gauss-Legendre quadrature (i.e., in both the x and y directions), but restricted to a mere quadrant of the domain (since bilateral symmetry pertains across both domain medians, yielding a domain mean L that is strictly diagonal.
Parameters:
lam
marcx map-coordinate half-spans
marcy map-coordinate half-spans
a Extended Schmidt Gnomonic parameter
k Extended Schmidt Gnomonic parameter
garcx geographical half-spans
garcy geographical half-spans
q
ff failure flag
Author:
R. J. Purser
Definition at line 1072 of file pesg.f90.
References pietc::ms18, pietc::ms36, pietc::ms54, pietc::ms72, pietc::o5, pietc::s18, pietc::s36, pietc::s54, pietc::s72, and pietc::u5.
subroutine pesg::gaulegh (integer(spi), intent(in) m, real(dp), dimension(m), intent(out) x, real(dp), dimension(m), intent(out) w) [private]
This Gauss-Legendre quadrature integrates exactly any even polynomial up to degree m*4-2 in the half-interval [0,1]. This code is liberally adapted from the algorithm given in Press et al., Numerical Recipes.
Parameters:
m number of nodes in half-interval
x nodes and weights
w nodes and weights
Author:
R. J. Purser
Definition at line 1851 of file pesg.f90.
References pietc::pih, pietc::u0, pietc::u1, and pietc::u2.
subroutine, public pesg::get_edges (real(dp), intent(in) arcx, real(dp), intent(in) arcy, real(dp), dimension(3), intent(out) edgex, real(dp), dimension(3), intent(out) edgey)
For angles (degrees) of the arcs spanning the halfwidths between the region's center and its x and y edges, get the two cartesian vectors that represent the locations of these edge midpoints in the positive x and y directions.
Parameters:
arcx Center-relative angle (degrees) of edge midpoint in +x
arcy Center-relative angle (degrees) of edge midpoint in +y
edgex region's +x edge midpoint as cartesian unit 3-vector
edgey region's +y edge midpoint as cartesian unit 3-vector
Author:
R. J. Purser
Definition at line 488 of file pesg.f90.
References pietc::dtor, and pietc::u0.
subroutine pesg::get_meanqd (integer(spi), intent(in) ngh, real(dp), intent(in) lam, real(dp), dimension(ngh), intent(in) xg, real(dp), dimension(ngh), intent(in) wg, real(dp), dimension(2), intent(in) ak, real(dp), dimension(2), intent(in) ma, real(dp), intent(out) q, real(dp), dimension(2), intent(out) qdak, real(dp), dimension(2), intent(out) qdma, real(dp), dimension(2), intent(out) ga, real(dp), dimension(2,2), intent(out) gadak, real(dp), dimension(2,2), intent(out) gadma, logical, intent(out) ff)
For a parameter vector, ak and a map-space domain-parameter vector, ma, return the lambda-parameterized quality diagnostic, Q, and the geographic domain-parameter vector ga. Lambda is given by lam <1. Also, return the derivatives, qdak and qdma, of Q wrt ak and ma, and the derivatives gadak and gadma, of ga wrt ak and ma.
The domain averages of Q are accurately computed by bi-Gauss-Legendre quadrature over the positive quadrant of the domain (exploiting the symmetry) of the four constituent terms, v1, v2, v3, v4, from which the mean Q is computed using a quadratic formula of these constituents. The number of Gauss points in eaxh half-interval is ngh, and the nodes themselves are, in proportion to the half-interval, at xg. the normalized gauss weights are wg.
If a failure occurs, colmputations cease immediately and a failure flag, FF, is raised on return.
Parameters:
ngh
lam Lambda
xg
wg
ak parameter vector
ma map-space domain-parameter vector
q lambda-parameterized quality diagnostic
qdak derivatives value
qdma derivatives value
ga geographic domain-parameter vector
gadak
gadma
ff error flag
Author:
R. J. Purser
Definition at line 603 of file pesg.f90.
References pietc::rtod, and pietc::u0.
subroutine pesg::get_meanqs (integer(spi), intent(in) n, integer(spi), intent(in) ngh, real(dp), intent(in) lam, real(dp), dimension(ngh), intent(in) xg, real(dp), dimension(ngh), intent(in) wg, real(dp), dimension(2,n), intent(in) aks, real(dp), dimension(2,n), intent(in) mas, real(dp), dimension(n), intent(out) qs, logical, intent(out) ff) [private]
Like getmeanqd, except for n different values, aks, of ak and n different values, mas of ma, and without any of the derivatives.
Parameters:
n
ngh
lam
xg
wg
aks
mas
qs
ff
Author:
R. J. Purser
Definition at line 681 of file pesg.f90.
References pietc::u0.
subroutine pesg::get_qofv (real(dp), intent(in) lam, real(dp), intent(in) v1, real(dp), intent(in) v2, real(dp), intent(in) v3, real(dp), intent(in) v4, real(dp), intent(out) q) [private]
The quadratic quantity Q depends linearly on v1 and v4 (which are already quadratic diagnostics of EL) and quadratically on v2 and v3 (which are linear diagnostics of EL). EL = (1/2)log(G), where G=J^T.J, J the jacobian.
Parameters:
lam
v1 quadratic diagnostics of EL
v2 linear diagnostics of EL
v3 linear diagnostics of EL
v4 quadratic diagnostics of EL
q quadratic quantity
Author:
R. J. Purser
Definition at line 728 of file pesg.f90.
References pietc::u1.
subroutine pesg::get_qofvd (real(dp), intent(in) lam, real(dp), intent(in) v2, real(dp), intent(in) v3, real(dp), dimension(2), intent(in) v1d, real(dp), dimension(2), intent(in) v2d, real(dp), dimension(2), intent(in) v3d, real(dp), dimension(2), intent(in) v4d, real(dp), dimension(2), intent(out) qd) [private]
Like get_qofv, but for (only) the 2-vector derivatives of Q. Note that the quadratic diagnostics v1 and v4 do not participate in this formula.
Parameters:
lam
v2
v3
v1d
v2d
v3d
v4d
qd
Author:
R. J. Purser
Definition at line 750 of file pesg.f90.
References pietc::u1, and pietc::u2.
subroutine pesg::get_qsofvs (integer(spi), intent(in) n, real(dp), intent(in) lam, real(dp), dimension(n), intent(in) v1s, real(dp), dimension(n), intent(in) v2s, real(dp), dimension(n), intent(in) v3s, real(dp), dimension(n), intent(in) v4s, real(dp), dimension(n), intent(out) qs) [private]
General util to convert value.
Parameters:
n
lam
v1s
v2s
v3s
v4s
qs
Author:
R. J. Purser
Definition at line 770 of file pesg.f90.
References pietc::u1.
subroutine pesg::get_qx (real(dp), dimension(3,2), intent(in) j0, real(dp), intent(out) v1, real(dp), intent(out) v2, real(dp), intent(out) v3, real(dp), intent(out) v4) [private]
From a jacobian matrix, j0, get a sufficient set of v. . diagnostics such that, from averages of these v, we can later compute the collective variance of Q(lam) that they imply for any choice of the 'lambda' parameter, lam. Note that v1 and v4 are quadratic diagnostics of EL, while v2 and v3 are linear.
Parameters:
j0 jacobian matrix
v1 quadratic diagnostics of EL
v2 linear diagnostics of EL
v3 linear diagnostics of EL
v4 quadratic diagnostics of EL
Author:
R. J. Purser
Definition at line 511 of file pesg.f90.
References pietc::o2, and pietc::u2.
subroutine pesg::get_qxd (real(dp), dimension(3,2), intent(in) j0, real(dp), dimension(3,2,2), intent(in) j0d, real(dp), intent(out) v1, real(dp), intent(out) v2, real(dp), intent(out) v3, real(dp), intent(out) v4, real(dp), dimension(2), intent(out) v1d, real(dp), dimension(2), intent(out) v2d, real(dp), dimension(2), intent(out) v3d, real(dp), dimension(2), intent(out) v4d)
From a jacobian matrix, j0, and its derivative, j0d, get a sufficient set of v. . diagnostics such that, from average of these diagnostics, we can later compute the collective variance of Q and its derivative.
Parameters:
j0 jacobian matrix
j0d derivative of j0
v1
v2
v3
v4
v1d
v2d
v3d
v4d
Author:
R. J. Purser
Definition at line 541 of file pesg.f90.
References pietc::o2, pietc::u0, and pietc::u2.
subroutine pesg::gtoxm_ak_dd_g (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), intent(in) dlat, real(dp), intent(in) dlon, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff) [private]
Like gtoxm_ak_rr_g, except lat, lon, azimuth, are expressed in degrees.
Parameters:
a parameter of the ESG mapping
k parameter of the ESG mapping
pdlat degrees latitude defining mapping projection center
pdlon degrees longitude defining mapping projection center
pdazi Azimuth of mapping orientation at its center
delx central x-spacing of the grid in radians
dely central y-spacing of the grid in radians
dlat degrees latitude of a point to be mapped
dlon degrees longitude of a point to be mapped
xm 2-vector image of the point in center-relative grid units
ff failure flag
Author:
R. J. Purser
Definition at line 1983 of file pesg.f90.
References pietc::dtor, and gtoxm_ak_rr_g().
subroutine pesg::gtoxm_ak_dd_m (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) dlat, real(dp), intent(in) dlon, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff) [private]
Like gtoxm_ak_rr_m, except lat, lon, azimuth, are expressed in degrees.
Parameters:
a parameter of the ESG mapping
k parameter of the ESG mapping
pdlat degrees latitude defining mapping center
pdlon degrees longitude defining mapping center
pdazi Azimuth of mapping orientation at its center
dlat degrees latitude of point to be mapped
dlon degrees longitude of point to be mapped
xm 2-vector center-relative map space image of the point
ff failure flag
Author:
R. J. Purser
Definition at line 1954 of file pesg.f90.
References pietc::dtor, and gtoxm_ak_rr_m().
subroutine pesg::gtoxm_ak_rr_g (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), intent(in) lat, real(dp), intent(in) lon, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff)
Given the map specification (angles in radians), the grid spacing (in map-space units) and the sample lat-lon (in radian), return the the image in map space in a 2-vector in grid units. If the transformation is invalid, return a .true. failure flag.
Parameters:
a parameter of the ESG mapping
k parameter of the ESG mapping
plat radians latitude defining mapping projection center
plon radians longitude defining mapping projection center
pazi Azimuth of mapping orientation at its center
delx central x-spacing of the grid in radians
dely central y-spacing of the grid in radians
lat radians latitude of a point to be mapped
lon radians longitude of a point to be mapped
xm 2-vector map space image in center-relative grid units
ff failure flag
Author:
R. J. Purser
Definition at line 1932 of file pesg.f90.
References gtoxm_ak_rr_m().
Referenced by gtoxm_ak_dd_g().
subroutine pesg::gtoxm_ak_rr_m (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) lat, real(dp), intent(in) lon, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff) [private]
Given the map specification (angles in radians), the grid spacing (in map-space units) and the sample lat-lon (in radian), return the the image in map space in a 2-vector in grid units. If the transformation is invalid, return a .true. failure flag.
Parameters:
a parameters of an ESG mapping
k parameters of an ESG mapping
plat radians latitude defining mapping projection center
plon radians longitude defining mapping projection center
pazi Aximuth of mapping orientation at its center
lat radians latitude of a point to be mapped
lon radians longitude of a point to be mapped
xm 2-vector center-relative map-space image of mapped point
ff failure flag
Author:
R. J. Purser
Definition at line 1887 of file pesg.f90.
References pietc::u0, and pietc::u1.
Referenced by gtoxm_ak_dd_m(), and gtoxm_ak_rr_g().
subroutine pesg::guessak_geo (real(dp), intent(in) asp, real(dp), intent(in) arc, real(dp), dimension(2), intent(out) ak) [private]
Given an aspect ratio, asp<=1, and major semi-axis, arc, in geographical (degree) units measured along the rectangle's median, return a first guess for the parameter vector, ak, approximately optimal for the domain of the given dimensions.
Parameters:
asp aspect ratio of intended domain
arc major semi-axis angle in degrees for intended domain
ak first guess of the parameter vector
Author:
R. J. Purser
Definition at line 808 of file pesg.f90.
subroutine pesg::guessak_map (real(dp), intent(in) asp, real(dp), intent(in) tmarcx, real(dp), dimension(2), intent(out) ak) [private]
Given an aspect ratio, asp<=1, and major semi-axis, arc, in map-space nondimensional units, return a first guess for the parameter vector, ak, approximately optimal for the domain of the given dimensions.
Parameters:
asp aspect ratio
tmarcx
ak first guess for the parameter vector
Author:
R. J. Purser
Definition at line 790 of file pesg.f90.
References pietc::rtod.
subroutine, public pesg::hgrid_ak (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) a, real(dp), intent(in) k, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) re, real(dp), intent(in) delxre, real(dp), intent(in) delyre, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glat, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glon, real(dp), dimension(lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, logical, intent(out) ff)
Like hgrid_ak_rr_c except the argument list includes the earth radius, re, and this is used to express the map-space grid increments in the dimensional units, delxre, delyre on entry, and to express the grid cell areas, garea, in dimensional units upon return. The gridded lats and lons, glat and glon, remain in radians.
Parameters:
lx center-relative x grid index for left edge of the domain
ly center-relative y grid index for lower edge of the domain
nx numbers of the grid spaces in x
ny numbers of the grid spaces in y
a parameters of an ESG mapping
k parameters of an ESG mapping
plat radians latitude of the projection center of the mapping
plon radians longitude of the projection center of the mapping
pazi Azimuth of map orientation at its center
re earth radius
delxre map-space grid increments in the dimensional units
delyre map-space grid increments in the dimensional units
glat grid points for latitude
glon grid points for longitude
garea array of grid-cell areas in dimensional units
ff failure flag
Author:
R. J. Purser
Definition at line 1765 of file pesg.f90.
subroutine pesg::hgrid_ak_c (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) a, real(dp), intent(in) k, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) re, real(dp), intent(in) delxre, real(dp), intent(in) delyre, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glat, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glon, real(dp), dimension(lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, real(dp), dimension(lx:lx+nx-1,ly:ly+ny ), intent(out) dx, real(dp), dimension(lx:lx+nx ,ly:ly+ny-1), intent(out) dy, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) dangle_dx, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) dangle_dy, logical, intent(out) ff) [private]
Like hgrid_ak_rr_c except the argument list includes the earth radius, re, and this is used to express the map-space grid increments in the dimensional units, delxre, delyre on entry, and to express the grid cell areas, garea, and the x- and y- grid steps, dx and dy, in dimensional units upon return. The gridded lats and lons, glat and glon, remain in radians. Also, in order for the argument list to remain compatible with an earlier version of this routine, the relative rotations of the steps, dangle_dx and dangle_dy, are returned as degrees instead of radians (all other angles in the argument list, i.e., plat,plon,pazi,glat,glon, remain radians).
Parameters:
lx center-relative x grid index for left edge of the domain
ly center-relative y grid index for lower edge of the domain
nx number of grid spaces in x
ny number of grid spaces in y
a Extended Schmidt Gnomonic parameter
k Extended Schmidt Gnomonic parameter
plat latitude of projection center of the mapping (radians)
plon longitude of projection center of the mapping (radians)
pazi Azimuth of map orientation at its center (radians)
re earth radius in dimensional length units
delxre map-space grid increments in the dimensional units
delyre map-space grid increments in the dimensional units
glat gridded lats (radians)
glon gridded lons (radians)
garea grid cell areas in dimensional units
dx x- grid steps in dimensional units
dy y- grid steps in dimensional units
dangle_dx azimuth rotations of the steps dx (in degrees)
dangle_dy azimuth rotations of the steps dy (in degrees)
ff failure flag
Author:
R. J. Purser
Definition at line 1817 of file pesg.f90.
References hgrid_ak_rr_c(), and pietc::rtod.
subroutine, public pesg::hgrid_ak_dc (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) a, real(dp), intent(in) k, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(3, lx:lx+nx ,ly:ly+ny ), intent(out) xc, real(dp), dimension(3,2,lx:lx+nx ,ly:ly+ny ), intent(out) xcd, real(dp), dimension( lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, logical, intent(out) ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (pdlat,pdlon) and twisted about this center by an azimuth angle of pdazi counterclockwise (these angles in degrees). Like hgrid_ak_rx, return the grid points' cartesians xc and Jacobian matrices, xcd. Garea, the area of each grid cell, is also returned as in hgrid_ak_rx, and a failure flag, ff, raised when a failure occurs anywhere in these calculations.
Parameters:
lx center-relative x grid index for left edge of the domain
ly center-relative y grid index for lower edge of the domain
nx numbers of the grid spaces in x
ny numbers of the grid spaces in y
a parameters of an ESG mapping
k parameters of an ESG mapping
pdlat degrees latitude of the projection center of the mapping
pdlon degrees longitude of the projection center of the mapping
pdazi azimuth of the orientation of the mapping at its center
delx central x-spacing of the grid in radians
dely central y-spacing of the grid in radians
xc grid points' earth-centered unit cartesians
xcd Jacobian matrices, d(xc)/d(xm)
garea array of grid-cell areas (steradians)
ff failure flag
Author:
R. J. Purser
Definition at line 1723 of file pesg.f90.
References pietc::dtor.
subroutine, public pesg::hgrid_ak_dd (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) a, real(dp), intent(in) k, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) gdlat, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) gdlon, real(dp), dimension(lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, logical, intent(out) ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (pdlat,pdlon) and twisted about this center by an azimuth angle of pdazi counterclockwise (these angles in degrees). Like hgrid_ak_rr, return the grid points' lats and lons, except that here the angles are returned in degrees. Garea, the area of each grid cell, is returned as in hgrid_ak_rr, and a failure flag, ff, raised when a failure occurs anywhere in these calculations.
Parameters:
lx center-relative x grid index for left edge of the domain
ly center-relative y grid index for lower edge of the domain
nx number of the grid spaces in x
ny number of the grid spaces in y
a parameter of an ESG mapping
k parameter of an ESG mapping
pdlat degrees latitude of the projection center of mapping
pdlon degrees longitude of the projection center of mapping
pdazi degrees azimuth of orientation of mapping at its center
delx central x-spacing of the grid (in radians)
dely central y-spacing of the grid (in radians)
gdlat array of grid point latitudes (in degrees)
gdlon array of grid point longitudes (in dgrees)
garea array of grid cell areas (in steradians)
ff failure flag
Author:
R. J. Purser
Definition at line 1629 of file pesg.f90.
References pietc::dtor, and pietc::rtod.
subroutine pesg::hgrid_ak_dd_c (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) a, real(dp), intent(in) k, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) gdlat, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) gdlon, real(dp), dimension(lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, real(dp), dimension(lx:lx+nx-1,ly:ly+ny ), intent(out) dx, real(dp), dimension(lx:lx+nx ,ly:ly+ny-1), intent(out) dy, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) dangle_dx, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) dangle_dy, logical, intent(out) ff) [private]
Like hgrid_ak_rr_c, except all the angle arguments (but not delx,dely) are in degrees instead of radians.
Parameters:
lx center-relative x grid index for left edge of the domain
ly center-relative y grid index for lower edge of the domain
nx numbers of the grid spaces in x
ny numbers of the grid spaces in y
a parameters of an ESG mapping
k parameters of an ESG mapping
pdlat latitude defining projection center of the mapping
pdlon longitude defining projection center of the mapping
pdazi azimuth of the orientation of the mapping at its center
delx central x-spacing of the grid (in radians)
dely central y-spacing of the grid (in radians)
gdlat array of grid point degree-latitudes
gdlon array of grid point degree-longitudes
garea array of grid-cell areas (steradians)
dx step sizes of the grid-cell edges in x (earth radius=1 unit)
dy step sizes of the grid-cell edges in y (earth radius=1 unit)
dangle_dx azimuth rotation of the x grid steps, dx (degrees)
dangle_dy azimuth rotation of the y grid steps, dy (degrees)
ff failure flag
Author:
R. J. Purser
Definition at line 1672 of file pesg.f90.
References pietc::dtor, hgrid_ak_rr_c(), and pietc::rtod.
subroutine, public pesg::hgrid_ak_rc (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(3, lx:lx+nx ,ly:ly+ny ), intent(out) xc, real(dp), dimension(3,2,lx:lx+nx ,ly:ly+ny ), intent(out) xcd, real(dp), dimension( lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, logical, intent(out) ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians). Assume the radius of the earth is unity, and using the central mapping point as the coordinate origin, set up the grid with central x-spacing delx and y-spacing dely. The grid index location of the left-lower corner of the domain is (lx,ly) (typically both NEGATIVE). The numbers of the grid spaces in x and y directions are nx and ny. (Note that, for a centered rectangular grid lx and ly are negative and, in magnitude, half the values of nx and ny respectively.) Return the unit cartesian vectors xc of the grid points and their jacobian matrices xcd wrt the map coordinates, and return a rectangular array, garea, of dimensions nx-1 by ny-1, that contains the areas of each of the grid cells
If all goes well, return a lowered failure flag, ff=.false. . But if, for some reason, it is not possible to complete this task, return the raised failure flag, ff=.TRUE. .
Parameters:
lx center-relative x grid index for left edge of the domain
ly center-relative y grid index for lower edge of the domain
nx numbers of the grid spaces in x
ny numbers of the grid spaces in y
a parameters of the ESG mapping centered at (plat,plon)
k parameters of the ESG mapping centered at (plat,plon)
plat latitude of the projection center of the mapping (radians)
plon longitude of the projection center of the mapping (radians)
pazi azimuth of orientation of mapping at its center
delx central x-spacing of the grid (in radians)
dely central y-spacing of the grid (in radians)
xc Earth-centered unit cartesian 3-vectors at each grid point
xcd Jacobian matrices, d(xc)/d(xm), at each grid point
garea rectangular array of grid-cell areas (steradians)
ff failure flag
Author:
R. J. Purser
Definition at line 1540 of file pesg.f90.
References pietc::u0, and pietc::u1.
subroutine, public pesg::hgrid_ak_rr (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glat, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glon, real(dp), dimension(lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, logical, intent(out) ff)
Use a and k as the parameters of an Extended Schmidt-transformed Gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians). Assume the radius of the earth is unity, and using the central mapping point as the coordinate origin, set up the grid with central x-spacing delx and y-spacing dely. The grid index location of the left-lower corner of the domain is (lx,ly) (typically both NEGATIVE). The numbers of the grid spaces in x and y directions are nx and ny. (Note that, for a centered rectangular grid lx and ly are negative and, in magnitude, half the values of nx and ny respectively.) Return the latitude and longitude, in radians again, of the grid points thus defined in the arrays, glat and glon, and return a rectangular array, garea, of dimensions nx-1 by ny-1, that contains the areas of each of the grid cells
If all goes well, return a lowered failure flag, ff=.false. . But if, for some reason, it is not possible to complete this task, return the raised failure flag, ff=.TRUE. .
Parameters:
lx center-relative grid index in x of left edge of the domain
ly center-relative grid index in y of lower edge of the domain
nx number of grid spaces in x
ny number of grid spaces in y
A parameter of the ESG mapping centered at (plat,plon)
K parameter of the ESG mapping centered at (plat,plon)
plat latitude of projection center of mapping (radians)
plon longitude of projection center of mapping (radians)
pazi azimuth of orientation of mapping at its center
delx central x-spacing of the grid (radians)
dely central y-spacing of the grid (radians)
glat grid points' latitudes
glon grid points' longitudes
garea array of grid-cell areas (steradians)
ff failure flag
Author:
R. J. Purser
Definition at line 1220 of file pesg.f90.
References pietc::u0, and pietc::u1.
subroutine pesg::hgrid_ak_rr_c (integer(spi), intent(in) lx, integer(spi), intent(in) ly, integer(spi), intent(in) nx, integer(spi), intent(in) ny, real(dp), intent(in) a, real(dp), intent(in) k, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glat, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) glon, real(dp), dimension(lx:lx+nx-1,ly:ly+ny-1), intent(out) garea, real(dp), dimension(lx:lx+nx-1,ly:ly+ny ), intent(out) dx, real(dp), dimension(lx:lx+nx ,ly:ly+ny-1), intent(out) dy, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) angle_dx, real(dp), dimension(lx:lx+nx ,ly:ly+ny ), intent(out) angle_dy, logical, intent(out) ff)
Use a and k as the parameters of an extended Schmidt-transformed gnomonic (ESG) mapping centered at (plat,plon) and twisted about this center by an azimuth angle of pazi counterclockwise (these angles in radians). Using the central mapping point as the coordinate origin, set up the grid with central x-spacing delx and y-spacing dely in nondimensional units, (i.e., as if the earth had unit radius) and with the location of the left- lower corner of the grid at center-relative grid index pair, (lx,ly) and with the number of the grid spaces in x and y directions given by nx and ny. (Note that, for a centered rectangular grid lx and ly are negative and, in magnitude, half the values of nx and ny respectively.) Return the latitude and longitude, again, in radians, of the grid pts thus defined in the arrays, glat and glon; return a rectangular array, garea, of dimensions nx-1 by ny-1, that contains the areas of each of the grid cells in nondimensional 'steradian' units.
In this version, these grid cell areas are computed by 2D integrating the scalar jacobian of the transformation, using a 4th-order centered scheme. The estimated grid steps, dx and dy, are returned at the grid cell edges, using the same 4th-order scheme to integrate the 1D projected jacobian. The angles, relative to local east and north, are returned respectively as angle_dx and angle_dy at grid cell corners, in radians counterclockwise.
if all goes well, return a .FALSE. failure flag, ff. If, for some reason, it is not possible to complete this task, return the failure flag as .TRUE.
Parameters:
lx center-relative x grid index for left edge of the domain
ly center-relative y grid index for lower edge of the domain
nx numbers of the grid spaces in x
ny numbers of the grid spaces in y
a Extended Schmidt Gnomonic parameter
k Extended Schmidt Gnomonic parameter
plat latitude of the projection center of the mapping (radians)
plon longitude of the projection center of the mapping (radians)
pazi azimuth of the orientation of the mapping at its center
delx central x-spacing of the grid (radians)
dely central y-spacing of the grid (radians)
glat grid points' latitudes (radians)
glon grid points' longitudes (radians)
garea array of grid-cell areas (steradians)
dx grid steps in x at grid cell edges (radians)
dy grid steps in y at grid cell edges (radians)
angle_dx x angles relative to local east (radians)
angle_dy y angles relative to local north (radians)
ff failure flag
Author:
R. J. Purser
Definition at line 1337 of file pesg.f90.
References pietc::u0, and pietc::u1.
Referenced by hgrid_ak_c(), and hgrid_ak_dd_c().
subroutine, public pesg::xctoxm_ak (real(dp), intent(in) a, real(dp), intent(in) k, real(dp), dimension(3), intent(in) xc, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff)
Inverse mapping of xmtoxc_ak. That is, go from given cartesian unit 3-vector, xc, to map coordinate 2-vector xm (or return a raised failure flag, FF, if the attempt fails).
Parameters:
a ESG mapping parameter for line spacing profile
k ESG mapping parameter for Gauss curvature in Schmidt mapping
xc Earth-centered cartesian unit 3-vector
xm 2-vector map coordinate
ff Failure flag
Author:
R. J. Purser
Definition at line 465 of file pesg.f90.
References pietc::f.
subroutine pesg::xctoxs (real(dp), dimension(3), intent(in) xc, real(dp), dimension(2), intent(out) xs) [private]
Inverse of xstoxc. I.e., cartesians to stereographic.
Parameters:
xc Earth-centered cartesian unit 3-vector
xs Stereographic map coordinates
Author:
R. J. Purser
Definition at line 68 of file pesg.f90.
References pietc::u1.
subroutine pesg::xmtog_ak_dd_g (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(2), intent(in) xm, real(dp), intent(out) dlat, real(dp), intent(out) dlon, logical, intent(out) ff)
Like xmtog_ak_rr_g, except lat, lon, azimuth, are expressed in degrees.
Parameters:
a parameters of an ESG mapping
k parameters of an ESG mapping
pdlat degrees latitude of projection center of the mapping
pdlon degrees longitude of projection center of the mapping
pdazi Azimuth of the mapping orientation about its center
delx central x-spacing of the grid in radians
dely central y-spacing of the grid in radians
xm map coordinates, in grid units, of a point to be mapped
dlat degrees latitude of the point
dlon degrees longitude of the point
ff failure flag
Author:
R. J. Purser
Definition at line 2117 of file pesg.f90.
References pietc::dtor, pietc::rtod, and xmtog_ak_rr_m().
subroutine pesg::xmtog_ak_dd_m (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) pdlat, real(dp), intent(in) pdlon, real(dp), intent(in) pdazi, real(dp), dimension(2), intent(in) xm, real(dp), intent(out) dlat, real(dp), intent(out) dlon, logical, intent(out) ff) [private]
Like xmtog_ak_rr_m, except lat, lon, azimuth, are expressed in degrees.
Parameters:
a parameters of the ESG mapping
k parameters of the ESG mapping
pdlat degrees latitude of the projection center of the mapping
pdlon degrees longitude of the projection center of the mapping
pdazi Azimuth of the orientation of the mapping at its center
xm map space 2-vector coordinates of a point
dlat degrees latitude of the point
dlon degrees longitude of the point
ff failure flag
Author:
R. J. Purser
Definition at line 2086 of file pesg.f90.
References pietc::dtor, pietc::rtod, and xmtog_ak_rr_m().
subroutine pesg::xmtog_ak_rr_g (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), intent(in) delx, real(dp), intent(in) dely, real(dp), dimension(2), intent(in) xm, real(dp), intent(out) lat, real(dp), intent(out) lon, logical, intent(out) ff)
For an ESG map with parameters, (A,K), and geographical orientation, given by plon,plat,pazi (radians), and given a point in grid-space units as the 2-vector, xm, return the geographical coordinates, lat, lon, (radians) of this point. If instead the transformation is invalid for any reason, then return the raised failure flag, FF=.true.
Parameters:
a parameters of the ESG mapping
k parameters of the ESG mapping
plat radians latitude of the projection center of the mapping
plon radians longitude of the projection center of the mapping
pazi Azimuth of the orientation of the mapping at its center
delx central x-spacing of the grid in radians
dely central y-spacing grid point in radians
xm grid-space 2-vector coordinates of a point to be mapped
lat radians latitude of the point
lon radians longitude of the point
ff failure flag
Author:
R. J. Purser
Definition at line 2062 of file pesg.f90.
References xmtog_ak_rr_m().
subroutine pesg::xmtog_ak_rr_m (real(dp), intent(in) A, real(dp), intent(in) K, real(dp), intent(in) plat, real(dp), intent(in) plon, real(dp), intent(in) pazi, real(dp), dimension(2), intent(in) xm, real(dp), intent(out) lat, real(dp), intent(out) lon, logical, intent(out) ff) [private]
Given the ESG map specified by parameters (A,K) and geographical center and orientation, plat,plon,pazi (radians), and a position, in map-space coordinates given by the 2-vector, xm, return the geographical coordinates, lat and lon (radians). If the transformation is invalid for any reason, return instead with a raised failure flag, FF= .true.
Parameters:
a parameter of an ESG mapping
k parameter of an ESG mapping
plat radians latitude of the projection center of the mapping
plon radians longitude of the projection center of the mapping
pazi Azimuth of orientation of the mapping at its center
xm center-relative 2-vector map space coordinates of a point
lat radians latitude of the point
lon radians longitude of the point
ff failure flag
Author:
R. J. Purser
Definition at line 2014 of file pesg.f90.
References pietc::u0, and pietc::u1.
Referenced by xmtog_ak_dd_g(), xmtog_ak_dd_m(), and xmtog_ak_rr_g().
subroutine, public pesg::xmtoxc_ak (real(dp), intent(in) a, real(dp), intent(in) k, real(dp), dimension(2), intent(in) xm, real(dp), dimension(3), intent(out) xc, real(dp), dimension(3,2), intent(out) xcd, logical, intent(out) ff)
Assuming the A-K parameterization of the Extended Schmidt-transformed Gnomonic (ESG) mapping, and given a map-space 2-vector, xm, find the corresponding cartesian unit 3-vector and its derivative wrt xm, jacobian matrix, xcd. If for any reason the mapping cannot be done, return a raised failure flag, FF.
Parameters:
a ESG mapping parameter for line spacing profile
k ESG mapping parameter for Gauss curvature in Schmidt mapping
xm map-space 2-vector
xc Earth-centered cartesian unit 3-vector
xcd Jacobian matrix, d(xc)/d(xm)
ff Failure flag
Author:
R. J. Purser
Definition at line 439 of file pesg.f90.
subroutine pesg::xmtoxc_vak (real(dp), dimension(2), intent(in) ak, real(dp), dimension(2), intent(in) xm, real(dp), dimension(3), intent(out) xc, real(dp), dimension(3,2), intent(out) xcd, logical, intent(out) ff)
Assuming the vector AK parameterization of the Extended Schmidt-transformed Gnomonic (ESG) mapping with parameter vector, and given a map-space 2-vector, xm, find the corresponding cartesian unit 3-vector and its derivative wrt xm, the Jacobian matrix, xcd. If for any reason the mapping cannot be done, return a raised failure flag,z FF.
Parameters:
ak 2-vector parameterization of the ESG mapping
xm 2-vector of map plane coordinates
xc Earth-centered cartesian unit 3-vector
xcd Jacobian, d(xc)/d(xm)
ff Failure flag
Author:
R. J. Purser
Definition at line 381 of file pesg.f90.
subroutine pesg::xmtoxc_vak1 (real(dp), dimension(2), intent(in) ak, real(dp), dimension(2), intent(in) xm, real(dp), dimension(3), intent(out) xc, real(dp), dimension(3,2), intent(out) xcd, real(dp), dimension(3,2), intent(out) xc1, real(dp), dimension(3,2,2), intent(out) xcd1, logical, intent(out) ff) [private]
Like xmtoxc_vak, _ak, but also return derivatives wrt ak.
Parameters:
ak 2-vector parameterization of the ESG mapping
xm 2-vector of map plane coordinates
xc Earth-centered cartesian unit 3-vector
xcd Jacobian of xc wrt xm, d(xc)/d(xm)
xc1 Partial derivatives wrt ak of xc, d(xc)/d(ak)
xcd1 Second derivative wrt xm and ak of xc, d^2(xc)/(d(xm)d(ak))
ff Failure flag
Author:
R. J. Purser
Definition at line 400 of file pesg.f90.
References xmtoxt1(), and xttoxs1().
subroutine pesg::xmtoxt (real(dp), intent(in) a, real(dp), dimension(2), intent(in) xm, real(dp), dimension(2), intent(out) xt, real(dp), dimension(2,2), intent(out) xtd, logical, intent(out) ff) [private]
Like zmtozt, but for 2-vector xm and xt, and 2*2 diagonal Jacobian xtd.
Parameters:
a Mapping parameter controlling grid line spacing profile
xm Vector value of map coordinates
xt Vector value of gnomonic plane coordinates
xtd 2*2 diagonal Jacobian, d(xt)/d(xm)
ff Failure flag
Author:
R. J. Purser
Definition at line 254 of file pesg.f90.
References pietc::u0.
subroutine pesg::xmtoxt1 (real(dp), intent(in) a, real(dp), dimension(2), intent(in) xm, real(dp), dimension(2), intent(out) xt, real(dp), dimension(2,2), intent(out) xtd, real(dp), dimension(2), intent(out) xt1, real(dp), dimension(2,2), intent(out) xtd1, logical, intent(out) ff) [private]
Like zmtozt1, but for 2-vector xm and xt, and 2*2 diagonal Jacobian xtd Also, the derivatives, wrt a, of these quantities.
Parameters:
a Mapping parameter controlling grid line spacing profile
xm Vector value of map plane coordinates
xt Vector value of gnomonic plane coordinates
xtd 2*2 diagonal Jacobian, d(xt)/d(xm)
xt1 Derivative wrt a of xt, d(xt)/da
xtd1 Derivative wrt a of Jacobian xtd, d^2(xt)/(d(xm)da)
ff Failure flag
Author:
R. J. Purser
Definition at line 276 of file pesg.f90.
References pietc::u0, and zmtozt1().
Referenced by xmtoxc_vak1().
subroutine pesg::xstoxc (real(dp), dimension(2), intent(in) xs, real(dp), dimension(3), intent(out) xc, real(dp), dimension(3,2), intent(out) xcd) [private]
Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar. xcd=d(xc)/d(xs) is the jacobian matrix, encoding distortion and metric.
Parameters:
xs Stereographic map coordinates
xc Cartesian earth-centered 3-vector
xcd Value of jacobian matrix, encoding distortion and metric
Author:
R. J. Purser
Definition at line 85 of file pesg.f90.
References pietc::u1, and pietc::u2.
subroutine pesg::xstoxc1 (real(dp), dimension(2), intent(in) xs, real(dp), dimension(3), intent(out) xc, real(dp), dimension(3,2), intent(out) xcd, real(dp), dimension(3,2,2), intent(out) xcdd)
Standard transformation from polar stereographic map coordinates, xs, to cartesian, xc, assuming the projection axis is polar. xcd=d(xc)/d(xs) is the jacobian matrix, encoding distortion and metric. xcdd is the further derivative, wrt xs, of xcd.
Parameters:
xs Stereographic map coordinates
xc Cartesian earth-centered 3-vector
xcd Jacobian matrix, encoding distortion and metric
xcdd Further derivative, wrt xs, of xcd
Author:
R. J. Purser
Definition at line 107 of file pesg.f90.
References pietc::u0, pietc::u1, and pietc::u2.
subroutine pesg::xstoxt (real(dp), intent(in) k, real(dp), dimension(2), intent(in) xs, real(dp), dimension(2), intent(out) xt, logical, intent(out) ff)
Inverse of xttoxs.
Parameters:
k Gaussian curvature parameter of Schmidt mapping
xs Stereographic plane coordinates
xt Scaled gnomonic plane coordinates
ff Failure flag
Author:
R. J. Purser
Definition at line 139 of file pesg.f90.
References pietc::u1, and pietc::u2.
subroutine pesg::xttoxm (real(dp), intent(in) a, real(dp), dimension(2), intent(in) xt, real(dp), dimension(2), intent(out) xm, logical, intent(out) ff)
Inverse of xmtoxt.
Parameters:
a Mapping parameter controlling grid line spacing profile
xt Gnomonic plane coordinates
xm Map coordinates
ff Failure flag
Author:
R. J. Purser
Definition at line 235 of file pesg.f90.
subroutine pesg::xttoxs (real(dp), intent(in) k, real(dp), dimension(2), intent(in) xt, real(dp), dimension(2), intent(out) xs, real(dp), dimension(2,2), intent(out) xsd, logical, intent(out) ff) [private]
Scaled gnomonic plane xt to standard stereographic plane xs.
Parameters:
k Gaussian curvature parameter of Schmidt mapping
xt Scaled gnomonic plane
xs Standard stereographic plane
xsd Jacobian matrix, d(xs)/d(xt).
ff Failure flag
Author:
R. J. Purser
Definition at line 159 of file pesg.f90.
References pietc::u0, and pietc::u1.
subroutine pesg::xttoxs1 (real(dp), intent(in) k, real(dp), dimension(2), intent(in) xt, real(dp), dimension(2), intent(out) xs, real(dp), dimension(2,2), intent(out) xsd, real(dp), dimension(2,2,2), intent(out) xsdd, real(dp), dimension(2), intent(out) xs1, real(dp), dimension(2,2), intent(out) xsd1, logical, intent(out) ff)
Like xttoxs, but also, return the derivatives, wrt K, of xs and xsd.
Parameters:
k Gaussian curvature parameter of the Schmidt mapping
xt Scaled gnomonic plane
xs Standard stereographic plane
xsd Jacobian matrix, d(xs)/d(xt)
xsdd Second partial derivatives, d^2(xs)/(d(xt)d(xt))
xs1 Derivative of xs wrt mapping parameter, d(xs)/dk
xsd1 Derivative of Jacobian wrt k: d^2(xs)/(d(xt)dk)
ff Failure flag
Author:
R. J. Purser
Definition at line 193 of file pesg.f90.
References pietc::o2, pietc::u0, pietc::u1, and pietc::u2.
Referenced by xmtoxc_vak1().
subroutine pesg::zmtozt (real(dp), intent(in) a, real(dp), intent(in) zm, real(dp), intent(out) zt, real(dp), intent(out) ztd, logical, intent(out) ff) [private]
Evaluate the function, zt = tan(sqrt(A)*z)/sqrt(A), and its derivative, ztd, for positive and negative A and for the limiting case, A --> 0.
Parameters:
a Mapping parameter controlling grid line spacing profile
zm Scalar value of single map plane coordinate
zt Scalar value of single gnomonic plane coordinate
ztd Derivative of gnomonic coordinate, d(zt)/d(zm)
ff Failure flag
Author:
R. J. Purser
Definition at line 323 of file pesg.f90.
References pietc::f, pietc::pih, pietc::u0, and pietc::u1.
subroutine pesg::zmtozt1 (real(dp), intent(in) a, real(dp), intent(in) zm, real(dp), intent(out) zt, real(dp), intent(out) ztd, real(dp), intent(out) zt1, real(dp), intent(out) ztd1, logical, intent(out) ff) [private]
Like zmtozt, but also, get the derivative with respect to a, zt1 of zt, and ztd1 of ztd.
Parameters:
a Mapping parameter controlling grid line spacing profile
zm Single map plane coordinate
zt Single gnomonic plane coordinate
ztd Derivative wrt zm of zt, d(zt)/d(zm)
zt1 Derivative wrt a of zt, d(zt)/da
ztd1 Derivative wrt a of ztd, d^2(zt)/(d(zm)da)
ff Failure flag
Author:
R. J. Purser
Definition at line 348 of file pesg.f90.
References pietc::o3.
Referenced by xmtoxt1().
subroutine pesg::zttozm (real(dp), intent(in) a, real(dp), intent(in) zt, real(dp), intent(out) zm, logical, intent(out) ff) [private]
Inverse of zmtozt.
Parameters:
a Mapping parameter controlling grid line spacing profile
zt Scalar value of single gnomonic plane coordinate
zm Scalar value of single map plane coordinate
ff Failure flag
Author:
R. J. Purser
Definition at line 299 of file pesg.f90.
References pietc::f, pietc::u0, and pietc::u1.
Author
Generated automatically by Doxygen for grid_tools from the source code.