.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pfun.f90" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pfun.f90 \- Routine evaluating useful functions not always available in Fortran\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBpfun::ahav\fP"
.br
.ti -1c
.RI "interface \fBpfun::ahavh\fP"
.br
.ti -1c
.RI "interface \fBpfun::atanh\fP"
.br
.ti -1c
.RI "interface \fBpfun::gd\fP"
.br
.ti -1c
.RI "interface \fBpfun::gdi\fP"
.br
.ti -1c
.RI "interface \fBpfun::hav\fP"
.br
.ti -1c
.RI "interface \fBpfun::havh\fP"
.br
.ti -1c
.RI "interface \fBpfun::sech\fP"
.br
.ti -1c
.RI "interface \fBpfun::sechs\fP"
.br
.ti -1c
.RI "interface \fBpfun::sinhox\fP"
.br
.ti -1c
.RI "interface \fBpfun::sinhoxm\fP"
.br
.ti -1c
.RI "interface \fBpfun::sinox\fP"
.br
.ti -1c
.RI "interface \fBpfun::sinoxm\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBpfun\fP"
.br
.RI "This module is for evaluating several useful real-valued functions that are not always available in Fortran compilers\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "real(dp) function \fBpfun::ahav_d\fP (a)"
.br
.RI "Arc-haversine function for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBpfun::ahav_s\fP (a)"
.br
.RI "Arc-haversine function for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBpfun::ahavh_d\fP (a)"
.br
.RI "Hyperbolic arc-haversine for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBpfun::ahavh_s\fP (a)"
.br
.RI "Hyperbolic arc-haversine for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBpfun::atanh_d\fP (t)"
.br
.RI "Hyperbolic arc-tangent for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBpfun::atanh_s\fP (t)"
.br
.RI "Hyperbolic arc-tangent for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBpfun::gd_d\fP (x)"
.br
.RI "Gudermannian function (related to Mercator map projections) "
.ti -1c
.RI "real(sp) function \fBpfun::gd_s\fP (x)"
.br
.RI "Gudermannian function (related to Mercator map projections) "
.ti -1c
.RI "real(dp) function \fBpfun::gdi_d\fP (y)"
.br
.RI "Inverse Gudermannian function for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBpfun::gdi_s\fP (y)"
.br
.RI "Inverse Gudermannian function for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBpfun::hav_d\fP (t)"
.br
.RI "Haversine function for double precision real (for geometry on the sphere)\&. "
.ti -1c
.RI "real(sp) function \fBpfun::hav_s\fP (t)"
.br
.RI "Haversine function for single precision real (for geometry on the sphere)\&. "
.ti -1c
.RI "real(dp) function \fBpfun::havh_d\fP (t)"
.br
.RI "Hyperbolic-haversine for double precision real (for pseudosphere geometry)\&. "
.ti -1c
.RI "real(sp) function \fBpfun::havh_s\fP (t)"
.br
.RI "Hyperbolic-haversine for single precision real (for pseudosphere geometry)\&. "
.ti -1c
.RI "real(dp) function \fBpfun::sech_d\fP (x)"
.br
.RI "Hyperbolic secant for double precision real\&. "
.ti -1c
.RI "real(sp) function \fBpfun::sech_s\fP (x)"
.br
.RI "Hyperbolic secant for single precision real\&. "
.ti -1c
.RI "real(dp) function \fBpfun::sechs_d\fP (x)"
.br
.RI "Hyperbolic secant-squared function (logistic distribution)\&. "
.ti -1c
.RI "real(sp) function \fBpfun::sechs_s\fP (x)"
.br
.RI "Hyperbolic secant-squared function (logistic distribution)\&. "
.ti -1c
.RI "real(dp) function \fBpfun::sinhox_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sinh(x)/x\&. "
.ti -1c
.RI "real(dp) function \fBpfun::sinhoxm_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sinh(x)/x-1\&. "
.ti -1c
.RI "real(dp) function \fBpfun::sinox_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sin(x)/x\&. "
.ti -1c
.RI "real(dp) function \fBpfun::sinoxm_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sin(x)/x-1, still accurate near x=0\&. "
.in -1c
.SH "Detailed Description"
.PP 
Routine evaluating useful functions not always available in Fortran\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition in file \fBpfun\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
