.TH "pfun::sinoxm" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pfun::sinoxm
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function \fBsinoxm_d\fP (x)"
.br
.RI "Evaluate the symmetric real function sin(x)/x-1, still accurate near x=0\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file pfun\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function pfun::sinoxm::sinoxm_d (real(dp), intent(in) x)\fC [private]\fP"

.PP
Evaluate the symmetric real function sin(x)/x-1, still accurate near x=0\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP double precision real argument 
.RE
.PP
\fBReturns:\fP
.RS 4
r sin(x)/x-1 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 291 of file pfun\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
