.TH "pmat4::qtospin" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::qtospin
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBqtospin\fP (q, cspin)"
.br
.RI "Go from the unit quaternion to the complex spinor representation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file pmat4\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pmat4::qtospin::qtospin (real(dp), dimension(0:3), intent(in) q, complex(dpc), dimension(2,2), intent(out) cspin)\fC [private]\fP"

.PP
Go from the unit quaternion to the complex spinor representation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIq\fP given unit quaternion representation 
.br
\fIcspin\fP spinor representation 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 1575 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
