.TH "pmat4::cross_product" 3 "Tue Jan 17 2023" "Version 1.9.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmat4::cross_product
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "real(dp) function, dimension(3) \fBcross_product_d\fP (a, b)"
.br
.RI "Return the cross product of two double precision real 3-vectors\&. "
.ti -1c
.RI "real(sp) function, dimension(3) \fBcross_product_s\fP (a, b)"
.br
.RI "Return the cross product of two single precision real 3-vectors\&. "
.ti -1c
.RI "real(dp) function, dimension(4) \fBtriple_cross_product_d\fP (u, v, w)"
.br
.RI "Return the triple_cross_product for 4-vectors\&. "
.ti -1c
.RI "real(sp) function, dimension(4) \fBtriple_cross_product_s\fP (u, v, w)"
.br
.RI "Deliver the triple-cross-product, x, of the three 4-vectors, u, v, w, with the sign convention that ordered, {u,v,w,x} form a right-handed quartet in the generic case (determinant >= 0)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file pmat4\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "real(dp) function, dimension(3) pmat4::cross_product::cross_product_d (real(dp), dimension(3), intent(in) a, real(dp), dimension(3), intent(in) b)\fC [private]\fP"

.PP
Return the cross product of two double precision real 3-vectors\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP real type input 3-vector 
.br
\fIb\fP real type input 3-vector 
.RE
.PP
\fBReturns:\fP
.RS 4
c result, double precision real 3-vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 215 of file pmat4\&.f90\&.
.SS "real(sp) function, dimension(3) pmat4::cross_product::cross_product_s (real(sp), dimension(3), intent(in) a, real(sp), dimension(3), intent(in) b)\fC [private]\fP"

.PP
Return the cross product of two single precision real 3-vectors\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP real type input 3-vector 
.br
\fIb\fP real type input 3-vector 
.RE
.PP
\fBReturns:\fP
.RS 4
c result, single precision real 3-vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 202 of file pmat4\&.f90\&.
.SS "real(dp) function, dimension(4) pmat4::cross_product::triple_cross_product_d (real(dp), dimension(4), intent(in) u, real(dp), dimension(4), intent(in) v, real(dp), dimension(4), intent(in) w)\fC [private]\fP"

.PP
Return the triple_cross_product for 4-vectors\&. 
.PP
\fBParameters:\fP
.RS 4
\fIu\fP real type input 4-vector 
.br
\fIv\fP real type input 4-vector 
.br
\fIw\fP real type input 4-vector 
.RE
.PP
\fBReturns:\fP
.RS 4
x result, triple-cross-product 4-vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 253 of file pmat4\&.f90\&.
.SS "real(sp) function, dimension(4) pmat4::cross_product::triple_cross_product_s (real(sp), dimension(4), intent(in) u, real(sp), dimension(4), intent(in) v, real(sp), dimension(4), intent(in) w)\fC [private]\fP"

.PP
Deliver the triple-cross-product, x, of the three 4-vectors, u, v, w, with the sign convention that ordered, {u,v,w,x} form a right-handed quartet in the generic case (determinant >= 0)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIu\fP real type input 4-vector 
.br
\fIv\fP real type input 4-vector 
.br
\fIw\fP real type input 4-vector 
.RE
.PP
\fBReturns:\fP
.RS 4
x result, triple-cross-product 4-vector 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 232 of file pmat4\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
