utils
NAME
utils - Module that contains general utility routines.
SYNOPSIS
Functions/Subroutines
subroutine fill_regional_halo (data, halo)
This routine extrapolate geolat_c and geolon_c halo points for the regional standalone grid.
subroutine handle_err (status, string)
Prints an error message to standard output, then halts program execution with a bad status.
subroutine read_namelist
Read the program namelist file.
Variables
character(len=512) grid_file = 'atmos_mosaic.nc'
Path/name of the grid mosaic file.
integer grid_type = 0
Grid type.
character(len=128) mask_field = 'slmsk'
NetCDF record name of the land/sea mask.
logical nested = .false.
If true, process a global grid with a nest.
logical regional = .false.
If true, process a stand-alone regional grid.
real res = 48.
The 'CRES' resolution.
real stretch_fac = 1.0
Grid stretching factor.
character(len=128) topo_field = 'orog_filt'
NetCDF record name of the filtered topography (or orography).
character(len=512) topo_file = 'orog'
Path/name of the topography (or orography) file.
logical zero_ocean = .true.
If true, no diffusive flux into water/ocean area (preserve islands).
Detailed Description
Module that contains general utility routines.
Author:
GFDL programmer
Function/Subroutine Documentation
subroutine utils::fill_regional_halo (real, dimension(1-halo:,1-halo:,:), intent(inout) data, integer, intent(in) halo)
This routine extrapolate geolat_c and geolon_c halo points for the regional standalone grid. Halo points are needed for dxc and dyc calculation.
Parameters:
data - field to be extrapolated
halo - number of halo rows/columns
Author:
Ratko Vasic (NCEP/EMC)
Definition at line 71 of file utils.F90.
Referenced by read_grid_file().
subroutine utils::handle_err (integer, intent(in) status, character(len=*), intent(in) string)
Prints an error message to standard output, then halts program execution with a bad status.
Parameters:
status Error status code.
string Error message.
Author:
GFDL Programmer
Definition at line 107 of file utils.F90.
Referenced by read_grid_file(), and read_namelist().
subroutine utils::read_namelist ()
Read the program namelist file. Then, write the namelist variables to standard output.
Author:
GFDL Programmer
Definition at line 37 of file utils.F90.
References grid_file, grid_type, handle_err(), mask_field, nested, regional, res, stretch_fac, topo_field, topo_file, and zero_ocean.
Referenced by filter_topo().
Variable Documentation
character(len=512) utils::grid_file = 'atmos_mosaic.nc'
Path/name of the grid mosaic file.
Definition at line 18 of file utils.F90.
Referenced by read_grid_file(), and read_namelist().
integer utils::grid_type = 0
Grid type. 0 for a gnomonic grid.
Definition at line 25 of file utils.F90.
Referenced by filter_topo(), and read_namelist().
character(len=128) utils::mask_field = 'slmsk'
NetCDF record name of the land/sea mask.
Definition at line 17 of file utils.F90.
Referenced by read_namelist().
logical utils::nested = .false.
If true, process a global grid with a nest.
Definition at line 22 of file utils.F90.
Referenced by filter_topo(), read_grid_file(), and read_namelist().
logical utils::regional = .false.
If true, process a stand-alone regional grid.
Definition at line 23 of file utils.F90.
Referenced by filter_topo(), read_grid_file(), and read_namelist().
real utils::res = 48.
The 'CRES' resolution.
Definition at line 28 of file utils.F90.
Referenced by read_namelist().
real utils::stretch_fac = 1.0
Grid stretching factor.
Definition at line 27 of file utils.F90.
Referenced by filter_topo(), and read_namelist().
character(len=128) utils::topo_field = 'orog_filt'
NetCDF record name of the filtered topography (or orography).
Definition at line 15 of file utils.F90.
Referenced by read_namelist().
character(len=512) utils::topo_file = 'orog'
Path/name of the topography (or orography) file.
Definition at line 14 of file utils.F90.
Referenced by read_namelist().
logical utils::zero_ocean = .true.
If true, no diffusive flux into water/ocean area (preserve islands).
Definition at line 20 of file utils.F90.
Referenced by read_namelist().
Author
Generated automatically by Doxygen for grid_tools from the source code.