model_grid
NAME
model_grid - Sets up the ESMF grid objects for the input data grid and target FV3 grid.
SYNOPSIS
Functions/Subroutines
subroutine, public cleanup_input_target_grid_data
Deallocate all esmf grid objects.
subroutine, public define_input_grid (localpet, npets)
Driver routine to setup the esmf grid object for the input grid.
subroutine define_input_grid_gaussian (npets)
Define grid object for input data on global gaussian grids.
subroutine define_input_grid_grib2 (npets)
Define input grid object for grib2 input data.
subroutine define_input_grid_mosaic (localpet, npets)
Define input grid for tiled data using the 'mosaic', 'grid' and orography files.
subroutine, public define_target_grid (localpet, npets)
Setup the esmf grid object for the target grid.
subroutine gdt_to_gds (igdtnum, igdstmpl, igdtlen, kgds, ni, nj, res)
Convert the GRIB2 grid description template to to the GRIB1 grid description section.
subroutine get_model_latlons (mosaic_file, orog_dir, num_tiles, tile, i_tile, j_tile, ip1_tile, jp1_tile, latitude, latitude_s, latitude_w, longitude, longitude_s, longitude_w)
Read model lat/lons for a single tile from the 'grid' specificaton file.
subroutine get_model_mask_terrain (orog_file, idim, jdim, mask, terrain)
Read the model land mask and terrain for a single tile from the orography file.
Variables
integer, public i_input
i-dimension of input grid (or of each global tile)
integer, public i_target
i dimension of each global tile, or of a nest, target grid.
type(esmf_grid), public input_grid
input grid esmf grid object
character(len=50), public input_grid_type = 'latlon'
map projection of input grid
integer, public ip1_input
i_input plus 1
integer, public ip1_target
ip1_target plus 1
integer, public j_input
j-dimension of input grid (or of each global tile)
integer, public j_target
j dimension of each global tile, or of a nest, target grid.
integer, public jp1_input
j_input plus 1
integer, public jp1_target
jp1_target plus 1
type(esmf_field), public landmask_target_grid
land mask target grid - '1' land; '0' non-land
type(esmf_field), public latitude_input_grid
latitude of grid center, input grid
type(esmf_field), public latitude_s_input_grid
latitude of 'south' edge of grid box, input grid
type(esmf_field), public latitude_s_target_grid
latitude of 'south' edge of grid box, target grid
type(esmf_field), public latitude_target_grid
latitude of grid center, target grid
type(esmf_field), public latitude_w_input_grid
latitude of 'west' edge of grid box, input grid
type(esmf_field), public latitude_w_target_grid
latitude of 'west' edge of grid box, target grid
type(esmf_field), public longitude_input_grid
longitude of grid center, input grid
type(esmf_field), public longitude_s_input_grid
longitude of 'south' edge of grid box, input grid
type(esmf_field), public longitude_s_target_grid
longitude of 'south' edge of grid box, target grid
type(esmf_field), public longitude_target_grid
longitude of grid center, target grid
type(esmf_field), public longitude_w_input_grid
longitude of 'west' edge of grid box, input grid
type(esmf_field), public longitude_w_target_grid
longitude of 'west' edge of grid box, target grid
integer, public lsoil_target = 4
Number of soil layers, target grid.
integer, public num_tiles_input_grid
Number of tiles, input grid.
integer, public num_tiles_target_grid
Number of tiles, target grid.
type(esmf_field), public seamask_target_grid
sea mask target grid - '1' non-land; '0' land
type(esmf_grid), public target_grid
target grid esmf grid object.
type(esmf_field), public terrain_target_grid
terrain height target grid
character(len=5), dimension(:), allocatable, public tiles_target_grid
Tile names of target grid.
Detailed Description
Sets up the ESMF grid objects for the input data grid and target FV3 grid.
Author:
George Gayno NCEP/EMC
Function/Subroutine Documentation
subroutine, public model_grid::cleanup_input_target_grid_data ()
Deallocate all esmf grid objects.
Author:
George Gayno NCEP/EMC
Definition at line 1394 of file model_grid.F90.
References input_grid, landmask_target_grid, latitude_input_grid, latitude_s_input_grid, latitude_s_target_grid, latitude_target_grid, latitude_w_input_grid, latitude_w_target_grid, longitude_input_grid, longitude_s_input_grid, longitude_s_target_grid, longitude_target_grid, longitude_w_input_grid, longitude_w_target_grid, seamask_target_grid, target_grid, and terrain_target_grid.
Referenced by chgres().
subroutine, public model_grid::define_input_grid (integer, intent(in) localpet, integer, intent(in) npets)
Driver routine to setup the esmf grid object for the input grid. If the input source is tiled fv3 restart or history data, the grid is created by reading the mosaic and grid files. If the input source is fv3 global gaussian nemsio, spectral gfs global gaussian nemsio, or spectral gfs global gaussian sigio/sfcio, the grid is setup by computing lat/lons using the sp library.
Parameters:
localpet ESMF local persistent execution thread
npets Number of persistent execution threads
Author:
George Gayno NCEP/EMC
Definition at line 117 of file model_grid.F90.
References define_input_grid_gaussian(), define_input_grid_grib2(), define_input_grid_mosaic(), and program_setup::input_type.
Referenced by chgres().
subroutine model_grid::define_input_grid_gaussian (integer, intent(in) npets)
Define grid object for input data on global gaussian grids. Recognized file formats:
fv3gfs nemsio
spectral gfs nemsio (starting July 19, 2017)
spectral gfs sigio (prior to July 19, 2017)
spectral gfs sfcio (prior to July 19, 2017)
Parameters:
npets Number of persistent execution threads.
Author:
George Gayno NCEP/EMC
Definition at line 148 of file model_grid.F90.
References program_setup::atm_files_input_grid, program_setup::convert_atm, program_setup::convert_sfc, program_setup::data_dir_input_grid, i_input, input_grid, program_setup::input_type, ip1_input, j_input, jp1_input, latitude_input_grid, longitude_input_grid, num_tiles_input_grid, and program_setup::sfc_files_input_grid.
Referenced by define_input_grid().
subroutine model_grid::define_input_grid_grib2 (integer, intent(in) npets)
Define input grid object for grib2 input data.
Parameters:
npets Number of persistent execution threads
Author:
Larissa Reames
Jeff Beck
George Gayno
Definition at line 615 of file model_grid.F90.
References program_setup::data_dir_input_grid, gdt_to_gds(), program_setup::grib2_file_input_grid, i_input, input_grid, input_grid_type, ip1_input, j_input, jp1_input, latitude_input_grid, and longitude_input_grid.
Referenced by define_input_grid().
subroutine model_grid::define_input_grid_mosaic (integer, intent(in) localpet, integer, intent(in) npets)
Define input grid for tiled data using the 'mosaic', 'grid' and orography files.
Parameters:
localpet ESMF local persistent execution thread
npets Total number of persistent execution threads
Author:
George Gayno NCEP/EMC
Definition at line 402 of file model_grid.F90.
References get_model_latlons(), i_input, input_grid, ip1_input, j_input, jp1_input, latitude_input_grid, latitude_s_input_grid, latitude_w_input_grid, longitude_input_grid, longitude_s_input_grid, longitude_w_input_grid, program_setup::mosaic_file_input_grid, num_tiles_input_grid, program_setup::orog_dir_input_grid, and program_setup::orog_files_input_grid.
Referenced by define_input_grid().
subroutine, public model_grid::define_target_grid (integer, intent(in) localpet, integer, intent(in) npets)
Setup the esmf grid object for the target grid.
Parameters:
localpet ESMF local persistent execution thread
npets Number of persistent execution threads
Author:
George Gayno NCEP/EMC
Definition at line 888 of file model_grid.F90.
References get_model_latlons(), get_model_mask_terrain(), i_target, ip1_target, j_target, jp1_target, landmask_target_grid, latitude_s_target_grid, latitude_target_grid, latitude_w_target_grid, longitude_s_target_grid, longitude_target_grid, longitude_w_target_grid, lsoil_target, program_setup::mosaic_file_target_grid, program_setup::nsoill_out, num_tiles_target_grid, program_setup::orog_dir_target_grid, program_setup::orog_files_target_grid, seamask_target_grid, target_grid, terrain_target_grid, and tiles_target_grid.
Referenced by chgres().
subroutine model_grid::gdt_to_gds (integer, intent(in) igdtnum, integer, dimension(igdtlen), intent(in) igdstmpl, integer, intent(in) igdtlen, integer, dimension(200), intent(out) kgds, integer, intent(out) ni, integer, intent(out) nj, real, intent(out) res) [private]
Convert the GRIB2 grid description template to to the GRIB1 grid description section.
Parameters:
igdtnum GRIB2 grid description template number.
igdstmpl Length of grib2 grid description template.
igdtlen Array of GRIB2 grid description template octets.
kgds Array of GRIB1 grid description octets.
ni I-dimension of grid.
nj J-dimension of grid.
res Resolution of grid in km.
Author:
George Gayno NCEP/EMC
Definition at line 1449 of file model_grid.F90.
Referenced by define_input_grid_grib2().
subroutine model_grid::get_model_latlons (character(len=*), intent(in) mosaic_file, character(len=*), intent(in) orog_dir, integer, intent(in) num_tiles, integer, intent(in) tile, integer, intent(in) i_tile, integer, intent(in) j_tile, integer, intent(in) ip1_tile, integer, intent(in) jp1_tile, real(esmf_kind_r8), dimension(i_tile, j_tile), intent(out) latitude, real(esmf_kind_r8), dimension(i_tile, jp1_tile), intent(out) latitude_s, real(esmf_kind_r8), dimension(ip1_tile, j_tile), intent(out) latitude_w, real(esmf_kind_r8), dimension(i_tile, j_tile), intent(out) longitude, real(esmf_kind_r8), dimension(i_tile, jp1_tile), intent(out) longitude_s, real(esmf_kind_r8), dimension(ip1_tile, j_tile), intent(out) longitude_w)
Read model lat/lons for a single tile from the 'grid' specificaton file.
Parameters:
mosaic_file The mosaic file associated with the 'grid' files.
orog_dir Directory containing the 'grid' and orography files.
num_tiles Total number of tiles
tile Tile number to be read
i_tile 'i' dimension of the tile
j_tile 'j' dimension of the tile
ip1_tile 'i' dimension of the tile plus 1
jp1_tile 'j' dimension of the tile plus 1
latitude grid box center latitude
latitude_s latitude of 'south' edge of grid box
latitude_w latitude of 'west' edge of grid box
longitude grid box center longitude
longitude_s longitude of 'south' edge of grid box
longitude_w longitude of 'west' edge of grid box
Author:
George Gayno NCEP/EMC
Definition at line 1179 of file model_grid.F90.
Referenced by define_input_grid_mosaic(), and define_target_grid().
subroutine model_grid::get_model_mask_terrain (character(len=*), intent(in) orog_file, integer, intent(in) idim, integer, intent(in) jdim, integer(esmf_kind_i8), dimension(idim,jdim), intent(out) mask, real(esmf_kind_i8), dimension(idim,jdim), intent(out) terrain)
Read the model land mask and terrain for a single tile from the orography file.
Parameters:
orog_file Path/name of orography file
idim 'i' dimension of tile
jdim 'j' dimension of tile
mask land mask of tile
terrain terrain height of tile
Author:
George Gayno NCEP/EMC
Definition at line 1327 of file model_grid.F90.
Referenced by define_target_grid().
Variable Documentation
integer, public model_grid::i_input
i-dimension of input grid (or of each global tile)
Definition at line 27 of file model_grid.F90.
Referenced by surface::adjust_soil_levels(), atm_input_data::calcalpha_rotlatlon(), define_input_grid_gaussian(), define_input_grid_grib2(), define_input_grid_mosaic(), atm_input_data::gridrot(), sfc_input_data::read_grib_soil(), atm_input_data::read_input_atm_gaussian_nemsio_file(), atm_input_data::read_input_atm_gaussian_netcdf_file(), atm_input_data::read_input_atm_gfs_gaussian_nemsio_file(), atm_input_data::read_input_atm_gfs_sigio_file(), atm_input_data::read_input_atm_grib2_file(), atm_input_data::read_input_atm_restart_file(), atm_input_data::read_input_atm_tiled_history_file(), nst_input_data::read_input_nst_nemsio_file(), nst_input_data::read_input_nst_netcdf_file(), sfc_input_data::read_input_sfc_gaussian_nemsio_file(), sfc_input_data::read_input_sfc_gfs_gaussian_nemsio_file(), sfc_input_data::read_input_sfc_gfs_sfcio_file(), sfc_input_data::read_input_sfc_netcdf_file(), sfc_input_data::read_input_sfc_restart_file(), atm_input_data::read_winds(), and grib2_util::rh2spfh_gfs().
integer, public model_grid::i_target
i dimension of each global tile, or of a nest, target grid.
Definition at line 37 of file model_grid.F90.
Referenced by define_target_grid(), static_data::get_static_fields(), surface::interp(), surface::regrid_many(), surface::search_many(), write_data::write_fv3_atm_bndy_data_netcdf(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_grid), public model_grid::input_grid
input grid esmf grid object
Definition at line 52 of file model_grid.F90.
Referenced by surface::adjust_soil_levels(), cleanup_input_target_grid_data(), define_input_grid_gaussian(), define_input_grid_grib2(), define_input_grid_mosaic(), atm_input_data::init_atm_esmf_fields(), sfc_input_data::init_sfc_esmf_fields(), surface::interp(), atm_input_data::read_input_atm_gaussian_nemsio_file(), atm_input_data::read_input_atm_gaussian_netcdf_file(), atm_input_data::read_input_atm_restart_file(), atm_input_data::read_input_atm_tiled_history_file(), and nst_input_data::read_input_nst_data().
character(len=50), public model_grid::input_grid_type = 'latlon'
map projection of input grid
Definition at line 21 of file model_grid.F90.
Referenced by define_input_grid_grib2(), and sfc_input_data::read_input_sfc_grib2_file().
integer, public model_grid::ip1_input
i_input plus 1
Definition at line 33 of file model_grid.F90.
Referenced by define_input_grid_gaussian(), define_input_grid_grib2(), and define_input_grid_mosaic().
integer, public model_grid::ip1_target
ip1_target plus 1
Definition at line 43 of file model_grid.F90.
Referenced by define_target_grid(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
integer, public model_grid::j_input
j-dimension of input grid (or of each global tile)
Definition at line 30 of file model_grid.F90.
Referenced by surface::adjust_soil_levels(), atm_input_data::calcalpha_rotlatlon(), define_input_grid_gaussian(), define_input_grid_grib2(), define_input_grid_mosaic(), atm_input_data::gridrot(), sfc_input_data::read_grib_soil(), atm_input_data::read_input_atm_gaussian_nemsio_file(), atm_input_data::read_input_atm_gaussian_netcdf_file(), atm_input_data::read_input_atm_gfs_gaussian_nemsio_file(), atm_input_data::read_input_atm_gfs_sigio_file(), atm_input_data::read_input_atm_grib2_file(), atm_input_data::read_input_atm_restart_file(), atm_input_data::read_input_atm_tiled_history_file(), nst_input_data::read_input_nst_nemsio_file(), nst_input_data::read_input_nst_netcdf_file(), sfc_input_data::read_input_sfc_gaussian_nemsio_file(), sfc_input_data::read_input_sfc_gfs_gaussian_nemsio_file(), sfc_input_data::read_input_sfc_gfs_sfcio_file(), sfc_input_data::read_input_sfc_netcdf_file(), sfc_input_data::read_input_sfc_restart_file(), atm_input_data::read_winds(), and grib2_util::rh2spfh_gfs().
integer, public model_grid::j_target
j dimension of each global tile, or of a nest, target grid.
Definition at line 40 of file model_grid.F90.
Referenced by define_target_grid(), static_data::get_static_fields(), surface::interp(), surface::regrid_many(), surface::search_many(), write_data::write_fv3_atm_bndy_data_netcdf(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_sfc_data_netcdf().
integer, public model_grid::jp1_input
j_input plus 1
Definition at line 35 of file model_grid.F90.
Referenced by define_input_grid_gaussian(), define_input_grid_grib2(), define_input_grid_mosaic(), and atm_input_data::read_winds().
integer, public model_grid::jp1_target
jp1_target plus 1
Definition at line 45 of file model_grid.F90.
Referenced by define_target_grid(), write_data::write_fv3_atm_bndy_data_netcdf(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public model_grid::landmask_target_grid
land mask target grid - '1' land; '0' non-land
Definition at line 74 of file model_grid.F90.
Referenced by surface::adjust_soilt_for_terrain(), surface::calc_liq_soil_moisture(), cleanup_input_target_grid_data(), define_target_grid(), surface::interp(), surface::nst_land_fill(), surface::qc_check(), surface::rescale_soil_moisture(), surface::roughness(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public model_grid::latitude_input_grid
latitude of grid center, input grid
Definition at line 57 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), atm_input_data::convert_winds_to_xyz(), define_input_grid_gaussian(), define_input_grid_grib2(), define_input_grid_mosaic(), and atm_input_data::read_winds().
type(esmf_field), public model_grid::latitude_s_input_grid
latitude of 'south' edge of grid box, input grid
Definition at line 61 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), and define_input_grid_mosaic().
type(esmf_field), public model_grid::latitude_s_target_grid
latitude of 'south' edge of grid box, target grid
Definition at line 79 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), atmosphere::convert_winds_to_uv(), define_target_grid(), atmosphere::VINTG_WAM(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public model_grid::latitude_target_grid
latitude of grid center, target grid
Definition at line 77 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), define_target_grid(), surface::interp(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public model_grid::latitude_w_input_grid
latitude of 'west' edge of grid box, input grid
Definition at line 67 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), and define_input_grid_mosaic().
type(esmf_field), public model_grid::latitude_w_target_grid
latitude of 'west' edge of grid box, target grid
Definition at line 82 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), atmosphere::convert_winds_to_uv(), define_target_grid(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public model_grid::longitude_input_grid
longitude of grid center, input grid
Definition at line 59 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), atm_input_data::convert_winds_to_xyz(), define_input_grid_gaussian(), define_input_grid_grib2(), define_input_grid_mosaic(), and atm_input_data::read_winds().
type(esmf_field), public model_grid::longitude_s_input_grid
longitude of 'south' edge of grid box, input grid
Definition at line 64 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), and define_input_grid_mosaic().
type(esmf_field), public model_grid::longitude_s_target_grid
longitude of 'south' edge of grid box, target grid
Definition at line 87 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), atmosphere::convert_winds_to_uv(), define_target_grid(), and write_data::write_fv3_atm_data_netcdf().
type(esmf_field), public model_grid::longitude_target_grid
longitude of grid center, target grid
Definition at line 85 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), define_target_grid(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public model_grid::longitude_w_input_grid
longitude of 'west' edge of grid box, input grid
Definition at line 70 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), and define_input_grid_mosaic().
type(esmf_field), public model_grid::longitude_w_target_grid
longitude of 'west' edge of grid box, target grid
Definition at line 90 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), atmosphere::convert_winds_to_uv(), define_target_grid(), and write_data::write_fv3_atm_data_netcdf().
integer, public model_grid::lsoil_target = 4
Number of soil layers, target grid.
Definition at line 25 of file model_grid.F90.
Referenced by surface::adjust_soil_levels(), surface::create_surface_esmf_fields(), define_target_grid(), surface::interp(), surface::search_many(), and write_data::write_fv3_sfc_data_netcdf().
integer, public model_grid::num_tiles_input_grid
Number of tiles, input grid.
Definition at line 47 of file model_grid.F90.
Referenced by define_input_grid_gaussian(), define_input_grid_mosaic(), atm_input_data::read_input_atm_restart_file(), atm_input_data::read_input_atm_tiled_history_file(), nst_input_data::read_input_nst_netcdf_file(), sfc_input_data::read_input_sfc_netcdf_file(), and sfc_input_data::read_input_sfc_restart_file().
integer, public model_grid::num_tiles_target_grid
Number of tiles, target grid.
Definition at line 49 of file model_grid.F90.
Referenced by define_target_grid(), static_data::get_static_fields(), surface::interp(), write_data::write_fv3_atm_data_netcdf(), and write_data::write_fv3_sfc_data_netcdf().
type(esmf_field), public model_grid::seamask_target_grid
sea mask target grid - '1' non-land; '0' land
Definition at line 93 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), define_target_grid(), and surface::interp().
type(esmf_grid), public model_grid::target_grid
target grid esmf grid object.
Definition at line 54 of file model_grid.F90.
Referenced by cleanup_input_target_grid_data(), atmosphere::create_atm_b4adj_esmf_fields(), atmosphere::create_atm_esmf_fields(), surface::create_nst_esmf_fields(), static_data::create_static_fields(), surface::create_surface_esmf_fields(), define_target_grid(), atmosphere::horiz_interp_thomp_mp_climo(), and surface::interp().
type(esmf_field), public model_grid::terrain_target_grid
terrain height target grid
Definition at line 96 of file model_grid.F90.
Referenced by surface::adjust_soilt_for_terrain(), cleanup_input_target_grid_data(), atmosphere::compute_zh(), define_target_grid(), and atmosphere::newps().
character(len=5), dimension(:), allocatable, public model_grid::tiles_target_grid
Tile names of target grid.
Definition at line 19 of file model_grid.F90.
Referenced by define_target_grid(), and static_data::read_static_file().
Author
Generated automatically by Doxygen for chgres_cube from the source code.