.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/cpld_gridgen.fd/postwgts.F90" 3 "Mon Oct 23 2023" "Version 1.11.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/cpld_gridgen.fd/postwgts.F90 \- Create the ESMF weights for post\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpostwgts::make_postwgts\fP"
.br
.RI "Create the ESMF weights files to remap velocity points from their native stagger location to the center (Ct) location\&. "
.in -1c
.SH "Detailed Description"
.PP 
Create the ESMF weights for post\&. 


.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov
.RE
.PP
This module creates the ESMF weights used to remap from the tripole grid to a rectilinear grid 
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition in file \fBpostwgts\&.F90\fP\&.
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine postwgts::make_postwgts ()"

.PP
Create the ESMF weights files to remap velocity points from their native stagger location to the center (Ct) location\&. Create the ESMF weights file to remap from the Ct location to a rectilinear grid
.PP
\fBAuthor:\fP
.RS 4
Denise.Worthen@noaa.gov 
.RE
.PP

.PP
Definition at line 25 of file postwgts\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
