.TH "vartypedefs::vardefs" 3 "Mon Oct 23 2023" "Version 1.11.0" "cpld_gridgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vartypedefs::vardefs
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "character(len=cm) \fBlong_name\fP"
.br
.RI "A variable's long name\&. "
.ti -1c
.RI "character(len=cm) \fBunit_name\fP"
.br
.RI "A variable's unit\&. "
.ti -1c
.RI "character(len=cm) \fBvar_name\fP"
.br
.RI "A variable name\&. "
.ti -1c
.RI "character(len=2) \fBvar_type\fP"
.br
.RI "A variable's type\&. "
.ti -1c
.RI "character(len=cm) \fBvertices\fP"
.br
.RI "A variable's vertices\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file vartypedefs\&.F90\&.
.SH "Field Documentation"
.PP 
.SS "character(len=cm) vartypedefs::vardefs::long_name"

.PP
A variable's long name\&. 
.PP
Definition at line 18 of file vartypedefs\&.F90\&.
.SS "character(len=cm) vartypedefs::vardefs::unit_name"

.PP
A variable's unit\&. 
.PP
Definition at line 19 of file vartypedefs\&.F90\&.
.SS "character(len=cm) vartypedefs::vardefs::var_name"

.PP
A variable name\&. 
.PP
Definition at line 17 of file vartypedefs\&.F90\&.
.SS "character(len= 2) vartypedefs::vardefs::var_type"

.PP
A variable's type\&. 
.PP
Definition at line 20 of file vartypedefs\&.F90\&.
.SS "character(len=cm) vartypedefs::vardefs::vertices"

.PP
A variable's vertices\&. 
.PP
Definition at line 21 of file vartypedefs\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cpld_gridgen from the source code\&.
