name: Intel oneAPI Linux Build and Test
on: [push, pull_request, workflow_dispatch]

jobs:
  ufs_utils-oneapi:
    runs-on: ubuntu-24.04
    # Dependencies are preinstalled in a container image.
    # For available images, see https://github.com/orgs/NOAA-EMC/packages?tab=packages&q=ufs-utils.
    # See https://github.com/NOAA-EMC/ci-common-build-cache/#using-container-images for further container usage instructions.
    container: ghcr.io/noaa-emc/ci-common-build-cache/ufs-utils-ubuntu-24.04-oneapi-2025.3-intel-oneapi-mpi-2021.17@sha256:93fb43fdd2e74e1a4081b52bbf5a1afd244d4e48219fa2c7f06fdcddb609697e

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
            path: ufs_utils
            submodules: recursive

      - name: "Install Intel compilers & MPI"
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        with: # Match versions to container configuration
          install-classic: false
          oneapi-version: 2025.3
          install-mpi: true
          mpi-version: 2021.17
          mpi-wrapper-setup: oneapi
          compiler-setup: oneapi
          configure-gcc: false

      - name: build
        shell: bash
        run: |
          . /entrypoint.sh
          spack uninstall --force --yes-to-all gcc-runtime intel-oneapi-runtime # prevents CMake config warnings
          ############################
          ## Modify Spack installation, if needed
          ##
          ## For `swap-package` custom Spack command documentation,
          ## see https://github.com/NOAA-EMC/spack-helpers#modify-package-spec-swap-package.
          ## To request a package addition or update , create an issue or PR at
          ## https://github.com/NOAA-EMC/ci-common-build-cache/.
          ##
          ## Configure a different version/build options for a package:
          #spack swap-package foo@1.2.3
          ## Configure an additional package not already in Spack:
          #spack add bar@4.5.6
          ## Concretize environment and run the installation:
          #spack concretize --fresh
          #spack install --only-concrete
          ############################
          cmake -S ufs_utils -B build -DCMAKE_INSTALL_PREFIX=install
          cmake --build build --parallel 4 --verbose
          cmake --install build
          ctest --test-dir build --parallel 4 --output-on-failure
