.TH "pesg::get_qx" 3 "Wed Mar 13 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pesg::get_qx \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBget_qx\fP (j0, v1, v2, v3, v4)"
.br
.RI "\fIFrom a jacobian matrix, j0, get a sufficient set of v\&. \fP"
.ti -1c
.RI "subroutine \fBget_qxd\fP (j0, j0d, v1, v2, v3, v4, v1d, v2d, v3d, v4d)"
.br
.RI "\fIFrom a jacobian matrix, j0, and its derivative, j0d, get a sufficient set of v\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file pesg\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine pesg::get_qx::get_qx (real(dp), dimension(3,2), intent(in)j0, real(dp), intent(out)v1, real(dp), intent(out)v2, real(dp), intent(out)v3, real(dp), intent(out)v4)\fC [private]\fP"

.PP
From a jacobian matrix, j0, get a sufficient set of v\&. \&. diagnostics such that, from averages of these v, we can later compute the collective variance of Q(lam) that they imply for any choice of the 'lambda' parameter, lam\&. Note that v1 and v4 are quadratic diagnostics of EL, while v2 and v3 are linear\&.
.PP
\fBParameters:\fP
.RS 4
\fIj0\fP jacobian matrix 
.br
\fIv1\fP quadratic diagnostics of EL 
.br
\fIv2\fP linear diagnostics of EL 
.br
\fIv3\fP linear diagnostics of EL 
.br
\fIv4\fP quadratic diagnostics of EL 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 511 of file pesg\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine pesg::get_qx::get_qxd (real(dp), dimension(3,2), intent(in)j0, real(dp), dimension(3,2,2), intent(in)j0d, real(dp), intent(out)v1, real(dp), intent(out)v2, real(dp), intent(out)v3, real(dp), intent(out)v4, real(dp), dimension(2), intent(out)v1d, real(dp), dimension(2), intent(out)v2d, real(dp), dimension(2), intent(out)v3d, real(dp), dimension(2), intent(out)v4d)\fC [private]\fP"

.PP
From a jacobian matrix, j0, and its derivative, j0d, get a sufficient set of v\&. \&. diagnostics such that, from average of these diagnostics, we can later compute the collective variance of Q and its derivative\&.
.PP
\fBParameters:\fP
.RS 4
\fIj0\fP jacobian matrix 
.br
\fIj0d\fP derivative of j0 
.br
\fIv1\fP 
.br
\fIv2\fP 
.br
\fIv3\fP 
.br
\fIv4\fP 
.br
\fIv1d\fP 
.br
\fIv2d\fP 
.br
\fIv3d\fP 
.br
\fIv4d\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser 
.RE
.PP

.PP
Definition at line 541 of file pesg\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
