pmat::swpvv
NAME
pmat::swpvv -
SYNOPSIS
Private Member Functions
subroutine cswpvv (d, e)
Swap a pair of complex vectors.
subroutine dswpvv (d, e)
Swap a pair of double precision vectors.
subroutine sswpvv (d, e)
Swap a pair of single precision vectors.
Detailed Description
Definition at line 26 of file pmat.f90.
Member Function/Subroutine Documentation
subroutine pmat::swpvv::cswpvv (complex(dpc), dimension(:), intent(inout)d, complex(dpc), dimension(:), intent(inout)e) [private]
Swap a pair of complex vectors.
Parameters:
d vector
e vector
Author:
R. J. Purser
Definition at line 71 of file pmat.f90.
Referenced by pmat::cinvmtf(), and pmat::cldumf().
subroutine pmat::swpvv::dswpvv (real(dp), dimension(:), intent(inout)d, real(dp), dimension(:), intent(inout)e) [private]
Swap a pair of double precision vectors.
Parameters:
d vector
e vector
Author:
R. J. Purser
Definition at line 60 of file pmat.f90.
Referenced by pmat::dinvmtf(), and pmat::dldumf().
subroutine pmat::swpvv::sswpvv (real(sp), dimension(:), intent(inout)d, real(sp), dimension(:), intent(inout)e) [private]
Swap a pair of single precision vectors.
Parameters:
d vector
e vector
Author:
R. J. Purser
Definition at line 49 of file pmat.f90.
Referenced by pmat::sinvmtf(), and pmat::sldumf().
Author
Generated automatically by Doxygen for grid_tools from the source code.