.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pmat.f90" 3 "Wed Mar 13 2024" "Version 1.13.0" "grid_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/grid_tools.fd/regional_esg_grid.fd/pmat.f90 \- 
.PP
Utility routines for various linear inversions and Cholesky\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBpmat::inv\fP"
.br
.ti -1c
.RI "interface \fBpmat::invl\fP"
.br
.ti -1c
.RI "interface \fBpmat::invu\fP"
.br
.ti -1c
.RI "interface \fBpmat::l1lm\fP"
.br
.ti -1c
.RI "interface \fBpmat::ldlm\fP"
.br
.ti -1c
.RI "interface \fBpmat::ldum\fP"
.br
.ti -1c
.RI "module \fBpmat\fP"
.br
.ti -1c
.RI "interface \fBpmat::swpvv\fP"
.br
.ti -1c
.RI "interface \fBpmat::udlmm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility routines for various linear inversions and Cholesky\&. 


.PP
\fBAuthor:\fP
.RS 4
R\&. J\&. Purser, NOAA/NCEP/EMC, Tsukasa Fujita, JMA\&. 
.RE
.PP

.PP
Definition in file \fBpmat\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for grid_tools from the source code\&.
