pmat5::gtoframe
NAME
pmat5::gtoframe -
SYNOPSIS
Private Member Functions
subroutine gtoframem (plat, plon, orth)
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth.
subroutine gtoframev (plat, plon, xp, yp, zp)
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates.
subroutine sgtoframem (splat, splon, sorth)
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth.
subroutine sgtoframev (splat, splon, sxp, syp, szp)
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates.
Detailed Description
Definition at line 43 of file pmat5.f90.
Member Function/Subroutine Documentation
subroutine pmat5::gtoframe::gtoframem (real(dp), intent(in)plat, real(dp), intent(in)plon, real(dp), dimension(3,3), intent(out)orth) [private]
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth. Double precision version.
Parameters:
plat latitude (degrees) of point.
plon longitude (degrees) of point.
orth orthonormal matrix.
Author:
R. J. Purser
Definition at line 616 of file pmat5.f90.
Referenced by pmat5::sgtoframem().
subroutine pmat5::gtoframe::gtoframev (real(dp), intent(in)plat, real(dp), intent(in)plon, real(dp), dimension(3), intent(out)xp, real(dp), dimension(3), intent(out)yp, real(dp), dimension(3), intent(out)zp) [private]
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates. Double precision version.
Parameters:
plat latitude (degrees) of point.
plon longitude (degrees) of point.
xp unit X-basis vector of cartesian frame.
yp unit Y-basis vector of cartesian frame.
zp unit Z-basis vector of cartesian frame.
Author:
R. J. Purser
Definition at line 661 of file pmat5.f90.
Referenced by pmat5::gtoframem(), and pmat5::sgtoframev().
subroutine pmat5::gtoframe::sgtoframem (real(sp), intent(in)splat, real(sp), intent(in)splon, real(sp), dimension(3,3), intent(out)sorth) [private]
From the degree lat and lon (plat and plon) return the standard orthogonal 3D frame at this location as an orthonormal matrix, orth. Single precision version.
Parameters:
splat latitude (degrees) of point.
splon longitude (degrees) of point.
sorth orthonormal matrix.
Author:
R. J. Purser
Definition at line 599 of file pmat5.f90.
subroutine pmat5::gtoframe::sgtoframev (real(sp), intent(in)splat, real(sp), intent(in)splon, real(sp), dimension(3), intent(out)sxp, real(sp), dimension(3), intent(out)syp, real(sp), dimension(3), intent(out)szp) [private]
Given a geographical point by its degrees lat and lon, plat and plon, return its standard orthogonal cartesian frame, {xp,yp,zp} in earth-centered coordinates. Single precision version.
Parameters:
splat latitude (degrees) of point.
splon longitude (degrees) of point.
sxp xp unit X-basis vector of cartesian frame.
syp yp unit Y-basis vector of cartesian frame.
szp zp unit Z-basis vector of cartesian frame.
Author:
R. J. Purser
Definition at line 636 of file pmat5.f90.
Author
Generated automatically by Doxygen for grid_tools from the source code.