.TH "/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/ocean_merge.fd Directory Reference" 3 "Thu Feb 15 2024" "Version 1.12.0" "ocean_merge" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/ocean_merge.fd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmerge_lake_ocnmsk\&.f90\fP"
.br
.RI "\fIDetermines the water mask by merging the lake mask with the mapped ocean mask from MOM6\&. \fP"
.in -1c
