.TH "/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/set_soilveg_snippet.f90" 3 "Tue Jan 17 2023" "Version 1.9.0" "noah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/sorc/lsm_routines.fd/noah.fd/set_soilveg_snippet.f90 \- Routine to set Noah LSM soil and veg params needed for sflx_snippet\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBset_soilveg_snippet_mod\fP"
.br
.RI "Below was extracted from namelist_soilveg\&.f and set_soilveg\&.f (couldn't get above to compile for doxygen) "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBset_soilveg_snippet_mod::set_soilveg\fP (isot, ivet, maxsmc, bb, satpsi, iret)"
.br
.RI "This subroutine initializes soil and vegetation parameters needed in global_cycle/land_increment\&.f90\&. "
.in -1c
.SH "Detailed Description"
.PP 
Routine to set Noah LSM soil and veg params needed for sflx_snippet\&. 


.PP
\fBAuthor:\fP
.RS 4
Clara Draper 
.RE
.PP

.PP
Definition in file \fBset_soilveg_snippet\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for noah from the source code\&.
